extends Node

var raw_blocks = [
["talk_to_elijah","_none","_none","_pass","","not met_elijah",['es_intro', 'elijah_default'],"",""],
["es_intro","???","sean_neutral","what do you know, fresh meat ;)","display_sean","","","",""],
["","you","","uh, hi","met_elijah","","","",""],
["","","","i'm {player}","met_sean","","","",""],
["","???","","nice to meet ya","","","","",""],
["","","","i'm sean.","","","","",""],
["","","","that lump over there is elijah","","","","",""],
["","elijah",['elijah_neutral', 'sean_neutral'],"elijah puts on an offended expression.","display_elijah_and_sean","","","",""],
["","","","hey","","","","",""],
["","","","that lump over there has feelings, you know.","","","","",""],
["","sean","","maybe you oughta stop acting like a lump, then","","","","",""],
["","_none","","you motion at elijah's notebook.","","","","",""],
["","you","","what are you working on?","","","","",""],
["","elijah","","i'm trying to write a poem.","","","","",""],
["","you","","what's it about?","","","","",""],
["","elijah","","trees","","","","",""],
["","you","","ah, like, what kind?","","","","",""],
["","elijah","","the metaphysical kind","","","","",""],
["","you","","oh","","","","",""],
["","","","dope","","","","",""],
["","sean","","so, {player}...","","","","",""],
["","","","whatcha in for?","","","","",""],
["","you","","in for?","","","","",""],
["","sean","","you know, why are you in purrgatory?","","","","",""],
["","","","everyone here's got a story.","","","","",""],
["","","","for example, elijah is here for being too lumpy","","","","",""],
["","elijah","","what is it with you and lumpiness today??","","","","",""],
["","you","","well [i]i[/i] don't think you're lumpy...","","","","",""],
["","elijah","","thank you.","","","","",""],
["","sean","","anyway, like i was saying...","","","","",""],
["","","","what's your sin?","","","","",""],
["","you","","i don't remember much about my past life, actually.","","","","",""],
["","","","knowing me, it was probably something like...","","","","",""],
["","","","","","","","",[['partying too much', 'es_intro_party'], ['annoying people to death', 'es_intro_annoy'], ['being lazy', 'es_intro_lazy'], ['shoplifting', 'es_intro_shoplifting']]],
["es_intro_party","you","","partying too much.","","","","",""],
["","sean","","hehe","","","","",""],
["","","","you and me both ;)","","","","",""],
["","elijah","","there are worse ways to spend your time.","","","es_intro_cont","",""],
["es_intro_annoy","you","","annoying people to death.","","","","",""],
["","elijah","","oh, sean does that too.","","","","",""],
["","sean","","you're already dead. how could i annoy you to death?","","","","",""],
["","elijah","","you annoy me to, from, and during death.","","","","",""],
["","","","maybe if you keep going you'll annoy me back to life.","","","es_intro_cont","",""],
["es_intro_lazy","you","","being lazy.","","","","",""],
["","elijah","","that's probably why i'm here, too.","","","","",""],
["","","","didn't do nothing while alive.","","","","",""],
["","","","doomed to do nothing in death.","","","","",""],
["","sean","","aww, that's just depressing","","","es_intro_cont","",""],
["es_intro_shoplifting","you","","shoplifting.","","","","",""],
["","elijah","","i'll bet ya that's why sean's here.","","","","",""],
["","sean","","what do you mean?","","","","",""],
["","","","i'll have you know i'm a model citizen. i've never shoplifted even [i]once[/i].","","","","",""],
["","elijah","","you sure? ain't never snatched a candy bar from the corner store? ","","","","",""],
["","","","never snuck a golden watch into your pocket?","","","","",""],
["","","","never swiped a newborn from its cradle?","","","","",""],
["","sean","","...","","","","",""],
["","","","what","","","","",""],
["","elijah","","forget it.","","","es_intro_cont","",""],
["es_intro_cont","you","","how about you, sean? why are you here?","","","","",""],
["","sean","","oh, me?","","","","",""],
["","","","too much sex.","","","","",""],
["","elijah","","sean.","","","","",""],
["","sean","","i was a freaking stud magnet, dude","","","","",""],
["","","","getting booty all day every day","","","","",""],
["","elijah","","...[i]sean.[/i] ","","","","",""],
["","sean","","so god decided to send me down here to repent","","","","",""],
["","","","among a bunch of prudes","","","","",""],
["","","","like elijah.","","","","",""],
["","elijah","","sean, don't scare off the new person.","","","","",""],
["","","","","","","","",[["it's not like i have anywhere else to go", "es_intro_go"], ["*awkward cough*", "es_intro_yikes"]]],
["es_intro_go","you","","it's okay, it's not like i have anywhere else to go.","","","","",""],
["","sean","","see?","","","","",""],
["","","","loosen up, elijah","","","","",""],
["","elijah","","hmph","","","es_intro_lady","",""],
["es_intro_yikes","you","","*cough cough*","","","","",""],
["","sean","","eheh, anyway","","","","",""],
["es_intro_lady","sean","","it's either that or the time i knocked over an old lady while on my bike.","","","","",""],
["","you","","oh no!","","","","",""],
["","sean","","nah, she was fine","","","","",""],
["","","","probably outlived me, the lucky bastard","","","","",""],
["","you","","oh, ok","","","","",""],
["","elijah","","welcome to purrgatory, anyway.","","","","",""],
["","","","for what it's worth.","","","","",""],
["","you","","thanks.","","","null","",""],
["elijah_default","_none","elijah_neutral","_none","","","",['true', 'numa_started_poem and not numa_finished_poem'],[["what's up?", "elijah_wasup"], ["(ask about numa's poem)", "elijah_numa"]]],
["elijah_numa","you","","hey, you're pretty good at poetry, right?","","","","",""],
["","elijah","","eh, i don't know 'bout that.","","","","",""],
["","you","","well, it looks like you have a lot of... experience.","","","","",""],
["","_none","","you motion to the giant mass of crumpled papers.","","","","",""],
["","elijah","","heh. fair enough.","","","","",""],
["","you","","numa is trying to write a poem… maybe you could help?","","","","",""],
["","elijah","","oh?","","","","",""],
["","","","i'm down.","","","","",""],
["","","","what's she need help with?","","","","",""],
["","you","","i don't suppose you know any rhymes for \"orange\"?","","","","",""],
["","elijah","","hmm","","","","",""],
["","","","porridge. lozenge.","","","","",""],
["","you","","hmmmmmm","","","","",""],
["","elijah","","melange, maybe.","","","","",""],
["","you","","what's that?","","","","",""],
["","elijah","","means a mixture of things","","","","",""],
["","","","comes from french.","","","","",""],
["","you","","oh, cool","","","","",""],
["","elijah","","why is she trying to rhyme with orange?","","","","",""],
["","","","","","","","",[["she's writing a love poem for kyungsoon", "elijah_numa_love"], ["i don't know", "elijah_numa_idk"]]],
["elijah_numa_love","you","","she's writing a love poem for kyungsoon","","","","",""],
["","elijah","","oh, really?","","","","",""],
["","","","that's funny","","","","",""],
["","you","","what is?","","","","",""],
["","elijah","","even after death, people still write love poems.","","","","",""],
["","","","didn't realize she had a thing for kyungsoon","","","","",""],
["","you","","yeah, it kind of confuses me too","","","","",""],
["","","","anyway, don't tell her i told you this!","","","","",""],
["","","","it's supposed to be a secret","","","","",""],
["","elijah","","roger.","","","elijah_numa_offer","",""],
["elijah_numa_idk","you","","ah, i don't know","","","","",""],
["elijah_numa_offer","elijah","","might be better if i talked to her directly.","","","","",""],
["","you","","yeah, probably","","","","",""],
["","elijah","","alright, then","","","","",""],
["","","","lead the way.","","","","",""],
["","_none",['elijah_neutral', 'numa_neutral'],"you walk to the garden with elijah.",[['elijah_goto_garden', true], ['elijah_show_numa', true]],"","","",""],
["","numa","","oh, hello…","","","","",""],
["","elijah","","what's up.","","","","",""],
["","you","","i recruited elijah to help you with the poem!","","","","",""],
["","numa","","you -- you did what?!","","","","",""],
["","","","um…","","","","",""],
["","","","did you tell him about…","","","","",""],
["","you","","it's okay, you can trust elijah","","","","",""],
["","","","right?","","","","",""],
["","elijah","","yeah, yeah, of course.","","","","",""],
["","","","i know sharing your poetry can be hard, but i promise i won't judge.","","","","",""],
["","","","i'm just glad someone else in purrgatory is taking an interest in poetry","","","","",""],
["","numa","","…","","","","",""],
["","","","ok because","","","","",""],
["","","","i like, really need help ;;","","","","",""],
["","elijah","","can we hear what you have so far?","","","","",""],
["","numa","","alright, um","","","","",""],
["","","","it's not very good","","","","",""],
["","elijah","","no worries.","","","","",""],
["","numa","","ahem","","","","",""],
["","","","roses are white","","","","",""],
["","","","violets are white","","","","",""],
["","elijah","","heh, strong start.","","","","",""],
["","numa","","to me, you are","","","","",""],
["","","","a shining light.","","","","",""],
["","elijah","","hm…","","","","",""],
["","","","that line could be a little punchier.","","","","",""],
["","","","how about \"blazing\"?","","","","",""],
["","numa","","a blazing light?","","","","",""],
["","","","ooh, i like that!","numa_finished_poem","","","",""],
["","_none","","seems like you should give them time to work.","elijah_working_with_numa_timer","","null","",""],
["elijah_wasup","you","elijah_neutral","wasup?","","","","",""],
["","elijah","","just working on poetry","","","","",""],
["","you","","cool, cool","","","null","",""],
["elijah_helping_numa","elijah",['elijah_neutral', 'numa_neutral'],"so, if you had to compare your mysterious lover to something,","","","","",""],
["","","","what would it be?","","","","",""],
["","numa","","hm…","","","","",""],
["","","","i don't know…","","","","",""],
["","elijah","","don't think about it too hard. just say the first thing that comes to mind.","","","","",""],
["","numa","","uh, ok, a lamppost!","","","","",""],
["","elijah","","a lamppost?","","","","",""],
["","numa","","because she's tall, and.. bright?","","","","",""],
["","","","i guess?","","","","",""],
["","elijah","","alright","","","","",""],
["","","","we can work with this","","","","",""],
["","_none","","seems like they still need time.","","","null","",""]
]