extends Node

var raw_blocks = [
["talk_to_elijah","_none","_none","_pass","",['met_elijah', '_pronouns_she'],['elijah_default', 'es_intro', 'es_intro1'],"","",""],
["es_intro","???","sean_neutral","what do you know, fresh meat :P",[['display_sean', true], ['met_sean', true]],"","es_intro2","","",""],
["es_intro1","???","sean_neutral","what do you know, fresh meat ;)",[['display_sean', true], ['met_sean', true]],"","","","",""],
["es_intro2","you","","uh, hi!","","","","","",""],
["","","","i'm {player}","","","","","",""],
["","???","","nice to meet ya","elijah_and_sean_together","","","","",""],
["","","","i'm sean.","","","","","",""],
["","sean","","that lump over there is elijah","","","","","",""],
["","_none",['elijah_neutral', 'sean_neutral'],"elijah chuckles.",[['display_elijah_and_sean', true], ['met_elijah', true]],"","","","",""],
["","elijah","","hey","","","","","",""],
["","","","that lump over there has feelings, you know.","","","","","",""],
["","sean","","maybe you oughta stop acting like a lump, then :P","","","","","",""],
["","_none","","you motion at elijah's notebook.","","","","","",""],
["","you","","what are you working on?","","","","","",""],
["","elijah","","writing a poem.","","","","","",""],
["","you","","what's it about?","","","","","",""],
["","elijah","","ah, you know. trees. existential dread. that sort of thing.","","","","","",""],
["","you","","cool!","","","","","",""],
["","sean","","so, {player}...","","","","","",""],
["","","","whatcha in for?","","","","","",""],
["","you","","in for?","","","","","",""],
["","sean","","you know, why are you in purrgatory?","","","","","",""],
["","","","everyone here's got a story.","","","","","",""],
["","","","for example, elijah is here for being too lumpy","","","","","",""],
["","elijah","","hey!","","","","","",""],
["","you","","uh, i don't remember much about my past life.","","","","","",""],
["","","","knowing me, it was probably something like...","","","","","",""],
["","","","","","","","",['partying too much', 'annoying people to death', 'being lazy', 'shoplifting'],['es_intro_party', 'es_intro_annoy', 'es_intro_lazy', 'es_intro_shoplifting']],
["es_intro_party","you","","partying too much.","","","","","",""],
["","sean","","hehe","","","","","",""],
["","","","you and me both ;)","","","","","",""],
["","elijah","","there are worse ways to spend your time.","","","es_intro_cont","","",""],
["es_intro_annoy","you","","annoying people to death.","","","","","",""],
["","elijah","","oh, sean does that too.","","","","","",""],
["","sean","","you're already dead. how could i annoy you to death?","","","","","",""],
["","elijah","","you annoy me to, from, and during death.","","","","","",""],
["","","","maybe if you keep going you'll annoy me back to life.","","","es_intro_cont","","",""],
["es_intro_lazy","you","","being lazy.","","","","","",""],
["","elijah","","that's probably why i'm here, too.","","","","","",""],
["","","","didn't do nothing while alive.","","","","","",""],
["","","","doomed to do nothing in death.","","","","","",""],
["","sean","","aww, that's just depressing","","","es_intro_cont","","",""],
["es_intro_shoplifting","you","","shoplifting.","","","","","",""],
["","elijah","","i'll bet ya that's why sean's here.","","","","","",""],
["","sean","","what do you mean?","","","","","",""],
["","","","i'll have you know i'm a model citizen. i've never shoplifted even [i]once[/i].","","","","","",""],
["","elijah","","you sure? ","","","","","",""],
["","","","ain't never snatched a candy bar from the corner store? ","","","","","",""],
["","","","never snuck a golden watch into your pocket?","","","","","",""],
["","","","never swiped a newborn from its cradle?","","","","","",""],
["","sean","","...","","","","","",""],
["","","","nope, not that i remember!","","","es_intro_cont","","",""],
["es_intro_cont","you","","how about you, sean? why are you here?","","","","","",""],
["","sean","","oh, me?","","","","","",""],
["","","","too much sex.","","","","","",""],
["","elijah","","sean.","","","","","",""],
["","sean","","i was a freaking stud magnet, dude","","","","","",""],
["","","","getting booty all day every day","","","","","",""],
["","elijah","","...[i]sean.[/i] ","","","","","",""],
["","sean","","so god decided to send me down here to repent","","","","","",""],
["","","","among a bunch of prudes.","","","","","",""],
["","","","like elijah.","","","","","",""],
["","elijah","","sean, don't scare off the new person.","","","","","",""],
["","","","","","","","",['it\'s not like i have anywhere else to go', '*awkward cough*'],['es_intro_go', 'es_intro_yikes']],
["es_intro_go","you","","it's okay, it's not like i have anywhere else to go.","","","","","",""],
["","sean","","see?","","","","","",""],
["","","","loosen up, elijah","","","","","",""],
["","elijah","","hmph","","","es_intro_lady","","",""],
["es_intro_yikes","you","","*cough cough*","","","","","",""],
["","sean","","eheh, anyway","","","","","",""],
["es_intro_lady","sean","","it's either that or the time i knocked over an old lady while on my bike.","","","","","",""],
["","you","","oh no!","","","","","",""],
["","sean","","nah, she was fine","","","","","",""],
["","","","probably outlived me, the lucky bastard","","","","","",""],
["","you","","oh, ok","","","","","",""],
["","elijah","","welcome to purrgatory, anyway.","","","","","",""],
["","","","for what it's worth.","","","","","",""],
["","you","","thanks!","","","null","","",""],
["elijah_default","_none","elijah_neutral","elijah is scribbling something as you approach.","","","","","",""],
["","","","","","","",['numa_started_poem and not numa_finished_poem',  'tried_meowseum_door and not opened_meowseum_door and not (asked_about_meowseum_door and told_code_to_sean)', 'true', 'opened_meowseum_door', 'true', 'true'],['(about numa\'s poem)', '(about the meowseum door)', 'what\'s up?', 'how\'s the poetry?', 'what does that word on the sign mean?', 'why do you always do that with your hands?'],['elijah_numa', 'elijah_meowseum', 'elijah_wasup', 'elijah_hows_the_poetry', 'elijah_odontophorous', 'elijah_hands']],
["elijah_numa","you","","so, you're pretty good at poetry, right?","","","","","",""],
["","elijah","","eh, i don't know about that.","","","","","",""],
["","you","","well, at least you have a lot of... experience.","","","","","",""],
["","_none","","you motion toward the giant mass of crumpled papers.","","","","","",""],
["","elijah","","pfft","","","","","",""],
["","","","fair enough","","","","","",""],
["","you","","numa is trying to write a poem… maybe you could help?","","","","","",""],
["","elijah","","oh?","","","","","",""],
["","","","i'm down.","","","","","",""],
["","","","what's she need help with?","","","","","",""],
["","you","","i don't suppose you know any rhymes for \"orange\"?","","","","","",""],
["","elijah","","uhhhh, i don't know.","","","","","",""],
["","","","porridge?","","","","","",""],
["","you","","hmmmmmm","","","","","",""],
["","elijah","","melange, maybe?","","","","","",""],
["","you","","what's that?","","","","","",""],
["","elijah","","means a mixture of things","","","","","",""],
["","","","comes from the french.","","","","","",""],
["","you","","oh, cool","","","","","",""],
["","elijah","","why is she trying to rhyme with orange?","","","","","",""],
["","","","","","","","",['she\'s writing a love poem for kyungsoon', 'i don\'t know'],['elijah_numa_love', 'elijah_numa_idk']],
["elijah_numa_love","you","","she's writing a love poem for kyungsoon","","","","","",""],
["","elijah","","oh, word?","","","","","",""],
["","","","that's funny","","","","","",""],
["","you","","what is?","","","","","",""],
["","elijah","","even after death, people still write love poems.","","","","","",""],
["","","","didn't realize she had a thing for kyungsoon","","","","","",""],
["","you","","yeah, it kind of confuses me too","","","","","",""],
["","","","anyway, don't tell her i told you this!","","","","","",""],
["","","","it's supposed to be a secret","","","","","",""],
["","elijah","","roger.","","","elijah_numa_offer","","",""],
["elijah_numa_idk","you","","ah, i don't know","","","","","",""],
["elijah_numa_offer","you","","might be better if you talked to her directly?","","","","","",""],
["","elijah","","sure, sure.","","","","","",""],
["","","","lead the way.","","","","","",""],
["","_none",['elijah_neutral', 'numa_neutral'],"you walk to the garden with elijah.",[['elijah_goto_garden', true], ['elijah_show_numa', true]],"","","","",""],
["","numa","","oh, uh, hey guys!",[['elijah_and_sean_together', false]],"","","","",""],
["","elijah","","what's up?","","","","","",""],
["","you","","i recruited elijah to help you with the poem!","","","","","",""],
["","numa","","you did WHAT?!","","","","","",""],
["","","","um…","","","","","",""],
["","","","did you tell him about…","","","","","",""],
["","you","","it's okay, you can trust elijah","","","","","",""],
["","","","right?","","","","","",""],
["","elijah","","yeah, yeah, of course.","","","","","",""],
["","","","i know sharing your poetry can be hard, but i promise i won't judge.","","","","","",""],
["","","","i'm just glad someone else in purrgatory is taking an interest in poetry","","","","","",""],
["","numa","","…","","","","","",""],
["","","","ok good because","","","","","",""],
["","","","i like, really need help ;;","","","","","",""],
["","elijah","","can we hear what you have so far?","","","","","",""],
["","numa","","alright, um","","","","","",""],
["","","","it's not very good","","","","","",""],
["","elijah","","no worries.","","","","","",""],
["","numa","","ahem","","","","","",""],
["","","","roses are white","","","","","",""],
["","","","violets are white","","","","","",""],
["","","","to me, you are","","","","","",""],
["","","","a shining light.","","","","","",""],
["","elijah","","hm…","","","","","",""],
["","","","that line could be a little punchier.","","","","","",""],
["","","","how about \"blazing\"?","","","","","",""],
["","numa","","a blazing light?","","","","","",""],
["","","","ooh, i like that!","numa_finished_poem","","","","",""],
["","_none","","seems like you should give them time to work.","elijah_working_with_numa_timer","","null","","",""],
["elijah_helping_numa","elijah",['elijah_neutral', 'numa_neutral'],"so, if you had to compare your mysterious lover to something,","","","","","",""],
["","","","what would it be?","","","","","",""],
["","numa","","hm…","","","","","",""],
["","","","i don't know…","","","","","",""],
["","elijah","","don't think about it too hard. just say the first thing that comes to mind.","","","","","",""],
["","numa","","uh, ok, a lamppost!","","","","","",""],
["","elijah","","a lamppost?","","","","","",""],
["","numa","","because she's tall, and.. bright?","","","","","",""],
["","","","i guess?","","","","","",""],
["","elijah","","alright","","","","","",""],
["","","","we can work with this","","","","","",""],
["","_none","","seems like they still need time.","","","null","","",""],
["elijah_meowseum","_none","_none","_pass","",['asked_sean_only', 'got_meowseum_passcode and asked_about_meowseum_door', 'asked_about_meowseum_door'],['elijah_meowseum_catchup', 'elijah_meowseum3', 'elijah_meowseum2', 'elijah_meowseum1'],"","",""],
["elijah_meowseum1","you","","do you know how to get into the meowseum?","","","","","",""],
["","","","there's a padlock on the door","","","","","",""],
["","elijah","","ah, that would be sean's fault.","","elijah_and_sean_together",['elijah_meowseum1a', 'elijah_meowseum1b'],"","",""],
["elijah_meowseum1a","sean",['elijah_neutral', 'sean_neutral'],"oh, yeah!","display_elijah_and_sean","","","","",""],
["","","","that's from hide-and-seek.","","","sean_hide_and_seek","","",""],
["elijah_meowseum1b","elijah","","he put it there during hide-and-seek.","asked_elijah_only","","","","",""],
["","","","","","","","",['you were playing hide-and-seek?', 'you padlocked a door while playing hide-and-seek?'],['elijah_hide_and_seek1', 'elijah_hide_and_seek2']],
["elijah_hide_and_seek1","you","","you were playing hide and seek?","","","","","",""],
["","","","aren't you kind of old for that?","","","","","",""],
["","elijah","","hey, we're stuck in neverland.","","","","","",""],
["","","","might as well act like it.","","","elijah_hide_and_seek3","","",""],
["elijah_hide_and_seek2","you","","you padlocked a door while playing hide-and-seek?","","","","","",""],
["","elijah","","sean said he wanted to make the game \"spicier\"","","","","","",""],
["","","","...","","","","","",""],
["","","","i suppose it worked","","","","","",""],
["","","","if only because he locked natalie into the museum.","","","","","",""],
["","you","","really??","","","","","",""],
["elijah_hide_and_seek3","elijah","","anyway, i think he wrote the code down on one of my old poems","asked_about_meowseum_door","","","","",""],
["","","","should be around here somewhere.","","","","","",""],
["","","","...","","","","","",""],
["","","","hm...","","","","","",""],
["","you","","what is it?","","","","","",""],
["","elijah","","not where i thought it was","","","","","",""],
["","","","could be that he dropped it in the park when he went on a walk earlier.","","got_meowseum_passcode",['elijah_is_it_1234', 'elijah_hide_and_seek4'],"","",""],
["elijah_hide_and_seek4","","","anyway, ask him if he remembers the code","","","","","",""],
["","","","which he probably doesn't","","","","","",""],
["","","","in which case we'll just have to find the paper...","","","","","",""],
["","you","","okay, i'll take a [i]lock[/i] around!","","","","","",""],
["","elijah","","heh, good luck","","","","","",""],
["","","","i'll keep looking around here.","","","null","","",""],
["elijah_meowseum2","you","","any luck finding the passcode to the meowseum?","","","","","",""],
["","elijah","","nope, lady luck has not visited us today.","","","","","",""],
["elijah_lady_luck","","","but also, there's like, a million papers in here","","","","","",""],
["","","","so i wouldn't hedge my bets.","","","","","",""],
["","you","","lol right","","elijah_and_sean_together",['elijah_lady_luck1', 'elijah_lady_luck2'],"","",""],
["elijah_lady_luck1","sean",['elijah_neutral', 'sean_neutral'],"i bet it's in the park","display_elijah_and_sean","","","","",""],
["","","","you should take a look around there","","","","","",""],
["","elijah","","if you have the time, that is.","","","","","",""],
["","sean","","of course {they} {have/has} the time. it's purrgatory.","","","","","",""],
["","elijah","","hey, being polite ain't never hurt anyone.","","","null","","",""],
["elijah_lady_luck2","elijah","","you should take a look around the park.","","","","","",""],
["","","","i bet he dropped it there earlier.","","","","","",""],
["","you","","alrighty","","","null","","",""],
["elijah_meowseum3","you","","so, uh","","","","","",""],
["","","","i think i found the poem you guys mentioned","","","","","",""],
["","elijah","","oh, did you?","","","elijah_is_it_1234_1","","",""],
["elijah_is_it_1234","you","","oh, i think i saw it earlier!","","","","","",""],
["elijah_is_it_1234_1","you","","but all it said in the corner was \"ronnie wood\"...?","","elijah_and_sean_together",['elijah_is_it_1234_2', 'elijah_is_it_1234_3'],"","",""],
["elijah_is_it_1234_2","sean",['elijah_neutral', 'sean_neutral'],"YEAH THAT'S IT!","display_elijah_and_sean","","sean_ronnie_wood","","",""],
["elijah_is_it_1234_3","elijah","","huh?","","","","","",""],
["","","","ohhhhh, i remember this now.","","","","","",""],
["","","","sean said he would choose the number based on his favorite ronnie wood album, 1234.","","","","","",""],
["","you","","...really?","","","","","",""],
["","","","so the combination is just 1234?","","","","","",""],
["","elijah","","yes. really.","","","","","",""],
["","you","","lmao cool","","","null","","",""],
["elijah_meowseum_catchup","you","","hey, sean said that he wrote the passcode to the meowseum on one of your poems",[['asked_sean_only', false]],"","","","",""],
["","","","do you know where it is?","","","","","",""],
["","elijah","","i thought he had it?","","","","","",""],
["","you","","i guess he lost it...?","","","","","",""],
["","elijah","","pfft","","","","","",""],
["","","","figures","","","","","",""],
["","","","i'll take a look around, but i don't really know where it could be.","","got_meowseum_passcode",['elijah_meowseum_catchup1', 'elijah_meowseum_catchup2'],"","",""],
["elijah_meowseum_catchup1","you","","actually, i think i might have found it...","","","elijah_is_it_1234_1","","",""],
["elijah_meowseum_catchup2","you","","ah, alright, thanks.","","","null","","",""],
["elijah_wasup","you","elijah_neutral","what's up?","","elijah_quest_complete",['elijah_wasup_after', 'elijah_wasup_before'],"","",""],
["elijah_wasup_before","","","_pass","","",['_rand', 'elijah_wasup1', 'elijah_wasup2', 'elijah_wasup3', 'elijah_wasup4', 'elijah_wasup5', 'elijah_wasup6', 'elijah_wasup7', 'elijah_wasup8', 'elijah_wasup9', 'elijah_wasup10', 'elijah_wasup11', 'elijah_wasup12', 'elijah_wasup13', 'elijah_wasup14', 'elijah_wasup15', 'elijah_wasup16', 'elijah_wasup17', 'elijah_wasup18', 'elijah_wasup19', 'elijah_wasup20'],"","",""],
["elijah_wasup_after","","","_pass","","",['_rand', 'elijah_wasup1_after', 'elijah_wasup2', 'elijah_wasup4_after', 'elijah_wasup5', 'elijah_wasup6', 'elijah_wasup7', 'elijah_wasup8', 'elijah_wasup9', 'elijah_wasup10', 'elijah_wasup11', 'elijah_wasup12', 'elijah_wasup13', 'elijah_wasup14', 'elijah_wasup15', 'elijah_wasup16', 'elijah_wasup17', 'elijah_wasup18', 'elijah_wasup20'],"","",""],
["elijah_wasup1","elijah","","just poetry","","","","","",""],
["","you","","cool, cool.","","","null","","",""],
["elijah_wasup1_after","elijah","","just weeds.","","","","","",""],
["","you","","cool, cool.","","","null","","",""],
["elijah_wasup2","elijah","","wondering if we'll ever run out of paper.","","","","","",""],
["","you","","well, it your bookshelf is running pretty low...","","","","","",""],
["","elijah","","oh, that's just the most recent batch","","","","","",""],
["","","","there's a storage crate in the warehouse just full of 'em.","","","","","",""],
["","you","","wow","","","null","","",""],
["elijah_wasup3","elijah","","oh, you know. writing words. ","","","","","",""],
["","","","wording rights.","","","","","",""],
["","","","righting wrongs and writing wrong words.","","","","","",""],
["","you","","cool!","","","null","","",""],
["elijah_wasup4","you","","you look like you're in pain :c","","","","","",""],
["","elijah","","hand is... cramping...","","","","","",""],
["","you","","well, at least you're [i]hand[/i]-ling it pretty well!","","","","","",""],
["","elijah","","ha... ha...","","","null","","",""],
["elijah_wasup4_after","you","","you look like you're in pain :c","","","","","",""],
["","elijah","","yeah, my back is really feeling it right now","","","","","",""],
["","","","am i really getting that old?","","","null","","",""],
["elijah_wasup5","elijah","","thought i saw a spider earlier","","","","","",""],
["","you","","oh no","","","","","",""],
["","elijah","","...but it was just a weird eraser shaving.","","","","","",""],
["","you","","oh, thank god","","","","","",""],
["","","","i HATE spiders","","","","","",""],
["","elijah","","why the ire for our 8-legged homies?","","","","","",""],
["","you","","they're not MY homies ):<","","elijah_and_sean_together",['elijah_wasup5a', 'elijah_wasup5b'],"","",""],
["elijah_wasup5a","sean",['elijah_neutral', 'sean_neutral'],"i'm on {player}'s side. spiders don't have rights.","display_elijah_and_sean","","","","",""],
["elijah_wasup5b","elijah","","if you say so.","","","null","","",""],
["elijah_wasup6","elijah","","man, i wish i could eat cheerios again.","","","","","",""],
["","you","","me too, cereal is yummy","","","","","",""],
["","elijah","","mhm","","","","","",""],
["","","","was the only thing worth getting out of bed for, some days.","","","","","",""],
["","you","","oh ):","","","null","","",""],
["elijah_wasup7","elijah","","i don't know","","","","","",""],
["","","","is anything ever up?","","","","","",""],
["","you","","wow, i never thought of it that way before...","","","null","","",""],
["elijah_wasup8","elijah","","what do you think of the phrase \"everywhere the triumph of the mediocre\"?","","","","","",""],
["","you","","oh, that's pretty good!!","","","","","",""],
["","","","did you write that?","","","","","",""],
["","elijah","","nope","","","","","",""],
["","you","","oh","","","","","",""],
["","elijah","","it was some frenchman","","","","","",""],
["","","","can't remember the name anymore.","","elijah_and_sean_together",['elijah_wasup8a', 'elijah_wasup8b'],"","",""],
["elijah_wasup8a","you","","ah, i see","","","null","","",""],
["elijah_wasup8b","sean",['elijah_neutral', 'sean_neutral'],"i call bullshit","display_elijah_and_sean","","","","",""],
["","","","i was mediocre my whole life, and [i]i[/i] died in a 7-eleven.","","","","","",""],
["","elijah","","pfft","","","","","",""],
["","","","point taken.","","","","","",""],
["","you","","i'm sure you weren't mediocre at [i]everything[/i]","","","","","",""],
["","sean","","that's true","","","","","",""],
["","","","i was pretty good at lovin' ;)","","","","","",""],
["","you","","ooh ;)","","","null","","",""],
["elijah_wasup9","elijah","","not much.","","","","","",""],
["","","","what's up with you?","","","","","",""],
["","you","","not much also.","","","null","","",""],
["elijah_wasup10","elijah","","i was wondering","","","","","",""],
["","","","is twerking still a thing?","","","","","",""],
["","you","","um, i guess?","","","","","",""],
["","","","at least it was when i died","","","","","",""],
["","","","why... do you ask?","","","","","",""],
["","elijah","","morbid curiosity.","","","null","","",""],
["elijah_wasup11","elijah","","thinking about that one robert frost poem.","","","","","",""],
["","you","","what about it?","","","","","",""],
["","elijah","","when he said \"i have miles to go before i sleep\"?","","","","","",""],
["","","","i really felt that","","","null","","",""],
["elijah_wasup12","elijah","","what do you think of the word \"sepulchre\"?","","","","","",""],
["","you","","uh, what does it mean?","","","","","",""],
["","elijah","","i don't know","","","","","",""],
["","","","i never found out","","","","","",""],
["","you","","hm","","","","","",""],
["","","","well, it's a pretty cool sounding word.","","","","","",""],
["","elijah","","sure is.","","","null","","",""],
["elijah_wasup13","elijah","","what do you think of the word \"rustic\"?","","","","","",""],
["","you","","hmm","","","","","",""],
["","","","it's kinda rude, i guess","","","","","",""],
["","elijah","","hmmmmm","","","","","",""],
["","","","maybe you're right.","","","null","","",""],
["elijah_wasup14","elijah","","what do you think of the word \"grimy\"?","","","","","",""],
["","you","","uhhh","","","","","",""],
["","","","you can [i]grimy[/i] a river?","","","","","",""],
["","elijah","","...","","","","","",""],
["","","","heh, that was a good one","","","","","",""],
["","you","","thanks!","","","null","","",""],
["elijah_wasup15","elijah","","did you ever read the pit and the pendulum?","","","","","",""],
["","you","","i don't think so, why do you ask?","","","","","",""],
["","elijah","","cus that shit was wack, man","","","null","","",""],
["elijah_wasup16","elijah","","did you ever read hamlet?","","","","","",""],
["","you","","uh, nope","","","","","",""],
["","elijah","","me neither.","","","","","",""],
["","you","","oh","","","","","",""],
["","","","you think we missed out on much?","","","","","",""],
["","elijah","","probably not.","","","null","","",""],
["elijah_wasup17","elijah","","wish i could have played tennis while i was alive.","","","","","",""],
["","you","","oh really?","","","","","",""],
["","elijah","","yeah, always thought it looked fun","","","","","",""],
["","","","should have tried it at least once.","","","","","",""],
["","you","","you could have been an olympic champion and we'll never know!","","","","","",""],
["","elijah","","hah","","","","","",""],
["","","","that's a good one.","","","null","","",""],
["elijah_wasup18","elijah","","did you know you don't have to breathe in purrgatory?","","","","","",""],
["","you","","what?","","","","","",""],
["","elijah","","it always freaks out newcomers.","","","","","",""],
["","","","try it.","","","","","",""],
["","you","","um, okay.","","","","","",""],
["","","","...","","","","","",""],
["","elijah","","...","","","","","",""],
["","you","","...","","","","","",""],
["","elijah","","...","","","","","",""],
["","you","","...","","","","","",""],
["","elijah","","...","","","","","",""],
["","you","","that's freaky.","","","","","",""],
["","elijah","","told you so.","","","null","","",""],
["elijah_wasup19","elijah","","writer's block.","","","","","",""],
["","you","","you do look sort of [i]pen[/i]-sive.","","","","","",""],
["","elijah","","pfft.","","","null","","",""],
["elijah_wasup20","elijah","","nothing.","","","","","",""],
["","you","","yep, sounds about right.","","","null","","",""],
["elijah_hows_the_poetry","you","","how's the poetry going?","","","","","",""],
["","elijah","","same as usual, i suppose.","","sean_went_to_piano",['elijah_hows_the_poetry2', 'elijah_hows_the_poetry1'],"","",""],
["elijah_hows_the_poetry1","you","","does that mean... good? or bad?","","","","","",""],
["","elijah","","bad.","","","","","",""],
["","_none","","elijah sighs and throws another crumpled paper onto the pile.","","","","","",""],
["elijah_hows_the_poetry2","","","","","","",['true', 'true', 'not elijah_suggested_found_poetry'],['did you write in real life?', 'what\'s all this on the floor?', 'can i hear some of it?'],['elijah_real_life', 'elijah_floor', 'elijah_hear_poetry']],
["elijah_real_life","you","","were you a writer in real life, too?","","","","","",""],
["","elijah","","ha. not much of one.","","","","","",""],
["","","","but yeah, i did write.","","","","","",""],
["","you","","that's pretty cool","","","","","",""],
["","","","how did you get started?","","","","","",""],
["","elijah","","joined a club in college.","","","","","",""],
["","you","","ooh, fun","","","","","",""],
["","elijah","","yep, warner robins poetry slam, that's what we called ourselves","","","","","",""],
["","","","it was a pretty low-key thing","","","","","",""],
["","you","","i'm guessing you're the one who put up the \"purrgatory poetry slam\" banner, then?","","","","","",""],
["","elijah","","ah... yeah. that would be me","","","","","",""],
["","you","","how did that go?","","","","","",""],
["","elijah","","well... uh... how do i put this politely...","","elijah_and_sean_together",['elijah_real_life1', 'elijah_real_life2'],"","",""],
["elijah_real_life1","sean",['elijah_neutral', 'sean_neutral'],"it was total dog shit?","display_elijah_and_sean","","","","",""],
["","elijah","","...not my first choice of words.","","","","","",""],
["","sean","","well it [i]was[/i]. no one showed up.","","","","","",""],
["","","","(except me)","","","","","",""],
["","elijah","","yes, i enjoyed your poem \"there's no toilets in purrgatory\" very much.","","","","","",""],
["","sean","","some of my best work :P","","","","","",""],
["","elijah","","do you write much, {player}?","","","elijah_real_life3","","",""],
["elijah_real_life2","elijah","","it was a total bust.","","","","","",""],
["","","","no one showed up, except for sean.","","","","","",""],
["","you","","aw, damn","","","","","",""],
["","","","better luck next time?","","","","","",""],
["","elijah","","i suppose.","","","","","",""],
["","you","","i mean, no one took the sign down","","","","","",""],
["","","","so if you think about it, the slam is still going right now.","","","","","",""],
["","elijah","","that's definitely one way of looking at it.","","","","","",""],
["","","","how about you, do you write much?","","","","","",""],
["elijah_real_life3","","","","","","","",['yeah!', 'no'],['elijah_real_life4', 'elijah_real_life5']],
["elijah_real_life4","you","","yeah!","","","","","",""],
["","","","nothing serious, but i used to","","","","","",""],
["","","","i guess i fell out of the habit","","","","","",""],
["","elijah","","and out of the world?","","","","","",""],
["","you","","lol, yeah, and that.","","","","","",""],
["","elijah","","well, you have plenty of time to pick it up again.","","","","","",""],
["","you","","that's true","","","","","",""],
["","","","maybe i should!","","","null","","",""],
["elijah_real_life5","you","","not really","","","","","",""],
["","","","words aren't really my strong suit.","","","","","",""],
["","elijah","","well, you seem pretty good at wordplay","","","","","",""],
["","you","","that's different!","","","","","",""],
["","","","i can't just write a bunch of puns and call that a poem.","","","","","",""],
["","elijah","","why not?","","","","","",""],
["","","","a poem can be anything you want, man","","","","","",""],
["","you","","hmm...","","","","","",""],
["","","","maybe you're [i]write[/i]!","","","null","","",""],
["elijah_floor","you","","so, what's all this on the floor?","","","","","",""],
["","","","it's not all poems, is it?","","","","","",""],
["","elijah","","fraid so.","","","","","",""],
["","you","","why do you throw them all away??","","elijah_and_sean_together",['elijah_floor1', 'elijah_floor2'],"","",""],
["elijah_floor1","sean",['elijah_neutral', 'sean_neutral'],"that's what i always say!","display_elijah_and_sean","","","","",""],
["","","","and then [i]he's[/i] always like...","","","","","",""],
["","elijah","","they're just not very good.","","","","","",""],
["","sean","","they're totally fine!","","","","","",""],
["","elijah","","but you haven't read any of them!","","","","","",""],
["","sean","","yes, because you won't [i]let[/i] me read any of them!!","","","","","",""],
["","","","ugh","","","","","",""],
["","","","{player}, do you see what i've been dealing with?","","","","","",""],
["","you","","umm, yeah, i guess","","","","","",""],
["","elijah","","one of these days, i'll stumble upon the perfect words in the perfect order","","","","","",""],
["","","","until then, i am cursed to discard vapid pages for eternity.","","","","","",""],
["","sean","","you're really not","","","","","",""],
["","elijah","","yes i am","","","","","",""],
["","","","i am cursed","","","","","",""],
["","sean","","you are doing this to YOURSELF","","","","","",""],
["","elijah","","it is beyond my authority","","","","","",""],
["","sean","","ARGH","","","null","","",""],
["elijah_floor2","elijah","","they're just not very good.","","","","","",""],
["","you","","wow","","","","","",""],
["","","","all of them?","","","","","",""],
["","elijah","","one of these days, i'll stumble upon the perfect words in the perfect order","","","","","",""],
["","","","until then, i am cursed to discard vapid pages for eternity.","","","","","",""],
["","you","","damn","","","null","","",""],
["elijah_odontophorous","you","","what does the word on that sign mean?","","","","","",""],
["","elijah","","odontophorous?","","","","","",""],
["","","","no clue.","","","","","",""],
["","","","my working theory is that it's a type of bug.","","","","","",""],
["","","","what do you think?","","","","","",""],
["","you","","hmm","","","","","",""],
["","","","","","","","",['something that smells really bad', 'something that\'s yellowish-white', 'something that\'s part of a tooth', 'someone who\'s a suck-up'],['elijah_odontophorous1', 'elijah_odontophorous2', 'elijah_odontophorous3', 'elijah_odontophorous4']],
["elijah_odontophorous1","you","","something that smells really bad ","","","elijah_odontophorous5","","",""],
["elijah_odontophorous2","you","","something that's yellowish-white","","","elijah_odontophorous5","","",""],
["elijah_odontophorous3","you","","something that's part of the tooth","","","elijah_odontophorous5","","",""],
["elijah_odontophorous4","you","","someone who's a suck-up","","","","","",""],
["elijah_odontophorous5","elijah","","could be.","","","","","",""],
["","you","","but wait","","","","","",""],
["","","","why did you frame a word that you don't know?","","","","","",""],
["","elijah","","[i]i[/i] didn't put it up there. it was there when i got here.","","","","","",""],
["","you","","oh, weird","","elijah_and_sean_together",['elijah_odontophorous6', 'null'],"","",""],
["elijah_odontophorous6","sean",['elijah_neutral', 'sean_neutral'],"my theory is that satan was having a little laugh and decided to use the only word that elijah doesn't know.","display_elijah_and_sean","","","","",""],
["","elijah","","you trippin, man. there are plenty of words i don't know.","","","","","",""],
["","","","have you heard one of oliver's lectures? he talks circles around me.","","","","","",""],
["","sean","","yeah, once","","","","","",""],
["","","","i feel asleep at \"denominator.\"","","","","","",""],
["","elijah","","that's... not even a hard word","","","","","",""],
["","sean","","well no need to rub it in ):<","","","null","","",""],
["elijah_hands","you","","i hope this isn't rude, but","","","","","",""],
["","","","why do you always do that with your hands?","","","","","",""],
["","elijah","","you mean folding them like this?","","","","","",""],
["","you","","yeah, that.","","","","","",""],
["","elijah","","oh, it's just that sean is too cute.","","","","","",""],
["","you","","wait","","","","","",""],
["","","","really??","","","","","",""],
["","elijah","","nah, i'm just pulling your leg. ","","","","","",""],
["","","","i'm a pangolin.","","","","","",""],
["","","","this is just how we stand.","","","","","",""],
["","you","","oh","","","null","","",""],
["elijah_hear_poetry","_none","_none","_pass","","sean_went_to_piano",['elijah_hear_more_poetry', 'elijah_hear_poetry0'],"","",""],
["elijah_hear_poetry0","you","","can i hear some of it?","","","","","",""],
["","elijah","","oh, i don't know about that.","","","","","",""],
["","","","it's a work in progress.","","","","","",""],
["","you","","ooh, do you want some feedback?","","","","","",""],
["","elijah","","nah, don't worry about it, man.","","","","","",""],
["","","","preciate it, though.","","","","","",""],
["","","","","","","","",['push it', 'let it go'],['elijah_hear_poetry2', 'elijah_hear_poetry1']],
["elijah_hear_poetry1","you","","alrighty, if you say so.","","","null","","",""],
["elijah_hear_poetry2","you","","come on i promise i won't judge!!","","","","","",""],
["","","","i'm just curious!","","","","","",""],
["","elijah","","well...","","","","","",""],
["","","","i guess i have been struggling to finish this one for a while.","","","","","",""],
["","","","it just has a few holes i can't fill in.","","","","","",""],
["","sean",['elijah_neutral', 'sean_neutral'],"what if you like, madlib it?","display_elijah_and_sean","","","","",""],
["","","","like you put in random words and see what you get.","","","","","",""],
["","you","","that sounds fun!","","","","","",""],
["","elijah","","hmmm","","","","","",""],
["","","","maybe it could be fun.","","","","","",""],
["","","","like i'll describe the word, and then you choose it?","","","","","",""],
["","","","","","","","",['let\'s do it', 'actually maybe later'],['elijah_hear_poetry4', 'elijah_hear_poetry3']],
["elijah_hear_poetry3","you","","actually... maybe later, sorry","","","","","",""],
["","","","there's some other stuff i want to get to...","","","","","",""],
["","elijah","","oh.","","","","","",""],
["","","","well. ","","","","","",""],
["","","","take your time, i guess.","","","","","",""],
["","you","","sorry...","","","","","",""],
["","elijah","","'sokay.","","","null","","",""],
["elijah_hear_poetry4","you","elijah_neutral","yeah let's do it!","display_elijah","","","","",""],
["","elijah","","okay!","","","","","",""],
["","","","alright okay","","","","","",""],
["","_none","","elijah smooths out a mostly-uncrumpled paper from the desk.","","","","","",""],
["","elijah","","first word - or phrase - is...","","","","","",""],
["","","","an action that you would be concerned about if you saw a stranger doing it.","","","","","",""],
["","you","","hmmm....","","","","","",""],
["","","","","","","","",['following me', 'crying', 'juggling knives', 'putting ranch on pizza'],['elijah_wander1a', 'elijah_wander1b', 'elijah_wander1c', 'elijah_wander1d']],
["elijah_wander1a","you","","following me","_madlib1_following me","","","","",""],
["","","","that's would definitely make me concerned","","","","","",""],
["","elijah","","fair enough.","","","","","",""],
["","","","next word is...","","","elijah_wander2","","",""],
["elijah_wander1b","you","","crying!","_madlib1_crying","","","","",""],
["","","","that poor stranger","","","","","",""],
["","elijah","","fair enough.","","","","","",""],
["","","","next word is...","","","elijah_wander2","","",""],
["elijah_wander1c","you","","juggling knives!","_madlib1_juggling knives","","","","",""],
["","elijah","","huh?","","","","","",""],
["","you","","wouldn't that make you concerned? if you saw someone juggling knives?","","","","","",""],
["","elijah","","fair enough","","","","","",""],
["","","","next word is...","","","elijah_wander2","","",""],
["elijah_wander1d","you","","putting ranch on pizza","_madlib1_putting ranch on pizza","","","","",""],
["","elijah","","that's gross","","","","","",""],
["","you","","right??","","","","","",""],
["","sean",['elijah_neutral', 'sean_neutral'],"hey, i put ranch on pizza!","display_elijah_and_sean","","","","",""],
["","elijah","","of course you do.","","","","","",""],
["","sean","","it's good. it makes it spicy.","","","","","",""],
["","you","","sean... no....","","","","","",""],
["","sean","","let me live my life okay!!","","","","","",""],
["","elijah","","anyway, the next word is...","","","elijah_wander2","","",""],
["elijah_wander2","","elijah_neutral","something you would find in a forest.","display_elijah","","","","",""],
["","","","","","","","",['branches', 'tulips', 'witches', 'worms'],['elijah_wander2a', 'elijah_wander2b', 'elijah_wander2c', 'elijah_wander2d']],
["elijah_wander2a","you","","branches!","_madlib2_branches","","","","",""],
["","elijah","","uhh","","","","","",""],
["","","","branches? are you sure?","","","","","",""],
["","you","","yeah, why?","","","","","",""],
["","elijah","","heh. no reason.","","","","","",""],
["","","","so, last one is...","","","elijah_wander3","","",""],
["elijah_wander2b","you","","tulips!","_madlib2_flowers","","","","",""],
["","","","like, you know. flowers.","","","","","",""],
["","elijah","","i gotcha","","","","","",""],
["","","","last one is...","","","elijah_wander3","","",""],
["elijah_wander2c","you","","witches!","_madlib2_witches","","","","",""],
["","","","they always live in forests. i think","","","","","",""],
["","elijah","","do they?","","","","","",""],
["","you","","yes","","","","","",""],
["","","","this is a witch fact","","","","","",""],
["","elijah","","alright, let's go with that, then","","","","","",""],
["","","","last one is...","","","elijah_wander3","","",""],
["elijah_wander2d","you","","woooorms","_madlib2_worms","","","","",""],
["","elijah","","good choice","","","","","",""],
["","you","","thank you","","","","","",""],
["","elijah","","last one is...","","","elijah_wander3","","",""],
["elijah_wander3","elijah","","something that can cover something else","","","","","",""],
["","you","","ooh, this one's open-ended","","","","","",""],
["","","","i'm gonna go with....","","","","","",""],
["","","","","","","","",['glitter', 'moonlight', 'a blanket', 'a tortilla'],['elijah_wander3a', 'elijah_wander3b', 'elijah_wander3c', 'elijah_wander3d']],
["elijah_wander3a","you","","glitter!","_madlib3_glitter","","","","",""],
["","elijah","","i suppose one could be covered in glitter","","","","","",""],
["","you","","you know it","","","elijah_wander4","","",""],
["elijah_wander3b","you","","moonlight!","_madlib3_moonlight","","","","",""],
["","elijah","","a classic","","","","","",""],
["","you","","i know, thank you","","","elijah_wander4","","",""],
["elijah_wander3c","you","","a blanket","_madlib3_a blanket","","","","",""],
["","","","cus it covers you at night","","","","","",""],
["","elijah","","reading you loud and clear","","","elijah_wander4","","",""],
["elijah_wander3d","you","","a tortilla!!","_madlib3_a tortilla","","","","",""],
["","","","cus","elijah_tortilla","","","","",""],
["","","","you know","","","","","",""],
["","","","it covers food","","","","","",""],
["","elijah","","reading you loud and clear","","","elijah_wander4","","",""],
["elijah_wander4","_none","","elijah scribbles on his paper for a moment.","","","","","",""],
["","elijah","","okay, that's everything","","","","","",""],
["","","","ready to hear our masterpiece?","","","","","",""],
["","you","","im ready!","","","","","",""],
["","elijah","","alright","","","","","",""],
["","","","ahem","","","","","",""],
["","","","...","","","","","",""],
["","you","","...","","","","","",""],
["","elijah","","...","","","","","",""],
["","you","","take your time!","","","","","",""],
["","elijah","","yes i will, thank you","","","","","",""],
["","","","...","","","","","",""],
["","","","[i]i'm lost in the woods[/i]","","","","","",""],
["","","","[i]footsore, ears ringing[/i]","","","","","",""],
["","","","[i]like i got dragged to a party, or[/i]","","","","","",""],
["","","","[i]dropped a grenade[/i]","","","","","",""],
["","","","[i]i think the trees are {madlib1}[/i]","","","","","",""],
["","","","[i]they open up, like[/i]","","","","","",""],
["","","","[i]a creaky garage door[/i]","","","","","",""],
["","","","[i]revealing sharp maws,[/i]","","","","","",""],
["","","","[i]branches splitting into {madlib2}[/i]","","","","","",""],
["","","","[i]pick yourself up, they say[/i]","","","","","",""],
["","","","[i]chill out, count to five[/i]","","","","","",""],
["","","","[i]stagger through the bracken 'til[/i]","","","","","",""],
["","","","[i]it covers you like {madlib3}.[/i]","","","","","",""],
["","you","","...","","","","","",""],
["","","","yo that was awesome!","","","","","",""],
["","elijah","","really?","","","","","",""],
["","you","","i mean...","","","","","",""],
["","","","","","","","",['it was really pretty', 'it was really silly'],['elijah_wander6', 'elijah_wander7']],
["elijah_wander6","you","","it was really pretty!","","","","","",""],
["","","","we're a great team :3","","","","","",""],
["","elijah","","heh, thank you","","","elijah_wander8","","",""],
["elijah_wander7","you","","it was really silly","","","","","",""],
["","","","which is fine!","","","","","",""],
["","elijah","","heh, i guess so","","","","","",""],
["elijah_wander8","sean",['elijah_neutral', 'sean_neutral'],"yoo does this mean you're going to stop moping about your poetry??","display_elijah_and_sean","elijah_tortilla",['elijah_wander8a', 'elijah_wander8b'],"","",""],
["elijah_wander8a","","","i liked the tortilla btw, you should keep that part","","","","","",""],
["elijah_wander8b","elijah","","hmm....","","","","","",""],
["","","","i think....","","","","","",""],
["","sean","","yes???","","","","","",""],
["","elijah","","i think.............","","","","","",""],
["","sean","","that your poetry is good?","","","","","",""],
["","elijah","","[i]sigh[/i]","","","","","",""],
["","","","i think it's a lost cause","","","","","",""],
["","","","the poem still sucks","","","","","",""],
["","sean","","oh my god, you're such a freaking downer!!","","","","","",""],
["","","","elijah. listen to me. you're talented as hell and anyone would be lucky to write like you","","","","","",""],
["","elijah","","you're just saying that.","","","","","",""],
["","sean","","i am not!!"," ","","","","",""],
["","","","i'd give anything to be in your shoes!","","","","","",""],
["","elijah","","pfft. really?","","","","","",""],
["","","","my life fucking sucked","","","","","",""],
["","you","","um, guys, i think--","","","","","",""],
["","sean","","well at least you accomplished something!","","","","","",""],
["","","","how do you think i feel?","","","","","",""],
["","","","spent my whole life partying, died at 24, never did anything productive","","","","","",""],
["","elijah","","oh, get over yourself.","","","","","",""],
["","","","you were partying. so you enjoyed yourself. is that not good enough for you?","","","","","",""],
["","sean","","uh, no? i guess?","","","","","",""],
["","elijah","","what about dani, were they not--","","","","","",""],
["","sean","","don't bring dani into this!","","","","","",""],
["","you","","guys, guys","","","","","",""],
["","","","","","","","",['maybe you two need to cool down', 'there\'s nothing you can do about the past', 'stop being mean to each other jesus'],['elijah_argument1', 'elijah_argument2', 'elijah_argument3']],
["elijah_argument1","you","","i think both of you need to cool down a little","","","","","",""],
["","","","maybe it would be a good idea to like, have some time apart?","","","","","",""],
["","elijah","","...","","","","","",""],
["","","","that's a good idea.","","","","","",""],
["","sean","","yeah, yeah, whatever. ","","","","","",""],
["","","","i guess you're right.","","","","","",""],
["","","","sorry i brought it up","","","","","",""],
["","_none","","elijah shrugs.","","","","","",""],
["","elijah","","we cool.","","","elijah_argument4","","",""],
["elijah_argument2","you","","there's nothing you can do about that stuff now!","","","","","",""],
["","","","we're all in purrgatory together, and that's all that matters","","","","","",""],
["","sean","","i mean i GUESS","","","","","",""],
["","","","but i'm still a little pissed","","","","","",""],
["","_none","","elijah shrugs.","","","elijah_argument4","","",""],
["elijah_argument3","you","","stop being so mean to each other, jesus","","","","","",""],
["","","","we're all stuck here together anyway, we might as well get along","","","","","",""],
["","sean","","i'm not being mean!","","","","","",""],
["","","","i'm just pointing out the obvious!","","","","","",""],
["","elijah","","you are a little mean sometimes.","","","","","",""],
["","sean","","NO IM NOT","","","","","",""],
["","","","when have i been mean even once?","","","","","",""],
["","elijah","","well, there's that time you called me lumpy...","","","","","",""],
["","sean","","THAT WAS FRIENDLY BANTER","","","elijah_argument4","","",""],
["elijah_argument4","sean","","you know what","","","","","",""],
["","","","i'm gonna go... somewhere else","","","","","",""],
["","","","i'll be at the piano if u wanna chat, {player}","","","","","",""],
["","you","","oh, alright","","","","","",""],
["","sean","","seeya","","","","","",""],
["","elijah","","cya","","","","","",""],
["","","elijah_neutral","...",[['elijah_and_sean_together', false]],"","","","",""],
["","you","","...","sean_went_to_piano","","","","",""],
["","","","um","","","","","",""],
["","","","are you alright?","elijah_went_to_sleep","","","","",""],
["","elijah","","yeah","","","","","",""],
["","","","...","","","","","",""],
["","","","thanks for helping me with my poem","","","","","",""],
["","","","i think i'm going to take a nap.","","","","","",""],
["","you","","oh, alright","","","","","",""],
["","","","have a nice sleep!","","","","","",""],
["","elijah","","thanks","","","","","",""],
["","","","i'll just be in the other room","","","","","",""],
["","","","wake me up if you need anything.","","","","","",""],
["","you","","alrighty","","","null","","",""],
["elijah_hear_more_poetry","you","","can i hear more poetry maybe?","","","","","",""],
["","","","the tree one was really good","","","","","",""],
["","elijah","","appreciate it.","","","","","",""],
["","","","hmm...","","","","","",""],
["","_none","","elijah uncrumples a piece of paper from the floor.","","","","","",""],
["","elijah","","oh, i remember this one.","","","","","",""],
["","","","this is from my \"blue period.\"","","","","","",""],
["","you","","like picasso?","","","","","",""],
["","elijah","","huh?","","","","","",""],
["","","","no, like i used a blue pen.","","","","","",""],
["","you","","oh","","","","","",""],
["","_none","","elijah tosses it back onto the pile.","","","","","",""],
["","elijah","","i think...","","","","","",""],
["","","","i'm not really in the mood right now.","","","","","",""],
["","","","maybe later?","","","","","",""],
["","you","","ok, that's cool","","","null","","",""],
["elijah_nap","_none","_none","elijah mumbles in his sleep.","","","","","",""],
["","","","","","","",['numa_started_poem and not numa_finished_poem', 'sean_jammed',  'true'],['wake him to ask about numa', 'wake him to ask if you can read his poems', 'let sleeping pangolins lie'],['elijah_nap_numa', 'elijah_nap_poems', 'null']],
["elijah_nap_numa","you","","hey... elijah?","","","","","",""],
["","","","...","","","","","",""],
["","","","elijah??","","","","","",""],
["","elijah","elijah_neutral","mmmah. what?","_hide_elijah_asleep","","","","",""],
["","you","","sorry to wake you up...","","","","","",""],
["","elijah","","sokay... need somethin?","","","elijah_numa","","",""],
["elijah_nap_poems","you","","psst... elijah...","","","","","",""],
["","elijah","","bubr","","","","","",""],
["","you","","uhhhh","","","","","",""],
["","","","elijah?","","","","","",""],
["","elijah","","fubmr... ham... ","","","","","",""],
["","you","","ham?","","","","","",""],
["","elijah","","mmNO!!","","","","","",""],
["","_none","elijah_neutral","elijah shoots up from the bench, breathing hard.","_hide_elijah_asleep","","","","",""],
["","","","","","","","",['are you okay?', 'it\'s just me'],['elijah_nap1', 'elijah_nap2']],
["elijah_nap1","you","","are you okay?","","","","","",""],
["","elijah","","........","","","","","",""],
["","","","yeah","","","","","",""],
["","","","mfine","","","","","",""],
["","","","just a bad dream","","","","","",""],
["","you","","oh, i'm sorry...","","","elijah_nap3","","",""],
["elijah_nap2","you","","it's okay, it's just me!","","","","","",""],
["","elijah","","........","","","","","",""],
["","","","oh","","","","","",""],
["","","","{player}","","","","","",""],
["","you","","yep","","","","","",""],
["","elijah","","sorry","","","","","",""],
["","","","bad dream","","","","","",""],
["elijah_nap3","_none","","elijah shakes his head.","","","","","",""],
["","elijah","","you need somethin?","","","","","",""],
["","you","","um, i was actually wondering if i could maybe...","","","","","",""],
["","","","read some of your poems?","","","","","",""],
["","elijah","","hmmm?","","","","","",""],
["","you","","i know you don't like sharing, but","","","","","",""],
["","","","you know i think it's a shame if you never share your work!","","","","","",""],
["","","","and i'm really curious!","","","","","",""],
["","elijah","","hmm....","","","","","",""],
["","you","","and umm","","","","","",""],
["","","","i think they're really good?","","","","","",""],
["","","","probably?","","","","","",""],
["","elijah","","...","","","","","",""],
["","you","","please?","","","","","",""],
["","elijah","","...","","","","","",""],
["","","","yeah, why not.","","","","","",""],
["","you","","oh, thanks!","","","","","",""],
["","elijah","","doesn really matter in the end","","","","","",""],
["","","","we're just spokes in the cosmic unicycle","","","","","",""],
["","","","goin round and round","","","","","",""],
["","you","","uhh","","","","","",""],
["","","","sure, i guess","","","","","",""],
["","elijah","","...","","","","","",""],
["","","","you can read whatever you want.","","","","","",""],
["","","","im gonna go for a walk","","","","","",""],
["","you","","ok","","","","","",""],
["","","","thanks, again!","","","","","",""],
["","elijah","","don't mention it.","","","","","",""],
["","you","_none","...","elijah_woke_up","","null","","",""],
["elijah_caught","_none","","just as you replace the poem, elijah walks in.","","","","","",""],
["","you","elijah_neutral","oh, uhh, hi!!","","","","","",""],
["","elijah","","...","","","","","",""],
["","","","what are you doing in here?","","","","","",""],
["","you","","um...","","","","",['lie', 'tell the truth'],['elijah_caught1', 'elijah_caught1',]],
["elijah_caught1","you","","well--","","","","","",""],
["","elijah","","you know what, never mind.","","","","","",""],
["","","","it doesn't matter","","","","","",""],
["","you","","oh","","","","","",""],
["","elijah","","you can read some poems, if that's what you wanted.","","","","","",""],
["","","","doesn really matter in the end","","","","","",""],
["","","","we're just spokes in the cosmic unicycle","","","","","",""],
["","","","goin round and round","","","","","",""],
["","you","","oh ummm","","","","","",""],
["","","","thanks?","","","","","",""],
["","elijah","","don't mention it.","","","","","",""],
["","","","...","","","","","",""],
["","","","i'm gonna go for a walk.","","","","","",""],
["","you","","alrighty!","","","","","",""],
["","","_none","...","elijah_woke_up","","null","","",""],
["elijah_dropoff","_none","elijah_neutral","elijah looks over his shoulder.",[['_quest_elijah_company', false]],"","","","",""],
["","","","","","","","",['what\'s up?', 'are you okay?', 'you shouldn\'t sit so close to the edge'],['elijah_dropoff1', 'elijah_dropoff2', 'elijah_dropoff3']],
["elijah_dropoff1","you","","what's up?","","","","","",""],
["","elijah","","not much","","","elijah_dropoff6","","",""],
["elijah_dropoff2","you","","are you okay?","","","","","",""],
["","elijah","","is anyone here okay?","","","","","",""],
["","","","","","","","",['hmmm', 'the cat'],['elijah_dropoff4', 'elijah_dropoff5']],
["elijah_dropoff3","you","","you shouldn't sit so close to the edge...","","","","","",""],
["","_none","","elijah shrugs","","","elijah_dropoff6","","",""],
["elijah_dropoff4","you","","hmmmm","","","","","",""],
["","","","idk","","","","","",""],
["","_none","","elijah shrugs","","","elijah_dropoff6","","",""],
["elijah_dropoff5","you","","the cat seems to be doing ok!","","","","","",""],
["","elijah","","hah","","","elijah_dropoff6","","",""],
["elijah_dropoff6","you","","umm, mind if i sit?","","","","","",""],
["","elijah","","go ahead.","","","","","",""],
["","you","","...","","","","","",""],
["","elijah","","...","","","","","",""],
["","you","","hey, can i... ask you a question?","","","","","",""],
["","elijah","","shoot.","","","","","",""],
["elijah_dropoff_choice","","","","","","",['not elijah_dropoff_asked1', 'not elijah_dropoff_asked2', 'not elijah_dropoff_asked3', 'true'],['what\'s on your mind?', 'did you sleep well?', 'how did you die?', 'are you thinking about jumping?'],['elijah_dropoff7', 'elijah_dropoff8', 'elijah_dropoff9', 'elijah_dropoff10']],
["elijah_dropoff7","you","","what's on your mind?","elijah_dropoff_asked1","","","","",""],
["","elijah","","hmm","","","","","",""],
["","","","thinking about that time one of my friends tried to teach me to skateboard.","","","","","",""],
["","","","his name was naeem.","","","","","",""],
["","you","","wow, radical","","","","","",""],
["","elijah","","it was kind of radical.","","","","","",""],
["","","","up until i fell off and busted my knee.","","","","","",""],
["","you","","oh no :c","","","","","",""],
["","elijah","","yeah","","","","","",""],
["","","","in front of all his skater friends, too.","","","","","",""],
["","","","i remember thinking they all looked cool","","","","","",""],
["","","","i thought skaters were only cool in movies.","","","","","",""],
["","you","","you're pretty cool too!","","","","","",""],
["","elijah","","pfft. thanks.","","","elijah_dropoff_choice","","",""],
["elijah_dropoff8","you","","did you sleep well?","elijah_dropoff_asked2","","","","",""],
["","elijah","","not really","","","","","",""],
["","","","i have a lot of nightmares","","","","","",""],
["","you","","aww, i'm sorry","","","","","",""],
["","","","what about, if you don't mind me asking?","","","","","",""],
["","elijah","","kuwait, mostly","","","","","",""],
["","","","sometimes basic training.","","","","","",""],
["","","","i was in the army.","","","","","",""],
["","you","","ohh, i see","","","","","",""],
["","elijah","","basic training is a bitch.","","","","","",""],
["","","","they don't tell you that during recruitment.","","","","","",""],
["","you","","damn...","","","elijah_dropoff_choice","","",""],
["elijah_dropoff9","you","","this might be a little rude, but...","elijah_dropoff_asked3","","","","",""],
["","","","how did you die?","","","","","",""],
["","elijah","","it's fine.","","","","","",""],
["","","","i commited suicide.","","","","","",""],
["","you","","oh","","","","","",""],
["","elijah","","weird how it's \"committing\" suicide, huh?","","","","","",""],
["","","","it's a commitment. no second chances.","","","","","",""],
["","","","at least, unless you end up in purrgatory.","","","","","",""],
["","","","then your whole plan kinda goes to shit.","","","","","",""],
["","you","","uh huh","","","","","",""],
["","elijah","","...","","","","","",""],
["","you","","...","","","elijah_dropoff_choice","","",""],
["elijah_dropoff10","you","","are you... thinking about jumping?","","","","","",""],
["","elijah","","...","","","","","",""],
["","","","i don't know.","","","","","",""],
["","","","...","","","","","",""],
["","","","you know when you feel like there's a fog over everything?","","elijah_tortilla",['elijah_dropoff12a', 'elijah_dropoff12b'],"","",""],
["elijah_dropoff12a","","","or... in your words... a tortilla.","","","","","",""],
["","","","a really heavy one.","","","","","",""],
["elijah_dropoff12b","","","that feeling when you don't even have the energy to shower.","","","","","",""],
["","","","when you constantly lie to your folks that you're between jobs.","","","","","",""],
["","","","run out of paper but you can't even go to the store because all your clothes are dirty.","","","","","",""],
["","","","you know that feeling?","","","","","",""],
["","you","","i guess...","","","","","",""],
["","elijah","","...","","","","","",""],
["","","","i'm sorry to make you deal with all my problems","","","","","",""],
["","","","people here would probably be better off if i was gone.","","","","","",""],
["","you","","what? that's not true!","","","","","",""],
["","","","i know sean cares about you a lot, and i'm sure the others do too!","","","","","",""],
["","elijah","","do you think so?","","","","","",""],
["","","","all i do all day is bicker with him and mope around.","","","","","",""],
["","","","i'm just weighing him down.","","","","","",""],
["","you","","well,","","","","","",""],
["","","","ummmmm","","","","","",""],
["","","","...","","","","","",""],
["","","","i think that he... probably","","","","","",""],
["","","","...","","","","","",""],
["","???","","hey, uh, hope i'm not interrupting anything","","","","","",""],
["","elijah","","sean?","","","","","",""],
["","sean",['elijah_neutral', 'sean_neutral'],"yeah it's me! speak of the snake.","","","","","",""],
["","","","just, uh, happened to be passing by.","","","","","",""],
["","","","weird coincidence meeting you here!","","","","","",""],
["","","","by the way, what [i]are[/i] you doing in here?","","","","","",""],
["","elijah","","just... chilling.","","","","","",""],
["","sean","","well, why don't we chill in, i don't know, the park?","","","","","",""],
["","","","this place gives me the creeps. we should definitely go somewhere else","","","","","",""],
["","","","i heard numa needs some help pruning trees!","","","","","",""],
["","you","","i thought all the trees here were dead...?","","","","","",""],
["","_none","","sean shoots you a look.","","","","","",""],
["","you","","oh, uh, yeah, i bet numa could use a lot of help!","","","","","",""],
["","elijah","","...","","","","","",""],
["","","","sure.","","","","","",""],
["","","","why not.","","","","","",""],
["","sean","","cooool cool cool cool","","","","","",""],
["","_none","","elijah stands up, and sean leads you back out of the cave.","_goto_hallway3","","","","",""],
["","sean","","ahh, doesn't that LED light feel much better?","","","","","",""],
["","elijah","","i'm practically rejuvenated.","","","","","",""],
["","sean","","oh, yeah, baby, that's gonna be great for my tan!","","","","","",""],
["","_none","","you walk in silence for a while.","_goto_garden1","","","","",""],
["","sean","","so, uh, by the way","","","","","",""],
["","","","elijah","","","","","",""],
["","","","you're my best friend, alright?","","","","","",""],
["","","","you're my compadre. my pal. my crony.","","","","","",""],
["","elijah","","...i don't think that means what you think it does, sean","","","","","",""],
["","sean","","ok, but you get what i mean","","","","","",""],
["","","","like, i care about you a whole lot, you dig?","","","","","",""],
["","elijah","","...sure.","","","","","",""],
["","","","thanks.","","","","","",""],
["","sean","","no problem, boblem","","","","","",""],
["","_none","","...","_goto_garden4","","","","",""],
["","elijah","","so you said numa needed help?","","","","","",""],
["","sean","","yeah, i think she's in there somewhere","","","","","",""],
["","elijah","","hmm, alright...","","","","","",""],
["","_none","","elijah disappears into the park.","","","","","",""],
["","elijah","sean_neutral","numa?","","","","","",""],
["","sean","","...","","","","","",""],
["","","","oh, man.","","","","","",""],
["","","","i think... elijah and i have some talking to do","","","","","",""],
["","you","","i think that is a good idea","","","","","",""],
["","sean","","i mean, i never knew that he felt--","","","","","",""],
["","_none","","numa's voice drifts out from the park.","","","","","",""],
["","numa","","prune the trees?","","","","","",""],
["","","","but... they're all dead...","","","","","",""],
["","sean","","ah, shit","","","","","",""],
["","","","i'll see you later {player}, alright??","","","","","",""],
["","you","","alright!","","","","","",""],
["","sean","","and, you know","","","","","",""],
["","","","thanks. for all that.","elijah_sean_bench_timer","","","","",""],
["","_none","","sean rushes into the garden too.",[['_delay__goto_flashback_elijah', true], ['_delay_elijah_quest_complete', true], ['_delay_sean_quest_complete', true]],"","null","","",""],
["end_flashback","you","","...","","","","","",""],
["","_none","","you pick yourself up from the ground.","","","null","","",""],
["elijah_sean_on_bench","_none","","better leave them alone for now.","","","null","","",""],
["elijah_post_quest","_none","_none","_pass","","elijah_saw_penis_flower",['elijah_default_post', 'elijah_post_quest_a'],"","",""],
["elijah_post_quest_a","you","elijah_neutral","hey elijah!","elijah_saw_penis_flower","","","","",""],
["","elijah","","hey!","","","","","",""],
["","_none","","elijah sits up and wipes sweat off his forehead.","","","","","",""],
["","you","","good to uhh see you out of the study","","","","","",""],
["","elijah","","mhm","","","","","",""],
["","","","feels good to be getting what counts as fresh air in this place","","","","","",""],
["","","","numa has me on beautification duty.","","","","","",""],
["","you","","oh, i see, how are those... weeds? doing?","","","","","",""],
["","elijah","","honestly? ain't sure if i'm pulling up weeds or plants right now","","","","","",""],
["","_none","","he pulls up a green thing by its roots.","","","","","",""],
["","","","","","","","",['i think that one\'s a weed', 'i think that one\'s a plant', 'idk lol'],['elijah_post_quest1', 'elijah_post_quest2', 'elijah_post_quest3']],
["elijah_post_quest1","you","","i think that one's a weed?","","","","","",""],
["","elijah","","oh, good.","","","elijah_post_quest4","","",""],
["elijah_post_quest2","you","","i think that one's a plant?","","","","","",""],
["","_none","","elijah stares at it, then shrugs.","","","","","",""],
["","elijah","","whoops.","","","elijah_post_quest4","","",""],
["elijah_post_quest3","you","","idk either lol","","","","","",""],
["","elijah","","one of these days i'll become a weed whisperer. just not today.","","","","","",""],
["elijah_post_quest4","you","","so ummm","","","","","",""],
["","","","do you want to... talk about earlier?","","","","","",""],
["","elijah","","nah","","","","","",""],
["","you","","are you sure?","","","","","",""],
["","elijah","","maybe later.","","","","","",""],
["","","","i'll get around to it.","","","","","",""],
["","","","right now, i'm feeling good, and i'm gonna keep it that way.","","","","","",""],
["","you","","great!","","","","","",""],
["","elijah","","you gotta enjoy the little things!","","","","","",""],
["","","","like this weird-ass flower.","","","","","",""],
["","","","look at it","","","","","",""],
["","you","","oh, it's shaped kind of like a...","","","","","",""],
["","","","like a...","","","","","",""],
["","elijah","","like something familiar?","","","","","",""],
["","you","","yes its shape is certainly","","","","","",""],
["","","","evocative? of a certain thing?","","","","","",""],
["","elijah","","mmm, yes, well said","","","","","",""],
["","you","","it definitely looks a little [i]root[/i]","","met_numa",['elijah_post_quest_normal', 'elijah_post_quest_alt'],"","",""],
["elijah_post_quest_alt","???",['elijah_neutral', 'numa_neutral'],"oh, um... hello","met_numa","","","","",""],
["","you","","hi!","","","","","",""],
["","???","","hey hey, haha","","","","","",""],
["","","","sorry, i didn't realize that there was anyone...","","","","","",""],
["","","","i mean, i didn't want to interrupt your conversation or anything","","","","","",""],
["","you","","oh that's okay","","","","","",""],
["","","","i'm {player}, what's your name?","","","","","",""],
["","???","","numa","","","","","",""],
["","numa","","just... wanted to ask elijah if everything was going okay, haha","","","","","",""],
["","elijah","","things are going fantastic.","","","elijah_post_quest5","","",""],
["elijah_post_quest_normal","numa",['elijah_neutral', 'numa_neutral'],"oh, hey {player}!","","","","","",""],
["","","","elijah, how is everything going?","","","","","",""],
["","elijah","","fantastic.","","","","","",""],
["elijah_post_quest5","","","would you look at this flower?","","","","","",""],
["","numa","","oh, it's very... nice","","","","","",""],
["","elijah","","doesn't it remind you of something?","","","","","",""],
["","numa","","...","","","","","",""],
["","","","......","","","","","",""],
["","","","no","","","","","",""],
["","elijah","","are you sure?","","","","","",""],
["","you","","[i]i[/i] think it looks like something","","","","","",""],
["","elijah","","yes i too believe this flower is suggestive of another thing","","","","","",""],
["","you","","i do in fact have a hunch that this flower resembles another object or thing","","","","","",""],
["","numa","","OKAY it looks like a penis!!","","","","","",""],
["","","","jeez!","","","","","",""],
["","elijah","","PFFFFT","","","","","",""],
["","you","","hehehehe","","","","","",""],
["","numa","","it's not that funny!","","","","","",""],
["","elijah","","snrk... it is kinda funny though...","","","","","",""],
["","","","the way you said it..","","","","","",""],
["","numa","","well, if you're going to be like that, maybe i'll keep this water bottle for myself!!","","","","","",""],
["","elijah","","wait, you brought me water?","","","","","",""],
["","numa","","have fun with your... penis flower!","","","","","",""],
["","elijah","","pfft","","","","","",""],
["","","","penis flower","","","","","",""],
["","_none","elijah_neutral","numa marches away.","","","","","",""],
["","elijah","","wait no please i'm so thirsty","","","","","",""],
["","","","NUMA","","","","","",""],
["","_none","","elijah scrambles after her.","elijah_why","","null","","",""],
["elijah_default_post","elijah","elijah_neutral","hey, {player}.","","","","","",""],
["","","","","","","",['true', 'true', 'numa_started_poem and not numa_finished_poem', 'true'],['what\'s up?', 'how\'s the gardening?', '(about numa\'s poem)', '(ask about...)'],['elijah_wasup', 'elijah_hows_the_gardening', 'elijah_numa', 'elijah_ask_about']],
["elijah_hows_the_gardening","you","","how's the gardening?","","","","","",""],
["","elijah","","gonna be real with you","","","","","",""],
["","","","this shit's hard work.","","","","","",""],
["","you","","oh is it?","","","","","",""],
["","elijah","","yeah, man","","","","","",""],
["","","","i'm no quitter, but damn, i'm getting a work out.","","","","","",""],
["","","","dunno how numa does this all day","","","","","",""],
["","","","she's a tough one","","","","","",""],
["","","","little, but tough.","","","","","",""],
["","you","","like an ant?","","","","","",""],
["","elijah","","hm?","","","","","",""],
["","you","","you know, they can like","","","","","",""],
["","","","lift ten times their body weight or something","","","","","",""],
["","elijah","","wow.","","","null","","",""],
["elijah_ask_about","","","","","","","",['friends', 'work', 'travel'],['elijah_friends', 'elijah_work', 'elijah_travel']],
["elijah_friends","you","","what were your friends like?","","","","","",""],
["","elijah","","before all this, you mean?","","","","","",""],
["","","","before dying?","","","","","",""],
["","you","","yeah","","","","","",""],
["","elijah","","they were alright.","","","","","",""],
["","","","spent a lot of time with the poetry slam crew.","","","","","",""],
["","you","","were there a lot of you?","","","","","",""],
["","elijah","","oh, god no","","","","","",""],
["","","","there were 6 of us, at our busiest","","","","","",""],
["","you","","oh, i see","","","","","",""],
["","elijah","","people always came and went, though.","","","","","",""],
["","","","like aram!","","","","","",""],
["","","","he joined the club when his family immigrated from armenia","","","","","",""],
["","","","then he left two weeks later to pursue his dreams of being a nurse","","","","","",""],
["","you","","wow","","","","","",""],
["","elijah","","yeah","","","","","",""],
["","","","he taught me how to say jackass in armenian","","","","","",""],
["","you","","only that?","","","","","",""],
["","elijah","","well, he taught me some other stuff too","","","","","",""],
["","","","but that's the only one i remember.","","","","","",""],
["","you","","LOL","","","","","",""],
["","elijah","","lol","","","","","",""],
["","you","","so, were you particularly close to any of them?","","","","","",""],
["","elijah","","yeah, you could say that.","","","","","",""],
["","","","there were three of us, we were pretty tight for a while","","","","","",""],
["","","","only ones that kept coming to the meetings, in the end.","","","","","",""],
["","you","","ooh, cool","","","","","",""],
["","elijah","","yeah, lots of good memories there","","","","","",""],
["","","","we drifted apart eventually, though.","","","","","",""],
["","","","one of them, jessica, she left to join a family business","","","","","",""],
["","","","and the other one, naeem","","","","","",""],
["","","","i think he left for a college in... california? maybe?","","","","","",""],
["","you","","and you moved to purrgatory!","","","","","",""],
["","elijah","","pfft, sure did.","","","","","",""],
["","","","ain't exactly what i had in mind, but hey, at least there's good company here.","","","null","","",""],
["elijah_work","you","","so, how did you make a living?","","","","","",""],
["","elijah","","heh, beats me","","","","","",""],
["","","","last job i had was at a place called southern tools.","","","","","",""],
["","you","","oh, and you sold...","","","","","",""],
["","elijah","","tools? yeah","","","","","",""],
["","","","sold tools, to tools.","","","","","",""],
["","you","","lmao nice","","","","","",""],
["","","","did you like it there?","","","","","",""],
["","elijah","","it was alright, i guess.","","","","","",""],
["","","","owner was an honest guy, just couldn't afford to keep me on the payroll.","","","","","",""],
["","you","","aw ):","","","","","",""],
["","elijah","","'salright","","","","","",""],
["","","","what i [i]really[/i] wanted to do was--","","","","","",""],
["","","","well, nah.","","","","","",""],
["","","","well...","","","","","",""],
["","you","","what?","","","","","",""],
["","elijah","","don't laugh","","","","","",""],
["","","","but what i [i]really[/i] wanted to do was be a sailor.","","","","","",""],
["","","","since i was five.","","","","","",""],
["","you","","oh that's cool!","","","","","",""],
["","elijah ","","you think?","","","","","",""],
["","you","","yeah, i wouldn't laugh at something like that","","","","","",""],
["","","","boats and stuff!!","","","","","",""],
["","elijah","","oh man... i was so into boats and stuff.","","","","","",""],
["","","","and knots","","","","","",""],
["","","","i taught myself thirty different knots in middle school.","","","","","",""],
["","you","","wow","","","","","",""],
["","elijah","","i grew out of it, though.","","","","","",""],
["","","","at least, i thought i did.","","","","","",""],
["","","","when i entered high school i threw away all my toy boats and forgot about the whole thing.","","","","","",""],
["","","","but looking back on it...","","","","","",""],
["","","","what if i had just left home and found work on a freighter or something?","","","","","",""],
["","","","left my landlocked troubles far behind?","","","","","",""],
["","","","wrote poems on the deck with only the waves to accompany me?","","","","","",""],
["","","","i mean, what's the worst that could have happened?","","","","","",""],
["","you","","i dunno","","","","","",""],
["","","","getting eaten by a whale?","","","","","",""],
["","elijah","","pfft","","","","","",""],
["","","","at least that would have been a cool way to go.","","","null","","",""],
["elijah_travel","you","","did you travel much?","","","","","",""],
["","elijah","","man, not nearly as much as i wanted to.","","","","","",""],
["","","","it's expensive.","","","","","",""],
["","you","","yeah, i feel that...","","","","","",""],
["","elijah","","you know, i think that was the tipping point that got me to enlist in the army.","","","","","",""],
["","you","","what, travel?","","","","","",""],
["","elijah","","yep.","","","","","",""],
["","","","that, and all my friends were doing it...","","","","","",""],
["","","","and it's not like i had any backup plans","","","","","",""],
["","","","thought i might as well get to see the world, you know?","","","","","",""],
["","you","","did you?","","","","","",""],
["","elijah","","pfft, no.","","","","","",""],
["","","","saw a bunch of army base and desert, and got slapped with a stress disorder for my troubles.","","","","","",""],
["","you","","oh, i'm sorry","","","","","",""],
["","elijah","","nah, it's fine.","","","","","",""],
["","","","i was one of the lucky ones, actually.","","","","","",""],
["","","","especially considering what was happening with global politics at the time.","","","","","",""],
["","","","never got into active combat.","","","","","",""],
["","you","","oh, good","","","","","",""],
["","elijah","","sorry.","","","","","",""],
["","","","didn't want to dampen the mood.","","","","","",""],
["","you","","nah, it's ok","","","","","",""],
["","elijah","","i went on some good travels too!","","","","","",""],
["","","","me and some friends drove up to north carolina one time.","","","","","",""],
["","you","","oh, what do they have there?","","","","","",""],
["","elijah","","some pretty awesome mountains.","","","","","",""],
["","","","sometimes i feel like i can still feel the wind up there.","","","","","",""],
["","","","oh, and a lot of nascar stuff.","","","","","",""],
["","you","","ooh, are you into racing?","","","","","",""],
["","elijah","","oh god, no, but jessica could [i]not[/i] get enough of it.","","","","","",""],
["","","","dragged us to the nascar hall of fame AND the charlotte motor speedway","","","","","",""],
["","you","","oh lol","","","","","",""],
["","elijah","","listen, if i wanted to see a bunch of white men in fancy cars, i would have stayed home and watched [i]mad max.[/i]","","","null","","",""]
]