extends Node

var raw_blocks = [
["talk_to_elijah","_none","_none","_pass","",['met_elijah', '_pronouns_she'],['elijah_default', 'es_intro', 'es_intro_alt'],"","",""],
["es_intro","???","sean_neutral","what do you know, fresh meat :P","display_sean","","es_intro2","","",""],
["es_intro1","???","sean_neutral","what do you know, fresh meat ;)","display_sean","","","","",""],
["es_intro2","you","","uh, hi","met_elijah","","","","",""],
["","","","i'm {player}","met_sean","","","","",""],
["","???","","nice to meet ya","elijah_and_sean_together","","","","",""],
["","","","i'm sean.","","","","","",""],
["","","","that lump over there is elijah","","","","","",""],
["","_none",['elijah_neutral', 'sean_neutral'],"elijah chuckles.","display_elijah_and_sean","","","","",""],
["","elijah","","hey","","","","","",""],
["","","","that lump over there has feelings, you know.","","","","","",""],
["","sean","","maybe you oughta stop acting like a lump, then :P","","","","","",""],
["","_none","","you motion at elijah's notebook.","","","","","",""],
["","you","","what are you working on?","","","","","",""],
["","elijah","","i'm trying to write a poem.","","","","","",""],
["","you","","what's it about?","","","","","",""],
["","elijah","","trees","","","","","",""],
["","you","","ah, like, what kind?","","","","","",""],
["","elijah","","the metaphysical kind.","","","","","",""],
["","you","","oh","","","","","",""],
["","","","cool","","","","","",""],
["","sean","","so, {player}...","","","","","",""],
["","","","whatcha in for?","","","","","",""],
["","you","","in for?","","","","","",""],
["","sean","","you know, why are you in purrgatory?","","","","","",""],
["","","","everyone here's got a story.","","","","","",""],
["","","","for example, elijah is here for being too lumpy","","","","","",""],
["","elijah","","what is it with you and lumpiness today, man??","","","","","",""],
["","you","","i don't think you're lumpy...","","","","","",""],
["","elijah","","thank you.","","","","","",""],
["","sean","","anyway, like i was saying...","","","","","",""],
["","","","what's your sin?","","","","","",""],
["","you","","i don't remember much about my past life.","","","","","",""],
["","","","knowing me, it was probably something like...","","","","","",""],
["","","","","","","","",['partying too much', 'annoying people to death', 'being lazy', 'shoplifting'],['es_intro_party', 'es_intro_annoy', 'es_intro_lazy', 'es_intro_shoplifting']],
["es_intro_party","you","","partying too much.","","","","","",""],
["","sean","","hehe","","","","","",""],
["","","","you and me both ;)","","","","","",""],
["","elijah","","there are worse ways to spend your time.","","","es_intro_cont","","",""],
["es_intro_annoy","you","","annoying people to death.","","","","","",""],
["","elijah","","oh, sean does that too.","","","","","",""],
["","sean","","you're already dead. how could i annoy you to death?","","","","","",""],
["","elijah","","you annoy me to, from, and during death.","","","","","",""],
["","","","maybe if you keep going you'll annoy me back to life.","","","es_intro_cont","","",""],
["es_intro_lazy","you","","being lazy.","","","","","",""],
["","elijah","","that's probably why i'm here, too.","","","","","",""],
["","","","didn't do nothing while alive.","","","","","",""],
["","","","doomed to do nothing in death.","","","","","",""],
["","sean","","aww, that's just depressing","","","es_intro_cont","","",""],
["es_intro_shoplifting","you","","shoplifting.","","","","","",""],
["","elijah","","i'll bet ya that's why sean's here.","","","","","",""],
["","sean","","what do you mean?","","","","","",""],
["","","","i'll have you know i'm a model citizen. i've never shoplifted even [i]once[/i].","","","","","",""],
["","elijah","","you sure? ","","","","","",""],
["","","","ain't never snatched a candy bar from the corner store? ","","","","","",""],
["","","","never snuck a golden watch into your pocket?","","","","","",""],
["","","","never swiped a newborn from its cradle?","","","","","",""],
["","sean","","...","","","","","",""],
["","","","nope, not that i remember!","","","es_intro_cont","","",""],
["es_intro_cont","you","","how about you, sean? why are you here?","","","","","",""],
["","sean","","oh, me?","","","","","",""],
["","","","too much sex.","","","","","",""],
["","elijah","","sean.","","","","","",""],
["","sean","","i was a freaking stud magnet, dude","","","","","",""],
["","","","getting that booty all day every day","","","","","",""],
["","elijah","","...[i]sean.[/i] ","","","","","",""],
["","sean","","so god decided to send me down here to repent","","","","","",""],
["","","","among a bunch of prudes.","","","","","",""],
["","","","like elijah.","","","","","",""],
["","elijah","","sean, don't scare off the new person.","","","","","",""],
["","","","","","","","",['it\'s not like i have anywhere else to go', '*awkward cough*'],['es_intro_go', 'es_intro_yikes']],
["es_intro_go","you","","it's okay, it's not like i have anywhere else to go.","","","","","",""],
["","sean","","see?","","","","","",""],
["","","","loosen up, elijah","","","","","",""],
["","elijah","","hmph","","","es_intro_lady","","",""],
["es_intro_yikes","you","","*cough cough*","","","","","",""],
["","sean","","eheh, anyway","","","","","",""],
["es_intro_lady","sean","","it's either that or the time i knocked over an old lady while on my bike.","","","","","",""],
["","you","","oh no!","","","","","",""],
["","sean","","nah, she was fine","","","","","",""],
["","","","probably outlived me, the lucky bastard","","","","","",""],
["","you","","oh, ok","","","","","",""],
["","elijah","","welcome to purrgatory, anyway.","","","","","",""],
["","","","for what it's worth.","","","","","",""],
["","you","","thanks.","","","null","","",""],
["elijah_default","_none","elijah_neutral","...","","","",['sean_went_to_piano and not elijah_moved_on_from_argument', 'true', 'true', 'numa_started_poem and not numa_finished_poem',  'tried_meowseum_door and not (asked_about_meowseum_door and told_code_to_sean) and not (not asked_about_meowseum_door and opened_meowseum_door)', 'true', 'true'],['what was that all about?', 'what\'s up?', 'how\'s the poetry?', '(about numa\'s poem)', '(about the meowseum door)', 'what does that word on the sign mean?', 'why do you always do that with your hands?'],['elijah_spat', 'elijah_wasup', 'elijah_hows_the_poetry', 'elijah_numa', 'elijah_meowseum', 'elijah_odontophorous', 'elijah_hands']],
["elijah_numa","you","","hey, you're pretty good at poetry, right?","","","","","",""],
["","elijah","","eh, i don't know about that.","","","","","",""],
["","you","","well, it looks like you have a lot of... experience.","","","","","",""],
["","_none","","you motion to the giant mass of crumpled papers.","","","","","",""],
["","elijah","","pfft","","","","","",""],
["","","","fair enough","","","","","",""],
["","you","","numa is trying to write a poem… maybe you could help?","","","","","",""],
["","elijah","","oh?","","","","","",""],
["","","","i'm down.","","","","","",""],
["","","","what's she need help with?","","","","","",""],
["","you","","i don't suppose you know any rhymes for \"orange\"?","","","","","",""],
["","elijah","","hmm","","","","","",""],
["","","","porridge. lozenge.","","","","","",""],
["","you","","hmmmmmm","","","","","",""],
["","elijah","","melange, maybe.","","","","","",""],
["","you","","what's that?","","","","","",""],
["","elijah","","means a mixture of things","","","","","",""],
["","","","comes from the french.","","","","","",""],
["","you","","oh, cool","","","","","",""],
["","elijah","","why is she trying to rhyme with orange?","","","","","",""],
["","","","","","","","",['she\'s writing a love poem for kyungsoon', 'i don\'t know'],['elijah_numa_love', 'elijah_numa_idk']],
["elijah_numa_love","you","","she's writing a love poem for kyungsoon","","","","","",""],
["","elijah","","oh, word?","","","","","",""],
["","","","that's funny","","","","","",""],
["","you","","what is?","","","","","",""],
["","elijah","","even after death, people still write love poems.","","","","","",""],
["","","","didn't realize she had a thing for kyungsoon","","","","","",""],
["","you","","yeah, it kind of confuses me too","","","","","",""],
["","","","anyway, don't tell her i told you this!","","","","","",""],
["","","","it's supposed to be a secret","","","","","",""],
["","elijah","","roger.","","","elijah_numa_offer","","",""],
["elijah_numa_idk","you","","ah, i don't know","","","","","",""],
["elijah_numa_offer","elijah","","might be better if i talked to her directly.","","","","","",""],
["","you","","yeah, probably","","","","","",""],
["","elijah","","alright, then","","","","","",""],
["","","","lead the way.","","","","","",""],
["","_none",['elijah_neutral', 'numa_neutral'],"you walk to the garden with elijah.",[['elijah_goto_garden', true], ['elijah_show_numa', true]],"","","","",""],
["","numa","","oh, hello…",[['elijah_and_sean_together', false]],"","","","",""],
["","elijah","","what's up.","","","","","",""],
["","you","","i recruited elijah to help you with the poem!","","","","","",""],
["","numa","","you -- you did what?!","","","","","",""],
["","","","um…","","","","","",""],
["","","","did you tell him about…","","","","","",""],
["","you","","it's okay, you can trust elijah","","","","","",""],
["","","","right?","","","","","",""],
["","elijah","","yeah, yeah, of course.","","","","","",""],
["","","","i know sharing your poetry can be hard, but i promise i won't judge.","","","","","",""],
["","","","i'm just glad someone else in purrgatory is taking an interest in poetry","","","","","",""],
["","numa","","…","","","","","",""],
["","","","ok because","","","","","",""],
["","","","i like, really need help ;;","","","","","",""],
["","elijah","","can we hear what you have so far?","","","","","",""],
["","numa","","alright, um","","","","","",""],
["","","","it's not very good","","","","","",""],
["","elijah","","no worries.","","","","","",""],
["","numa","","ahem","","","","","",""],
["","","","roses are white","","","","","",""],
["","","","violets are white","","","","","",""],
["","elijah","","pfft, strong start.","","","","","",""],
["","numa","","to me, you are","","","","","",""],
["","","","a shining light.","","","","","",""],
["","elijah","","hm…","","","","","",""],
["","","","that line could be a little punchier.","","","","","",""],
["","","","how about \"blazing\"?","","","","","",""],
["","numa","","a blazing light?","","","","","",""],
["","","","ooh, i like that!","numa_finished_poem","","","","",""],
["","_none","","seems like you should give them time to work.","elijah_working_with_numa_timer","","null","","",""],
["elijah_helping_numa","elijah",['elijah_neutral', 'numa_neutral'],"so, if you had to compare your mysterious lover to something,","","","","","",""],
["","","","what would it be?","","","","","",""],
["","numa","","hm…","","","","","",""],
["","","","i don't know…","","","","","",""],
["","elijah","","don't think about it too hard. just say the first thing that comes to mind.","","","","","",""],
["","numa","","uh, ok, a lamppost!","","","","","",""],
["","elijah","","a lamppost?","","","","","",""],
["","numa","","because she's tall, and.. bright?","","","","","",""],
["","","","i guess?","","","","","",""],
["","elijah","","alright","","","","","",""],
["","","","we can work with this","","","","","",""],
["","_none","","seems like they still need time.","","","null","","",""],
["elijah_meowseum","_none","_none","_pass","",['asked_sean_only', 'got_meowseum_passcode and asked_about_meowseum_door', 'asked_about_meowseum_door'],['elijah_meowseum_catchup', 'elijah_meowseum3', 'elijah_meowseum2', 'elijah_meowseum1'],"","",""],
["elijah_meowseum1","you","","do you know how to get into the meowseum?","","","","","",""],
["","","","there's a padlock on the door","","","","","",""],
["","elijah","","ah, that would be sean's fault.","","elijah_and_sean_together",['elijah_meowseum1a', 'elijah_meowseum1b'],"","",""],
["elijah_meowseum1a","sean",['elijah_neutral', 'sean_neutral'],"oh, yeah!","display_elijah_and_sean","","","","",""],
["","","","that's from hide-and-seek.","","","sean_hide_and_seek","","",""],
["elijah_meowseum1b","elijah","","he put it there during hide-and-seek.","asked_elijah_only","","","","",""],
["","","","","","","","",['you were playing hide-and-seek?', 'you padlocked a door while playing hide-and-seek?'],['elijah_hide_and_seek1', 'elijah_hide_and_seek2']],
["elijah_hide_and_seek1","you","","you were playing hide and seek?","","","","","",""],
["","","","aren't you two kind of old for that?","","","","","",""],
["","elijah","","hey, we're stuck in neverland.","","","","","",""],
["","","","might as well act like it.","","","elijah_hide_and_seek3","","",""],
["elijah_hide_and_seek2","you","","you padlocked a door while playing hide-and-seek?","","","","","",""],
["","elijah","","sean said he wanted to make the game \"spicier\"","","","","","",""],
["","","","...","","","","","",""],
["","","","i suppose it worked","","","","","",""],
["","","","if only because he locked natalie into the museum.","","","","","",""],
["","you","","really??","","","","","",""],
["elijah_hide_and_seek3","elijah","","anyway, i think he wrote the code down on one of my old poems","asked_about_meowseum_door","","","","",""],
["","","","should be around here somewhere.","","","","","",""],
["","","","...","","","","","",""],
["","","","hm...","","","","","",""],
["","you","","what is it?","","","","","",""],
["","elijah","","not where i thought it was","","","","","",""],
["","","","could be that he dropped it in the park when we went on a walk earlier.","","got_meowseum_passcode",['elijah_is_it_1234', 'elijah_hide_and_seek4'],"","",""],
["elijah_hide_and_seek4","","","anyway, ask him if he remembers the code","","","","","",""],
["","","","which he probably doesn't","","","","","",""],
["","","","in which case we'll just have to find the paper...","","","","","",""],
["","you","","okay, i'll take a [i]lock[/i] around!","","","","","",""],
["","elijah","","heh, good luck","","","","","",""],
["","","","i'll keep looking around here.","","","null","","",""],
["elijah_meowseum2","you","","any luck finding the passcode to the meowseum?","","","","","",""],
["","elijah","","nope, lady luck has not visited us today.","","","","","",""],
["elijah_lady_luck","","","but also, there's like, a million papers in here","","","","","",""],
["","","","so i wouldn't hedge my bets.","","","","","",""],
["","you","","lol right","","elijah_and_sean_together",['elijah_lady_luck1', 'elijah_lady_luck2'],"","",""],
["elijah_lady_luck1","sean",['elijah_neutral', 'sean_neutral'],"i bet it's in the park","display_elijah_and_sean","","","","",""],
["","","","you should take a look around there","","","","","",""],
["","elijah","","if you have the time, that is.","","","","","",""],
["","sean","","of course {they} {have/has} the time. it's purrgatory.","","","","","",""],
["","elijah","","hey, being polite ain't never hurt anyone.","","","null","","",""],
["elijah_lady_luck2","elijah","","you should take a look around the park.","","","","","",""],
["","","","i bet he dropped it there earlier.","","","","","",""],
["","you","","alrighty","","","null","","",""],
["elijah_meowseum3","you","","so, uh","","","","","",""],
["","","","i think i found the passcode to the meowseum","","","","","",""],
["","elijah","","oh, did you?","","","elijah_is_it_1234_1","","",""],
["elijah_is_it_1234","you","","oh, i think i saw it earlier!","","","","","",""],
["elijah_is_it_1234_1","you","","is it 1234?","","elijah_and_sean_together",['elijah_is_it_1234_2', 'elijah_is_it_1234_3'],"","",""],
["elijah_is_it_1234_2","sean",['elijah_neutral', 'sean_neutral'],"YEAH THAT'S IT!","display_elijah_and_sean","","sean_ronnie_wood","","",""],
["elijah_is_it_1234_3","elijah","","1234?","","","","","",""],
["","","","pfft","","","","","",""],
["","","","knowing sean, that's probably it.","","","","","",""],
["","you","","great.","","","null","","",""],
["elijah_meowseum_catchup","you","","hey, sean said that he wrote the passcode to the meowseum on one of your poems",[['asked_sean_only', false]],"","","","",""],
["","","","do you know where it is?","","","","","",""],
["","elijah","","i thought he had it?","","","","","",""],
["","you","","i guess he lost it...?","","","","","",""],
["","elijah","","pfft","","","","","",""],
["","","","figures","","","","","",""],
["","","","i'll take a look around, but i don't really know where it could be.","","","","","",""],
["","you","","ah, alright, thanks.","","","null","","",""],
["elijah_wasup","you","elijah_neutral","what's up?","","",['_rand', 'elijah_wasup1', 'elijah_wasup2', 'elijah_wasup3', 'elijah_wasup4', 'elijah_wasup5', 'elijah_wasup6', 'elijah_wasup7', 'elijah_wasup8', 'elijah_wasup9', 'elijah_wasup10', 'elijah_wasup11', 'elijah_wasup12', 'elijah_wasup13', 'elijah_wasup14', 'elijah_wasup15', 'elijah_wasup16', 'elijah_wasup17', 'elijah_wasup18', 'elijah_wasup19', 'elijah_wasup20'],"","",""],
["elijah_wasup1","elijah","","just poetry","","","","","",""],
["","you","","cool, cool.","","","null","","",""],
["elijah_wasup2","elijah","","wondering if we'll ever run out of paper.","","","","","",""],
["","you","","well, it looks like your bookshelf is running pretty low...","","","","","",""],
["","elijah","","oh, that's just the most recent batch","","","","","",""],
["","","","there's a storage crate in the warehouse just full of 'em.","","","","","",""],
["","you","","wow","","","null","","",""],
["elijah_wasup3","elijah","","oh, you know. writing words. ","","","","","",""],
["","","","wording rights.","","","","","",""],
["","","","righting wrongs and writing wrong words.","","","","","",""],
["","you","","cool!","","","null","","",""],
["elijah_wasup4","you","","you look like you're in pain :c","","","","","",""],
["","elijah","","hand is... cramping...","","","","","",""],
["","you","","well, at least you're [i]hand[/i]-ling it pretty well!","","","","","",""],
["","elijah","","ha... ha...","","","null","","",""],
["elijah_wasup5","elijah","","thought i saw a spider earlier","","","","","",""],
["","you","","oh no","","","","","",""],
["","elijah","","...but it was just a weird eraser shaving.","","","","","",""],
["","you","","oh, thank god","","","","","",""],
["","","","i HATE spiders","","","","","",""],
["","elijah","","why the ire for our 8-legged homies?","","","","","",""],
["","you","","they're not MY homies ):<","","elijah_and_sean_together",['elijah_wasup5a', 'elijah_wasup5b'],"","",""],
["elijah_wasup5a","sean",['elijah_neutral', 'sean_neutral'],"i'm on {player}'s side. spiders don't have rights.","display_elijah_and_sean","","","","",""],
["elijah_wasup5b","elijah","","if you say so.","","","null","","",""],
["elijah_wasup6","elijah","","man, i wish i could eat cheerios again.","","","","","",""],
["","you","","me too, cereal is yummy","","","","","",""],
["","elijah","","mhm","","","","","",""],
["","","","was the only thing worth getting out of bed for, some days.","","","","","",""],
["","you","","oh ):","","","null","","",""],
["elijah_wasup7","elijah","","i don't know","","","","","",""],
["","","","is anything ever up?","","","","","",""],
["","you","","wow, i never thought of it that way before...","","","null","","",""],
["elijah_wasup8","elijah","","workin on a poem","","","","","",""],
["","","","what do you think of the phrase \"everywhere the triumph of the mediocre\"?","","","","","",""],
["","you","","oh, that's pretty good!!","","","","","",""],
["","","","did you write that?","","","","","",""],
["","elijah","","nope","","","","","",""],
["","you","","oh","","","","","",""],
["","elijah","","it was some frenchman","","","","","",""],
["","","","can't remember the name anymore.","","elijah_and_sean_together",['elijah_wasup8a', 'elijah_wasup8b'],"","",""],
["elijah_wasup8a","you","","ah, i see","","","null","","",""],
["elijah_wasup8b","sean",['elijah_neutral', 'sean_neutral'],"i call bullshit","display_elijah_and_sean","","","","",""],
["","","","i was mediocre my whole life, and [i]i[/i] died in a 7-eleven.","","","","","",""],
["","elijah","","pfft","","","","","",""],
["","","","point taken.","","","","","",""],
["","you","","i'm sure you weren't mediocre at [i]everything[/i]","","","","","",""],
["","sean","","that's true","","","","","",""],
["","","","i was pretty good at lovin' ;)","","","","","",""],
["","you","","ooh ;)","","","null","","",""],
["elijah_wasup9","elijah","","not much.","","","","","",""],
["","","","what's up with you?","","","","","",""],
["","you","","not much also.","","","null","","",""],
["elijah_wasup10","elijah","","i was wondering","","","","","",""],
["","","","is twerking still a thing?","","","","","",""],
["","you","","um, i guess?","","","","","",""],
["","","","why... do you ask?","","","","","",""],
["","elijah","","because ","","","","","",""],
["","","","visions of miley cyrus's undulating bottom plagued my final waking hours","","","","","",""],
["","","","and it haunts me to this day","","","","","",""],
["","you","","jesus christ","","","null","","",""],
["elijah_wasup11","elijah","","thinking about that one robert frost poem.","","","","","",""],
["","you","","what about it?","","","","","",""],
["","elijah","","when he said \"i have miles to go before i sleep\"?","","","","","",""],
["","","","i really felt that","","","null","","",""],
["elijah_wasup12","elijah","","what do you think of the word \"sepulchre\"?","","","","","",""],
["","you","","uh, what does it mean?","","","","","",""],
["","elijah","","i don't know","","","","","",""],
["","","","i never found out","","","","","",""],
["","you","","hm","","","","","",""],
["","","","well, it's a pretty cool sounding word.","","","","","",""],
["","elijah","","sure is.","","","null","","",""],
["elijah_wasup13","elijah","","what do you think of the word \"rustic\"?","","","","","",""],
["","you","","hmm","","","","","",""],
["","","","it's kinda rude, i guess","","","","","",""],
["","elijah","","hmmmmm","","","","","",""],
["","","","maybe you're right.","","","null","","",""],
["elijah_wasup14","elijah","","what do you think of the word \"grimy\"?","","","","","",""],
["","you","","uhhh","","","","","",""],
["","","","you can [i]grimy[/i] a river?","","","","","",""],
["","elijah","","...","","","","","",""],
["","","","heh, that was a good one","","","","","",""],
["","you","","thanks!","","","null","","",""],
["elijah_wasup15","elijah","","did you ever read the pit and the pendulum?","","","","","",""],
["","you","","i don't think so, why do you ask?","","","","","",""],
["","elijah","","cus that shit was wack, man","","","null","","",""],
["elijah_wasup16","elijah","","did you ever read hamlet?","","","","","",""],
["","you","","uh, nope","","","","","",""],
["","elijah","","me neither.","","","","","",""],
["","you","","oh","","","","","",""],
["","","","you think we missed out on much?","","","","","",""],
["","elijah","","probably not.","","","null","","",""],
["elijah_wasup17","elijah","","wish i could have played tennis while i was alive.","","","","","",""],
["","you","","oh really?","","","","","",""],
["","elijah","","yeah, always thought it looked fun","","","","","",""],
["","","","should have tried it at least once.","","","","","",""],
["","you","","you could have been an olympic champion and we'll never know!","","","","","",""],
["","elijah","","hah","","","","","",""],
["","","","that's a good one.","","","null","","",""],
["elijah_wasup18","elijah","","did you know you don't have to breathe in purrgatory?","","","","","",""],
["","you","","what?","","","","","",""],
["","elijah","","it always freaks out newcomers.","","","","","",""],
["","","","try it.","","","","","",""],
["","you","","um, okay.","","","","","",""],
["","","","...","","","","","",""],
["","elijah","","...","","","","","",""],
["","you","","...","","","","","",""],
["","elijah","","...","","","","","",""],
["","you","","...","","","","","",""],
["","elijah","","...","","","","","",""],
["","you","","that's freaky.","","","","","",""],
["","elijah","","told you so.","","","null","","",""],
["elijah_wasup19","elijah","","writer's block.","","","","","",""],
["","you","","you do look sort of [i]pen[/i]-sive.","","","","","",""],
["","elijah","","pfft.","","","null","","",""],
["elijah_wasup20","elijah","","nothing.","","","","","",""],
["","you","","yep, sounds about right.","","","null","","",""],
["elijah_hows_the_poetry","you","","how's the poetry going?","","","","","",""],
["","elijah","","same as usual, i suppose.","","sean_went_to_piano",['elijah_hows_the_poetry2', 'elijah_hows_the_poetry1'],"","",""],
["elijah_hows_the_poetry1","you","","does that mean... good? or bad?","","","","","",""],
["","elijah","","bad.","","","","","",""],
["","_none","","elijah sighs and throws another crumpled paper onto the pile.","","","","","",""],
["elijah_hows_the_poetry2","","","","","","",['true', 'true', 'not elijah_suggested_found_poetry', 'elijah_suggested_found_poetry'],['did you write in real life?', 'what\'s all this on the floor?', 'can i hear some of it?', 'let\'s write some poetry!'],['elijah_real_life', 'elijah_floor', 'elijah_hear_poetry', 'elijah_found']],
["elijah_real_life","you","","were you a writer in real life, too?","","","","","",""],
["","elijah","","ha. not much of one.","","","","","",""],
["","","","but yeah, i did write.","","","","","",""],
["","you","","that's pretty cool","","","","","",""],
["","","","how did you get started?","","","","","",""],
["","elijah","","joined a club in college.","","","","","",""],
["","you","","ooh, fun","","","","","",""],
["","elijah","","yep, warner robins poetry slam, that's what we called ourselves","","","","","",""],
["","","","though we never got enough people to put on a slam","","","","","",""],
["","you","","oh lol","","","","","",""],
["","elijah","","yeah, it was a pretty low-key thing","","","","","",""],
["","you","","i'm guessing you're the one who put up the \"purrgatory poetry slam\" banner, then?","","","","","",""],
["","elijah","","ah... yeah. that would be me","","","","","",""],
["","you","","how did that go?","","","","","",""],
["","elijah","","well... uh... how do i put this politely...","","elijah_and_sean_together",['elijah_real_life1', 'elijah_real_life2'],"","",""],
["elijah_real_life1","sean",['elijah_neutral', 'sean_neutral'],"it was total dog shit?","display_elijah_and_sean","","","","",""],
["","elijah","","...not my first choice of words.","","","","","",""],
["","sean","","well it [i]was[/i]. no one showed up.","","","","","",""],
["","","","(except me)","","","","","",""],
["","elijah","","yes, i enjoyed your poem \"there's no toilets in purrgatory\" very much.","","","","","",""],
["","sean","","some of my best work :P","","","","","",""],
["","you","","lol","","","","","",""],
["","elijah","","do you write much, {player}?","","","elijah_real_life3","","",""],
["elijah_real_life2","elijah","","it was a total bust.","","","","","",""],
["","","","no one showed up, except for sean.","","","","","",""],
["","you","","aw, damn","","","","","",""],
["","","","better luck next time?","","","","","",""],
["","elijah","","i suppose.","","","","","",""],
["","you","","i mean, no one took the sign down","","","","","",""],
["","","","so if you think about it, the slam is still going right now.","","","","","",""],
["","elijah","","that's definitely one way of looking at it.","","","","","",""],
["","","","how about you, do you write much?","","","","","",""],
["elijah_real_life3","","","","","","","",['yeah!', 'no'],['elijah_real_life4', 'elijah_real_life5']],
["elijah_real_life4","you","","yeah!","","","","","",""],
["","","","nothing serious, but i used to","","","","","",""],
["","","","i guess i fell out of the habit","","","","","",""],
["","elijah","","and out of the world?","","","","","",""],
["","you","","lol, yeah, and that.","","","","","",""],
["","elijah","","well, you have plenty of time to pick it up again.","","","","","",""],
["","you","","that's true","","","","","",""],
["","","","maybe i should!","","","null","","",""],
["elijah_real_life5","you","","not really","","","","","",""],
["","","","words aren't really my strong suit.","","","","","",""],
["","elijah","","well, you seem pretty good at wordplay","","","","","",""],
["","you","","that's different!","","","","","",""],
["","","","i can't just write a bunch of puns and call that a poem.","","","","","",""],
["","elijah","","why not?","","","","","",""],
["","","","a poem can be anything you want, man","","","","","",""],
["","you","","hmm...","","","","","",""],
["","","","maybe you're [i]write[/i]!","","","null","","",""],
["elijah_floor","you","","so, what's all this on the floor?","","","","","",""],
["","","","it's not all poems, is it?","","","","","",""],
["","elijah","","fraid so.","","","","","",""],
["","you","","why do you throw them all away??","","elijah_and_sean_together",['elijah_floor1', 'elijah_floor2'],"","",""],
["elijah_floor1","sean",['elijah_neutral', 'sean_neutral'],"that's what i always say!","display_elijah_and_sean","","","","",""],
["","","","and then [i]he's[/i] always like...","","","","","",""],
["","elijah","","they're just not very good.","","","","","",""],
["","sean","","they're totally fine!","","","","","",""],
["","elijah","","but you haven't read any of them!","","","","","",""],
["","sean","","yes, because you won't [i]let[/i] me read any of them!!","","","","","",""],
["","","","ugh","","","","","",""],
["","","","{player}, do you see what i've been dealing with?","","","","","",""],
["","you","","umm, yeah, i guess","","","","","",""],
["","elijah","","one of these days, i'll stumble upon the perfect words in the perfect order","","","","","",""],
["","","","until then, i am cursed to discard vapid pages for eternity.","","","","","",""],
["","sean","","you're really not","","","","","",""],
["","elijah","","yes i am","","","","","",""],
["","","","i am cursed","","","","","",""],
["","sean","","you are doing this to YOURSELF","","","","","",""],
["","elijah","","it is beyond my authority","","","","","",""],
["","sean","","ARGH","","","null","","",""],
["elijah_floor2","elijah","","they're just not very good.","","","","","",""],
["","you","","wow","","","","","",""],
["","","","all of them?","","","","","",""],
["","elijah","","one of these days, i'll stumble upon the perfect words in the perfect order","","","","","",""],
["","","","until then, i am cursed to discard vapid pages for eternity.","","","","","",""],
["","you","","damn","","","null","","",""],
["elijah_odontophorous","you","","what does the word on that sign mean?","","","","","",""],
["","elijah","","no clue.","","","","","",""],
["","","","my working theory is that it's a type of bug.","","","","","",""],
["","","","what do you think?","","","","","",""],
["","you","","hmm","","","","","",""],
["","","","","","","","",['something that smells really bad', 'something that\'s yellowish-white', 'something that\'s part of a tooth', 'someone who\'s a suck-up'],['elijah_odontophorous1', 'elijah_odontophorous2', 'elijah_odontophorous3', 'elijah_odontophorous4']],
["elijah_odontophorous1","you","","something that smells really bad ","","","elijah_odontophorous5","","",""],
["elijah_odontophorous2","you","","something that's yellowish-white","","","elijah_odontophorous5","","",""],
["elijah_odontophorous3","you","","something that's part of the tooth","","","elijah_odontophorous5","","",""],
["elijah_odontophorous4","you","","someone who's a suck-up","","","","","",""],
["elijah_odontophorous5","elijah","","could be.","","","","","",""],
["","you","","but wait","","","","","",""],
["","","","why did you frame a word that you don't know?","","","","","",""],
["","elijah","","[i]i[/i] didn't put it up there. it was there when i got here.","","","","","",""],
["","you","","oh, weird","","elijah_and_sean_together",['elijah_odontophorous6', 'null'],"","",""],
["elijah_odontophorous6","sean",['elijah_neutral', 'sean_neutral'],"my theory is that satan was having a little laugh and decided to use the only word that elijah doesn't know.","display_elijah_and_sean","","","","",""],
["","elijah","","you trippin, man. there are plenty of words i don't know.","","","","","",""],
["","","","have you heard one of oliver's lectures? he talks circles around me.","","","","","",""],
["","sean","","yeah, once","","","","","",""],
["","","","i feel asleep at \"denominator.\"","","","","","",""],
["","elijah","","that's... not even a hard word","","","","","",""],
["","sean","","well no need to rub it in ):<","","","null","","",""],
["elijah_hands","you","","i hope this isn't rude, but","","","","","",""],
["","","","why do you always do that with your hands?","","","","","",""],
["","elijah","","you mean folding them like this?","","","","","",""],
["","you","","yeah, that.","","","","","",""],
["","elijah","","oh, it's just that sean is too cute.","","","","","",""],
["","","","around him, my hands flutter like they have a mind of their own.","","","","","",""],
["","you","","wait. really??","","elijah_and_sean_together",['elijah_hands1', 'elijah_hands2'],"","",""],
["elijah_hands1","sean",['elijah_neutral', 'sean_neutral'],"pfffffffffffffft, yeah right.","display_elijah_and_sean","","","","",""],
["elijah_hands2","elijah","","nah, i'm just pulling your leg. ","","","","","",""],
["","","","i'm a pangolin. this is my default position.","","","","","",""],
["","you","","oh","","","null","","",""],
["elijah_hear_poetry","_none","_none","_pass","","sean_went_to_piano",['elijah_hear_more_poetry', 'elijah_hear_poetry0'],"","",""],
["elijah_hear_poetry0","you","","can i hear some of it?","","","","","",""],
["","elijah","","oh, i don't know about that.","","","","","",""],
["","","","it's sort of a work in progress, you know?","","","","","",""],
["","you","","maybe i can help you out!","","","","","",""],
["","","","do you need some inspiration?","","","","","",""],
["","elijah","","nah, don't worry about it, man.","","","","","",""],
["","","","preciate it, though.","","","","","",""],
["","","","","","","","",['push it', 'let it go'],['elijah_hear_poetry2', 'elijah_hear_poetry1']],
["elijah_hear_poetry1","you","","alrighty, if you say so.","","","null","","",""],
["elijah_hear_poetry2","you","","come on i promise i won't judge!!","","","","","",""],
["","","","i'm just curious. and it can't be worse than [i]my[/i] writing skills","","","","","",""],
["","sean",['elijah_neutral', 'sean_neutral'],"don't bother. i've been trying to hear his poetry for ages.","display_elijah_and_sean","","","","",""],
["","elijah","","well...","","","","","",""],
["","","","i have been thinking that some feedback would be... constructive","","","","","",""],
["","sean","","really??","","","","","",""],
["","","","so you'll show {them} but you won't show me? ):","","","","","",""],
["","elijah","","no, no, this is one that you've seen before","","","","","",""],
["","sean","","oh the tree one?","","","","","",""],
["","elijah","","yes, the tree one.","","","","","",""],
["","","","i just thought... maybe a fresh perspective would help?","","","","","",""],
["","","","i'll read you what i have, but there's a couple of holes","","","","","",""],
["","","","so i could maybe use some... suggestions? if you don't mind?","","","","","",""],
["","","","","","","","",['sure!', 'maybe later'],['elijah_hear_poetry4', 'elijah_hear_poetry3']],
["elijah_hear_poetry3","you","","actually... maybe later, sorry","","","","","",""],
["","","","there's some other stuff i want to get to...","","","","","",""],
["","elijah","","oh.","","","","","",""],
["","","","well. ","","","","","",""],
["","","","take your time, i guess.","","","","","",""],
["","you","","sorry...","","","","","",""],
["","elijah","","'sokay.","","","null","","",""],
["elijah_hear_poetry4","you","elijah_neutral","sure let's do it!","display_elijah","","","","",""],
["","elijah","","alright! ","","","","","",""],
["","","","well...","","","","","",""],
["","_none","","elijah locates a mostly-uncrumpled paper on the desk.","","","","","",""],
["","elijah","","it goes something like","","","","","",""],
["","","","...","","","","","",""],
["","","","i wander through the forest","","","","","",""],
["","","","repulsively","","","","","",""],
["","","","leaving my blasphemous tracks","","","","","",""],
["","","","looking for...","","","","","",""],
["","_none","","elijah pauses.","","","","","",""],
["","elijah","","uh, dunno how to end that sentence.","","","","","",""],
["","","","what do you think?","","","","","",""],
["","you","","uhhh","","","","","",""],
["","","","","","","","",['salvation', 'the way out', 'a friend', 'blueberries'],['elijah_wander1a', 'elijah_wander1b', 'elijah_wander1c', 'elijah_wander1d']],
["elijah_wander1a","you","","salvation?","","","","","",""],
["","elijah","","hm...","","","","","",""],
["","","","looking for salvation.","","","","","",""],
["","you","","yep","","","","","",""],
["","elijah","","that's not bad.","","","","","",""],
["","_none","","elijah scribble something down.","","","elijah_wander2","","",""],
["elijah_wander1b","you","","the way out?","","","","","",""],
["","elijah","","hm...","","","","","",""],
["","","","looking for the way out.","","","","","",""],
["","you","","you know. since you're lost in a forest.","","","","","",""],
["","elijah","","yeah, makes sense.","","","elijah_wander2","","",""],
["elijah_wander1c","you","","a friend?","","","","","",""],
["","elijah","","hm...","","","","","",""],
["","","","looking for a friend.","","","","","",""],
["","you","","you can always use a friend!","","","","","",""],
["","elijah","","true enough","","","elijah_wander2","","",""],
["elijah_wander1d","you","","blueberries?","","","","","",""],
["","elijah","","...blueberries?","","","","","",""],
["","you","","i don't know","","","","","",""],
["","","","maybe you went to the forest to get blueberries?","","","","","",""],
["","elijah","","pfft","","","","","",""],
["","","","could be","","","","","",""],
["elijah_wander2","elijah","","anyway, the next stanza goes like this","","","","","",""],
["","","","...","","","","","",""],
["","","","the dead tree still grows","","","","","",""],
["","","","painfully","","","","","",""],
["","","","bark cracking","","","","","",""],
["","","","branches splitting into...","","","","","",""],
["","_none","","elijah pauses again.","","","","","",""],
["","","","","","","","",['nothing', 'blossoms', 'dust', 'more branches'],['elijah_wander2a', 'elijah_wander2b', 'elijah_wander2c', 'elijah_wander2d']],
["elijah_wander2a","you","","nothing?","","","","","",""],
["","elijah","","branches splitting into nothing?","","","","","",""],
["","you","","yep yep","","","","","",""],
["","elijah","","hmmmmmmm","","","","","",""],
["","","","it's fitting, in a way.","","","elijah_wander3","","",""],
["elijah_wander2b","you","","blossoms?","","","","","",""],
["","elijah","","branches splitting into blossoms?","","","","","",""],
["","you","","yeah!","","","","","",""],
["","","","like the tree is dead, but it's still growing and blooming.","","","","","",""],
["","elijah","","i see.","","","elijah_wander3","","",""],
["elijah_wander2c","you","","dust?","","","","","",""],
["","elijah","","branches splitting into dust?","","","","","",""],
["","","","hey, that has quite a ring to it!","","","","","",""],
["","you","","right?","","","","","",""],
["","_none","","elijah makes a note on his paper.","","","elijah_wander3","","",""],
["elijah_wander2d","you","","more branches?","","","","","",""],
["","elijah","","branches splitting into... more branches?","","","","","",""],
["","you","","yeah","","","","","",""],
["","","","i mean, that's how trees work","","","","","",""],
["","elijah","","well, you're not wrong.","","","","","",""],
["elijah_wander3","elijah","","ahem. so, moving on","","","","","",""],
["","","","...","","","","","",""],
["","","","the bird in the nest","","","","","",""],
["","","","meets my eyes","","","","","",""],
["","","","blissfully","","","","","",""],
["","","","...","","","","","",""],
["","","","it says ","","","","","",""],
["","","","you lost your way","","","","","",""],
["","","","a long time ago","","","","","",""],
["","","","the only thing left ","","","","","",""],
["","","","is to...","","","","","",""],
["","_none","","elijah pauses one more time.","","","","","",""],
["","","","","","","","",['start over', 'give up', 'move on', 'use google maps'],['elijah_wander3a', 'elijah_wander3b', 'elijah_wander3c', 'elijah_wander3d']],
["elijah_wander3a","you","","start over.","","","","","",""],
["","elijah","","the only thing left is to start over.","","","","","",""],
["","you","","right?","","","","","",""],
["","","","if you lose your way, you can't give up.","","","","","",""],
["","","","you just have to start from the beginning and hope for the best.","","","","","",""],
["","elijah","","hm","","","","","",""],
["","","","that's not what i was thinking, but","","","","","",""],
["","","","well, maybe you're right.","","","elijah_wander4","","",""],
["elijah_wander3b","you","","give up.","","","","","",""],
["","elijah","","the only thing left is to give up.","","","","","",""],
["","you","","i mean","","","","","",""],
["","","","that's what the poem is implying, right?","","","","","",""],
["","","","\"leaving blasphemous tracks\" or whatever","","","","","",""],
["","","","i don't know","","","","","",""],
["","elijah","","no, you're right","","","","","",""],
["","","","it is a pretty depressing poem","","","elijah_wander4","","",""],
["elijah_wander3c","you","","move on.","","","","","",""],
["","elijah","","the only thing left is to move on.","","","","","",""],
["","you","","i think the wanderer is clinging to the past","","","","","",""],
["","","","that's what the tree represents, right?","","","","","",""],
["","","","like, it died a long time ago, but it refuses to accept it","","","","","",""],
["","","","so um","","","","","",""],
["","","","what's left is to come to terms with it and move on","","","","","",""],
["","elijah","","hmm","","","","","",""],
["","","","never thought of it that way before.","","","elijah_wander4","","",""],
["elijah_wander3d","you","","use google maps!","elijah_google_maps","","","","",""],
["","elijah","","huh?","","","","","",""],
["","you","","the only thing left is to use google maps.","","","","","",""],
["","","","that's my answer and i'm sticking to it","","","","","",""],
["","elijah","","heh","","","","","",""],
["","","","heheheheh","","","","","",""],
["","","","why didn't i think of that earlier?","","","","","",""],
["elijah_wander4","_none","","elijah looks at the paper for a few seconds, then puts it away.","","","","","",""],
["","elijah","","well, i don't know if that's exactly what i wanted.","","","","","",""],
["","","","but it was enlightening anyway.","","","","","",""],
["","","","thanks.","","","","","",""],
["","you","","you're welcome!","","","","","",""],
["","","","the poem was good!!","","","","","",""],
["","elijah","","was it?","","","","","",""],
["","sean",['elijah_neutral', 'sean_neutral'],"your poem is fine dude!","display_elijah_and_sean","elijah_google_maps",['elijah_wander4a', 'elijah_wander4b'],"","",""],
["elijah_wander4a","","","i liked google maps, you should keep that","","","","","",""],
["","elijah","","heh, i'll think about it","","","","","",""],
["elijah_wander4b","sean","","listen","","","","","",""],
["","","","real talk","","","","","",""],
["","","","you're lucky you found your passion before u died","","","","","",""],
["","elijah","","not that it helped me much...","","","","","",""],
["","sean","","that passion comes through in your writing, that's all that matters!","","","","","",""],
["","","","dude, you're such a downer.","","","","","",""],
["","","","i would have [i]killed[/i] for a talent like that","","","","","",""],
["","elijah","","pffft","","","","","",""],
["","","","trust me, it's not all that it's cracked up to be.","","","","","",""],
["","","","besides, i'm sure you had some sort of talent.","","","","","",""],
["","sean","","i meeeean","","","","","",""],
["","","","i tried learning to play music but i was always ass at it","","","","","",""],
["","","","all i really did was fuck around, you know?","","","","","",""],
["","","","i never accomplished shit.","","","","","",""],
["","elijah","","who cares, man?","","","","","",""],
["","","","is enjoying life not good enough for you?","","","","","",""],
["","sean","","uh, no? i guess?","","","","","",""],
["","elijah","","what about dani, were they enough for you?","","","","","",""],
["","you","","uh... guys?","","","","","",""],
["","sean","","of course dani was enough!","","","","","",""],
["","","","[i]is[/i] enough","","","","","",""],
["","","","that's not the issue!!","","","","","",""],
["","elijah","","i don't know what i'm trying to say.","","","","","",""],
["","","","i just think ","","","","","",""],
["","","","you should appreciate what you had.","","","","","",""],
["","","","you had it easy, man.","","","","","",""],
["","you","","guys i think--","","","","","",""],
["","sean","","you think i had it easy??","","","","","",""],
["","","","do you [i]know[/i] how hard it is to grow up gay in a town of 4000 people?","","","","","",""],
["","elijah","","no, i guess not.","","","","","",""],
["","sean","","...","","","","","",""],
["","","","whatever, man","","","","","",""],
["","","","sorry i brought it up","","","","","",""],
["","_none","","elijah shrugs.","","","","","",""],
["","sean","","...","","","","","",""],
["","","","hey, i think i'm gonna go","","","","","",""],
["","","","i'll be at the piano if u wanna chat, {player}","","","","","",""],
["","you","","alright!","","","","","",""],
["","sean","","seeya","","","","","",""],
["","elijah","","cya","","","","","",""],
["","","elijah_neutral","...",[['elijah_and_sean_together', false]],"","","","",""],
["","you","","...","sean_went_to_piano","","null","","",""],
["elijah_spat","you","","what was that all about? with sean?","elijah_moved_on_from_argument","","","","",""],
["","","","um, if you don't mind me asking","","","","","",""],
["","elijah","","nothing, really.","","","","","",""],
["","","","i think... we could both work on our communication skills.","","","","","",""],
["","","","sorry you had to see that.","","","","","",""],
["","you","","it's ok","","","","","",""],
["","","","though i think...","","","","","",""],
["","","","","","","","",['you had a point', 'you were kind of harsh'],['elijah_spat1', 'elijah_spat2']],
["elijah_spat1","you","","you had a point","","","","","",""],
["","","","it's too late to regret what we didn't have.","","","","","",""],
["","","","we might as well appreciate what we [i]did,[/i] right?","","","","","",""],
["","elijah","","yeah, that's what i mean!","","","","","",""],
["","","","though i think i could have said it a little better. hah.","","","","","",""],
["","you","","yeah","","","","","",""],
["","elijah","","...","","","","","",""],
["","","","i mean, come on.","","","","","",""],
["","","","he had charisma, confidence","","","","","",""],
["","","","a loving partner","","","","","",""],
["","","","...a flawless body","","","","","",""],
["","","","don't tell him i said that.","","","","","",""],
["","you","","lol, i won't","","","","","",""],
["","elijah","","man, if i had half of what he...","","","","","",""],
["","","","...","","","","","",""],
["","","","i don't know. you didn't come here to hear me air my laundry.","","","elijah_spat3","","",""],
["elijah_spat2","you","","you were... kinda harsh.","","","","","",""],
["","","","i think he just wanted you to feel better about your writing.","","","","","",""],
["","elijah","","i think","","","","","",""],
["","","","you're probably right.","","","","","",""],
["","you","","sorry","","","","","",""],
["","elijah","","nah. my bad.","","","","","",""],
["","","","but...","","","","","",""],
["","","","...","","","","","",""],
["","","","i mean, how am i supposed to feel?","","","","","",""],
["","","","he's over here putting himself down when he had everything i...","","","","","",""],
["","","","i mean, he had charisma, confidence","","","","","",""],
["","","","a loving partner","","","","","",""],
["","","","...a flawless body","","","","","",""],
["","","","don't tell him i said that.","","","","","",""],
["","you","","lol, i won't","","","","","",""],
["","elijah","","[i]sigh[/i]","","","","","",""],
["","","","i'm just making excuses for being a bad friend.","","","","","",""],
["","","","you didn't come here to hear me air my laundry.","","","","","",""],
["elijah_spat3","you","","it's ok, i don't mind!","","","","","",""],
["","elijah","","still.","","","","","",""],
["","","","let's talk about something else","","","","","",""],
["","you","","okay, like what?","","","","","",""],
["","elijah","","um","","","","","",""],
["","","","...","","","","","",""],
["","you","","...","","","","","",""],
["","elijah","","[i]sigh[/i]","","","","","",""],
["","","","i don't know","","","","","",""],
["","","","i think","","","","","",""],
["","","","i'm just going to take a nap.","","","","","",""],
["","you","","oh, alright","","","","","",""],
["","","","have a nice sleepy!","","","","","",""],
["","elijah","","thanks","","","null","","",""],
["elijah_hear_more_poetry","you","","can i hear more poetry maybe?","","","","","",""],
["","","","the tree one was really good","","","","","",""],
["","elijah","","appreciate it.","","","","","",""],
["","","","hmm...","","","","","",""],
["","_none","","elijah uncrumples a piece of paper from the floor.","","","","","",""],
["","elijah","","oh, i remember this one.","","","","","",""],
["","","","this is from my \"blue period.\"","","","","","",""],
["","you","","like picasso?","","","","","",""],
["","elijah","","huh?","","","","","",""],
["","","","no, i just used a blue pen.","","","","","",""],
["","you","","oh","","","","","",""],
["","_none","","elijah tosses it back onto the pile.","","","","","",""],
["","elijah","","i think...","","","","","",""],
["","","","i'm not really in the mood right now.","","","","","",""],
["","","","maybe later?","","","","","",""],
["","you","","ok, that's cool","","","null","","",""]
]