extends Node

var raw_blocks = [
["lucifur_meeting","_none","_none","you enter the library and find lucifur sitting at a table.","_goto_library_lucifur","","","","",""],
["","lucifur","","well, well, well.",[['player_called', false]],"","","","",""],
["","","","look who the cat dragged in :3",[['waiting', false]],"","","","",""],
["","","","","","","","",['you called me in here...', 'do your worst, lucifur!', 'it me'],['lucifur_meeting1', 'lucifur_meeting2', 'lucifur_meeting3']],
["lucifur_meeting1","you","","you're the one who called me in here...","","","","","",""],
["","lucifur","","yes, i am the cat in this scenario, and you are the one that i dragged in.","","","","","",""],
["","","","do try to keep up, would you?","","","lucifur_meeting4","","",""],
["lucifur_meeting2","you","","do your worst, lucifur!","","","","","",""],
["","","","i'm ready for anything!","","","","","",""],
["","lucifur","","raring to go, eh?","","","","","",""],
["","","","good, because we have a lot of paperwork to get through.","","","lucifur_meeting4","","",""],
["lucifur_meeting3","you","","it me","","","","","",""],
["","lucifur","","un-fur-tunately, yes.","","","lucifur_meeting4","","",""],
["lucifur_meeting4","_none","","lucifur pulls a folder out of nowhere and starts riffling through it.","","","","","",""],
["","lucifur","","let's take a look at your files, why don't we?","","","","","",""],
["","","","hm....","","","","","",""],
["","","","interesting, very interesting...","","","","","",""],
["","you","","um, what does it say?","","","","","",""],
["","lucifur","","do you want the good news or the bad news?","","","","","",""],
["","","","","","","","",['good news', 'bad news'],['lucifur_meeting4a', 'lucifur_meeting4b']],
["lucifur_meeting4b","you","","the bad news?","","","","","",""],
["","lucifur","","well, let's see....","","","","","",""],
["","_none","","lucifur shuffles through the papers.","","","","","",""],
["","lucifur","","ah. littering. tisk tisk.","","","","","",""],
["","you","","what? when?","","","","","",""],
["","lucifur","","tuesday, june 13th, 2017","","","","","",""],
["","","","oh, yeah. that doesn't look good on your record at all.","","","","","",""],
["","","","beelzebub's gonna have a field day with this one.","","","","","",""],
["","you","","wait, really?","","","","","",""],
["","","","is littering really that bad??","","","","","",""],
["","lucifur","","...nah, i'm just messing with you!","","","","","",""],
["","","","hah, i crack myself up sometimes.","","","","","",""],
["","you","",":c","","","lucifur_meeting4c","","",""],
["lucifur_meeting4a","you","","the good news!","","","","","",""],
["","lucifur","","well, let's see....","","","","","",""],
["","_none","","lucifur shuffles through the papers.","","","","","",""],
["","lucifur","","oh, would you look at that!","","","","","",""],
["","","","you won the nobel prize!","","","","","",""],
["","you","","i did??","","","","","",""],
["","_none","","lucifur squints at the paper.","","","","","",""],
["","lucifur","","oh, sorry, it's a little smudged. it says you won \"no big prizes.\"","","","","","",""],
["","you","",":c","","","lucifur_meeting4c","","",""],
["lucifur_meeting4c","you","","can i look at it?","","","","","",""],
["","lucifur","","oh, you wouldn't want to see it. lots of legalese.","","","","","",""],
["","","","i suppose i [i]could[/i] walk you through it... but that's way above my pay grade.","","","","","",""],
["","you","","above your pay grade?","","","","","",""],
["","","","aren't you supposed to be the ruler of hell or something...?","","","","","",""],
["","lucifur","","hey, who's the one interviewing who here?","","","","","",""],
["","_none","","lucifur snaps the folder shut.","","","","","",""],
["","lucifur","","listen, bud, i don't know how to tell you this, but...","","","","","",""],
["","","","your chances aren't looking great.","","","","","",""],
["","you","","oh, why not?","","","","","",""],
["","lucifur","","well, sorry to break it to ya, but you're still a kitten.","","","","","",""],
["","","","a neophyte. a blank slate. wet behind the ears. fresh out of the oven. you getting my drift?","","","","","",""],
["","you","","um, are you saying that... i need to spend more time in purrgatory?","","","","","",""],
["","lucifur","","right-o. ","","","","","",""],
["","you","","ah... i see","","","","","",""],
["","","","is there anything i can do to like, change your mind, or...?","","","","","",""],
["","lucifur","","oh, bless your whiskers. ","","","","","",""],
["","","","listen, this interview is more of a formality than anything.","","","","","",""],
["","","","you haven't done your time, {player}, and that's the bottom line.","","","","","",""],
["","","","i mean, didn't your memories get knocked out of your silly little head on the way here?","","","","","",""],
["","","","how are you supposed to move on with your afterlife when you can't even remember your before-life?","","","","","",""],
["","","","mm-mm. no can do.","","","","","",""],
["","you","","wait, i can remember some of it!","","","","","",""],
["","lucifur","","oh, really?","","oliver_quest_complete or numa_quest_complete or kyungsoon_quest_complete or sean_quest_complete or elijah_quest_complete or natalie_quest_complete or tori_quest_complete",['lucifur_after_form1', 'lucifur_after_form2'],"","",""],
["lucifur_after_form1","you","","yeah, i've been having these flashbacks?","","","","","",""],
["","","","i think i'm starting to fill in some of the gaps, though i'm still not totally sure why i'm here...","","","","","",""],
["","","","i mean, i'm not really sure why [i]any[/i] of us are here, but i think i'm starting to have an idea--","","","","","",""],
["","lucifur","","well, spit it out, already. ","","","","","",""],
["","","","what can you tell me about your life?","","","","","",""],
["","you","","hm... let me think...","","","lucifur_bio0","","",""],
["lucifur_after_form2","you","","um, yeah, i think so!","","","","","",""],
["","","","if i think really hard?","","","","","",""],
["","lucifur","","well, spit it out, already. ","","","","","",""],
["","","","what can you tell me about your life?","","","","","",""],
["","you","","hm... let me think...","","","lucifur_bio0","","",""],
["lucifur_bio0","","","","show_bio_choices0","","","",['...'],['lucifur_bio_done']],
["lucifur_bio1","","","","show_bio_choices1","","","",['...'],['lucifur_bio_done']],
["lucifur_bio2","","","","show_bio_choices2","","","",['...'],['lucifur_bio_done']],
["lucifur_bio_gluttony","you","","my favorite food was {bio.food}?","lucifur_talked_about_gluttony","","","","",""],
["","lucifur","","fascinating. ","","","","","",""],
["","","","thank you for this essential insight into your life story.","","","","","",""],
["","you","","just thought i'd mention it...","","","lucifur_bio0","","",""],
["lucifur_bio_pride","you","","i remember that... i was {bio.pride}","lucifur_talked_about_pride","","","","",""],
["","","","i don't know how much that matters as far as saving my soul or whatever","","","","","",""],
["","","","but it's just one of the little things in life that i took pride in","","","","","",""],
["","","","like when i {bio.proudest_moment}, you know?","","","","","",""],
["","lucifur","","amazing. you really are accomplished, aren't you?","","","","","",""],
["","you","","i mean... i thought it was pretty great at the time...","","","lucifur_bio0","","",""],
["lucifur_bio_wrath","you","","oh, i remember where i grew up!","lucifur_talked_about_wrath","","","","",""],
["","","","i can still {bio.hometown} like it was yesterday","","","","","",""],
["","","","oh, oh, yeah, and my favorite place was {bio.favorite_place}!","","","","","",""],
["","lucifur","","oh, spare me the nostalgia","","","","","",""],
["","","","after the first couple thousand damned souls it gets old.","","","","","",""],
["","you","","ah... sorry","","","lucifur_bio0","","",""],
["lucifur_bio_envy","you","","um, i remember this one person really well","lucifur_talked_about_envy","","","","",""],
["","","","they were {bio.role_model}","","","","","",""],
["","","","i guess i thought they were really {bio.envy} and i wished i was like that too, you know?","","","","","",""],
["","lucifur","","mmmm, can't relate","","","","","",""],
["","","","i'm the most {bio.envy} person i know :3","","","","","",""],
["","you","","...","","","","","",""],
["","","","well... i'm sure that's nice","","","","","",""],
["","lucifur","","oh yeah, being me is awesome","","","lucifur_bio0","","",""],
["lucifur_bio_lust","you","","oh!","lucifur_talked_about_lust","","","","",""],
["","","","{bio.partner_name}!","","","","","",""],
["","lucifur","","who?","","","","","",""],
["","you","","they were my {bio.partner}","","","","","",""],
["","","","they liked {bio.partner_about}","","","","","",""],
["","lucifur","","touching.","","","","","",""],
["","you","","yeah","","","","","",""],
["","","","i hope they're okay...","","","","","",""],
["","lucifur","","i'd worry about your own situation first if i were you, bub.","","","","","",""],
["","you","","right, right","","","lucifur_bio0","","",""],
["lucifur_bio_greed","you","","i remember when {bio.setback}","lucifur_talked_about_greed","","","","",""],
["","","","i think that was probably the biggest struggle of my life","","","","","",""],
["","","","i remember thinking, all i really needed was {bio.desire}, you know?","","","","","",""],
["","","","like i was just sitting there, trying to come to terms with my life, and that's the conclusion i drew","","","","","",""],
["","lucifur","","well, look at where you are now. bet your friends would be proud.","","","","","",""],
["","you","","thanks!","","","","","",""],
["","lucifur","","no, that was--","","","","","",""],
["","","","never mind, go on","","","lucifur_bio0","","",""],
["lucifur_bio_sloth","you","","i remember i always wanted to {bio.dream}!","lucifur_talked_about_sloth","","","","",""],
["","","","oh man, it would have been great","","","","","",""],
["","","","there's a lot of stuff i didn't do, actually","","","","","",""],
["","","","like i could have {bio.regret}...","","","","","",""],
["","lucifur","","shame.","","","lucifur_bio0","","",""],
["lucifur_bio_done","you","","...","",['oliver_quest_complete and numa_quest_complete and kyungsoon_quest_complete and sean_quest_complete and elijah_quest_complete and natalie_quest_complete and tori_quest_complete', 'oliver_quest_complete or numa_quest_complete or kyungsoon_quest_complete or sean_quest_complete or elijah_quest_complete or natalie_quest_complete or tori_quest_complete'],['lucifur_bio_done2', 'lucifur_bio_done1', 'lucifur_bio_done3'],"","",""],
["lucifur_bio_done2","lucifur","","well?","saved_everyone","","","","",""],
["","you","","um...","","","","","",""],
["","","","that's all that i can remember right now","","","","","",""],
["","lucifur","","hmm. i see.","","","","","",""],
["","","","tell me one more thing.","","","","","",""],
["","","","why do you think you're in purrgatory?","","","","","",""],
["","you","","oh, well...","","","","","",""],
["","","","","","","","",['to atone for my sins', 'to come to terms with my death', 'to help other people', 'because your queue was backed up, idk'],['lucifur_bio_done2a', 'lucifur_bio_done2b', 'lucifur_bio_done2c', 'lucifur_bio_done2d']],
["lucifur_bio_done2a","you","","i think i'm here to atone for my sins.","","","","","",""],
["","lucifur","","oh?","","","","","",""],
["","you","","i mean... everyone down here, they all did something they regret","","","","","",""],
["","","","oliver and tori, they neglected their friends and family in favor of other pursuits","","","","","",""],
["","","","numa, kyungsoon, they lashed out at people and pushed them away","","","","","",""],
["","","","i don't understand it completely, but i think that's why we're here","","","","","",""],
["","","","i mean, no one here is evil, i'm sure of that. ","","","","","",""],
["","","","just imperfect.","","","","","",""],
["","","","and i think this is a place where we can come to terms with our imperfections and forgive ourselves.","","","","","",""],
["","lucifur","","heh. interesting.","","","lucifur_bio_done2e","","",""],
["lucifur_bio_done2b","you","","i think i'm here to come to terms with my death.","","","","","",""],
["","lucifur","","how so?","","","","","",""],
["","you","","well... i think everyone here left something, or someone, behind on earth","","","","","",""],
["","","","elijah and natalie, they never finished their masterpieces","","","","","",""],
["","","","sean, oliver, they never got to say goodbye to their loved ones","","","","","",""],
["","","","death is shocking, you know? it takes time to get over it and move on.","","","","","",""],
["","","","sometimes... a lot of time.","","","","","",""],
["","","","but we all have to move on one way or another, and i think that's why we're here.","","","","","",""],
["","","","to give us time to find ourselves again.","","","","","",""],
["","lucifur","","interesting, very interesting.","","","lucifur_bio_done2e","","",""],
["lucifur_bio_done2c","you","","i think we're here to help one another.","","","","","",""],
["","lucifur","","...say again?","","","","","",""],
["","you","","i mean, where would elijah be without sean? ","","","","","",""],
["","","","where would numa and kyungsoon be without each other?","","","","","",""],
["","","","sometimes purrgatory doesn't have a meaning. sometimes purrgatory is just purrgatory, you know?","","","","","",""],
["","","","but one thing that's true is that we're all stuck here together.","","","","","",""],
["","","","so all we can do is help each other march on","","","","","",""],
["","","","planting gardens and cataloging libraries and writing poems and whatever we want to do","","","lucifur_bio_done2e","","",""],
["","lucifur","","heh. inspiring.","","","","","",""],
["lucifur_bio_done2d","you","","i think we're here because your queue was backed up, idk","","","","","",""],
["","lucifur","","really?","","","","","",""],
["","","","that's it?","","","","","",""],
["","you","","how should i know??","","","","","",""],
["","","","you can't ask an ant why it builds an anthill","","","","","",""],
["","","","you can't ask a fly why it... i don't know... flies","","","","","",""],
["","","","all i know is that we got put down here and that we have to make the best of a bad situation.","","","","","",""],
["","lucifur","","i see, i see.","","","lucifur_bio_done2e","","",""],
["lucifur_bio_done2e","lucifur","","well. ","","","","","",""],
["","","","you're certainly a curious little nugget, aren't you?","","","","","",""],
["","you","","me? why?","","","","","",""],
["","lucifur","","been busy since you got here, huh, munchkin?","","","","","",""],
["","you","","busy? busy doing what??","","","","","",""],
["","lucifur","","why don't you tell me, furball?","","","","","",""],
["","you","","tell you what???","","","","","",""],
["","lucifur","","you've only been down here a couple of days at most, and you've achieved more than [i]they[/i] have in years.","","","","","",""],
["","","","oh, you should have heard the others, they couldn't shut up about you!","","","","","",""],
["","","","{player} this, {player} that... honestly, after hearing all of them, i was expecting you to be a little more interesting.","","","","","",""],
["","","","and now i find out that you're already back on track with your memories?","","","","","",""],
["","","","that's im-purr-essive, i'll admit.","","","","","",""],
["","you","","oh... i see.","","","","","",""],
["","","","does that mean that you're... changing your mind?","","","","","",""],
["","lucifur","","hmmmm","","","","","",""],
["","","","unfortunately, no.","","","","","",""],
["","","","i'm afraid rules are rules. i just can't let you out until you've done your time in purrgatory.","","","","","",""],
["","","","them's the breaks.","","","","","",""],
["","you","","oh... okay.","","","lucifur_end_meeting","","",""],
["lucifur_bio_done1","lucifur","","well?","","","","","",""],
["","you","","um...","","","","","",""],
["","","","that's all that i can remember right now","","","","","",""],
["","lucifur","","well, well, well.","","","","","",""],
["","","","you're starting to get back on track with your memories. that's unexpected, i'll admit.","","","","","",""],
["","","","but that's not nearly enough.","","","","","",""],
["","","","if you wanna go through those pearly gates, you've gotta sit your ass down and wait.","","","","","",""],
["","","","see what i did there?","","","","","",""],
["","","","the rhyme?","","","","","",""],
["","you","","yeah i caught that","","","","","",""],
["","lucifur","","bottom line is, i can't let you out until you've done your time in purrgatory.","","","","","",""],
["","","","them's the breaks.","","","","","",""],
["","you","","okay... i see.","","","lucifur_end_meeting","","",""],
["lucifur_bio_done3","lucifur","","well? cat got your tongue?","saved_no_one","","","","",""],
["","you","","um...","","","","","",""],
["","","","nothing's coming to mind right now.","","","","","",""],
["","lucifur","","oh, wonderful.","","","","","",""],
["","","","are you about done wasting my time, then?","","","","","",""],
["","you","","sheesh, sorry...","","","lucifur_end_meeting","","",""],
["lucifur_end_meeting","lucifur","","yeah, i think we're done here.","","","","","",""],
["","","","let me just grab my stuff and we can--","","","","","",""],
["","you","","wait wait wait!","","","","","",""],
["","","","there's this one question i've been dying to ask.","","","","","",""],
["","lucifur","","well? what is it?","","","","","",""],
["","","","","","","","",['why is there no down escalator?', 'what does the elevator only have one button?', 'why is there a train track but no train?'],['lucifur_end_meeting1', 'lucifur_end_meeting2', 'lucifur_end_meeting3']],
["lucifur_end_meeting1","you","","why is there an up escalator but not a down escalator?","","","","","",""],
["","lucifur","","oh, that's easy.","","","","","",""],
["","","","because lucifur does not let things escalate :3","","","lucifur_end_meeting4","","",""],
["lucifur_end_meeting2","you","","why does the elevator only go to one floor?","","","","","",""],
["","lucifur","","ah, that's what i call the musical elevator.","","","","","",""],
["","","","the only thing it lifts... is your heart :3","","","lucifur_end_meeting4","","",""],
["lucifur_end_meeting3","you","","why is there a train track with no train?","","","","","",""],
["","lucifur","","well, that's simple.","","","","","",""],
["","","","i didn't want our conversation to be derailed :3","","","lucifur_end_meeting4","","",""],
["lucifur_end_meeting4","_none","","lucifur claps his hands and the papers all disappear.","","","","","",""],
["","lucifur","","scurry along now! it's time for the big announcement!","","","","","",""],
["","","","ooooh, this is always the most exciting part.","empty_commons","","","","",""],
["","_none","lucifur_neutral","you let yourself be herded back into the commons. the conversation dies as soon as you emerge.","_goto_commons1","","","","",""],
["","lucifur","","toms and queens, friends and foes, the interviews are over!","","","","","",""],
["","","","finally, we've reached the denoue-maw of your journey. the a-paw-gee. the final fur-ontier. ","","","","","",""],
["","","","it is my utmost pleasure to deliver my fur-dict. my mew de grace. my magnum o-paw-s. my--","","","","","",""],
["","kyungsoon",['lucifur_neutral', 'kyungsoon_neutral'],"oh my god, just get on with it","","","","","",""],
["","lucifur","","hmph. no appreciation for dramatic effect around here.","","","","","",""],
["","tori",['lucifur_neutral', 'tori_neutral'],"so you made your decision? you know which one of us are going to leave?","","","","","",""],
["","lucifur","","yes, indeed!","","","","","",""],
["","","","without further ado, your mew-est denizens of heaven:","","","","","",""],
["","","","...","","","","","",""],
["","","","oh, shoot, my shoe is untied","","","","","",""],
["","","","when did that happen?","","","","","",""],
["","numa",['lucifur_neutral', 'numa_neutral'],"STOP IT! YOU'RE DOING THAT ON PURPOSE!!","","","","","",""],
["","lucifur","","doing what on purpose? :3","","","","","",""],
["","numa","","DELAYING THE RESULTS!!!","","","","","",""],
["","elijah",['lucifur_neutral', 'elijah_neutral'],"do your worst, lucifur. we've waited for years. we can wait a few minutes more.","","","","","",""],
["","sean",['lucifur_neutral', 'elijah_neutral', 'sean_neutral'],"yeah, what he said!","","","","","",""],
["","lucifur","","oh, fine, i'll get on with it.","","","","","",""],
["","","","it's no fun when you start getting all valiant about it.","","","","","",""],
["","","lucifur_neutral","ahem!","","","","","",""],
["","","","i am proud to anounce your newest denizens of heaven:","",['oliver_quest_complete', 'kyungsoon_quest_complete', 'elijah_quest_complete', 'tori_quest_complete', 'natalie_quest_complete'],['judgement_oliver', 'judgement_kyungsoon', 'judgement_elijah', 'judgement_tori', 'judgement_natalie', 'judgement_no_one'],"","",""],
["judgement_oliver","","","oliver.","",['kyungsoon_quest_complete', 'elijah_quest_complete', 'tori_quest_complete', 'natalie_quest_complete'],['judgement_kyungsoon', 'judgement_elijah', 'judgement_tori', 'judgement_natalie', 'judgement_done'],"","",""],
["judgement_kyungsoon","","","kyungsoon.","","","","","",""],
["","","","numa.","",['elijah_quest_complete', 'tori_quest_complete', 'natalie_quest_complete'],['judgement_elijah', 'judgement_tori', 'judgement_natalie', 'judgement_done'],"","",""],
["judgement_elijah","","","elijah.","","","","","",""],
["","","","sean.","",['tori_quest_complete', 'natalie_quest_complete'],['judgement_tori', 'judgement_natalie', 'judgement_done'],"","",""],
["judgement_tori","","","tori.","","natalie_quest_complete",['judgement_natalie', 'judgement_done'],"","",""],
["judgement_natalie","","","natalie.","","","judgement_done","","",""],
["judgement_done","","","aaaaand that's all!","","oliver_quest_complete",['reactions1a', 'reactions2'],"","",""],
["reactions1a","oliver","oliver_neutral","oh, thank god","","","","","",""],
["reactions2","","","_pass","","oliver_quest_complete and natalie_quest_complete",['reactions2a', 'reactions3'],"","",""],
["reactions2a","natalie",['oliver_neutral', 'natalie_neutral'],"you can say that again!","","","","","",""],
["reactions3","","","_pass","","oliver_quest_complete and not natalie_quest_complete",['reactions3a', 'reactions4'],"","",""],
["reactions3a","lucifur",['oliver_neutral', 'lucifur_neutral'],"i think you mean thank [i]me[/i] ;3","","","","","",""],
["reactions4","","","_pass","","oliver_quest_complete and not tori_quest_complete",['reactions4a', 'reactions5'],"","",""],
["reactions4a","tori",['oliver_neutral', 'tori_neutral'],"congratulations, oliver.","","","","","",""],
["","","","i just want you to know i still expect your next chess move, postmarked from heaven.","","","","","",""],
["","oliver","","heh, of course","","","","","",""],
["","","","i'm sorry you didn't make it through, tori... i wish i could just take you with me","","","","","",""],
["","tori","","well, if wishes were nickles, i could have bought my way out of purrgatory by now.","","","","","",""],
["","","","don't worry about me. i'll be fine.","","","","","",""],
["reactions5","","","_pass","","natalie_quest_complete and not oliver_quest_complete",['reactions5a', 'reactions6'],"","",""],
["reactions5a","natalie","natalie_neutral","oh my god","","","","","",""],
["","","","i did it","","","","","",""],
["reactions6","","","_pass","","natalie_quest_complete and not (oliver_quest_complete or tori_quest_complete)",['reactions6a', 'reactions7'],"","",""],
["reactions6a","tori",['natalie_neutral', 'tori_neutral'],"congratulations, natalie.","","","","","",""],
["","","","i'm looking forward to that nocturnal reboot published by heaven press.","","","","","",""],
["","natalie","","aw, thanks tori","","","","","",""],
["","","","i hope you get out soon too","","","","","",""],
["","","","maybe we can meet again someday!","","","","","",""],
["","tori","","that would be nice.","","","","","",""],
["reactions7","","","_pass","","natalie_quest_complete and oliver_quest_complete and not tori_quest_complete",['reactions7a', 'reactions8'],"","",""],
["reactions7a","tori",['oliver_neutral', 'tori_neutral'],"and natalie -- i'm looking forward to that nocturnal reboot published by heaven press.","","","","","",""],
["","natalie",['oliver_neutral', 'tori_neutral', 'natalie_neutral'],"aw, thanks tori","","","","","",""],
["","","","i hope you get out soon too","","","","","",""],
["","","","maybe we can meet again someday!","","","","","",""],
["","tori","","that would be nice.","","","","","",""],
["reactions8","","","_pass","","tori_quest_complete",['reactions8a', 'reactions9'],"","",""],
["reactions8a","tori","tori_neutral","heh","","","","","",""],
["","","","so it was that easy all along...","","","","","",""],
["reactions9","","","_pass","","tori_quest_complete and not oliver_quest_complete",['reactions9a', 'reactions10'],"","",""],
["reactions9a","oliver",['tori_neutral', 'oliver_neutral'],"congrats, tori!","","","","","",""],
["","","","i'm... really happy for you."," ","","","","",""],
["","","","you deserve it, after working so hard.","","","","","",""],
["","tori","","keep your head up, soldier.","","","","","",""],
["","","","if i know you, i'm sure you'll be right on my heels.","","","","","",""],
["reactions10","","","_pass","","elijah_quest_complete",['reactions10a', 'reactions11'],"","",""],
["reactions10a","sean","sean_neutral","elijah! WE DID IT!! ","","","","","",""],
["","","","ELIJAH WE'RE GETTING OUT OF HERE!!","","","","","",""],
["","elijah",['sean_neutral', 'elijah_neutral'],"...","","","","","",""],
["","sean","","WOO!! PEARLY GATES, HERE WE COME!!!","","","","","",""],
["","elijah","","i... i can't believe it","","","","","",""],
["","","","we're really going to heaven","","","","","",""],
["","","","heheh","","","","","",""],
["","","","hahahahaha!","","","","","",""],
["","","","we did it!","","","","","",""],
["reactions11","","","_pass","","elijah_quest_complete and not natalie_quest_complete",['reactions11a', 'reactions12'],"","",""],
["reactions11a","natalie",['sean_neutral', 'elijah_neutral', 'natalie_neutral'],"congrats, guys","","","","","",""],
["","","","i'm really going to miss you two down here","","","","","",""],
["","sean","","aw, natalie...","","","","","",""],
["","","","it wouldn't have been purrgatory without you","","","","","",""],
["","natalie","","thanks!","","","","","",""],
["","","","...i think. that's a compliment, right?","","","","","",""],
["","elijah","","alright, bring it in, guys, bring it in","","","","","",""],
["reactions12","","","_pass","","kyungsoon_quest_complete",['reactions12a', 'reactions13'],"","",""],
["reactions12a","kyungsoon","kyungsoon_neutral","...","","","","","",""],
["","","","numa?","","","","","",""],
["","","","are you okay?","","","","","",""],
["","numa",['kyungsoon_neutral', 'numa_neutral'],"we're...","","","","","",""],
["","","","we're going to heaven...","","","","","",""],
["","kyungsoon","","yep","","","","","",""],
["","numa","","we're going to heaven TOGETHER!!","","","","","",""],
["","kyungsoon","","yep","","","","","",""],
["","numa","","OH MY GOSH","","","","","",""],
["","_none","","numa hugs kyungsoon.","","","","","",""],
["","numa","","I CAN'T BELIEVE IT, WE'RE GOING TO HEAVEN!!","","","","","",""],
["","","","AAAAAA THIS IS AMAZING!!!","","","","","",""],
["","kyungsoon","","haha","","","","","",""],
["","","","yeah","","","","","",""],
["","","","it's pretty great","","","","","",""],
["","_none","","kyungsoon pats numa awkwardly.","","","","","",""],
["reactions13","","","_pass","","not elijah_quest_complete",['reactions13a', 'reactions14'],"","",""],
["reactions13a","sean","sean_neutral","wait","","","","","",""],
["","","","but that's it?","","","","","",""],
["","","","what about the rest of us??","","","","","",""],
["","","","how much longer do we have to fucking wait??","","","","","",""],
["","lucifur",['sean_neutral', 'lucifur_neutral'],"only the fates can tell!","","","","","",""],
["","","","though they're notoriously hard to reach on the phone","","","","","",""],
["","sean","","you've gotta be fuckin kidding me!","","","","","",""],
["","elijah",['elijah_neutral', 'sean_neutral'],"[i]sigh[/i]","","","","","",""],
["","","","maybe this is what we deserve...","","","","","",""],
["reactions14","","","_pass","","natalie_quest_complete and not elijah_quest_complete",['reactions14a', 'reactions15'],"","",""],
["reactions14a","natalie",['elijah_neutral', 'sean_neutral', 'natalie_neutral'],"i'm sorry guys... i'm gonna miss you loads","","","","","",""],
["","sean","","ugh. i'll miss you too, nats","","","","","",""],
["","","","it just won't be purrgatory without you","","","","","",""],
["","natalie","","thanks!","","","","","",""],
["","","","...i think. that's a compliment, right?","","","","","",""],
["","elijah","","alright, bring it in, guys, bring it in","","","","","",""],
["reactions15","","","_pass","","not kyungsoon_quest_complete",['reactions15a', 'reactions16'],"","",""],
["reactions15a","_none",['kyungsoon_neutral', 'numa_neutral'],"numa and kyungsoon are sitting nearby, looking dejected.","","","","","",""],
["","you","","too bad none of us made it, huh?","","","","","",""],
["","kyungsoon","","...","","","","","",""],
["","","","eh","","","","","",""],
["reactions16","","","_pass","","not oliver_quest_complete and not tori_quest_complete",['reactions16a', 'reactions17'],"","",""],
["reactions16a","oliver","oliver_neutral","guess i'll be staying in this library for a while longer, huh?","","","","","",""],
["","","","it's... a little hard to swallow","","","","","",""],
["","","","after getting so close, to have freedom snatched away from you...","","","","","",""],
["reactions17","","","_pass","","not natalie_quest_complete and not elijah_quest_complete",['reactions17a', 'reactions18'],"","",""],
["reactions17a","natalie","natalie_neutral","...","","","","","",""],
["","","","that's just how the cookie crumbles. i guess.","","","","","",""],
["reactions18","","","_pass","","not (tori_quest_complete or natalie_quest_complete or oliver_quest_complete)",['reactions18a', 'reactions19'],"","",""],
["reactions18a","tori","tori_neutral","can't say i'm surprised.","","","","","",""],
["","","","getting out of purrgatory has never been that easy.","","","","","",""],
["reactions19","","","_pass","","oliver_quest_complete and not saved_everyone",['reactions19a', 'reactions20'],"","",""],
["reactions19a","_none","_none","you wait silently as chatter breaks out through the room.","","","","","",""],
["","","oliver_neutral","eventually, oliver approaches you.","","","","","",""],
["","oliver","","um, {player}","","","","","",""],
["","","","so you didn't make the cut, huh?","","","","","",""],
["","you","","yeah, lucifur said i haven't been here long enough, or something","","","","","",""],
["","oliver","","ah, i see","","","","","",""],
["","","","it's a shame, to have to say goodbye only just after we've met...","","","","","",""],
["","","","i think -- and maybe i'm just waxing poetic, but -- if any of us deserves heaven, it's you.","","","","","",""],
["","you","","aw, thanks...","","","","","",""],
["","","","","","","","",['you deserve it too', 'promise me you won\'t overwork yourself', 'read some non-meow books for me'],['reactions19b', 'reactions19c', 'reactions19d']],
["reactions19b","you","","but you deserve it too!","","","","","",""],
["","","","i mean, you've been working away down here for long enough","","","","","",""],
["","oliver","","eheh, it has been a while.","","","","","",""],
["","","","shame i never got to finish that catalog...","","","","","",""],
["","","","but i left quite extensive notes -- perhaps a future librarian will finish the job for me?","","","","","",""],
["","you","","maybe!","","","reactions19e","","",""],
["reactions19c","you","","promise me you won't overwork yourself in heaven too?","","","","","",""],
["","oliver","","well, i'll certainly try.","","","","","",""],
["","","","eheh. i don't know. it's a very old habit of mine.","","","","","",""],
["","","","but maybe heaven will be a more relaxing environment.","","","","","",""],
["","you","","god, it better be","","","reactions19e","","",""],
["reactions19d","you","","read some non-meow books for me!","","","","","",""],
["","oliver","","oh, don't worry, i will.","","","","","",""],
["","","","i can't wait to get my hands on some reading material. [i]any[/i] reading material.","","","","","",""],
["","","","i'd settle for the back of a cereal box right now!","","","","","",""],
["","you","","lol","","","reactions19e","","",""],
["reactions19e","oliver","","by the way, {player}... can i ask you a favor?","","","","","",""],
["","you","","yeah?","","","","","",""],
["","oliver","","when i'm gone, can you just make sure--","","","","","",""],
["","","","no need to exert yourself too much, but if you don't mind--","","","","","",""],
["","","","would you take care of the library for me?","","","","","",""],
["","","","just make sure no one eats too many books or anything?","","","","","",""],
["","","","it would mean a lot to me.","","","","","",""],
["","you","","oh!","","","","","",""],
["","","","yeah... i can do that","","","","","",""],
["","oliver","","thank you.","","","","","",""],
["reactions20","","","_pass","","numa_quest_complete and not oliver_quest_complete",['reactions20a', 'reactions21'],"","",""],
["reactions20a","_none","_none","you wait silently as chatter breaks out through the room.","","","","","",""],
["","","numa_neutral","eventually, numa approaches you.","","","","","",""],
["","numa","","oh, {player}... i'm so sorry you didn't make it ;;","","","","","",""],
["","you","","it's okay!","","","","","",""],
["","","","i'm just glad you and kyungsoon got to stay together","","","","","",""],
["","numa","","aaa thank you","","","","","",""],
["","","","i'm really happy too!","","","","","",""],
["","","","umm, but i just wanted to come and say... thank you, again","","","","","",""],
["","","","you know, for getting me off my butt after all this time","","","","","",""],
["","you","","of course!","","","","","",""],
["","","","","","","","",['a little push can go a long way', 'think you\'ll keep gardening in heaven?', 'are you nervous at all?'],['reactions20b', 'reactions20c', 'reactions20d']],
["reactions20b","you","","a little push can go a long way.","","","","","",""],
["","numa","","true!","","","","","",""],
["","","","like... a dung beetle, pushing a dung ball!","","","","","",""],
["","you","","yeah, sure!","","","","","",""],
["","numa","","did you know the egyptian scarab is actually a dung beetle??","","","","","",""],
["","you","","oh, cool","","","reactions20e","","",""],
["reactions20c","you","","think you'll keep gardening in heaven?","","","","","",""],
["","numa","","that would be nice!","","","","","",""],
["","","","i bet they have proper gardening supplies too...","","","","","",""],
["","you","","oh, for sure","","","","","",""],
["","numa","","like ph strips!","numa_mentioned_ph_strips","","","","",""],
["","","","oh man... i would KILL for some ph strips...","","","","","",""],
["","","","not you, of course","","","","","",""],
["","","","but someone","","","","","",""],
["","you","","o","","","reactions20e","","",""],
["reactions20d","you","","are you nervous at all? about going to heaven?","","","","","",""],
["","numa","","oh, yeah, totally","","","","","",""],
["","","","i mean i'm nervous about everything haha","","","","","",""],
["","","","but it's a good kind of nervous!","","","","","",""],
["","","","like, a warm and fuzzy nervous","","","","","",""],
["","","","it's like i'm a kid again and it's christmas eve and my grandpa is coming to visit","","","","","",""],
["","you","","aww, that's nice","","","","","",""],
["","numa","","yeah...","","","reactions20e","","",""],
["reactions20e","numa","","oh, um, by the way","","","","","",""],
["","","","if you don't mind, there's actually one more favor i wanted to ask...","","","","","",""],
["","","","if that's okay with you i mean!","","","","","",""],
["","you","","sure, go ahead","","","","","",""],
["","numa","","ummm ;;","","","","","",""],
["","","","after i leave...","","","","","",""],
["","","","do you mind watching the garden for me?","","","","","",""],
["","","","you know, make sure no one steps on too many flowers or anything?","","","","","",""],
["","you","","sure!","","","","","",""],
["","","","don't worry, your flowers are safe with me","","","","","",""],
["","numa","","thank you :)","","","","","",""],
["reactions21","","","_pass","","tori_quest_complete and not oliver_quest_complete and not numa_quest_complete",['reactions21a', 'reactions22'],"","",""],
["reactions21a","_none","_none","you wait silently as chatter breaks out through the room.","","","","","",""],
["","","tori_neutral","eventually, tori approaches you.","","","","","",""],
["","tori","","{player}. drew the short end of the stick this time, huh?","","","","","",""],
["","you","","yeah, you can say that again...","","","","","",""],
["","tori","","don't give up hope. if you stay strong, your time will come too.","","","","","",""],
["","","","honestly, after all you did to help me, it feels wrong to be leaving you down here...","","","","","",""],
["","","","but i suppose lucifur can't be convinced?","","","","","",""],
["","you","","no... he was pretty adamant that i had to stay.","","","","","",""],
["","tori","","shame. heaven could use an angel like you.","","","","","",""],
["","you","","aw, that's nice of you","","","","","",""],
["","","","","","","","",['you know, you already have the wings', 'any plans for heaven?', 'shame you never got through that door'],['reactions21b', 'reactions21c', 'reactions21d']],
["reactions21b","you","","you know, if you think about it, you already have the wings","","","","","",""],
["","","","you just need the halo and you're set!","","","","","",""],
["","tori","","ah, yes. i do believe angels are known for their nocturnal vision and hooked beaks.","","","","","",""],
["","you","","lol","","","reactions22","","",""],
["reactions21c","you","","do you have any plans for heaven yet?","","","","","",""],
["","tori","","oh, of course. i've always had killing god on my bucket list.","","","","","",""],
["","you","","lol good one","","","","","",""],
["","","","...","","","","","",""],
["","","","wait","","","","","",""],
["","","","are you serious?","","","","","",""],
["","tori","","nah, i'm just kidding.","","","","","",""],
["","","","...maybe.","","","","","",""],
["","","","i'll have to scope out the place first, of course, before really deciding what i want to do with my afterlife.","","","","","",""],
["","","","see if god has any obvious weak points","","","","","",""],
["","","","stuff like that.","","","","","",""],
["","you","","ah... yes, of course","","","reactions22","","",""],
["reactions21d","you","","shame you never got through that door","","","","","",""],
["","","","the one you were staking out?","","","","","",""],
["","tori","","true, true.","","","","","",""],
["","","","for all we know, on the other side were unfathomable riches.","","","","","",""],
["","","","or the secret to lifelong happiness.","","","","","",""],
["","","","but i guess some mysteries were never meant to be solved.","","","","","",""],
["","you","","yeah, i guess so.","","saw_ponyflip",['reactions21e', 'reactions22'],"","",""],
["reactions21e","you","","...","","","","","",""],
["","","","","","","","",['tell her what was behind the door', 'don\'t'],['reactions21f', 'reactions21g']],
["reactions21f","you","","actually, um...","","","","","",""],
["","","","there's something i've been meaning to tell you about--","","","reactions22","","",""],
["reactions21g","_none","","you decide it would be best to keep it to yourself.","","","reactions22","","",""],
["reactions22","","","_pass","","saved_everyone",['protest', 'reactions_done'],"","",""],
["reactions_done","lucifur","lucifur_neutral","alright, alright, that was all very tearjerking and entertaining, but wrap it up folks!","","","","","",""],
["","","","we have some new angels to swear in!","","","","","",""],
["","natalie",['lucifur_neutral', 'natalie_neutral'],"wait, like, now? like right now?","","","","","",""],
["","lucifur","","yyyyes? what better time to begin eternal paradise?","","","","","",""],
["","natalie","","i dunno... i thought we'd have more time to say goodbye","","","","","",""],
["","lucifur","","well, you'd better make it quick, because i'm a busy cat. i don't have time to be hanging out in this room all day.","","","","","",""],
["","you","","but... that's what you've been doing for the past--","","","","","",""],
["","lucifur","","AHEM. if you'll follow me to the antechamber, please!","antechamber_portal","","","","",""],
["_none","_none","lucifur_neutral","lucifur leads everyone back to the room where you started.","_goto_antechamber1","","","","",""],
["","you","","whoa, a portal",[['empty_commons', false]],"","","","",""],
["","lucifur","","there will be plenty of paperwork and red tape in due time, but for now, all you have to do is step through the portal.","","","","","",""],
["","","","someone will greet you on the other side.","","","","","",""],
["","you","","that's really it?","","","","","",""],
["","","","you just step through and you'd be in heaven?","","","","","",""],
["","lucifur","","right-o.","","","","","",""],
["","","","whenever you're ready.","","","","","",""],
["","","","...","","","","","",""],
["","","","......","","","","","",""],
["","","","ahem, i said, [i]whenever you're ready[/i]","","","","","",""],
["","","","jeez, people are usually more eager to go to heaven than this.","","","","","",""],
["goodbyes1","","","_pass","","sean_quest_complete",['goodbyes1a', 'goodbyes2'],"","",""],
["goodbyes1a","_none","sean_neutral","sean steps forward.","","","","","",""],
["","sean","","well, it's been a blast, guys!","","","","","",""],
["","","","actually, not really. most of it was terrible.","","","","","",""],
["","","","but it's been real, you know?","","","","","",""],
["","natalie",['sean_neutral', 'natalie_neutral'],"absolutely. the realest","","","","","",""],
["","sean","","so, yeah.","","","","","",""],
["","","","see ya on the other side, green beans!","","","","","",""],
["","you","","maybe one day!","","","","","",""],
["","sean","","cowabunga!!","","","","","",""],
["","_none","_none","sean leaps through the portal.","","","","","",""],
["","elijah","elijah_neutral","...","","","","","",""],
["","","","guess i'd better make sure he doesn't get up to any trouble.","","","","","",""],
["","","","don't want him disrobing any angels or nothin. heh","","","","","",""],
["","","","take care, everyone.","","","","","",""],
["","_none","_none","elijah follows sean through.","","","","","",""],
["goodbyes2","","","_pass","","tori_quest_complete",['goodbyes2a', 'goodbyes3'],"","",""],
["goodbyes2a","tori","tori_neutral","no point in delaying this any further.","","","","","",""],
["","","","everyone, it's been a pleasure.","","","","","",""],
["","you","","good luck, tori","","","","","",""],
["","oliver",['oliver_neutral', 'tori_neutral'],"pleasure was ours!","","","","","",""],
["","_none","_none","tori gives everyone a curt nod, then briskly walks through the portal.","","","","","",""],
["goodbyes3","","","_pass","","oliver_quest_complete",['goodbyes3a', 'goodbyes4'],"","",""],
["goodbyes3a","oliver","oliver_neutral","...","","","","","",""],
["","","","well, guess i should go, then","","","","","",""],
["","","","um, it's been nice knowing everyone.","","","","","",""],
["","you","","you too!","","","","","",""],
["","oliver","","{player}... kyungsoon...","","","","","",""],
["","","","i just want to say...","","","","","",""],
["","","","um... i really...","","","","","",""],
["","","","well","","","","","",""],
["","","","i guess i don't really know what to say.","","","","","",""],
["","kyungsoon",['oliver_neutral', 'kyungsoon_neutral'],"whatever dude","","","","","",""],
["","","","just go through","","","","","",""],
["","_none","","oliver nods.","","","","","",""],
["","oliver","","yes, you're right, of course","","","","","",""],
["","","","so, in that case...","","","","","",""],
["","","","goodbye!","","","","","",""],
["","you","","see ya","","","","","",""],
["","_none","","oliver takes a deep breath, then walks through.","","","","","",""],
["goodbyes4","","","_pass","","numa_quest_complete",['goodbyes4a', 'goodbyes5'],"","",""],
["goodbyes4a","numa","numa_neutral","...","","","","","",""],
["","","","wait... we can really just walk in?","","","","","",""],
["","lucifur",['numa_neutral', 'lucifur_neutral'],"has this not been made abundantly clear already??","","","","","",""],
["","numa","","aaa sorry","","","","","",""],
["","","","it's just... hard to believe we're really leaving","","","","","",""],
["","","numa_neutral","but, um...","","","","","",""],
["","","","goodbye, everyone","","","","","",""],
["","","","it's been really nice knowing you!","","","","","",""],
["","you","","bye, numa","","","","","",""],
["","","","good luck on the other side!","","","","","",""],
["","numa","","...","","","","","",""],
["","","","just gotta...","","","","","",""],
["","","","go through the big scary portal...","","","","","",""],
["","kyungsoon",['kyungsoon_neutral', 'numa_neutral'],"want to go in together?","","","","","",""],
["","numa","","oh, yes please ;;","","","","","",""],
["","_none","","kyungsoon takes numa's hand","","","","","",""],
["","kyungsoon","","well","","","","","",""],
["","","","cya, nerds","","","","","",""],
["","_none","","they step through the portal together.","","","","","",""],
["goodbyes5","","","_pass","","natalie_quest_complete",['goodbyes5a', 'goodbyes_done'],"","",""],
["goodbyes5a","natalie","natalie_neutral","...","","","","","",""],
["","","","oh, it's just me, right?","","","","","",""],
["","you","","yeah, i think so.","","","","","",""],
["","natalie","","cool, cool","","","","","",""],
["","","","welp","","","","","",""],
["","","","thanks for being awesome, guys","","","","","",""],
["","you","","we all know you're the [i]moth[/i] awesome of all","","","","","",""],
["","natalie","","oh, you","","","","","",""],
["","","","bring it in, guys","","","","","",""],
["","_none","","natalie gives everyone a hug.","","","","","",""],
["","natalie","","come to heaven soon, okay?","","","","","",""],
["","you","","i'll try","","","","","",""],
["","natalie","","cya!","","","","","",""],
["","_none","","natalie takes a breath, then goes through.","","","","","",""],
["goodbyes_done","lucifur","lucifur_neutral","...","","","","","",""],
["","","","well, i believe that's all she wrote!","","","","","",""],
["","","","i'd love to stay and chat, but i do need to catch up on a couple... thousand... quarterly reports.","","","","","",""],
["","","","i have to say, despite the inconvenience, it [i]was[/i] nice to finally get to know the denizens of my realm.","","","","","",""],
["","you","","you mean, after secretly spying on them for years...?","","","","","",""],
["","lucifur","","spying??","","","","","",""],
["","","","my friend, i live by one simple maxim:","","","","","",""],
["","","","if you wouldn't do it in front of other people, then you shouldn't do it in front of a cat.","","","","","",""],
["","","","you know who you are.","","","","","",""],
["","_none","","lucifur claps and the portal disappears.",[['antechamber_portal', false], ['portal_zwoop', true]],"","","","",""],
["","lucifur","","enjoy the rest of your stay in purrgatory!","postgame","","","","",""],
["","","","lucifur out!","_delay_lucifur_disappears","","null","","",""],
["lucifur_disappeared","_none","_none","_pass","","","","","",""],
["aftermath_oliver_alone","","","_pass","","numa_quest_complete and elijah_quest_complete and tori_quest_complete and natalie_quest_complete and not oliver_quest_complete",['aftermath_oliver_alone1', 'aftermath_natalie_alone'],"","",""],
["aftermath_oliver_alone1","_none","_none","...","","","","","",""],
["","oliver","oliver_neutral","well...","","","","","",""],
["","","","i guess it's just us two now, huh?","","","","","",""],
["","you","","yeah... guess so.","","","","","",""],
["","oliver","","wow.","","","","","",""],
["","","","...","","","","","",""],
["","","","um, i'll be in the library if you need me.","","","","","",""],
["","you","","alrighty.","","","","","",""],
["","oliver","","...","","","","","",""],
["","_none","","oliver shuffles away.","","","null","","",""],
["aftermath_natalie_alone","","","_pass","","numa_quest_complete and elijah_quest_complete and tori_quest_complete and oliver_quest_complete and not natalie_quest_complete",['aftermath_natalie_alone1', 'aftermath_tori_alone'],"","",""],
["aftermath_natalie_alone1","_none","_none","...","","","","","",""],
["","natalie","natalie_neutral","welp.","","","","","",""],
["","","","so it's just you and me, huh?","","","","","",""],
["","you","","yep","","","","","",""],
["","natalie","","it's gonna be quiet around here","","","","","",""],
["","","","more than usual, anyway.","","","","","",""],
["","you","","yeah, tell me about it","","","","","",""],
["","natalie","","...","","","","","",""],
["","","","well, i'll be in the attic if you need me","","","","","",""],
["","","","got lots of sleep to catch up on","","","","","",""],
["","you","","lol alright","","","","","",""],
["","","","sleep tight","","","","","",""],
["","natalie","","thanks, dude","","","","","",""],
["","_none","","natalie wanders away.","","","null","","",""],
["aftermath_tori_alone","","","_pass","","numa_quest_complete and elijah_quest_complete and natalie_quest_complete and oliver_quest_complete and not tori_quest_complete",['aftermath_tori_alone1', 'aftermath_sean_elijah_alone'],"","",""],
["aftermath_tori_alone1","_none","_none","...","","","","","",""],
["","tori","tori_neutral","guess that just leaves you and me.","","","","","",""],
["","you","","yeah, wow...","","","","","",""],
["","tori","","hm. well, certainly will be less noisy around here.","","","","","",""],
["","you","","yep","","","","","",""],
["","tori","","...","","","","","",""],
["","","","i'll see you around, comrade.","","","","","",""],
["","","","keep your head up. our time will come too.","","","","","",""],
["","you","","thanks... i'll try.","","","","","",""],
["","tori","","that's what i like to hear.","","","","","",""],
["","_none","","tori briskly walks away.","","","null","","",""],
["aftermath_sean_elijah_alone","","","_pass","","numa_quest_complete and not elijah_quest_complete and natalie_quest_complete and oliver_quest_complete and tori_quest_complete",['aftermath_sean_elijah_alone1', 'aftermath_kyungsoon_numa_alone'],"","",""],
["aftermath_sean_elijah_alone1","_none","_none","...","","","","","",""],
["","sean",['elijah_neutral', 'sean_neutral'],"welp, just the three of us now, huh?","","","","","",""],
["","you","","i guess so.","","","","","",""],
["","sean","","man, i should have just run for it...","","","","","",""],
["","","","probably could have gotten through the portal before that douche caught me","","","","","",""],
["","elijah","","or you would have gotten turned into a frog.","","","","","",""],
["","sean","","whatever dude","","","","","",""],
["","","","at least being a frog would have been sort of interesting.","","","","","",""],
["","","","...","","","","","",""],
["","","","anyway. i'll see you guys around, i guess.","","","","","",""],
["","_none","elijah_neutral","sean sulks away.","","","","","",""],
["","elijah","","...","","","","","",""],
["","","","seeya, {player}.","","","","","",""],
["","you","","cya.","","","","","",""],
["","_none","_none","elijah leaves as well.","","","null","","",""],
["aftermath_kyungsoon_numa_alone","","","_pass","","not numa_quest_complete and elijah_quest_complete and natalie_quest_complete and oliver_quest_complete and tori_quest_complete",['aftermath_kyungsoon_numa_alone1', 'aftermath1'],"","",""],
["aftermath_kyungsoon_numa_alone1","_none","_none","...","","","","","",""],
["","numa","numa_neutral","wow... only three of us left, huh?","","","","","",""],
["","kyungsoon",['numa_neutral', 'kyungsoon_neutral'],"yep","","","","","",""],
["","","","not even the cat","","","","","",""],
["","numa","","...","","","","","",""],
["","","","well...","","","","","",""],
["","","","i'll be in the garden if anyone needs me, i guess...","","","","","",""],
["","_none","","you glance at kyungsoon.","","","","","",""],
["","you","","and i guess you'll be in your usual spot?","","","","","",""],
["","kyungsoon","","[i]shrug[/i]","","","","","",""],
["","","","probably.","","","","","",""],
["","_none","kyungsoon_neutral","after a moment of awkward silence, numa leaves the room.","","","","","",""],
["","","_none","kyungsoon follows soon after.","","","null","","",""],
["aftermath1","you","","...","","not natalie_quest_complete",['aftermath1a', 'aftermath2'],"","",""],
["aftermath1a","natalie","natalie_neutral","weeeeelp","","","","","",""],
["","","","time to go back to sleeping.","","","","","",""],
["aftermath2","","","_pass","","not oliver_quest_complete",['aftermath2a', 'aftermath3'],"","",""],
["aftermath2a","oliver","oliver_neutral","guess it's back to cataloging for me...","","","","","",""],
["aftermath3","","","_pass","","not sean_quest_complete",['aftermath3a', 'aftermath4'],"","",""],
["aftermath3a","sean","sean_neutral","man, i should have just run for it...","","","","","",""],
["","","","probably could have gotten through the portal before that douche caught me","","","","","",""],
["","elijah",['elijah_neutral', 'sean_neutral'],"or you would have gotten turned into a frog.","","","","","",""],
["","sean","","whatever dude","","","","","",""],
["","","","at least being a frog would have been sort of interesting.","","","","","",""],
["aftermath4","","","_pass","","not tori_quest_complete",['aftermath4a', 'aftermath5'],"","",""],
["aftermath4a","tori","tori_neutral","i've got some work to attend to.","","","","","",""],
["","","","i'll see you all another time.","","","","","",""],
["aftermath5","","","_pass","","not numa_quest_complete",['aftermath5a', 'aftermath6'],"","",""],
["aftermath5a","numa","numa_neutral","um...","","","","","",""],
["","","","i'll be in the garden if anyone needs me, i guess...","","","","","",""],
["","_none","kyungsoon_neutral","you glance at kyungsoon.","","","","","",""],
["","you","","and i guess you'll be in your usual spot?","","","","","",""],
["","kyungsoon","","[i]shrug[/i]","","","","","",""],
["","","","probably.","","","","","",""],
["aftermath6","","","_pass","","not natalie_quest_complete",['aftermath6a', 'aftermath7'],"","",""],
["aftermath6a","natalie","natalie_neutral","catch ya later, guys","","","","","",""],
["","you","","yeah, you too","","","","","",""],
["aftermath7","","","_pass","","(not oliver_quest_complete and not tori_quest_complete and natalie_quest_complete) or (not oliver_quest_complete and not natalie_quest_complete and tori_quest_complete)",['aftermath7a', 'aftermath_done'],"","",""],
["aftermath7a","oliver","oliver_neutral","see you later, i suppose","","","","","",""],
["aftermath_done","_none","_none","one by one the others trickle out of the room, leaving you alone.","","","","","",""],
["","you","","...","","","null","","",""],
["judgement_no_one","lucifur","lucifur_neutral","...no one.","","","","","",""],
["","you","","...what?","","","","","",""],
["","","","what do you mean, no one?","","","","","",""],
["","lucifur","","i mean that you are such a lackluster group of bean bags that, as it turns out, not a single one of you deserves to go to heaven!","","","","","",""],
["","sean",['lucifur_neutral', 'sean_neutral'],"what? that's ridiculous!","","","","","",""],
["","","","what about me, what did i do?","","","","","",""],
["","","","was it the old lady i ran over??","","","","","",""],
["","lucifur","","sorry, the old lady you did [i]what[/i] to?","","","","","",""],
["","sean","","uh.......","","","","","",""],
["","","","nuthin","","","","","",""],
["","tori",['lucifur_neutral', 'tori_neutral'],"lucifur, surely you're mistaken.","","","","","",""],
["","","","most of these people don't have a malicious bone in their body.","","","","","",""],
["","lucifur","","results are results, my dear girl.","","","","","",""],
["","","","look on the bright side: maybe you can try again in a few centuries!","","","","","",""],
["","numa",['lucifur_neutral', 'tori_neutral', 'numa_neutral'],"CENTURIES???","","","","","",""],
["","tori","","i think you're being a little--","","","","","",""],
["","lucifur","","[i]i[/i] think you are all forgetting who's the purr-ince of hell here.","","","","","",""],
["","","","you should be grateful that you ended up here and not somewhere much, much worse.","","","","","",""],
["","","","i mean, you don't think you're the only eight souls in the afterlife, do you?","","","","","",""],
["","","","consider yourself lucky that your greatest grievance is a shortage of orange soda.","","","","","",""],
["","tori","","...","","","","","",""],
["","lucifur","lucifur_neutral","well, if that's settled, then i actually have another announcement to make.","","","","","",""],
["","","","whether you deserve to rot here forever or not, i can't leave this facility over capacity.","","","","","",""],
["","","","so i will be choosing one of you at random to go to heaven.","","","","","",""],
["","_none","","...","","","","","",""],
["","oliver",['lucifur_neutral', 'oliver_neutral'],"so in the end, it's a coin flip that will decide our fate...","","","","","",""],
["","lucifur","","well, not exactly. more of a d8 roll.","","","","","",""],
["","_none","lucifur_neutral","lucifur snaps and an eight-sided die appears in his hand. your names are printed on the sides.","","","","","",""],
["","lucifur","","sinners! if you believe in benevolent forces, pray to them now...","","","","","",""],
["","","","because not even god can bend the whims of random chance!","","","","","",""],
["","","","when this dice finishes tumbling, one of you shall be delivered unto heaven above!","","","","","",""],
["","","","and the rest of you--","","","","","",""],
["","oliver",['lucifur_neutral', 'oliver_neutral'],"do you mean die?","","","","","",""],
["","lucifur","","sorry?","","","","","",""],
["","oliver","","um, dice is the plural. i think you meant \"when this die finishes tumbling.\"","","","","","",""],
["","","","sorry","","","","","",""],
["","lucifur","","oh, god dammit. i always get those mixed up","","","","","",""],
["","","","you said die is the plural one...?","","","","","",""],
["","oliver","","um, dice.","","","","","",""],
["","lucifur","","right, right. one die, two dice.","","","","","",""],
["","","","anyway, i'm going to roll it now.","","","","","",""],
["","","","hup!","","","","","",""],
["","_none","lucifur_neutral","lucifur throws the die, which rolls under a chair.","","","","","",""],
["","lucifur","","fuck","","","","","",""],
["","","","hold on","","","","","",""],
["","_none","","lucifur crouches and sticks his arm underneath.","","","","","",""],
["","lucifur","","ugh, there's cat hair all over the floor","","","","","",""],
["","","","that one's my bad, guys. next time i'll install a vacuum cleaner","","","","","",""],
["","","","where is this goddamn dice??","","","","","",""],
["","oliver",['lucifur_neutral', 'oliver_neutral'],"die","","","","","",""],
["","lucifur","","yes, that","","","","","",""],
["","elijah",['lucifur_neutral', 'elijah_neutral'],"i think it's over there by the mat.","","","","","",""],
["","lucifur","","oh! thank you. ","","","","","",""],
["","","lucifur_neutral","ahem. so the one who will be going to heaven is....","","","","","",""],
["","","","{player}!","","","","","",""],
["","","","","","","","",['wait, me?', 'YES!'],['judgement_no_one1', 'judgement_no_one2']],
["judgement_no_one1","you","","...","","","","","",""],
["","","","wait","","","","","",""],
["","","","me?","","","","","",""],
["","lucifur","","no, the other {player}. [i]yes[/i], you.","","","","","",""],
["","sean",['lucifur_neutral', 'sean_neutral'],"what -- but {they} JUST GOT HERE!!","","","","","",""],
["","lucifur","","well, {aren't/isn't} {they} just a lucky little bugger.","","","judgement_no_one3","","",""],
["judgement_no_one2","you","","YES!","","","","","",""],
["","","","oh, thank god!","","","","","",""],
["","sean",['lucifur_neutral', 'sean_neutral'],"what -- but you JUST GOT HERE!!","","","","","",""],
["","_none","","you shrug.","","","judgement_no_one3","","",""],
["judgement_no_one3","sean","","that's bullshit!","","","","","",""],
["","","","let elijah go! he's been here the longest!","","","","","",""],
["","elijah",['lucifur_neutral', 'sean_neutral', 'elijah_neutral'],"well, hold on now--","","","","","",""],
["","tori",['lucifur_neutral', 'sean_neutral', 'elijah_neutral', 'tori_neutral'],"leave {player} alone. {they} didn't ask for this.","","","","","",""],
["","sean","","yeah, newsflash, NONE OF US asked for this!","","","","","",""],
["","lucifur","lucifur_neutral","children, children!","","","","","",""],
["","","","you heard what i said, not even god can bend the whims of yadda yadda","","","","","",""],
["","","","so get over yourselves already and follow me to the antechamber.","","","","","",""],
["","_none","_none","lucifur marches down the corridors. mutely, the others trickle after him.","antechamber_portal","","","","",""],
["","","","eventually, he stops in the room where you started.","_goto_antechamber1","","","","",""],
["","lucifur","lucifur_neutral","aaand here we are!",[['empty_commons', false]],"","","","",""],
["","you","","whoa, a portal","","","","","",""],
["","lucifur","","there will be plenty of paperwork and red tape in due time, but for now, all you have to do is step through.","","","","","",""],
["","","","someone will greet you on the other side.","","","","","",""],
["","you","","that's... really it?","","","","","",""],
["","","","i just step through and i'll be in heaven?","","","","","",""],
["","lucifur","","right-o.","","","","","",""],
["","","","whenever you're ready.","","","","","",""],
["","_none","_none","you nervously step up to the portal.","","","","","",""],
["","you","","um...","","","","","",""],
["","","","well","","","","","",""],
["","","","goodbye, everyone, i guess","","","","","",""],
["","natalie","natalie_neutral","bye...","","","","","",""],
["","oliver","oliver_neutral","take care.","","","","","",""],
["","kyungsoon","kyungsoon_neutral","cya","","","","","",""],
["","you","","...","","","","","",""],
["","","","","","","","",['it was nice knowing you', 'thank you for being so welcoming', 'sorry'],['bad_end1', 'bad_end2', 'bad_end3']],
["bad_end1","you","_none","it was nice knowing you.","","","","","",""],
["","_none","","...","","","bad_end4","","",""],
["bad_end2","you","_none","thank you for being so welcoming","","","","","",""],
["","_none","","...","","","bad_end4","","",""],
["bad_end3","you","_none","sorry...","","","","","",""],
["","_none","","...","","","bad_end4","","",""],
["bad_end4","_none","","everyone seems to be avoiding your gaze.","","","","","",""],
["","","","nothing left but to go through.","","","null","","",""],
["protest","lucifur","lucifur_neutral","alright, alright, that was all very tearjerking and entertaining, but wrap it up folks!","","","","","",""],
["","","","we have some new angels to swear in!","","","","","",""],
["","oliver",['lucifur_neutral', 'oliver_neutral'],"wait, but... ","","","","","",""],
["","","","what about {player}?","","","","","",""],
["","","","","","","","",['huh?', 'yeah!'],['protest1', 'protest2']],
["protest1","you","","huh?","","","","","",""],
["","","","what about me?","","","","","",""],
["","oliver","","well... unless i missed someone...","","","","","",""],
["","","","you're the only one whose name lucifur didn't call.","","","protest3","","",""],
["protest2","you","","yeah, what about me?","","","","","",""],
["","","","i'm the only one whose name you didn't call!","","","protest3","","",""],
["protest3","lucifur","","oh, is that so?","","","","","",""],
["","","","well, that's really quite un-fur-tunate for you, isn't it?","","","","","",""],
["","","","anyway, if you'll follow me to the antechamber--","","","","","",""],
["","natalie",['lucifur_neutral', 'natalie_neutral'],"wait wait wait. we can't just leave {player} behind!","","","","","",""],
["","lucifur","","oh, you can. and you will!","","","","","",""],
["","","","funny how that works out.","","","","","",""],
["","you","","you can't really be leaving me here all alone!","","","","","",""],
["","","","right??","","","","","",""],
["","elijah",['lucifur_neutral', 'elijah_neutral'],"come on, lucifur, maybe we can talk this out","","","","","",""],
["","","","purrgatory was bad enough when there were seven of us... it'll be shit on your own.","","","","","",""],
["","sean",['lucifur_neutral', 'elijah_neutral', 'sean_neutral'],"yeah! what he said!","","","","","",""],
["","lucifur","","children, children.","","","","","",""],
["","","","i've reviewed all the documents, and the bottom line is, {they} {haven't/hasn't} earned {their} passage yet.","","","","","",""],
["","tori",['lucifur_neutral', 'tori_neutral'],"surely you must be mistaken.","","","","","",""],
["","","","i mean, i don't think {player} has a malicious bone in {their} body.","","","","","",""],
["","lucifur","","results are results, my dear girl.","","","","","",""],
["","","","look on the bright side: maybe {they} can try again in a few centuries!","","","","","",""],
["","you","","sorry, centuries??","","","","","",""],
["","tori","","lucifur, don't you think that's a little--","","","","","",""],
["","lucifur","lucifur_neutral","what [i]i[/i] think is that you're forgetting who's the purr-ince of hell here.","","","","","",""],
["","","","you should be grateful that you ended up here and not somewhere much, much worse.","","","","","",""],
["","","","i mean, you don't think you're the only eight souls in the afterlife, do you?","","","","","",""],
["","","","consider yourself lucky that your greatest grievance is a shortage of orange soda.","","","","","",""],
["","you","","...","","","","","",""],
["","lucifur","","well, if that's settled, then will you all [i]kindly[/i] follow me to the antechamber?","","","","","",""],
["","_none","_none","lucifur starts down the corridor.","","","","","",""],
["","numa","numa_neutral","no.","","","","","",""],
["","lucifur",['lucifur_neutral', 'numa_neutral'],"[i]sigh[/i]","","","","","",""],
["","","","listen, you can squabble as long as you'd like, but you have to go to heaven eventually.","","","","","",""],
["","numa","","no, i mean i'm not going!","","","","","",""],
["","lucifur","","pardon?","","","","","",""],
["","numa","","i'm not going to heaven without {player}.","","","","","",""],
["","","","and... neither is kyungsoon!!!","","","","","",""],
["","kyungsoon",['lucifur_neutral', 'numa_neutral', 'kyungsoon_neutral'],"wait what","","","","","",""],
["","numa","","the thing is...","","","","","",""],
["","","","i [i]thought[/i] i deserved to go to heaven","","","","","",""],
["","","","i came to terms with my death, conquered my fear of rejection, you know... um, all that stuff","","","","","",""],
["","","","but the thing is","","","","","",""],
["","","","{player} is the only reason i did any of that!","","","","","",""],
["","","","{they}{'re/'s} the only one that tried to get me to open up, even after {they} knew how weird i was!","","","","","",""],
["","","","without {them}, kyungsoon and i would have never talked to each other!!","","","","","",""],
["","","","so if any of us get to leave, it should be {them}!","","","","","",""],
["","","","","","","","",['just go, numa', 'you would really do that for me?', 'wait, we should talk about this'],['protest4', 'protest5', 'protest6']],
["protest4","you","","i appreciate it, numa, but you should just go...","","","","","",""],
["","","","i'm sure i can figure things out down here ","","","","","",""],
["","numa","","no!","","","","","",""],
["","","","i've had enough of being pushed around.","","","","","",""],
["","","","i don't want to go to heaven if you can't come with us","","","protest7","","",""],
["protest5","you","","you would... really do that for me?","","","","","",""],
["","numa","","i mean, yeah!","","","","","",""],
["","","","you're my friend, after all...","","","protest7","","",""],
["protest6","you","","wait, maybe we should talk about this first...?","","","","","",""],
["","numa","","no way!","","","","","",""],
["","","","i've done enough sitting around and worrying for a lifetime.","","","","","",""],
["","","","i'm taking action while i still have the chance.","","","protest7","","",""],
["protest7","lucifur","","i can't believe it. you actually want to turn down eternal paradise.","","","","","",""],
["","","","kyungsoon, i don't suppose you're on board with this inane plan?","","","","","",""],
["","kyungsoon","","um","","","","","",""],
["","","","well","","","","","",""],
["","","","...","","","","","",""],
["","","","numa... it's [i]heaven[/i]...","","","","","",""],
["","numa","","um, i guess you can go if you want.","","","","","",""],
["","","","but","","","","","",""],
["","","","...","","","","","",""],
["","","","i would really like it if you stayed ;;","","","","","",""],
["","kyungsoon","","...","","","","","",""],
["","","","okay, i'll stay","","","","","",""],
["","lucifur","","oh my satan.","","","","","",""],
["","","","you are possibly the dumbest souls i've ever met in my ludicrously long life.","","","","","",""],
["","","","but fine!","","","","","",""],
["","","","if you two want to stay, then stay. it's no fur off my back.","","","","","",""],
["","","","will the rest of you come with me?","","","","","",""],
["","oliver",['lucifur_neutral', 'oliver_neutral'],"i'm -- i'm staying too!","","","","","",""],
["","lucifur","","oh, for antichrist's sake.","","","","","",""],
["","oliver","","{player}, you know better than anyone -- you know i've been selfish before. i put myself before my friends and family.","","","","","",""],
["","","","but... i'm not going to make any more decisions i regret!","","","","","",""],
["","","","you're my friend, and i'm going to stick by your side.","","","","","",""],
["","","","...","","","","","",""],
["","","","besides... i have a lot of cataloging to catch up on.","","","","","",""],
["","lucifur","","great. fine. sure.","","","","","",""],
["","","","who else wants to stay?","","","","","",""],
["","elijah",['lucifur_neutral', 'elijah_neutral'],"me.","","","","","",""],
["","","","{player} was there when i needed it. finna be there when {they} {need/needs} it too.","","","","","",""],
["","natalie",['lucifur_neutral', 'elijah_neutral', 'natalie_neutral'],"me too!","","","","","",""],
["","","","{player} got me out of my funk and helped me start being creative again.","","","","","",""],
["","","","{they} {deserve/deserves} this more than anyone.","","","","","",""],
["","sean",['lucifur_neutral', 'elijah_neutral', 'natalie_neutral', 'sean_neutral'],"...","","","","","",""],
["","","","eh, heaven's probably full of prudes, anyway","","","","","",""],
["","lucifur","lucifur_neutral","great! fantastic! who's even left??","","","","","",""],
["","you","","...tori?","","","","","",""],
["","tori",['lucifur_neutral', 'tori_neutral'],"...","","","","","",""],
["","","","i have to agree with lucifur on this one.","","","","","",""],
["","","","you are nothing short of a bunch of idiots.","","","","","",""],
["","lucifur","","THANK you!","","","","","",""],
["","tori","","but like it or not, you're my idiots.","","","","","",""],
["","","","we all go, or none of us go.","","","","","",""],
["","you","","aw, guys...","","","","","",""],
["","","","i... don't know what to say. ","","","","","",""],
["","lucifur","","ARGH","","","","","",""],
["","","","don't any of you nitwits understand?","","","","","",""],
["","","","purrgatory is OVER CAPACITY.","","","","","",""],
["","","","one of you HAS to leave. ","","","","","",""],
["","","","i don't even care which one! as long as it's one of you!","","","","","",""],
["","numa",['lucifur_neutral', 'numa_neutral'],"then just let all of us leave!","","","","","",""],
["","lucifur","","no! {player} hasn't done {their} time!","","","","","",""],
["","tori",['lucifur_neutral', 'tori_neutral'],"well, then it seems that we're at an impasse.","","","","","",""],
["","elijah",['lucifur_neutral', 'elijah_neutral'],"aren't you the ruler of hell or something? can't you just bend the rules a little?","","","","","",""],
["","lucifur","","ugh, well, maybe \"ruler of hell\" was a [i]bit[/i] of a hyperbole.","","","","","",""],
["","","","it's more like... senior soul acommodation manager.","","","","","",""],
["","","","of hell.","","","","","",""],
["","","","but purrgatory is MY domain!","","","","","",""],
["","","","and there's a cat's chance in hell i'll let you leave before you do your time!","","","","","",""],
["","you","lucifur_neutral","but... why does it matter so much to you?","","","","","",""],
["","lucifur","","that's none of your cat-damned business.","","","","","",""],
["","","","I'M the one in charge here, so i can do what i want.","","","","","",""],
["","you","","hm...","","","","","",""],
["","","","i think i understand... ","","","","","",""],
["","lucifur","","understand what?","","","","","",""],
["convince_lucifur","","lucifur_neutral","","","","",['not tried_to_convince_lucifur1', 'not tried_to_convince_lucifur2', 'not tried_to_convince_lucifur3'],['you just want to do a good job', 'you\'re just proud of what you\'ve made', 'you just want control'],['convince_lucifur1', 'convince_lucifur2', 'convince_lucifur3']],
["convince_lucifur1","you","","you're just trying to do a good job of managing purrgatory, right?","tried_to_convince_lucifur1","","","","",""],
["","","","i mean, you seem like an ambitious person, and the afterlife must be a hellish work environment...","","","","","",""],
["","","","so you hold yourself to high standards!","","","","","",""],
["","lucifur","","pfft. yeah, right.","","","","","",""],
["","","","i've had this job for millenia and i ain't about to lose it anytime soon.","","","","","",""],
["","you","","oh, i see","","","","","",""],
["","","","then maybe...","","tried_to_convince_lucifur1 and tried_to_convince_lucifur2 and tried_to_convince_lucifur3",['convince_lucifur4', 'convince_lucifur'],"","",""],
["convince_lucifur2","you","","do you want me to stay here because you're proud of what you've made?","tried_to_convince_lucifur2","","","","",""],
["","","","i mean, all things considered, purrgatory is an impressive place...","","","","","",""],
["","","","maybe you just want someone to appreciate your accomplishments.","","","","","",""],
["","lucifur","","oh, i couldn't care less about this garbage heap.","","","","","",""],
["","","","it's not even wheelchair accessible...","","","","","",""],
["","you","","oh, right","","","","","",""],
["","","","hm... then...","","tried_to_convince_lucifur1 and tried_to_convince_lucifur2 and tried_to_convince_lucifur3",['convince_lucifur4', 'convince_lucifur'],"","",""],
["convince_lucifur3","you","","you just want to feel like you're in control, don't you?","tried_to_convince_lucifur3","","","","",""],
["","","","you need everything to go the way you planned it, and you're snapping at anyone who breaks the rules","","","","","",""],
["","","","i mean... we can all understand that.","","","","","",""],
["","lucifur","","oh, you think this is all some sort of power trip?","","","","","",""],
["","","","you think i'd be running around as a kitty cat if i wanted to crush you under an iron paw?","","","","","",""],
["","you","","oh, good point","","","","","",""],
["","","","well, maybe...","","tried_to_convince_lucifur1 and tried_to_convince_lucifur2 and tried_to_convince_lucifur3",['convince_lucifur4', 'convince_lucifur'],"","",""],
["convince_lucifur4","you","","um...","","","","","",""],
["","","","...","","","","","",""],
["","","","i don't know... those were all of my ideas","","","","","",""],
["","lucifur","","hah! ","","","","","",""],
["","","","you thought you could probe the mind of the devil himself?!","","","","","",""],
["","","","you might have been able to befriend the bedraggled lemmings that washed up in this place, but my ma-claw-nations are far beyond your understanding!","","","","","",""],
["","","","only i can decree who stays and who leaves, and that's final.","","","","","",""],
["","","","now, will you motley lot go to heaven already, or do you have any more absurd speculations about my motives??","","","","","",""],
["","kyungsoon",['lucifur_neutral', 'kyungsoon_neutral'],"you're lonely","","","","","",""],
["","lucifur","","i -- you -- what?!","","","","","",""],
["","kyungsoon","","you want {player} to stay cus you're lonely","","","","","",""],
["","lucifur","","i mean -- pfft. okay. hah. ","","","","","",""],
["","","","that's even more ridiculous than what {player} said.","","","","","",""],
["","","","like, guys, are you hearing this? i'm not the only one hearing this, right?","","","","","",""],
["","","","i'm literally lucifur. i'm evil in-claw-nate. do you think i get [i]lonely[/i]?","","","","","",""],
["","kyungsoon","","yes","","","","","",""],
["","lucifur","","no! i don't!","","","","","",""],
["","","","i'm not lonely!","","","","","",""],
["","kyungsoon","","man","","","","","",""],
["","","","i've been sitting in this room with you for years","","","","","",""],
["","","","you get pouty if we go too long without scritching your ears","","","","","",""],
["","lucifur","","i--","","","","","",""],
["","kyungsoon","","one time i accidentally locked you in the commons for an hour","","","","","",""],
["","","","and by the time i got back you had torn down elijah's poster, knocked over a chair, and peed in the corner","","","","","",""],
["","","","then you wouldn't stop meowing and nuzzling my legs until i patted you like a bongo","","","","","",""],
["","lucifur","","...","","","","","",""],
["","you","","oh, lucifur, i didn't know...","","","","","",""],
["","lucifur","lucifur_neutral","don't you \"oh, lucifur\" me!","","","","","",""],
["","","","do you think being stuck here for a few years is bad??","","","","","",""],
["","","","i've been managing this goddamn facility for millenia!","","","","","",""],
["","","","you have NO idea how many souls have passed through purrgatory without so much as batting an eye at me.","","","","","",""],
["","","","it's like, oh hi lucifur, oh bye lucifur, we're gonna go have a great time in heaven now, but YOU'RE NOT INVITED!","","","","","",""],
["","","","so sue me for delaying the process a little bit!","","","","","",""],
["","you","","um--","","","","","",""],
["","lucifur","","i would have let you go, you know!","","","","","",""],
["","","","all of you! {player} too! ","","","","","",""],
["","","","after a few years at most, maybe a few decades! that's nothing in the time scale of the afterlife!","","","","","",""],
["","","","but nooOoOoO, you have to use the POWER OF FRIENDSHIP to ruin EVERYTHING","","","","","",""],
["","you","","...","","","","","",""],
["","","","","","","","",['(be kind)', '(be fair)'],['convince_lucifur5', 'convince_lucifur6']],
["convince_lucifur5","you","","i'm so sorry, lucifur...","","","","","",""],
["","","","i didn't know. ","","","","","",""],
["","","","i mean, none of us knew.","","","","","",""],
["","","","but i think if anyone can understand what it's like to be trapped and alone, well... it's us","","","","","",""],
["","lucifur","","hmph.","","","","","",""],
["","","","i don't need your pity.","","","","","",""],
["","you","","okay, okay","","","","","",""],
["","","","but like","","","","","",""],
["","","","you know forcing people to stay with you isn't going to solve anything, right?","","","","","",""],
["","","","maybe if you were a little less... uh...","","","","","",""],
["","tori",['lucifur_neutral', 'tori_neutral'],"overbearing?","","","","","",""],
["","elijah",['lucifur_neutral', 'elijah_neutral'],"megalomaniacal?","","","","","",""],
["","oliver",['lucifur_neutral', 'oliver_neutral'],"...mean?","","","","","",""],
["","you","lucifur_neutral","well, you know.","","","","","",""],
["","","","maybe if you did something nice for the people who end up here, they'd be more inclined to like you back.","","","","","",""],
["","lucifur","","like what?","","","","","",""],
["","","","what exactly do you think i should do?","","","","","",""],
["","you","","maybe you can start with...","","","","","",""],
["","","","letting me go to heaven?","","","","","",""],
["","lucifur","","hah! preposterous.","","","","","",""],
["","","","like you'd know better than someone who's been working in the biz for millenia.","","","","","",""],
["","","","clearly you don't understand the basic principles of managing deceased souls.","","","","","",""],
["","you","","[i]sigh[/i]","","","","","",""],
["","","","worth a shot","","","convince_lucifur7","","",""],
["convince_lucifur6","you","","lucifur, i'm really sorry you went through all that","","","","","",""],
["","","","but... like... forcing people to stay with you is only going to make them resent you more.","","","","","",""],
["","","","you need to put something into a relationship in order for people to reciprocate.","","","","","",""],
["","lucifur","","hmph.","","","","","",""],
["","","","i don't need advice from a mere mortal.","","","","","",""],
["","you","","listen, if anyone understands what it's like to be lonely, it's us.","","","","","",""],
["","","","but... you can't just expect these people to be your friends. not after forcing them to go through all this.","","","","","",""],
["","","","the only thing you can do is try to make things right.","","","","","",""],
["","lucifur","","oh yeah?","","","","","",""],
["","","","and what exactly do you think i should do?","","","","","",""],
["","you","","maybe...","","","","","",""],
["","","","let me go to heaven?","","","","","",""],
["","lucifur","","hah! preposterous.","","","","","",""],
["","","","like you'd know better than someone who's been working in the biz for millenia.","","","","","",""],
["","","","clearly you don't understand the basic principles of managing deceased souls.","","","","","",""],
["","you","","[i]sigh[/i]","","","","","",""],
["","","","well, i tried.","","","convince_lucifur7","","",""],
["convince_lucifur7","lucifur","","you know what?","","","","","",""],
["","","","i know what's wrong, and i've got a better idea to salvage this mess of a sitaution.","","","","","",""],
["","you","","yes?","","","","","",""],
["","lucifur","","oho, yes. only the brilliant mind of lucifur could have come up with this.","","","","","",""],
["","","","i'll let all of you go to heaven!","","","","","",""],
["","you","","w--","","","","","",""],
["","","","but that's--","","","","","",""],
["","natalie",['lucifur_neutral', 'natalie_neutral'],"shh... just let him have this...","","","","","",""],
["","lucifur","lucifur_neutral","CLEARLY, this place needs tidying up.","","","","","",""],
["","","","like, good lord! look at the number of cobwebs in this place!","","","","","",""],
["","elijah",['lucifur_neutral', 'elijah_neutral'],"and the tally marks all over the walls?","","","","","",""],
["","lucifur","","yes! that's just depressing! ","","","","","",""],
["","","","no wonder retention is so goddamned low in this place. ","","","","","",""],
["","","lucifur_neutral","i'll need a full deep cleaning... should call in the electrician, too... ","","","","","",""],
["","","","not to mention, can a cat get some goddamn wallpaper around here??","","","","","",""],
["","numa",['lucifur_neutral', 'numa_neutral'],"ooh, yeah, some wallpaper will really brighten up the place!","","","","","",""],
["","lucifur","","well, that settles it.","","","","","",""],
["","","lucifur_neutral","i need this place vacated ASAP so i can call in the cleaners, and that means you too, {player}.","","","","","",""],
["","_none","","lucifur pauses.","","","","","",""],
["","lucifur","","does that... sound okay to you?","","","","","",""],
["","you","","...me?","","","","","",""],
["","","","well, i think that's--","","","","","",""],
["","lucifur","","SIKE! i'm the devil! i don't give a shit what you think!","","","","","",""],
["","","","you're going to heaven whether you like it or not!","","","","","",""],
["","","","haha!","","","","","",""],
["","you","","uh","","","","","",""],
["","","","okay!","","","","","",""],
["","lucifur","","to the antechamber!!","","","","","",""],
["","_none","lucifur_neutral","lucifur marches through the corridors. everyone else hurries to catch up.","_goto_antechamber5","","","","",""],
["","lucifur","","my word! how did i let this ceiling get like this?",[['empty_commons', false]],"","","","",""],
["","","","now, that's a safety hazard. i need to get this fixed ASAP.","","","","","",""],
["","","","tut tut.","antechamber_portal","","","","",""],
["","_none","lucifur_neutral","lucifur skids to a stop in the room where you started.","_goto_antechamber1","","","","",""],
["","lucifur","","aaand here we are!","","","","","",""],
["","you","","whoa, a portal","","","","","",""],
["","lucifur","","yes, yes. now scurry along through. i have a lot of work to do.","","","","","",""],
["","you","","wait, we just... go through there? and we end up in heaven?","","","","","",""],
["","lucifur","","don't worry, there will be plenty of paperwork in time. but for now you just have to go through.","","","","","",""],
["","","","now, who's going first??","","","","","",""],
["","","","...","","","","","",""],
["","","","anyone?","","","","","",""],
["","sean",['lucifur_neutral', 'sean_neutral'],"well, you don't need to tell me twice.","","","","","",""],
["","","","cowabunga!!","","","","","",""],
["","_none","lucifur_neutral","sean leaps through the portal.","","","","","",""],
["","elijah",['lucifur_neutral', 'elijah_neutral'],"heh. right behind you, buddy.","","","","","",""],
["","_none","lucifur_neutral","one by one, the others enter the portal.","","","","","",""],
["","","","finally, you're left alone with lucifur.","_delay_lucifur_in_antechamber","","null","","",""],
["lucifur_goodbye","_none","_none","_pass","","lucifur_said_goodbye",['lucifur_goodbye2', 'lucifur_goodbye1'],"","",""],
["lucifur_goodbye1","you","lucifur_neutral","...","lucifur_said_goodbye","","","","",""],
["","","","um, lucifur?","","","","","",""],
["","lucifur","","yes, {player}?","","","","","",""],
["","you","","thank you.","","","","","",""],
["","","","i hope you'll be okay down--","","","","","",""],
["","lucifur","","oh, stop with your bleeding heart.","","","","","",""],
["","","","i'm letting you off the hook, remember? go before i change my mind.","","","","","",""],
["","you","","sorry, sorry...","","","null","","",""],
["lucifur_goodbye2","lucifur","lucifur_neutral","what did i tell you? get meow-t of here!","","","","","",""],
["","you","","okay, okay!","","","null","","",""],
["end_leave_antechamber","lucifur","lucifur_neutral","oh, no you don't!","","","","","",""],
["","","","you're going to heaven whether you like it or not, kid.","","","","","",""],
["","you","","eep, sorry","","","null","","",""],
["end_portal","_none","_none","you step into the portal.","_delay_end_fade_out_trigger","","null","","",""]
]