extends Node

var raw_blocks = [
["phone_call","","","_pass","",['called_lucifur', '_inv_business_card'],['phone_call_busy', 'phone_call0', 'phone_call_early'],"","",""],
["phone_call_busy","_none","_none","[i]ring ring ring. ring ring ring.[/i]","start_ringtone","","","","",""],
["","","","[i]hello valued sinner! unfortunately, we are experiencing a high volume of calls right now.[/i]","end_ringtone","","","","",""],
["","","","[i]please hold until our next available agent can assist you.[/i]","","","","","",""],
["","","","[i]your estimated hold time is:[/i]","","","","","",""],
["","","","[i]three.[/i]","","","","","",""],
["","","","[i]hundred.[/i]","","","","","",""],
["","","","[i]thousand.[/i]","","","","","",""],
["","","","[i]years.[/i]","","","","","",""],
["","","","[i]thank you for your patience![/i]","","","","","",""],
["","","","hold music starts playing.","_music_Fly_Me_To_The_Meow","","","","",""],
["","","","...","","","","","",""],
["","","","you hang up.",[['_music_null', true], ['phone_hang_up', true]],"","null","","",""],
["phone_call_early","_none","_none","[i]ring ring ring. ring ring ring.[/i]","start_ringtone","","","","",""],
["","","","hm, no one's picking up.","end_ringtone","","","","",""],
["","","","maybe you should try again later.","","","null","","",""],
["phone_call_911","_none","_none","[i]ring ring ring. ring ring ring.[/i]","start_ringtone","","","","",""],
["","operator","","[i]911, what's your emergency?[/i]","end_ringtone","","","","",""],
["","you","","um, hello","","","","","",""],
["","","","i'm stuck in purrgatory","","","","","",""],
["","operator","","[i]sorry, you're stuck where?[/i]","","","","","",""],
["","you","","purrgatory","","","","","",""],
["","","","with two r's?","","","","","",""],
["","operator","","...","","","","","",""],
["","","","[i]are you calling to report an emergency?[/i]","","","","","",""],
["","you","","well","","","","","",""],
["","","","no, i guess not","","","","","",""],
["","_none","","they hang up.","phone_hang_up","","null","","",""],
["phone_call0","_none","_none","[i]ring ring ring. ring ring ring.[/i]","start_ringtone","","","","",""],
["","","","[i]hello valued sinner! you've reached the office of the devil.[/i]","end_ringtone","","","","",""],
["","","","[i]for inquiries about redeeming lost souls, press 1.[/i]","phone_nav","","","","",""],
["","","","[i]for ferrying services, press 2.[/i]","","","","","",""],
["","","","[i]to speak to the devil, press 3.[/i]","","","null","","",""],
["phone_call1","","","[i]beep![/i]","","","","","",""],
["","","","[i]with our HellHaste soul redemption service, you can pay off your mortal sins in no time at all![/i]","","","","","",""],
["","","","[i]please wait while we retrieve the latest information.[/i]","","","","","",""],
["","","","...","","","","","",""],
["","","","[i]we regret to inform you that no souls are being redeemed at this time.[/i]","","","","","",""],
["","","","[i]please call again soon![/i]",[['phone_nav', false]],"","","","",""],
["","","","[i]beep. beep. beep.[/i]","phone_beep","","null","","",""],
["phone_call2","","","[i]beep![/i]","phone_nav2","","","","",""],
["","","","[i]thank you for choosing SoulFare![/i]","","","","","",""],
["","","","[i]our state-of-the-art ferrying service makes passing on a comfortable, streamlined experience.[/i]","","","","","",""],
["","","","[i]to upgrade your account to premium, press 1.[/i]","","","","","",""],
["","","","[i]for a schedule of upcoming departures from your location, press 2.[/i]","","","null","","",""],
["phone_call21","","","[i]beep![/i]","","","","","",""],
["","","","[i]premium members get reduced wait times at designated SoulFare offices and one free haunting per year, all for the low price of... your soul![/i]","","","","","",""],
["","","","[i]we've detected that your name is: {player}.[/i]","","","","","",""],
["","","","[i]please wait while we retrieve your information.[/i]","","","","","",""],
["","","","...","","","","","",""],
["","","","[i]no account could be found under your name.[/i]",[['phone_nav2', false]],"","","","",""],
["","","","[i]please call again soon![/i]",[['phone_nav', false]],"","","","",""],
["","","","[i]beep. beep. beep.[/i]","phone_beep","","null","","",""],
["phone_call22","","","[i]beep![/i]","","","","","",""],
["","","","[i]we've detected that you are calling from: purrgatory.[/i]","","","","","",""],
["","","","[i]please wait while we retrieve the latest information.[/i]","","","","","",""],
["","","","...","","","","","",""],
["","","","[i]unfortunately, SoulFare services are not currently available at your location.[/i]",[['phone_nav2', false]],"","","","",""],
["","","","[i]please call again soon![/i]",[['phone_nav', false]],"","","","",""],
["","","","[i]beep. beep. beep.[/i]","phone_beep","","null","","",""],
["phone_call3","","","your finger hovers over the 3 button.","","","","","",""],
["","","","you have a feeling there's no going back after this action.","","","","","",""],
["","","","press it?","","","","","",""],
["","","","","","","","",['yes', 'maybe later'],['phone_call4', 'phone_call_hang_up']],
["phone_call_hang_up","","","you hang up.",[['phone_hang_up', true], ['phone_nav', false]],"","null","","",""],
["phone_call4","","","[i]beep![/i]","phone_press_3","","","","",""],
["","","","[i]the devil is busy right now. please hold until the next availability.[/i]","called_lucifur","","","","",""],
["","","","[i]remember, your salvation is our greatest priority![/i]","","","","","",""],
["","","","hold music starts playing.","_music_Fly_Me_To_The_Meow","","","","",""],
["","","","...","on_hold","","","","",""],
["","","","....",[['phone_nav', false]],"","","","",""],
["","","",".....","",['numa_at_commons', 'ks_at_commons'],['phone_call5a', 'phone_call6', 'phone_call7'],"","",""],
["phone_call5a","numa",['kyungsoon_neutral', 'numa_neutral'],"um, {player}, what are you doing?",[['_goto_commons1', true], ['_hide_kyungsoon_idle&numa_at_commons', true]],"","","","",""],
["","you","","just calling someone","","","","","",""],
["","kyungsoon","","who?","","","","","",""],
["","you","","the devil, i think","","","","","",""],
["","_none","","...","","","","","",""],
["","","","....","","","","","",""],
["","","",".....","","","","","",""],
["","numa","","do you... think that's going to work?","","","","","",""],
["","you","","idk","","","","","",""],
["","","","worth a shot, i guess?","","","","","",""],
["","_none","","...","","","","","",""],
["","","","....","","","","","",""],
["","","",".....","","","phone_call8","","",""],
["phone_call6","kyungsoon","kyungsoon_neutral","what are you doing?",[['_goto_commons1', true], ['_hide_kyungsoon_idle', true]],"","","","",""],
["","you","","just calling someone","","","","","",""],
["","kyungsoon","","who?","","","","","",""],
["","you","","the devil, i think","","","","","",""],
["","_none","","...","","","","","",""],
["","","","....","","","","","",""],
["","","",".....","","","","","",""],
["","kyungsoon","","do you actually think that's going to work?","","","","","",""],
["","you","","idk","","","","","",""],
["","","","worth a shot, i guess?","","","","","",""],
["","_none","","...","","","","","",""],
["","","","....","","","","","",""],
["","","",".....","","","phone_call8","","",""],
["phone_call7","_none","","...","_goto_commons1","","","","",""],
["","","","....","","","","","",""],
["","","",".....","","","","","",""],
["","you","","hmmm","","","","","",""],
["","_none","","...","","","","","",""],
["","","","....","","","","","",""],
["","","",".....","","","","","",""],
["","you","","wish someone was here to talk to...","","","","","",""],
["","_none","","...","","","","","",""],
["","","","....","","","","","",""],
["","","",".....","","","phone_call8","","",""],
["phone_call8","","","[i]great news, you're next in the queue![/i]",[['on_hold', false], ['_music_null', true]],"","","","",""],
["","","","[i]the devil will be with you shortly.[/i]","_delay_lucifur_appears","","null","","",""],
["lucifur_intro","???","lucifur_neutral","BAM!",[['_quest_call_lucifur', false], ['_music_Lucifur', true], ['_hide_lucifur&lucifur_extra', true]],"","","","",""],
["","","","did someone call? :3c","","","","","",""],
["","you","","huh?!","","","","","",""],
["","???","","what did you think? was that a pretty good entrance or what?","",['numa_at_commons', 'ks_at_commons'],['lucifur_intro_numa', 'lucifur_intro_ks', 'lucifur_intro_player'],"","",""],
["lucifur_intro_numa","kyungsoon",['kyungsoon_neutral', 'numa_neutral', 'lucifur_neutral'],"who the hell are you","_hide_kyungsoon_idle&numa_at_commons&lucifur&lucifur_extra","","","","",""],
["","???","","i'm lucifur, duh?","","","","","",""],
["","lucifur","","the decei-fur of the world, the angel of the ab-hiss, etc?","","","","","",""],
["","numa","","lucifur?","","","","","",""],
["","","","but -- what did you do to the cat?!","","","","","",""],
["","lucifur","","i didn't do anything to the cat, you ninny. i [i]am[/i] the cat.","","","","","",""],
["","","","and i was having a perfectly balmy time, too, until someone very rudely called my number.","","","","","",""],
["","","","","","","","",['oh, sorry', 'you were here the whole time??'],['lucifur_intro_numa1', 'lucifur_intro_numa2']],
["lucifur_intro_numa1","you","","oh, sorry","","","","","",""],
["","numa","","why are you apologizing??","","","","","",""],
["","","","this is LITERALLY SATAN!","","","lucifur_intro_numa3","","",""],
["lucifur_intro_numa2","you","","wait, so you've been here the whole time and you didn't do anything??","","","","","",""],
["","lucifur","","uhhhhhhhhh, sorry, i was busy being cute and offering emotional companionship?","","","","","",""],
["","","","sheesh, no appreciation for my hard work around here","","","","","",""],
["","numa","","hard work--?","","","","","",""],
["","","","WE'VE BEEN STUCK HERE FOR YEARS!","","","lucifur_intro_numa3","","",""],
["lucifur_intro_numa3","kyungsoon","","want me to beat him up for you babe","","","","","",""],
["","numa","","HONESTLY? KIND OF??","","","","","",""],
["","lucifur","","now now, there's no need for violence!","","","","","",""],
["","","","i'm strictly here on business matters.","","","","","",""],
["","","","this place is over capacity, so i need to get around to fixing that anyway.","","","","","",""],
["","_none","","lucifur snaps his fingers.","_delay_lucifur_snaps","","null","","",""],
["lucifur_intro_ks","kyungsoon",['kyungsoon_neutral', 'lucifur_neutral'],"who the hell are you","_hide_kyungsoon_idle&lucifur&lucifur_extra","","","","",""],
["","???","","uh, i'm lucifur, duh?","","","","","",""],
["","lucifur","","the decei-fur of the world, the angel of the ab-hiss, etc?","","","","","",""],
["","kyungsoon","","...what did you do to the cat?","","","","","",""],
["","lucifur","","i didn't do anything to the cat, you ninny. i [i]am[/i] the cat.","","","","","",""],
["","","","and i was having a perfectly balmy time, too, until someone very rudely called my number.","","","","","",""],
["","","","","","","","",['oh, sorry', 'you were here the whole time??'],['lucifur_intro_ks1', 'lucifur_intro_ks2']],
["lucifur_intro_ks1","you","","oh, sorry...","","","","","",""],
["","lucifur","","no worries, my dear subject.","","","","","",""],
["","","","it's all [i]fur[/i]-given.","","","lucifur_intro_ks3","","",""],
["lucifur_intro_ks2","you","","wait, so you've been here the whole time and you didn't say anything??","","","","","",""],
["","lucifur","","uhhhhhhhhh, sorry, i was busy being cute and offering emotional companionship?","","","","","",""],
["","","","sheesh, no appreciation for my hard work around here","","","lucifur_intro_ks3","","",""],
["lucifur_intro_ks3","kyungsoon","","...","","","","","",""],
["","","","i liked that cat...","","","","","",""],
["","lucifur","","anyway, let's get down to business.","","","","","",""],
["","","","this place is over capacity, so i need to get around to fixing that anyway.","","","","","",""],
["","_none","","lucifur snaps his fingers.","_delay_lucifur_snaps","","null","","",""],
["lucifur_intro_player","you","","wait, who are you?","","","","","",""],
["","???","","uh, i'm lucifur, duh?","","","","","",""],
["","lucifur","","the decei-fur of the world, the angel of the ab-hiss, etc?","","","","","",""],
["","you","","lucifur?","","","","","",""],
["","","","what did you do to the cat??","","","","","",""],
["","lucifur","","i didn't do anything to the cat, you ninny. i [i]am[/i] the cat.","","","","","",""],
["","","","and i was having a perfectly balmy time, too, until someone very rudely called my number.","","","","","",""],
["","","","","","","","",['oh, sorry', 'you were here the whole time??'],""],
["lucifur_intro_player1","you","","oh, sorry","","","","","",""],
["","lucifur","","no worries, my dear subject.","","","","","",""],
["","","","it's all [i]fur[/i]-given.","","","lucifur_intro_player3","","",""],
["lucifur_intro_player2","you","","wait, so you've been here the whole time and you didn't say anything??","","","","","",""],
["","lucifur","","uhhhhhhhhh, sorry, i was busy being cute and offering emotional companionship?","","","","","",""],
["","","","sheesh, no appreciation for my hard work around here","","","lucifur_intro_player3","","",""],
["lucifur_intro_player3","lucifur","","anyway, let's get down to business.","","","","","",""],
["","","","this place is over capacity, so i need to get around to fixing that anyway.","","","","","",""],
["","_none","","lucifur snaps his fingers.","_delay_lucifur_snaps","","null","","",""],
["lucifur_gathering","{sean}","sean_neutral","so that's why you should never put soap in your--",[['poofing', true], ['_hide_lucifur&lucifur_extra', true]],"","","","",""],
["","","","huh?","","","","","",""],
["","","","what just happened?","","","","","",""],
["","{tori}",['tori_neutral', 'sean_neutral'],"excuse me, who are you and what the hell is going on?!","","","","","",""],
["","lucifur","lucifur_neutral","hang on, hang on. ","","","","","",""],
["","","","i know you're all [i]feline[/i] a little stressed, but there's no [i]knead[/i] to throw a [i]hiss[/i]-y fit.","","","","","",""],
["","","","i'm lucifur, ruler of hell, and i'm here with [i]fur[/i]-tunate [i]mews[/i]: at least one of you is getting [i]meow[/i]-t of this place [i]purr[i]-ever!","","","","","",""],
["","","","any questions? :3","","","","","",""],
["","natalie",['lucifur_neutral', 'natalie_neutral'],"...","","","","","",""],
["","","","i don't think i like puns anymore...","","","","","",""],
["","oliver",['lucifur_neutral', 'oliver_neutral'],"wait, if you're really here to let us go, then i certainly won't be the the first to complain, but...","","","","","",""],
["","","","why now? after all this time?","","","","","",""],
["","lucifur","","well, it's pretty simple, actually","","","","","",""],
["","","","the maximum occupancy of this place is seven, and {player} here makes eight.","","","","","",""],
["","you","","really?","","","","","",""],
["","","","that's it?","","","","","",""],
["","lucifur","","yeah, [i]meow[/i]-nagement really gets on our case if we go over.","","","","","",""],
["","","","plus i wanted to see the look on your face when i went POOF out of nowhere","","","","","",""],
["","","","hehe","","","","","",""],
["","{tori}",['lucifur_neutral', 'tori_neutral'],"i have a question.","","","","","",""],
["","","","you said at least one of us will leave. but how will you decide which ones?","","","","","",""],
["","lucifur","","well, it's simple.","","","","","",""],
["","","","i'll evaluate your souls and decide which ones are worthy of [i]cat[/i]-scending to heaven.","","","","","",""],
["","_none","","the room is silent for a moment.","","","","","",""],
["","{sean}",['lucifur_neutral', 'sean_neutral'],"pbbt, well, guess i'm out then.","","","","","",""],
["","","","have fun in heaven, guys! ","","","","","",""],
["","","","spare a thought for poor ole sean every now and then","","","","","",""],
["","{tori}",['lucifur_neutral', 'tori_neutral'],"wait, wait, wait.","","","","","",""],
["","","","so you're just going to leave the rest of us here to rot?","","","","","",""],
["","lucifur","","yep!","","","","","",""],
["","","","it's a real win-lose situation","","","","","",""],
["","{tori}","","pardon?","","","","","",""],
["","lucifur","","some of you will win, some of you will lose. win-lose.","","","","","",""],
["","","","it's business talk, you probably wouldn't have heard of it.","","","","","",""],
["","{numa}",['lucifur_neutral', 'numa_neutral'],"but... we've been waiting for so long!","","","","","",""],
["","","","you can't just leave us here forever!","","","","","",""],
["","lucifur","","sure i can!","","","","","",""],
["","","","i'm evil. i can do whatever i want.","","","","","",""],
["","","","wa-BAM!","_delay_lucifur_frog","","null","","",""],
["lucifur_gathering1","lucifur","lucifur_neutral","just turned that lamp into a frog. that's evil as fuck.",[['_hide_lucifur&lucifur_extra', true], ['frog_in_commons', true]],"","","","",""],
["","{numa}",['lucifur_neutral', 'numa_neutral'],"it's... really not...","","","","","",""],
["","lucifur","","anyway, let's get on with this already.","","","","","",""],
["","","","i'll call you into my library one by one, and we can have a little chat.","","","","","",""],
["","","","in the meanwhile, the rest of you can wait here.","","","","","",""],
["","","","sound good?","","","","","",""],
["","oliver",['lucifur_neutral', 'oliver_neutral'],"wait, sorry","","","","","",""],
["","","","did you say... [i]your[/i]... library?","","","","","",""],
["","","","i thought it was [i]my[/i]...","","","","","",""],
["","","","i mean, not to be presumptuous, but i've been doing a lot of work--","","","","","",""],
["","","","it, it just seemed like the library wasn't being properly maintained, so i--","","","","","",""],
["","","","that is, given the state of disrepair--","","","","","",""],
["","lucifur","","oh, you cute little thing.","","","","","",""],
["","","","it's mine.","","","","","",""],
["","","","elijah, you're up first, big boy!","","met_elijah",['lucifur_gathering3', 'lucifur_gathering2'],"","",""],
["lucifur_gathering2","_none",['lucifur_neutral', 'elijah_neutral', 'oliver_neutral'],"the pangolin looks startled.","","","","","",""],
["lucifur_gathering3","elijah",['lucifur_neutral', 'elijah_neutral', 'oliver_neutral'],"huh?","","","","","",""],
["","","","why me?","","","","","",""],
["","lucifur","","first to arrive, first to leave! it's only fair.","","","","","",""],
["","","","don't be scared... i don't nip ;3","","","","","",""],
["","elijah","","well... alright...","elijah_interviewing","","","","",""],
["","_none","oliver_neutral","elijah nervously follows lucifur into the library.",[['lucifur_in_commons', false]],"","","","",""],
["","oliver","","...","elijah_interviewed","","","","",""],
["","","","but i did so much dusting...",[['_delay_waiting', true], ['_delay_remove_poofing', true], ['_delay_waited', true]],"","null","","",""],
["lucifur_exit","_none","_none","you should probably stay here like lucifur said.","","","null","","",""],
["lucifur_calls_natalie","_none","_none","the library doors burst open and lucifur escorts elijah outside.","","","","","",""],
["","lucifur","lucifur_neutral","mothballs! you're up next","","","","","",""],
["","natalie",['lucifur_neutral', 'natalie_neutral'],"oh, is that me?","_hide_wait_natalie","","","","",""],
["","","","awesome","natalie_interviewing","","","","",""],
["","","","so, lucy boy, before we get started--","natalie_interviewed","","","","",""],
["","lucifur","","first of all, it's not lucy boy, it's lucifur.","","","","","",""],
["","natalie","","okay, lucifur--","","","","","",""],
["","lucifur","","that's [i]mr.[/i] lucifur to you.","","","","","",""],
["","natalie","","...okay, mr. lucifur","","","","","",""],
["","","","i just wanted to ask, why am i down here in the first place?","","","","","",""],
["","lucifur","","i'm afraid that's con-[i]fur[/i]-dential, my girl.","","","","","",""],
["","natalie","","aw, man","","","","","",""],
["","","","is it because i'm left handed?","","","","","",""],
["","lucifur","","what? what does that have to do with anything?","","","","","",""],
["","{tori}",['lucifur_neutral', 'natalie_neutral', 'tori_neutral'],"they used to beat you for being left-handed because they thought it was satanic, you know.","_hide_wait_natalie&wait_tori","","","","",""],
["","lucifur","","wait, really?","","","","","",""],
["","","","hey, don't look at me like that! i don't have any control over what people do in my name.","","","","","",""],
["","","","besides... ","","","","","",""],
["","","","i'm [i]cat[/i]-bidextrous :3c","","","","","",""],
["","","","come on, now! we have work to do!","_delay_remove_elijah_interviewing","","","","",""],
["","_none","_none","lucifur disappears into the libary with natalie trailing behind.","_hide_null","","null","","",""],
["lucifur_calls_oliver","_none","_none","lucifur's voice booms out as natalie leaves the library.","","","","","",""],
["","lucifur","","oliver! get in here!","","","","","",""],
["","","","it's time for a little cat-and-mouse game, if you know what i mean :3c","","","","","",""],
["","_none","oliver_neutral","oliver takes a deep breath.","_hide_wait_oliver","","","","",""],
["","oliver","","alright... here goes nothing...","oliver_interviewing","","","","",""],
["","","","","oliver_interviewed","","","",['you\'ve got this!', 'just be honest', 'there\'s a lot more than "nothing" on the line'],['lucifur_calls_oliver1', 'lucifur_calls_oliver2', 'lucifur_calls_oliver3']],
["lucifur_calls_oliver1","you","","you've got this!!","","","","","",""],
["","oliver","","thanks, i hope i do","","","","","",""],
["","","","no big deal... just the most important interview of my life...","","","","","",""],
["","you","","or death","","","","","",""],
["","oliver","","heh, yes, or death.","","","lucifur_calls_oliver4","","",""],
["lucifur_calls_oliver2","you","","just be honest!","","","","","",""],
["","","","whatever happens will happen","","","","","",""],
["","oliver","","yes, i suppose lying to the devil is only asking for trouble...","","suggested_code",['lucifur_calls_oliver2a', 'lucifur_calls_oliver4'],"","",""],
["lucifur_calls_oliver2a","","","do you think he'll give me bonus points if i show him a typo in one of his books?","","","","","",""],
["","you","","umm, worth a shot?","","","lucifur_calls_oliver4","","",""],
["lucifur_calls_oliver3","you","","well, technically, there's a lot more than nothing on the line","","","","","",""],
["","oliver","","oh, yes, i suppose so","","","","","",""],
["","you","","in fact it would be more accurate to say, like","","","","","",""],
["","","","\"here goes everything\"","","","","","",""],
["","oliver","","yes... indeed...","","","","","",""],
["","you","","...","","","","","",""],
["","","","that didn't help, did it?","","","lucifur_calls_oliver4","","",""],
["lucifur_calls_oliver4","lucifur","","what's taking so long?? get in here, mousey boy!","","","","","",""],
["","oliver","","uh, coming!","_delay_remove_natalie_interviewing","","null","","",""],
["lucifur_calls_kyungsoon","_none","_none","oliver scurries out of the library. lucifur sticks his head out the door.","","","","","",""],
["","lucifur","lucifur_neutral","kyungsoon, i'll see you soon!","","","","","",""],
["","","","heh, see what i did there?","","","","","",""],
["","kyungsoon",['lucifur_neutral', 'kyungsoon_neutral'],"no","_hide_wait_kyungsoon","","","","",""],
["","lucifur","","...what do you mean no?","kyungsoon_interviewing","","","","",""],
["","kyungsoon","","i didn't see what you did","kyungsoon_interviewed","","","","",""],
["","","","could you do it again?","","","","","",""],
["","lucifur","","kyung[i]soon[/i], i'll see you [i]soon[/i]","","","","","",""],
["","","","it's a play on words","","","","","",""],
["","kyungsoon","","sorry, i don't get it","","","","","",""],
["","lucifur","","just get in the library","","","","","",""],
["","","","asshole","","","","","",""],
["","_none","_none","kyungsoon goes in without another word.","_delay_remove_oliver_interviewing","","null","","",""],
["lucifur_calls_numa","_none","_none","the doors open and kyungsoon leaves the library.","","","","","",""],
["","lucifur","","numa numa! it's your time to shine!","","met_numa",['lucifur_calls_numa0a', 'lucifur_calls_numa0'],"","",""],
["lucifur_calls_numa0","_none","numa_neutral","based on the look on the snail's face, that must be her.","_hide_wait_numa","","","","",""],
["lucifur_calls_numa0a","numa","numa_neutral","oh my god",[['met_numa', true], ['_hide_wait_numa', true]],"","","","",""],
["","","","i didn't realize it was my turn next","numa_interviewing","","","","",""],
["","","","aaaaaaaaaaaaaaa what do i do what do i do???","numa_interviewed","","","","",""],
["","you","","hey, chill out, it'll be okay!","","","","","",""],
["","numa","","it's not okay!","","","","","",""],
["","","","i'm going to ruin everything like i ALWAYS do","","","","","",""],
["","","","EXCEPT THIS TIME MY LIFE IS ON THE LINE!!","","numa_quest_complete",['lucifur_calls_numa2', 'lucifur_calls_numa1'],"","",""],
["lucifur_calls_numa1","lucifur","","numa! i know you're a little slow, but we don't have all day!","","","","","",""],
["","","","get it?","","","","","",""],
["","","","cus you're a snail?","","","","","",""],
["","_none","","numa takes a deep breath, then runs through the doors.","","","","","",""],
["","numa","_none","AAAAAAAA","_delay_remove_kyungsoon_interviewing","","null","","",""],
["lucifur_calls_numa2","kyungsoon",['kyungsoon_neutral', 'numa_neutral'],"it'll be fine babe","_hide_wait_numa&wait_kyungsoon","","","","",""],
["","","","he didn't even ask me any hard questions","","","","","",""],
["","numa","","but i didn't prepare at all ;;","","","","","",""],
["","","","what if i don't know any of the answers??","","","","","",""],
["","","","what if i flunk the test?","","","","","",""],
["","","","is it even possible to flunk this test???","","","","","",""],
["","kyungsoon","","hey","","","","","",""],
["","","","wanna go in together?","","","","","",""],
["","numa","","well -- really?","","","","","",""],
["","","","do you think we're allowed to?","","","","","",""],
["","kyungsoon","","why not?","","","","","",""],
["","numa","","i mean...","","","","","",""],
["","","","that would really help...","","","","","",""],
["","kyungsoon","","...","","","","","",""],
["","","","wanna hold hands too?","","","","","",""],
["","numa","","yes please","","","","","",""],
["","lucifur","","numa! i know you're a little slow, but we don't have all day!","","","","","",""],
["","","","get it?","","","","","",""],
["","","","cus you're a snail?","","","","","",""],
["","_none","","numa grabs kyungsoon's hand tightly.","","","","","",""],
["","numa","","okay!! we're going in!!","","","","","",""],
["","_none","","they march through the doors together.","","","null","","",""],
["lucifur_calls_tori","","","_pass","","numa_quest_complete",['lucifur_calls_tori2', 'lucifur_calls_tori1'],"","",""],
["lucifur_calls_tori1","_none","_none","the door bursts open and numa runs out.","_delay_remove_numa_interviewing","","lucifur_calls_tori3","","",""],
["lucifur_calls_tori2","_none","_none","the door bursts open and numa runs out, dragging kyungsoon behind her.",[['_delay_remove_numa_interviewing', true], ['_delay_remove_kyungsoon_interviewing', true]],"","lucifur_calls_tori3","","",""],
["lucifur_calls_tori3","lucifur","lucifur_neutral","alright, featherweight, you're up!","","","","","",""],
["","{tori}",['lucifur_neutral', 'tori_neutral'],"[i]ahem[/i]","_hide_wait_tori","met_tori",['lucifur_calls_tori4', 'lucifur_calls_tori5'],"","",""],
["lucifur_calls_tori4","_none","","tori steps up to lucifur and holds out her hand.","","","","","",""],
["","tori","","tori peck, pleasure to meet you.","","","lucifur_calls_tori6","","",""],
["lucifur_calls_tori5","_none","","the owl steps up to lucifur and holds out her hand.","","","","","",""],
["","???","","tori peck, pleasure to meet you.","met_tori","","lucifur_calls_tori6","","",""],
["lucifur_calls_tori6","lucifur","","yes, i know your name.","","","","","",""],
["","","","just because i called you featherweight doesn't mean i forgot.","tori_interviewing","","","","",""],
["","tori","","you have a quick wit, i can appreciate that.","tori_interviewed","","","","",""],
["","","","i'm looking forward to reaching a mutually beneficial agreement with you.","","","","","",""],
["","_none","","lucifur reluctantly shakes tori's hand.","","","","","",""],
["","lucifur","","geez... suddenly i feel underdressed","","","","","",""],
["","","","just get in here already","","","","","",""],
["","tori","","with pleasure.","","","null","","",""],
["lucifur_calls_sean","_none","_none","tori marches out of the library, looking pleased.","","","","","",""],
["","lucifur","lucifur_neutral","okay, sean, you're up.","","met_sean",['lucifur_calls_sean2', 'lucifur_calls_sean1'],"","",""],
["lucifur_calls_sean1","_none",['lucifur_neutral', 'sean_neutral'],"the snake hops to his feet.","_hide_wait_sean","","","","",""],
["lucifur_calls_sean2","sean",['lucifur_neutral', 'sean_neutral'],"alriiiiight, let's do this lucy boy!",[['met_sean', true], ['_hide_wait_sean', true]],"","","","",""],
["","lucifur","","again, do [i]not[/i] call me lucy boy.","sean_interviewing","","","","",""],
["","sean","","okay, we'll save the pet names for when we know each other a little better ;)","sean_interviewed","","","","",""],
["","lucifur","","wh -- you -- i'm sorry?","","","","","",""],
["","elijah",['lucifur_neutral', 'sean_neutral', 'elijah_neutral'],"sean... are you flirting with the literal devil?","_hide_wait_sean&wait_elijah","","","","",""],
["","sean","","hey, all i'm saying is","","","","","",""],
["","","","i've always wondered why hell is hot, and now i understand why (;","","","","","",""],
["","lucifur","","just hurry up and get in here!","","","","","",""],
["","","","we have a lot to discuss.","","","","","",""],
["","","","...in private.","","","","","",""],
["","sean","","haha, don't mind if i do (;;;","_delay_remove_tori_interviewing","","null","","",""],
["wait_kyungsoon_dot","kyungsoon","kyungsoon_neutral","...","","","null","","",""],
["wait_oliver_dot","oliver","oliver_neutral","...","","","null","","",""],
["wait_numa_dot","numa","numa_neutral","...","","","null","","",""],
["wait_elijah_dot","elijah","elijah_neutral","...","","","null","","",""],
["wait_sean_dot","sean","sean_neutral","...","","","null","","",""],
["wait_tori_dot","tori","tori_neutral","...","","","null","","",""],
["wait_natalie_dot","natalie","natalie_neutral","...","","","null","","",""],
["wait_kyungsoon","","","_pass","",['player_called', 'wait_talked_to_kyungsoon4', 'wait_talked_to_kyungsoon3', 'wait_talked_to_kyungsoon2', 'wait_talked_to_kyungsoon1'],['wait_kyungsoon_encourage', 'wait_kyungsoon_dot', 'wait_kyungsoon4', 'wait_kyungsoon3', 'wait_kyungsoon2', 'wait_kyungsoon1'],"","",""],
["wait_kyungsoon1","you","kyungsoon_neutral","hey, kyungsoon","wait_talked_to_kyungsoon1","","","","",""],
["","kyungsoon","","...","_delay_waited_once","","","","",""],
["","you","","do you think you'll get out?","","","","","",""],
["","kyungsoon","","meh","","","","","",""],
["","you","","yeah, idk either","","broke_vending_machine",['wait_kyungsoon1a', 'null'],"","",""],
["wait_kyungsoon1a","kyungsoon","","[i]munch munch[/i]","","","null","","",""],
["wait_kyungsoon2","you","kyungsoon_neutral","this whole \"delivering judgement\" thing doesn't seem to be bothering you much","wait_talked_to_kyungsoon2","","","","",""],
["","kyungsoon","","eh","_delay_waited_once","","","","",""],
["","","","what am i supposed to do about it?","","","","","",""],
["","you","","i guess that's true...","","","","","",""],
["","","","but you're not nervous or anything?","","","","","",""],
["","kyungsoon","","i'm actually a robot","","","","","",""],
["","","","i don't feel emotions","","","","","",""],
["","you","","oh","","kyungsoon_quest_complete and not numa_interviewing",['wait_kyungsoon2b', 'wait_kyungsoon2a'],"","",""],
["wait_kyungsoon2a","","","can you prove it?","","","","","",""],
["","kyungsoon","","nope","","","","","",""],
["","you","","why not?","","","","","",""],
["","kyungsoon","","out of robot juice","","","","","",""],
["","you","","you mean electricity?","","","","","",""],
["","kyungsoon","","no","","","","","",""],
["","","","juice","","","","","",""],
["","you","","ah","","","null","","",""],
["wait_kyungsoon2b","numa",['kyungsoon_neutral', 'numa_neutral'],"oh, wow...","_hide_wait_kyungsoon&wait_numa","","","","",""],
["","","","i've never met a real life robot before","","","","","",""],
["","kyungsoon","","beep boop","","","","","",""],
["","","","i am kyungsoonbot","","","","","",""],
["","","","initiating tickle sequence","","","","","",""],
["","numa","","huh?","","","","","",""],
["","","","no -- ah!","","","","","",""],
["","","","hahahaha, hold on!","","","","","",""],
["","kyungsoon","","negative, beep","","","","","",""],
["","numa","","heheheHAHAHA","","","null","","",""],
["wait_kyungsoon3","kyungsoon","kyungsoon_neutral","think i could take lucifur on?","wait_talked_to_kyungsoon3","","","","",""],
["","you","","like, in a fight?","_delay_waited_once","","","","",""],
["","kyungsoon","","yeah","","","","","",""],
["","you","","hmm","","","","","",""],
["","","","do you have any martial arts experience?","","","","","",""],
["","kyungsoon","","no","","","","","",""],
["","you","","do you have any fighting experience in general?","","","","","",""],
["","kyungsoon","","no","","","","","",""],
["","you","","uhhhh","","","","","",""],
["","","","are you more or less in shape or engage in any physical activity at all?","","","","","",""],
["","kyungsoon","","no","","","","","",""],
["","you","","then why do you think fighting him is a good idea??","","","","","",""],
["","kyungsoon","","cus","","","","","",""],
["","","","he looks like a dweeb","","","null","","",""],
["wait_kyungsoon4","","","_pass","","kyungsoon_quest_complete and not numa_interviewing",['wait_kyungsoon4a', 'wait_kyungsoon4b'],"","",""],
["wait_kyungsoon4a","kyungsoon",['kyungsoon_neutral', 'numa_neutral'],"you know, numa","_hide_wait_kyungsoon&wait_numa","","","","",""],
["","","","even if we end up in two different places...","wait_talked_to_kyungsoon4","","","","",""],
["","","","i'm glad we met","_delay_waited_once","","","","",""],
["","numa","","oh... me too!","","","","","",""],
["","","","and after wanting to talk to you for so long...","","","","","",""],
["","kyungsoon","","really?","","","","","",""],
["","","","i always thought you were avoiding me","","","","","",""],
["","numa","","well -- not on purpose!","","","","","",""],
["","","","i guess i just got nervous every time i saw you","","","","","",""],
["","","","i'm so sorry ;;","","","","","",""],
["","kyungsoon","","no, it's okay","","","","","",""],
["","","","just","","","","","",""],
["","","","recontextualizing a lot of things","","","","","",""],
["","numa","","like... what?","","","","","",""],
["","kyungsoon","","that time i ran into you in the closet and you tried to hide under a bucket?","","","","","",""],
["","numa","","oh my god, you remember that??","","","","","",""],
["","you","","i'm sure the two of you won't be separated!","","","","","",""],
["","","","surely the devil's not [i]that[/i] heartless, right?","","","","","",""],
["","kyungsoon","","the devil","","","","","",""],
["","you","","yeah!","","","","","",""],
["","kyungsoon","","you think the devil might not be heartless","","","","","",""],
["","you","","...yeah","","","","","",""],
["","kyungsoon","","...","","","","","",""],
["","","","maybe, i dunno","","","","","",""],
["","numa","","um, i hope you stay with us too, {player}!","","","","","",""],
["","","","you're a really good friend!","","","","","",""],
["","","","right, kyungsoon?","","","","","",""],
["","kyungsoon","","eh","","","","","",""],
["","","","i guess it would be cool if you didn't burn in hell","","","","","",""],
["","","","or whatever","","","","","",""],
["","you","","aww, thanks kyungsoon","","","","","",""],
["","","","that means a lot coming from you","","","null","","",""],
["wait_kyungsoon4b","you","kyungsoon_neutral","maybe lucifur will be nice and let us all go to heaven anyway!","wait_talked_to_kyungsoon4","","","","",""],
["","","","i mean, we've been here for a long time","_delay_waited_once","","","","",""],
["","","","surely he's not [i]that[/i] heartless","","","","","",""],
["","kyungsoon","","the devil","","","","","",""],
["","you","","yeah!","","","","","",""],
["","kyungsoon","","you think the devil might not be heartless","","","","","",""],
["","you","","...yeah","","","","","",""],
["","kyungsoon","","...","","","","","",""],
["","","","maybe, i dunno","","","null","","",""],
["wait_oliver","","","_pass","",['player_called', 'wait_talked_to_oliver4', 'wait_talked_to_oliver3', 'wait_talked_to_oliver2', 'wait_talked_to_oliver1'],['wait_oliver_encourage', 'wait_oliver_dot', 'wait_oliver4', 'wait_oliver3', 'wait_oliver2', 'wait_oliver1'],"","",""],
["wait_oliver1","oliver","oliver_neutral","i don't like lucifur very much.","wait_talked_to_oliver1","","","","",""],
["","you","","yeah, he's kind of a jerk","_delay_waited_once","","","","",""],
["","oliver","","right?","","","","","",""],
["","","","can you believe he called me a \"cute little thing\"??","","","","","",""],
["","","","","","","","",['you are though', 'rude af'],['wait_oliver1a', 'wait_oliver1b']],
["wait_oliver1a","you","","you are, though","","","","","",""],
["","oliver","","i--","","","","","",""],
["","","","that's not the point and you know it!","","sean_interviewing",['null', 'wait_oliver1a1'],"","",""],
["wait_oliver1a1","{sean}",['oliver_neutral', 'sean_neutral'],"{they}{'re/'s} right, though (;","_hide_wait_oliver&wait_sean","","","","",""],
["","oliver","","AGH","","","null","","",""],
["wait_oliver1b","you","","yeah that was rude af","","","","","",""],
["","oliver","","can't believe i've been cataloging [i]his[/i] books all along...","","","","","",""],
["","you","","aw, don't think of it that way","","","","","",""],
["","","","you've taken care of the library for so long, it might as well be yours!","","","","","",""],
["","oliver","","i guess...","","","null","","",""],
["wait_oliver2","oliver","oliver_neutral","gosh... waiting around like this makes me so antsy/","wait_talked_to_oliver2","","","","",""],
["","","","aren't you? antsy, i mean?","","","","","",""],
["","you","","i mean, yeah, a little","","","","","",""],
["","","","there's a lot on the line","","","","","",""],
["","oliver","","don't remind me...","","","","","",""],
["","you","","do you want to do something to take your mind off it? ","","","","","",""],
["","","","like play a game, maybe?","","","","","",""],
["","oliver","","well, i suppose we could play tic-tac-toe.","","","","","",""],
["","you","","sure!","","oliver_quest_complete",['wait_oliver2a', 'wait_oliver2a1'],"","",""],
["wait_oliver2a","oliver","","are you... sure you want to? i mean, after last time?","","","","","",""],
["","","","i understand if it wasn't very, um, fun for you","","","","","",""],
["","you","","nah, it's alright","","","","","",""],
["wait_oliver2a1","you","","who should go first?","","","","","",""],
["","oliver","","uhh,","","tori_interviewing",['wait_oliver_2g', 'wait_oliver2b'],"","",""],
["wait_oliver2b","{tori}",['oliver_neutral', 'tori_neutral'],"here, i have a coin. i'll flip for you.","","","","","",""],
["","","","heads or tails?","","","","","",""],
["","","","","","","","",['heads', 'tails'],['wait_oliver2c', 'wait_oliver2d']],
["wait_oliver2c","you","","uh, heads!","","","wait_oliver2e","","",""],
["wait_oliver2d","you","","uh, tails!","","","wait_oliver2e","","",""],
["wait_oliver2e","{tori}","","alright.","","","","","",""],
["","","","...","commons_flip_coin","","","","",""],
["","{tori}","","by lucifur's butthole.","_delay__goto_wait_coin_flip","","null","","",""],
["wait_oliver2g","elijah",['oliver_neutral', 'elijah_neutral'],"here, i can flip for y'all.","","","","","",""],
["","","","heads or tails?","","","","","",""],
["","","","","","","","",['heads', 'tails'],['wait_oliver2h', 'wait_oliver2i']],
["wait_oliver2h","you","","uh, heads!","","","wait_oliver2j","","",""],
["wait_oliver2i","you","","uh, tails!","","","wait_oliver2j","","",""],
["wait_oliver2j","elijah","","alrighty.","","","","","",""],
["","_none","","...","commons_flip_coin","","","","",""],
["","elijah","","holy scales.","_delay__goto_wait_coin_flip","","null","","",""],
["wait_oliver2_after_flip","you","","it... landed on its edge...","","","","","",""],
["","oliver","","...","","","","","",""],
["","","","let's call it a tie?","_delay_waited_once","","","","",""],
["","you","","yeah that seems fair","_delay__goto_commons1","","null","","",""],
["wait_oliver3","oliver","oliver_neutral","hey {player}, have you ever read dante's [i]purgatorio[/i]?","wait_talked_to_oliver3","","","","",""],
["","you","","his what now?","_delay_waited_once","","","","",""],
["","oliver","","erm, the sequel to dante's [i]inferno[/i]","","","","","",""],
["","you","","oh!","","","","","",""],
["","","","no i haven't","","","","","",""],
["","oliver","","well, i was reflecting, and...","","","","","",""],
["","","","truth is, we could have had it a lot worse.","","","","","",""],
["","you","","how so?","","","","","",""],
["","oliver","","well, according to dante, people who committed the sin of pride were made to carry around boulders everywhere they went","","","","","",""],
["","","","could you imagine?","","","","","",""],
["","you","","wow, that wouldn't [i]rock[/i]","","","","","",""],
["","oliver","","haha, yeah, no.","","","","","",""],
["","","","but you know. maybe it's a reminder that we should be grateful for what we have?","","","","","",""],
["","","","i don't know.","","elijah_interviewing",['wait_oliver3b', 'wait_oliver3a'],"","",""],
["wait_oliver3a","elijah",['oliver_neutral', 'elijah_neutral'],"hey, that's really interesting. ","_hide_wait_oliver&wait_elijah","","","","",""],
["","","","what about envy? what was the punishment for that?","","","","","",""],
["","oliver","","er, eyes sewn shut","","","","","",""],
["","elijah","","yikes","","natalie_interviewing",['wait_oliver3d', 'wait_oliver3c'],"","",""],
["wait_oliver3b","sean",['oliver_neutral', 'sean_neutral'],"what about lust?","_hide_wait_oliver&wait_sean","","","","",""],
["","","","what was the punishment for that?","","","","","",""],
["","oliver","","er, running through a wall of fire","","","","","",""],
["","sean","","yikes","","natalie_interviewing",['wait_oliver3d', 'wait_oliver3c'],"","",""],
["wait_oliver3c","natalie",['oliver_neutral', 'natalie_neutral'],"ooh, ooh, what about laziness?","_hide_wait_oliver&wait_natalie","","","","",""],
["","oliver","","uhh, if i remember correctly, they were just forced to run around?","","","","","",""],
["","natalie","","oh god","","","","","",""],
["","","","my worst nightmare","","numa_interviewing or kyungsoon_interviewing or not broke_vending_machine",['null', 'wait_oliver3e'],"","",""],
["wait_oliver3d","sean",['oliver_neutral', 'sean_neutral'],"ooh, ooh, what about lust?","_hide_wait_oliver&wait_sean","","","","",""],
["","oliver","","uhh, if i remember correctly, they were forced to run through a wall of fire?","","","","","",""],
["","sean","","heh","","","","","",""],
["","","","that gives a whole new meaning to hot","","","","","",""],
["wait_oliver3e","numa",['oliver_neutral', 'numa_neutral'],"what about double dipping?","_hide_wait_oliver&wait_numa","","","","",""],
["","oliver","","um","","","","","",""],
["","","","i don't think double dipping is one of the seven deadly sins...?","","","","","",""],
["","numa","","well it SHOULD be!","","","","","",""],
["","kyungsoon",['oliver_neutral', 'numa_neutral', 'kyungsoon_neutral'],"i already said sorry, jeez","_hide_wait_oliver&wait_numa&wait_kyungsoon","","","","",""],
["","numa","","WE ONLY HAD ONE CONTAINER OF FUN DIP BETWEEN US, KYUNGSOON!!","","","","","",""],
["","kyungsoon","","i'm sorry!! jeez!!","","","null","","",""],
["wait_oliver4","oliver","oliver_neutral","...","wait_talked_to_oliver4","","","","",""],
["","you","","you okay?","_delay_waited_once","","","","",""],
["","oliver","","huh?","","","","","",""],
["","","","oh, yeah","","","","","",""],
["","","","just contemplating.","","","","","",""],
["","you","","ah, yeah. i love contemplating.","","oliver_quest_complete",['wait_oliver4a', 'wait_oliver4b'],"","",""],
["wait_oliver4a","oliver","","might be meeting my mom again soon.","","","","","",""],
["","you","","oh, right...","","","","","",""],
["","","","i almost forgot","","","","","",""],
["","oliver","","or not. ","","","","","",""],
["","","","depends on whether i impressed lucifur or not.","","","","","",""],
["wait_oliver4b","oliver","","it's funny, isn't it?","","","","","",""],
["","","","i've aced every test i've ever taken... but i might fail the first test that actually matters.","","","","","",""],
["","you","","aw, it's going to be okay","","","","","",""],
["","","","i don't think this is really the kind of test you can study for anyway... you just have to be honest and hope for the best","","","","","",""],
["","oliver","","i guess so.","","oliver_quest_complete",['wait_oliver4c', 'null'],"","",""],
["wait_oliver4c","you","","i'm sure your mom would be proud of you.","","","","","",""],
["","oliver","","...","","","","","",""],
["","","","thanks.","","","null","","",""],
["wait_numa","","","_pass","",['player_called', 'numa_interviewed and wait_talked_to_numa4', 'numa_interviewed and wait_talked_to_numa3', 'numa_interviewed', 'wait_talked_to_numa2', 'wait_talked_to_numa1'],['wait_numa_encourage', 'wait_numa_dot', 'wait_numa4', 'wait_numa3', 'wait_numa_nervous', 'wait_numa2', 'wait_numa1'],"","",""],
["wait_numa1","","","_pass","","met_numa",['wait_numa1a', 'wait_numa1z'],"","",""],
["wait_numa1z","you","numa_neutral","um, hey, i'm {player}! i don't think we've met","","","","","",""],
["","???","","oh, um, i'm numa","met_numa","","","","",""],
["","numa","","nice to meet you","","","","","",""],
["","","","funny time to meet each other, huh?","","","","","",""],
["","","","hahahaha it's so funny","","","","","",""],
["","","","hahaHAHAHA","","","wait_numa1b","","",""],
["wait_numa1a","you","numa_neutral","hey, numa","","","","","",""],
["","numa","","oh hello","","","","","",""],
["","","","what a funny situation we're in, huh?","","","","","",""],
["","","","hahahaha it's so funny","","","","","",""],
["","","","hahaHAHAHA","","","wait_numa1b","","",""],
["wait_numa1b","you","","um, are you okay?","wait_talked_to_numa1","","","","",""],
["","numa","","yeah i'm fine, why wouldn't i be fine?","_delay_waited_once","","","","",""],
["","","","i'm just the teeniest bit anxious","","","","","",""],
["","","","i don't know why, it's not that big of a deal","","","","","",""],
["","","","it's just like a job interview!","","","","","",""],
["","","","except it's like i forgot to prepare for it","","","","","",""],
["","","","and also if i don't pass then i BURN IN HELL","","","","","",""],
["","","","hahahahaaaaaaaaa","","","","","",""],
["","","","","","","",['it\'ll be okay!', 'deep breaths'],['wait_numa1c', 'wait_numa1d'],""],
["wait_numa1c","you","","it'll be okay, i promise!","","","","","",""],
["","","","you're so nice, there's no way you won't go to heaven","","","","","",""],
["","numa","","aaaaaaaaaaaaaaa i don't know","","","","","",""],
["","","","what about all of my pet fish that died?","","","","","",""],
["","","","and what about that time i pretended to have a broken leg so i didn't have to go to my friend kate's birthday party?","","","","","",""],
["","","","or that time i got really mad at a guy who was trying to hit on me at the mall and whacked him with a tray??","","","","","",""],
["","you","","the time you did [i]what[/i]?","","","","","",""],
["","numa","","AAA forget i said anything!!","","","null","","",""],
["wait_numa1d","you","","deep breaths numa, deep breaths!","","","","","",""],
["","numa","","ok ok, you're right","","","","","",""],
["","","","maybe i should do some deep breathing","","","","","",""],
["","you","","just breathe in...","","","","","",""],
["","_none","","numa breathes in.","","","","","",""],
["","you","","...and let it all out!","","","","","",""],
["","numa","","AAAAAAAAAAAAAAAA","","","","","",""],
["","","","...","","","","","",""],
["","","","sorry","","","","","",""],
["","","","there's a lot to let out ;;","","","null","","",""],
["wait_numa2","numa","numa_neutral","i hope someone takes care of the garden if i end up leaving ;;","wait_talked_to_numa2","","","","",""],
["","","","i hope this doesn't sound rude, but...","_delay_waited_once","","","","",""],
["","","","i really don't trust that cat man to properly care for those flowers!!","","","","","",""],
["","you","","wait, what was the garden like before you got here?","","","","","",""],
["","numa","","oh, it was horrible!","","","","","",""],
["","","","tools mislabeled... weeds everywhere...","","","","","",""],
["","","","even two plants growing in the same pot!","","","","","",""],
["","","","those roots need 12 to 18 inches of room to grow or they'll be susceptible to fungus and rot!!","","","","","",""],
["","you","","oh wow","","","","","",""],
["","","","sounds like it was pretty bad","","","","","",""],
["","numa","","mhm","","","","","",""],
["","","","except the catnip","","","","","",""],
["","","","the catnip patch is pretty much in perfect shape all the time","","","","","",""],
["","you","","huh","","","","","",""],
["","","","wonder why","","","null","","",""],
["wait_numa_nervous","you","numa_neutral","hey numa","","","","","",""],
["","","","...","","","","","",""],
["","","","numa?","","","","","",""],
["","_none","","numa is vibrating rapidly.","","","null","","",""],
["wait_numa3","you","numa_neutral","good job making it through the interview!","wait_talked_to_numa3","","","","",""],
["","numa","","oh... i barely did...","_delay_waited_once","numa_quest_complete",['wait_numa3b', 'wait_numa3a'],"","",""],
["wait_numa3a","","","i felt like i was about to break down at any moment...","","","","","",""],
["","you","","aw, i'm sorry","","","","","",""],
["","numa","","and, and he acted like it was funny the whole time!!","","","","","",""],
["","","","i didn't want to say this, but i think lucifur is...","","","","","",""],
["","","","is...","","","","","",""],
["","","","a very rude person!!","","","","","",""],
["","","","there, i said it!!","","","","","",""],
["","you","","yeah, he is!","","","","","",""],
["","numa","","and he made some extremely questionable architectural decisions when he designed this place!","","","","","",""],
["","you","","true, it's not even wheelchair accessible!","","","","","",""],
["","numa","","and, and, and","","","","","",""],
["","","","HIS TRIDENT LOOKS REALLY DUMB!!","","","","","",""],
["","you","","yeah!","","","","","",""],
["","numa","","phew","","","","","",""],
["","","","um, i feel a little better now that that's off my chest, haha","","","","","",""],
["","","","sorry for dumping all that on you","","","","","",""],
["","you","","it's okay!","","","null","","",""],
["wait_numa3b","","","i felt like i was about to break down at any moment, even with kyungsoon there ;;","","","","","",""],
["","you","","aw, i'm sorry","","","","","",""],
["","numa","","and, and he acted like it was funny the whole time!!","","","","","",""],
["","","","i didn't want to say this, but i think lucifur is...","","","","","",""],
["","","","is...","","","","","",""],
["","","","a very rude person!!","","","","","",""],
["","","","there, i said it!!","","","","","",""],
["","you","","yeah, he is!","","","","","",""],
["","numa","","and he made some extremely questionable architectural decisions when he designed this place!","","","","","",""],
["","you","","true, it's not even wheelchair accessible!","","","","","",""],
["","numa","","and, and, and","","","","","",""],
["","","","HIS TRIDENT LOOKS REALLY DUMB!!","","","","","",""],
["","kyungsoon",['kyungsoon_neutral', 'numa_neutral'],"whoa now","_hide_wait_numa&wait_kyungsoon","","","","",""],
["","","","that might be going a little too far","","","","","",""],
["","numa","","oh -- really??","","","","","",""],
["","kyungsoon","","nah i'm just kidding","","","","","",""],
["","","","his trident looks stupid as shit","","","","","",""],
["","numa","","EXACTLY!","","","null","","",""],
["wait_numa4","","","_pass","","broke_vending_machine",['wait_numa4_snacks', 'wait_numa4_alt'],"","",""],
["wait_numa4_alt","numa","numa_neutral","well, i'm glad i'm done being anxious about that interview","wait_talked_to_numa4","","","","",""],
["","you","","good!","_delay_waited_once","","","","",""],
["","numa","","now i can get a head start on being anxious about the results!","","","","","",""],
["","you","","yeah!","","","","","",""],
["","","","wait what?","","","","","",""],
["","numa","","aaaaaaaaaaaaaaaa","","","null","","",""],
["wait_numa4_snacks","numa","numa_neutral","um... does anyone... want any snacks??","wait_talked_to_numa4","","","","",""],
["","","","kyungsoon and i had some with us when we were teleported here","_delay_waited_once","","","","",""],
["","","","if you want, haha","","natalie_interviewing",['wait_numa4b', 'wait_numa4a'],"","",""],
["wait_numa4a","natalie",['numa_neutral', 'natalie_neutral'],"no thanks, they look un-[i]hell[/i]-thy","_hide_wait_numa&wait_natalie","","","","",""],
["","you","","nice one","","sean_interviewing",['wait_numa4c', 'wait_numa4b'],"","",""],
["wait_numa4b","sean",['numa_neutral', 'sean_neutral'],"do you have any doritos?","_hide_wait_numa&wait_sean","","","","",""],
["","numa","","ummm sorry, no ;;","","","","","",""],
["","sean","","awww","","","","","",""],
["","","","i'm good, then","","","","","",""],
["","numa","","how about cheez-its?","","","","","",""],
["","sean","","no thanks","","oliver_interviewing",['null', 'wait_numa4c'],"","",""],
["wait_numa4c","you","","hey, oliver, i bet you like cheez-its, right?","","","","","",""],
["","oliver",['numa_neutral', 'oliver_neutral'],"actually, the idea that mice like cheese is just a myth!","_hide_wait_numa&wait_oliver","","","","",""],
["","","","mice will eat cheese if there's nothing else available, but they have no preference for it","","","","","",""],
["","you","","oh cool","","","","","",""],
["","oliver","","...also that's sort of racist","","","","","",""],
["","you","","oh","","","","","",""],
["","","","sorry","","","null","","",""],
["wait_elijah","","","_pass","",['player_called', 'wait_talked_to_elijah4', 'wait_talked_to_elijah3', 'wait_talked_to_elijah2', 'wait_talked_to_elijah1'],['wait_elijah_encourage', 'wait_elijah_dot', 'wait_elijah4', 'wait_elijah3', 'wait_elijah2', 'wait_elijah1'],"","",""],
["wait_elijah1","","","_pass","","met_elijah",['wait_elijah1_met', 'wait_elijah1_not_met'],"","",""],
["wait_elijah1_not_met","you","elijah_neutral","so, elijah, right?","met_elijah","","","","",""],
["","elijah","","that's right.","","","","","",""],
["","","","and you are...?","","","","","",""],
["","you","","{player}!","","","","","",""],
["","elijah","","{player}. nice to meet you, man.","","","","","",""],
["wait_elijah1_met","you","elijah_neutral","so, what did lucifur ask you about?","wait_talked_to_elijah1","","","","",""],
["","elijah","","oh, he just asked me some questions about my life","_delay_waited_once","","","","",""],
["","","","i thought it would be something like, how many acts of kindness did you do?","","","","","",""],
["","","","but naw","","","","","",""],
["","","","he asked me what's my favorite kind of cereal","","","","","",""],
["","you","","huh","","","","","",""],
["","","","what is your favorite kind of cereal?","","","","","",""],
["","elijah","","honey bunches of oats, of course","","sean_interviewing",['wait_elijah1z', 'wait_elijah1a'],"","",""],
["wait_elijah1z","you","","cool!","","","null","","",""],
["wait_elijah1a","{sean}",['elijah_neutral', 'sean_neutral'],"maybe he's... planning a surprise cereal party!","_hide_wait_elijah&wait_sean","","","","",""],
["","","","where he makes everyone their favorite cereal, to make up for being stuck here for so long?","","natalie_interviewing",['wait_elijah1b', 'wait_elijah1c'],"","",""],
["wait_elijah1b","elijah","","well, it better be the best bowl of cereal i've ever had!","","","null","","",""],
["wait_elijah1c","natalie",['elijah_neutral', 'sean_neutral', 'natalie_neutral'],"honestly, it might be worth it for a nice bowl of lucky charms","_hide_wait_elijah&wait_sean&wait_natalie","","","","",""],
["","{sean}","","oh my god, with lots of marshmallows?","","","","","",""],
["","natalie","","are you kidding?","","","","","",""],
["","","","marshmallows ONLY","","","","","",""],
["","{sean}","","YESSSSS","","","","","",""],
["","","","MARSHMALLOW GANG","","","","","",""],
["","natalie","","HNNNNG MARSHMALLOW GANG","","","","","",""],
["","_none","","sean dabs.","","","","","",""],
["","elijah","","???","","","null","","",""],
["wait_elijah2","elijah","elijah_neutral","you know...","wait_talked_to_elijah2","","","","",""],
["","","","i never did find out what odontophorous means.","_delay_waited_once","numa_interviewing",['wait_elijah2a', 'wait_elijah2b'],"","",""],
["wait_elijah2a","you","","aw, that's too bad","","","","","",""],
["","","","maybe you should have asked lucifur","","","","","",""],
["","elijah","","dangit, i should have!","","","null","","",""],
["wait_elijah2b","{numa}",['elijah_neutral', 'numa_neutral'],"odontophorous?","_hide_wait_elijah&wait_numa","","","","",""],
["","","","you mean, relating to the projection in the mouth of snails and other mollusks that supports the radula?","","","","","",""],
["","elijah","","huh, is that what it means?","","","","","",""],
["","{numa}","","i thought everyone knew that ;;","","","","","",""],
["","you","","wait, what's a radula?","","","","","",""],
["","{numa}","","oh, um, it's like tiny teeth for snails!","","","","","",""],
["","","","they use them to scrape food off of surfaces","","","","","",""],
["","you","","that's freaky","","kyungsoon_interviewing or not kyungsoon_quest_complete",['wait_elijah2c', 'wait_elijah2d'],"","",""],
["wait_elijah2c","{numa}","","no it's not ;;","","","","","",""],
["","elijah","","it is a little freaky, sorry","","","","","",""],
["","{numa}","","):","","","null","","",""],
["wait_elijah2d","kyungsoon",['elijah_neutral', 'numa_neutral', 'kyungsoon_neutral'],"yeah, now imagine how it felt when i kissed her","_hide_wait_elijah&wait_numa&wait_kyungsoon","","","","",""],
["","{numa}","","K-KYUNGSOON!!","","","null","","",""],
["wait_elijah3","elijah","elijah_neutral","honestly...","wait_talked_to_elijah3","","","","",""],
["","","","it's hard to believe this is really happening.","_delay_waited_once","","","","",""],
["","you","","yeah?","","","","","",""],
["","elijah","","i've been here longer than anyone else, you know.","","","","","",""],
["","","","almost got used to this lot in death. almost did.","","","","","",""],
["","","","thought it would just be me and sean kicking the shit for eternity.","","","","","",""],
["","you","","oh yeah i can imagine","","","","","",""],
["","","","and here i am, having just arrived...","","","","","",""],
["","elijah","","yeah, man","","","","","",""],
["","","","you got off easy","","","","","",""],
["","you","","yep","","","","","",""],
["","elijah","","you'll probably go to heaven, too. you're a good egg.","","","","","",""],
["","you","","aw, thanks","","","null","","",""],
["wait_elijah4","elijah","elijah_neutral","tell you what.","wait_talked_to_elijah4","","","","",""],
["","","","i'm not even afraid.","_delay_waited_once","","","","",""],
["","you","","what's that?","","","","","",""],
["","elijah","","i mean i've stared down the barrel of death before, and i'll do it again!","","","","","",""],
["","","","ain't nothing left that lucifur can do to ole elijah.","","sean_interviewing",['wait_elijah4a', 'wait_elijah4b'],"","",""],
["wait_elijah4a","you","","that's the spirit!","","","","","",""],
["","elijah","","does he think hell is bad? ","","","","","",""],
["","","","i'd like to see him come on down to georgia and see how he fares!","","","","","",""],
["","you","","i think they wrote a song about that!","","","","","",""],
["","elijah","","huh?","","","","","",""],
["","","","oh","","","","","",""],
["","","","yeah, i guess they did","","","null","","",""],
["wait_elijah4b","sean",['elijah_neutral', 'sean_neutral'],"aw yeah, that's the spirit!!","_hide_wait_elijah&wait_sean","","","","",""],
["","elijah","","does he think hell is bad? ","","","","","",""],
["","","","i'd like to see him come on down to georgia and see how he fares!","","","","","",""],
["","you","","i think they wrote a song about that!","","","","","",""],
["","elijah","","huh?","","","","","",""],
["","","","oh","","","","","",""],
["","","","yeah, i guess they did","","","","","",""],
["","sean","","hey, elijah, you know","","","","","",""],
["","","","if we end up going different places... ","","","","","",""],
["","","","i'm gonna miss ya","","","","","",""],
["","elijah","","oh, i'd miss you too, man. i'd miss you too.","","","","","",""],
["","","","but let's not jump the gun yet.","","","","","",""],
["","sean","","yeah, we're probably all going to hell anyway","","","","","",""],
["","elijah","","heh, maybe so","","","null","","",""],
["wait_sean","","","_pass","",['player_called', 'wait_talked_to_sean4', 'wait_talked_to_sean3', 'wait_talked_to_sean2', 'wait_talked_to_sean1'],['wait_sean_encourage', 'wait_sean_dot', 'wait_sean4', 'wait_sean3', 'wait_sean2', 'wait_sean1'],"","",""],
["wait_sean1","","","_pass","","met_sean",['wait_sean_regular', 'wait_sean_intro'],"","",""],
["wait_sean_intro","you","sean_neutral","uh, hey, i don't think we've met!","met_sean","","","","",""],
["","","","i'm {player}","","","","","",""],
["","???","","heya!","","","","","",""],
["","sean","","sean's the name, lovin's the game ;)","","","","","",""],
["","","","how's purrgatory been treatin ya?","","","","","",""],
["","you","","um, could be worse!","","","","","",""],
["","","","especially since we might be about to escape","","","","","",""],
["","sean","","right on, dude","","","","","",""],
["","you","","do you think lucifur will pick you to leave?","","","","","",""],
["","sean","","oh, uhhh","","","wait_sean1x","","",""],
["wait_sean_regular","you","sean_neutral","so, do you think lucifur will pick you to leave?","","","","","",""],
["","sean","","oh uhhhh","","","","","",""],
["","","","probably not, if i'm gonna be honest","","","","","",""],
["","","","","","","","",['but you deserve it!', 'me neither'],['wait_sean1z', 'wait_sean1y']],
["wait_sean1z","you","","but you totally deserve it!","","","","","",""],
["","","","heaven, i mean","","","wait_sean1x","","",""],
["wait_sean1y","you","","yeah, me neither","","","wait_sean1x","","",""],
["wait_sean1x","sean","","idk bro","wait_talked_to_sean1","","","","",""],
["","","","i'm just a snerson","_delay_waited_once","","","","",""],
["","you","","what?","","","","","",""],
["","sean","","a snerson","","","","","",""],
["","","","trying to live his best snife","","elijah_interviewing",['wait_sean1a', 'wait_sean1b'],"","",""],
["wait_sean1a","you","","??????","","","null","","",""],
["wait_sean1b","elijah",['elijah_neutral', 'sean_neutral'],"sean, you always say that when you're avoiding a question","_hide_wait_elijah&wait_sean","","","","",""],
["","sean","","MEE?? SNAVOIDING A SNESTION??","","","","","",""],
["","","","I WOULD SNEVER","","","","","",""],
["","you","","ohh i get it now","","","","","",""],
["","","","like a snake person","","","","","",""],
["","sean","","snes","","","","","",""],
["","elijah","","[i]snigh[/i]","","","null","","",""],
["wait_sean2","sean","sean_neutral","you know, this place isn't all bad","wait_talked_to_sean2","","","","",""],
["","","","i'm gonna miss some parts of it","_delay_waited_once","","","","",""],
["","you","","like what?","","","","","",""],
["","sean","","like, you know","","","","","",""],
["","","","the piano..","","","","","",""],
["","","","drawing tally marks on all the walls...","","","","","",""],
["","you","","that was you??","","","","","",""],
["","sean","","oliver's butt tattoo...","","","","","",""],
["","you","","wait","","","","","",""],
["","","","sorry, oliver's what??","","oliver_interviewing",['wait_sean2a', 'wait_sean2b'],"","",""],
["wait_sean2a","sean","","you heard me :P","","","","","",""],
["","you","","how do you even know...?","","","","","",""],
["","sean","","how do you think? ;)","","","null","","",""],
["wait_sean2b","oliver",['sean_neutral', 'oliver_neutral'],"[i]please[/i], let's not talk about that","_hide_wait_oliver&wait_sean","","","","",""],
["","you","","how do you even know...?","","","","","",""],
["","sean","","how do you think? ;)","","","null","","",""],
["wait_sean3","sean","sean_neutral","hey","wait_talked_to_sean3","","","","",""],
["","","","have you tried poking the frog","_delay_waited_once","","","","",""],
["","you","","hm?","","","","","",""],
["","_none","","sean pokes the frog.","","","","","",""],
["","frog","","glunk","glunk","","","","",""],
["","you","","omg","","","","","",""],
["","","","do it again","","","","","",""],
["","frog","","glunk","glunk","natalie_interviewing",['wait_sean3d', 'wait_sean3z'],"","",""],
["wait_sean3z","natalie",['sean_neutral', 'natalie_neutral'],"o shit waddup","_hide_wait_natalie&wait_sean","","","","",""],
["","","","","","","","",['here come dat boi', 'what?'],['wait_sean3a', 'wait_sean3b']],
["wait_sean3a","you","","here come dat boi","","","wait_sean3c","","",""],
["wait_sean3b","you","","what?","","","wait_sean3c","","",""],
["wait_sean3c","sean","","oh my god that meme is so oLD","","","","","",""],
["","natalie","","no way dude","","","","","",""],
["","","","that was the freshest meme when i died","","","","","",""],
["","sean","","wtf??","","","","","",""],
["","","","are you literally a fossil??","","","","","",""],
["","natalie","","alright wise guy, if ur future memes are so good then tell us one","","","","","",""],
["","sean","","they're not funny if you don't know about them yet!","","","","","",""],
["","natalie","","try me","","","","","",""],
["","","","i'll find anything funny","","","","","",""],
["","sean","","hmmmmmmm","","","","","",""],
["","","","tide pods?","","","","","",""],
["","natalie","","which are...?","","","","","",""],
["","sean","","they're like laundry detergent pods, but they kind of look like candy?","","","","","",""],
["","","","so people started joking about eating them","","","","","",""],
["","","","and then tide had to release a statement saying like, please do not eat tide pods?","","","","","",""],
["","natalie","","damn are future people stupid","","","","","",""],
["","sean","","idk man, i guess so","","","","","",""],
["","you","","you know... sean dying the year of tide pods is kind of suspicious...","","","","","",""],
["","sean","","hey!","","","null","","",""],
["wait_sean3d","you","","why does it sound like that?","","","","","",""],
["","sean","","beats me","","","","","",""],
["","","","dumbass devil can't even get the frog to sound right","","","null","","",""],
["wait_sean4","sean","sean_neutral","...","wait_talked_to_sean4","","","","",""],
["","you","","something on ur mind?","_delay_waited_once","","","","",""],
["","sean","","nah","","","","","",""],
["","","","i'm just chilling","","","","","",""],
["","","","over here","","","","","",""],
["","","","me and this chair","","","","","",""],
["","you","","are u sure?","","sean_quest_complete",['wait_sean4b', 'wait_sean4a'],"","",""],
["wait_sean4a","sean","","yeah, it's nothing man","","","","","",""],
["","","","...","","","","","",""],
["","","","just, uh","","","","","",""],
["","","","hope you get to heaven, bro","","","","","",""],
["","you","","oh, thank you!","","","","","",""],
["","sean","","mhm","","","","","",""],
["","","","and the frog too","","","","","",""],
["","frog","","glunk","glunk","","null","","",""],
["wait_sean4b","sean","","...","","","","","",""],
["","","","wellllll","","","","","",""],
["","","","i was just sorta thinking","","","","","",""],
["","","","that i really need to go to heaven","","","","","",""],
["","you","","aw, i hope you--","","","","","",""],
["","sean","","no no no listen","","","","","",""],
["","","","it's not cus i'm afraid of hell or anything","","","","","",""],
["","","","honestly i bet people have more fun down in hell than whatever they do in heaven all day","","","","","",""],
["","","","playin the harp or whatever","","","","","",""],
["","","","i'm just thinkin","","","","","",""],
["","","","if i ever want a chance to see dani again...","","","","","",""],
["","you","","ahh, i understand","","","","","",""],
["","sean","","yeah man","","","","","",""],
["","","","idk","","","","","",""],
["","","","i'm just","","","","","",""],
["","","","i'm scared i fucked up my chances while i was alive and now it's too late to fix it","","","","","",""],
["","you","","listen, you'll be fine!","","","","","",""],
["","","","i mean, dani must have seen something in you, right?","","","","","",""],
["","sean","","heh, guess so","","","","","",""],
["","you","","you'll see them again someday!","","","","","",""],
["","","","maybe you'll even be able to play them that song","","","","","",""],
["","sean","","what song?","","","","","",""],
["","you","","you know","","","","","",""],
["","","","[i]i'm stuck in purrgatory toooo~[/i]","purrgatory_blues1","","","","",""],
["","sean","","OH YEAH!!","","","","","",""],
["","","","i bet that'll be a big hit in heaven haha","","","","","",""],
["","you","","totally","","","","","",""],
["","sean","","yeah","","","","","",""],
["","","","...","","","null","","",""],
["wait_tori","","","_pass","",['player_called', 'wait_talked_to_tori4', 'wait_talked_to_tori3', 'wait_talked_to_tori2', 'wait_talked_to_tori1'],['wait_tori_encourage', 'wait_tori_dot', 'wait_tori4', 'wait_tori3', 'wait_tori2', 'wait_tori1'],"","",""],
["wait_tori1","","","_pass","","met_tori",['wait_tori_regular', 'wait_tori_intro'],"","",""],
["wait_tori_intro","you","tori_neutral","um, hello!","met_tori","","","","",""],
["","???","","{player}, nice to meet you.","","","","","",""],
["","","","my name is tori.","","","","","",""],
["","you","","wait, how did you know my...","","","","","",""],
["","tori","","i've been looking forward to meeting you, but i'm afraid there are more pressing issues at hand.","","","","","",""],
["","","","i just finished drawing up the battle plans.","","","wait_tori_asdf","","",""],
["wait_tori_regular","tori","tori_neutral","hey, {player}. ","","","","","",""],
["","","","great timing. i just finished drawing up the battle plans.","","","","","",""],
["wait_tori_asdf","you","","sorry, the... battle plans?","wait_talked_to_tori1","","","","",""],
["","tori","","yes.","_delay_waited_once","","","","",""],
["","you","","do you care to elaborate?","","","","","",""],
["","tori","","no time.","","","","","",""],
["","","","hey folks! we need to have a meeting. get over here.","","sean_interviewing",['wait_tori1b', 'wait_tori1a'],"","",""],
["wait_tori1a","{sean}",['tori_neutral', 'sean_neutral'],"oh, boy, here we go again","_hide_wait_tori&wait_sean","","","","",""],
["","tori","","this is important!","","natalie_interviewing",['wait_tori1b1', 'wait_tori1b'],"","",""],
["wait_tori1b","natalie",['tori_neutral', 'natalie_neutral'],"what is it, boss?","_hide_wait_tori&wait_natalie","","wait_tori1b2","","",""],
["wait_tori1b1","elijah",['tori_neutral', 'elijah_neutral'],"what is it, boss?","_hide_wait_tori&wait_elijah","","wait_tori1b2","","",""],
["wait_tori1b2","tori","","what is [i]it[/i]?","","","","","",""],
["","","","what is [i]it[/i] but our very fates hanging in balance?","","","","","",""],
["","","","our fleeting afterlives dangling over a pit of despair?","","natalie_interviewing",['wait_tori1d', 'wait_tori1c'],"","",""],
["wait_tori1c","natalie",['tori_neutral', 'natalie_neutral'],"uh, sorry boss, still confused","_hide_wait_tori&wait_natalie","","wait_tori1e","","",""],
["wait_tori1d","elijah",['tori_neutral', 'elijah_neutral'],"...sorry, could you run that by me again?","_hide_wait_tori&wait_elijah","","wait_tori1e","","",""],
["wait_tori1e","tori","","what i'm saying is, we can't just let lucifur walk all over us!","","","","","",""],
["","","","more than ever, we need a plan.","","","","","",""],
["","","","there's eight of us and one of him. if we work together, then we can take him on!","","","","","",""],
["","","","now are you a mouse, or a man?!","","oliver_interviewing",['wait_tori1f', 'wait_tori1e1'],"","",""],
["wait_tori1e1","oliver",['tori_neutral', 'oliver_neutral'],"uh--","_hide_wait_tori&wait_oliver","kyungsoon_interviewing",['wait_tori1h', 'wait_tori1f'],"","",""],
["wait_tori1f","kyungsoon",['tori_neutral', 'kyungsoon_neutral'],"hell yeah, let's just jump him","_hide_wait_tori&wait_kyungsoon","sean_interviewing",['wait_tori1h', 'wait_tori1g'],"","",""],
["wait_tori1g","{sean}",['tori_neutral', 'kyungsoon_neutral', 'sean_neutral'],"i'm in!","_hide_wait_tori&wait_kyungsoon&wait_sean","","","","",""],
["","","","i'll hold his scrawny little arms behind his back while you punch him","","","","","",""],
["","kyungsoon","","deal","","","","","",""],
["wait_tori1h","you","","wait wait wait","","","","","",""],
["","","","but doesn't he have magic powers or something?","","","","","",""],
["","tori","","hmm... true. he can turn into a cat.","","","","","",""],
["","","","what if he just wriggles out of our grasp?","","numa_interviewing",['wait_tori1j', 'wait_tori1i'],"","",""],
["wait_tori1i","{numa}",['tori_neutral', 'numa_neutral'],"oh... i don't think i could hurt a cat...","_hide_wait_tori&wait_numa","natalie_interviewing",['wait_tori1k', 'wait_tori1j'],"","",""],
["wait_tori1j","natalie",['tori_neutral', 'natalie_neutral'],"plus i'm allergic","_hide_wait_tori&wait_natalie","","","","",""],
["wait_tori1k","_none",['tori_neutral', 'lucifur_neutral'],"lucifur pokes his head out of the library.","_hide_wait_tori","","","","",""],
["","lucifur","","hello, children!","","","","","",""],
["","","","just a friendly reminder that fomenting revolution is strictly against company policy and could get you a very long stint in the 4th circle of hell.","","","","","",""],
["","you","","what... what does the 4th circle look like?","","","","","",""],
["","lucifur","","the better question is... what does it [i]smell[/i] like?","","","","","",""],
["","","","yeah. not so eager now, huh?","","","","","",""],
["","","","now, where was i...","","","","","",""],
["","tori","tori_neutral","...","","","","","",""],
["","you","","...","","natalie_interviewing",['wait_tori1m', 'wait_tori1l'],"","",""],
["wait_tori1l","natalie",['tori_neutral', 'natalie_neutral'],"welp. meeting adjourned?","_hide_wait_tori&wait_natalie","","wait_tori1n","","",""],
["wait_tori1m","{sean}",['tori_neutral', 'sean_neutral'],"welp. meeting adjourned?","_hide_wait_tori&wait_sean","","wait_tori1n","","",""],
["wait_tori1n","tori","","yes, i suppose.","","","","","",""],
["","","tori_neutral","didn't even get to use the diagrams...","_hide_wait_tori","","","","",""],
["","","","","","","","",['good try though', 'maybe you should just go along with it'],['wait_tori1o', 'wait_tori1p']],
["wait_tori1o","you","","i thought that was a very good attempt to foment revolution, all things considered!","","","","","",""],
["","tori","","thanks. i appreciate that.","","","null","","",""],
["wait_tori1p","you","","maybe you should just go along with what he says, for now?","","","","","",""],
["","","","i don't want you to be turned into a frog, or anything","","","","","",""],
["","tori","","your concern is duly noted.","","","null","","",""],
["wait_tori2","tori","tori_neutral","{player}! watch out!","wait_talked_to_tori2","","","","",""],
["","you","","aah! ","_delay_waited_once","","","","",""],
["","","","what is it??","","","","","",""],
["","tori","","nothing. just keeping you on your toes.","","","","","",""],
["","","","it's crucial that we stay alert right now. anything could happen, and we need to be prepared.","","","","","",""],
["","you","","oh...","","","","","",""],
["","","","geez... okay...","","oliver_interviewing",['wait_tori2b', 'wait_tori2a'],"","",""],
["wait_tori2a","oliver",['tori_neutral', 'oliver_neutral'],"hey, tori. sorry to interrupt, but i was wondering--","_hide_wait_tori&wait_oliver","","","","",""],
["","tori","","OLIVER! BEHIND YOU!","","","","","",""],
["","oliver","","huh? what??","","","","","",""],
["","tori","","HIT THE DECK, KID!","","","","","",""],
["","","","IT COULD HIT AT ANY MOMENT!!","","","","","",""],
["","oliver","tori_neutral","AAA OKAY","","","null","","",""],
["wait_tori2b","sean",['tori_neutral', 'sean_neutral'],"hey, tori my gal, i was wondering if--","_hide_wait_tori&wait_sean","","","","",""],
["","tori","","SEAN! BEHIND YOU!","","","","","",""],
["","sean","","huh? what??","","","","","",""],
["","tori","","HIT THE DECK, KID!","","","","","",""],
["","","","IT COULD HIT AT ANY MOMENT!!","","","","","",""],
["","sean","tori_neutral","AAA OKAY","","","null","","",""],
["wait_tori3","tori","tori_neutral","i have my plan all figured out.","wait_talked_to_tori3","","","","",""],
["","","","oh yes, things are looking up for ol' tori peck.","_delay_waited_once","","","","",""],
["","","","do you want to know what it is?","","","","","",""],
["","you","","uh, sure!","","","","","",""],
["","tori","","i'm going to make lucifur a proposal.","","","","","",""],
["","","","i'm the ideal business partner! ","","","","","",""],
["","","","profit-minded. efficient. thorough.","","","","","",""],
["","","","and my worst trait? being a perfectionist.","","","","","",""],
["","","","in fact, i already have a few ideas to make hell inc a nice buck.","","","","","",""],
["","","","parched from sitting around in purrgatory? buy our fresh, lucifur-brand orange soda!","","","","","",""],
["","","","tired of working off your sins? pay a small premium fee to get into the purrgatory fast lane™!","","","","","",""],
["","you","","uhhh","","","","","",""],
["","","","that sounds...","","","","","",""],
["","","","","","","","",['evil', 'cool i guess'],['wait_tori3a', 'wait_tori3b', 'wait_tori3c']],
["wait_tori3a","you","","i mean... trying to profit off of people waiting in purrgatory...","","","","","",""],
["","","","that seems kind of... evil?","","","","","",""],
["","tori","","exactly!","","","","","",""],
["","","","lucifur will eat it up!","","","","","",""],
["","you","","no, like","","","","","",""],
["","","","evil as in... you really shouldn't do that?","","","","","",""],
["","","","besides, no one in purrgatory has money in the first place","","","wait_tori3c","","",""],
["wait_tori3b","you","","cool? i guess?","","","","","",""],
["","tori","","i'll admit, it's a bit nefarious, but that's exactly why lucifur will eat it up!","","","","","",""],
["","","","what can i say? ","","","","","",""],
["","","","blame the game, not the player.","","","","","",""],
["","you","","but... does anyone in purrgatory have money in the first place?","","","","","",""],
["wait_tori3c","tori","","hm.","","","","","",""],
["","","","that's a good point.","","","","","",""],
["","","","well, let's call it a work in progress.","","","null","","",""],
["wait_tori4","tori","tori_neutral","...","wait_talked_to_tori4","","","","",""],
["","","","hey, {player}. ","_delay_waited_once","","","","",""],
["","you","","hiya","","","","","",""],
["","tori","","you know, it's a little strange.","","","","","",""],
["","","","i've been looking for a way to escape all these years.","","","","","",""],
["","","","then lucifur shows up and says, hey, you can leave now.","","","","","",""],
["","","","you don't think i've been wasting my time, do you?","","","","","",""],
["","you","","no, not at all!","","","","","",""],
["","","","i mean","","","","","",""],
["","","","it's not like there's anything really productive to do down here anyway?","","","","","",""],
["","tori","","maybe for [i]you[/i].","","","","","",""],
["","","","i could have been honing my karate.","","","","","",""],
["","","","i'm probably horribly out of shape.","","natalie_interviewing",['wait_tori4b', 'wait_tori4a'],"","",""],
["wait_tori4a","natalie",['tori_neutral', 'natalie_neutral'],"oh yeah, you know karate, right?","_hide_wait_tori&wait_natalie","","","","",""],
["","tori","","do i [i]know[/i] karate?","","","","","",""],
["","","","does a cat know how to meow?","","","","","",""],
["","","","does a frog know how to croak??","","","","","",""],
["","natalie","","i think... yes?","","","","","",""],
["","tori","","yes. i know karate.","","","","","",""],
["","","","in fact, i happen to be a 2nd dan black belt.","","","","","",""],
["","natalie","","cool!!","","","","","",""],
["","","","can you teach me a karate kick or something?","","","","","",""],
["","tori","","hah!","","","","","",""],
["","","","before you learn to kick, you must learn how to stand.","","","","","",""],
["","","","a proper stance gives you balance. it allows you to strike with power and to defend with ease.","","","","","",""],
["","","","take for example the heisoku-dachi. perhaps the most basic of stances, used as a ready stance in some kata.","","","","","",""],
["","","","your feet must be together at your heels and toes. back and neck straight. pelvis upward.","","","","","",""],
["","","","perhaps most importantly: be present, mentally and physically.","","","","","",""],
["","natalie","","am -- am i doing it right??","","","","","",""],
["","tori","","arms out, natalie!","","","","","",""],
["","natalie","","eep sorry","","","","","",""],
["","tori","","and don't be so tense!","","","","","",""],
["","natalie","","im sorry but this doesn't really feel like i'm doing karate","","","","","",""],
["","tori","","well, you're NOT, unless you straighten those shoulders!","","","","","",""],
["","_none","","you have a feeling that tori has forgotten about you.","","","null","","",""],
["wait_tori4b","oliver",['tori_neutral', 'oliver_neutral'],"oh yeah, you know karate, right?","_hide_wait_tori&wait_oliver","","","","",""],
["","tori","","do i [i]know[/i] karate?","","","","","",""],
["","","","does a cat know how to meow?","","","","","",""],
["","","","does a frog know how to croak??","","","","","",""],
["","oliver","","actually, only male frogs croak! ","","","","","",""],
["","","","female frogs lack the vocal sacs that allow frogs to make that distinctive \"croaking\" noise, and in fact... um...","","","","","",""],
["","","","sorry, you were saying?","","","","","",""],
["","tori","","yes. i know karate.","","","","","",""],
["","","","in fact, i happen to be a 2nd dan black belt.","","","","","",""],
["","you","","that's pretty cool!","","","","","",""],
["","oliver","","agreed!","","","","","",""],
["","","","do you think you could teach me a karate kick or something?","","","","","",""],
["","tori","","hah!","","","","","",""],
["","","","before you learn to kick, you must learn how to stand.","","","","","",""],
["","","","a proper stance gives you balance. it allows you to strike with power and to defend with ease.","","","","","",""],
["","","","take for example the heisoku-dachi. perhaps the most basic of stances, used as a ready stance in some kata.","","","","","",""],
["","","","your feet must be together at your heels and toes. back and neck straight. pelvis upward.","","","","","",""],
["","","","perhaps most importantly: be present, mentally and physically.","","","","","",""],
["","oliver","","am -- am i doing it right?","","","","","",""],
["","tori","","arms out, oliver!","","","","","",""],
["","oliver","","sorry, sorry!","","","","","",""],
["","tori","","and don't be so tense!","","","","","",""],
["","oliver","","i have to say, this doesn't really feel like i'm doing karate...","","","","","",""],
["","tori","","well, you're NOT, unless you straighten those shoulders!","","","","","",""],
["","_none","","you have a feeling that tori has forgotten about you.","","","null","","",""],
["wait_natalie","","","_pass","",['player_called', 'wait_talked_to_natalie4', 'wait_talked_to_natalie3', 'wait_talked_to_natalie2', 'wait_talked_to_natalie1'],['wait_natalie_encourage', 'wait_natalie_dot', 'wait_natalie4', 'wait_natalie3', 'wait_natalie2', 'wait_natalie1'],"","",""],
["wait_natalie1","natalie","natalie_neutral","so listen","wait_talked_to_natalie1","","","","",""],
["","","","i've been workin on a theory","_delay_waited_once","","","","",""],
["","","","and this might sound crazy","","","","","",""],
["","","","but what if purrgatory is cat heaven?","","","","","",""],
["","you","","you mean like heaven for cats?","","","","","",""],
["","natalie","","yeah like... cat heaven","","","","","",""],
["","you","","hmmmmm","","","","","",""],
["","","","that would explain all the catnip and milk and stuff","","","","","",""],
["","natalie","","and the cat bed","","","","","",""],
["","you","","but if purrgatory is cat heaven, then where are all the cats?","","","","","",""],
["","natalie","","hmmm, that's a good point","","","","","",""],
["","","","and why put people in it?","","","","","",""],
["","","","why not build a separate purrgatory for people?","","","","","",""],
["","you","","a persontory, if you will","","","","","",""],
["","natalie","","a person tori","","tori_interviewing",['wait_natalie1b', 'wait_natalie1a'],"","",""],
["wait_natalie1a","{tori}",['natalie_neutral', 'tori_neutral'],"yes? do you need something?","_hide_wait_tori&wait_natalie","","","","",""],
["","natalie","","oh sorry, me and {player} were just discussing the nature of purrgatory!","","","","","",""],
["","you","","persontory, you mean","","","","","",""],
["","{tori}","","[i]sigh[/i]","","","","","",""],
["","","","maybe the real purrgatory is the friends we made along the way.","","","","","",""],
["","natalie","","aw, that's so sweet!","","","","","",""],
["","","","...","","","","","",""],
["","","","wait","","","null","","",""],
["wait_natalie1b","you","","yeah","","","","","",""],
["","natalie","","it's a mystery","","","null","","",""],
["wait_natalie2","natalie","natalie_neutral","do you think bees eat their own honey?","wait_talked_to_natalie2","","","","",""],
["","you","","uhhh","_delay_waited_once","","","","",""],
["","","","","","","","",['no', 'yes'],['wait_natalie2a', 'wait_natalie2b']],
["wait_natalie2a","you","","nnnnnno?","","","","","",""],
["","","","why would they make honey and then just eat it?","","","","","",""],
["","natalie","","what else would they use it for?","","","","","",""],
["","you","","idk, building beehives?","","numa_interviewing",['wait_natalie2d', 'wait_natalie2e'],"","",""],
["wait_natalie2b","you","","yyyyyyes?","","","","","",""],
["","","","why would they make honey and then just not eat it?","","","","","",""],
["","natalie","","idk, maybe they use it for something else","","","","","",""],
["","you","","like what?","","","","","",""],
["","","","building beehives?","","numa_interviewing",['wait_natalie2d', 'wait_natalie2e'],"","",""],
["wait_natalie2d","natalie","","no no no, you have it all wrong","","","","","",""],
["","","","that's what beeswax is for","","","","","",""],
["","you","","ohhh yeah","","","","","",""],
["","","","wait","","","","","",""],
["","","","so do bees make both honey AND wax?","","","","","",""],
["","natalie","","yeah i guess?","","","","","",""],
["","you","","then... what is nectar??","","","","","",""],
["","natalie","","oh geez, idk","","","","","",""],
["","you","","why is this the question that you're asking anyway?","","","","","",""],
["","natalie","","idk, it's just been [i]bug[/i]-ging me","","","","","",""],
["","you","","ah so you're just [i]bee[/i]-ing curious","","","","","",""],
["","natalie","","yeah i just [i]wasp[/i] to know","","","","","",""],
["","","","also humor is my coping mechanism in stressful situations","","","","","",""],
["","you","","oh, i see","","","null","","",""],
["wait_natalie2e","natalie",['numa_neutral', 'natalie_neutral'],"no no no, you have it all wrong",[['_anim_numa_creeping1', true], ['_hide_wait_natalie&wait_numa', true]],"","","","",""],
["","","","that's what beeswax is for","","","","","",""],
["","you","","ohhh yeah","","","","","",""],
["","","","wait","_anim_numa_creeping2","","","","",""],
["","","","so do bees make both honey AND wax?","","","","","",""],
["","natalie","","yeah i guess?","","","","","",""],
["","you","","then... what is nectar??","","","","","",""],
["","natalie","","oh geez, idk","_anim_numa_creeping3","","","","",""],
["","you","","...","","","","","",""],
["","","","um","","met_numa",['wait_natalie2g', 'wait_natalie2f'],"","",""],
["wait_natalie2f","you","","hello","","","wait_natalie2h","","",""],
["wait_natalie2g","you","","hi numa","","","wait_natalie2h","","",""],
["wait_natalie2h","{numa}","","oh... hello...","","","","","",""],
["","","","i'm sorry for butting in, but i couldn't help but overhear...","","","","","",""],
["","","","are you talking about bees??","","","","","",""],
["","natalie","","hell yeah","","","","","",""],
["","","","hit us with a bug fact numes, i know you have a ton of them","","","","","",""],
["","{numa}","","get this...","","","","","",""],
["","","","bees have such a good sense of smell, they've been trained to sniff out hidden land mines in croatia!","","","","","",""],
["","you","","wow!","","","","","",""],
["","{numa}","","bee fact :)","_delay__anim_default","","null","","",""],
["wait_natalie3","you","natalie_neutral","wasup?","wait_talked_to_natalie3","","","","",""],
["","natalie","","you know, just waiting for lucifur to deliver judgement upon me","_delay_waited_once","","","","",""],
["","you","","ah. same here.","","","","","",""],
["","natalie","","see i don't think i did anything [i]bad[/i]","","","","","",""],
["","","","i just don't think i did a lot of good things either","","","","","",""],
["","","","mostly i just slept a lot","","","","","",""],
["","you","","there's nothin wrong with that!","","","","","",""],
["","natalie","","mmm i guess","","","","","",""],
["","you","","in fact, maybe taking a nap would help ease your nerves?","","","","","",""],
["","natalie","","nah man","","","","","",""],
["","","","i'm way to amped up right now to sleep","","","","","",""],
["","you","","oh, yeah i guess that makes sense","","","","","",""],
["","natalie","","appreciate it, though","","","null","","",""],
["wait_natalie4","natalie","natalie_neutral","this is a [i]hell[/i] of a situation, huh?","wait_talked_to_natalie4","","","","",""],
["","you","","yeah i [i]heaven[/i]'t been this excited in years","_delay_waited_once","","","","",""],
["","natalie","","yeah i'm basically on [i]cloud[/i] nine right now","","","","","",""],
["","you","","i'm having a [i]devil[/i] of a time right now","","","","","",""],
["","natalie","","a real [i]halo[/i]-f a time","","","","","",""],
["","you","","i'm just [i]wing[/i]-ing it at this point","","","","","",""],
["","natalie","","i'm living on a [i]prayer[/i]","","","","","",""],
["","you","","i hope i can [i]horn[/i] my way into heaven","","","","","",""],
["","natalie","","i hope...","","","","","",""],
["","","","...","","","","","",""],
["","","","i hope lucifur doesn't [i]demon[/i]-itize my youtube videos","","","","","",""],
["","you","","nice","","","","","",""],
["","_none",['natalie_neutral', 'lucifur_neutral'],"lucifur pokes his head out of the library.","","","","","",""],
["","lucifur","","could you kids keep it down out there??","","","","","",""],
["","natalie","","yeah, not so fun when you're on the receiving end, is it???","","","null","","",""],
["lucifur_calls_player","_none","_none","sean saunters out of the library, shrugging his jacket on. lucifur yells from inside.","","","","","",""],
["","lucifur","","ahem, alright! last but not least...","","","","","",""],
["","","","{player}!","","","","","",""],
["","you","","oh, okay","_delay_remove_sean_interviewing","","","","",""],
["","","","coming!","player_called","","null","","",""],
["wait_kyungsoon_encourage","kyungsoon","kyungsoon_neutral","...","","","","","",""],
["","","","good luck","","","","","",""],
["","you","","thanks","","","null","","",""],
["wait_oliver_encourage","oliver","oliver_neutral","you've got this, {player}!","","","","","",""],
["","you","","heh, i hope so","","","null","","",""],
["wait_numa_encourage","numa","numa_neutral","um, good luck!","","","","","",""],
["","you","","thanks, you too!","","","","","",""],
["","","","...","","","","","",""],
["","","","wait, sorry","","","","","",""],
["","numa","","omg it's okay, i do that all the time","","","","","",""],
["","you","","oh my god isn't it the worst?","","","","","",""],
["","lucifur","","{player}!!","","","","","",""],
["","you","","eep, coming!","","","null","","",""],
["wait_sean_encourage","sean","sean_neutral","don't even sweat it dude, you got this","","","","","",""],
["","you","","thanks dude","","","null","","",""],
["wait_elijah_encourage","elijah","elijah_neutral","godspeed my friend","","","","","",""],
["","you","","thank you, thank you","","","null","","",""],
["wait_tori_encourage","tori","tori_neutral","get in there and show that devil what you're made of.","","","","","",""],
["","you","","yes ma'am!","","","null","","",""],
["wait_natalie_encourage","natalie","natalie_neutral","go kick lucifur's butt","","","","","",""],
["","you","","oh i will","","","null","","",""],
["lucifur_library","","","_pass","","player_called",['lucifur_meeting', 'lucifur_exit'],"","",""]
]