extends Node

var raw_blocks = [
["flowers_init","_none","_none","_pass","","not flowers_played_once",['flowers_first', 'flowers_repeat'],"","",""],
["flowers_first","you","_none","oh god, it smells really bad back here","numa_goto_flowerbed","","","","",""],
["","numa","","i know, the flowers in purrgatory have kind of a weird smell","flowers_played_once","","","","",""],
["","","","just try to hold your breath, i guess ;;","","","","","",""],
["","you","","i'll try...","","","","","",""],
["","","","what do you need me to do?","","","","","",""],
["","numa","","well like i said, i always have a hard time finding the exact flower i'm looking for...","","","","","",""],
["","","","if i describe what flower i need, could you find it for me?","","","","","",""],
["","you","","okay, but we're gonna have to be quick","","","","","",""],
["","","","i don't think i can stand the smell for long","","","","","",""],
["","numa","","alright, we'll be quick!","","","","","",""],
["","","","i just need 8 flowers, if that's okay","","","","","",""],
["","you","","let's do it!","flower_start_flag","","null","","",""],
["flowers_fail","you","_none","argh, i can't do it any more","increment_flower_fails","","","","",""],
["","","","it just smells too bad","","","","","",""],
["","numa","","aaa i'm sorry","","","","","",""],
["","you","","it's okay!","","","","","",""],
["","","","let's try again later","","","","","",""],
["","numa","","okay ;;","","","","","",""],
["","you","numa_neutral","i don't know how you do that regularly","flowers_goto_garden","","","","",""],
["","numa","","i mean, you get used to it, haha","","","","","",""],
["","","","kind of...","","","","","",""],
["","you","","sorry i couldn't help more","","","","","",""],
["","numa","","it's fine...","","","null","","",""],
["flowers_succeed","numa","_none","that's all of them!","numa_finished_flowers","","","","",""],
["","you","","woo, we did it!","","","","","",""],
["","numa","","thank you so much for your help, {player}...","","","","","",""],
["","","","this is going to save me a lot of work :)","","","","","",""],
["","you","","glad to help!","","","","","",""],
["","you","numa_neutral","so, the flowers are settled now?","flowers_goto_garden","","","","",""],
["","numa","","yeah, i think so!","","","","","",""],
["","","","i'll start arranging them asap","","","","","",""],
["","","","they're going to look so beautiful in a bouquet!!","","","","","",""],
["","you","","awesome!","","","","","",""],
["","numa","","unless...","","","","","",""],
["","","","what if kyungsoon doesn't like flowers?","","","","","",""],
["","","","what if she absolutely HATES flowers?","","","","","",""],
["","","","what if she's allergic to flowers and that's why she died??","","","","","",""],
["","","","oh no, i'm an idiot, why didn't i think of that earlier?","","","","","",""],
["","you","","no no, don't start second-guessing yourself now!","","","","","",""],
["","","","i'm sure she's going to love them","","","","","",""],
["","numa","","okay...","","","","","",""],
["","","","i guess you're right...","","","null","","",""],
["flowers_repeat","you","_none","ugh, i forgot how bad it smells","numa_goto_flowerbed","","","","",""],
["","numa","","i know, i know, sorry","","","","","",""],
["","","","ready to start?","","","","","",""],
["","you","","ready!","flower_start_flag","","null","","",""]
]