extends Node

var raw_blocks = [
["kyungsoon_heaven","","","_pass","","talked_to_kyungsoon_heaven",['kyungsoon_heaven2', 'kyungsoon_heaven1'],"","",""],
["kyungsoon_heaven1","kyungsoon","kyungsoon_neutral","...","talked_to_kyungsoon_heaven","","","","",""],
["","you","","what's up?","","","","","",""],
["","kyungsoon","","we're in heaven","","","","","",""],
["","you","","sure are","","","","","",""],
["","kyungsoon","","...","","","","","",""],
["","","","think they have any good korean food here?","","","","","",""],
["","you","","oh, yeah","","","","","",""],
["","","","probably the best","","","","","",""],
["","kyungsoon","","good","","","","","",""],
["","numa",['kyungsoon_neutral', 'numa_neutral'],"numa appears with an armful of greens.","_hide_kyungsoon_heaven&numa_heaven","","","","",""],
["","","","KYUNGSOON!! LOOK AT THIS!!","","","","","",""],
["","kyungsoon","","oh, cool leaves","","","","","",""],
["","numa","","they have an edible garden! there's a sign that says you can take all you want!!!","","","","","",""],
["","","","hold on, is that--","","","","","",""],
["","","","[i]GASP[/i]","","","","","",""],
["","_none","kyungsoon_neutral","numa drops the vegetables and runs off in another direction.","","","","","",""],
["","kyungsoon","","...","","","","","",""],
["","","","what's an edible garden?","","","","","",""],
["","you","","iuno","","","","","",""],
["","","","i guess like a garden that's edible?","","","","","",""],
["","kyungsoon","","wow ","","","","","",""],
["","","","i never would have guessed","","","","","",""],
["","_none","","numa's voice floats through the air.","","","","","",""],
["","numa","","AAAAAAAAAAA","","","","","",""],
["","","","THEY HAVE SWISS CHARD!!","","","","","",""],
["","kyungsoon","","swiss what?","","","","","",""],
["","_none",['kyungsoon_neutral', 'numa_neutral'],"numa appears again with an bundle of leaves.","","","","","",""],
["","numa","","SWISS CHAAARD!","","","","","",""],
["","","","kyungsoon, {player}, do you want some??","","","","","",""],
["","you","","i'm good!","","","","","",""],
["","kyungsoon","","no thanks","","","","","",""],
["","numa","","aw, you're really missing out!!!","","","","","",""],
["","_none","","numa chomps on a leaf gleefully.","","","","","",""],
["","kyungsoon","","...","","","","","",""],
["","","","okay, i'll have one","","","","","",""],
["","","","if you're that excited about a leaf then it must be pretty good","","","","","",""],
["","numa","","yay!!!","","","null","","",""],
["kyungsoon_heaven2","kyungsoon","kyungsoon_neutral","...","","","","","",""],
["","","","this is nice","","","null","","",""],
["numa_heaven","","","_pass","","talked_to_numa_heaven",['numa_heaven2', 'numa_heaven1'],"","",""],
["numa_heaven1","numa","numa_neutral","{player}!!!","talked_to_numa_heaven","","","","",""],
["","","","this place is amazing!!","","","","","",""],
["","","","aaa it's so green and lush and vibrant :)","","","","","",""],
["","you","","yeah, it's pretty awesome!","","","","","",""],
["","numa","","and this is just the entry hall, too!","","","","","",""],
["","you","","wait, really?","","","","","",""],
["","numa","","yeah, i think the gate to heaven proper is up ahead!","","","","","",""],
["","","","but i feel like i could spend a lifetime right here and then some","","numa_mentioned_ph_strips",['numa_heaven1a', 'numa_heaven1b'],"","",""],
["numa_heaven1a","you","","did you ever find any ph strips?","","","","","",""],
["","numa","","funny you should mention that!","","","","","",""],
["","","","beause, as a matter of fact...","","","","","",""],
["","_none","","numa pulls out two fistfuls of colored strips from her pockets.","","","","","",""],
["","numa","","YES I DID!!!","","","null","","",""],
["numa_heaven1b","you","","you must really like this garden, huh?","","","","","",""],
["","numa","","of course!","","","","","",""],
["","","","and the best part is...","","","","","",""],
["","_none","","numa pulls out two fistfuls of colored strips from her pockets.","","","","","",""],
["","numa","","IT HAS PH STRIPS!!","","","","","",""],
["","you","","oh cool!","","","null","","",""],
["numa_heaven2","numa","numa_neutral","thank you again, {player}...","","","","","",""],
["","","","i don't think kyungsoon and i would be here without you :)","","","","","",""],
["","you","","aw, it's nothing.","","","null","","",""],
["sean_heaven","","","_pass","","talked_to_sean_heaven",['sean_heaven2', 'sean_heaven1'],"","",""],
["sean_heaven1","sean","sean_neutral","can you believe it, dude?","talked_to_sean_heaven","","","","",""],
["","","","we're really here!","","","","","",""],
["","you","","yeah!","","","","","",""],
["","sean","","that's right, sean the snake finally made it to heaven","","","","","",""],
["","","","take that, joe whittaker!!","","","","","",""],
["","you","","wait, who's joe whittaker?","","","","","",""],
["","sean","","oh, it's a long story.","","","","","",""],
["","","","actually, it's a pretty short story, now that i think about it","","","","","",""],
["","","","but i don't really want to talk about it.","","","","","",""],
["","","","actually, i do want to talk about it!","","","","","",""],
["","","","he's this street preacher who used to preach outside of the record store i worked at","","","","","",""],
["","","","and he was always like \"ohhhh you're going to hell for having homosexual relations ohhhhhh im a big jerk idiot\"","","","","","",""],
["","","","well GUESS WHAT!","","","","","",""],
["","","","I'M IN HEAVEN NOW!","","","","","",""],
["","you","","you sure showed him!!","","","","","",""],
["","sean","","yeah! i sure frickin did!","","","null","","",""],
["sean_heaven2","sean","sean_neutral","man... if only dani could see me now","","","null","","",""],
["elijah_heaven","","","_pass","","talked_to_elijah_heaven",['elijah_heaven2', 'elijah_heaven1'],"","",""],
["elijah_heaven1","elijah","elijah_neutral","oh hey, {player}.","talked_to_elijah_heaven","","","","",""],
["","you","","heya!","","","","","",""],
["","elijah","","ain't this a beautiful view?","","","","","",""],
["","you","","you said it.","","","","","",""],
["","elijah","","man","","","","","",""],
["","","","it feels like a weight's been lifted from my shoulders, you know?","","","","","",""],
["","","","it's like i'm sitting on a cloud.","","","","","",""],
["","","","and not just because this bridge is literally supported by clouds.","","","","","",""],
["","you","","lol, i know what you mean","","","","","",""],
["","","","do you think your friends back home would be proud of you?","","","","","",""],
["","elijah","","oh, those folks?","","","","","",""],
["","","","nah, they're probably too busy living their lives to worry about little old me","","","","","",""],
["","","","doing med school or... selling heirlooms... or whatever they're up to nowadays","","","","","",""],
["","you","","still","","","","","",""],
["","","","getting to heaven... it's something","","","","","",""],
["","elijah","","oh yeah","","","","","",""],
["","","","it's something, alright.","","","","","",""],
["","","","hmm... could even write a poem about it...","","","null","","",""],
["elijah_heaven2","elijah","elijah_neutral","\"sat on clouds of pearl...\"","","","","","",""],
["","","","no... \"sat on clouds of satin...\"","","","null","","",""],
["oliver_heaven","","","_pass","","talked_to_oliver_heaven",['oliver_heaven2', 'oliver_heaven1'],"","",""],
["oliver_heaven1","oliver","oliver_neutral","{player}, this library is amazing!","talked_to_oliver_heaven","","","","",""],
["","","","it's much cozier than the one back in purrgatory, don't you think?","","","","","",""],
["","you","","oh yeah, way better ambience","","","","","",""],
["","","","no offense","","","","","",""],
["","oliver","","none taken!","","","","","",""],
["","","","you know, in a way it's sort of bittersweet.","","","","","",""],
["","","","i never did figure out the mystery of the meows, and now i never will.","","","","","",""],
["","","","but...","","","","","",""],
["","","","you know what?","","","","","",""],
["","you","","yes...?","","","","","",""],
["","oliver","","i don't even care that much!","","","","","",""],
["","you","","oh, good!","","","","","",""],
["","oliver","","yeah!","","","","","",""],
["","","","there are much better things in store for all of us.","","","","","",""],
["","you","","yeah, that's the spirit!","","","","","",""],
["","oliver","","eheh","","","","","",""],
["","","","it's hard not to be a little gleeful when you're in heaven.","","","","","",""],
["","","","by the way...","","","","","",""],
["","","","if you ever run across a laura catherine mousley or an andrew mousley","","","","","",""],
["","","","will you let them know i'm doing okay?","","","","","",""],
["","you","","of course.","","","","","",""],
["","oliver","","thank you.","","","null","","",""],
["oliver_heaven2","oliver","oliver_neutral","do you... think they have anime in heaven?","","","","","",""],
["","you","","well i would hope so","","","null","","",""],
["natalie_heaven","","","_pass","","talked_to_natalie_heaven",['natalie_heaven2', 'natalie_heaven1'],"","",""],
["natalie_heaven1","natalie","natalie_neutral","yoooo {player} look","talked_to_natalie_heaven","","","","",""],
["","","","they have coloring books!","","","","","",""],
["","you","","no way!","","","","","",""],
["","_none","","natalie holds up a picture of a dog colored like a rainbow.","","","","","",""],
["","natalie","","yes way and it RULES","","","","","",""],
["","","","want a sheet?","","","","","",""],
["","you","","maybe later!","","","","","",""],
["","","","don't you like, want to explore heaven?","","","","","",""],
["","natalie","","well, i'll get around to it","","","","","",""],
["","","","i'm taking my time, you know?","","","","","",""],
["","","","heaven's not going anywhere","","","","","",""],
["","you","","true, true","","","","","",""],
["","natalie","","now if you'll excuse me, i have to color in this dracopire.","","","","","",""],
["","you","","say again?","","","","","",""],
["","natalie","","dracopire. you know, like a dragon vampire?","","","","","",""],
["","you","","ohhhh","","","null","","",""],
["natalie_heaven2","natalie","natalie_neutral","you know... i always wanted to nap on a cloud","","","","","",""],
["","you","","gotta put that on the to do list","","","","","",""],
["","natalie","","for sure","","","null","","",""],
["tori_heaven","","","_pass","","talked_to_tori_heaven",['tori_heaven2', 'tori_heaven1'],"","",""],
["tori_heaven1","you","tori_neutral","hi tori!","talked_to_tori_heaven","","","","",""],
["","tori","","hey, partner.","","","","","",""],
["","","","gate's up ahead, if that's what you're looking for.","","","","","",""],
["","you","","nah, i just wanted to ask how you're--","","","","","",""],
["","tori","","wait, let me guess.","","","","","",""],
["","","","you're going around checking up on everyone and seeing how they're doing?","","","","","",""],
["","you","","uh...","","","","","",""],
["","","","yes?","","","","","",""],
["","tori","","heh. seems to be your m.o.","","","","","",""],
["","","","well, let me ask you this:","","","","","",""],
["","","","how are [i]you[/i] doing?","","","","","",""],
["","you","","ummm","","","","","",""],
["","","","","","","","",['i\'m relieved we all made it', 'i\'m sad that it\'s over', 'i\'m sort of numb rn'],['tori_heaven1a', 'tori_heaven1b', 'tori_heaven1c']],
["tori_heaven1a","you","","well, mostly i'm relieved that we made it","","","","","",""],
["","","","i don't want to worry too much about what's up ahead","","","","","",""],
["","","","i'm just grateful we're all here","","","","","",""],
["","tori","","i see, i see.","","","","","",""],
["","","","well, maybe i could take a leaf from your book.","","","","","",""],
["","","","my first instinct was to head through the gate straight away, but everyone else seems to be taking their time","","","","","",""],
["","","","so i'm taking a moment to relax and be grateful as well.","","","tori_heaven1d","","",""],
["tori_heaven1b","you","","this is going to sound kind of weird, but...","","","","","",""],
["","","","i'm sort of sad that it's over","","","","","",""],
["","","","i know purrgatory sucked, but it was also cozy in a way","","","","","",""],
["","tori","","don't fret too much. i have a feeling that this is just the beginning.","","","","","",""],
["","","","...not to be cliche or anything.","","","","","",""],
["","","","personally, i wanted to head through the gate right away, but everyone else seems to be taking their time","","","","","",""],
["","","","so i'm taking a moment to relax as well.","","","tori_heaven1d","","",""],
["tori_heaven1c","you","","honestly, i'm kind of numb right now","","","","","",""],
["","","","i don't think my body's really processed that we're in heaven yet","","","","","",""],
["","tori","","yeah, i can understand that.","","","","","",""],
["","","","just take it easy. your body will catch up eventually.","","","","","",""],
["","","","personally, i wanted to head through the gate right away, but everyone else seems to be taking their time","","","","","",""],
["","","","so i'm taking a moment to relax as well.","","","tori_heaven1d","","",""],
["tori_heaven1d","you","","you seem pretty tense for someone who's supposed to be relaxing...","","","","","",""],
["","tori","","well, of course.","","","","","",""],
["","","","what if i need to defend myself from a crowd of attackers at a moment's notice?","","","","","",""],
["","you","","well... ah, never mind.","","","","","",""],
["","tori","","heh. i'm just joshin you.","","","","","",""],
["","","","take care, {player}.","","","","","",""],
["","","","heaven's lucky to have an angel like you.","","","","","",""],
["","you","","aw, thanks","","","","","",""],
["","","","you take care too!","","","","","",""],
["","tori","","i'll try.","","","null","","",""],
["tori_heaven2","tori","tori_neutral","these are some cool windows, huh?","","","","","",""],
["","you","","let me guess, you're an experienced stained glass artisan?","","","","","",""],
["","tori","","nah, i just think they're neat.","","","null","","",""],
["heaven_confirm","_none","_none","ready to go in?","_delay_enter_gate","","","","",""],
["","","","","","","","",['yes', 'no'],['null', 'heaven_confirm1']],
["heaven_confirm1","_none","_none","maybe in a bit.",[['_delay_enter_gate', false]],"","null","","",""]
]