extends Node

var raw_blocks = [
["ks_default","_none","_none","_pass","","ks_quest_complete or numa_quest_complete",['ks_and_numa', 'ks_c1'],"",""],
["ks_c1","","","_pass","","commons_flowers",['ks_leaves', 'ks_default2'],"",""],
["ks_leaves","kyungsoon","kyungsoon_neutral","kyungsoon is munching on leaves when you approach.","","","","",""],
["","","","","","","",['true', 'not ks_talked_about_numa', 'ks_talked_about_numa and not ks_quest_complete'],[['what\'s up?', 'ks_wasup'], ['about numa…', 'ks_numa'], ['about numa…', 'ks_numa_options']]],
["ks_default2","_none","kyungsoon_neutral","you approach kyungsoon.","","","","",""],
["","","","","","","",['true', 'numa_started_food and not numa_progressed_food'],[['what\'s up?', 'ks_wasup'], ['what\'s your favorite food?', 'ks_food']]],
["ks_wasup","you","","wasup?","","","","",""],
["","kyungsoon","","same old","","","","",""],
["","you","","mhm","","","null","",""],
["ks_numa","you","","hey","ks_talked_about_numa","","","",""],
["","kyungsoon","","sup","","","","",""],
["","you","","about numa","","","","",""],
["","kyungsoon","","yeah","","","","",""],
["","","","she ok?","","","","",""],
["","","","","","","","",[['she wanted to tell you she likes you', 'ks_numa_likes'], ['she had something to confess', 'ks_numa_confess']]],
["ks_numa_likes","you","","she wanted to tell you she likes you.","","","","",""],
["","kyungsoon","","figured","","","","",""],
["","","","explains the flowers","","","","",""],
["","you","","yep","","","ks_numa_q","",""],
["ks_numa_confess","you","","she had, um, something to confess","","","","",""],
["","kyungsoon","","that she likes me?","","","","",""],
["","you","","oh","","","","",""],
["","","","well i guess it was pretty obvious","","","","",""],
["","kyungsoon","","yeah","","","","",""],
["","","","she got me flowers","","","","",""],
["ks_numa_q","","","","","","","",[['she put a lot of work into those', 'ks_numa_work'], ['don\'t you like the gifts?', 'ks_numa_gifts']]],
["ks_numa_work","you","","she put a lot of work into those, you know","","","","",""],
["","kyungsoon","","i can see that","","","ks_numa_poem","",""],
["ks_numa_gifts","you","","don't you like the gifts?","","","","",""],
["","kyungsoon","","well","","","","",""],
["","","","no one's ever given me flowers before","","","","",""],
["","you","","me neither","","","","",""],
["","kyungsoon","","it's a bit corny","","","","",""],
["","you","","a bit","","","","",""],
["ks_numa_poem","you","","did you read the poem?","","","","",""],
["","kyungsoon","","poem?","","","","",""],
["","","","she actually wrote me a poem?","","","","",""],
["","you","","uh","","","","",""],
["","","","yeah","","","","",""],
["","kyungsoon","","what is this, high school","","","","",""],
["","","","lol","","","","",""],
["","you","","lol","","","","",""],
["","","","","","","","",[['you should give her a chance', 'ks_numa_chance'], ['guess you\'re not interested, then?', 'ks_numa_interested']]],
["ks_numa_chance","you","","you should give her a chance. i think it would mean a lot to her","","","","",""],
["","kyungsoon","","if she wants to hang out","","","","",""],
["","","","i'm right here","","","","",""],
["","you","","it might be better if you go to her…?","","","","",""],
["","kyungsoon","","…","","","","",""],
["","you","","…","","","","",""],
["","","","not happening?","","","","",""],
["","kyungsoon","","i don't know, maybe","","","","",""],
["","you","","hmm","","","ks_numa_options","",""],
["ks_numa_interested","you","","i'm guessing you're not interested?","","","","",""],
["","kyungsoon","","why?","","","","",""],
["","you","","i don't know","","","","",""],
["","","","tone of voice?","","","","",""],
["","kyungsoon","","…","","","","",""],
["","you","","so you are interested?","","","","",""],
["","kyungsoon","","didn't say that","","","","",""],
["","you ","","):<","","","","",""],
["","","","you should probably go talk to her","","","","",""],
["","","","i think she's crying","","","","",""],
["","kyungsoon","","…","","","","",""],
["","you","","…","","","","",""],
["","","","not happening?","","","","",""],
["","kyungsoon","","i don't know, maybe","","","","",""],
["","you","","hmm","","","","",""],
["ks_numa_options","","kyungsoon_neutral","","","","",['not ks_numa_sit_done', 'not ks_numa_cute_done', 'not (ks_numa_sit_done and ks_numa_cute_done)', 'ks_numa_sit_done and ks_numa_cute_done', 'true'],[['don\'t you get tired of sitting here alone?', 'ks_numa_sit'], ['she said you were cute', 'ks_numa_cute'], ['just get up you lazy bum', 'ks_numa_no'], ['just get up you lazy bum', 'ks_numa_getup'], ['talk to you later', 'ks_numa_bye']]],
["ks_numa_sit","you","","don't you get tired of sitting here alone?","ks_numa_sit_done","","","",""],
["","","","it's not like you have anything better to do.","","","","",""],
["","kyungsoon","","it's purrgatory.","","","","",""],
["","","","it's boring","","","","",""],
["","","","that's the point","","","","",""],
["","you","","but you don't have to handle it by yourself","","","","",""],
["","","","we help each other, that's what people do","","","","",""],
["","kyungsoon","","eh","","","","",""],
["","","","we're all here for a reason","","","","",""],
["","","","probably deserve it","","","","",""],
["","you","","including you?","","","","",""],
["","kyungsoon","","yeah","","","","",""],
["","you","","why?","","","","",""],
["","kyungsoon","","i mean","","","","",""],
["","","","this is how i always was","","","","",""],
["","","","sitting around","","","","",""],
["","","","unemployed","","","","",""],
["","","","eating shit","","","","",""],
["","","","making people cry","","","","",""],
["","","","","","","","",[['i think oliver made her cry', 'ks_numa_oliver'], ['that doesn\'t make you a bad person', 'ks_numa_bad']]],
["ks_numa_oliver","you","","to be fair, i think oliver is the one that made her cry","","","","",""],
["","kyungsoon","","heh","","","","",""],
["","","","oliver makes me want to cry too","","","","",""],
["","you","","lol","","","ks_numa_right","",""],
["ks_numa_bad","you","","that doesn't make you a bad person","","","","",""],
["","kyungsoon","","duh","","","","",""],
["","","","otherwise i'd be in hell","","","","",""],
["ks_numa_right","you","","point is, you have a chance to make things right with numa","","","","",""],
["","kyungsoon","","…","","","","",""],
["","","","whatever","","","","",""],
["","","","she can do better than me, anyway.","","","","",""],
["","you","","oh, you two are perfect for each other","","","","",""],
["","kyungsoon","","?","","","","",""],
["","you","","never mind.","","","ks_numa_options","",""],
["ks_numa_bye","you","","talk to you later","","","","",""],
["","kyungsoon","","cya","","","null","",""],
["ks_numa_cute","you","","she said you were cute","ks_numa_cute_done","","","",""],
["","kyungsoon","","cool","","","","",""],
["","you","","cute as a kitten","","","","",""],
["","kyungsoon","","weird","","","","",""],
["","you","","she also said you were mysterious, tall, smart, and sexy","","","","",""],
["","kyungsoon","","…","","","","",""],
["","","","really?","","","","",""],
["","you","","ok, i don't think she said sexy","","","","",""],
["","kyungsoon","","literally no one has ever called me sexy","","","","",""],
["","you","","i see","","","","",""],
["","kyungsoon","","numa is way cuter than me, anyway","","","","",""],
["","","","objectively","","","","",""],
["","you","","nah","","","","",""],
["","kyungsoon","","yeah","","","","",""],
["","you","","point is she is [i]really[/i] into you","","","","",""],
["","kyungsoon","","her mistake","","","","",""],
["","","","she's gonna be really disappointed when she gets to know me","","","","",""],
["","you","","how do you know?","","","","",""],
["","kyungsoon","","have a feeling","","","","",""],
["","","","","","","","",[['can\'t be more disappointed than she is now', 'ks_numa_disappointed'], ['oh my god, just give it a chance', 'ks_numa_god']]],
["ks_numa_disappointed","you","","she can't possibly be more disappointed than she is now","","","","",""],
["","","","she's literally sobbing","","","","",""],
["","kyungsoon","","hm","","","","",""],
["","you","","just give it a chance already!","","","","",""],
["","kyungsoon","","hmmm","","","ks_numa_options","",""],
["ks_numa_god","you","","oh my god, just give it a chance already","","","","",""],
["","kyungsoon","","?","","","","",""],
["","you","","like","","","","",""],
["","","","this is starting to get old","","","","",""],
["","","","both of you need to get over yourselves","","","","",""],
["","","","and just","","","","",""],
["","","","talk to each other","","","","",""],
["","","","and kiss","","","","",""],
["","kyungsoon","","damn","","","","",""],
["","you","","yeah","","","","",""],
["","","","chew on that","","","","",""],
["","kyungsoon","","…","","","ks_numa_options","",""],
["ks_numa_no","you","","just get up, you lazy bum","","","","",""],
["","kyungsoon","","ok, i'm convinced","","","","",""],
["","you","","really?","","","","",""],
["","kyungsoon","","no lol","","","","",""],
["","you","","):<","","","ks_numa_options","",""],
["ks_numa_getup","you","","just get up, you lazy bum","","","","",""],
["","kyungsoon","","…","","","","",""],
["","","","fine","","","","",""],
["","you","","really?","","","","",""],
["","kyungsoon","","yeah","","","","",""],
["","_none","","kyungsoon stands up.","","","","",""],
["","you","","oh, sweet","","","","",""],
["","kyungsoon","","where is she?","","","","",""],
["","you","","in her room, most likely","","","","",""],
["","","","i'll show you","","","","",""],
["","kyungsoon","","k","","","","",""],
["","_none","","you lead kyungsoon to the vent, where you can hear quiet sobbing.","ks_goto_vents","","","",""],
["","you","","hey, numa","","","","",""],
["","numa","","what do you want?","","","","",""],
["","you","","i brought kyungsoon!","","","","",""],
["","_none","","…","","","","",""],
["","kyungsoon","","uh","","","","",""],
["","","","hi","","","","",""],
["","numa","","…hi…","","","","",""],
["","kyungsoon","","thanks for the flowers and stuff","","","","",""],
["","numa","","you're welcome…","","","","",""],
["","kyungsoon","","you realize they smell like shit, right","","","","",""],
["","_none","","you shake your head at kyungsoon","","","","",""],
["","kyungsoon","","but they're uhh","","","","",""],
["","","","pretty","","","","",""],
["","numa","","…","","","","",""],
["","kyungsoon","","uh","","","","",""],
["","","","i heard you were an accountant","","","","",""],
["","numa","","intern…","","","","",""],
["","kyungsoon","","right","","","","",""],
["","numa","","um","","","","",""],
["","","","how about you?","","","","",""],
["","kyungsoon","","oh i just mooched off my parents","","","","",""],
["","","","they would have been stoked if i went into accounting","","","","",""],
["","numa","","why didn't you?","","","","",""],
["","kyungsoon","","i'm shit at math","","","","",""],
["","numa","","oh","","","","",""],
["","","","haha","","","","",""],
["","kyungsoon","","they tried to get me to learn violin too","","","","",""],
["","numa","","no way, i played violin!","","","","",""],
["","kyungsoon","","yeah?","","","","",""],
["","numa","","i mean, i was never very good…","","","","",""],
["","kyungsoon","","oh, i was awful","","","","",""],
["","","","i was like 12","","","","",""],
["","","","one time i knocked over a candle with my bow","","","","",""],
["","","","at my teacher's place","","","","",""],
["","","","curtains caught fire","","","","",""],
["","numa","","omg","","","","",""],
["","kyungsoon","","yeah","","","","",""],
["","","","it was pretty funny","","","","",""],
["","numa","","was his house okay","","","","",""],
["","kyungsoon","","yeah but he refused to teach me again","","","","",""],
["","numa","","oh no","","","","",""],
["","kyungsoon","","good riddance","","","","",""],
["","","","he was an ass","","","","",""],
["","numa","","hehe :)",[['numa_crying', 'false']],"","","",""],
["","_none","","kyungsoon gives you an \"am i doing this right\" look","numa_quest_complete","","","",""],
["","","","you flash her a thumbs up","ks_quest_complete","","","",""],
["","","","maybe it's time to give them some alone time.","ks_at_vent_timer","","null","",""],
["ks_food","you","","so, what's your favorite food?","numa_progressed_food","","","",""],
["","kyungsoon","","steak","","","","",""],
["","you","","oh","","","","",""],
["","","","what about your favorite food in purrgatory?","","","","",""],
["","kyungsoon","","hm","","","","",""],
["","","","leaf","","","","",""],
["","you","","leaves?","","","","",""],
["","kyungsoon","","yeah as in leave me alone","","","","",""],
["","you","","lol nice","","","","",""],
["","","","…","","","","",""],
["","","","but, like, what's actually your favorite food in purrgatory","","","","",""],
["","kyungsoon","","it's actually leaves","","","","",""],
["","you","","for real?","","","","",""],
["","kyungsoon","","yeah","","","","",""],
["","you","","why","","","","",""],
["","kyungsoon","","i like the cronch","","","","",""],
["","you","","ok","","","null","",""],
["ks_and_numa","_none","_none","_pass","","ks_at_vent",['ks_and_numa_vent', 'ks_and_numa_commons_c1'],"",""],
["ks_and_numa_vent","_none","kyungsoon_neutral","kyungsoon and numa are still chatting.","","","","",""],
["","","","seems like your work here is done.","","","null","",""],
["ks_and_numa_commons_c1","_none","_none","_pass","","not ks_and_numa_commons1_done",['ks_and_numa_commons1', 'ks_and_numa_commons_c2'],"",""],
["ks_and_numa_commons_c2","","","_pass","","not ks_and_numa_commons2_done",['ks_and_numa_commons2', 'ks_and_numa_commons3'],"",""],
["ks_and_numa_commons1","numa",['kyungsoon_neutral', 'numa_neutral'],"oh, hi, $player!","display_kyungsoon_and_numa","","","",""],
["","you","","heyo!","ks_and_numa_commons1_done","","","",""],
["","numa","","kyungsoon and i are talking about our favorite foods.","","","","",""],
["","kyungsoon","","mine is steak","","","","",""],
["","","","bulgogi, actually","","","","",""],
["","numa","","what's that?","","","","",""],
["","kyungsoon","","korean beef","","","","",""],
["","numa","","oh, it sounds nice","","","","",""],
["","kyungsoon","","yeah","","","","",""],
["","","","guess you've never had it?","","","","",""],
["","numa","","oh, um, i was vegetarian","","","","",""],
["","","","sorry","","","","",""],
["","kyungsoon","","ah i see","","","","",""],
["","","","is it because","","","","",""],
["","","","uh","","","","",""],
["","numa","","because i'm a snail?","","","","",""],
["","kyungsoon","","yeah","","","","",""],
["","numa","","kind of","","","","",""],
["","","","meat just doesn't sit well with me","","","","",""],
["","","","and the poor animals ;;","","","","",""],
["","kyungsoon","","but animals are tasty","","","","",""],
["","numa","","nooo ;;","","","","",""],
["","kyungsoon","","yes","","","","",""],
["","numa","","nooooooooooooooooooooo","","","","",""],
["","_none","","looks like they're getting along well.","","","null","",""],
["ks_and_numa_commons2","kyungsoon",['kyungsoon_neutral', 'numa_neutral'],"honestly, the worst part about being dead is not having real food","display_kyungsoon_and_numa","","","",""],
["","numa","","really?","ks_and_numa_commons2_done","","","",""],
["","","","that's the worst part for you?","","","","",""],
["","kyungsoon","","well","","","","",""],
["","","","it's up there","","","","",""],
["","numa","","i think the worst part for me is there's no sky","","","","",""],
["","","","i feel like everything would be so much better if i could feel the sun again","","","","",""],
["","kyungsoon","","aw","","","","",""],
["","","","i'm sorry","","","","",""],
["","numa","","i'll get used to it… maybe.","","","","",""],
["","kyungsoon","","i hardly ever went outside anyway","","","","",""],
["","numa","","oh, but that's so unhealthy for you!","","","","",""],
["","","","i mean","","","","",""],
["","","","not that you look unhealthy","","","","",""],
["","","","or anything","","","","",""],
["","","","sorry","","","","",""],
["","kyungsoon","","it's ok i'm unhealthy as fuck","","","","",""],
["","","","i'm like","","","","",""],
["","","","a walking garbage can","","","","",""],
["","numa","","well you're a very pr…","","","","",""],
["","","","um","","","","",""],
["","","","pre…","","","","",""],
["","kyungsoon","","a very pretty garbage can?","","","","",""],
["","numa","","yes ;;","","","","",""],
["","kyungsoon","","hah","","","","",""],
["","","","thanks, i guess","","","null","",""],
["ks_and_numa_commons3","_none",['kyungsoon_neutral', 'numa_neutral'],"looks like kyungsoon and numa are still chatting.","display_kyungsoon_and_numa","","null","",""]
]