extends Node

var raw_blocks = [
["ks_default","_none","_none","_pass","","kyungsoon_quest_complete or numa_quest_complete",['ks_and_numa_commons', 'ks_c1'],"","",""],
["ks_c1","","","_pass","","commons_flowers",['ks_leaves', 'ks_default2'],"","",""],
["ks_leaves","_none","kyungsoon_neutral","kyungsoon is munching on leaves.","","","","","",""],
["","","","","","","",['true', 'not ks_talked_about_numa', 'ks_talked_about_numa and not kyungsoon_quest_complete', 'true', 'true'],['what\'s up?', 'about numa...', 'about numa...', 'what are your hobbies?', 'where did this cat come from?'],['ks_wasup', 'ks_numa', 'ks_numa_options', 'ks_hobbies', 'ks_cat']],
["ks_default2","kyungsoon","kyungsoon_neutral","...","","","",['true', 'numa_started_food and not numa_finished_food', 'true', 'true'],['what\'s up?', '(ask about food for numa)', 'what are your hobbies?', 'where did this cat come from?'],['ks_wasup', 'ks_food', 'ks_hobbies', 'ks_cat']],
["ks_hobbies","you","","so, what are your hobbies?","","","","","",""],
["","kyungsoon","","oh, you know","","","","","",""],
["","","","sitting","","","","","",""],
["","","","breathing","","","","","",""],
["","","","","","","","",['me too', 'what about in real life?'],['ks_hobbies1', 'ks_hobbies2']],
["ks_hobbies1","you","","me too","","","","","",""],
["","","","i love sitting and breathing","","","","","",""],
["","kyungsoon","","cant beat it","","","","","",""],
["","you","","yep","","","null","","",""],
["ks_hobbies2","you","","what about, like, in real life?","","","","","",""],
["","","","before you died?","","","","","",""],
["","kyungsoon","","video games, i guess","","","","","",""],
["","you","","cool!","","","","","",""],
["","","","what kind?","","","","","",""],
["","kyungsoon","","the kind where you mind your own business","","","","","",""],
["","you","","oh, um","","","","","",""],
["","","","i love those games","","","","","",""],
["","kyungsoon","","me too","","","null","","",""],
["ks_cat","you","","so, where did this cat come from?","","","","","",""],
["","","","is it yours?","","","","","",""],
["","kyungsoon","","idk","","","","","",""],
["","","","it's always been there","","","","","",""],
["","you","","just standing still?","","","","","",""],
["","kyungsoon","","it walks around sometimes","","","","","",""],
["","you","","hmm","","","","","",""],
["","","","does it have a name?","","","","","",""],
["","kyungsoon","","cat","","","","","",""],
["","you","","[i]nod nod[/i]","","","","","",""],
["","","","good name","","","null","","",""],
["ks_wasup","you","","wasup?","","",['_rand', 'ks_wasup1', 'ks_wasup2', 'ks_wasup3', 'ks_wasup4', 'ks_wasup5', 'ks_wasup6', 'ks_wasup7', 'ks_wasup8', 'ks_wasup9', 'ks_wasup10'],"","",""],
["ks_wasup1","kyungsoon","","same old","","","","","",""],
["","you","","cool","","","null","","",""],
["ks_wasup2","kyungsoon","","just ran a half-marathon","","","","","",""],
["","you","","really?","","","","","",""],
["","kyungsoon","","no of course not","","","","","",""],
["","you","","oh","","","null","","",""],
["ks_wasup3","kyungsoon","","you'd think a place called purrgatory would have more than one cat","","","","","",""],
["","you","","that's true","","","","","",""],
["","","","never thought about it that way before...","","","null","","",""],
["ks_wasup4","kyungsoon","","your mom","","","","","",""],
["","you","","...why do i even bother","","","null","","",""],
["ks_wasup5","kyungsoon","","it's purrgatory","","","","","",""],
["","","","nothing's ever up","","","","","",""],
["","you","","fair","","","null","","",""],
["ks_wasup6","kyungsoon","","...","","","","","",""],
["","you","","eaten anything good lately?","","","","","",""],
["","kyungsoon","","...","","","","","",""],
["","you","","alright, good talk","","","null","","",""],
["ks_wasup7","kyungsoon","","mm","","","","","",""],
["","you","","yeah me too","","","null","","",""],
["ks_wasup8","kyungsoon","","the ceiling","","","","","",""],
["","you","","i should have seen that one coming","","","null","","",""],
["ks_wasup9","kyungsoon","","i feel like we repeat ourselves a lot","","","","","",""],
["","you","","really?","","","","","",""],
["","","","i hadn't noticed","","","","","",""],
["","kyungsoon","","iuno","","","null","","",""],
["ks_wasup10","kyungsoon","","kyungsoon purrgatory","","","","","",""],
["","you","","what?","","","","","",""],
["","kyungsoon","","nothin","","","","","",""],
["","you","","i","","","","","",""],
["","","","what","","","null","","",""],
["ks_numa","you","","hey, about numa...","ks_talked_about_numa","","","","",""],
["","kyungsoon","","yeah?","","","","","",""],
["","","","","","","","",['she wanted to tell you she likes you', 'she had something to confess'],['ks_numa_likes', 'ks_numa_confess']],
["ks_numa_likes","you","","she wanted to tell you she likes you","","","","","",""],
["","kyungsoon","","explains the flowers","","","","","",""],
["","you","","yep","","","ks_numa_q","","",""],
["ks_numa_confess","you","","she, um, had something to confess...","","","","","",""],
["","kyungsoon","","that she likes me?","","","","","",""],
["","you","","oh","","","","","",""],
["","","","well, i guess it's pretty obvious","","","","","",""],
["","kyungsoon","","yeah","","","","","",""],
["","","","got me flowers and everything","","","","","",""],
["","you","","don't you like the gifts?","","","","","",""],
["","kyungsoon","","well","","","","","",""],
["","","","no one's ever given me flowers before","","","","","",""],
["","you","","me neither","","","","","",""],
["","kyungsoon","","it's a bit corny","","","","","",""],
["","you","","maybe a bit","","","","","",""],
["","you","","did you read the poem?","","","","","",""],
["","kyungsoon","","poem?","","","","","",""],
["","","","she actually wrote me a poem?","","","","","",""],
["","you","","uhhh yeah!","","","","","",""],
["","kyungsoon","","what is this, high school?","","","","","",""],
["","","","lol","","","","","",""],
["","","","","","","","",['you should give her a chance!', 'guess you\'re not interested, then?'],['ks_numa_chance', 'ks_numa_interested']],
["ks_numa_chance","you","","you should give her a chance! ","","","","","",""],
["","","","i think it would mean a lot to her","","","","","",""],
["","kyungsoon","","if she wants to hang out, i'm right here","","","","","",""],
["","you","","it might be easier for you to go to her...?","","","","","",""],
["","kyungsoon","","hmm...","","","","","",""],
["","you","","...","","","","","",""],
["","","","not happening?","","","","","",""],
["","kyungsoon","","[i]shrug[/i]","","","","","",""],
["","_none","","maybe there's a way to convince her...","","","ks_numa_options","","",""],
["ks_numa_interested","you","","i guess you're not interested, then?","","","","","",""],
["","kyungsoon","","i didn't say that","","","","","",""],
["","you","","well, i gathered from... idk... your tone of voice","","","","","",""],
["","kyungsoon","","...","","","","","",""],
["","you","","so you are interested?","","","","","",""],
["","kyungsoon","","i didn't say that","","","","","",""],
["","you ","","):<","","","","","",""],
["","","","i think you should go talk to her","","","","","",""],
["","","","i think she's crying","","","","","",""],
["","kyungsoon","","hmm...","","","","","",""],
["","you","","...","","","","","",""],
["","","","not happening?","","","","","",""],
["","kyungsoon","","[i]shrug[/i]","","","","","",""],
["","_none","","maybe there's a way to convince her...","","","ks_numa_options","","",""],
["ks_numa_options","","kyungsoon_neutral","","","","",['not ks_numa_sit_done', 'not ks_numa_cute_done', 'not (ks_numa_sit_done and ks_numa_cute_done)', 'ks_numa_sit_done and ks_numa_cute_done', 'true'],['don\'t you get bored of sitting here alone?', 'you know she called you cute', 'just get up, you lazy bum', 'just get up, you lazy bum', 'never mind'],['ks_numa_sit', 'ks_numa_cute', 'ks_numa_no', 'ks_numa_getup', 'ks_numa_bye']],
["ks_numa_sit","you","","don't you get bored of sitting here alone?","ks_numa_sit_done","","","","",""],
["","kyungsoon","","it's purrgatory","","","","","",""],
["","","","it's boring","","","","","",""],
["","","","that's the point","","","","","",""],
["","you","","but it doesn't have to be like that!","","","","","",""],
["","","","we can help each other through it. that's what people do","","","","","",""],
["","kyungsoon","","eh","","","","","",""],
["","","","they put us down here for a reason","","","","","",""],
["","","","we probably deserve it","","","","","",""],
["","you","","including you?","","","","","",""],
["","kyungsoon","","yeah","","","","","",""],
["","you","","why?","","","","","",""],
["","kyungsoon","","i mean","","","","","",""],
["","","","this is how i always was","","","","","",""],
["","","","sitting around","","","","","",""],
["","","","eating shit","","","","","",""],
["","","","playing video games","","","","","",""],
["","","","making people cry","","","","","",""],
["","","","","","","","",['i think oliver made her cry', 'that doesn\'t make you a bad person'],['ks_numa_oliver', 'ks_numa_bad']],
["ks_numa_oliver","you","","to be fair, i think oliver is the one that made her cry","","","","","",""],
["","kyungsoon","","heh","","","","","",""],
["","","","oliver makes me want to cry too","","","","","",""],
["","you","","lol","","","ks_numa_right","","",""],
["ks_numa_bad","you","","that doesn't make you a bad person!","","","","","",""],
["","kyungsoon","","i guess not","","","","","",""],
["","","","otherwise i'd be in hell proper","","","","","",""],
["ks_numa_right","you","","the point is, it doesn't matter what you did when you were alive","","","","","",""],
["","","","you have a chance to make things right with numa, right now!","","","","","",""],
["","kyungsoon","","...","","","","","",""],
["","","","whatever","","","","","",""],
["","","","she can do better than me, anyway","","","","","",""],
["","you","","oh, you two are perfect for each other","","","","","",""],
["","kyungsoon","","?","","","","","",""],
["","you","","never mind","","","ks_numa_options","","",""],
["ks_numa_bye","you","","ah, never mind","","","","","",""],
["","","","talk to you later","","","","","",""],
["","kyungsoon","","cya","","","null","","",""],
["ks_numa_cute","you","","you know she said you were cute!","ks_numa_cute_done","","","","",""],
["","kyungsoon","","cool","","ks_heard_cute_as_kitten",['ks_kitten', 'ks_sexy'],"","",""],
["ks_kitten","you","","cute as a kitten, even","","","","","",""],
["","kyungsoon","","sorta weird, but okay","","","","","",""],
["ks_sexy","you","","she also said you were smart, confident, and sexy","","","","","",""],
["","kyungsoon","","...","","","","","",""],
["","","","really?","","","","","",""],
["","you","","ok, i don't think she said sexy","","","","","",""],
["","","","but she said all those other things!","","","","","",""],
["","kyungsoon","","whatever","","","","","",""],
["","","","numa is objectively way cuter than me, anyway","","","","","",""],
["","you","","weeell, i don't know about that","","","","","",""],
["","","","the point is, she is [i]really[/i] into you","","","","","",""],
["","kyungsoon","","her mistake","","","","","",""],
["","","","she's gonna be really disappointed when she gets to know me","","","","","",""],
["","you","","how do you know?","","","","","",""],
["","kyungsoon","","have a feeling","","","","","",""],
["","","","","","","","",['she can\'t be more disappointed than she is now', 'just give it a chance already!'],['ks_numa_disappointed', 'ks_numa_god']],
["ks_numa_disappointed","you","","she can't possibly be more disappointed than she is now!","","","","","",""],
["","kyungsoon","","hmm","","","","","",""],
["","you","","you've got to take a chance sometimes, you know","","","","","",""],
["","kyungsoon","","hmmm","","","ks_numa_options","","",""],
["ks_numa_god","you","","oh my god, just give it a chance already!","","","","","",""],
["","kyungsoon","","?","","","","","",""],
["","you","","seriously, this is starting to get old","","","","","",""],
["","","","both of you need to get over yourselves and just","","","","","",""],
["","","","like","","","","","",""],
["","","","talk to each other!","","","","","",""],
["","","","and kiss!","","","","","",""],
["","kyungsoon","","damn","","","","","",""],
["","you","","yeah","","","","","",""],
["","","","chew on [i]that[/i]","","","","","",""],
["","kyungsoon","","...","","","ks_numa_options","","",""],
["ks_numa_no","you","","just get up, you lazy bum!","","","","","",""],
["","kyungsoon","","ok, i'm convinced","","","","","",""],
["","you","","really?","","","","","",""],
["","kyungsoon","","no lol","","","","","",""],
["","you","","):<","","","ks_numa_options","","",""],
["ks_numa_getup","you","","just get up, you lazy bum!","","","","","",""],
["","kyungsoon","","...","","","","","",""],
["","","","fine","","","","","",""],
["","you","","wait, really?","","","","","",""],
["","kyungsoon","","yeah","","","","","",""],
["","_none","","kyungsoon stands up.","","","","","",""],
["","you","","oh, cool","","","","","",""],
["","","","that was easier than i expected","","","","","",""],
["","kyungsoon","","where is she?","","","","","",""],
["","you","","in her room, most likely","","","","","",""],
["","","","here, i'll show you","","","","","",""],
["","kyungsoon","","k","","","","","",""],
["","_none","","you lead kyungsoon to the vent.","ks_goto_vents","","","","",""],
["","you","","hey, numa!","","","","","",""],
["","numa","","what do you want?!","","","","","",""],
["","you","","i brought kyungsoon!","","","","","",""],
["","numa","","WHAT?","","","","","",""],
["","_none","","there's a sound like someone hitting her head on the ceiling, a faint \"ow,\" then silence.","","","","","",""],
["","kyungsoon","","uh","","","","","",""],
["","","","hi","","","","","",""],
["","numa","","hello...","","","","","",""],
["","kyungsoon","","thanks for the flowers and stuff","","","","","",""],
["","numa","","um, you're welcome","","","","","",""],
["","kyungsoon","","you realize they smell like shit, right?","","","","","",""],
["","_none","","you shake your head at kyungsoon.","","","","","",""],
["","kyungsoon","","but they're uhhh","","","","","",""],
["","","","pretty","","","","","",""],
["","numa","","aaa thank you","","","","","",""],
["","kyungsoon","","uhhh","","","","","",""],
["","","","i heard you were an accountant?","","","","","",""],
["","numa","","yeah, sort of!","","","","","",""],
["","","","i was just an intern when i died","","","","","",""],
["","kyungsoon","","that's cool","","","","","",""],
["","numa","","how about you?","","","","","",""],
["","","","like, um, what did you do? when you were alive?","","","","","",""],
["","kyungsoon","","oh, i just mooched off of my parents","","","","","",""],
["","","","they would have been stoked if i went into something like accounting","","","","","",""],
["","numa","","why didn't you?","","","","","",""],
["","kyungsoon","","cus i'm shit at math","","","","","",""],
["","numa","","oh, haha","","","","","",""],
["","","","um, not that there's anything wrong with that","","","","","",""],
["","kyungsoon","","there was no satisfying my parents anyway","","","","","",""],
["","","","i was never the perfect son they thought i was","","","","","",""],
["","numa","","oh... i'm sorry...","","","","","",""],
["","kyungsoon","","you know, they tried to get me to learn violin too","","","","","",""],
["","numa","","no way, me too!","","","","","",""],
["","kyungsoon","","yeah?","","","","","",""],
["","numa","","i mean, i was never very good...","","","","","",""],
["","kyungsoon","","oh, i was awful","","","","","",""],
["","","","one time i knocked over a candle with my bow at my teacher's place and the curtains caught fire","","","","","",""],
["","numa","","oh no, was his house okay??","","","","","",""],
["","kyungsoon","","the house was fine, but he refused to teach me again","","","","","",""],
["","","","good riddance, too","","","","","",""],
["","","","he was an ass","","","","","",""],
["","numa","","hehe, good riddance :)","_quest_numa_friendship","","","","",""],
["","_none","","kyungsoon gives you an \"am i doing this right?\" look.",[['numa_crying', 'false']],"","","","",""],
["","","","you flash her a thumbs up.",[['ks_at_vent_timer', true], ['_quest_numa_friendship', false], ['numa_quest_complete', true], ['kyungsoon_quest_complete', true], ['_delay__goto_flashback_numa', true]],"","null","","",""],
["ks_post_flashback","kyungsoon","","{player}??","","","","","",""],
["","","","...","","","","","",""],
["","","","dude, wake up","","","","","",""],
["","you","kyungsoon_neutral","...",[['_goto_hallway6', true], ['_hide_kyungsoon_at_vent', true]],"","","","",""],
["","","","huh? what?","","","","","",""],
["","kyungsoon","","are you ok?","","","","","",""],
["","","","you just, like, fell down the stairs","","","","","",""],
["","you","","oh... yeah, i'm fine...","","","","","",""],
["","kyungsoon","","are you sure","","","","","",""],
["","","","you don't look fine","","","","","",""],
["","you","","yeah","","","","","",""],
["","kyungsoon","","k","","","null","","",""],
["ks_food","you","","so, what's your favorite food?","numa_progressed_food","","","","",""],
["","kyungsoon","","steak","","","","","",""],
["","you","","hm...","","","","","",""],
["","","","what about your favorite food in purrgatory, then?","","","","","",""],
["","kyungsoon","","leaf","","","","","",""],
["","you","","leaf?","","","","","",""],
["","kyungsoon","","yeah as in leaf me alone","","","","","",""],
["","you","","oh, haha","","","","","",""],
["","","","...","","","","","",""],
["","","","but, like, what's actually your favorite food in purrgatory?","","","","","",""],
["","kyungsoon","","it's actually leaves","","","","","",""],
["","you","","really?","","","","","",""],
["","","","why?","","","","","",""],
["","kyungsoon","","i like the cronch","","","null","","",""],
["ks_and_numa_vent","_none","_none","kyungsoon and numa are still chatting.","","","","","",""],
["","","","seems like your work here is done.","","","null","","",""],
["ks_and_numa_commons","","","_pass","","ks_and_numa_commons_done",['ks_and_numa_still_chatting', 'ks_and_numa_commons1'],"","",""],
["ks_and_numa_commons1","numa",['kyungsoon_neutral', 'numa_neutral'],"hi, {player}!","display_kyungsoon_and_numa","","","","",""],
["","you","","heyo!","ks_and_numa_commons_done","","","","",""],
["","numa","","kyungsoon and i were just talking about our favorite foods.","ks_and_numa_at_house","","","","",""],
["","","","mine is ramen!","","","","","",""],
["","kyungsoon","","mine is steak","","","","","",""],
["","","","or maybe bulgogi","","","","","",""],
["","numa","","what's that?","","","","","",""],
["","kyungsoon","","marinated korean meat","","","","","",""],
["","","","my dad used to make it at his restaurant","","","","","",""],
["","numa","","oh, that sounds nice!","","","","","",""],
["","kyungsoon","","yep","","","","","",""],
["","","","guess you've never had it?","","","","","",""],
["","numa","","oh, um, i mean","","","","","",""],
["","","","i'm a vegetarian, actually","","","","","",""],
["","","","leaf eater here, haha","","","","","",""],
["","kyungsoon","","ah, i see","","","","","",""],
["","","","is it because you're...","","","","","",""],
["","","","you know...","","","","","",""],
["","numa","","...a snail?","","","","","",""],
["","","","i guess so, maybe.","","","","","",""],
["","","","but also... the poor animals ;;","","","","","",""],
["","kyungsoon","","but animals are tasty","","","","","",""],
["","numa","","nooo ;;","","","","","",""],
["","kyungsoon","","yes","","","","","",""],
["","numa","","nooooooooooooooooooooo","","","","","",""],
["","_none","","looks like they're getting along well.","","","null","","",""],
["ks_and_numa_house","","","_pass","","ks_and_numa_house_done",['ks_and_numa_still_chatting', 'ks_and_numa_house1'],"","",""],
["ks_and_numa_house1","kyungsoon",['kyungsoon_neutral', 'numa_neutral'],"honestly, the worst part about being dead is not having real food","ks_and_numa_house_done","","","","",""],
["","numa","","really?","ks_and_numa_at_meowseum","","","","",""],
["","","","that's the worst part for you?","","","","","",""],
["","kyungsoon","","well, it's up there","","","","","",""],
["","numa","","i think the worst part for me is that there's no sky.","","","","","",""],
["","","","sometimes i just want to feel the sun again, you know?","","","","","",""],
["","kyungsoon","","aw","","","","","",""],
["","","","that's sad","","","","","",""],
["","numa","","oh, hi {player}!","","","","","",""],
["","you","","hey!","","","","","",""],
["","","","what are you two doing all the way out here?","","","","","",""],
["","kyungsoon","","i am also wondering that","","","","","",""],
["","numa","","oh, um, i just thought it would be good to change up the scenery a little!","","","","","",""],
["","","","get a little exercise, haha","","","","","",""],
["","","","i mean--","","","","","",""],
["","","","not that you look like you need exercise, or anything!!","","","","","",""],
["","","","you look great, actually! haha","","","","","",""],
["","","","aaaa sorry","","","","","",""],
["","kyungsoon","","lol it's ok it's ok","","","","","",""],
["","","","i'm actually unhealthy as fuck","","","","","",""],
["","","","if i didn't die of alcohol poisoning i probably would have had a stroke or something","","","","","",""],
["","numa","","oh!","","","","","",""],
["","","","i didn't know that's how you died...","","","","","",""],
["","","","i'm so sorry aaa","","","","","",""],
["","kyungsoon","","what are you apologizing for?","","","","","",""],
["","","","literally all of us are dead","","","","","",""],
["","numa","","yeah, but i just died of an eyestalk infection...","","","","","",""],
["","","","that sounds so much worse ;;","","","","","",""],
["","you","","sorry to interrupt, but","","","","","",""],
["","","","you two know that there's a sofa like, right there, right?","","","","","",""],
["","kyungsoon","","the floor is chiller","","","","","",""],
["","numa","","yeah!","","","","","",""],
["","","","it's chill to the max!","","","","","",""],
["","","","that's a thing people say, right?","","","","","",""],
["","kyungsoon","","sure, why not","","","","","",""],
["","numa","","chill to the maximum!!","","","null","","",""],
["ks_and_numa_meowseum","","","_pass","","ks_and_numa_meowseum_done",['ks_and_numa_still_chatting', 'ks_and_numa_meowseum1'],"","",""],
["ks_and_numa_meowseum1","numa",['kyungsoon_neutral', 'numa_neutral'],"did you have any pets?","ks_and_numa_meowseum_done","","","","",""],
["","kyungsoon","","well","ks_and_numa_at_train","","","","",""],
["","","","me and my girlfriend always wanted to adopt a bulldog","","","","","",""],
["","","","but other than that, no pets","","","","","",""],
["","","","we broke up before i died, by the way","","","","","",""],
["","","","so it's not like","","","","","",""],
["","","","i'm betrothed to her after death or anything","","","","","",""],
["","numa","","oh, uh, cool","","","","","",""],
["","kyungsoon","","how about you?","","","","","",""],
["","","","pets, i mean","","","","","",""],
["","","","not like death betrothal or whatever","","","","","",""],
["","numa","","oh, i had a goldfish named pumpkin!","","","","","",""],
["","kyungsoon","","aw, that's a cute name","","","","","",""],
["","numa","","thanks!!","","","","","",""],
["","","","his full name was pumpkin carassius auratus jr.","","","","","",""],
["","kyungsoon","","wow","","","","","",""],
["","","","what happened to pumpkin sr?","","","","","",""],
["","numa","","oh, he died of fin rot ;;","","","","","",""],
["","kyungsoon","","oh","","","","","",""],
["","numa","","...","","","","","",""],
["","kyungsoon","","...","","","","","",""],
["","numa","","oh, hey {player}!","","","","","",""],
["","","","i didn't notice you all the way on the other side of the room!","","","","","",""],
["","you","","hey!","","","null","","",""],
["ks_and_numa_train","","","_pass","",['upcat_done', 'ks_and_numa_train_done'],['ks_and_numa_train4', 'ks_and_numa_train3', 'ks_and_numa_train1'],"","",""],
["ks_and_numa_train1","you",['kyungsoon_neutral', 'numa_neutral'],"oh, hey guys","ks_and_numa_train_done","","","","",""],
["","numa","","hi {player}!","","","","","",""],
["","you","","what are you doing here, of all places?","","","","","",""],
["","kyungsoon","","sometimes i just come here and stare at the vending machine","","","","","",""],
["","","","think about life","","","","","",""],
["","","","you know","","","","","",""],
["","you","","don't you have any coins to put in it or something?","","","","","",""],
["","kyungsoon","","i tried... but it only takes pennies","","","","","",""],
["","you","","oh wow","","","","","",""],
["","numa","","hey...","","","","","",""],
["","","","what if we just smashed it?","","","","","",""],
["","kyungsoon","","meh","","","","","",""],
["","","","i tried once, but it's really tough","","","","","",""],
["","","","plastic or something","","","","","",""],
["","","","besides, tori would probably get mad at me","","","","","",""],
["","numa","","well, tori can...","","","","","",""],
["","","","go frick herself!","","","","","",""],
["","","","there, i said it!!","","","","","",""],
["","kyungsoon","","haha","","","","","",""],
["","","","i don't know","","","","","",""],
["","","","i don't really feel like i deserve it","","","","","",""],
["","","","maybe if i ever get to heaven then i'll have some snacks","","","","","",""],
["","numa","","aw, that's not true!","","","","","",""],
["","","","you're really cool and you deserve some snacks right now!!","","","","","",""],
["","kyungsoon","","i don't knoooooooow","","","","","",""],
["","numa","","you know what?","","","","","",""],
["","","","i'm taking matters into my own hands!","","","","","",""],
["","_none",['kyungsoon_neutral'],"numa marches out of the train station.","","","","","",""],
["","kyungsoon","","...","","","","","",""],
["","you","","...","","","","","",""],
["","","","","","","","",['things going well with numa?', 'enjoying the change in scenery?', 'done anything fun recently?'],['ks_and_numa_train1a', 'ks_and_numa_train1b', 'ks_and_numa_train1c']],
["ks_and_numa_train1a","you","","so, things going well with numa?","","","","","",""],
["","kyungsoon","","no we're pretty much mortal enemies now","","","","","",""],
["","you","","oh no!","","","","","",""],
["","kyungsoon","","yeah we hate each other's guts","","","","","",""],
["","","","we're gonna battle to the death at midnight","","","","","",""],
["","","","you're invited","","","","","",""],
["","you","","aw, thanks","","","ks_and_numa_train1d","","",""],
["ks_and_numa_train1b","you","","so, enjoying the change in scenary?","","","","","",""],
["","kyungsoon","","oh yeah","","","","","",""],
["","","","this white wall is much nicer than the other one","","","","","",""],
["","you","","oh for sure","","","","","",""],
["","kyungsoon","","maybe i'll go crazy","","","","","",""],
["","","","hang a picture of a cat on it or something","","","","","",""],
["","you","","whoa now... don't get too wild","","","ks_and_numa_train1d","","",""],
["ks_and_numa_train1c","you","","so, done anything fun recently?","","","","","",""],
["","kyungsoon","","oh yeah","","","","","",""],
["","","","went skydiving the other day","","","","","",""],
["","you","","oh, exciting","","","","","",""],
["","kyungsoon","","landed in an active volcano","","","","","",""],
["","","","turned into a skeleton from the intense heat","","","","","",""],
["","","","became the first ever skydiving skeleton","","","","","",""],
["","","","just regular shit","","","","","",""],
["","you","","the most normal of shit","","","ks_and_numa_train1d","","",""],
["ks_and_numa_train1d","kyungsoon","","...","","","","","",""],
["","","","but it's been nice, i guess","","","","","",""],
["","","","nicer than usual","","","","","",""],
["","you","","aw, that's good","","","","","",""],
["","kyungsoon","","so like","","","","","",""],
["","","","thanks for getting me off my butt or whatever","","","","","",""],
["","you","","heh, you're welcome","","","","","",""],
["","_none","","numa runs back in with a crowbar.","","","","","",""],
["","numa",['kyungsoon_neutral', 'numa_crowbar'],"AAAAAAAAAAAAAAAAAAAAAAA","_anim_numa_with_crowbar","","","","",""],
["","_none","_none","[i]bam![/i]",[['_anim_default', true], ['vending_machine_flag1', true]],"","","","",""],
["","numa","","stupid vending machine! ","breaking_vending_machine","","","","",""],
["","_none","","[i]bam! bam! bam![/i]","vending_machine_flag2","","","","",""],
["","numa","","give! my! girlfriend! her! snacks!!","","","","","",""],
["","_none","","[i]THUD[/i]",[['vending_machine_flag3', true], ['_delay_vending_machine_flag4', true]],"","null","","",""],
["ks_and_numa_train2","numa",['kyungsoon_neutral', 'numa_neutral'],"hah... hah... there!","_hide_ks_and_numa2","","","","",""],
["","","","phew","","","","","",""],
["","","","i really needed that, haha","","","","","",""],
["","","","um... what do you think?","","","","","",""],
["","kyungsoon","","...","","","","","",""],
["","","","that","","","","","",""],
["","","","was the coolest thing anyone has ever done for me","","","","","",""],
["","numa","","really?","","","","","",""],
["","","","um... i mean... it's nothing, hehe","","","","","",""],
["","","","do you want some snacks?","","","","","",""],
["","kyungsoon","","god yes","_delay_broke_vending_machine","","","","",""],
["","","","gimme those","_delay_remove_breaking_vending_machine","","null","","",""],
["ks_and_numa_train3","kyungsoon",['kyungsoon_neutral', 'numa_neutral'],"mmmmmmm","upcat_done","","","","",""],
["","","","i can't remember the last time i had real food...","","","","","",""],
["","numa","","me neither!!","","","","","",""],
["","","","is yours good?","","","","","",""],
["","kyungsoon","","hell yes","","","","","",""],
["","","","not as good as upcat though","","","","","",""],
["","numa","","what's upcat?","","","","","",""],
["","kyungsoon","","...uh","","","","","",""],
["","numa","","what? what's upcat?","","","","","",""],
["","","","aaa did i say something wrong??","","","","","",""],
["","kyungsoon","","no no","","","","","",""],
["","","","i just didn't think i'd get this far...","","","null","","",""],
["ks_and_numa_train4","_none","_none","they look happy.","dont_display_kyungsoon_and_numa","","null","","",""],
["ks_and_numa_still_chatting","_none","_none","looks like kyungsoon and numa are still chatting.","dont_display_kyungsoon_and_numa","","null","","",""],
["kyungsoon_snowglobe","","","_pass","","talked_to_kyungsoon_snowglobe",['kyungsoon_snowglobe1', 'kyungsoon_snowglobe2'],"","",""],
["kyungsoon_snowglobe1","you","_none","are you... okay?","","","","","",""],
["","kyungsoon","","oogh...","","","","","",""],
["","","","so full...","","","null","","",""],
["kyungsoon_snowglobe2","you","_none","kyungsoon?","talked_to_kyungsoon_snowglobe","","","","",""],
["","_none","","kyungsoon groans.","","","","","",""],
["","kyungsoon","","i can't believe i ate the whole thing...","","","","","",""],
["","you","","the whole what??","","","","","",""],
["","kyungsoon","","thing","","","","","",""],
["","","","[i]burp[/i]","","","null","","",""]
]