extends Node

var raw_blocks = [
["screwdriver","","","_pass","","met_numa",['screwdriver1', 'screwdriver2'],"","",""],
["screwdriver1","_none","_none","you take the screwdriver.","_inv_screwdriver","","null","","",""],
["screwdriver2","_none","_none","you should probably talk to the gardener before randomly taking her stuff.","","","null","","",""],
["vent","","","_pass","","numa_crying and not numa_quest_complete",['numa_cry', 'ventc'],"","",""],
["ventc","","","_pass","","numa_snooped",['vent_locked', 'ventc2'],"","",""],
["ventc2","","","_pass","","_inv_screwdriver",['vent_open', 'vent_closed'],"","",""],
["vent_closed","","","the vent is secured by several screws.","","","","","",""],
["","","","if you had a screwdriver, you could probably open it.","_quest_vent","","null","","",""],
["vent_open","","","you use the screwdriver to loosen the cover.",[['opened_vent', true], ['_quest_vent', false]],"","null","","",""],
["vent_locked","","","you can't get in because numa took the screwdriver.","","","null","","",""],
["vent_not_rn","","","elijah's poem probably isn't in there.","","","","","",""],
["","","","you can play around in the vents later!","","","null","","",""],
["numas_notebook","_none","_none","it says \"numa's diary\" on the front","","","","","",""],
["","","","read it?","","","","",['yes', 'no'],['notebook_read', 'notebook_end']],
["notebook_read","","","you open to a random page in the middle of the notebook.","","","","","",""],
["","","","[i]day 458[/i]","","","","","",""],
["","","","[i]the deathberries are going to ripen soon. i cant wait. (sarcasm.)[/i]","","","","","",""],
["","","","[i]i started pruning the thorns off the roses. maybe it'll save someone from a prick some day.[/i]","","","","","",""],
["","","","[i]i wish kyungsoon was here. she would probably think the deathberries are ugly though. (they are pretty ugly.)[/i]","","","","","",""],
["notebook_end","_none","","you put the notebook down.","","","null","","",""],
["numas_drawing","_none","_none","it's a drawing of a snail and a hyena holding hands.","","","null","","",""],
["flowers_etc","_none","_none","the gifts that numa dropped.","","","null","","",""],
["room_placeholder","_none","_none","(placeholder) sorry, you can't go there.","","","null","","",""],
["welcome_sign","","","_pass","",['postgame', 'antechamber_portal'],['welcome_sign3', 'welcome_sign2', 'welcome_sign1'],"","",""],
["welcome_sign1","_none","_none","\"welcome to purrgatory.\"","","","","","",""],
["","","","what a warm welcome.","","","null","","",""],
["welcome_sign2","_none","_none","\"welcome to purrgatory.\"","","","","","",""],
["","","","a little late, now.","","","null","","",""],
["welcome_sign3","_none","_none","\"welcome to purrgatory.\"","","","","","",""],
["","","","it's almost like nothing happened at all.","","","null","","",""],
["lucifur_wuz_here","","","_pass","","postgame",['lucifur_wuz_here2', 'lucifur_wuz_here1'],"","",""],
["lucifur_wuz_here1","_none","_none","\"lucifur wuz here.\" ","","","null","","",""],
["lucifur_wuz_here2","_none","_none","oh, THAT'S who wrote this.","","","null","","",""],
["library_sign","_none","_none","\"commons.\"","","","null","","",""],
["bell_sign","","","_pass","","postgame",['bell_sign2', 'bell_sign1'],"","",""],
["bell_sign1","_none","_none","looks like someone's taken a bite out of this sign.","","","null","","",""],
["bell_sign2","_none","_none","\"hell.\"","","","","","",""],
["","","","at least you're not there.","","","null","","",""],
["antechamber_ttt","","","_pass","","postgame",['antechamber_ttt2', 'antechamber_ttt1'],"","",""],
["antechamber_ttt1","_none","_none","it's a draw.","","","null","","",""],
["antechamber_ttt2","_none","_none","still a draw.","","","null","","",""],
["antechamber_tally","","","_pass","","postgame",['antechamber_tally2', 'antechamber_tally1'],"","",""],
["antechamber_tally1","_none","_none","someone counted to 21 here.","","","null","","",""],
["antechamber_tally2","_none","_none","maybe you should start drawing tallies too...","","","null","","",""],
["commons_lamp","_none","_none","it's a lamp.","","","","","",""],
["","","","enlightening!","","","null","","",""],
["commons_chair1","_none","_none","a chair.","","","null","","",""],
["commons_chair2","_none","_none","this chair has seen better days.","","","null","","",""],
["poetry_slam_sign","_none","_none","it says \"purrgatory poetry slam.\"","","","null","","",""],
["hallway_pipe","_none","_none","a pipe.","","","","","",""],
["","_none","_none","maybe getting out of here is a [i]pipe[/i] dream.","","","null","","",""],
["cat_picture","_none","_none","isn't this the cat from the other room?","","","null","","",""],
["hallway_tally1","_none","_none","11 tallies.","","","null","","",""],
["pencil","_none","_none","a pencil. the lead is broken.","","","null","","",""],
["spiderweb1","_none","_none","oh god is that a spiderweb?","","","","","",""],
["","","","do spiders go to purrgatory??","","","null","","",""],
["clock","_none","_none","a clock with no hands.","","","null","","",""],
["trash_can","_none","_none","a trash can.","","","null","","",""],
["water_tap","_none","_none","a water cooler. it looks like it's full of orange soda.","","oliver_asked_for_soda",['water_tap2', 'null'],"","",""],
["water_tap2","","","no cups, though, so you can't get any for oliver.","","","","","",""],
["","","","wonder where you could find one...?","","","null","","",""],
["piano","_none","_none","it's an electric piano.","","","null","","",""],
["piano_chair","_none","_none","yet another chair.","","","null","","",""],
["fake_door","_none","_none","this isn't a door, just a drawing of a door on the wall.","","","null","","",""],
["puddle","_none","_none","a puddle of something.","","","null","","",""],
["escalator","_none","_none","this escalator only goes down...","","","null","","",""],
["caution_sign","_none","_none","\"caution.\"","","","null","","",""],
["meowseum_ttt","_none","_none","X wins!","","","","","",""],
["","","","just kidding. it's a draw.","","","null","","",""],
["donations_jar","_none","_none","a jar for donations, repurposed from a fish bowl.","","","","","",""],
["","","","guess they're [i]fishing[/i] for money!","","","","","",""],
["","","","mysteriously, there's a sock and a leaf inside.","","","null","","",""],
["exit_sign","_none","_none","unfortunately, this is probably an exit out of the meowseum, not purrgatory.","","","null","","",""],
["meowseum_lamp","_none","_none","a lamp.","","","null","","",""],
["tile","_none","_none","someone has pulled a tile off the floor. it's cement underneath.","","","null","","",""],
["spiderweb2","_none","_none","oh god more spiders","","","null","","",""],
["chair_picture","_none","_none","why would anyone frame a picture of a chair...?","","","null","","",""],
["down_button","_none","_none","this button opens the door.","","","null","","",""],
["elevator_panel","_none","_none","_pass","","","","","",""],
["elevator_button","_none","_none","you push the button, but the elevator doesn't move.","","","","","",""],
["","","","guess you're already on that floor.","","","null","","",""],
["graveyard","_none","_none","a graveyard in the afterlife?","","","null","","",""],
["river","_none","_none","the river is full of milk. yuck.","","","null","","",""],
["garden_tree","_none","_none","despite being dead, this tree is bearing some sort of black fruit.","","","null","","",""],
["garden_bush","_none","_none","a dead bush.","","","","","",""],
["","","","no need to beat around it!","","","null","","",""],
["garden_sapling","_none","_none","a sapling.","","","null","","",""],
["garden_mural","_none","_none","someone's drawn a nice mural on the walls!","","","null","","",""],
["catnip","_none","_none","is that... catnip?","","","null","","",""],
["garden_ttt","_none","_none","another draw.","","","null","","",""],
["garden_potted_plant","_none","_none","a potted plant.","","","null","","",""],
["garden_pot","_none","_none","a pot.","","","null","","",""],
["garden_boots","_none","_none","rain boots.","","","","","",""],
["","","","does it rain in purrgatory...?","","","null","","",""],
["garden_bricks","_none","_none","some bricks.","","","null","","",""],
["dried_flower","_none","_none","a sad looking flower.","","","null","","",""],
["well","_none","_none","well, well, well, what do we have here?","","","","","",""],
["","","","(it's a well.)","","","","","",""],
["","","","(also it's full of milk.)","","","null","","",""],
["garden_flowers","_none","_none","these flowers smell like fish. gross.","","","null","","",""],
["sock","_none","_none","a sock.","","","","","",""],
["","","","being in purrgatory really [i]socks.[/i]","","","null","","",""],
["hallway_lightbulb","_none","_none","a lightbulb.","","","","","",""],
["","","","it's dead, of course.","","","null","","",""],
["cubby_pillow","_none","_none","the pillow is stuffed with leaves.","","","null","","",""],
["cubby_tally","_none","_none","lots and lots of tally marks.","","","null","","",""],
["cubby_blanket","_none","_none","looks like someone was sleeping here.","","","null","","",""],
["reception_sign","_none","_none","\"welcome.\"","","","null","","",""],
["filing_cabinet","_none","_none","it's a filing cabinet.","","","null","","",""],
["reception_plant","_none","_none","this potted plant is obviously dead.","","","null","","",""],
["reception_desk","_none","_none","the receptionist's desk.","","","null","","",""],
["reception_paper","_none","_none","some paper or something.","","","null","","",""],
["reception_water","_none","_none","water. ","","","","","",""],
["","","","it's important to stay hydrated!","","","null","","",""],
["reception_computer","_none","_none","a really old computer.","","","null","","",""],
["reception_picture","_none","_none","a picture frame.","","","null","","",""],
["vent_leaf","_none","_none","a leaf.","","","","","",""],
["","","","why would anyone [i]leaf[/i] this lying around?","","","null","","",""],
["vent_stick","_none","_none","a stick.","","","","","",""],
["","","","why would anyone [i]stick[/i] this in a vent?","","","null","","",""],
["vent_leaves","_none","_none","more leaves.","","","","","",""],
["","","","i can't be-[i]leaf[/i] you're not out of puns yet!","","","null","","",""],
["ending_sign","_none","_none","(this is the end of the current build.)","","","","","",""],
["","","","(there are no more objectives to complete.)","","","","","",""],
["","","","(thank you for playing!)","","","null","","",""],
["default","_none","_none","(placeholder) you look at the thing.","","","null","","",""],
["house_cat","_none","_none","_pass","","house_cat_pushed_glass",['house_cat2', 'house_cat1'],"","",""],
["house_cat1","_none","_none","...what's that cat doing here?","","","null","","",""],
["house_cat2","_none","_none","bad cat!","","","null","","",""],
["house_glass","_none","_none","a glass, dangerously close to the edge.","","oliver_asked_for_soda",['house_glass2', 'null'],"","",""],
["house_glass2","","","you could use this to get oliver some orange soda!","house_cat_pushed_glass","","","","",""],
["","","","as you reach for the glass, the cat locks eyes with you.","house_natalie_heard_glass","","","","",""],
["","you","","don't you dare.","_delay_house_cat_pushing_glass","","null","","",""],
["house_glass_next","you","_none","dammit.","","met_natalie and not looking_for_poem",['null', 'house_glass_end'],"","",""],
["house_glass_end","_none","","maybe you should just tell oliver that you can't find a cup.",[['_quest_oliver_soda1', false], ['_quest_oliver_soda2', true]],"","null","","",""],
["null","_none","_none","_pass","","","null","","",""],
["passcode","_none","_none","it's a crumpled up poem. it says:","got_meowseum_passcode","","","","",""],
["","","","[i]purrgatory is a maze[/i]","","","","","",""],
["","","","[i]and sometimes a haze[/i]","","","","","",""],
["","","","[i]but at least here[/i]","","","","","",""],
["","","","[i]there are no mondays[/i]","","","","","",""],
["","","","in the corner, in much messier handwriting, is the phrase \"passcode: ronnie wood.\"","","","null","","",""],
["battery1","_none","_none","it's a double-a battery! this'll come in handy.","_inv_battery1","","null","","",""],
["battery2","_none","_none","it's a double-a battery! what luck.","_inv_battery2","","null","","",""],
["out_of_batteries","_none","_none","it's out of batteries...","","","null","","",""],
["crumpled_papers","_none","_none","that's a lot of paper.","","","null","","",""],
["antechamber_rubble","_none","_none","some rubble.","","","null","","",""],
["antechamber_ceiling","","","_pass","","postgame",['antechamber_ceiling2', 'antechamber_ceiling1'],"","",""],
["antechamber_ceiling1","_none","_none","someone should fix this ceiling.","","","null","","",""],
["antechamber_ceiling2","_none","_none","still needs to be fixed.","","","null","","",""],
["attic_galaxy","_none","_none","a drawing of a galaxy.","","natalie_awake_in_attic and not looking_for_poem",['attic_galaxy1', 'null'],"","",""],
["attic_galaxy1","natalie","natalie_neutral","i call this one \"starry night!\"","show_natalie","","","","",""],
["","you","","isn't there already a piece of art called that?","","","","","",""],
["","natalie","","nah, i don't think so","","","null","","",""],
["attic_books","_none","_none","this desk is being held up by a couple of books.","","","null","","",""],
["attic_dog","_none","_none","what a cute dog!","","natalie_awake_in_attic and not looking_for_poem",['attic_dog1', 'null'],"","",""],
["attic_dog1","natalie","natalie_neutral","that's my dog, jimmy!","show_natalie","","null","","",""],
["attic_rainbow","_none","_none","a rainbow.","","natalie_awake_in_attic and not looking_for_poem",['attic_rainbow1', 'null'],"","",""],
["attic_rainbow1","natalie","natalie_neutral","that's just a rainbow or something, idk","show_natalie","","null","","",""],
["attic_ufo","_none","_none","a ufo.","","natalie_awake_in_attic and not looking_for_poem",['attic_ufo1', 'null'],"","",""],
["attic_ufo1","natalie","natalie_neutral","my great uncle claimed he was abducted by a ufo in the 60's!","show_natalie","","","","",""],
["","","","he also said that he had mind reading powers that only worked on frogs","","","","","",""],
["","","","great uncle ernesto was kind of weird","","","null","","",""],
["attic_dog2","_none","_none","doggo!","","natalie_awake_in_attic and not looking_for_poem",['attic_dog2_1', 'null'],"","",""],
["attic_dog2_1","natalie","natalie_neutral","doggo!!","show_natalie","","null","","",""],
["attic_grandma","_none","_none","a drawing of an old lady.","","natalie_awake_in_attic and not looking_for_poem",['attic_grandma1', 'null'],"","",""],
["attic_grandma1","natalie","natalie_neutral","that's my grandmother, may she rest in peace","show_natalie","","","","",""],
["","","","hopefully in heaven and not here","","","null","","",""],
["attic_moth","_none","_none","a moth.","","natalie_awake_in_attic and not looking_for_poem",['attic_moth1', 'null'],"","",""],
["attic_moth1","natalie","natalie_neutral","that's the main character of my webcomic, sofia!","show_natalie","","","","",""],
["","","","she's a little off model due to all of my refs being on earth","","","null","","",""],
["attic_meowna_lisa","_none","_none","it's the mona lisa with a cat face.","","natalie_awake_in_attic and not looking_for_poem",['attic_meowna_lisa1', 'null'],"","",""],
["attic_meowna_lisa1","you","","wow, did you draw this too?","","","","","",""],
["","natalie","natalie_neutral","uhh, yeah, totally!","show_natalie","","null","","",""],
["attic_candles","_none","_none","some candles.","","","null","","",""],
["attic_window","_none","_none","there's nothing behind this window, it's just mounted on the wall.","","","null","","",""],
["attic_footstool","_none","_none","footstool. for short people.","","","null","","",""],
["attic_nightstand","_none","_none","there's a lighter and some dust bunnies in the drawer.","","","null","","",""],
["attic_bed","_none","_none","a cozy bed.","","","null","","",""],
["attic_desk","_none","_none","there are some art supplies inside.","","","null","","",""],
["attic_crate","_none","_none","a wooden box.","","","","","",""],
["","","","isn't that [i]crate[/i]?","","","null","","",""],
["towels","_none","_none","some dirty towels.","","","null","","",""],
["closet_big_box","_none","_none","this box is full of spoons?","","","null","","",""],
["wipes","_none","_none","wipes.","","","null","","",""],
["closet_towels","_none","_none","some neatly stacked towels.","","","null","","",""],
["cleaner","_none","_none","cleaning fluid.","","","null","","",""],
["fertilizer_bag","_none","_none","a stinky, stinky bag of fertilizer.","","","null","","",""],
["closet_soap","_none","_none","soap.","","","null","","",""],
["closet_paper_towels","_none","_none","some paper towels.","","","null","","",""],
["closet_boxes","_none","_none","these boxes are empty.","","","null","","",""],
["closet_rope","_none","_none","rope.","","","null","","",""],
["electric_box_warning","_none","_none","it says \"danger: risk of death.\"","","","null","","",""],
["electric_box_note","_none","_none","a scribbled note that says \"no shit\"","","","null","","",""],
["electric_box","","","_pass","","blackout",['electric_box1', 'electric_box2'],"","",""],
["electric_box1","_none","_none","it's too dark to mess with the wires.","","","null","","",""],
["electric_box2","_none","_none","some sort of electric box?","","","null","","",""],
["closet_tile","_none","_none","a displaced ceiling tile.","","","null","","",""],
["closet_wires","_none","_none","you're no expert, but that really doesn't look safe.","","","null","","",""],
["closet_pipe","_none","_none","an exposed pipe.","","","","","",""],
["","","","maybe getting out of here is a [i]pipe[/i] dream.","","","","","",""],
["","","","...did you make that joke already?","","","null","","",""],
["paper_towel_holder","_none","_none","paper towels.","","","null","","",""],
["cylinder","_none","_none","it's...","","","","","",""],
["","","","uh...","","","","","",""],
["","","","actually, you have no clue what this is.","","","null","","",""],
["closet_sink","_none","_none","a sink.","","","null","","",""],
["closet_notes","_none","_none","some notes about supply deficiencies or something.","","","null","","",""],
["calendar","_none","_none","according to this calendar, it's meowvember the fourth.","","","null","","",""],
["commons_mat","_none","_none","a mat.","","","null","","",""],
["commons_poem","_none","_none","someone dropped some notes here.","","","","","",""],
["","","","the writing is illegible.","","","null","","",""],
["tack","_none","_none","a loose tack.","","","","","",""],
["","","","that's just [i]tack[/i]-y!","","","null","","",""],
["dropoff_fence","_none","_none","this fence is not very sturdy.","","","null","","",""],
["dropoff_pit","_none","_none","no sign of the bottom.","","","null","","",""],
["elevator_railing","_none","_none","it's a railing.","","","null","","",""],
["emergency_lights","_none","_none","some emergency lights, maybe?","","","null","","",""],
["exit_door","_none","_none","it won't open.","","","null","","",""],
["exit_painting","_none","_none","it's that freaking cat again!","","","null","","",""],
["field_tree","_none","_none","a dead tree.","","","null","","",""],
["field_rocks","_none","_none","a rock.","","","null","","",""],
["field_river","_none","_none","the river is full of milk. yuck.","","","null","","",""],
["weeds","_none","_none","weeds.","","","null","","",""],
["wheelbarrow","_none","_none","a wheelbarrow full of weeds.","","","","","",""],
["","","","a weedbarrow!","","","null","","",""],
["field_grave1","_none","_none","\"he was a proud father of 16 cats.\"","","","null","","",""],
["field_grave2","_none","_none","\"she died like she lived: unremarkably.\"","","","null","","",""],
["field_grave3","_none","_none","\"good riddance.\"","","","null","","",""],
["field_grave4","_none","_none","\"ze died like ze lived: fighting crocodiles.\"","","","null","","",""],
["field_grave5","_none","_none","this one just says \"brb.\"","","","null","","",""],
["field_grave6","_none","_none","\"they were a good parent but a bad tightrope walker.\"","","","null","","",""],
["field_flowers","_none","_none","aw, someone left them some flowers!","","","null","","",""],
["field_fence","_none","_none","a fence.","","","","","",""],
["","","","no of-[i]fence[/i] taken!","","","null","","",""],
["field_shack","_none","_none","a broken down shack.","","","null","","",""],
["bad_tree","_none","_none","is it just you, or is that tree more poorly drawn than the others?","","","null","","",""],
["field_tiny_tree","_none","_none","it's a tiny little tree!","","","null","","",""],
["field_distant_cemetery","_none","_none","there's a graveyard over there.","","","null","","",""],
["field_distant_doorway","_none","_none","a doorway in the distance.","","","null","","",""],
["field_bench","_none","_none","a bench.","","","null","","",""],
["field_sign","_none","_none","it says \"please stay off the grass! - purrgatory paw-rks and re-claw-ation.\"","","","","","",""],
["","","","ok, that one's a bit of a stretch.","","","null","","",""],
["field_bush","_none","_none","a dead bush.","","","null","","",""],
["horseshoe","_none","_none","looks like someone was playing horseshoe.","","","null","","",""],
["field_path","_none","_none","a nice scenic path.","","","null","","",""],
["field_grate","_none","_none","this is where the milk is coming from.","","","null","","",""],
["garden_sidewalk_end","_none","_none","a sidewalk sort of ends here.","","","","","",""],
["","","","guess it got [i]side[/i]-tracked!","","","null","","",""],
["garden_liquid","_none","_none","you don't even want to know what that liquid is.","","","null","","",""],
["garden_mallet","_none","_none","a mallet.","","","null","","",""],
["garden_spade","_none","_none","a spade.","","","","","",""],
["","","","looks like purrgatory has gardening supplies in [i]spades[/i].","","","null","","",""],
["garden_paint","_none","_none","a can of white paint.","","","null","","",""],
["garden_pencil","_none","_none","a pencil.","","","null","","",""],
["garden_cube","_none","_none","a mysterious tiny cube.","","","null","","",""],
["garden_rock","_none","_none","a rock.","","","null","","",""],
["garden_pebble","_none","_none","a pebble.","","","null","","",""],
["garden_sidewalk","_none","_none","the sidewalk.","","","null","","",""],
["garden_ceiling","_none","_none","some sort of advanced watering and lighting system.","","","null","","",""],
["compost","_none","_none","some compost.","","","null","","",""],
["garden_wires","_none","_none","wires.","","","","","",""],
["","","","[i]wire[/i] you even looking at these?","","","null","","",""],
["garden_leaves","_none","_none","some cronchy looking leaves.","","","null","","",""],
["garden_flower","_none","_none","a flower.","","","null","","",""],
["hoe","_none","_none","a hoe.","","","null","","",""],
["hallway_puddle","_none","_none","the pipe's leaking a little.","","","null","","",""],
["hallway_rocks","_none","_none","rocks.","","","null","","",""],
["hallway_stalagtites","_none","_none","stalactites, not stalagmites.","","","","","",""],
["","","","remember, c is for ceiling, g is for ground!","","","null","","",""],
["cave_sign","_none","_none","it says \"watch your paws!\"","","","null","","",""],
["cave_path","_none","_none","who designed this path??","","","null","","",""],
["cave_stuff","_none","_none","cave stuff.","","","null","","",""],
["more_cave_stuff","_none","_none","more cave stuff.","","","null","","",""],
["elijahs_chair","_none","_none","chair.","","","null","","",""],
["elijahs_bookshelf","_none","_none","a mostly empty bookshelf.","","","null","","",""],
["elijahs_desk","_none","_none","a desk, also covered in papers.","","","null","","",""],
["odontophorous","_none","_none","odonto-what now?","","","null","","",""],
["spiderweb3","_none","_none","MORE SPIDERS","","","null","","",""],
["meowseum_lamp","_none","_none","cool lamps.","","","null","","",""],
["meowseum_poster","_none","_none","an advertisement for an exhibit called \"discover the cat.\"","","","null","","",""],
["meowseum_bench","_none","_none","a bench.","","","null","","",""],
["tile","_none","_none","someone dug up a floor tile here.","","","","","",""],
["","","","you're [i]floored[/i]!","","","null","","",""],
["meowseum_sign","_none","_none","\"the cat meowseum\"?","","","null","","",""],
["hours_sign","_none","_none","according to this sign, the meowseum is open every day except mewsday.","","","null","","",""],
["rock_tower","_none","_none","some sort of rock tower thing?","","","null","","",""],
["catwalk","_none","_none","it's a [i]cat[/i]-walk!","","","","","",""],
["","","","also this looks VERY unsafe.","","","null","","",""],
["catwalk_exit","_none","_none","looks like you need to come from the other side to lower this drawbridge.","","","null","","",""],
["drawbridge_up","_none","_none","looks like you need to come from the other side to lower this drawbridge.","","","null","","",""],
["drawbridge_down","_none","_none","oh cool, someone lowered this drawbridge for you.","","","null","","",""],
["house_cacti","_none","_none","some sort of cactus or something.","","","null","","",""],
["house_welcome","_none","_none","\"welcome.\"","","","null","","",""],
["house_lamp","_none","_none","a stylish lamp.","","","null","","",""],
["house_couch","_none","_none","a sofa.","","","null","","",""],
["house_carpet1","_none","_none","a carpet.","","","null","","",""],
["house_window","_none","_none","it's just bricks behind this window.","","","null","","",""],
["house_bowl","_none","_none","a bowl.","","","null","","",""],
["house_cylinder","_none","_none","a cylinder.","","","null","","",""],
["flower_picture","_none","_none","a nice picture of a flower.","","","null","","",""],
["house_soap","_none","_none","a bar of soap.","","","null","","",""],
["house_rag","_none","_none","a rag.","","","null","","",""],
["house_vase","_none","_none","what a fancy vase!","","","null","","",""],
["house_carpet2","_none","_none","another carpet.","","","null","","",""],
["house_stool","_none","_none","a stool.","","","null","","",""],
["broken_glasses","_none","_none","looks like someone was pushing glasses off of this counter.","","","null","","",""],
["conveyer_belt","_none","_none","some sort of glass delivering machine?","","","null","","",""],
["house_bin","_none","_none","this chute goes down forever.","","","null","","",""],
["toaster","_none","_none","a toaster.","","","null","","",""],
["house_mat","_none","_none","some sort of mat.","","","null","","",""],
["house_sink","_none","_none","a sink!","","","","","",""],
["","","","...","","","","","",""],
["","","","yep, it dispenses milk.","","","null","","",""],
["house_cabinets","_none","_none","you can't open these because someone forgot to draw handles on them.","","","null","","",""],
["house_potted_plant","_none","_none","cool plant.","","","null","","",""],
["stained_glass","_none","_none","a stained glass window.","","","null","","",""],
["house_upstairs_carpet","_none","_none","a carpet.","","","null","","",""],
["house_pillows","_none","_none","someone REALLY went to town on these pillows.","","","null","","",""],
["live_laugh_meow","_none","_none","\"live laugh meow.\"","","","null","","",""],
["bedroom_bed","_none","_none","instead of a mattress, this bed just has a cat bed on top of it.","","","null","","",""],
["bedroom_lamp","_none","_none","a little lamp.","","","null","","",""],
["bedroom_table","_none","_none","a stylish table.","","","null","","",""],
["bedroom_rug","_none","_none","it's a carpet.","","","","","",""],
["","","","or is it a rug?","","","","","",""],
["","","","it probably doesn't [i]mat[/i]-ter.","","","null","","",""],
["library_windows","_none","_none","some big old windows.","","","null","","",""],
["library_pencil","_none","_none","a pencil.","","","null","","",""],
["library_magnifying_glass","_none","_none","a magnifying glass.","","","null","","",""],
["library_work_papers","_none","_none","some papers covered with notes.","","","null","","",""],
["library_work_books","_none","_none","these are all full of meows too.","","","null","","",""],
["library_ceiling_lamps","_none","_none","these tiny spheres are lamps.","","","","","",""],
["","","","[i]orb[/i] are they?","","","","","",""],
["","","","(yeah, they are.)","","","null","","",""],
["library_infinity","_none","_none","an infinity sign.","","","","","",""],
["","","","well, that's a little on the nose.","","","null","","",""],
["david","_none","_none","that's michelangelo's david!","","","","","",""],
["","","","something looks a bit off...","","","null","","",""],
["library_lamp","_none","_none","a lamp.","","","null","","",""],
["standing_cat","_none","_none","it's a cat standing on its hind legs.","","","null","","",""],
["lucifur_paintings","_none","_none","how many pictures of this cat are there??","","","null","","",""],
["donations_text","_none","_none","it says \"donations. your contributions are greatly appreciate! - meowseum meow-nagement\"","","","null","","",""],
["lobby_bench","_none","_none","a bench.","","","null","","",""],
["lobby_infinity","_none","_none","infinity.","","","null","","",""],
["standing_cat_sign","_none","_none","this sign says \"felis erectus, the ancestor of the modern human.\" ","","","","","",""],
["","","","that... doesn't seem right?","","","null","","",""],
["cat_with_pearl_earring","_none","_none","this is the painting from the poster!","","opened_meowseum_door and not sean_broke_sculpture",['cat_with_pearl_earring_elijah', 'null'],"","",""],
["cat_with_pearl_earring_sign","_none","_none","\"johannes furmeer. [i]cat with a pearl earring,[/i] c. 1665. oil on canvas.\"","","","null","","",""],
["meowseum_tallies","_none","_none","7 tallies.","","","null","","",""],
["yarn","_none","_none","it's just a ball of yarn.","","opened_meowseum_door and not sean_broke_sculpture",['yarn_elijah', 'null'],"","",""],
["yarn_sign","_none","_none","\"a holy artifact. source unknown.\"","","","null","","",""],
["discover_the_cat","_none","_none","\"discover the cat. an exhibit all about our claw-some feline fur-riends!\"","","","","","",""],
["","","","the rest of this sign is basically just cat puns.","","opened_meowseum_door and not sean_broke_sculpture",['discover_the_cat_elijah', 'null'],"","",""],
["cat_gogh","_none","_none","a portrait of a cat.","","opened_meowseum_door and not sean_broke_sculpture",['cat_gogh_elijah', 'null'],"","",""],
["apple_cat","_none","_none","a cat with an apple in front of its head.","","opened_meowseum_door and not sean_broke_sculpture",['apple_cat_elijah', 'null'],"","",""],
["the_screm","_none","_none","isn't the cat supposed to be screaming or something?","","opened_meowseum_door and not sean_broke_sculpture",['the_screm_elijah', 'null'],"","",""],
["screm_sign","_none","_none","\"edvard meownch. [i]the meow,[/i] 1893. oil, tempera, and pastel on cardboard.\"","","","null","","",""],
["missing_painting","_none","_none","looks like a painting is missing.","","opened_meowseum_door and not sean_broke_sculpture",['missing_painting_elijah', 'null'],"","",""],
["missing_painting_sign","_none","_none","\"leonyardo da vinci. [i]meowna lisa,[/i] 1503. oil on poplar panel.\"","","","null","","",""],
["starry_night","_none","_none","...this is just the normal starry night.","","opened_meowseum_door and not sean_broke_sculpture",['starry_night_elijah', 'null'],"","",""],
["starry_night_sign","_none","_none","\"vincent cat gogh. [i]the furry night,[/i] 1889. oil on canvas.\"","","","null","","",""],
["battle_of_cattysburg","_none","_none","a bunch of cats at war.","","opened_meowseum_door and not sean_broke_sculpture",['battle_of_cattysburg_elijah', 'null'],"","",""],
["cattysburg_sign","_none","_none","\"charles pawsper kitten. [i]battle of cattysburg,[/i] c. 1900. oil on canvas.\"","","","null","","",""],
["sphinx","_none","_none","a hairless cat.","","","null","","",""],
["sphinx_sign","_none","_none","\"sphinx. selectively bred to have no fur, these cats also have long, narrow heads and webbed paws. don't be fooled by its appearance, this breed is known to be energetic and affectionate!\"","","","null","","",""],
["cats_come_in","_none","_none","\"cats come in all shapes and sizes.\"","","","","","",""],
["","","","...the rest of this sign is just scribbles?","","","null","","",""],
["cat_inventor","_none","_none","it's a picture of some dude with a cat.","","","null","","",""],
["cat_inventor_sign","_none","_none","\"the only surviving photograph of john cat, the inventor of cats.\"","","","null","","",""],
["statue_lights","_none","_none","some lights.","","","null","","",""],
["maine_coon","_none","_none","a fluffy cat.","","opened_meowseum_door and not sean_broke_sculpture",['maine_coon_sean', 'null'],"","",""],
["maine_coon_broken","_none","_none","rest in pieces, maine coon.","","","null","","",""],
["maine_coon_sign","_none","_none","\"maine coon. adapted for survival in winter climates, these gentle giants are known for their intelligence and playfulness. cat fact: maine coons are the largest breed of domesticated cat in the world!\"","","","null","","",""],
["schrodingers","","","_pass","","opened_meowseum_door and not sean_broke_sculpture",['schrodingers_sean', 'schrodingers_alone'],"","",""],
["schrodingers_alone","_none","_none","a box that says \"do not open.\"","","","","","",""],
["","","","open it?","","","","",['yes', 'no'],['schrodingers1', 'null']],
["schrodingers1","","","there's... nothing inside.","","","null","","",""],
["schrodingers_sign","_none","_none","\"schrodinger's cat. first discovered by cat breeder erwin schrodinger in 1935, these quantum kitties are best known for entering states of quantum superposition. dead or alive, these mysterious cats are the perfect low-maintenance buddy!\"","","","null","","",""],
["airplane","_none","_none","a paper airplane.","","opened_meowseum_door and not sean_broke_sculpture",['airplane_sean', 'null'],"","",""],
["abstract_cat","_none","_none","this one's just a sphere??","","","null","","",""],
["abstract_cat_sign","_none","_none","\"abstract cat. popular among physicists for its uniform density, this breed's natural habitat is a frictionless vacuum. watch out, these spherical felines are as playful as they are homogenous!\"","","","null","","",""],
["scaly_cat","_none","_none","that's a lizard.","","","null","","",""],
["scaly_cat_sign","_none","_none","\"scaly cat. known for its long, forked tongue and tapered tail, this wacky cat has armored scales instead of fur. If you can get past its rough exterior, this breed can be a loyal and loving friend!\"","","","null","","",""],
["3d_cat","_none","_none","it's... it's beautiful.","","","null","","",""],
["3d_cat_sign","_none","_none","\"CAT.\"","","","null","","",""],
["3d_cat_lights","_none","_none","bright lights.","","","null","","",""],
["cat_butt","_none","_none","clearly this painting was too beautiful to display outside.","","","null","","",""],
["filing_boxes","_none","_none","some filing boxes or something.","","","null","","",""],
["meowseum_pencil","_none","_none","it's a popsicle stick.","","","null","","",""],
["meowseum_cards","_none","_none","some flash cards.","","","null","","",""],
["this_side_right","_none","_none","it says \"this side right.\"","","","null","","",""],
["litter_box","_none","_none","whatever's in this box smells really gross.","","","null","","",""],
["spilled_litter","_none","_none","this box is full of... dirt?","","","","","",""],
["","","","...","","","","","",""],
["","","","oh, it's cat litter.","","","null","","",""],
["flat_box","_none","_none","a flat box.","","","","","",""],
["","","","it's not very [i]flat[/i]-tering.","","","null","","",""],
["mop_bucket","_none","_none","a mop bucket.","","","null","","",""],
["mop","_none","_none","a mop.","","","null","","",""],
["mop_water","_none","_none","mop water.","","","null","","",""],
["pipe2","_none","_none","another pipe.","","","null","","",""],
["hallway_crack","_none","_none","a crack.","","","","","",""],
["","","","guess the afterlife's not all it's [i]cracked[/i] out to be.","","","null","","",""],
["hallway_scribble","_none","_none","just a scribble.","","","null","","",""],
["trash_can_paper","_none","_none","someone threw a poem into this trash can.","","","","","",""],
["","","","[i]orange soda[/i]","","","","","",""],
["","","","[i]lukewarm and runny[/i]","","","","","",""],
["","","","[i]whenever i drink it[/i]","","","","","",""],
["","","","[i]my stomach feels funny[/i]","","","null","","",""],
["chairon","_none","_none","the receptionist's chair.","","","null","","",""],
["reception_keyboard","_none","_none","a keyboard.","","","null","","",""],
["reception_mouse","_none","_none","a mouse.","","","null","","",""],
["study_lamp","_none","_none","oliver's desk lamp.","","","null","","",""],
["study_board","_none","_none","a board covered in notes and stuff.","","","null","","",""],
["study_books","_none","_none","some books that oliver was cataloging, maybe?","","","null","","",""],
["study_papers","_none","_none","this handwriting is completely illegible!","","","null","","",""],
["study_floor_papers","_none","_none","some papers on the floor.","","","null","","",""],
["study_bed","_none","_none","looks like oliver sleeps here too.","","","null","","",""],
["study_chair","_none","_none","a comfy looking desk chair.","","","null","","",""],
["train_display","_none","_none","looks like some sort of train schedule.","","","","","",""],
["","","","under \"departures\" it says \"heaven: delayed.\"","","","","","",""],
["","","","under \"arrivals\" it says \"{player}: arrived.\"","","","null","","",""],
["train_bench","_none","_none","an uncomfortable looking bench.","","","null","","",""],
["vending_machine","_none","_none","a vending machine.","","","null","","",""],
["train_exits","_none","_none","unfortunately, this tunnel ends in like ten feet.","","","null","","",""],
["train_tracks","_none","_none","train tracks that don't go anywhere.","","","null","","",""],
["train_columns","_none","_none","a column. holds up the ceiling.","","","null","","",""],
["crowbar","_none","_none","a crowbar.","","","null","","",""],
["warehouse_wood","_none","_none","just a plank or something.","","","null","","",""],
["containers","_none","_none","lots of big containers.","","","null","","",""],
["cat_food","_none","_none","yep, that's cat food.","","","null","","",""],
["warehouse_button2","_none","_none","opens the door.","","","null","","",""],
["warehouse_cube","_none","_none","some sort of... cube.","","","null","","",""],
["warehouse_notice","_none","_none","it says \"notice: paw-thorized workers only in the warehouse, please!\"","","","","","",""],
["","","","in smaller text, it says \"(beware of hazardous materials and heavy machinery. purrgatory claims no liability in the case of death or dismemberment.)\"","","","null","","",""],
["warehouse_electrical_box","_none","_none","an electrical box.","","","null","","",""],
["warehouse_pallet","_none","_none","a pallet.","","","null","","",""],
["warehouse_cardboard","_none","_none","some cardboard boxes.","","","null","","",""],
["spiral_staircase","_none","_none","a spiral staircase.","","","null","","",""],
["warehouse_skylight","_none","_none","there's nothing behind this skylight, just ceiling.","","","null","","",""],
["small_containers","_none","_none","small containers.","","","null","","",""],
["closet_water","_none","_none","it's milk. you don't even have to check.","","","null","","",""],
["broom","_none","_none","a broom.","","","null","","",""],
["bucket","_none","_none","a bucket.","","","null","","",""],
["closet_blanket","_none","_none","a blanket.","","","null","","",""],
["dropoff_dropoff","_none","_none","you carefully peek over the edge.","_goto_dropoff2","","null","","",""],
["field_arch","_none","_none","cool archway.","","","null","","",""],
["field_bricks","_none","_none","bricks.","","","null","","",""],
["draw_a_paw","_none","_none","it's one of those old draw-a-paw toys with a half-drawn dog on it.","","","","","",""],
["","","","on the back, it says \"if found, return to natalie pls.\"","","","","","",""],
["","","","maybe you should hold on to this.",[['_inv_draw_a_paw', true], ['_quest_natalie_draw_a_paw', true]],"","null","","",""],
["hallway_mural","_none","_none","you and natalie's beautiful mural.","","","null","","",""],
["field_x","_none","_none","a big old X on the ground.","","","null","","",""],
["attic_pencil_box","_none","_none","looks like natalie replaced the books with a box of pencils.","","","null","","",""],
["attic_anime","_none","_none","looks like a cartoon character.","","","null","","",""],
["attic_hallway","_none","_none","a drawing of a hallway filled with doors.","","","null","","",""],
["attic_cat","_none","_none","this cat looks suspiciously familiar...","","","null","","",""],
["attic_map","_none","_none","some sort of treasure map.","","","null","","",""],
["attic_scripts","_none","_none","a script, probably for natalie's webcomic.","","","null","","",""],
["attic_planets","_none","_none","a diagram of some planets, complete with scientific notes.","","","null","","",""],
["attic_something","_none","_none","you don't even know what this is supposed to be.","","","null","","",""],
["attic_something2","_none","_none","a page of doodles.","","","null","","",""],
["attic_castle","_none","_none","a menacing castle at night.","","","null","","",""],
["attic_six_arms","_none","_none","a character with four arms.","","","null","","",""],
["attic_ref","_none","_none","a ref sheet for natalie's moth character.","","","null","","",""],
["attic_writing","_none","_none","some writing.","","","null","","",""],
["attic_scribble","_none","_none","artistic scribbles.","","","null","","",""],
["attic_schematic","_none","_none","looks like she's planning a comic page.","","","null","","",""],
["attic_something3","_none","_none","sketches of some characters you don't recognize.","","","null","","",""],
["attic_tape","_none","_none","tape. it's sticky.","","","null","","",""],
["attic_something4","_none","_none","doodles.","","","null","","",""],
["attic_layout","_none","_none","a layout for a comic page.","","","null","","",""],
["attic_discarded","_none","_none","some discarded papers.","","","null","","",""],
["attic_ball","_none","_none","a balled up piece of paper.","","","null","","",""],
["attic_hotdog","_none","_none","a paper folded in half, hotdog style.","","","null","","",""],
["attic_supplies","_none","_none","art supplies.","","","null","","",""],
["field_dirt","_none","_none","a bunch of dirt.","","","","","",""],
["","","","it's dirty.","","","null","","",""],
["field_jacket","_none","_none","tori's blazer.","","","null","","",""],
["dropoff_rope","_none","_none","rope.","","","null","","",""],
["dropoff_rope2","_none","_none","you sure hope this rope is strong...","","","null","","",""],
["dropoff_plank","_none","_none","someone pulled up one of the planks.","","","","","",""],
["","","","why [i]wood[/i] anyone do that?","","","null","","",""],
["house_doorbell","_none","_none","ring the doorbell?","","","",['not rang_doorbell and not met_natalie', 'rang_doorbell or met_natalie', 'true'],['yes', 'yes', 'no'],['house_doorbell1', 'house_doorbell2', 'null']],
["house_doorbell1","_none","","you ring the doorbell.","ding_dong","","","","",""],
["","","","...","rang_doorbell","","","","",""],
["","","","a sleepy-looking moth opens the door.","","","","","",""],
["","???","natalie_neutral","zzz...","","","","","",""],
["","","","cam i... help you?","","","","","",""],
["","you","","oh, uh, hi!","","","","","",""],
["","","","is this your house?","","","","","",""],
["","???","","zzz...","","","","","",""],
["","","","sorry, i dont want any cookies...","","","","","",""],
["","","","im tryna watch my weight...","","","","","",""],
["","you","","uh","","","","","",""],
["","","","what cookies?","","","","","",""],
["","???","","mmmm","","","","","",""],
["","","","coomkies","","","","","",""],
["","_none","","you wave your hand in front of her eyes. she doesn't respond.","","","","","",""],
["","???","","haha, cool","","","","","",""],
["","","","alrighty... have a nice day....","","","","","",""],
["","_none","_none","she closes the door.","","","","","",""],
["","you","","????","","","null","","",""],
["house_doorbell2","_none","","you ring the doorbell.","ding_dong","","","","",""],
["","","","no response.","","","null","","",""],
["snowglobe_library","_none","_none","cool, a snowglobe!","_inv_snowglobe_library","","null","","",""],
["snowglobe_closet","_none","_none","cool, a snowglobe!","_inv_snowglobe_closet","","null","","",""],
["snowglobe_meowseum","_none","_none","cool, a snowglobe!","_inv_snowglobe_meowseum","","null","","",""],
["lockers","","","_pass","","_inv_snowglobe_locker or placed_snowglobes",['lockers2', 'lockers1'],"","",""],
["lockers1","_none","_none","hey, there's something in here...","","","","","",""],
["","","","cool, a snowglobe!","_inv_snowglobe_locker","","null","","",""],
["lockers2","_none","_none","there's nothing left in these lockers.","","","null","","",""],
["snowglobe_house","_none","_none","cool, a snowglobe!","_inv_snowglobe_house","","null","","",""],
["padlock","_none","_none","a padlock, no longer locked.","","","null","","",""],
["open_padlock","_none","_none","the padlock opens!",[["_quest_meowseum_door", false], ["opened_meowseum_door", true]],"","meowseum_opened","","",""],
["see_padlock","_none","_none","the door is locked with a padlock.",[["_quest_meowseum_door", true], ["tried_meowseum_door", true]],"","null","","",""],
["warehouse_door","_none","_none","solid metal.","","","null","","",""],
["elevator_door","_none","_none","an elevator.","","","null","","",""],
["elevator_inside_door","_none","_none","door.","","","null","","",""],
["house_door","_none","_none","looks like it's locked from the inside.","","","null","","",""],
["study_door","_none","_none","seems to be jammed or something.","","","null","","",""],
["hallway_ladder","_none","_none","a ladder.","","","","","",""],
["","","","guess things are looking up!","","","null","","",""],
["phone_blackout","_none","_none","the phone's not working.","","","null","","",""],
["junk_food","_none","_none","more junk food than you could ever want.","","","null","","",""],
["frog","_none","_none","poor froggy.","","","null","","",""],
["commons_outlet","_none","_none","an electrical outlet.","","","null","","",""],
["heaven_fountain","_none","_none","a fountain.","","","","","",""],
["","","","not milk this time.","","","null","","",""],
["heaven_bench","_none","_none","a bench.","","","null","","",""],
["heaven_greenery","_none","_none","wow...","","","","","",""],
["","","","so this is heaven.","","","null","","",""],
["heaven_picnic_table","_none","_none","a nice place for a picnic.","","","null","","",""],
["heaven_planter","_none","_none","a planter?","","","","","",""],
["","","","i 'ardly know 'er!","","","null","","",""],
["heaven_arch","_none","_none","a gateway.","","","","","",""],
["","","","truly a work of [i]arch.[/i]","","","null","","",""],
["heaven_garden","_none","_none","flowers and stuff.","","","null","","",""],
["heaven_building","_none","_none","a big old building.","","","null","","",""],
["heaven_birds","_none","_none","birds.","","","","","",""],
["","","","guess they're just winging it!","","","null","","",""],
["heaven_armchair","_none","_none","a comfy looking armchair.","","","null","","",""],
["heaven_study","_none","_none","a nice place to study.","","","null","","",""],
["heaven_book","_none","_none","these books have actual words in them!","","","null","","",""],
["heaven_painting","_none","_none","a nice painting.","","","null","","",""],
["heaven_clock","_none","_none","a working clock.","","","","","",""],
["","","","it's about time!","","","null","","",""],
["heaven_potted_plant","_none","_none","a fern or something.","","","null","","",""],
["heaven_water","_none","_none","cold, refreshing water.","","","null","","",""],
["heaven_trash","_none","_none","a trash can.","","","null","","",""],
["heaven_chair","_none","_none","chairs.","","","null","","",""],
["heaven_desk","_none","_none","a desk with some travel guides on it.","","","null","","",""],
["heaven_box","_none","_none","a mysterious white box.","","","null","","",""],
["heaven_city","_none","_none","looks like a heavenly city off in the distance.","","","null","","",""],
["heaven_bridge","_none","_none","a stone bridge.","","","null","","",""],
["heaven_cloud","_none","_none","you've never seen a cloud this close before.","","","","","",""],
["","","","looks soft.","","","null","","",""],
["heaven_bench2","_none","_none","a bench.","","","null","","",""],
["heaven_torch","_none","_none","some lights.","","","","","",""],
["","","","things are looking bright!","","","null","","",""],
["heaven_window","_none","_none","a stained glass window.","","","null","","",""],
["heaven_gate","_none","_none","the pearly gates.","","","null","","",""],
["wait_books","_none","_none","some books that oliver was carrying.","","","null","","",""],
["gift_books","_none","_none","the books that oliver gave to kyungsoon.","","","null","","",""],
["library_ladder1","_none","_none","a rickety ladder leading to the next room.","","","null","","",""],
["library_ladder2","_none","_none","no one would mind if you took this ladder... right?",[['_inv_ladder', true], ['took_ladder', true]],"","null","","",""],
["warehouse_ladder","_none","_none","a ladder you stole from oliver.","","","null","","",""],
["cat_toy","","","_pass","","_inv_ladder",['cat_toy2', 'cat_toy1'],"","",""],
["cat_toy1","_none","_none","is that a cat toy up there?","","","","","",""],
["","","","it's too high to reach.","","","null","","",""],
["cat_toy2","_none","_none","a cat toy.","","","","","",""],
["","","","the ladder's just long enough to reach!",[['_inv_ladder', false], ['_inv_cat_toy', true], ['took_cat_toy', true], ['placed_ladder', true]],"","null","","",""],
["cat_toy_stick","_none","_none","the stick that came off the cat toy.","","","null","","",""],
["give_cat_toy","_none","_none","you pull out the cat toy.","","","","","",""],
["","you","","guess who found a kitty toy for you!!","","","","","",""],
["","cat","","meow?","","","","","",""],
["","_none","","you shake the rod, which promptly causes the string to detach from it.","","","","","",""],
["","you","","oh, shoot","","","","","",""],
["","","","um...","","","","","",""],
["","_none","","you drape the remains of the cat toy on the cat. it doesn't seem to mind.",[['_inv_cat_toy', false], ['gave_cat_toy', true]],"","","","",""],
["","you","","there you go","","","null","","",""],
["escalator_wires","_none","_none","wires.","","","null","","",""],
["snowglobe_table","","","_pass","",['placed_snowglobes', '_inv_snowglobe_library and _inv_snowglobe_closet and _inv_snowglobe_meowseum and _inv_snowglobe_locker  and _inv_snowglobe_house and _inv_snowglobe_park and _inv_snowglobe_dropoff'],['snowglobe_table1', 'snowglobe_table2', 'snowglobe_table3'],"","",""],
["snowglobe_table1","_none","_none","a table holding your cool snowglobe collection.","","","null","","",""],
["snowglobe_table2","_none","_none","huh, your cool snowglobes fit perfectly into these little indentations...","","","","","",""],
["","","","a part of the wall slides away, revealing a doorway.",[['placed_snowglobes', true], ['_inv_snowglobes', false]],"","","","",""],
["","you","","ooooh","","","null","","",""],
["snowglobe_table3","_none","_none","a table with seven circular indentations in it.","","","null","","",""],
["snowglobe_freedom","_none","_none","freedom?","","","null","","",""],
["snowglobe_woo","_none","_none","woo!!","","","null","","",""],
["snowglobe_cat","_none","_none","it's a crossed out cat head.","","","null","","",""],
["snowglobe_salvation","_none","_none","salvation this way.","","","","","",""],
["","","","that sounds promising...","","","null","","",""],
["snowglobe_debris1","_none","_none","you have no clue what this might have been.","","","null","","",""],
["snowglobe_debris2","_none","_none","isn't this metal? how did she even eat this??","","","null","","",""],
["snowglobe_debris3","_none","_none","a pile of half-eaten debris.","","","null","","",""],
["snowglobe_poster","_none","_none","some sort of poster.","","","null","","",""],
["snowglobe_pole","_none","_none","a pole or something.","","","","","",""],
["","","","this room is very disa-[i]pole[/i]-ting.","","","","","",""],
["","","","...even that pun was disappointing.","","","null","","",""],
["oliver_ttt","_none","_none","this is where you and oliver played tic tac toe.","","","null","","",""],
["bell_rope","","","_pass","",['blackout', 'numa_crying', 'oliver_sleeping', 'ready_for_slam'],['bell_rope_blackout', 'bell_rope_numa', 'bell_rope_oliver', 'bell_rope_slam', 'bell_rope_default'],"","",""],
["bell_rope_blackout","_none","_none","you should probably fix the lights before calling the slam.","","","null","","",""],
["bell_rope_numa","_none","_none","you should probably make sure numa's okay before calling the slam.","","","null","","",""],
["bell_rope_oliver","_none","_none","you should probably wait till oliver's awake before calling the slam.","","","null","","",""],
["bell_rope_slam","_none","_none","well, it's time to start the everything slam.","","","","","",""],
["","","","ring the bell?","","","","",['yes', 'no'],['bell_rope_slam2', 'null']],
["bell_rope_slam2","_none","_none","you grab the rope and pull with all your strength.",[['_quest_elijah_bell', false]],"","","","",""],
["","","","[i]dong... dong... dong... dong... dong...[/i]","ringing_bell","","","","",""],
["","","","that should do it.",[['ready_for_slam', false], ['slam_in_session', true], ['did_slam', true]],"","null","","",""],
["bell_rope_default","_none","_none","you should probably leave that alone for now.","","","null","","",""],
["meowseum_broom","_none","_none","elijah's discarded broom.","","","null","","",""],
["broken_lock","_none","_none","a broken lock.","","","null","","",""],
["meowseum_mallet","_none","_none","a mallet.","","","","","",""],
["","","","you have a feeling you know what happened to that lock...","","","null","","",""],
["broken_lock_holder","_none","_none","this is where the lock would have gone.","","","null","","",""],
["broken_lamp","_none","_none","a broken lamp.","","met_sean and not opened_meowseum_door",['broken_lamp1', 'null'],"","",""],
["broken_lamp1","sean","sean_neutral","yeah, i busted that lamp a couple weeks ago.","_hide_sean_idle","","","","",""],
["","","","turns out there's a good reason why indoor baseball's not a thing!","","","null","","",""]
]