extends Node

var raw_blocks = [
["screwdriver","_none","_none","you take the screwdriver.","_inv_screwdriver","","null","","",""],
["vent","","","_pass","","numa_crying and not numa_quest_complete",['numa_cry', 'ventc'],"","",""],
["ventc","","","_pass","","numa_snooped",['vent_locked', 'ventc2'],"","",""],
["ventc2","","","_pass","","_inv_screwdriver",['vent_open', 'vent_closed'],"","",""],
["vent_closed","","","the vent is secured by several screws.","","","","","",""],
["","","","if you had a screwdriver, you could probably open it.","_quest_vent","","null","","",""],
["vent_open","","","you use the screwdriver to loosen the cover.",[['opened_vent', true], ['_quest_vent', false]],"","null","","",""],
["vent_locked","","","you can't get in because numa took the screwdriver.","","","null","","",""],
["numas_notebook","_none","_none","it says \"numa's diary\" on the front","","","","","",""],
["","","","read it?","","","","",['yes', 'no'],['notebook_read', 'notebook_end']],
["notebook_read","","","you open to a random page in the notebook.","","","","","",""],
["","notebook","","day 458:\nthe deathberries are going to ripen soon. i cant wait. (sarcasm.)","","","","","",""],
["","","","i started pruning the thorns off the roses. i don't have anything else to do. maybe it'll save someone from a prick some day.","","","","","",""],
["","","","i wish kyungsoon was here. she would probably think the deathberries are ugly though. (they are pretty ugly.)","","","","","",""],
["","","","but everything is ugly in comparison to kyungsoon.","","","","","",""],
["notebook_end","_none","","you put the notebook down.","","","null","","",""],
["numas_drawing","_none","_none","it's a drawing of a snail and a hyena holding hands.","","","null","","",""],
["flowers_etc","_none","_none","the gifts that numa dropped.","","","null","","",""],
["room_placeholder","_none","_none","(placeholder) sorry, you can't go there","","","null","","",""],
["welcome_sign","_none","_none","\"welcome to purrgatory.\"","","","","","",""],
["","","","what a warm welcome.","","","null","","",""],
["lucifur_wuz_here","_none","_none","\"lucifur wuz here.\" ","","","null","","",""],
["library_sign","_none","_none","\"library.\"","","","null","","",""],
["bell_sign","_none","_none","looks like someone's taken a bite out of this sign.","","","null","","",""],
["antechamber_ttt","_none","_none","it's a draw.","","","null","","",""],
["antechamber_tally","_none","_none","someone counted to 21 here.","","","null","","",""],
["commons_lamp","_none","_none","it's a lamp.","","","","","",""],
["","","","enlightening!","","","null","","",""],
["commons_chair1","_none","_none","a chair.","","","null","","",""],
["commons_chair2","_none","_none","this chair has seen better days.","","","null","","",""],
["poetry_slam_sign","_none","_none","it says \"purrgatory poetry slam,\" probably.","","","null","","",""],
["hallway_pipe","_none","_none","a pipe.","","","","","",""],
["","_none","_none","maybe getting out of here is a pipe dream.","","","null","","",""],
["lockers","_none","_none","there's nothing in these lockers.","","","null","","",""],
["cat_picture","_none","_none","isn't this the cat from the other room?","","","null","","",""],
["hallway_tally1","_none","_none","11 tallies.","","","null","","",""],
["pencil","_none","_none","a pencil. the lead is broken.","","","null","","",""],
["spiderweb1","_none","_none","oh god is that a spiderweb","","","","","",""],
["","","","do spiders go to purrgatory??","","","null","","",""],
["clock","_none","_none","a clock with no hands.","","","null","","",""],
["trash_can","_none","_none","a trash can.","","","null","","",""],
["water_tap","_none","_none","a water cooler. it looks like it's full of orange soda.","","oliver_asked_for_soda",['water_tap2', 'null'],"","",""],
["water_tap2","","","no cups, though.","","","","","",""],
["","","","wonder where you could find one...?","","","null","","",""],
["piano","_none","_none","it's an electric piano.","","","null","","",""],
["piano_chair","_none","_none","yet another chair.","","","null","","",""],
["fake_door","_none","_none","this isn't a door, just a drawing of a door on the wall.","","","null","","",""],
["puddle","_none","_none","a puddle of something.","","","null","","",""],
["escalator","_none","_none","it's an escalator.","","","null","","",""],
["caution_sign","_none","_none","\"caution.\"","","","null","","",""],
["meowseum_ttt","_none","_none","X wins!","","","","","",""],
["","","","just kidding. it's a draw.","","","null","","",""],
["donations_jar","_none","_none","a jar for donations, repurposed from a fish bowl.","","","","","",""],
["","","","guess they're fishing for money!","","","","","",""],
["","","","mysteriously, there's a sock and a leaf inside.","","","null","","",""],
["exit_sign","_none","_none","unfortunately, this is probably an exit out of the meowseum, not purrgatory.","","","null","","",""],
["meowseum_lamp","_none","_none","a lamp.","","","null","","",""],
["tile","_none","_none","someone's pulled a tile off the floor. it's cement underneath.","","","null","","",""],
["spiderweb2","_none","_none","oh god more spiders","","","null","","",""],
["chair_picture","_none","_none","why would anyone frame a picture of a chair…?","","","null","","",""],
["down_button","_none","_none","this button opens the door.","","","null","","",""],
["elevator_panel","_none","_none","this elevator only seems to go to one floor.","","","null","","",""],
["elevator_button","_none","_none","you push the button for the first floor, but the elevator doesn't move.","","","","","",""],
["","","","guess you're already on that floor.","","","null","","",""],
["graveyard","_none","_none","a graveyard in the afterlife?","","","null","","",""],
["river","_none","_none","the river is full of milk. yuck.","","","null","","",""],
["garden_tree","_none","_none","despite being dead, this tree is bearing some sort of black fruit.","","","null","","",""],
["garden_bush","_none","_none","a dead bush.","","","","","",""],
["","","","no need to beat around it!","","","null","","",""],
["garden_sapling","_none","_none","a sapling.","","","null","","",""],
["garden_mural","_none","_none","someone's drawn a pretty mural on the walls.","","","null","","",""],
["catnip","_none","_none","is that… catnip?","","","null","","",""],
["garden_ttt","_none","_none","another draw.","","","null","","",""],
["garden_potted_plant","_none","_none","a potted plant.","","","null","","",""],
["garden_pot","_none","_none","a pot.","","","null","","",""],
["garden_boots","_none","_none","rain boots, for some reason.","","","null","","",""],
["garden_bricks","_none","_none","some bricks.","","","null","","",""],
["dried_flower","_none","_none","a sad looking flower.","","","null","","",""],
["well","_none","_none","well, well, well, what do we have here?","","","","","",""],
["","","","(it's a well.)","","","","","",""],
["","","","(also it's full of milk.)","","","null","","",""],
["garden_flowers","_none","_none","these flowers smell like fish. gross.","","","null","","",""],
["sock","_none","_none","a sock.","","","","","",""],
["","","","being in purrgatory really socks.","","","null","","",""],
["hallway_lightbulb","_none","_none","a lightbulb.","","","","","",""],
["","","","it's dead, of course.","","","null","","",""],
["cubby_pillow","_none","_none","the pillow is stuffed with leaves.","","","null","","",""],
["cubby_tally","_none","_none","lots and lots of tally marks.","","","null","","",""],
["cubby_blanket","_none","_none","looks like someone was sleeping here.","","","null","","",""],
["reception_sign","_none","_none","\"welcome.\"","","","null","","",""],
["filing_cabinet","_none","_none","it's a filing cabinet.","","","null","","",""],
["reception_plant","_none","_none","this potted plant looks like it's dead.","","","null","","",""],
["reception_desk","_none","_none","the receptionist's desk.","","","null","","",""],
["reception_paper","_none","_none","some paper or something.","","","null","","",""],
["reception_water","_none","_none","water. it's important to stay hydrated!","","","null","","",""],
["reception_computer","_none","_none","a really old computer.","","","null","","",""],
["reception_picture","_none","_none","a picture frame.","","","null","","",""],
["vent_leaf","_none","_none","a leaf.","","","","","",""],
["","","","why would anyone [i]leaf[/i] this lying around?","","","null","","",""],
["vent_stick","_none","_none","a stick.","","","null","","",""],
["","","","why would anyone [i]stick[/i] this in a vent?","","","","","",""],
["vent_leaves","_none","_none","more leaves.","","","null","","",""],
["ending_sign","_none","_none","(this is the end of the current build.)","","","","","",""],
["","","","(there are no more objectives to complete.)","","","","","",""],
["","","","(thank you for playing!)","","","null","","",""],
["default","_none","_none","(placeholder) you look at the thing.","","","null","","",""],
["house_cat","_none","_none","_pass","","house_cat_pushed_glass",['house_cat2', 'house_cat1'],"","",""],
["house_cat1","_none","_none","what's that cat doing here?","","","null","","",""],
["house_cat_2","_none","_none","bad cat!","","","null","","",""],
["house_glass","_none","_none","a glass.","","oliver_asked_for_soda",['house_glass2', 'null'],"","",""],
["house_glass2","","","you could use this to get oliver some orange soda!","house_cat_pushed_glass","","","","",""],
["","","","as you reach for the glass, the cat locks eyes with you.","house_natalie_heard_glass","","","","",""],
["","you","","don't you dare.","house_cat_pushing_glass","","null","","",""],
["house_glass_next","you","_none","dammit.","","","null","","",""],
["null","_none","_none","_pass","","","null","","",""],
["meowseum_door","_none","_none","_pass","","got_meowseum_passcode",['meowseum_door1', 'meowseum_door2'],"","",""],
["meowseum_door1","_none","_none","you unlock the padlock with the code.",[['unlocked_meowseum_door', true], ['_quest_meowseum_door', false], ['got_meowseum_passcode', true]],"","null","","",""],
["meowseum_door2","_none","_none","_pass","","tried_meowseum_door",['meowseum_door3', 'meowseum_door4'],"","",""],
["meowseum_door3","_none","_none","still locked.","","","","","",""],
["","","","looks like you need a four-digit code.","","","null","","",""],
["meowseum_door4","_none","_none","the meowseum is locked with a padlock.","tried_meowseum_door","","","","",""],
["","","","looks like you need a four-digit code.","_quest_meowseum_door","","null","","",""],
["passcode","_none","_none","it's a crumpled up poem. it says:","got_meowseum_passcode","","","","",""],
["","","","[i]purrgatory is a maze[/i]","","","","","",""],
["","","","[i]and sometimes a haze[/i]","","","","","",""],
["","","","[i]but at least[/i]","","","","","",""],
["","","","[i]there are no mondays[/i]","","","","","",""],
["","","","in the corner is the number \"1234.\"","","","null","","",""],
["battery1","_none","_none","it's a double-a battery! this'll come in handy.","_inv_battery1","","null","","",""],
["battery2","_none","_none","it's a double-a battery! what luck.","_inv_battery2","","null","","",""],
["out_of_batteries","_none","_none","it's out of batteries...","","","null","","",""],
["crumpled_papers","_none","_none","_pass","","elijah_went_to_sleep",['poems', 'crumpled_papers1'],"","",""],
["crumpled_papers1","_none","_none","that's a lot of paper.","","","null","","",""],
["antechamber_rubble","_none","_none","some rubble.","","","null","","",""],
["antechamber_ceiling","_none","_none","someone should fix this ceiling.","","","null","","",""],
["attic_galaxy","_none","_none","a drawing of a galaxy.","","","null","","",""],
["attic_dog","_none","_none","what a cute dog!","","","null","","",""],
["attic_rainbow","_none","_none","a rainbow.","","","null","","",""],
["attic_ufo","_none","_none","a ufo.","","","null","","",""],
["attic_dog2","_none","_none","that's a doggo.","","","null","","",""],
["attic_grandma","_none","_none","a drawing of an old lady.","","","null","","",""],
["attic_moth","_none","_none","that's a moth.","","","null","","",""],
["attic_candles","_none","_none","some candles.","","","null","","",""],
["attic_window","_none","_none","there's nothing behind this window, it's just mounted on the wall.","","","null","","",""],
["attic_footstool","_none","_none","footstool. for short people.","","","null","","",""],
["attic_nightstand","_none","_none","there's a lighter and some dust bunnies in the drawer.","","","null","","",""],
["attic_bed","_none","_none","a cozy bed.","","","null","","",""],
["attic_desk","_none","_none","there are some art supplies inside.","","","null","","",""],
["attic_crate","_none","_none","a wooden box.","","","","","",""],
["","","","isn't that [i]crate[/i]?","","","null","","",""],
["towels","_none","_none","some dirty towels.","","","null","","",""],
["closet_big_box","_none","_none","this box is full of spoons?","","","null","","",""],
["wipes","_none","_none","wipes.","","","null","","",""],
["closet_towels","_none","_none","some neatly stacked towels.","","","null","","",""],
["cleaner","_none","_none","cleaning fluid.","","","null","","",""],
["fertilizer_bag","_none","_none","a stinky, stinky bag of fertilizer.","","","null","","",""],
["closet_soap","_none","_none","soap.","","","null","","",""],
["closet_paper_towels","_none","_none","some paper towels.","","","null","","",""],
["closet_snowglobe","_none","_none","cool, a snowglobe!","","","null","","",""],
["closet_boxes","_none","_none","these boxes are empty.","","","null","","",""],
["closet_rope","_none","_none","rope.","","","null","","",""],
["electric_box_warning","_none","_none","it says \"DANGER: risk of death.\"","","","null","","",""],
["electric_box_note","_none","_none","a scribbled note that says \"risk of death? like, again?\"","","","null","","",""],
["electric_box","_none","_none","some sort of electric box?","","","null","","",""],
["closet_tile","_none","_none","a displaced ceiling tile.","","","null","","",""],
["closet_wires","_none","_none","you're no expert, but that really doesn't look safe.","","","null","","",""],
["closet_pipe","_none","_none","an exposed pipe.","","","","","",""],
["","","","maybe getting out of here is a pipe dream.","","","","","",""],
["","","","...did you make that joke already?","","","null","","",""],
["paper_towel_holder","_none","_none","paper towels.","","","null","","",""],
["cylinder","_none","_none","it's...","","","","","",""],
["","","","uh...","","","","","",""],
["","","","actually, you have no clue what this is.","","","null","","",""],
["closet_notes","_none","_none","some notes about supply deficiencies or something.","","","null","","",""],
["calendar","_none","_none","according to this calendar, it's meowvember the fourth.","","","null","","",""],
["commons_mat","_none","_none","a mat.","","","","","",""],
["","","","it proably doesn't [i]mat[/i]-ter for anything.","","","null","","",""],
["commons_poem","_none","_none","someone dropped some notes here.","","","","","",""],
["","","","the writing is illegible.","","","null","","",""],
["tack","_none","_none","a loose tack.","","","","","",""],
["","","","that's just tacky!","","","null","","",""],
["dropoff_fence","_none","_none","this fence doesn't look very sturdy...","","","null","","",""],
["dropoff_pit","_none","_none","no sign of the bottom.","","","null","","",""],
["elevator_railing","_none","_none","it's just a railing.","","","null","","",""],
["emergency_lights","_none","_none","some emergency lights, maybe?","","","null","","",""],
["exit_door","_none","_none","it won't open, and there's no keyhole.","","","null","","",""],
["exit_painting","_none","_none","it's that freaking cat again!","","","null","","",""],
["field_tree","_none","_none","a dead tree.","","","null","","",""],
["field_rocks","_none","_none","a rock.","","","null","","",""],
["field_river","_none","_none","the river is full of milk. yuck.","","","null","","",""],
["weeds","_none","_none","weeds, or flowers. it's hard to tell.","","","null","","",""],
["wheelbarrow","_none","_none","a wheelbarrow full of a weeds.","","","","","",""],
["","","","a weedbarrow!","","","null","","",""],
["field_grave1","_none","_none","\"he was a proud father of 16 cats.\"","","","null","","",""],
["field_grave2","_none","_none","\"she died like she lived: unremarkably.\"","","","null","","",""],
["field_grave3","_none","_none","\"good riddance.\"","","","null","","",""],
["field_grave4","_none","_none","\"she died like she lived: fighting crocodiles.\"","","","null","","",""],
["field_grave5","_none","_none","this one just says \"brb.\"","","","null","","",""],
["field_grave6","_none","_none","\"they were a good parent but a bad tighrope walker\"","","","null","","",""],
["field_flowers","_none","_none","aw, someone left them some flowers!","","","null","","",""],
["field_fence","_none","_none","a fence.","","","","","",""],
["","","","no of-[i]fence[/i] taken!","","","null","","",""],
["field_shack","_none","_none","a broken down shack.","","","null","","",""],
["bad_tree","_none","_none","is it just you, or is that tree more poorly drawn than the others?","","","null","","",""],
["field_tiny_tree","_none","_none","it's a tiny little tree!","","","null","","",""],
["field_distant_cemetery","_none","_none","there's a cemetery over there.","","","","","",""],
["","","","wait","","","","","",""],
["","","","why is there a cemetery??","","","null","","",""],
["field_distant_doorway","_none","_none","a doorway in the distance.","","","null","","",""],
["field_bench","_none","_none","a bench.","","","null","","",""],
["field_sign","_none","_none","it says \"please stay off the grass! - purrgatory paw-rks and re-claw-ation.\"","","","","","",""],
["","","","ok, that one's a bit of a stretch.","","","null","","",""],
["field_bush","_none","_none","a dead bush.","","","null","","",""],
["horseshoe","_none","_none","looks like someone was playing horseshoe.","","","null","","",""],
["field_path","_none","_none","a nice scenic path.","","","null","","",""],
["hill","_none","_none","a big hill.","","","","","",""],
["","","","that's a [i]hill[/i] of a climb!","","","null","","",""],
["field_grate","_none","_none","this is where the milk is coming from.","","","null","","",""],
["garden_sidewalk_end","_none","_none","a sidewalk sort of ends here.","","","","","",""],
["","","","guess it got [i]side[/i]-tracked!","","","null","","",""],
["garden_liquid","_none","_none","you don't even want to know what that liquid is.","","","null","","",""],
["garden_mallet","_none","_none","a mallet.","","","null","","",""],
["garden_spade","_none","_none","a spade.","","","","","",""],
["","","","looks like purrgatory has gardening supplies in [i]spades[/i]!","","","null","","",""],
["garden_paint","_none","_none","a can of white paint.","","","null","","",""],
["garden_pencil","_none","_none","a pencil.","","","null","","",""],
["garden_cube","_none","_none","a mysterious tiny cube.","","","null","","",""],
["garden_rock","_none","_none","a rock.","","","null","","",""],
["garden_pebble","_none","_none","a pebble.","","","null","","",""],
["garden_sidewalk","_none","_none","the sidewalk.","","","null","","",""],
["garden_ceiling","_none","_none","some sort of advanced watering and lighting system.","","","null","","",""],
["garden_compost","_none","_none","some compost.","","","null","","",""],
["garden_wires","_none","_none","wires.","","","","","",""],
["","","","[i]wire[/i] you even looking at these?","","","null","","",""],
["garden_leaves","_none","_none","some cronchy looking leaves.","","","null","","",""],
["garden_flower","_none","_none","a flower.","","","null","","",""],
["garden_hoe","_none","_none","a hoe.","","","null","","",""],
["hallway_puddle","_none","_none","the pipe's leaking a little.","","","null","","",""],
["hallway_rocks","_none","_none","rocks.","","","null","","",""],
["hallway_stalagtites","_none","_none","stalactites, not stalagmites.","","","","","",""],
["","","","remember, c is for ceiling, g is for ground!","","","null","","",""],
["cave_sign","_none","_none","it says \"watch your paws!\"","","","null","","",""],
["cave_path","_none","_none","who designed this path??","","","null","","",""],
["cave_stuff","_none","_none","cave stuff.","","","null","","",""],
["more_cave_stuff","_none","_none","more cave stuff.","","","null","","",""],
["elijahs_chair","_none","_none","chair.","","","null","","",""],
["elijahs_bookshelf","_none","_none","a mostly empty bookshelf.","","","null","","",""],
["elijahs_desk","_none","_none","a desk, also covered in papers.","","","null","","",""],
["odontophorous","_none","_none","odonto-what now?","","","null","","",""],
["spiderweb2","_none","_none","MORE SPIDERS","","","null","","",""],
["meowseum_lamp","_none","_none","cool lamps.","","","null","","",""],
["meowseum_poster","_none","_none","it's advertising something called "discover the cat."","","","null","","",""],
["meowseum_bench","_none","_none","a bench.","","","null","","",""],
["tile","_none","_none","someone actually dug up a floor tile here.","","","","","",""],
["","","","you're [i]floored[/i]!","","","null","","",""],
["meowseum_sign","_none","_none","\"the cat meowseum\"?","","","null","","",""],
["hours_sign","_none","_none","according to this sign, the meowseum is open every day except... mewsday.","","","null","","",""],
["rock_tower","_none","_none","some sort of rock tower thing?","","","null","","",""],
["catwalk","_none","_none","it's a [i]cat[/i]-walk!","","","","","",""],
["","","","also this looks VERY unsafe.","","","null","","",""],
["house_cacti","_none","_none","some sort of cactus or something.","","","null","","",""],
["house_welcome","_none","_none","welcome.","","","null","","",""],
["warehouse_button","_none","_none","you guess this opens the door.","","","null","","",""],
["house_lamp","_none","_none","a stylish lamp.","","","null","","",""],
["house_couch","_none","_none","a sofa.","","","","","",""],
["","","","this is the comfiest seat in purrgatory you've seen [i]sofa[/i]-r!","","","null","","",""],
["house_carpet1","_none","_none","a carpet.","","","null","","",""],
["house_window","_none","_none","it's just bricks behind this window.","","","null","","",""],
["house_bowl","_none","_none","just a bowl.","","","null","","",""],
["house_books","_none","_none","some books filled with meows.","","","","","",""],
["","","","does oliver know these are here?","","","null","","",""],
["house_cylinder","_none","_none","some sort of... cylinder?","","","null","","",""],
["flower_picture","_none","_none","a nice picture of a flower.","","","null","","",""],
["house_soap","_none","_none","a bar of soap.","","","null","","",""],
["house_rag","_none","_none","a rag.","","","null","","",""],
["house_vase","_none","_none","what a fancy vase!","","","null","","",""],
["house_carpet2","_none","_none","another carpet.","","","null","","",""],
["house_stool","_none","_none","a stool.","","","null","","",""],
["broken_glasses","_none","_none","looks like someone was pushing glasses off of this counter.","","","null","","",""],
["conveyer_belt","_none","_none","some sort of glass delivering machine?","","","null","","",""],
["house_bin","_none","_none","this chute goes down forever.","","","null","","",""],
["toaster","_none","_none","a toaster.","","","null","","",""],
["house_mat","_none","_none","some sort of mat.","","","null","","",""],
["house_sink","_none","_none","a sink!","","","","","",""],
["","","","...","","","","","",""],
["","","","yep, it dispenses milk.","","","null","","",""],
["house_cabinets","_none","_none","you can't open these because there are no handles.","","","null","","",""],
["house_potted_plant","_none","_none","cool plant.","","","null","","",""],
["stained_glass","_none","_none","a stained glass window.","","","null","","",""],
["house_upstairs_carpet","_none","_none","a carpet.","","","null","","",""],
["house_pillows","_none","_none","someone REALLY went to town on these pillows.","","","null","","",""],
["live_laugh_meow","_none","_none","live laugh meow.","","","null","","",""],
["cat_bed","_none","_none","instead of a mattress, this bed just has a cat bed on top of it.","","","null","","",""],
["bedroom_lamp","_none","_none","a little lamp.","","","null","","",""],
["bedroom_table","_none","_none","a stylish table.","","","null","","",""],
["bedroom_rug","_none","_none","it's a carpet.","","","","","",""],
["","","","or is it a rug?","","","null","","",""],
["library_windows","_none","_none","some big old windows.","","","null","","",""],
["library_pencil","_none","_none","a pencil.","","","null","","",""],
["library_magnifying_glass","_none","_none","a magnifying glass.","","","null","","",""],
["library_work_papers","_none","_none","some papers covered with notes.","","","null","","",""],
["library_work_books","_none","_none","these are all full of meows too.","","","null","","",""],
["library_ceiling_lamps","_none","_none","these tiny orbs are lamps.","","","","","",""],
["","","","[i]orb[/i] are they?!","","","null","","",""],
["library_infinity","_none","_none","an infinity sign.","","","","","",""],
["","","","well, that's a little on the nose.","","","null","","",""],
["david","_none","_none","that's michelangelo's david!","","","","","",""],
["","","","something looks a little bit off...","","","null","","",""],
["library_lamp","_none","_none","a lamp.","","","null","","",""],
["standing_cat","_none","_none","it's a cat standing on its hind legs.","","","null","","",""],
["lucifur_paintings","_none","_none","how many pictures of this cat are there??","","","null","","",""],
["donations_text","_none","_none","it says \"donations. your contributions are greatly appreciate! - meowseum meow-nagement\"","","","null","","",""],
["lobby_bench","_none","_none","a bench.","","","null","","",""],
["lobby_infinity","_none","_none","infinity.","","","null","","",""],
["standing_cat_sign","_none","_none","this sign says \"felis erectus, the ancestor of the modern human.\" ","","","","","",""],
["","","","that... doesn't seem right?","","","null","","",""],
["cat_with_pearl_earring","_none","_none","hey, this is the painting from the poster!","","","null","","",""],
["cat_with_pearl_earring_sign","_none","_none","\"johannes furmeer. [i]cat with a pearl earing,[/i] c. 1665. oil on canvas.\"","","","null","","",""],
["meowseum_tallies","_none","_none","7 tallies.","","","null","","",""],
["yarn","_none","_none","it's just a ball of yarn.","","","null","","",""],
["yarn_sign","_none","_none","\"anonymous. [i]yarn,[/i] date unknown. yarn.\"","","","null","","",""],
["discover_the_cat","_none","_none","\"discover the cat.\"","","","","","",""],
["","","","\"an exhibit all about our claw-some feline fur-riends!\"","","","","","",""],
["","","","this sign is basically just cat puns.","","","null","","",""],
["cat_gogh","_none","_none","a portrait of a cat.","","","null","","",""],
["apple_cat","_none","_none","a cat with an apple in front of its head.","","","null","","",""],
["the_screm","_none","_none","isn't the cat supposed to be screaming or something?","","","null","","",""],
["screm_sign","_none","_none","\"edvard meownch. [i]the meow,[/i] 1893. oil, tempera, and pastel on cardboard.\"","","","null","","",""],
["missing_painting","_none","_none","who took this painting?","","","null","","",""],
["missing_painting_sign","_none","_none","not much is left of this label.","","","null","","",""],
["starry_night","_none","_none","hey, isn't that just starry night?","","","null","","",""],
["starry_night_sign","_none","_none"," ","","","null","","",""],
["battle_of_cattysburg","_none","_none","a bunch of cats at war.","","","null","","",""],
["cattysburg_sign","_none","_none","\"charles pawsper kitten. [i]battle of cattysburg,[/i] c. 1900. oil on canvas.\"","","","null","","",""],
["sphinx","_none","_none","a hairless cat.","","","null","","",""],
["sphinx_sign","_none","_none","\"sphinx. selectively bred to have no fur, these cats also have long, narrow heads and webbed paws. don't be fooled by its appearance, this breed is known to be energetic and affectionate!\"","","","null","","",""],
["cats_come_in","_none","_none","\"cats come in all shapes and sizes.\"","","","","","",""],
["","","","...the rest of this sign is just scribbles?","","","null","","",""],
["cat_inventor","_none","_none","it's a picture of some dude with a cat.","","","null","","",""],
["cat_inventor_sign","_none","_none","\"the only surviving photograph of john cat, the inventor of cats.\"","","","null","","",""],
["statue_lights","_none","_none","some lights.","","","null","","",""],
["maine_coon","_none","_none","a fluffy cat.","","","null","","",""],
["maine_coon_sign","_none","_none","\"maine coon. adapted for survival in winter climates, these gentle giants are known for their intelligence and playfulness. cat fact: maine coons are the largest breed of domesticated cat!\"","","","null","","",""],
["schrodingers","_none","_none","a box that says \"do not open.\"","","","","","",""],
["","","","open it?","","","","",['yes', 'no'],['schrodingers1', 'null']],
["schrodingers1","","","there's... nothing inside.","","","null","","",""],
["schrodingers_sign","_none","_none","\"schrodinger's cat. first discovered by cat breeder erwin schrodinger in 1935, these quantum kitties are best known for entering states of quantum superposition. dead or alive, these mysterious cats are the perfect low-maintenance buddy!\"","","","null","","",""],
["airplane","_none","_none","a paper airplane.","","","null","","",""],
["abstract_cat","_none","_none","this one's just a sphere??","","","null","","",""],
["abstract_cat_sign","_none","_none","\"abstract cat. popular among physicists for its uniform curvature, this breed's natural habitat is a frictionless vacuum. watch out, these spherical felines are as playful as they are homogenous!\"","","","null","","",""],
["scaly_cat","_none","_none","that's a lizard.","","","null","","",""],
["scaly_cat_sign","_none","_none","\"scaly cat. known for its long, forked tongue and tapered tail, this wacky cat has armored scales instead of fur. If you can get past its rough exterior, this breed can be a loyal and loving friend!\"","","","null","","",""],
["3d_cat","_none","_none","it's... it's beautiful.","","","null","","",""],
["3d_cat_sign","_none","_none","it just says "CAT" in all caps.","","","null","","",""],
["3d_cat_lights","_none","_none","bright lights.","","","null","","",""],
["cat_butt","_none","_none","clearly this painting was too beautiful to display.","","","null","","",""],
["filing_boxes","_none","_none","some filing boxes or something.","","","null","","",""],
["meowseum_pencil","_none","_none","it's a popsicle stick.","","","null","","",""],
["meowseum_snowglobe","_none","_none","cool, a snowglobe!","","","null","","",""],
["meowseum_cards","_none","_none","some flash cards.","","","null","","",""],
["this_side_right","_none","_none","it says \"this side right.\"","","","null","","",""],
["litter_box","_none","_none","whatever's in this box smells really gross.","","","null","","",""],
["spilled_litter","_none","_none","this box is full of... dirt?","","","","","",""],
["","","","...","","","","","",""],
["","","","oh, it's cat litter.","","","null","","",""],
["flat_box","_none","_none","a flat box.","","","","","",""],
["","","","it's not very [i]flat[/i]-tering.","","","null","","",""],
["mop_bucket","_none","_none","a mop bucket.","","","null","","",""],
["mop_bucket","_none","_none","a mop.","","","null","","",""],
["mop_water","_none","_none","mop water.","","","null","","",""],
["padlock","_none","_none","a padlock.","","","","","",""],
["","","","for once, it's already open!","","","null","","",""],
["pipe2","_none","_none","more pipe.","","","null","","",""],
["hallway_crack","_none","_none","a crack.","","","","","",""],
["","","","guess the afterlife's not all it's [i]cracked[/i] out to be.","","","null","","",""],
["hallway_scribble","_none","_none","just a scribble.","","","null","","",""],
["trash_can_paper","_none","_none","someone threw a poem into this trash can.","","","","","",""],
["","","","[i]orange soda[/i]","","","","","",""],
["","","","[i]lukewarm and runny[/i]","","","","","",""],
["","","","[i]whenever i drink it[/i]","","","","","",""],
["","","","[i]it upsets my tummy[/i]","","","null","","",""],
["chairon","_none","_none","the receptionist's chair.","","","null","","",""],
["reception_keyoard","_none","_none","a keyboard.","","","null","","",""],
["reception_mouse","_none","_none","a mouse.","","","null","","",""],
["study_lamp","_none","_none","oliver's desk lamp.","","","null","","",""],
["study_board","_none","_none","a board covered in notes and stuff.","","","null","","",""],
["study_books","_none","_none","some books that oliver was cataloging, maybe?","","","null","","",""],
["study_papers","_none","_none","this handwriting is completely illegible!","","","null","","",""],
["study_floor_papers","_none","_none","some papers on the floor.","","","null","","",""],
["study_bed","_none","_none","looks like oliver sleeps here too.","","","null","","",""],
["study_chair","_none","_none","a comfy looking desk chair.","","","null","","",""],
["train_display","_none","_none","looks like some sort of train schedule.","","","null","","",""],
["","_none","_none","under \"departures\" it says \"heaven: delayed.\"","","","null","","",""],
["","_none","_none","under \"arrivals\" it says...","","","null","","",""],
["","_none","_none","hey, that's your name!","","","null","","",""],
["train_bench","_none","_none","an uncomfortable looking bench.","","","null","","",""],
["vending_machine","_none","_none","a vending machine.","","","null","","",""],
["train_exits","_none","_none","unfortunately, this tunnel ends in like ten feet.","","","null","","",""],
["train_tracks","_none","_none","train tracks that don't go anywhere.","","","null","","",""],
["train_columns","_none","_none","a column. holds up the ceiling.","","","null","","",""],
["crowbar","_none","_none","a crowbar.","","","null","","",""],
["warehouse_wood","_none","_none","just a plank or something.","","","null","","",""],
["containers","_none","_none","lots of big containers.","","","null","","",""],
["cat_food","_none","_none","yep, that's cat food.","","","null","","",""],
["warehouse_button2","_none","_none","opens the door.","","","null","","",""],
["cat_toy","_none","_none","is that a cat toy up there?","","","null","","",""],
["warehouse_cube","_none","_none","some sort of... cube.","","","null","","",""],
["warehouse_notice","_none","_none","it says \"notice: only paw-thorized workers are allowed in the warehouse!\"","","","null","","",""],
["warehouse_electrical_box","_none","_none","an electrical box.","","","null","","",""],
["warehouse_pallet","_none","_none","a pallet.","","","null","","",""],
["warehouse_cardboard","_none","_none","some cardboard boxes.","","","null","","",""],
["spiral_staircase","_none","_none","a spiral staircase.","","","null","","",""],
["warehouse_skylight","_none","_none","there's nothing behind this skylight, just ceiling.","","","null","","",""],
["small_containers","_none","_none","aww, it's little mini versions of the big containers!","","","null","","",""]
]