extends Node

var raw_blocks = [
["screwdriver","_none","_none","you take the screwdriver.","_inv_screwdriver","","null","",""],
["vent","","","_pass","","numa_crying and not numa_quest_complete",['numa_cry', 'ventc'],"",""],
["ventc","","","_pass","","numa_snooped",['vent_locked', 'ventc2'],"",""],
["ventc2","","","_pass","","_inv_screwdriver",['vent_open', 'vent_closed'],"",""],
["vent_closed","","","the vent is secured by several screws. if you had a screwdriver, you could probably open it.","","","null","",""],
["vent_open","","","you use the screwdriver to loosen the cover.","opened_vent","","null","",""],
["vent_locked","","","you can't get in because numa took the screwdriver.","","","null","",""],
["numas_notebook","_none","_none","it says \"numa's diary\" on the front","","","","",""],
["","","","read it?","","","","",[['yes', 'notebook_read'], ['no', 'notebook_end']]],
["notebook_read","","","you open to a random page in the notebook.","","","","",""],
["","notebook","","day 458:\nthe deathberries are going to ripen soon. i cant wait. (sarcasm.)","","","","",""],
["","","","i started pruning the thorns off the roses. i don't have anything else to do. maybe it'll save someone from a prick some day.","","","","",""],
["","","","i wish kyungsoon was here. she would probably think the deathberries are ugly though. (they are pretty ugly.)","","","","",""],
["","","","but everything is ugly in comparison to kyungsoon.","","","","",""],
["notebook_end","_none","","you put the notebook down.","","","null","",""],
["numas_drawing","_none","_none","it's a drawing of a snail and a hyena holding hands.","","","null","",""],
["flowers_etc","_none","_none","the gifts that numa dropped.","","","null","",""],
["room_placeholder","_none","_none","there's nothing there, as if the room hasn't been made yet.","","","null","",""],
["welcome_sign","_none","_none","\"welcome to purrgatory.\"","","","","",""],
["","","","what a warm welcome.","","","null","",""],
["lucifur_wuz_here","_none","_none","\"lucifur wuz here.\" ","","","","",""],
["","","","who's lucifur?","","","null","",""],
["library_sign","_none","_none","\"library.\"","","","null","",""],
["bell_sign","_none","_none","looks like someone's taken a bite out of this sign.","","","null","",""],
["antechamber_ttt","_none","_none","it's a draw.","","","null","",""],
["antechamber_tally","_none","_none","someone counted to 21 before giving up.","","","null","",""],
["commons_lamp","_none","_none","it's a lamp.","","","","",""],
["","","","enlightening!","","","null","",""],
["commons_chair1","_none","_none","a chair.","","","null","",""],
["commons_chair2","_none","_none","this chair has seen better days.","","","null","",""],
["poetry_slam_sign","_none","_none","it says \"purrgatory poetry slam,\" probably.","","","null","",""],
["pipe","_none","_none","a pipe.","","","","",""],
["","_none","_none","maybe getting out of here is a pipe dream.","","","null","",""],
["lockers","_none","_none","there's nothing in these lockers.","","","null","",""],
["cat_picture","_none","_none","isn't this the cat from the other room?","","","null","",""],
["hallway_tally1","_none","_none","11 tallies.","","","null","",""],
["pencil","_none","_none","a pencil. the lead is broken.","","","null","",""],
["spiderweb1","_none","_none","a spiderweb. why are there spiders in purrgatory??","","","null","",""],
["clock","_none","_none","a clock with no hands.","","","null","",""],
["trash_can","_none","_none","a trash can.","","","null","",""],
["water_tap","_none","_none","a water cooler. it looks like it's full of orange soda.","","","null","",""],
["piano","_none","_none","the piano doesn't seem to be working.","","","null","",""],
["piano_chair","_none","_none","yet another chair.","","","null","",""],
["bowling_pin","_none","_none","a solitary bowling pin.","","","null","",""],
["fake_door","_none","_none","this isn't a door, just a drawing of a door on the wall.","","","null","",""],
["puddle","_none","_none","a puddle of something.","","","null","",""],
["escalator","_none","_none","this escalator just seems to wrap back around to the bottom.","","","null","",""],
["empty_sign","_none","_none","there's nothing even written on this sign.","","","null","",""],
["meowseum_ttt","_none","_none","how did they even get over there??","","","null","",""],
["donations","_none","_none","a jar for donations, but it looks like it's a fish bowl.","","","","",""],
["","_none","_none","guess they're fishing for money.","","","null","",""],
["meowseum_sign","_none","_none","\"cat meowseum\"…?","","","null","",""],
["exit_sign","_none","_none","unfortunately, this is the exit to the museum, not to purrgatory.","","","null","",""],
["meowseum_lamp","_none","_none","a lamp.","","","null","",""],
["tile","_none","_none","someone's pulled a tile off the floor. it's cement underneath.","","","null","",""],
["spiderweb2","_none","_none","oh god more spiders","","","null","",""],
["pole","_none","_none","there's nothing at the top of the pole.","","","","",""],
["","_none","_none","this is either a stripper pole or a really ineffective fireman's pole.","","","null","",""],
["club_chair","_none","_none","chairs.","","","null","",""],
["chair_picture","_none","_none","why would anyone frame a picture of a chair…?","","","null","",""],
["down_button","_none","_none","this button opens the door.","","","null","",""],
["elevator_panel","_none","_none","this elevator only seems to go to one floor.","","","null","",""],
["elevator_button","_none","_none","you push the button for the first floor, but the elevator doesn't move.","","","","",""],
["","_none","_none","guess you're already on that floor.","","","null","",""],
["graveyard","_none","_none","a graveyard in the afterlife?","","","null","",""],
["river","_none","_none","the river is full of milk. yuck.","","","null","",""],
["tree1","_none","_none","despite being dead, this tree is bearing some sort of black fruit.","","","null","",""],
["tree2","_none","_none","a dead tree.","","","null","",""],
["bush","_none","_none","a dead bush.","","","","",""],
["","_none","_none","no need to beat around it!","","","null","",""],
["vine","_none","_none","some sort of vine.","","","null","",""],
["weather_drawings","_none","_none","someone's drawn a sun and a cloud on the walls.","","","null","",""],
["catnip","_none","_none","is that… catnip?","","","null","",""],
["garden_ttt","_none","_none","another draw.","","","null","",""],
["potted_plant","_none","_none","a potted plant.","","","null","",""],
["pot","_none","_none","a pot.","","","null","",""],
["boots","_none","_none","rain boots, for some reason.","","","null","",""],
["bricks","_none","_none","some bricks.","","","null","",""],
["supplies","_none","_none","gardening supplies.","","","null","",""],
["dried_flower","_none","_none","a sad looking flower.","","","null","",""],
["well","_none","_none","a well with a working winch.","","","","",""],
["","_none","_none","it looks like it's full of milk.","","","null","",""],
["flower","_none","_none","these flowers smell horrible.","","","null","",""],
["rectangle","_none","_none","it's some sort of rectangle, i don't know.","","","null","",""],
["watering_can","_none","_none","a watering can.","","","","",""],
["","_none","_none","technically, it's a milk-ing can.","","","null","",""],
["sock","_none","_none","a sock.","","","","",""],
["","_none","_none","being in purrgatory really socks.","","","null","",""],
["lightbulb","_none","_none","a dead lightbulb.","","","null","",""],
["pillow","_none","_none","the pillow is stuffed with leaves.","","","null","",""],
["cubby_tally","_none","_none","lots and lots of tally marks.","","","null","",""],
["blanket","_none","_none","looks like someone was sleeping here.","","","null","",""],
["reception_sign","_none","_none","\"welcome.\"","","","null","",""],
["filing_cabinet","_none","_none","it's a filing cabinet.","","","null","",""],
["reception_plant","_none","_none","this potted plant looks like it's dead.","","","null","",""],
["reception_desk","_none","_none","the receptionist's desk.","","","null","",""],
["reception_books","_none","_none","some books or something.","","","null","",""],
["reception_water","_none","_none","water. it's important to stay hydrated!","","","null","",""],
["reception_computer","_none","_none","a really old computer.","","","null","",""],
["reception_picture","_none","_none","a picture frame.","","","null","",""],
["leaf","_none","_none","a leaf.","","","","",""],
["","_none","_none","why would anyone leaf this lying around?","","","null","",""],
["stick","_none","_none","a stick.","","","null","",""],
["leaves","_none","_none","more leaves.","","","null","",""]
]