extends Node

var raw_blocks = [
["natalie_glass","natalie","natalie_neutral","{player}?","","","","","",""],
["","","","what was that noise?","","","","","",""],
["","you","","natalie!","","","","","",""],
["","","","it's nothing, just broke a glass","","","","","",""],
["","","","well","","","","","",""],
["","","","watched the cat break a glass","","","","","",""],
["","cat","","meow :3","","","","","",""],
["","natalie","","oh, phew. i was worried someone got hurt","","","","","",""],
["","you","","do you know where i can find another glass?","","","","","",""],
["","","","i'm trying to get oliver a drink","","","","","",""],
["","natalie","","hmmm... dunno.","","","","","",""],
["","","","as far as i know, that was the last cup in purrgatory","","","","","",""],
["","you","","ugh","","","","","",""],
["","natalie","","but who knows? maybe you'll find a [i]cup[/i]-le lying around.","","","","","",""],
["","you","","heh","","","","","",""],
["","","","you [i]mug[/i] be kidding me","","","","","",""],
["","natalie","","hones-[i]tea[/i] is the best policy","","","","","",""],
["","you","","okay, i'd better go tell oliver he's not getting his orange soda",[['_quest_oliver_soda1', false], ['_quest_oliver_soda2', true]],"","","","",""],
["","natalie","","okay, see ya!","","","","","",""],
["","","","i'll be in the attic if u want to chat","","","","","",""],
["","you","","kk","","","null","","",""],
["natalie_wasup1","natalie","","do you think all dogs go to heaven?","","","","","",""],
["","","","","","","","",['yes', 'no'],['natalie_wasup1a', 'natalie_wasup1b']],
["natalie_wasup1a","you","","yeah","","","natalie_wasup1c","","",""],
["natalie_wasup1b","you","","not all of them","","","","","",""],
["natalie_wasup1c","natalie","","what about my pug, jimmy?","","","","","",""],
["","you","","um","","","","","",""],
["","","","was he well behaved?","","","","","",""],
["","natalie","","well, he pooped on all of our couches at least once.","","","","","",""],
["","you","","hmm...","","","","","",""],
["","","","hard to say.","","","","","",""],
["","natalie","","maybe he's in dog purgatory.","","","","","",""],
["","you","","maybe so.","","","","","",""],
["","","","wait","","","","","",""],
["","","","PUGATORY","","","","","",""],
["","natalie","","PUGATORY!!!","","","null","","",""]
]