extends Node

var raw_blocks = [
["natalie_glass","natalie","natalie_neutral","{player}?","","","","","",""],
["","","","what was that noise?","","","","","",""],
["","you","","it's nothing, just broke a glass!","","","","","",""],
["","natalie","","oh, phew","","","","","",""],
["","","","i was worried someone got hurt","","","","","",""],
["","you","","nah, i'm fine","","","","","",""],
["","","","do you know where i can find another glass, though?","","","","","",""],
["","natalie","","uhhhh... dunno","","","","","",""],
["","","","as far as i know, that was the last cup in purrgatory","","","","","",""],
["","you","","dang","","","","","",""],
["","natalie","","but who knows? maybe you'll find a [i]cup[/i]-le lying around.","","","","","",""],
["","you","","you [i]mug[/i] be kidding me","","","","","",""],
["","natalie","","hones-[i]tea[/i] is the best policy","","","","","",""],
["","you","","okay, i'd better go tell oliver he's not getting his orange soda",[['_quest_oliver_soda1', false], ['_quest_oliver_soda2', true]],"","","","",""],
["","natalie","","okay, see ya!","","","","","",""],
["","","","i'll be in the attic if u want to hang out","","","","","",""],
["","you","","kk","","","null","","",""],
["natalie_intro","???","","zzz...","met_natalie","","","","",""],
["","you","","hello?","","","","","",""],
["","???","","fwha?","natalie_awake_in_attic","blackout",['natalie_intro_a', 'natalie_intro_b'],"","",""],
["natalie_intro_a","","natalie_neutral","oh hey","_hide_natalie_sleeping","","","","",""],
["","","","who are you?","","","natalie_intro_c","","",""],
["natalie_intro_b","","natalie_neutral","oh, hey","_hide_natalie_sleeping","","","","",""],
["","","","who are you?","","","","","",""],
["natalie_intro_c","you","","i'm new here!","","","","","",""],
["","natalie","","hi new here, i'm natalie","","","","","",""],
["","","","","","","","",['nice one', 'boooooo'],['natalie_intro1', 'natalie_intro2']],
["natalie_intro1","you","","nice one","","","","","",""],
["","natalie","","thanks, i'll be here all eternity","","","natalie_intro3","","",""],
["natalie_intro2","you","","boooooooooooooooooooooo","","","","","",""],
["","natalie","","come on, that's a classic!","","","","","",""],
["natalie_intro3","","","but really, what's your name?","","","","","",""],
["","you","","it's {player}!","","","","","",""],
["","natalie","","cool, nice to meet you","","rang_doorbell",['natalie_intro_doorbell', 'natalie_intro_continue'],"","",""],
["natalie_intro_doorbell","you","","uh, i'm guessing you don't remember the","","","","","",""],
["","","","cookies thing?","","","","","",""],
["","natalie","","what cookies thing?","","","","","",""],
["","you","","earlier i rang the doorbell and you showed up and said you didn't want any cookies and then left??","","","","","",""],
["","natalie","","i did???","","","","","",""],
["","","","oh my god i must have been sleepwalking, i'm sorry","","","","","",""],
["","","","i was JUST having a great dream about cookies","","","","","",""],
["","you","","haha it's okay","","","","","",""],
["","","","it was funny","","","","","",""],
["","natalie","","still, sheesh","","","","","",""],
["","","","what a way to make a first impression","","","","","",""],
["","you","","it's all good, really","","","","","",""],
["natalie_intro_continue","you","","so, how long have you been here?","","","","","",""],
["","natalie","","oh, it's been a while","","","","","",""],
["","","","i still have the books i checked out from oliver when i arrived... they're probably overdue by years","","","","","",""],
["","you","","oh yeah, he convinced me to borrow a book too!","","","","","",""],
["","natalie","","you too??","","","","","",""],
["","","","lol that boy never changes","","","","","",""],
["","","","i really should return those books, come to think of it","","","","","",""],
["","you","","do you want me to take them for you?","","","","","",""],
["","","","i'm probably heading down there anyway","","","","","",""],
["","natalie","","oh heck that would be awesome, thanks","","","","","",""],
["","","","i'm glad i'm not a-[i]loan[/i] in this endeavor","","","","","",""],
["","you","","haha","","","","","",""],
["","","","dw i'll make sure to [i]book[/i] it to the library","","","","","",""],
["","natalie","","i'm sure oliver will be e-[i]late[/i]-ed to have them back","","","","","",""],
["","you","","i heard the library's good for [i]circulation[/i]","","","","","",""],
["","natalie","","oh, i think they [i]cover[/i]-ed that in the newspaper","","","","","",""],
["","you","","newspaper? more like... news-[i]paper[/i]","","","","","",""],
["","","","...","","","","","",""],
["","","","okay that one sucked","","","","","",""],
["","natalie","","heh, they can't all be winners","","","","","",""],
["","","","here are the books, anyway",[['_inv_natalies_books', true], ['_quest_return_books', true]],"","","","",""],
["","","","tell oliver i thought they were good!","","","","","",""],
["","you","","weren't you using them to hold up a table?","","","","","",""],
["","natalie","","wellllll maybe","","blackout",['natalie_intro4', 'natalie_intro5'],"","",""],
["natalie_intro4","natalie","","but he doesn't need to know that!","","","","","",""],
["","you","","oh, by the way, can i borrow one of your candles?","","","","","",""],
["","natalie","","sure, what for?","","","","","",""],
["","you","","um, tori and i are trying to fix the lights","","","","","",""],
["","","","but it's too dark to see the wires in the electrical box","","","","","",""],
["","natalie","","ohhh, gotcha","","","","","",""],
["","","","well, no rush!","","","","","",""],
["","","","the ambience is way better this way anyway","","","","","",""],
["","you","","okay, and thanks!",[['_delay__inv_candle', true], ['_delay_saw_natalie_intro', true]],"","null","","",""],
["natalie_intro5","natalie","","but he doesn't need to know that!","_delay_saw_natalie_intro","","null","","",""],
["natalie_default","natalie","natalie_neutral","hey, what's up?","","","","","",""],
["","","","","","","",['true', 'saw_natalie_intro and not returned_natalies_books', 'returned_natalies_books and not followed_up_on_natalies_books', '_inv_draw_a_paw', 'elijah_planning_slam and not invited_natalie', 'returned_draw_a_paw', 'true', 'true'],["what's up?", "about the books...", "about the books...", "(return the draw-a-paw)", '(invite natalie to the everything slam)', "how's the drawing?", "thoughts about life?", "i like your attic"],["natalie_wasup", "natalie_books", "natalie_books2", "natalie_draw_a_paw", 'natalie_invitation', "natalie_drawing", "natalie_living", "natalie_attic"]],
["natalie_wasup","you","","what's up?","","",['_rand', 'natalie_wasup1', 'natalie_wasup2', 'natalie_wasup3', 'natalie_wasup4', 'natalie_wasup5', 'natalie_wasup6', 'natalie_wasup7', 'natalie_wasup8', 'natalie_wasup9', 'natalie_wasup10', 'natalie_wasup11', 'natalie_wasup12', 'natalie_wasup13', 'natalie_wasup14', 'natalie_wasup15', 'natalie_wasup16', 'natalie_wasup17', 'natalie_wasup18', 'natalie_wasup19', 'natalie_wasup20', 'natalie_wasup21', 'natalie_wasup22'],"","",""],
["natalie_wasup1","natalie","","do you think all dogs go to heaven?","","","","","",""],
["","","","","","","","",['yes', 'no'],['natalie_wasup1a', 'natalie_wasup1b']],
["natalie_wasup1a","you","","yeah, totally","","","natalie_wasup1c","","",""],
["natalie_wasup1b","you","","maybe not all of them","","","","","",""],
["natalie_wasup1c","natalie","","what about my pug, jimmy?","","","","","",""],
["","you","","was he well behaved?","","","","","",""],
["","natalie","","well, he pooped on all of our couches at least once","","","","","",""],
["","you","","hmm...","","","","","",""],
["","","","hard to say.","","","","","",""],
["","","","maybe he's in dog purgatory?","","","","","",""],
["","natalie","","lol maybe","","","","","",""],
["","you","","wait","","","","","",""],
["","","","PUGATORY","","","","","",""],
["","natalie","","PUGATORY!!!","","","null","","",""],
["natalie_wasup2","natalie","","wasuup?","","","","","",""],
["","you","","wasuuuuuuuuuup","","","","","",""],
["","natalie","","wasuuuuuuuuuuuuuuuuuuuuup","","","null","","",""],
["natalie_wasup3","natalie","","just nappin","","","","","",""],
["","you","","nice","","","null","","",""],
["natalie_wasup4","natalie","","once i got into an argument with a bag of fertilizer","","","","","",""],
["","","","i told it that it's full of shit","","","","","",""],
["","you","","nice","","","null","","",""],
["natalie_wasup5","natalie","","recently my company started marketing to babies","","","","","",""],
["","","","turns out they're the fastest growing demographic!","","","","","",""],
["","you","","lol","","","null","","",""],
["natalie_wasup6","natalie","","i tried to tell a joke about turning on a lamp","","","","","",""],
["","","","but i was accused of making [i]light[/i] of the situation","","","","","",""],
["","you","","haha","","","null","","",""],
["natalie_wasup7","natalie","","did you know luna moths don't have mouths?","","","","","",""],
["","","","i know, i was speechless too","","","","","",""],
["","you","","niiiiice","","","null","","",""],
["natalie_wasup8","natalie","","zooooop","","","","","",""],
["","you","","huh?","","","","","",""],
["","natalie","","sorry, i was just trying out a new sound","","","","","",""],
["","","","...","","","","","",""],
["","","","zoooooooooooop","","","null","","",""],
["natalie_wasup9","natalie","","have you seen all the broken glass downstairs?","","","","","",""],
["","","","we really need to [i]crack[/i] down on the cleaning department","","","","","",""],
["","you","","lol","","","null","","",""],
["natalie_wasup10","natalie","","did you ever want to be an astronaut as a kid?","","","","","",""],
["","","","","","","","",['yeah', 'nope'],['natalie_wasup10a', 'natalie_wasup10b']],
["natalie_wasup10a","you","","yeah, did you too?","","","","","",""],
["","natalie","","oh god yeah ","","","","","",""],
["","","","i had a huge astronaut phase","","","","","",""],
["","","","you think we could still be astronauts?","","","","","",""],
["","","","like skeleton astronauts or something?","","","natalie_wasup10c","","",""],
["natalie_wasup10b","you","","not really","","","","","",""],
["","natalie","","man, i had a huge astronaut phase","","","","","",""],
["","","","you think i could still be an astronaut?","","","","","",""],
["","","","like a skeleton astronaut or something?","","","","","",""],
["natalie_wasup10c","you","","maybe!","","","","","",""],
["","natalie","","god i hope so","","","null","","",""],
["natalie_wasup11","natalie","","did you know my dad worked at the largest liquor store in the world?","","","","","",""],
["","","","that's not a setup for a joke, just a fun fact","","","","","",""],
["","you","","wow","","","","","",""],
["","","","did you get to drink lots of liquor?","","","","","",""],
["","natalie","","nah i was like 8","","","","","",""],
["","you","","oh lol","","","null","","",""],
["natalie_wasup12","natalie","","i wish they showed you stats when you died","","","","","",""],
["","","","i was aiming for a world record in \"percentage of life spent sleeping\"","","","","","",""],
["","you","","what was your score?","","","","","",""],
["","natalie","","40 percent at least. maybe 50","","","null","","",""],
["natalie_wasup13","natalie","","AAH!","","","","","",""],
["","you","","what? what's wrong?","","","","","",""],
["","natalie","","nothing, i just thought about star-nosed moles","","","","","",""],
["","you","","what are those...?","","","","","",""],
["","natalie","","trust me, you don't want to know","","","null","","",""],
["natalie_wasup14","natalie","","[i]achoo![/i]","","","","","",""],
["","you","","bless you","","","","","",""],
["","natalie","","thanks","","","","","",""],
["","","","what were we talking about?","","","","","",""],
["","you","","uhhh idk","","","","","",""],
["","natalie","","me neither","","","null","","",""],
["natalie_wasup15","natalie","","i tried to pay attention to an astronomy lecture","","","","","",""],
["","","","but i ended up spacing out","","","","","",""],
["","you","","nice","","","null","","",""],
["natalie_wasup16","natalie","","did any other new people show up while i was sleeping?","","","","","",""],
["","you","","uhh, i don't know","","","","","",""],
["","","","how many of you were there when you went to sleep?","","","","","",""],
["","natalie","","seven, i think","","","","","",""],
["","","","sean, elijah, numa, oliver, kyungsoon, tori...","","","","","",""],
["","","","wait who am i missing","","","","","",""],
["","you","","yourself?","","","","","",""],
["","natalie","","OH YEAH, i forgot to count myself!","","","","","",""],
["","","","lol","","","null","","",""],
["natalie_wasup17","natalie","","[i]yaaaaaaaaaaaaaaawn[/i]","","","","","",""],
["","","","oh god that was a big yawn","","","","","",""],
["","you","","impressive!","","","","","",""],
["","natalie","","anyway sorry what was the question?","","","","","",""],
["","you","","i said what's up?","","","","","",""],
["","natalie","","oh not much","","","null","","",""],
["natalie_wasup18","natalie","","thinking about chinchillas","","","","","",""],
["","","","they're so... roumd","","","","","",""],
["","you","","too bad we don't have any a-[i]round[/i] here","","","","","",""],
["","natalie","","god you said it","","","null","","",""],
["natalie_wasup19","natalie","","spaaaaaaaaaaaaaace","","","","","",""],
["","you","","true","","","null","","",""],
["natalie_wasup20","natalie","","just had the craziest dream","","","","","",""],
["","you","","about what?","","","","","",""],
["","natalie","","no clue, i forgot","","","","","",""],
["","","","it was definitely crazy though","","","null","","",""],
["natalie_wasup21","natalie","","just had a dream that purrgatory was full of snakes and it was called snurrgatory","","","","","",""],
["","you","","i don't even know what to say about that","","","null","","",""],
["natalie_wasup22","natalie","","wish there were color pencils in purrgatory","","","","","",""],
["","","","or colors in general","","","","","",""],
["","you","","if only","","","null","","",""],
["natalie_living","you","","thoughts about life?","","","","","",""],
["","natalie","","i liked it!","","","","","",""],
["","","","8 out of 10","","","","","",""],
["","you","","what did you do for a living?","","","","","",""],
["","natalie","","janitor. denver museum of nature and science ","","","","","",""],
["","you","","ooh, how was that?","","","","","",""],
["","natalie","","well","","","","","",""],
["","","","i worked overnight so i didn't have to talk to anyone","","","","","",""],
["","","","and i got into planetarium shows for free","","","","","",""],
["","","","so, can't complain.","","","","","",""],
["","","","though that didn't stop my mom from nagging me that it's not a real job","","","","","",""],
["","you","","oof, that sucks","","","","","",""],
["","natalie","","eh, what can you do","","","","","",""],
["","","","any other questions?","","","","","",""],
["","you","","sure, how about...","","","","","",""],
["","","","","","","","",['any regrets?', 'greatest accomplishment?', 'anything you miss?'],['natalie_living1', 'natalie_living2', 'natalie_living3']],
["natalie_living1","you","","any regrets?","","","","","",""],
["","natalie","","just one, dude:","","","","","",""],
["","","","not finishing my webcomic ","","","","","",""],
["","you","","ooh, you had a webcomic?","","","","","",""],
["","natalie","","yeah... it wasn't even halfway through","","","","","",""],
["","","","but oh well","","","","","",""],
["","","","it's not like i could have known when i would die","","","","","",""],
["","you","","dang, i'm sorry","","","","","",""],
["","","","what was it about?","","","","","",""],
["","natalie","","oh, it's about like a moth that fights nightmares in the dreaming world","","","","","",""],
["","","","it's pretty awesome","","","","","",""],
["","you","","sounds like a [i]dream[/i] come true!","","","","","",""],
["","natalie","","you heckin know it","","","null","","",""],
["natalie_living2","you","","greatest accomplishment?","","","","","",""],
["","natalie","","the time i fit 12 marshmallows in my mouth at once. ","","","","","",""],
["","","","next question","","","","","",""],
["","you","","holy crap","","","","","",""],
["","","","uhh","","","","","",""],
["","","","[i]how[/i] did you fit 12 marshmallows into your mouth?","","","","","",""],
["","natalie","","years of grueling training.","","","","","",""],
["","","","also i have a big mouth","","","null","","",""],
["natalie_living3","you","","anything you miss?","","","","","",""],
["","natalie","","hmmm","","","","","",""],
["","","","like out of everything?","","","","","",""],
["","","","oreos.","","","","","",""],
["","you","","oh yeah","","","","","",""],
["","","","oreos are good","","","","","",""],
["","natalie","","sooo good","","","","","",""],
["","","","they don't have them here, but kyungsoon and i did dig up some old cookies in the kitchen once","","","","","",""],
["","","","they were so delicious","","","","","",""],
["","you","","wow, lucky","","","","","",""],
["","natalie","","it's the little things in death!","","","null","","",""],
["natalie_attic","you","","i like your attic!","","","","","",""],
["","natalie","","thanks!","","","","","",""],
["","","","i figured if i was going to be stuck here i might as well be comfy","","","","","",""],
["","you","","what's with the candles?","","","","","",""],
["","natalie","","oh, i just think they smell nice","","","","","",""],
["","you","","i guess you could say they're [i]wick[/i]-ed?","","","","","",""],
["","natalie","","heh","","","","","",""],
["","","","i'm gonna have to remember that one","","","","","",""],
["","you","","by the way, did you draw all these yourself?","","","","","",""],
["","natalie","","yep!","","","","","",""],
["","you","","they're very good!","","","","","",""],
["","natalie","","thanks!","","returned_draw_a_paw",['null', 'natalie_attic1'],"","",""],
["natalie_attic1","","","i was going to do more, but i didn't want to use up all our paper","","","","","",""],
["","","","so then i started drawing on my draw-a-paw","","","","","",""],
["","","","but then i lost that too","","","","","",""],
["","you","","aw, that sucks","","","","","",""],
["","natalie","","yeahhh","","","","","",""],
["","","","but hey, being unable to draw isn't so bad!","","","","","",""],
["","","","means i have more time to sleep","","","null","","",""],
["natalie_books","you","","uh, what did you want me to do with the books again?","","","","","",""],
["","natalie","","just return them to oliver, if you don't mind","","","","","",""],
["","you","","gotcha, sorry","","","","","",""],
["","natalie","","it's okay, i'm super forgetful too","","","","","",""],
["","","","speaking of which, what was your name again?","","","","","",""],
["","you","","it's {player}","","","","","",""],
["","natalie","","ok cool cool","","","null","","",""],
["natalie_books2","you","","i gave oliver the books!","followed_up_on_natalies_books","","","","",""],
["","natalie","","sweeeet thank you, i owe you one","","","","","",""],
["","","","he didn't give me a late fee, did he?","","","","","",""],
["","you","","no, but he looked sad","","","","","",""],
["","natalie","","aw ):","","","","","",""],
["","","","poor guy just wants people to read his books","","","","","",""],
["","you","","i would, if it wasn't just meows...","","","","","",""],
["","natalie","","yeah, me too","","","","","",""],
["","","","well, i haven't read a book for fun since middle school, so maybe i wouldn't","","","","","",""],
["","","","but i would look at the pictures!","","","null","","",""],
["natalie_draw_a_paw","you","","hey, is this yours?",[['_inv_draw_a_paw', false], ['_quest_natalie_draw_a_paw', false]],"","","","",""],
["","natalie","","NO WAY","","","","","",""],
["","","","you found my draw-a-paw!!","","","","","",""],
["","","","where was it?","","","","","",""],
["","you","","just in the meowseum","","","","","",""],
["","natalie","","ooooh, that makes sense","","","","","",""],
["","","","i was in there for a while","","","","","",""],
["","","","anyway, thank you so much!! you're a real pal!","","","","","",""],
["","you","","you're welcome!","","","","","",""],
["","natalie","","if i can ever return the favor, just let me know","","","","","",""],
["","","","least i can do is lend a [i]paw[/i] ;)","","","","","",""],
["","you","","heh thanks","","","","","",""],
["","","","i'll let you know for sure","_delay_returned_draw_a_paw","","null","","",""],
["natalie_drawing","","","_pass","",['natalie_finished_drawing3', 'natalie_finished_drawing2', 'natalie_finished_drawing1'],['natalie_drawing4', 'natalie_drawing3', 'natalie_drawing2', 'natalie_drawing1'],"","",""],
["natalie_drawing1","","","_pass","","saw_natalie_drawing1",['natalie_drawing1b', 'natalie_drawing1a'],"","",""],
["natalie_drawing1a","you","","how's the drawing?","saw_natalie_drawing1","","","","",""],
["","natalie","","it's going great!","natalie_drawing_timer1","","","","",""],
["","","","i haven't drawn anything in, like, aaages","","","","","",""],
["","","","i'm drawing a little robot dude rn","","","","","",""],
["","you","","cool!","","","","","",""],
["","","","can i see?","","","","","",""],
["","natalie","","uhh, i'll show you when i'm done","","","","","",""],
["","","","it's not really anything worth looking at right now","","","","","",""],
["","you","","oh, okay","","","","","",""],
["","natalie","","so yeah just check back later or something","","","","","",""],
["","you","","ok!","","","null","","",""],
["natalie_drawing1b","you","","how's the little robot dude?","","","","","",""],
["","natalie","","still working on it!","","","","","",""],
["","you","","cool cool","","","null","","",""],
["natalie_drawing2","","","_pass","","saw_natalie_drawing2",['natalie_drawing2b', 'natalie_drawing2a'],"","",""],
["natalie_drawing2a","you","","how's the little robot dude?","saw_natalie_drawing2","","","","",""],
["","natalie","","oh, i ended up scrapping him","natalie_drawing_timer2","","","","",""],
["","you","","aw, rip","","","","","",""],
["","natalie","","yeah, that's just how the cookie crumbles yaknow","","","","","",""],
["","","","but it's ok because i'm drawing something WAY better now","","","","","",""],
["","you","","what is it?","","","","","",""],
["","natalie","","imagine this:","","","","","",""],
["","","","birds. but big","","","","","",""],
["","you","","ooh?","","","","","",""],
["","","","how big?","","","","","",""],
["","natalie","","SO big","","","","","",""],
["","","","just wait and see","","","","","",""],
["","","","it'll be awesome","","","","","",""],
["","you","","alright!","","","null","","",""],
["natalie_drawing2b","you","","how are the big birds looking?","","","","","",""],
["","natalie","","they're SO big dude. these birds are straight GIGANTIC.","","","","","",""],
["","you","","wow","","","","","",""],
["","natalie","","just give me a liiiittle more time","","","","","",""],
["","you","","okay!","","","null","","",""],
["natalie_drawing3","","","_pass","","saw_natalie_drawing3",['natalie_drawing3b', 'natalie_drawing3a'],"","",""],
["natalie_drawing3a","you","","how are the big birds looking?","saw_natalie_drawing3","","","","",""],
["","natalie","","okay i know what you're going to say","natalie_drawing_timer3","","","","",""],
["","","","but","","","","","",""],
["","","","i gave up on the birds, and i'm drawing something EVEN BETTER now","","","","","",""],
["","you","","oh???","","","","","",""],
["","natalie","","it's one of my original characters","","","","","",""],
["","","","whenever i feel uninspired, i always go back to him","","","","","",""],
["","","","he's like a dog, right?","","","","","",""],
["","","","and his fur is rainbow colored","","","","","",""],
["","","","and also he rides a skateboard and vapes","","","","","",""],
["","you","","that sounds like literally the coolest dog on the planet","","","","","",""],
["","natalie","","RIGHT??","","","","","",""],
["","","","i'll show you when i'm done!","","","","","",""],
["","you","","alright!","","","null","","",""],
["natalie_drawing3b","you","","how's the rainbow dog?","","","","","",""],
["","natalie","","i'm so excited. it's going to be awesome","","","","","",""],
["","you","","can't wait!","","","null","","",""],
["natalie_drawing4","you","","how's the rainbow dog?","","","","","",""],
["","natalie","","uhhhh","","","","","",""],
["","you","","...did you erase it again","","","","","",""],
["","natalie","","yeaaaaaaaaaah idk","","","","","",""],
["","","","i'm not really feeling it anymore","","","","","",""],
["","","","kinda just want to sleep","","","","","",""],
["","you","","aw, that's alright","","","","","",""],
["","","","you don't have to draw if you're not feeling like it","","","","","",""],
["","natalie","","mhm","","","","","",""],
["","","","that's how the cookie crumbles and all that","","","","","",""],
["","","","i guess","","","","","",""],
["","you","","yep","","","","","",""],
["","","","...","","","","","",""],
["","","","","","","","",['are you okay?', 'sounds like art block'],['natalie_drawing4a', 'natalie_drawing4b']],
["natalie_drawing4a","you","","are you okay?","","","","","",""],
["","","","you look kinda blue","","","","","",""],
["","natalie","","{player}. i always look blue","","","","","",""],
["","you","","i didn't mean it like that!","","","","","",""],
["","natalie","","lool","","","natalie_drawing4c","","",""],
["natalie_drawing4b","you","","sounds like you have art block, tbh","","","","","",""],
["","natalie","","yeah, probably","","","","","",""],
["","","","though usually it doesn't last so freaking LONG","","","","","",""],
["natalie_drawing4c","","","i guess i'm just feeling a little demotivated","","","","","",""],
["","","","cus i don't feel like doing anything at all","","","","","",""],
["","you","","ah, i feel you","","","","","",""],
["","","","it doesn't help that you're in purrgatory","","","","","",""],
["","natalie","","yeah, exactly","","","","","",""],
["","","","i think maybe i'll just go to sleep again.","","","","","",""],
["","","","unless you have a better suggestion","","","","","",""],
["","you","","uhhhh","","","","","",""],
["","","","what if you...","","","","","",""],
["natalie_activity","","","","","","",['not natalie_tried_activity1', 'not natalie_tried_activity2', 'not natalie_tried_activity3', 'not natalie_tried_activity4'],['pet the cat?', 'rang the bell?', 'took a walk?', 'painted a mural?'],['natalie_activity1', 'natalie_activity2', 'natalie_activity3', 'natalie_activity4']],
["natalie_activity1","you","","what if you went to the commons and pet the cat?","natalie_tried_activity1","","","","",""],
["","natalie","","ehh, no thanks","","","","","",""],
["","","","i'm allergic to cats","","","","","",""],
["","you","","and they put you in purrgatory?","","","","","",""],
["","","","oh my god that's so cruel","","","","","",""],
["","natalie","","right???","","","natalie_activity","","",""],
["natalie_activity2","you","","what if you went and rang that giant bell?","natalie_tried_activity2","","","","",""],
["","natalie","","oh, sean and i did that a while ago","","","","","",""],
["","","","tori and oliver got SUPER mad at us","","","","","",""],
["","you","","oof","","","","","",""],
["","natalie","","listen, it was totally worth it","","","","","",""],
["","","","don't want to bother them again, though","","","","","",""],
["","you","","yeah, that's fair","","","natalie_activity","","",""],
["natalie_activity3","you","","what if you took a walk in the park?","natalie_tried_activity3","","","","",""],
["","natalie","","ugh, no one told me the afterlife would involve exercise","","","","","",""],
["","","","mostly kidding","","","","","",""],
["","","","a walk sounds nice, but i dont think i'm up to it right now","","","","","",""],
["","you","","ah, ok","","","natalie_activity","","",""],
["natalie_activity4","you","","what if you painted a mural?","natalie_tried_activity4","","","","",""],
["","","","like, you know that one in the catnip garden?","","","","","",""],
["","natalie","","heh, do i [i]know[/i] it?","","","","","",""],
["","","","i'm the one that drew it!","","","","","",""],
["","you","","oh really?","","","","","",""],
["","natalie","","yeah, just a little gift for numa","","","","","",""],
["","you","","aww, that's really sweet!","","","","","",""],
["","","","maybe the two of us could make another one, just for ourselves?","","","","","",""],
["","natalie","","hmmm","","","","","",""],
["","","","tell you what","","","","","",""],
["","","","that actually sounds pretty fun","","","","","",""],
["","","","let's do it","","","","","",""],
["","you","","woohoo!","","","","","",""],
["","natalie","","let me just grab my art supplies...","","","","","",""],
["","","","where do you want to go?","","","","","",""],
["","you","","uhhhh","","","","","",""],
["","","","i don't know, i didn't think that far ahead","","","","","",""],
["","natalie","","it's fine, we can figure it out as we go","","","","","",""],
["","","","come on, let's go","","","","","",""],
["","_none","","the two of you climb out of the attic.","_goto_house5","","","","",""],
["","natalie","","wow, it's been a while since i've been down here.","","","","","",""],
["","","","what year is it?","","","","","",""],
["","you","","uh, 2021, i think","","","","","",""],
["","natalie","","heck, i died all the way back in 2015","","","","","",""],
["","you","","wow","","","","","",""],
["","natalie","","do we have flying cars yet?","","","","","",""],
["","","","","","","","",['no, but we have selfie sticks', 'no, but we have blockchain', 'yes'],['natalie_activity5', 'natalie_activity6', 'natalie_activity7']],
["natalie_activity5","you","","no, but we have these things called selfie sticks?","","","","","",""],
["","natalie","","oh, we had those too","","","","","",""],
["","","","my dad really loved them","","","","","",""],
["","you","","o i see","","","natalie_activity8","","",""],
["natalie_activity6","you","","no, but we have a thing called blockchain?","","","","","",""],
["","natalie","","wtf is that","","","","","",""],
["","","","some sort of badass melee weapon??","","","","","",""],
["","you","","no it's like, some sort of technology they use for bitcoin","","","","","",""],
["","","","apparently it's destroying the environment or something","","","","","",""],
["","natalie","","oh, we had bitcoin","","","","","",""],
["","","","that's not as exciting as i expected","","","","","",""],
["","you","","sorry to get your hopes up","","","natalie_activity8","","",""],
["natalie_activity7","you","","yes, and we all live in floating skyscrapers on the moon","","","","","",""],
["","natalie","","dude that's sick","","","","","",""],
["","you","","yeah, we all had to relocate after the earth was blown up by climate change","","","","","",""],
["","natalie","","damn, always knew it would be climate change that did us in","","","natalie_activity8","","",""],
["natalie_activity8","you","","so, is this like [i]your[/i] house?","_goto_house4","","","","",""],
["","natalie","","idk, it was empty when i got here","","","","","",""],
["","","","so i just moved in","","","","","",""],
["","","","","","","","",['did you draw that sign?', 'do you know what happened to those pillows?'],['natalie_activity9', 'natalie_activity10']],
["natalie_activity9","you","","did you draw that sign?","","","","","",""],
["","natalie","","oh god no","","","","","",""],
["","","","i tried to take it down once but it kept reappearing when i slept","","","","","",""],
["","you","","that's... sort of concerning","","","","","",""],
["","natalie","","tell me about it","","","natalie_activity11","","",""],
["natalie_activity10","you","","do you know what happened to those pillows?","","","","","",""],
["","natalie","","they were like that when i got here, but...","","","","","",""],
["","","","based on the general theme of this place?","","","","","",""],
["","","","...probably wild wolverines","","","","","",""],
["","you","","yeah, i was just thinking that too","traveling_with_natalie","","natalie_activity11","","",""],
["natalie_activity11","you","","so, where should we go?","_goto_hallway15","","","","",""],
["","natalie","","you know that long hallway outside of the commons?","","","","","",""],
["","","","probably lots of good walls to draw on there","","","","","",""],
["","you","","bet!","","","","","",""],
["","_none","","you make your way to the hallway.","_goto_hallway2","","","","",""],
["","natalie","","oh, this is PURRFECT","","","","","",""],
["","","","i can't wait to graffiti this up!","","","","","",""],
["","you","","heck yeah, go ahead!","","","","","",""],
["","natalie","","oh","","","","","",""],
["","","","like, right now?","","","","","",""],
["","you","","yeah, sure!","","","","","",""],
["","","","didn't you say you couldn't wait?","","","","","",""],
["","natalie","","yeah but i didn't mean it LITERALLY","","","","","",""],
["","","","like i could definitely wait if i had to","","","","","",""],
["","you","","aw, come on, just draw something!","","","","","",""],
["","_none","","natalie brandishes a pencil.","","","","","",""],
["","natalie","","okay, i'm gonna do it!!","","","","","",""],
["","you ","","go for it!!","","","","","",""],
["","natalie","","...","","","","","",""],
["","","","....","","","","","",""],
["","","",".....","","","","","",""],
["","_none","","natalie doesn't move.","","","","","",""],
["","you","","take ur time","","","","","",""],
["","natalie","","aaah i can't do it, dude","","","","","",""],
["","","","i'm still art blocked","","","","","",""],
["","you","","dang...","","","","","",""],
["","natalie","","what should i even draw?","","","","","",""],
["","you","","i don't know, maybe uhhh","","","","","",""],
["","","","","","","","",['a cat', 'a dragon', 'spongebob'],['natalie_mural4a', 'natalie_mural4b', 'natalie_mural4c']],
["natalie_mural4a","you","","a cat?","","","","","",""],
["","natalie","","okay, i'll draw a cat","","","","","",""],
["","","","i'm doing it for real!!","","","","","",""],
["","you","","ok!","","","","","",""],
["","_none","","natalie furiously scribbles on the wall.","","","","","",""],
["","natalie","","done!","natalie_chose_cat","","","","",""],
["","you","","nice!!","","","","","",""],
["","","","that's a cute cat!","","","","","",""],
["","natalie","","thanks!","","","","","",""],
["","you","","why is it saying fuck?","","","","","",""],
["","natalie","","because ","","","","","",""],
["","","","he did hard time in al-cat-raz and came out a changed feline","","","","","",""],
["","","","he no longer trusts anything but his own four paws","","","","","",""],
["","you","","o i see","","","natalie_mural4d","","",""],
["natalie_mural4b","you","","a dragon?","","","","","",""],
["","natalie","","okay, i'll draw a dragon","","","","","",""],
["","","","i'm doing it for real!!","","","","","",""],
["","you","","ok!","","","","","",""],
["","_none","","natalie furiously scribbles on the wall.","","","","","",""],
["","natalie","","done!","natalie_chose_dragon","","","","",""],
["","you","","nice!!","","","","","",""],
["","","","that's a cute dragon!","","","","","",""],
["","natalie","","thanks!","","","","","",""],
["","you","","why is it saying books?","","","","","",""],
["","natalie","","because it's a book wyrm","","","","","",""],
["","","","his only love in life is books and he hoards them in his lib-roar-y","","","","","",""],
["","","","but he's doomed to a life of tragedy because he keeps setting his own books on fire","","","","","",""],
["","you","","o i see","","","natalie_mural4d","","",""],
["natalie_mural4c","you","","spongebob?","","","","","",""],
["","natalie","","uhhhh okay i'll draw spongebob i guess","","","","","",""],
["","","","i'm doing it for real!!","","","","","",""],
["","you","","ok!","","","","","",""],
["","_none","","natalie furiously scribbles on the wall.","","","","","",""],
["","natalie","","done!","natalie_chose_spongebob","","","","",""],
["","you","","nice!!","","","","","",""],
["","","","that... is a surprisingly accurate spongebob","","","","","",""],
["","natalie","","i used to watch a lot of spongebob","","","","","",""],
["","you","","why is he saying pants?","","","","","",""],
["","natalie","","uhh","","","","","",""],
["","","","i don't know","","","","","",""],
["","","","it's the first word that came to mind","","","","","",""],
["","you","","o i see","","","","","",""],
["natalie_mural4d","natalie","","do you want to draw something?","","","","","",""],
["","you","","uhh, sure!","","","","","",""],
["","","","it might look kinda silly next to your masterpiece, though","","","","","",""],
["","natalie","","nahh, don't worry about it","","","","","",""],
["","","","here, take my pencils","","","","","",""],
["","you","","thanks!","","","","","",""],
["","","","here goes nothing...","_delay_start_drawing","","null","","",""],
["natalie_after_drawing","natalie","natalie_neutral","heck, nice work!","","","","","",""],
["","","","","","","","",['thanks!', 'it\'s terrible'],['natalie_mural5', 'natalie_mural6']],
["natalie_mural5","you","","thanks!","","","","","",""],
["","","","pretty happy with that, actually","","","","","",""],
["","natalie","","move over, picasso, there's a new artist in town","","","","","",""],
["","you","","haha","","","natalie_mural7","","",""],
["natalie_mural6","you","","are you kidding?","","","","","",""],
["","","","it's terrible","","","","","",""],
["","natalie","","awww, it's not that bad!","","natalie_chose_cat",['natalie_mural6a', 'natalie_mural7'],"","",""],
["natalie_mural6a","","","it goes well with the \"fuck\"","","","","","",""],
["","you","","that it does","","","","","",""],
["natalie_mural7","","","_pass","","met_tori",['natalie_mural7_normal', 'natalie_mural7_alt'],"","",""],
["natalie_mural7_alt","???","","natalie, what in satan's name are you doing?","","","","","",""],
["","_none",['tori_neutral', 'natalie_neutral'],"an owl appears down the hallway.","","","","","",""],
["","???","","and who might this be?","","","","","",""],
["","you","","i'm {player}!","","","","","",""],
["","???","","ah, {player}.","","","","","",""],
["","","","i've been expecting you.","","","","","",""],
["","natalie","","that's not ominous at all","","","","","",""],
["","???","","it's not ominous! just a fact.","","","","","",""],
["","tori","","i'm tori. i look forward to getting to know you better.","","","","","",""],
["","","","","","","","",['same here', 'that still sounds ominous'],['natalie_mural7_alt_a', 'natalie_mural7_alt_b']],
["natalie_mural7_alt_a","you","","um, same here!","","","","","",""],
["","natalie","","come on guys, this isn't a business meeting","","","","","",""],
["","tori","","just being polite.","","","natalie_mural7_alt_d","","",""],
["natalie_mural7_alt_b","you","","that still sounds kind of ominous...","","","","","",""],
["","_none","","tori rolls her eyes.","","","","","",""],
["","tori","","fine, you got me. i'm trying to lure you into my lair so i can eat you whole.","","","","","",""],
["","natalie","","i KNEW it!","","","natalie_mural7_alt_d","","",""],
["natalie_mural7_alt_d","tori","","anyway, i am curious...","","","","","",""],
["","","","what inspired you to start marking up the walls?","","","natalie_mural7_combined","","",""],
["natalie_mural7_normal","???","","what are you hooligans doing?","","","","","",""],
["","_none",['tori_neutral', 'natalie_neutral'],"tori appears down the hallway.","","","","","",""],
["","natalie","","hey tori!","","","natalie_mural7_combined","","",""],
["natalie_mural7_combined","natalie","","just adding a little splash of color to the hallway","","","","","",""],
["","","","metaphorically, of course","","","","","",""],
["","","","given the whole black-and-white thing","","","","","",""],
["","tori","","i see.","","","","","",""],
["","","","no offense, but is it a good idea to scribble all over the place we'll be stuck in for eternity?","","","","","",""],
["","natalie","","aww, we're just having a little bit of fun!","","","","","",""],
["","","","do you want to draw something too?","","","","","",""],
["","tori","","i'll pass this time.","",['natalie_chose_cat', 'natalie_chose_dragon'],['natalie_mural8', 'natalie_mural9', 'natalie_mural10'],"","",""],
["natalie_mural8","you","","do you like the cat?","","","","","",""],
["","tori","","i do like the cat, actually.","","","","","",""],
["","","","why is it saying fuck?","","","","","",""],
["","_none","","natalie waves her hand dismissively.","","","","","",""],
["","natalie","","long story.","","","natalie_mural11","","",""],
["natalie_mural9","you","","do you like the dragon?","","","","","",""],
["","tori","","i do like the dragon, actually.","","","","","",""],
["","","","why is it saying books?","","","","","",""],
["","_none","","natalie waves her hand dismissively.","","","","","",""],
["","natalie","","long story.","","","natalie_mural11","","",""],
["natalie_mural10","you","","do you like the spongebob?","","","","","",""],
["","tori","","i do like the spongebob, actually.","","","","","",""],
["","","","why is he saying pants?","","","","","",""],
["","_none","","natalie waves her hand dismissively.","","","","","",""],
["","natalie","","long story.","","","natalie_mural11","","",""],
["natalie_mural11","tori","","you know natalie, your art style kind of reminds me of this artist i used to follow.","","","","","",""],
["","","","i think her name was uh...","","","","","",""],
["","","","pocketnat?","","","","","",""],
["","natalie","","sorry what","","","","","",""],
["","tori","","pock-et-nat. like the word pocket, then nat, like your name.","","","","","",""],
["","natalie","","wh","","","","","",""],
["","tori","","yeah, she ran this webcomic called nocturnal, but she just disappeared one day. social media, everything.","","","","","",""],
["","","","natalie, are you okay?","","","","","",""],
["","natalie","","you read nocturnal??","","","","","",""],
["","tori","","oh, are you familiar with it?","","","","","",""],
["","natalie","","you... could say that, yeah","","","","","",""],
["","tori","","it used to be my favorite.","","","","","",""],
["","","","it was a sad, sad day when pocket disappeared.","","","","","",""],
["","","","granted, there were a couple of continuation comics made by fans, but i'm not sure if you were around for that, since you died before me.","","","","","",""],
["","","","come to think of it, you died around the same time pocket disappeared, so i guess you wouldn't have been.","","","","","",""],
["","natalie","","hhh","","","","","",""],
["","tori","","i'm... sorry, is it just me, or is this conversation becoming sort of one-sided?","","","","","",""],
["","you","","i think maybe what natalie is trying to say is--","","","","","",""],
["","natalie","","it me","","","","","",""],
["","","","me pocket","","","","","",""],
["","","","i mean i'm pocket","","","","","",""],
["","tori","","...sorry?","","","","","",""],
["","natalie","","IM POCKET ITS ME","","","","","",""],
["","","","I MADE NOCTURNAL","","","","","",""],
["","tori","","...no way","","","","","",""],
["","natalie","","YES WAY","","","","","",""],
["","tori","","oh my god","","","","","",""],
["","natalie","","dude this is so cool!!","","","","","",""],
["","","","i can't believe you used to read nocturnal!","","","","","",""],
["","tori","","if you really are pocketnat, i have to know.","","","","","",""],
["","","","were edvard and twist ever supposed to get together?","","","","","",""],
["","natalie","","well, DUH","","","","","",""],
["","","","the subtext is ALL OVER chapter 13","","","","","",""],
["","tori","","I KNEW IT.","","","","","",""],
["","you","","wow, this sure is crazy...","","","","","",""],
["","tori","","god, i remember i used to read so much fanfiction about those two.","","","","","",""],
["","natalie","","wait, really? who else shipped them?","","","","","",""],
["","tori","","the better question is, who DIDN'T ship them?","","","","","",""],
["","","","there's this one where sofia becomes a mech pilot...","","","","","",""],
["","you","","i think i'm just gonna... go...","","","","","",""],
["","natalie","","you know, spoilers, but that's surprisingly similar to something i was drafting for the third arc!","","","","","",""],
["","tori","","TELL ME. NOW.","natalie_tori_talking_timer","","","","",""],
["","_none","","you quietly sidle away from the conversation. they don't seem to notice.","_delay_natalie_completed_mural","","null","","",""],
["natalie_and_tori","natalie",['tori_neutral', 'natalie_neutral'],"...but the craziest part is?","","","","","",""],
["","","","they were ROOMMATES","","","","","",""],
["","tori","","oh my god they were roommates","","","null","","",""],
["natalie_post","","","_pass","","natalie_quest_complete",['natalie_post_default', 'natalie_post1'],"","",""],
["natalie_post1","natalie","natalie_neutral","oh, hey {player}!","","","","","",""],
["","","","heck, i'm sorry i snubbed you earlier","","","","","",""],
["","","","i was just so excited about nocturnal that i forgot about everything else","","","","","",""],
["","you","","it's okay, heh","","","","","",""],
["","","","wow, it looks like you've been hard at work","","","","","",""],
["","natalie","","you bet!!","","","","","",""],
["","","","tori got me motivated to work on nocturnal again, so i started drawing the next chapter based on what i remember from earth!","","","","","",""],
["","","","isn't that awesome??","","","","","",""],
["","you","","that's great!","","","","","",""],
["","","","getting over your art block [i]moth[/i] feel pretty good","","","","","",""],
["","natalie","","hehe yeah","","","","","",""],
["","","","i feel like i could draw ten robot dudes [i]antenna[/i] those big birds too","","","","","",""],
["","you","","guess all that art was [i]pen[/i]-t up inside you","","","","","",""],
["","natalie","","all you need sometimes is a push in the right [i]draw[/i]-rection","","","","","",""],
["","you","","you'd be [i]write[/i] about that","","","","","",""],
["","natalie","","you know what they say, before you learn to run you have to learn to [i]wok[/i]!","","","","","",""],
["","_none","","natalie holds up a drawing of an old lady holding a wok.","","","","","",""],
["","you","","what -- why do you just have that on hand??","","","","","",""],
["","natalie","","okay, see, sofia goes into the dream of an old lady in this chapter","","","","","",""],
["","","","and she's cooking dinner for her family, right?","","","","","",""],
["","","","like, a harmless little grandma","","","","","",""],
["","","","but it turns out, she's actually a SPY specializing in WOK COMBAT","","","","","",""],
["","you","","oh wow","","","","","",""],
["","natalie","","oooooooh it's gonna be so cool","","","","","",""],
["","","","i gotta get back to work","","","","","",""],
["","you","","ok have fun!!","","","","","",""],
["","natalie","","thanks, i think i will!","_delay__goto_flashback_natalie","","null","","",""],
["natalie_post2","natalie","","{player}!!","","","","","",""],
["","","","oh my god, are you okay?","","","","","",""],
["","you","natalie_neutral","...",[['_goto_attic', true], ['_hide_natalie_nocturnal', true]],"","","","",""],
["","","","urp","","","","","",""],
["","","","yeah i'm fine... just got dizzy all of a sudden","","","","","",""],
["","natalie","","dude you totally blacked out and fell over","","","","","",""],
["","","","are you sure you're okay?","","","","","",""],
["","you","","yes, i'm fine now","","","","","",""],
["","","","thanks though","","","","","",""],
["","natalie","","ok, good.","","","","","",""],
["","","","i was about to start doing mouth-to-mouth or something, geez","","","","","",""],
["","","","take it easy, okay?","","","","","",""],
["","you","","will do","","","null","","",""],
["natalie_post_default","natalie","natalie_neutral","what's up dude?","","","","","",""],
["","","","","","","",['true', 'saw_natalie_intro and not returned_natalies_books', 'returned_natalies_books and not followed_up_on_natalies_books', 'elijah_planning_slam and not invited_natalie', 'true', 'true'],["what's up?", "about the books...", "about the books...", '(invite natalie to the everything slam)', "so, nocturnal?", "thoughts about living?"],["natalie_wasup", "natalie_books", "natalie_books2", 'natalie_invitation', "natalie_nocturnal", "natalie_living"]],
["natalie_nocturnal","you","","so, nocturnal, huh?","","","","","",""],
["","natalie","","nocturnal dude","","","","","",""],
["","","","the closest i'll ever get to having a baby","","","","","",""],
["","","","","","","",['true', 'true', 'not got_nocturnal_summary'],['how come?', "how'd you get started?", "what's it about?"],['natalie_nocturnal1', 'natalie_nocturnal2', 'natalie_nocturnal3']],
["natalie_nocturnal1","you","","how come?","","","","","",""],
["","natalie","","oh, i'm just not interested in relationships and all that jazz.","","","","","",""],
["","","","nope, no thank you.","","","","","",""],
["","you","","ohh i see","","","","","",""],
["","natalie","","besides, why have a baby when you can have a dog?","","","","","",""],
["","you","","truuue","","","null","","",""],
["natalie_nocturnal2","you","","so how'd you get into making a webcomic?","","","","","",""],
["","natalie","","it was on my bucket list for a while, actually!","","","","","",""],
["","","","i mean, i've been making art since i was a kid","","","","","",""],
["","","","but when i turned 25 i was like, well, i'm well on my way to a midlife crisis, i might as well shake things up","","","","","",""],
["","","","and it went SO much better than i could have expected","","","","","",""],
["","you","","that's cool!","","","","","",""],
["","natalie","","the other things on my bucket list were to bowl a perfect game and run a d&d campaign","","","","","",""],
["","","","but i didn't have time to get around to that.","","","","","",""],
["","you","","isn't bowling a perfect game, like, really rare?","","","","","",""],
["","natalie","","yeah, but i like to dream big!","","","","","",""],
["","","","i wanted to be an astronaut until i was like, 17","","","","","",""],
["","you","","wow","","","null","","",""],
["natalie_nocturnal3","you","","so like, what's the whole thing about?","got_nocturnal_summary","","","","",""],
["","natalie","","ohoho","","","","","",""],
["","","","are you sure you want to go down that rabbit hole?","","","","","",""],
["","you","","maaaaybe?","","","","","",""],
["","natalie","","heh, i'll try to keep it short","","","","","",""],
["","","","i could talk about it for DAYS if you let me","","","","","",""],
["","","","but uhhh basically it's about a moth who can go into other people's dreams","","","","","",""],
["","","","and there's this mysterious creature called the blight that's giving people nightmares, right?","","","","","",""],
["","","","well, turns out it's an alien from space","","","","","",""],
["","","","so the moth -- sofia -- and her friends, they form a team to fight the blight","","","","","",""],
["","","","and they call themselves the nocturnals","","","","","",""],
["","","","does that make sense?","","","","","",""],
["","","","","","","","",['yeah i guess', 'ooh, interesting'],['natalie_nocturnal3a', 'natalie_nocturnal3b']],
["natalie_nocturnal3a","you","","yeah, i guess","","","","","",""],
["","natalie","","hehe, yeah, that's the basic gist of it","","","","","",""],
["","","","i better stop before i start rambling","","","natalie_nocturnal4","","",""],
["natalie_nocturnal3b","you","","ooh, interesting","","","","","",""],
["","natalie","","you think so??","","","","","",""],
["","","","the thing that introduces the whole story -- the \"call to adventure,\" sort of -- is a big dream leak in the city","","","","","",""],
["","","","and a dream leak is like when the blight leaks out from nightmares into the real world, right?","","","","","",""],
["","","","although they don't know that's what's happening until -- well, never mind that","","","","","",""],
["","","","so that's when they meet hazel, who--","","","","","",""],
["","","","wait, i didn't even introduce the others yet!","","","","","",""],
["","","","so there's edvard, he's sofia's best friend","","","","","",""],
["","","","then there's twist, who's sort of like a person trapped inside of a dream construct?","","","","","",""],
["","","","anyway, the three of them are running from the various monsters the blight created, but hazel puts them all in a time trance because--","","","","","",""],
["","","","wait wait wait, let me tell you about hazel!","","","","","",""],
["","","","","","","","",['(confused nod)', 'ok i\'m with you'],['natalie_nocturnal3c', 'natalie_nocturnal3d']],
["natalie_nocturnal3c","you","","[i]confused nod[/i]","","","","","",""],
["","natalie","","dang, sorry, i lost you didn't i","","","","","",""],
["","","","i think that's a pretty good introduction, anyway, don't want to spoil too much","","","natalie_nocturnal4","","",""],
["natalie_nocturnal3d","you","","ok i'm still with you","","","","","",""],
["","natalie","","right so hazel is a librarian and she's like their mentor figure, she's the one who saves them from the leak and teaches them how to defend themselves using lucid dreaming powers","","","","","",""],
["","","","but in the next chapter, when they get trapped inside the hall of specters--","","","","","",""],
["","","","wait, whoops, i almost told you a major spoiler","","","","","",""],
["","","","i mean, long story short is that hazel's dream avatar gets into trouble, and that's what makes sofia and co go like","","","","","",""],
["","","","\"well, we don't want to just sit around protecting ourselves, we want to go save hazel and anyone else who's in danger and stuff!\"","","","","","",""],
["","","","but hazel's mind is well-protected due to her being an experienced dream walker, right?","","","","","",""],
["","","","so in order to get into her dreamspace, they need something called a seeing-eye stone from the blight factory","","","","","",""],
["","","","and the blight factory -- i'll come back to that later, it's not that important","","","","","",""],
["","","","so all of THAT takes them through several chapters of shenanigans","","","","","",""],
["","","","during which they seek the help of a multi-dimensional entity named rune","","","","","",""],
["","","","but in order to interface with his dreamspace, the nocturnals have to force a time conjunction -- that's when one of rune's time facets projects onto our three-dimensional world, by the way--","","","","","",""],
["","","","and THAT'S where one of my favorite characters comes in...","","","","","",""],
["","","","tony the hot dog seller!!","","","","","",""],
["","","","","","","","",['(polite cough)', 'the hot dog seller??'],['natalie_nocturnal3e', 'natalie_nocturnal3f']],
["natalie_nocturnal3e","you","","[i]polite cough[/i]","","","","","",""],
["","natalie","","oh god sorry, i got way off track","","","","","",""],
["","","","but uhhhh yeah! nocturnal!","","","natalie_nocturnal4","","",""],
["natalie_nocturnal3f","you","","tony the hot dog seller??","","","","","",""],
["","natalie","","YES so chapter 4 ends on this major cliffhanger, where they're all cornered in the blight factory, and then chapter 5 opens with this major tangent","","","","","",""],
["","","","about this random character who we haven't seen since the first chapter, tony the hot dog seller","","","","","",""],
["","","","but this is the cool part","","","","","",""],
["","","","he keeps stumbling into the blight's traps and somehow bumbling his way through","","","","","",""],
["","","","and ultimately HE'S the one that creates the time conjunction by enacting something called the dreamspace hot dog gambit!","","","","","",""],
["","","","this is a bit of a spoiler ,but they eventually find out that tony is actually a BLIGHT PRINCE who defected from the throne and disgiused himself as a human","","","","","",""],
["","","","there's this great scene where rune threatens to eject tony into space and he's like","","","","","",""],
["","","","\"oh nooo, don't eject me into the environment at which my blight powers are most powerful, whatever will i do\"","","","","","",""],
["","","","ooo h, i'm getting so off track","","","","","",""],
["","","","right, eventually they manage to get rune's aid and destroy the factory, though they have to trade two soul essences and the MAJORITY of edvard's plushie collection","","","","","",""],
["","","","but hazel's dreamspace is nowhere to be found!","","","","","",""],
["","","","ummm i'm gonna skip over a couple of chapters in order to get you up to date","","","","","",""],
["","","","chapters 6 through 8 are mostly filler if we're being honest, though it does contain pollux's entire character arc, and a lot of people say she's their favorite","","","","","",""],
["","","","actually, people liked her so mucj i'm thinking about bringing her back in the new chapter, but that's not important","","","","","",""],
["","","","chapter 9, they get on a space elevator, yada yada, chapter 10 is mostly exploring twist's tragic backstory","","","","","",""],
["","","","but THEN, in chapter 11","","","","","",""],
["","","","the nocturnals end up stepping through dreams allthe way to nepal, right?","","","","","",""],
["","","","and you won't believe what they find there.","","","","","",""],
["","","","SPACE. PIRATES.","","","","","",""],
["","","","","","","","",['(pretend to check watch)', 'oh my god, space pirates??'],['natalie_nocturnal3g', 'natalie_nocturnal3h']],
["natalie_nocturnal3g","you","","[i]checking watch motion[/i]","","","","","",""],
["","natalie","","oh geez, how long was i rambling for?","","","","","",""],
["","","","sorry, that's nocturnal! haha","","","natalie_nocturnal4","","",""],
["natalie_nocturnal3h","you","","oh my god, space pirates??","","","","","",""],
["","natalie","","you hecking BET","","","","","",""],
["","","","the space pirates turn out to be the real villains of the third arc, though we haven't quite gotten there yet","","","","","",""],
["","","","but anyway, as sophia and the nocturnals are led on board the space pirate ship, arms bound, they see a familiar face before them...","","","","","",""],
["","","","HAZEL THE LIBRARIAN","","","","","",""],
["","you","","wait, what's hazel doing on a space pirate ship??","","","","","",""],
["","natalie","","well, THAT","","","","","",""],
["","","","you're going to have to read nocturnal to find out ;3","","","","","",""],
["","you","","awww, you can't leave me hanging like that!","","","","","",""],
["","natalie","","sorry bud, not spoiling this one for you","","","","","",""],
["","","","thanks for letting me rant about it for a while though!","","","","","",""],
["","you","","yeah, of course!","","","","","",""],
["","","","it sounds really cool","","","","","",""],
["","natalie","","i appreciate that, really","","","","","",""],
["","","","but now i gotta get back to coloring edvard's luscious hair","","","","","",""],
["","you","","please do not let me stop you","","","null","","",""],
["natalie_nocturnal4","you","","it's okay, it sounds interesting!","","","","","",""],
["","natalie","","heh, thanks","","","","","",""],
["","","","that reminds me, i should finish this panel...","","","","","",""],
["","you","","oh yeah, don't let me stop you","","","null","","",""],
["natalie_invitation","you","","so, elijah and i are planning something called an everything slam","invited_natalie","","","","",""],
["","","","it's like a poetry slam, but you can do anything you want, not just poetry!","","","","","",""],
["","natalie","","ooooh","","","","","",""],
["","","","can i come??","","","","","",""],
["","you","","yeah of course!","","","","","",""],
["","","","i was thinking you might like to set up an art exhibit or something","","","","","",""],
["","natalie","","yooo that would be awesome!","","","","","",""],
["","","","i'm totally down","","","","","",""],
["","you","","awesome!","","","","","",""],
["","","","we're thinking about ringing the big bell to let everyone know it's starting","","","","","",""],
["","","","does that work?","","","","","",""],
["","natalie","","sounds good to me dude","","","","","",""],
["","","","oooh i should pull out some of my old portfolios","","","","","",""],
["","","","bet there's some good stuff in there","","","","","",""],
["","you","","heck yeah","","","null","","",""]
]