extends Node

var raw_blocks = [
["natalie_glass","natalie","natalie_neutral","{player}?","","","","","",""],
["","","","what was that noise?","","","","","",""],
["","you","","natalie!","","","","","",""],
["","","","it's nothing, just broke a glass","","","","","",""],
["","","","well","","","","","",""],
["","","","watched the cat break a glass","","","","","",""],
["","cat","","meow :3","","","","","",""],
["","natalie","","oh, phew. i was worried someone got hurt","","","","","",""],
["","you","","do you know where i can find another glass?","","","","","",""],
["","","","i'm trying to get oliver a drink","","","","","",""],
["","natalie","","hmmm... dunno.","","","","","",""],
["","","","as far as i know, that was the last cup in purrgatory","","","","","",""],
["","you","","ugh","","","","","",""],
["","natalie","","but who knows? maybe you'll find a [i]cup[/i]-le lying around.","","","","","",""],
["","you","","heh","","","","","",""],
["","","","you [i]mug[/i] be kidding me","","","","","",""],
["","natalie","","hones-[i]tea[/i] is the best policy","","","","","",""],
["","you","","okay, i'd better go tell oliver he's not getting his orange soda",[['_quest_oliver_soda1', false], ['_quest_oliver_soda2', true]],"","","","",""],
["","natalie","","okay, see ya!","","","","","",""],
["","","","i'll be in the attic if u want to chat","","","","","",""],
["","you","","kk","","","null","","",""],
["natalie_intro","???","","zzz...","met_natalie","","","","",""],
["","you","","hello?","","","","","",""],
["","???","","fnmh?","natalie_awake_in_attic","blackout",['natalie_intro_a', 'natalie_intro_b'],"","",""],
["natalie_intro_a","","natalie_neutral","hey, the lights are out","_hide_natalie_sleeping","","natalie_intro_c","","",""],
["natalie_intro_b","","natalie_neutral","oh, hey","_hide_natalie_sleeping","","","","",""],
["natalie_intro_c","","","who are you?","","","","","",""],
["","you","","hi, i'm new here!","","","","","",""],
["","natalie","","hi new here, i'm natalie","","","","","",""],
["","","","","","","","",['nice one', 'boooooo'],['natalie_intro1', 'natalie_intro2']],
["natalie_intro1","you","","nice one","","","","","",""],
["","natalie","","thanks, i'll be here all eternity","","","natalie_intro3","","",""],
["natalie_intro2","you","","boooooooooooooooooooooo","","","","","",""],
["","natalie","","come on, that's a classic","","","","","",""],
["natalie_intro3","","","but really, what's your name?","","","","","",""],
["","you","","it's {player}","","","","","",""],
["","natalie","","cool, nice to meet you","","","","","",""],
["","you","","you too!","","rang_doorbell",['natalie_intro_doorbell', 'natalie_intro_continue'],"","",""],
["natalie_intro_doorbell","you","","uh, i'm guessing you don't remember the","","","","","",""],
["","","","cookies thing?","","","","","",""],
["","natalie","","the what thing?","","","","","",""],
["","you","","i rang the doorbell and you showed up and said you didn't want any cookies and then left??","","","","","",""],
["","","","i had to go through the back door","","","","","",""],
["","natalie","","i did???","","","","","",""],
["","","","oh my god i must have been sleepwalking i'm sorry LOL","","","","","",""],
["","you","","omg that's okay","","","","","",""],
["","","","it was funny","","","","","",""],
["","natalie","","you can tell i was sleepwalking because i would never turn down a cookie in real life","","","","","",""],
["","you","","lol","","","","","",""],
["natalie_intro_continue","","","so have you, uh, been here long?","","","","","",""],
["","natalie","","oh yeah, too long to count","","","","","",""],
["","","","i still have the books i checked out from oliver when i arrived... they're probably overdue by years","","","","","",""],
["","you","","oh yeah, he convinced me to loan a book too","","","","","",""],
["","natalie","","you too??","","","","","",""],
["","","","that boy never changes lol","","","","","",""],
["","you","","lol","","","","","",""],
["","natalie","","i really should return those books, come to think of it","","","","","",""],
["","you","","do you want me to take them for you?","","","","","",""],
["","","","all i'm doing is wandering around aimlessly anyway","","","","","",""],
["","natalie","","oh heck that would be awesome","","","","","",""],
["","","","i'm glad i'm not a-[i]loan[/i] in this","","","","","",""],
["","you","","haha","","","","","",""],
["","","","dw i'll make sure to [i]book[/i] it to the library","","","","","",""],
["","natalie","","i'm sure oliver will be e-[i]late[/i]-ed to have them back","","","","","",""],
["","you","","i heard the library's good for [i]circulation[/i]","","","","","",""],
["","natalie","","oh, i think they [i]cover[/i]-ed that in the newspaper","","","","","",""],
["","you","","newspaper? more like... news-[i]paper[/i]","","","","","",""],
["","natalie","","pfft","","","","","",""],
["","you","","ok that one sucked","","","","","",""],
["","natalie","","they can't all be winners","","","","","",""],
["","","","here's the books, anyway","_inv_natalies_books","","","","",""],
["","","","tell oliver i thought they were good!","","","","","",""],
["","you","","weren't you using them to hold up that table?","","","","","",""],
["","natalie","","yeahhhh","","blackout",['natalie_intro4', 'natalie_intro5'],"","",""],
["natalie_intro4","natalie","","but he doesn't need to know that","","","","","",""],
["","you","","oh, by the way, can i borrow one of ur candles?","","","","","",""],
["","natalie","","sure, what for?","","","","","",""],
["","you","","tori and i were messing with the electricity when the lights turned off","","","","","",""],
["","natalie","","heh, that must have been a nasty surpr-eyes","","","","","",""],
["","","","but no rush in turning the lights back on, alright?","","","","","",""],
["","","","the ambience is way better this way","","","","","",""],
["","you","","lol alright",[['_delay__inv_candle', true], ['_delay_saw_natalie_intro', true]],"","null","","",""],
["natalie_intro5","natalie","","but he doesn't need to know that","_delay_saw_natalie_intro","","null","","",""],
["natalie_default","natalie","natalie_neutral","oh hey, what's up?","","","","","",""],
["","","","","","","",['saw_natalie_intro and not returned_natalies_books', 'returned_natalies_books and not followed_up_on_natalies_books', '_inv_draw_a_paw', 'true', 'returned_draw_a_paw', 'true', 'true'],["(about the books)", "(about the books)", "(return the draw-a-paw)", "what's up?", "how's the drawing?", "thoughts about living?", "i like your attic"],["natalie_books", "natalie_books2", "natalie_draw_a_paw", "natalie_wasup", "natalie_drawing", "natalie_living", "natalie_attic"]],
["natalie_wasup","","","_pass","","natalie_talked_about_luna_moths",['natalie_wasup_all', 'natalie_wasup_most'],"","",""],
["natalie_wasup_all","you","","what's up?","","",['_rand', 'natalie_wasup1', 'natalie_wasup2', 'natalie_wasup3', 'natalie_wasup4', 'natalie_wasup5', 'natalie_wasup6', 'natalie_wasup7', 'natalie_wasup8', 'natalie_wasup9', 'natalie_wasup10', 'natalie_wasup11', 'natalie_wasup12', 'natalie_wasup13', 'natalie_wasup14', 'natalie_wasup15', 'natalie_wasup16', 'natalie_wasup17', 'natalie_wasup18', 'natalie_wasup19', 'natalie_wasup20', 'natalie_wasup21', 'natalie_wasup22'],"","",""],
["natalie_wasup_most","you","","what's up?","","",['_rand', 'natalie_wasup1', 'natalie_wasup2', 'natalie_wasup3', 'natalie_wasup4', 'natalie_wasup5', 'natalie_wasup6', 'natalie_wasup7', 'natalie_wasup9', 'natalie_wasup10', 'natalie_wasup11', 'natalie_wasup12', 'natalie_wasup13', 'natalie_wasup14', 'natalie_wasup15', 'natalie_wasup16', 'natalie_wasup17', 'natalie_wasup18', 'natalie_wasup19', 'natalie_wasup20', 'natalie_wasup21', 'natalie_wasup22'],"","",""],
["natalie_wasup1","natalie","","do you think all dogs go to heaven?","","","","","",""],
["","","","","","","","",['yes', 'no'],['natalie_wasup1a', 'natalie_wasup1b']],
["natalie_wasup1a","you","","yeah","","","natalie_wasup1c","","",""],
["natalie_wasup1b","you","","not all of them","","","","","",""],
["natalie_wasup1c","natalie","","what about my pug, jimmy?","","","","","",""],
["","you","","um","","","","","",""],
["","","","was he well behaved?","","","","","",""],
["","natalie","","he pooped on all of our couches at least once.","","","","","",""],
["","you","","hmm...","","","","","",""],
["","","","hard to say.","","","","","",""],
["","natalie","","maybe he's in dog purgatory.","","","","","",""],
["","you","","lol maybe","","","","","",""],
["","","","wait","","","","","",""],
["","","","PUGATORY","","","","","",""],
["","natalie","","PUGATORY!!!","","","null","","",""],
["natalie_wasup2","natalie","","i said it first","","","","","",""],
["","you","","oh yeah, sorry","","","","","",""],
["","","","not much, i guess","","","","","",""],
["","natalie","","cool cool","","","null","","",""],
["natalie_wasup3","natalie","","just nappin","","","","","",""],
["","you","","good 4 u","","","null","","",""],
["natalie_wasup4","natalie","","once i got into an argument with a bag of fertilizer","","","","","",""],
["","","","i told it that it's full of shit","","","","","",""],
["","you","","nice","","","null","","",""],
["natalie_wasup5","natalie","","recently my company started marketing to babies","","","","","",""],
["","","","bc they're the fastest growing demographic!","","","","","",""],
["","you","","lol","","","null","","",""],
["natalie_wasup6","natalie","","i tried to tell a joke about moths being attracted to light bulbs","","","","","",""],
["","","","but i was accused of making [i]light[/i] of the situation","","","","","",""],
["","you","","haha","","","null","","",""],
["natalie_wasup7","natalie","","did you know luna moths don't have mouths?","","","","","",""],
["","you","","really? how do they eat?","","","","","",""],
["","natalie","","they don't, they just die after a few days","","","","","",""],
["","","","i don't have a joke prepared for this one i just remembered and thought it was neat","","","","","",""],
["","you","","that is pretty neat","natalie_talked_about_luna_moths","","null","","",""],
["natalie_wasup8","natalie","","oh oh oh i thought of a joke about that luna moth thing!","","","","","",""],
["","you","","oh yeah? hit me","","","","","",""],
["","natalie","","did you know luna moths don't have mouths?","","","","","",""],
["","","","i know, i was speechless too","","","","","",""],
["","you","","niiiiice","","","null","","",""],
["natalie_wasup9","natalie","","have you seen all the broken glass downstairs?","","","","","",""],
["","","","we really need to [i]crack[/i] down on the cleaning department","","","","","",""],
["","you","","lol","","","null","","",""],
["natalie_wasup10","natalie","","did you ever want to be an astronaut?","","","","","",""],
["","","","","","","","",['yeah', 'nope'],['natalie_wasup10a', 'natalie_wasup10b']],
["natalie_wasup10a","you","","yeah, did you too?","","","","","",""],
["","natalie","","oh god yeah ","","","","","",""],
["","","","i had a huge astronaut phase","","","","","",""],
["","","","you think we could still be astronauts?","","","","","",""],
["","","","like skeleton astronauts or something?","","","natalie_wasup10c","","",""],
["natalie_wasup10b","you","","not really","","","","","",""],
["","natalie","","man, i had a huge astronaut phase","","","","","",""],
["","","","you think i could still be an astronaut?","","","","","",""],
["","","","like a skeleton astronaut or something?","","","","","",""],
["natalie_wasup10c","you","","maybe","","","","","",""],
["","natalie","","god i hope so","","","null","","",""],
["natalie_wasup11","natalie","","did you know my dad worked at the largest liquor store in the world?","","","","","",""],
["","you","","wow","","","","","",""],
["","","","did you get to drink lots of liquor?","","","","","",""],
["","natalie","","nah he left when i was 8","","","","","",""],
["","you","","oh","","","","","",""],
["","","","sorry","","","","","",""],
["","natalie","","lol it's ok","","","null","","",""],
["natalie_wasup12","natalie","","i wish they showed you stats when you died","","","","","",""],
["","","","i was aiming for a world record in \"percentage of life spent sleeping\"","","","","","",""],
["","you","","what was your score?","","","","","",""],
["","natalie","","40% at least. maybe 50","","","null","","",""],
["natalie_wasup13","natalie","","AAH!","","","","","",""],
["","you","","what? what's wrong?","","","","","",""],
["","natalie","","nothing, i just thought about star-nosed moles","","","","","",""],
["","you","","what are those...?","","","","","",""],
["","natalie","","trust me, you don't want to know","","","null","","",""],
["natalie_wasup14","natalie","","[i]achoo![/i]","","","","","",""],
["","you","","bless you","","","","","",""],
["","natalie","","thanks","","","","","",""],
["","","","what were we talking about?","","","","","",""],
["","you","","uhhh idk","","","","","",""],
["","natalie","","me neither","","","null","","",""],
["natalie_wasup15","natalie","","i tried to pay attention to the astronomy lecture","","","","","",""],
["","","","but i ended up spacing out","","","","","",""],
["","you","","nice","","","null","","",""],
["natalie_wasup16","natalie","","did any other new people show up while i was sleeping?","","","","","",""],
["","you","","uhh, i don't think so","","","","","",""],
["","natalie","","there were seven of us when i last checked","","","","","",""],
["","","","sean, elijah, numa, oliver, kyungsoon, tori...","","","","","",""],
["","","","wait who am i missing","","","","","",""],
["","you","","yourself?","","","","","",""],
["","natalie","","OH YEAH i forgot to count myself","","","","","",""],
["","","","lol","","","","","",""],
["","you","","lol","","","null","","",""],
["natalie_wasup17","natalie","","*yaaaaaaaaaaaaaaawn*","","","","","",""],
["","","","oh god that was a big yawn","","","","","",""],
["","you","","impressive!","","","","","",""],
["","natalie","","anyway sorry what was the question?","","","","","",""],
["","you","","i said \"what's up\"","","","","","",""],
["","natalie","","oh not much","","","null","","",""],
["natalie_wasup18","natalie","","thinking about chinchillas","","","","","",""],
["","","","they're so... roumd","","","","","",""],
["","you","","too bad we don't have any a-[i]round[/i] here","","","","","",""],
["","natalie","","god you said it","","","null","","",""],
["natalie_wasup19","natalie","","spaaaaaaaaaaaaaace","","","","","",""],
["","you","","true","","","null","","",""],
["natalie_wasup20","natalie","","just had the craziest dream","","","","","",""],
["","you","","about what?","","","","","",""],
["","natalie","","no clue i forgot","","","null","","",""],
["natalie_wasup21","natalie","","just had a dream that purrgatory was full of snakes and it was called snurrgatory","","","","","",""],
["","you","","i don't even know what to say about that","","","null","","",""],
["natalie_wasup22","natalie","","wish there were color pencils in purrgatory","","","","","",""],
["","","","or colors in general","","","","","",""],
["","you","","if only","","","null","","",""],
["natalie_living","you","","thoughts about living?","","","","","",""],
["","natalie","","i liked it!","","","","","",""],
["","","","8 out of 10","","","","","",""],
["","you","","what did you do for a living?","","","","","",""],
["","natalie","","janitor. denver museum of nature and science ","","","","","",""],
["","you","","ooh, how was that?","","","","","",""],
["","natalie","","well","","","","","",""],
["","","","i worked overnight so i didn't have to talk to anyone","","","","","",""],
["","","","and i got into planetarium shows for free","","","","","",""],
["","","","so, can't complain","","","","","",""],
["","","","though that didn't stop my mom from complaining it's not a real job","","","","","",""],
["","you","","oof, that sucks","","","","","",""],
["","natalie","","any other questions?","","","","","",""],
["","you","","uh, sure, how about...","","","","","",""],
["","","","","","","","",['any regrets?', 'greatest accomplishment?', 'anything you miss?'],['natalie_living1', 'natalie_living2', 'natalie_living3']],
["natalie_living1","you","","any regrets?","","","","","",""],
["","natalie","","nope!","","","","","",""],
["","","","well, actually...","","","","","",""],
["","","","yeah, one","","","","","",""],
["","","","not finishing my webcomic ","","","","","",""],
["","you","","oh yeah?","","","","","",""],
["","natalie","","yeah... wasn't even halfway through","","","","","",""],
["","","","but oh well","","","","","",""],
["","","","what can you do?","","","","","",""],
["","you","","what was it about?","","","","","",""],
["","natalie","","oh, it was about, like, a moth that fights nightmares in the dreaming world","","","","","",""],
["","","","it's pretty awesome","","","","","",""],
["","you","","sounds like a [i]dream[/i] come true","","","","","",""],
["","natalie","","you heckin know it","","","null","","",""],
["natalie_living2","you","","greatest accomplishment?","","","","","",""],
["","natalie","","the time i fit 12 marshmallows into my mouth at once. ","","","","","",""],
["","","","next question","","","","","",""],
["","you","","holy crap","","","","","",""],
["","","","uhh","","","","","",""],
["","","","[i]how[/i] did you fit 12 marshmallows into your mouth?","","","","","",""],
["","natalie","","years of grueling training.","","","","","",""],
["","","","also i have a big mouth","","","null","","",""],
["natalie_living3","you","","anything you miss?","","","","","",""],
["","natalie","","oh totally","","","","","",""],
["","","","i miss my friends, my family, my dog","","","","","",""],
["","","","all the usual suspects","","","","","",""],
["","you","","aw, i'm sorry","","","","","",""],
["","natalie","","it's alright.","","","","","",""],
["","","","you know what i really miss?","","","","","",""],
["","","","oreos.","","","","","",""],
["","you","","oh yeah","","","","","",""],
["","","","oreos are good","","","","","",""],
["","natalie","","i would kill for an oreo right now","","","","","",""],
["","","","not you!","","","","","",""],
["","","","but i would kill [i]someone[/i]","","","","","",""],
["","","","they better watch their back","","","","","",""],
["","you","","o-o","","","null","","",""],
["natalie_attic","you","","i like your attic!","","","","","",""],
["","natalie","","thanks!","","","","","",""],
["","","","i figured if i was going to be stuck here i might as well be comfy","","","","","",""],
["","you","","what's with the candles?","","","","","",""],
["","natalie","","oh, i just think they smell nice","","","","","",""],
["","you","","i guess you could say they're [i]wick[/i]-ed?","","","","","",""],
["","natalie","","heh","","","","","",""],
["","","","i'm gonna have to remember that one","","","","","",""],
["","you","","by the way, did you draw all these yourself?","","","","","",""],
["","natalie","","mhm!","","","","","",""],
["","you","","they're very good!","","","","","",""],
["","natalie","","thanks!","","returned_draw_a_paw",['null', 'natalie_attic1'],"","",""],
["natalie_attic1","","","i was going to do more, but we started running out of paper","","","","","",""],
["","","","so then i started drawing on my draw-a-paw","","","","","",""],
["","","","but then i lost that too","","","","","",""],
["","you","","aw, that sucks","","","","","",""],
["","natalie","","yeah, it's a real [i]draw[/i]-back","","","","","",""],
["","","","but hey, being unable to draw isn't so bad!","","","","","",""],
["","","","means i have more time to sleep","","","null","","",""],
["natalie_books","you","","uh, what did you want me to do with the books again?","","","","","",""],
["","natalie","","just return them to oliver, if you don't mind","","","","","",""],
["","you","","gotcha, sorry","","","","","",""],
["","natalie","","it's okay, i'm super forgetful too","","","","","",""],
["","","","btw what was your name again?","","","","","",""],
["","you","","it's {player}","","","","","",""],
["","natalie","","ok cool cool","","","null","","",""],
["natalie_books2","you","","i gave oliver the books!","followed_up_on_natalies_books","","","","",""],
["","natalie","","sweeeet, thank you","","","","","",""],
["","","","i owe you one","","","","","",""],
["","","","he didn't give me a late fee, did he?","","","","","",""],
["","you","","no, but he looked sad","","","","","",""],
["","natalie","","aw ):","","","","","",""],
["","","","poor guy just wants people to read his books","","","","","",""],
["","you","","i would, if it wasn't just meows...","","","","","",""],
["","natalie","","yeah, me too","","","","","",""],
["","","","well, i haven't read a book since middle school, so maybe not","","","","","",""],
["","","","but i would look at the pictures!","","","null","","",""],
["natalie_draw_a_paw","you","","hey, is this yours?",[['_inv_draw_a_paw', false]],"","","","",""],
["","natalie","","NO WAY","","","","","",""],
["","","","you found my draw-a-paw!!","","","","","",""],
["","","","where the heck was it?","","","","","",""],
["","you","","in the meowseum, by the giant floating cat statue...?","","","","","",""],
["","natalie","","ooooh, that explains it","","","","","",""],
["","","","i must have left it there that one time elijah and sean locked me into the meowseum","","","","","",""],
["","","","anyway, thank you so much!! you're a real pal!","","","","","",""],
["","you","","you're welcome!","","","","","",""],
["","natalie","","if i can ever return the favor, just let me know","","","","","",""],
["","","","least i can do is lend a 'paw ;)","","","","","",""],
["","you","","heh thanks","","","","","",""],
["","","","i'll let you know for sure","_delay_returned_draw_a_paw","","null","","",""],
["natalie_drawing","","","_pass","",['natalie_finished_drawing3', 'natalie_finished_drawing2', 'natalie_finished_drawing1'],['natalie_drawing4', 'natalie_drawing3', 'natalie_drawing2', 'natalie_drawing1'],"","",""],
["natalie_drawing1","","","_pass","","saw_natalie_drawing1",['natalie_drawing1b', 'natalie_drawing1a'],"","",""],
["natalie_drawing1a","you","","how's the drawing?","saw_natalie_drawing1","","","","",""],
["","natalie","","it's going great","natalie_drawing_timer1","","","","",""],
["","","","i haven't drawn anything in, like, ages","","","","","",""],
["","","","i'm doing a little robot dude rn","","","","","",""],
["","you","","ooh, cool","","","","","",""],
["","","","can i see?","","","","","",""],
["","natalie","","uhh, i'll show you when i'm done","","","","","",""],
["","","","don't wanna [i]bot[/i]-ch this one up yaknow","","","","","",""],
["","you","","nice","","","","","",""],
["","natalie","","but yeah just gimme a little bit","","","","","",""],
["","you","","ok!","","","null","","",""],
["natalie_drawing1b","you","","how's the little robot dude?","","","","","",""],
["","natalie","","still working on it!","","","null","","",""],
["natalie_drawing2","","","_pass","","saw_natalie_drawing2",['natalie_drawing2b', 'natalie_drawing2a'],"","",""],
["natalie_drawing2a","you","","how's the little robot dude?","saw_natalie_drawing2","","","","",""],
["","natalie","","oh, i ended up scrapping him","natalie_drawing_timer2","","","","",""],
["","you","","aw, rip","","","","","",""],
["","natalie","","that's just how the cookie crumbles yaknow","","","","","",""],
["","","","but it's ok because i'm drawing something WAY better now","","","","","",""],
["","you","","what is it?","","","","","",""],
["","natalie","","imagine this:","","","","","",""],
["","","","mushrooms. but big","","","","","",""],
["","you","","oo","","","","","",""],
["","","","how big?","","","","","",""],
["","natalie","","SO big","","","","","",""],
["","","","just wait and see","","","","","",""],
["","","","it'll be awesome","","","","","",""],
["","you","","alright!","","","null","","",""],
["natalie_drawing2b","you","","how are the big mushrooms looking?","","","","","",""],
["","natalie","","they're SO big dude. these mushrooms are straight GIGANTIC.","","","","","",""],
["","you","","wow","","","","","",""],
["","natalie","","just give me a liiiittle more time","","","null","","",""],
["natalie_drawing3","","","_pass","","saw_natalie_drawing3",['natalie_drawing3b', 'natalie_drawing3a'],"","",""],
["natalie_drawing3a","you","","how are the big mushrooms looking?","saw_natalie_drawing3","","","","",""],
["","natalie","","okay i know what you're going to say","natalie_drawing_timer3","","","","",""],
["","","","but","","","","","",""],
["","","","i gave up on the mushrooms, and i'm drawing something EVEN BETTER now","","","","","",""],
["","you","","oh???","","","","","",""],
["","natalie","","it's one of my original characters","","","","","",""],
["","","","whenever i feel uninspired, i always go back to him!","","","","","",""],
["","","","so he's like a dog, right?","","","","","",""],
["","","","but his fur is rainbow colored","","","","","",""],
["","","","and also he rides a skateboard, and vapes","","","","","",""],
["","you","","that sounds like literally the coolest thing on the planet","","","","","",""],
["","natalie","","RIGHT??","","","null","","",""],
["natalie_drawing3b","you","","how's the rainbow dog?","","","","","",""],
["","natalie","","i'm so excited. it's going to be awesome","","","","","",""],
["","you","","can't wait!","","","null","","",""],
["natalie_drawing4","you","","how's the rainbow dog?","","","","","",""],
["","natalie","","uhhhh","","","","","",""],
["","you","","did you erase it again","","","","","",""],
["","natalie","","yeaaaaaaaaaah idk","","","","","",""],
["","","","i'm not really feeling it anymore","","","","","",""],
["","","","kinda just want to sleep","","","","","",""],
["","you","","that's okay!","","","","","",""],
["","","","you don't have to draw if you're not feeling like it","","","","","",""],
["","natalie","","mhm","","","","","",""],
["","","","you know, that's how the cookie crumbles and all that","","","","","",""],
["","","","i guess","","","","","",""],
["","you","","yep","","","","","",""],
["","natalie","","we're just chilling","","","","","",""],
["","you","","just vibing","","","","","",""],
["","natalie","","yep","","","","","",""],
["","","","...","","","","","",""],
["","","","","","","","",['are you okay?', 'sounds like art block'],['natalie_drawing4a', 'natalie_drawing4b']],
["natalie_drawing4a","you","","are you okay?","","","","","",""],
["","","","you seem kinda blue","","","","","",""],
["","natalie","","nice one","","","","","",""],
["","you","","wait, i didn't mean it that way LOL","","","","","",""],
["","natalie","","lol it's okay","","","natalie_drawing4c","","",""],
["natalie_drawing4b","you","","sounds like you have art block, tbh","","","","","",""],
["","natalie","","yeah, probably","","","","","",""],
["","","","art block's a bitch","","","","","",""],
["","you","","mhm","","","","","",""],
["","natalie","","though usually it doesn't last so freaking LONG","","","","","",""],
["natalie_drawing4c","","","i guess i'm just feeling a little demotivated","","","","","",""],
["","","","i don't feel like doing anything at all","","","","","",""],
["","you","","i feel you","","","","","",""],
["","","","just purrgatory things","","","","","",""],
["","natalie","","yeah, just purrgatory things.","","","","","",""],
["","you","","is there anything i can do to help?","","","","","",""],
["","natalie","","nahhhh, it's okay","","","","","",""],
["","","","i appreciate it, though!","","","","","",""],
["","","","i think maybe i'll just go to sleep again.","","","","","",""],
["","","","unless you have a better idea","","","","","",""],
["","you","","uhhhh","","","","","",""],
["","","","what if we...","","","","","",""],
["natalie_activity","","","","","","",['not natalie_tried_activity1', 'not natalie_tried_activity2', 'not natalie_tried_activity3', 'not natalie_tried_activity4'],['pet the cat?', 'rang the bell?', 'took a walk?', 'painted a mural?'],['natalie_activity1', 'natalie_activity2', 'natalie_activity3', 'natalie_activity4']],
["natalie_activity1","you","","what if we went to the commons and pet the cat?","natalie_tried_activity1","","","","",""],
["","natalie","","ehh, no thanks","","","","","",""],
["","","","i'm allergic to cats","","","","","",""],
["","you","","and they put you in purrgatory?","","","","","",""],
["","","","oh my god that's so cruel","","","","","",""],
["","natalie","","right???","","","natalie_activity","","",""],
["natalie_activity2","you","","what if we went and rang that giant bell?","natalie_tried_activity2","","","","",""],
["","natalie","","oh, sean and i did that a while ago","","","","","",""],
["","","","tori and oliver got SUPER mad at us","","","","","",""],
["","you","","oh, whoops","","","","","",""],
["","natalie","","nah it was totally worth it","","","natalie_activity","","",""],
["","","","don't want to bother them again, though","","","","","",""],
["","you","","yeah, that's fair","","","","","",""],
["natalie_activity3","you","","what if we took a walk in the park?","natalie_tried_activity3","","","","",""],
["","natalie","","ugh, no one told me the afterlife would involve exercise","","","","","",""],
["","","","mostly kidding","","","","","",""],
["","","","a walk sounds nice but i dont think i'm up to it right now","","","","","",""],
["","you","","ah, ok","","","","","",""],
["","","","then what if we...","","","natalie_activity","","",""],
["natalie_activity4","you","","what if we painted a mural?","natalie_tried_activity4","","","","",""],
["","","","like that one in the catnip garden","","","","","",""],
["","natalie","","hmm... that could be fun","","","","","",""],
["","","","i painted that one, btw","","","","","",""],
["","you","","oh really??","","","","","",""],
["","natalie","","yeah numa said it looked so boring so i painted some weather on the walls","","","","","",""],
["","you","","that's sick!!","","","","","",""],
["","","","do you want to make another one?","","","","","",""],
["","natalie","","hmmmmmmm","","","","","",""],
["","you","","hmm?","","","","","",""],
["","natalie","","HMMMMMM","","","","","",""],
["","","","ok, let's do it!","","","","","",""],
["","you","","woohoo!!","","","","","",""],
["","natalie","","i'll grab my art supplies!","","","","","",""],
["","","","where to??","","","","","",""],
["","you","","uhhhh i don't know","","","","","",""],
["","natalie","","oh, it's fine, we'll figure it out as we go","","","","","",""],
["","you","","ok!","","","","","",""],
["","natalie","","let's go!!","","","","","",""],
["","you","","yeah!!!!","","","","","",""],
["","natalie","","yes!!!!","","","","","",""],
["","natalie","","wow, it's been a while since i've been out of the attic","_goto_house5","","","","",""],
["","","","what year is it?","","","","","",""],
["","you","","uh, 2020, i think","","","","","",""],
["","natalie","","heck, i died in 2015","","","","","",""],
["","you","","wow","","","","","",""],
["","natalie","","time flies when you're having fun!","","","","","",""],
["","you","","so, is this, like, your house?","_goto_house4","","","","",""],
["","natalie","","nah, it was here when i got here","","","","","",""],
["","you","","did you draw that sign?","","","","","",""],
["","natalie","","oh god no","","","","","",""],
["","","","i tried to take it down once but it kept reappearing when i slept","","","","","",""],
["","you","","that's a little concerning...","","","","","",""],
["","you","","so, where should we go?","_goto_hallway15","","","","",""],
["","natalie","","you know that long hallway outside of the commons?","","","","","",""],
["","","","probably lots of good walls to draw on there","","","","","",""],
["","you","","bet!","","","","","",""],
["","_none","","you eventually make your way to the hallway.","_goto_hallway2","","","","",""],
["","natalie","","oh, this is PURRFECT","","","","","",""],
["","","","i can't wait to graffiti this up","","","","","",""],
["","you","","wait, are we doing a mural or a graffiti?","","","","","",""],
["","natalie","","depends. do you think this is illegal?","","","","","",""],
["","","","","","","","",['yes', 'no'],['natalie_mural1', 'natalie_mural2']],
["natalie_mural1","you","","probably","","","","","",""],
["","natalie","","then it's graffiti.","","","natalie_mural3","","",""],
["natalie_mural2","you","","i don't think purrgatory has laws?","","","","","",""],
["","natalie","","then it's a mural.","","","","","",""],
["natalie_mural3","you","","cool","","","","","",""],
["","natalie","","ok! i'm gonna do it!","","","","","",""],
["","you","","alright!","","","","","",""],
["","natalie","","i'm gonna draw something!!","","","","","",""],
["","you ","","go for it!!","","","","","",""],
["","natalie","","...","","","","","",""],
["","you","","...","","","","","",""],
["","natalie","","...","","","","","",""],
["","you","","take ur time","","","","","",""],
["","natalie","","AGH","","","","","",""],
["","","","i can't do it, dude","","","","","",""],
["","","","i still have art block","","","","","",""],
["","you","","just draw anything, it doesn't matter!","","","","","",""],
["","natalie","","like what?","","","","","",""],
["","you","","like uhhh","","","","","",""],
["","","","","","","","",['a cat', 'a dragon', 'spongebob'],['natalie_mural4a', 'natalie_mural4b', 'natalie_mural4c']],
["natalie_mural4a","you","","a cat!","","","","","",""],
["","natalie","","okay, i'll draw a cat","","","","","",""],
["","","","i'm doing it for real!!!!","","","","","",""],
["","you","","ok!","","","","","",""],
["","natalie","","aaaaaaaaaaa","","","","","",""],
["","","","aaaaaaaaaaaaaaaaaaaaaaaaa!!!","","","","","",""],
["","","","ok done","natalie_chose_cat","","","","",""],
["","you","","nice!","","","","","",""],
["","","","that's a cute cat!","","","","","",""],
["","natalie","","thanks!","","","","","",""],
["","you","","why is it saying fuck?","","","","","",""],
["","natalie","","because it's rude","","","","","",""],
["","","","it did hard time in al-cat-raz and came out a changed feline","","","","","",""],
["","","","no longer trusts anything but his own four paws","","","","","",""],
["","you","","o i see","","","natalie_mural4d","","",""],
["natalie_mural4b","you","","a dragon!","","","","","",""],
["","natalie","","okay, i'll draw a dragon","","","","","",""],
["","","","i'm doing it for real!!!!","","","","","",""],
["","you","","ok!","","","","","",""],
["","natalie","","aaaaaaaaaaa","","","","","",""],
["","","","aaaaaaaaaaaaaaaaaaaaaaaaa!!!","","","","","",""],
["","","","ok done","natalie_chose_dragon","","","","",""],
["","you","","nice!!","","","","","",""],
["","","","that's a cute dragon!","","","","","",""],
["","natalie","","thanks!","","","","","",""],
["","you","","why is it saying books?","","","","","",""],
["","natalie","","because it's a book wyrm","","","","","",""],
["","","","his only love in life is books and he hoards them in his lib-roar-y","","","","","",""],
["","","","but he's doomed to tragedy because he keeps setting his books on fire","","","","","",""],
["","you","","o i see","","","natalie_mural4d","","",""],
["natalie_mural4c","you","","spongebob!","","","","","",""],
["","natalie","","uhhhh okay i'll draw spongebob i guess","","","","","",""],
["","","","i'm doing it for real!!!!","","","","","",""],
["","you","","ok!","","","","","",""],
["","natalie","","aaaaaaaaaaa","","","","","",""],
["","","","aaaaaaaaaaaaaaaaaaaaaaaaa!!!","","","","","",""],
["","","","ok done","natalie_chose_spongebob","","","","",""],
["","you","","nice!!","","","","","",""],
["","","","that... is a surprisingly accurate spongebob","","","","","",""],
["","natalie","","i watched a lot of spongebob","","","","","",""],
["","you","","why is he saying pants?","","","","","",""],
["","natalie","","uhh","","","","","",""],
["","","","i don't know","","","","","",""],
["","","","it's the first word that came to mind","","","","","",""],
["","you","","o i see","","","","","",""],
["natalie_mural4d","natalie","","do you want to draw something?","","","","","",""],
["","you","","uhh, sure!","","","","","",""],
["","natalie","","here, take my pencils","","","","","",""],
["","you","","thanks","","","","","",""],
["","","","here goes nothing...","_delay_start_drawing","","null","","",""],
["natalie_after_drawing","natalie","natalie_neutral","heck, nice work!","","","","","",""],
["","","","","","","","",['thanks!', 'it\'s terrible'],['natalie_mural5', 'natalie_mural6']],
["natalie_mural5","you","","thanks!","","","","","",""],
["","","","pretty happy with that, actually","","","","","",""],
["","natalie","","move over, picasso, there's a new artist in town","","","","","",""],
["","you","","lol","","","natalie_mural7","","",""],
["natalie_mural6","you","","are you kidding?","","","","","",""],
["","","","it's terrible","","","","","",""],
["","natalie","","awww, it's not that bad!","","","","","",""],
["","","","it goes well with the \"fuck\"","","","","","",""],
["","you","","that it does","","","","","",""],
["natalie_mural7","","","_pass","","met_tori",['natalie_mural7_normal', 'natalie_mural7_alt'],"","",""],
["natalie_mural7_alt","???",['tori_neutral', 'natalie_neutral'],"natalie, what are you doing?","","","","","",""],
["","","","wait a second. who's this?","","","","","",""],
["","you","","i'm {player}!","","","","","",""],
["","???","","hmm, interesting.","","","","","",""],
["","","","i've been expecting you.","","","","","",""],
["","natalie","","that's not ominous at all","","","","","",""],
["","???","","it's not ominous! just a fact!","","","","","",""],
["","tori","","i'm tori. i look forward to getting to know you better.","","","","","",""],
["","","","","","","","",['same here', 'that still sounds ominous', 'cool'],['natalie_mural7_alt_a', 'natalie_mural7_alt_b', 'natalie_mural7_alt_c']],
["natalie_mural7_alt_a","you","","um, same here!","","","","","",""],
["","natalie","","come on guys, it's not a business meeting","","","","","",""],
["","tori","","just being polite.","","","natalie_mural7_alt_d","","",""],
["natalie_mural7_alt_b","you","","that still sounds kind of ominous...","","","","","",""],
["","_none","","tori rolls her eyes.","","","","","",""],
["","tori","","fine, you got me, i'm trying to lure you into my lair so i can eat you whole.","","","","","",""],
["","natalie","","i KNEW it!","","","natalie_mural7_alt_d","","",""],
["natalie_mural7_alt_c","you","","cool","","","","","",""],
["","tori","","cool?","","","","","",""],
["","you","","yeah that's cool","","","","","",""],
["","tori","","cool","","","","","",""],
["natalie_mural7_alt_d","tori","","anyway, i am curious...","","","","","",""],
["","","","what inspired you to start marking up the walls?","","","natalie_mural7_combined","","",""],
["natalie_mural7_normal","tori",['tori_neutral', 'natalie_neutral'],"what are you hooligans doing?","","","","","",""],
["","natalie","","hey tori","","","natalie_mural7_combined","","",""],
["natalie_mural7_combined","natalie","","just adding a little splash of color to the hallway!","","","","","",""],
["","","","metaphorically","","","","","",""],
["","tori","","i see.","","","","","",""],
["","","","no offense, but is it a good idea to scribble all over the place we'll be stuck in for eternity?","","","","","",""],
["","natalie","","aww, we're just having a little bit of fun!","","","","","",""],
["","","","do you want to draw anything?","","","","","",""],
["","tori","","i'll pass this time.","",['natalie_chose_cat', 'natalie_chose_dragon'],['natalie_mural8', 'natalie_mural9', 'natalie_mural10'],"","",""],
["natalie_mural8","you","","do you like the cat?","","","","","",""],
["","tori","","i do like the cat, actually.","","","","","",""],
["","","","why is it saying fuck?","","","","","",""],
["","natalie","","long story.","","","natalie_mural11","","",""],
["natalie_mural9","you","","do you like the dragon?","","","","","",""],
["","tori","","i do like the dragon, actually.","","","","","",""],
["","","","why is it saying books?","","","","","",""],
["","natalie","","long story.","","","natalie_mural11","","",""],
["natalie_mural10","you","","do you like the spongebob?","","","","","",""],
["","tori","","i do like the spongebob, actually.","","","","","",""],
["","","","why is he saying pants?","","","","","",""],
["","natalie","","long story.","","","natalie_mural11","","",""],
["natalie_mural11","tori","","you know, your art style kind of reminds me of this artist i used to follow.","","","","","",""],
["","","","i think her name was uh...","","","","","",""],
["","","","pocketnat?","","","","","",""],
["","natalie","","sorry what","","","","","",""],
["","tori","","pock-et-nat. like a pants pocket, and then nat, like your name.","","","","","",""],
["","natalie","","w","","","","","",""],
["","tori","","yeah, she ran this webcomic called nocturnal, but she just disappeared one day. social media, everything.","","","","","",""],
["","","","natalie, are you okay?","","","","","",""],
["","you","","uh, i think--","","","","","",""],
["","natalie","","you read nocturnal??","","","","","",""],
["","tori","","oh, are you familiar with it?","","","","","",""],
["","natalie","","you -- you could say that, yeah","","","","","",""],
["","tori","","i'll admit, i didn't have much free time to spend on the internet when i was alive, but i always checked the weekly updates. the art was fantastic.","","","","","",""],
["","","","after pocket disappeared, there were a couple of continuation comics made by fans... i'm not sure if you were around for that, since you died before me.","","","","","",""],
["","","","come to think of it, you died around the same time pocket disappeared. so i guess you wouldn't have been.","","","","","",""],
["","natalie","","hhh","","","","","",""],
["","tori","","i'm sorry, is it just me, or is this conversation sort of one-sided...?","","","","","",""],
["","natalie","","me","","","","","",""],
["","","","it me","","","","","",""],
["","","","me pocket","","","","","",""],
["","","","i mean i'm pocket","","","","","",""],
["","tori","","...sorry?","","","","","",""],
["","natalie","","IM POCKET ITS ME","","","","","",""],
["","","","I MADE NOCTURNAL","","","","","",""],
["","tori","","no way","","","","","",""],
["","natalie","","YES WAY","","","","","",""],
["","you","","wait... so you two knew each other?","","","","","",""],
["","natalie","","this is incredible, i've never met a fan before!!","","","","","",""],
["","","","you are, right? a fan?","","","","","",""],
["","tori","","i would describe myself that way, yes","","","","","",""],
["","natalie","","that's so cool!!","","","","","",""],
["","tori","","if you really are pocketnat. i have to know.","","","","","",""],
["","","","do edvard and twist ever get together??","","","","","",""],
["","natalie","","well, DUH","","","","","",""],
["","","","the subtext is ALL OVER chapter 13","","","","","",""],
["","tori","","I KNEW IT.","","","","","",""],
["","","","gosh, i remember i used to read so much fanfiction about the abyss world...","","","","","",""],
["","you","","wow, this sure is crazy...","","","","","",""],
["","natalie","","the abyss world?? people liked that??","","","","","",""],
["","tori","","oh the fandom could not WAIT to get their twisted little hands on that","","","","","",""],
["","","","there's this one where sofia becomes a mech pilot--","","","","","",""],
["","you","","i think i'm just gonna... go...","","","","","",""],
["","natalie","","you know, that's surprisingly similar to something i was drafting for arc 2, though instead of sofia, it would have been rune...","","","","","",""],
["","tori","","TELL ME. NOW.","natalie_tori_talking_timer","","","","",""],
["","_none","","you quietly sidle away from the conversation. they don't seem to notice.","_delay_natalie_completed_mural","","null","","",""],
["natalie_and_tori","natalie",['tori_neutral', 'natalie_neutral'],"and they were ROOMMATES","","","","","",""],
["","tori","","oh my god they were roommates","","","null","","",""],
["natalie_post","","","_pass","","natalie_quest_complete",['natalie_post_default', 'natalie_post1'],"","",""],
["natalie_post1","natalie","natalie_neutral","oh, hey {player}!","","","","","",""],
["","","","heck, i'm sorry i snubbed you earlier","","","","","",""],
["","","","i was just so excited to find out tori read nocturnal i forgot about everything else","","","","","",""],
["","you","","it's okay, heh","","","","","",""],
["","","","wow, it looks like you've been hard at work","","","","","",""],
["","natalie","","you bet!!","","","","","",""],
["","","","tori got me motivated to work on nocturnal again, so i started drawing chapter 19 based on what i remember from earth!","","","","","",""],
["","","","isn't that awesome??","","","","","",""],
["","you","","that's great!","","","","","",""],
["","","","getting over your art block [i]moth[/i] feel pretty good","","","","","",""],
["","natalie","","yeah i feel like i could draw ten robot dudes [i]antennae[/i] those rainbow dogs too","","","","","",""],
["","you","","guess all that art was [i]pen[/i]-t up inside you","","","","","",""],
["","natalie","","all you need sometimes is a push in the right [i]draw[/i]-rection","","","","","",""],
["","you","","you'd be [i]write[/i] about that","","","","","",""],
["","natalie","","before you learn to run you have to learn to [i]craw[/i]-l","","","","","",""],
["","you","","wait, what?","","","","","",""],
["","natalie","","craw, like crawfish?","","","","","",""],
["","","","because like","","","","","",""],
["","","","okay, see, in this chapter sofia goes into the dream of a fisherman","","","","","",""],
["","","","and he's dreaming about lobsters, right?","","","","","",""],
["","","","actually, first i should probably explain who the fisherman is--","","","","","",""],
["","","","well, you probably don't want to hear about all this, haha","","","","","",""],
["","you","","maybe some other time!","","","","","",""],
["","","","i'd love to read it when you're done","","","","","",""],
["","natalie","","oh, good!","","","","","",""],
["","","","then i'll have two fans :3","","","","","",""],
["","you","","you know it!","","","","","",""],
["","natalie","","anyway i'm gonna get back to work","","","","","",""],
["","you","","ok have fun!!","_delay__goto_flashback_natalie","","null","","",""],
["natalie_post2","natalie","natalie_neutral","{player}!!","_goto_attic","","","","",""],
["","","","oh my god, are you okay?","","","","","",""],
["","you","","urp","","","","","",""],
["","","","yeah i'm fine... just got dizzy all of a sudden","","","","","",""],
["","natalie","","dude you totally blacked out and fell over","","","","","",""],
["","","","are you sure you're okay?","","","","","",""],
["","you","","yes, i'm fine now","","","","","",""],
["","","","thanks though","","","","","",""],
["","natalie","","ok, good.","","","","","",""],
["","","","i was about to start doing cpr or something, geez","","","","","",""],
["","you","","i appreciate the thought","","","","","",""],
["","natalie","","you appreciate that i thought about saving your life?","","","","","",""],
["","you","","yep","","","","","",""],
["","natalie","","well you are welcome","","","null","","",""],
["natalie_post_default","natalie","natalie_neutral","what's up dude??","","","","","",""],
["","","","","","","",['saw_natalie_intro and not returned_natalies_books', 'returned_natalies_books and not followed_up_on_natalies_books', 'true', 'true', 'true'],["(about the books)", "(about the books)", "what's up?", "thoughts about living?", "so, nocturnal?"],["natalie_books", "natalie_books2", "natalie_wasup", "natalie_living", "natalie_nocturnal"]],
["natalie_nocturnal","you","","so, nocturnal, huh?","","","","","",""],
["","natalie","","nocturnal dude","","","","","",""],
["","","","my baby","","","","","",""],
["","","","","","","","",['your baby?', "how'd you get started?", "what's it about?"],['natalie_nocturnal1', 'natalie_nocturnal2', 'natalie_nocturnal3']],
["natalie_nocturnal1","you","","your baby?","","","","","",""],
["","natalie","","lmao, it's as close as i'm ever gonna get to having a baby","","","","","",""],
["","you","","ah, are you just not interested, or...?","","","","","",""],
["","natalie","","not interested, nope, no thank you","","","","","",""],
["","","","i don't do relationships at all, let alone starting a family","","","","","",""],
["","you","","o i see","","","","","",""],
["","natalie","","yep","","","","","",""],
["","","","didn't mean to be snappy or anything, it's just that my family was always on my case about that kind of stuff","","","","","",""],
["","you","","i totally understand","","","","","",""],
["","natalie","","thanks dude!","","","","","",""],
["","","","who needs a partner when you have dogs, anyway?","","","","","",""],
["","you","","true","","","null","","",""],
["natalie_nocturnal2","you","","so how'd you get into making a webcomic?","","","","","",""],
["","natalie","","was on my bucket list for a while, actually!","","","","","",""],
["","","","i mean, i always did art","","","","","",""],
["","","","but when i was 24 i was like, well, i'm well on my way to a midlife crisis, i might as well get started on something new","","","","","",""],
["","you","","ooh that's cool","","","","","",""],
["","natalie","","yep!","","","","","",""],
["","","","other things on my bucket list were to bowl a perfect game and run a d&d campaign","","","","","",""],
["","","","but i didn't have time to get around to that","","","","","",""],
["","you","","isn't bowling a perfect game, like, really rare?","","","","","",""],
["","natalie","","yeah, but i like to dream big!","","","","","",""],
["","","","i wanted to be an astronaut 'til i was like, 16","","","","","",""],
["","you","","nice","","","null","","",""],
["natalie_nocturnal3","you","","so like, what's the whole thing about?","","","","","",""],
["","natalie","","ohoho","","","","","",""],
["","","","are you sure you want to go down that rabbit hole?","","","","","",""],
["","you","","maaaaybe?","","","","","",""],
["","natalie","","heh, i'll try to keep it short","","","","","",""],
["","","","i could talk about it for DAYS if you let me","","","","","",""],
["","","","but uhhh basically it's about a moth who can go into other people's dreams","","","","","",""],
["","","","and there's this mysterious creature called the blight that's giving people nightmares, right?","","","","","",""],
["","","","well, turns out it's an alien from space","","","","","",""],
["","","","so the moth -- sofia -- and her friends, they form a team to fight the blight","","","","","",""],
["","","","and they call themselves the nocturnals","","","","","",""],
["","","","uhh with me so far?","","","","","",""],
["","","","","","","","",['(nods)', 'ooh, interesting'],['natalie_nocturnal3a', 'natalie_nocturnal3b']],
["natalie_nocturnal3a","you","","[i]nod nod[/i]","","","","","",""],
["","natalie","","heck, sorry i started rambling already","","","","","",""],
["","","","anyway that's the concept!","","","natalie_nocturnal4","","",""],
["natalie_nocturnal3b","you","","ooh, interesting","","","","","",""],
["","natalie","","you think so??","","","","","",""],
["","","","ok, so like","","","","","",""],
["","","","there was a big leak in the city which they go to investigate","","","","","",""],
["","","","i should explain, a leak is like when the blight leaks out into the real world?","","","","","",""],
["","","","but actually it's still a matter of perception, but -- never mind that","","","","","",""],
["","","","so that's where they meet rune--","","","","","",""],
["","","","wait, i didn't even introduce the others yet","","","","","",""],
["","","","so there's edvard, he's sofia's best friend","","","","","",""],
["","","","and then twist, they're sort of like a person trapped inside of a dream construct?","","","","","",""],
["","","","so, they all go to the city, but they get trapped inside a time trance because--","","","","","",""],
["","","","oh my gosh, i forgot about hazel!","","","","","",""],
["","","","","","","","",['(confused blink)', 'ok i\'m with you'],['natalie_nocturnal3c', 'natalie_nocturnal3d']],
["natalie_nocturnal3c","you","","[i]confused blinking[/i]","","","","","",""],
["","natalie","","oh, sorry, i lost you didn't i","","","","","",""],
["","","","i think that's a pretty good introduction, anyway, don't want to spoil too much","","","natalie_nocturnal4","","",""],
["natalie_nocturnal3d","you","","ok i'm still with you","","","","","",""],
["","natalie","","right so hazel is a librarian and she's like a mentor figure, she's the one who teaches them all how to use lucid dreaming powers to fight the blight","","","","","",""],
["","","","but in chapter 3, when they get trapped inside the hall of dreams--","","","","","",""],
["","","","wait, i almost told you a major spoiler","","","","","",""],
["","","","i mean, long story short is that hazel's dream avatar is in trouble and that's why sofia and co are forced into action","","","","","",""],
["","","","so you might be thinking. well, if hazel's body is still okay, then why don't they just do a daydream leap into her head and break her out that way?","","","","","",""],
["","","","well that's because twist already lost their seeing-eye stone in the blight factory!","","","","","",""],
["","","","and THAT'S why they need rune's help, which brings us back to the city","","","","","",""],
["","","","see, rune is a multi-dimensional being, so in order to interface with his dreamspace, the nocturnals have to wait for a time conjunction--","","","","","",""],
["","","","that's when one of rune's facets projects onto the three-dimensional world, by the way--","","","","","",""],
["","","","which is why the blight tearing holes in the hall of dreams actually worked against it in the long run!","","","","","",""],
["","","","now, this is where tony the hot dog seller comes in.","","","","","",""],
["","","","","","","","",['(polite cough)', 'the hot dog seller??'],['natalie_nocturnal3e', 'natalie_nocturnal3f']],
["natalie_nocturnal3e","you","","[i]polite cough[/i]","","","","","",""],
["","natalie","","oh god sorry, that was way more than i wanted to say","","","","","",""],
["","","","so uhhhh yeah! nocturnal!","","","natalie_nocturnal4","","",""],
["natalie_nocturnal3f","you","","the hot dog seller??","","","","","",""],
["","natalie","","YES it's the start of chapter 5 -- we just ended on a major cliffhanger, in the time trance, and chapter 8 opens with this major tangent","","","","","",""],
["","","","about this random character who we haven't seen from chapter 2, tony the hot dog seller","","","","","",""],
["","","","but this is the cool part","","","","","",""],
["","","","he keeps stumbling into the blight's traps and bumbling his way through","","","","","",""],
["","","","and ultimately HE'S the one that dissolves the time trance and enacts the dreamspace hot dog gambit","","","","","",""],
["","","","this is a bit of a spoiler, but they eventually find out that tony is actually a BLIGHT PRINCE who defected from the throne and disguised himself as a human","","","","","",""],
["","","","there's this great scene where rune threatens to space tony--","","","","","",""],
["","","","oh, i'm getting so off track","","","","","",""],
["","","","right, eventually they manage to get rune's aid, though they have to trade two soul essences and the MAJORITY of edvard's air freshener collection","","","","","",""],
["","","","ummm i'm gonna skip over a couple of chapters in order to get you up to date","","","","","",""],
["","","","chapters 6 and 7 are mostly filler, if we're being honest, though it does contain pollux's entire character arc, and a lot of people say he's their favorite","","","","","",""],
["","","","actually, people liked him so much i'm thinking about bringing him back in chapter 20, but that's not important","","","","","",""],
["","","","so in chapter 8... well, chapter 8's not important either","","","","","",""],
["","","","the space elevator is chapter 10... twist's big lore drop is... i think that doesn't happen til chapter 12?","","","","","",""],
["","","","OH yeah, oh my god, how could i forget","","","","","",""],
["","","","this is the part where the nocturnals end up lateral-stepped all the way to nepal, right?","","","","","",""],
["","","","and you won't believe what they find there.","","","","","",""],
["","","","SPACE. PIRATES.","","","","","",""],
["","","","","","","","",['(pretend to check watch)', 'oh my god, space pirates??'],['natalie_nocturnal3g', 'natalie_nocturnal3h']],
["natalie_nocturnal3g","you","","[i]checking watch motion[/i]","","","","","",""],
["","natalie","","oh geez, how long was i rambling for?","","","","","",""],
["","","","sorry, that's nocturnal anyway!","","","natalie_nocturnal4","","",""],
["natalie_nocturnal3h","you","","oh my god, space pirates??","","","","","",""],
["","natalie","","you hecking bet","","","","","",""],
["","","","but as sophia and the nocturnals are led on board the space pirate ship, arms bound, they see a familiar face before them...","","","","","",""],
["","","","HAZEL THE LIBRARIAN","","","","","",""],
["","you","","wait, what's hazel doing on a space pirate ship??","","","","","",""],
["","natalie","","well, THAT","","","","","",""],
["","","","you're going to have to read nocturnal to find out ;3","","","","","",""],
["","you","","awww, you can't leave me hanging like that!","","","","","",""],
["","natalie","","sorry bud, not spoiling this one for you","","","","","",""],
["","","","thanks for letting me rant about it for a while though!","","","","","",""],
["","you","","of course!","","","","","",""],
["","","","it sounds really cool","","","","","",""],
["","natalie","","hah, that's not what most people think after i give them the spiel","","","","","",""],
["","","","but thank you, really","","","","","",""],
["","","","now i gotta get back to coloring edvard's luscious hair","","","","","",""],
["","you","","please do not let me stop you","","","null","","",""],
["natalie_nocturnal4","you","","it's okay, it sounds... interesting!","","","","","",""],
["","natalie","","heh, thanks","","","null","","",""]
]