extends Node

var raw_blocks = [
["talk_to_numa","_none","_none","_pass","","not met_numa",['numa_intro1', 'numa_c'],"","",""],
["numa_c","","","_pass","","trample_flag",['numa_intro2', 'numa_default'],"","",""],
["numa_intro1","","","_pass","","met_numa",['numa_intro1_alt', 'numa_intro1_normal'],"","",""],
["numa_intro1_normal","you","numa_neutral","hello?","met_numa","","","","",""],
["","???","","oh, hey! ","trample_flag","","","","",""],
["","","","um, you must be new","","","","","",""],
["","you","","yep!","","","","","",""],
["","","","what are you doing?","","","","","",""],
["","???","","oh, you know. gardening.","","","","","",""],
["","","","i guess that's kinda obvious. haha. sorry.","","","","","",""],
["","you","","uh, it's ok","","","","","",""],
["","","","i'm {player}. what's your name?","","","","","",""],
["","???","","numa","","","numa_intro1_combined","","",""],
["numa_intro1_alt","you","numa_neutral","hey!","","","","","",""],
["","numa","","oh, hey! ","","","","","",""],
["","","","um, {player}, right?","","","","","",""],
["","you","","yep that's me","","","","","",""],
["","","","what are you up to?","","","","","",""],
["","numa","","oh, you know. gardening.","","","","","",""],
["","","","i guess that's kinda obvious. haha. sorry.","","","","","",""],
["","you","","uh, it's ok","","","","","",""],
["numa_intro1_combined","","","","","","","",['it\'s cool that purrgatory has a garden', 'i can\'t believe plants can grow here', 'your flowers smell kind of bad'],['numa_garden', 'numa_grow', 'numa_smell']],
["numa_garden","you","","it's cool that purrgatory has a garden","","","numa_blank1","","",""],
["numa_grow","you","","i can't believe plants can grow here","","","numa_blank1","","",""],
["numa_smell","you","","your flowers smell kind of bad…","","","numa_blank1","","",""],
["numa_blank1","numa","","uh, yeah. i guess","","","","","",""],
["","","","","","","","",['what are you going to do with these flowers?', 'what kind of flower is that?', 'what\'s your favorite kind of flower?'],['numa_do_what', 'numa_what_kind', 'numa_favorite']],
["numa_do_what","you","","what are you planning on doing with those flowers?","","","numa_blank2","","",""],
["numa_what_kind","you","","what kind of flower are you watering?","","","numa_blank2","","",""],
["numa_favorite","you","","what's your favorite kind of flower?","","","numa_blank2","","",""],
["numa_blank2","numa","","um, i dunno. ","","","","","",""],
["","you","","uhh","","","","","",""],
["","","","","","","","",['you don\'t talk much', 'bye for now'],['numa_talk_much', 'numa_bye']],
["numa_talk_much","you","","you don't talk much, do you?","","","","","",""],
["","_none","","numa shrugs.","","","","","",""],
["numa_bye","you","","bye for now, i guess","","","","","",""],
["","","","enjoy gardening!","","","","","",""],
["","numa","","thanks!","","","","","",""],
["","","","enjoy, um, whatever you're doing.","","","","","",""],
["","you","","thanks","","","null","","",""],
["numa_intro2","_none","","maybe you should give her some space for now.","","","null","","",""],
["numa_leave","numa","numa_neutral","HEY! watch your step!!","surprise_audio","","","","",""],
["","_none","","you freeze with your foot in the air.","nearly_trampled_flower","","","","",""],
["","numa","","you almost stepped on a tulip!","","","","","",""],
["","","","do you know how hard it is to grow those in here??","","","","","",""],
["","you","","oh, sorry...","","","","","",""],
["","_none","","numa takes a deep breath.","","","","","",""],
["","numa","","sorry, i didn't mean to yell","","","","","",""],
["","","","what i meant was [i]please[/i] watch your step","","","","","",""],
["","","","if you don't mind.","","","","","",""],
["","you","","um, okay","","","","","",""],
["","","","i'll try not to step on anything","","","","","",""],
["","numa","","just, stay on the path from now on","","","","","",""],
["","you","","ok","","","","","",""],
["","numa","","thanks.","","","null","","",""],
["numa_default","_none","_none","_pass","","numa_quest_complete",['ks_and_numa', 'numa_default2'],"","",""],
["numa_default2","_none","numa_neutral","the rancid smell of the flowers hits you once more.","","","","","",""],
["numa_default_c1","","","_pass","","numa_pissed_off and not numa_snooped",['numa_default_taciturn', 'numa_default_c2'],"","",""],
["numa_default_c2","","","_pass","","numa_snooped and not numa_followed_up",['numa_follow_up', 'numa_default_main'],"","",""],
["numa_default_taciturn","","","","","","","",['what\'s up?', 'how\'s the gardening?', 'do you technically have four eyes?', 'have you met the others?'],['numa_dot', 'numa_dot', 'numa_dot', 'numa_dot']],
["numa_default_main","","","","","","",['numa_snooped', 'true', 'true', 'true', 'not numa_snooped'],['(about kyungsoon)', 'what\'s up?', 'how\'s the gardening?', 'do you technically have four eyes?', 'have you met the others?'],['numa_ks', 'numa_wasup', 'numa_how', 'numa_eyes', 'numa_others']],
["numa_others","you","","have you met oliver and kyungsoon?","numa_asked_about_others","","","","",""],
["","_none","","numa nods","","","","","",""],
["","you","","you must get to know each other pretty well when you're stuck in purrgatory together.","","","","","",""],
["","numa","","yeah, sort of.","","","","","",""],
["","","","except, um...","","","","","",""],
["","","","…","","","","","",""],
["","you","","yes?","","","","","",""],
["","numa","","well, kyungsoon, i haven't...","","","","","",""],
["","","","...","","","","","",""],
["","you","","what about kyungsoon?","","","","","",""],
["","numa","","•••","","","","","",""],
["","you","","did she... do something bad?","","","","","",""],
["","numa","","no no no no","","","","","",""],
["","","","aaa never mind, forget i said anything ;;","","","","","",""],
["","you","","uh, alright","","","null","","",""],
["numa_wasup","you","","what's up?","","",['_rand', 'numa_wasup1', 'numa_wasup2', 'numa_wasup3', 'numa_wasup4', 'numa_wasup5', 'numa_wasup6', 'numa_wasup7', 'numa_wasup8', 'numa_wasup9', 'numa_wasup10', 'numa_wasup11', 'numa_wasup12', 'numa_wasup13', 'numa_wasup14', 'numa_wasup15', 'numa_wasup16', 'numa_wasup17', 'numa_wasup18', 'numa_wasup19', 'numa_wasup20'],"","",""],
["numa_wasup1","numa","","um, just gardening things, haha","","","","","",""],
["","you","","haha","","","null","","",""],
["numa_wasup2","numa","","wish i had some sunscreen...","","","","","",""],
["","you","","but","","","","","",""],
["","","","there's no sun in purrgatory?","","","","","",""],
["","numa","","aaa i know","","","","","",""],
["","","","i'm just anxious about getting sunburned","","","","","",""],
["","","","it would make me feel better if i had sunscreen on","","","","","",""],
["","you","","oh","","","","","",""],
["","numa","","my skin is very sensitive ;;","","","null","","",""],
["numa_wasup3","numa","","um, the tulips are blooming nicely this time of year!","","","","","",""],
["","you","","oh!","","","","","",""],
["","","","are they?","","","","","",""],
["","numa","","...","","","","","",""],
["","","","no, not really","","","","","",""],
["","","","we don't even have tulips","","","","","",""],
["","","","i don't know why i said that","","","null","","",""],
["numa_wasup4","numa","","oh, just watering this flower!","","","","","",""],
["","you","","haven't you been watering that flower for a while?","","","","","",""],
["","numa","","um, yeah","","","","","",""],
["","","","it takes a lot of water","","","","","",""],
["","you","","but isn't that well full of milk...?","","","","","",""],
["","numa","","...","","","","","",""],
["","","","okay, fine, you got me","","","","","",""],
["","","","i'm pouring milk on this flower","","","","","",""],
["","you","","does that... help it grow?","","","","","",""],
["","numa","","i don't know ;;","","","null","","",""],
["numa_wasup5","numa","","time passes slowly in purrgatory...","","","","","",""],
["","","","even for a snail","","","null","","",""],
["numa_wasup6","numa","","i miss solving sudokus...","","","","","",""],
["","you","","there's no sudoku in purrgatory, huh?","","","","","",""],
["","numa","","nope","","","","","",""],
["","","","only tic tac toe ;;","","","null","","",""],
["numa_wasup7","numa","","i wonder how my garden back at home is doing?","","","","","",""],
["","you","","do you think someone else is taking care of it?","","","","","",""],
["","numa","","maybe!","","","","","",""],
["","","","well","","","","","",""],
["","","","actually, my dad probably dug it up to build that patio he wanted...","","","","","",""],
["","you","","aw","","","null","","",""],
["numa_wasup8","numa","","i'm worried about the soil content here...","","","","","",""],
["","","","i think it might be too sandy","","","","","",""],
["","you","","i'm [i]sand[/i] to hear that","","","","","",""],
["","numa","","oh, uh, haha","","","null","","",""],
["numa_wasup9","numa","","i've been thinking about pruning the bushes...","","","","","",""],
["","","","it's supposed to help them grow, i think","","","","","",""],
["","you","","you should go for it!","","","","","",""],
["","numa","","yeah, but, how much should i prune?","","","","","",""],
["","","","from what part of the plant?","","","","","",""],
["","","","what pruning technique do i use??","","","","","",""],
["","","","what if i kill them by accident???","","","","","",""],
["","you","","uhhh","","","","","",""],
["","numa","","no, it's too scary, i can't ;;","","","null","","",""],
["numa_wasup10","numa","","um, i don't know","","","","","",""],
["","","","i'm tired","","","","","",""],
["","you","","me too","","","null","","",""],
["numa_wasup11","numa","","my therapist told me to relax my muscles every now and then","","","","","",""],
["","you","","oh, that's a good idea!","","","","","",""],
["","","","are you doing it now?","","","","","",""],
["","numa","","uhhh","","","","","",""],
["","you","","you should relax your muscles","","","","","",""],
["","numa","","ummm i'm trying","","","","","",""],
["","you","","what's so hard about it? just relax!!","","","","","",""],
["","numa","","AAA I'M SORRY I'M TRYING","","","null","","",""],
["numa_wasup12","numa","","gosh, i could really use some ph strips...","","","","","",""],
["","you","","what kind of garden doesn't even have ph strips?","","","","","",""],
["","numa","","RIGHT??","","","null","","",""],
["numa_wasup13","numa","","did you know dragonflies have existed for 300 million years?","","","","","",""],
["","you","","cool!","","","","","",""],
["","numa","","bug fact!!","","","null","","",""],
["numa_wasup14","numa","","did you know fruit flies were the first animals to go to space?","","","","","",""],
["","you","","wow, really?","","","","","",""],
["","numa","","that's a bug fact!!","","","null","","",""],
["numa_wasup15","numa","","did you know caterpillars have 12 eyes?","","","","","",""],
["","you","","oh wow","","","","","",""],
["","numa","","bam, bug fact!!","","","null","","",""],
["numa_wasup16","numa","","you know, i never thought i would outlive my pet fish...","","","","","",""],
["","you","","that's good","","","","","",""],
["","","","i don't think it would have enjoyed purrgatory very much","","","","","",""],
["","numa","","haha, i guess not","","","null","","",""],
["numa_wasup17","numa","","i should start my mood tracker again...","","","","","",""],
["","you","","oh, what's that?","","","","","",""],
["","numa","","it's when you write down your mood every day!","","","","","",""],
["","","","um, it helps with mental health and stuff, haha","","","","","",""],
["","you","","ah, why did you stop?","","","","","",""],
["","numa","","well, um","","","","","",""],
["","","","it was kind of pointless because my mood was the same every day","","","","","",""],
["","you","","oh","","","","","",""],
["","","","because of...","","","","","",""],
["","numa","","because of purrgatory, yeah ;;","","","null","","",""],
["numa_wasup18","numa","","AAAA","","","","","",""],
["","you","","ahh!! what's wrong?!","","","","","",""],
["","numa","","oh, sorry, you caught me by surprise ;;","","","","","",""],
["","you","","oh","","","","","",""],
["","","","jesus","","","null","","",""],
["numa_wasup19","numa","","it's probably a good thing there's no coffee in purrgatory...","","","","","",""],
["","","","i used to drink it a lot...","","","","","",""],
["","you","","oh, yeah, i can imagine","","","null","","",""],
["numa_wasup20","numa","","do you know any bug facts?","","","","","",""],
["","you","","oh, ummm","","","","","",""],
["","","","only boring ones","","","","","",""],
["","numa","","there's no such thing as a boring bug fact!!","","","null","","",""],
["numa_how","you","","how's the gardening going?","","","","","",""],
["","numa","","oh, the flowers are doing good!","","","","","",""],
["","","","i mean, they smell like crap. haha","","","","","",""],
["","","","but, um, otherwise they're doing good.","","","","","",""],
["","you","","good to hear.","","","","","",""],
["","numa","","haha um","","","","","",""],
["","","","yeah","","","","","",""],
["","","","...","","","","","",""],
["","","","","","","","",['you must care about them a lot', 'were you a gardener in real life?', 'do you spend all your time here?'],['numa_protective', 'numa_gardener', 'numa_time']],
["numa_time","you","","do you spend all your time gardening?","","","","","",""],
["","numa","","i mean, i guess so","","","","","",""],
["","","","usually i'm here or in my room.","","numa_snooped",['numa_time1', 'numa_time2'],"","",""],
["numa_time1","numa","","but, um","","","","","",""],
["","","","you already know about that","","","","","",""],
["","you","","oh, uh, yeah","","","","","",""],
["","","","sorry","","","null","","",""],
["numa_time2","you","","wait, you have a room?","","","","","",""],
["","","","where?","","","","","",""],
["","numa","","um, it's in the vents","","","","","",""],
["","you","","huh.","","","","","",""],
["","numa","","so if you ever hear noises in the wall, you know who it is!","","","","","",""],
["","","","haha","","","","","",""],
["","","","um, just kidding","","","","","",""],
["","","","aa that was weird wasn't it","","","","","",""],
["","you","","lol it's okay","","","null","","",""],
["numa_protective","you","","you must care about those flowers a lot","","","","","",""],
["","numa","","um, yeah, i guess","","","","","",""],
["","","","sorry about earlier","","","","","",""],
["","","","again","","","","","",""],
["","","","sometimes i just get a little protective, or whatever ;;","","","","","",""],
["","you","","it's okay!","","","","","",""],
["","","","do people step on them a lot?","","","","","",""],
["","numa","","well...... not really","","","","","",""],
["","","","i just get really anxious that it might happen someday...","","","","","",""],
["","","","","","","","",['guess you nipped that problem in the bud', 'you should try to relax a little', '(pretend to step on a flower)'],['numa_bud', 'numa_loose', 'numa_pretend']],
["numa_bud","you","","well, i guess you nipped that problem in the [i]bud[/i]","","","","","",""],
["","numa","","...","","","","","",""],
["","","","heh","","","","","",""],
["","you","","hehe","","","null","","",""],
["numa_loose","you","","maybe you should try to relax a little","","","","","",""],
["","numa","","gardening is relaxing.","","","","","",""],
["","you","","ah, i see","","","","","",""],
["","numa","","it's just.","","","","","",""],
["","","","SO RELAXING.","","","","","",""],
["","","","i'm SO RELAXED right now.","","","","","",""],
["","you","","i... i see...","","","null","","",""],
["numa_pretend","you","","like this?","numa_pissed_off","","","","",""],
["","_none","","you lift your foot in preparation to squash a flower","","","","","",""],
["","numa","","…","","","","","",""],
["","you","","i'm gonna step on it","","","","","",""],
["","numa","","•••","","","","","",""],
["","you","","really? nothing?","","","","","",""],
["","_none","","numa starts shaking.","","","","","",""],
["","you","","...never mind.","","","null","","",""],
["numa_dot","numa","","…","","","","","",""],
["","_none","","it looks like she doesn't want to talk to you anymore.","","","null","","",""],
["numa_eyes","you","","those are your eyestalks, right?","","","","","",""],
["","numa","","mhm","","","","","",""],
["","you","","does that mean you technically have four eyes?","","","","","",""],
["","numa","","i mean, yeah.","","","","","",""],
["","you","","dope","","","null","","",""],
["numa_gardener","you","","were you a gardener in real life, too?","","","","","",""],
["","numa","","oh, no","","","","","",""],
["","","","i had a backyard garden, but as a job i was an intern at an accounting firm","","","","","",""],
["","you","","oh, i see","","","","","",""],
["","","","did you like it?","","","","","",""],
["","numa","","mhm","","","","","",""],
["","","","i mean, aren't all the cool kids into accounting? haha","","","","","",""],
["","","","","","","","",['sounds like my kind of job', 'what do accountants do anyway?'],['numa_job', 'numa_cool']],
["numa_cool","you","","what kind of stuff do accountants do, anyway?","","","","","",""],
["","numa","","oh, uh","","","","","",""],
["","","","financial statements and stuff","","","","","",""],
["","","","you know","","","","","",""],
["","you","","does that mean you could do my taxes?","","","","","",""],
["","numa","","uh, no, sorry.","","","","","",""],
["","","","that's the wrong type of accountant","","","","","",""],
["","you","","oh, my bad","","","null","","",""],
["numa_job","you","","i think i would have liked being an accountant. ","","","","","",""],
["","","","i always liked numbers and stuff","","","","","",""],
["","numa","","oh, yeah, me too!","","","","","",""],
["","","","this is kinda dumb but, um","","","","","",""],
["","","","i really liked making spreadsheets and stuff, hah","","","","","",""],
["","you","","yo i love spreadsheets!","","","","","",""],
["","numa","","oh really?","","","","","",""],
["","","","aaa that's cool","","","","","",""],
["","you","","what kind of accounting did you do?","","","","","",""],
["","numa","","i did financial accounting, mostly!","","","","","",""],
["","","","cash flow and balance sheets and, you know, stuff like that.","","","","","",""],
["","","","i wanted to be a CPA later in life","","","","","",""],
["","you","","ah, i see","","","","","",""],
["","numa","","i know, it's kind of boring","","","","","",""],
["","you","","no, no, not at all.","","","","","",""],
["","_none","","numa smiles.","","","null","","",""],
["snoop","numa","numa_neutral","{player}?",[['met_numa', true], ['surprise_audio', true]],"","","","",""],
["","_none","","you stop short as you run into numa in the vents.","","","","","",""],
["","you","","oh, um, numa!","","","","","",""],
["","numa","","what are you doing in here?!","","","","","",""],
["","you","","um, is this where you live?","","","","","",""],
["","numa","","yes!","","","","","",""],
["","","","","","","","",['i\'m sorry', '…'],['snoop_sorry', 'snoop_dots']],
["snoop_sorry","you","","i'm sorry, i was just exploring and i didn't know","","","","","",""],
["","numa","","just [i]exploring[/i]? in someone else's room??","","","","","",""],
["","you","","sorry...","","","snoop_1","","",""],
["snoop_dots","you","","...","","","","","",""],
["","numa","","were you snooping around in my room??","","","","","",""],
["snoop_1","numa","","i can't believe this!","","","","","",""],
["","","","you'd think screwing shut the door would be enough to keep people out...","","","","","",""],
["","","","wait","","","","","",""],
["","","","did...","","","","","",""],
["","","","did you read my notebook too??","","","","","",""],
["","","","","","","","",['yes', 'no'],['snoop_yes', 'snoop_no']],
["snoop_yes","you","","...yes, i'm sorry","","","","","",""],
["","","","i was just curious!","","","","","",""],
["","numa","","you WHAT?!","","","","","",""],
["","you","","it's okay! it wasn't embarrassing or anything!","","","","","",""],
["","numa","","THAT JOURNAL IS PRIVATE!","","","","","",""],
["","","","ASSHOLE!","numa_asshole","","","","",""],
["","you","","i'm sorry, i just took a peek, i promise!","","","","","",""],
["","numa","","i can't believe you--","","","","","",""],
["","","","why would--","","","","","",""],
["","","","wait, does that mean you saw...?","","","","","",""],
["","","","AGH","","","","","",""],
["","_none","","numa closes her eyes and starts taking deep breaths.","","","snoop_2a","","",""],
["snoop_no","you","","no, of course not","","","","","",""],
["","numa","","oh. okay.","","","","","",""],
["","","","good, because you shouldn't have!","","","","","",""],
["snoop_2a","you","","sorry for asking, but...","","","","","",""],
["snoop_2","","","","","","",['not snoop_keeping_track', 'true', 'true'],['are you counting the days you\'ve been here?', 'is that a drawing of you and kyungsoon?', 'could you back up please'],['snoop_track', 'snoop_pic', 'snoop_back']],
["snoop_track","you","","are you keeping track of how long you've been here?","snoop_keeping_track","","","","",""],
["","numa","","yeah. i guess.","","","","","",""],
["","you","","how come?","","","","","",""],
["","numa","","i don't know, i just have to keep track.","","","","","",""],
["","","","otherwise time just blends together and i hate it","","","","","",""],
["","you","","i see","","","snoop_2","","",""],
["snoop_pic","you","","is that a drawing of you and kyungsoon?","","","","","",""],
["","numa","","um, no. i mean, uh, maybe.","","","","","",""],
["","","","...","","","","","",""],
["snoop_friends","you","","you two must be friends, then?","","","","","",""],
["","numa","","well, not really…","","","","","",""],
["","you","","um… girlfriends?","","","","","",""],
["","_none","","numa mutters something that you can't hear","","","","","",""],
["snoop_pre_crush","","","","","","",['true', 'not snoop_tried_to_leave'],['you have a crush on her?', 'could you back up please'],['snoop_crush', 'snoop_back2']],
["snoop_crush","you","","do you… have a crush on her?","","","","","",""],
["","numa","","YES!","","","","","",""],
["","","","I HAVE A CRUSH ON KYUNGSOON!!","","","","","",""],
["","you","","oh","","","","","",""],
["","numa","","it's just that i can never work up the courage to talk to her, even though i've been stuck here for YEARS","","","","","",""],
["","","","and i've never told anyone about it either, in case they leaked the secret","","","","","",""],
["","","","i mean, i can't give her FLOWERS because they all smell HORRIBLE","","","","","",""],
["","","","and i just don't know what to do!!","","","","","",""],
["","_none","","numa puts her head in her hands.","","","","","",""],
["","numa","","aaa why am i telling you this ;;","","","","","",""],
["","you","","no, it's ok","","","","","",""],
["","numa","","i'm sorry, i should go","","","","","",""],
["","you","","it's ok, it's ok! it's just…","","","","","",""],
["snoop_c","","","","","","",['not snoop_fluffy', 'not snoop_offered_to_talk', 'true'],['what\'s so attractive about her?', 'would you like me to talk to her for you?', 'could you pleeease back up'],['snoop_attractive', 'snoop_talk', 'snoop_back3']],
["snoop_back","you","","could you, uh, back up please? there's not enough space to crawl past you","","","","","",""],
["","numa","","um, yeah. sure.","","","","","",""],
["","","","i was just wondering if you… saw the picture","","","","","",""],
["","you","","uh, the one of you and kyungsoon?","","","","","",""],
["","numa","","uh, yeah. well, i mean, it's not...","","","","","",""],
["","","","yeah, that one.","","","snoop_friends","","",""],
["snoop_back2","you","","if you wouldn't mind backing up so i can get out of the vent…","snoop_tried_to_leave","","","","",""],
["","numa","","oh, yeah, of course, it's just…","","","","","",""],
["","","","about kyungsoon…","","","","","",""],
["","you","","mhm?","","","","","",""],
["","numa","","…","","","snoop_pre_crush","","",""],
["snoop_attractive","you","","i don't see what's so attractive about kyungsoon…?","snoop_fluffy","","","","",""],
["","numa","","really??","","","","","",""],
["","","","i mean, she's so tall and mysterious...","","","","","",""],
["","","","and smart","","","","","",""],
["","","","and pretty","","","","","",""],
["","","","and... fluffy","","","","","",""],
["","you","","huh","","","snoop_c","","",""],
["snoop_talk","you","","i could talk to her, if you want?","snoop_offered_to_talk","","","","",""],
["","numa","","NO!","","","","","",""],
["","","","i mean","","","","","",""],
["","_none","","numa takes another deep breath.","","","","","",""],
["","numa","","i mean, please don't do that.","","","","","",""],
["","you","","jeez, okay","","","","","",""],
["","numa","","sorry, it's just","","","","","",""],
["","","","if i'm going to tell her, i want it to be perfect.","","","","","",""],
["","","","i want to give her gifts, maybe some food…","","","","","",""],
["","you","","food?","","","","","",""],
["","numa","","i mean, she really likes food, right?","","","","","",""],
["","you","","that's true","","","snoop_c","","",""],
["snoop_back3","you","","could you pleeease back up so we can get out of this vent","","","","","",""],
["","numa","","oh, sorry","","","","","",""],
["","","","sorry, sorry, sorry…","","","","","",""],
["","_none","","numa backs up and you finally leave the vent","snoop_leave_vent","","","","",""],
["","numa","","…","","","","","",""],
["","you","","…","","","","","",""],
["","numa","","um, please don't tell anyone about this","","","","","",""],
["","you","","my lips are sealed.","","","","","",""],
["","numa","","can i have the screwdriver please","","","","","",""],
["","you","","here",[['_inv_screwdriver', false]],"","","","",""],
["","_none","","numa takes the screwdriver and hurries down the stairs.","","","null","","",""],
["numa_follow_up","you","","um","numa_followed_up","","","","",""],
["","","","hey","","","","","",""],
["","numa","","hey","","","","","",""],
["","you","","sorry about snooping around earlier","","","","","",""],
["","numa","","it's... fine.","","numa_asshole",['numa_follow_up1', 'numa_follow_up2'],"","",""],
["numa_follow_up1","","","sorry for calling you an asshole.","","","numa_follow_up3","","",""],
["numa_follow_up2","","","sorry for blowing up at you.","","","","","",""],
["numa_follow_up3","you","","it's okay","","","","","",""],
["","","","i probably deserved it","","","","","",""],
["","_none","","numa shrugs.","","","","","",""],
["","numa","","let's... call it even?","","","","","",""],
["","","","i guess?","","","","","",""],
["","you","","sounds good to me.","","","","","",""],
["","numa","","great","","","","","",""],
["","_none","","the two of you stand around awkwardly. then numa goes back to watering.","","","null","","",""],
["numa_ks","you","numa_neutral","so, about kyungsoon…","","numa_helping",['numa_gift_options', 'numa_plan'],"","",""],
["numa_plan","numa","","oh, yeah","","","","","",""],
["","","","um, sorry about venting to you about that","","","","","",""],
["","you","","heh, no pun intended?","","","","","",""],
["","numa","","pun?","","","","","",""],
["","","","...oh. haha.","","","","","",""],
["","you","","but uh","","","","","",""],
["","","","you still want to talk to her, right?","","","","","",""],
["","numa","","i mean... i guess... i wanted to make everything perfect","","","","","",""],
["","","","this is going to sound so stupid","","","","","",""],
["","","","i want to arrange a boquet of flowers","","","","","",""],
["","","","and write her a poem","","","","","",""],
["","","","and get some food as a gift","","","","","",""],
["","","","","","","","",['i could help you with that', 'you should really just talk to her'],['numa_help', 'numa_talk']],
["numa_help","you","","i could try to help you with that!","numa_helping","","","","",""],
["","numa","","really?","","","","","",""],
["","you","","yeah, really!","","","","","",""],
["","","","consider it as making up for snooping around in your room","","","","","",""],
["","numa","","well...","","","","","",""],
["","","","i guess i could use some help...","_quest_numa_kyungsoon","","","","",""],
["","","","i guess it's pretty obvious that i'm not getting anywhere alone, right?","","","","","",""],
["","","","haha","","","numa_gift_options","","",""],
["numa_talk","you","","it would be a lot easier if you just talked to her...","","","","","",""],
["","numa","","oh, no no no, i can't do that","","","","","",""],
["","","","that's way too scary","","","","","",""],
["","you","","we're already dead, what is there to be afraid of??","","","","","",""],
["","numa","","i don't know","","","","","",""],
["","","","an eternity of self-hatred, fueled by inescapable rejection and humiliation?","","","","","",""],
["","you","","oh","","","","","",""],
["","","","i see","","","","","",""],
["","numa","","just normal feelings that everyone has, right?","","","","","",""],
["","","","hahahahaha","","","","","",""],
["","","","um. just kidding.","","","null","","",""],
["numa_gift_options","","","","","","","",['ready to talk to her?', '(about flowers)', '(about the poem)', '(about food)'],['numa_ready?', 'numa_flowers_c', 'numa_poem_c', 'numa_food_c']],
["numa_flowers_c","","","_pass","","not numa_started_flowers",['numa_flowers1', 'numa_flowers_c2'],"","",""],
["numa_flowers_c2","","","_pass","","not numa_finished_flowers",['numa_flowers2', 'numa_flowers3'],"","",""],
["numa_flowers1","you","","do you need any help picking out flowers?","numa_started_flowers","","","","",""],
["","numa","","oh, yes, please",[['flower_fails', 0]],"","","","",""],
["","","","my eyesight is bad, so i have a hard time finding the ones i want ;;","","","","","",""],
["","you","","well, how about this one--","","","","","",""],
["","numa","","DON'T TOUCH THAT!","","","","","",""],
["","","","i mean","","","","","",""],
["","_none","","numa breathes deeply.","","","","","",""],
["","numa","","please don't touch them, they're fragile","","","","","",""],
["","","","just point at them","","","","","",""],
["","you","","jeez","","","","","",""],
["","","","you're going to give me a heart attack one of these days","","","","","",""],
["","numa","","sorry ;;","","","flowers_init","","",""],
["numa_flowers2","you","","let's give flower-picking another shot…","","flower_fails >= 2",['numa_flowers_skip', 'flowers_init'],"","",""],
["numa_flowers_skip","numa","","ummmmmmmm","","","","","",""],
["","","","you know, i could always just... find the flowers myself...","","","","","",""],
["","","","if you'd rather, i mean","","","","","",""],
["","","","","","","","",['let me try one more time', 'yeah, you should probably do it yourself'],['numa_flowers_skip1', 'numa_flowers_skip2']],
["numa_flowers_skip1","you","","let me try one more time!","","","","","",""],
["","numa","","okay!!","","","flowers_init","","",""],
["numa_flowers_skip2","you","","yeah, i guess you should probably just do it yourself","","","","","",""],
["","","","i don't think i'm very good at this lol","","","","","",""],
["","","","sorry i couldn't be more of a help","","","","","",""],
["","numa","","no no it's okay!","","","","","",""],
["","","","umm i appreciate you trying","","","","","",""],
["","","","it'll just... probably... be faster by myself...","","","","","",""],
["","","","i mean i'm not saying you're bad at finding flowers or anything!!","","","","","",""],
["","","","it's just you know, i'm more familiar with the garden, and","","","","","",""],
["","","","you already tried a couple of times, and...","","","","","",""],
["","you","","no no i totally get it!","","","","","",""],
["","numa","","okay, cool","","","","","",""],
["","","","sorry ;;","numa_finished_flowers","","null","","",""],
["numa_flowers3","numa","","the flowers for kyungsoon are looking great!!","","","","","",""],
["","you","","great!","","","","","",""],
["","numa","","aaaaa i just hope she'll like them","","","","","",""],
["","","","want to help me find some more, just in case?","","","","","",""],
["","","","","","","","",['sure', 'not right now'],['flowers_init', 'numa_flowers_not']],
["numa_flowers_not","you","","not right now, sorry","","","","","",""],
["","numa","","oh, okay","","","null","","",""],
["numa_poem_c","","","_pass","","not numa_started_poem",['numa_poem1', 'numa_poem_c2'],"","",""],
["numa_poem_c2","","","_pass","","not numa_finished_poem",['numa_poem2', 'numa_poem3'],"","",""],
["numa_poem1","you","","how's that poem going?","numa_started_poem","","","","",""],
["","numa","","um, i think i could use some help, maybe","","","","","",""],
["","","","english was always one of my worst subjects","","","","","",""],
["","","","only b i've ever gotten...","","","","","",""],
["","you","","well, let's hear what you have so far!","","","","","",""],
["","numa","","are you sure?","","","","","",""],
["","","","it's not very good","","","","","",""],
["","","","actually, it's awful","","","","","",""],
["","","","actually it's pretty much the worst poem in the world","","","","","",""],
["","you","","damn","","","","","",""],
["","numa","","just, like, letting you know what you're getting into","","","","","",""],
["","you","","i'm sure it's fine!","","","","","",""],
["","","","promise i won't judge!","","","","","",""],
["","numa","","well...","","","","","",""],
["","","","it goes like this:","","","","","",""],
["","","","roses are white","","","","","",""],
["","","","violets are white","","","","","",""],
["","","","to me, you are","","","","","",""],
["","","","a shining light","","","","","",""],
["","you","","sounds good so far!","","","","","",""],
["","numa","","aa thank you","","","","","",""],
["","","","then it goes...","","","","","",""],
["","","","you are purple","","","","","",""],
["","","","soda is orange","","","","","",""],
["","","","…","","","","","",""],
["","","","that's all i have","","","","","",""],
["","","","nothing rhymes with orange ;;","","","","","",""],
["","you","","hmmmm....","","","","","",""],
["","","","","","","","",['and your face / i adore-enge', 'you pierce my heart / like a syringe', 'just switch the last two lines'],['numa_adore-enge', 'numa_syringe', 'numa_switch']],
["numa_adore-enge","you","","how about this","","","","","",""],
["","","","\"and your face, i adore-enge\"","","","numa_orange_after","","",""],
["numa_syringe","you","","how about this","","","","","",""],
["","","","\"you pierce my heart, like a syringe\"","","","numa_orange_after","","",""],
["numa_switch","you","","just switch the last two lines so that you don't have to rhyme with orange","","","","","",""],
["","","","\"soda is orange, you are purple\"","","","","","",""],
["","numa","","bubt, what rhymes with purple?","","","","","",""],
["","you","","uh","","","","","",""],
["","","","","","","","",['orange soda / i like to slurp-le', 'i got nothing'],['numa_slurp-le', 'numa_nothing']],
["numa_slurp-le","you","","\"orange soda, i like to slurp-le\"","","","numa_orange_after","","",""],
["numa_nothing","you","","i got nothing","","","numa_suit","","",""],
["numa_orange_after","numa","","…","","","","","",""],
["","you","","…","","","","","",""],
["","","","yeah, that sucks","","","","","",""],
["","numa","","sort of, yeah","","","","","",""],
["","","","sorry","","","","","",""],
["numa_suit","you","","i don't think poetry is my strong suit.","","","","","",""],
["","numa","","[i]sigh[/i]","","","","","",""],
["","","","i'm never going to finish this poem.","","","","","",""],
["","","","maybe i should just stick to spreadsheets...","","","","","",""],
["","you","","don't give up yet, maybe you'll think of something!","","","","","",""],
["","","","or maybe someone else can help?","","","","","",""],
["","numa","","who else would be willing to help with something like this?","","","","","",""],
["","you","","hmm...","","","","","",""],
["","","","i don't know, i'll think about it","","","","","",""],
["","numa","","thanks, i guess...","","","null","","",""],
["numa_poem2","you","","any progress on the poem?","","","","","",""],
["","numa","","not yet, sorry","","","","","",""],
["","","","i still can't think of the next line","","","","","",""],
["","","","i know, it's stupid ;;","","","","","",""],
["","you","","take your time","","","","","",""],
["","","","we have an eternity, after all.","","","null","","",""],
["numa_poem3","you","","was talking to elijah helpful?","","","","","",""],
["","numa","","yep!","","","","","",""],
["","","","i'm just putting some final touches on it now.","","","","","",""],
["","you","","can i hear it?","","","","","",""],
["","numa","","sure, here's a little excerpt:","","","","","",""],
["","","","you are purple","","","","","",""],
["","","","i am smitten","","","","","",""],
["","","","you're as cute","","","","","",""],
["","","","as a kitten!","ks_heard_cute_as_kitten","","","","",""],
["","you","","nice!","","","","","",""],
["","numa","","i know, it's so cute!!","","","","","",""],
["","","","thanks again for your help :)","","","","","",""],
["","you","","it's nothing, really.","","","null","","",""],
["numa_food_c","","","_pass","","not numa_started_food",['numa_food1', 'numa_food_c2'],"","",""],
["numa_food_c2","","","_pass","","not numa_progressed_food",['numa_food2', 'numa_food_c3'],"","",""],
["numa_food_c3","","","_pass","","not numa_finished_food",['numa_food3', 'numa_food4'],"","",""],
["numa_food1","you","","what are you doing about food?","numa_started_food","","","","",""],
["","numa","","um, i guess i haven't really thought about it","","","","","",""],
["","","","i don't even know what kind of food she likes…","","","","","",""],
["","","","","","","","",['books', 'keys', 'signs'],['numa_books', 'numa_keys', 'numa_signs']],
["numa_books","you","","i heard she likes to eat books.","","","","","",""],
["","numa","","books? really?","","","","","",""],
["","","","i guess i could give her my notebook…","","","","","",""],
["","you","","uh, are you sure you want her reading all of your personal writing?","","","numa_bad","","",""],
["numa_keys","you","","i heard she likes to eat keys.","","","","","",""],
["","numa","","keys? really?","","","","","",""],
["","","","well, i guess i could give her my screwdriver, which is kind of like a key…","","","","","",""],
["","you","","the one you need to get into your room?","","","numa_bad","","",""],
["numa_signs","you","","i heard she likes to eat signs.","","","","","",""],
["","numa","","signs? really?","","","","","",""],
["","","","i guess i could get that meowseum sign for her...","","","","","",""],
["","you","","the one that's made of glass?","","","numa_bad","","",""],
["numa_bad","numa","","oh","","","","","",""],
["","","","aaa you're right, that was stupid","","","","","",""],
["","","","sorry","","","","","",""],
["","you","","it's okay!","","","","","",""],
["","numa","",";;","","","","","",""],
["","you","","maybe i could talk to kyungsoon and find out what she likes.","","","","","",""],
["","numa","","well, i mean, that would be helpful!","","","","","",""],
["","","","just remember to, you know, be discreet about it","","","","","",""],
["","you","","i'll see what i can do!","","","null","","",""],
["numa_food2","you","","why don't you just give her some of that fruit in the other room?","","","","","",""],
["","","","it looks pretty tasty","","","","","",""],
["","numa","","oh, those are deathberries.","","","","","",""],
["","","","don't eat that","","","","","",""],
["","","","you'll be sick for WEEKS","","","","","",""],
["","you","","oh","","","","","",""],
["","numa","","yep","","","","","",""],
["","","","i just need to know what she likes, and then i'll be all set...","","","","","",""],
["","you","","right right","","","null","","",""],
["numa_food3","you","","i asked kyungsoon about her favorite food!","","","","","",""],
["","numa","","oh, really?? what did she say?","","","","","",""],
["","you","","it's leaves.","","","","","",""],
["","numa","","no way, i love leaves!","","","","","",""],
["","you","","great!","","","","","",""],
["","numa","","oh, they're all going to be dead and shriveled though","","","","","",""],
["","","","they probably won't taste very  good","","","","","",""],
["","","","actually, never mind","","","","","",""],
["","","","this is a terrible idea","","","","","",""],
["","you","","hey, it's the thought that counts!","","","","","",""],
["","numa","","do you think?","","","","","",""],
["","you","","yeah!","","","","","",""],
["","","","probably","","","","","",""],
["","numa","","that's not very reassuring ;;","numa_finished_food","","null","","",""],
["numa_food4","you","","is the food all ready?","","","","","",""],
["","numa","","yep, i'm almost done gathering the tastiest looking leaves for her...","","","","","",""],
["","you","","well, i guess i'll just [i]leaf[/i] you to it, then","","","","","",""],
["","numa","","i mean, you can stay if you want","","","","","",""],
["","","","it's no problem","","","","","",""],
["","","","...oh, that was a pun, wasn't it?","","","","","",""],
["","you","","it was a pun, yeah","","","","","",""],
["","numa","","haha","","","null","","",""],
["numa_ready?","you","","so, are you going to talk to her?","","numa_finished_flowers and numa_finished_poem and numa_finished_food",['numa_ready', 'numa_not_ready'],"","",""],
["numa_not_ready","numa","","oh no, not yet!","","not numa_finished_flowers",['numa_r_flowers', 'numa_r_c1'],"","",""],
["numa_r_flowers","","","i still haven't picked out the right flowers for her…","","","","","",""],
["numa_r_c1","","","_pass","","not numa_finished_poem",['numa_r_poem', 'numa_r_c2'],"","",""],
["numa_r_poem","","","i haven't finished the poem yet…","","","","","",""],
["numa_r_c2","","","_pass","","not numa_finished_food",['numa_r_food', 'numa_r_end'],"","",""],
["numa_r_food","","","i don't even know what food to get her!","","","","","",""],
["numa_r_end","numa","","everything needs to be perfect.","","","","","",""],
["","you","","hm, okay","","","null","","",""],
["numa_ready","numa","","well… i guess…","","","","","",""],
["","","","i have everything ready…","","","","","",""],
["","_none","","numa looks over at a boquet of flowers, a handwritten card, and a basket of leaves.","","","","","",""],
["","numa","","it's just","","","","","",""],
["","","","she's so pretty and confident and smart and,","","","","","",""],
["","","","she could do so much better than me, you know?","","","","","",""],
["","","","","","","","",['you\'ve got this!', 'what are you so worried about?'],['numa_got', 'numa_much']],
["numa_got","you","","you've got this, numa!","","","","","",""],
["","","","she's going to be blown away by all the gifts","","","","","",""],
["","numa","","do you think so?","","","","","",""],
["","you","","absolutely","","","","","",""],
["","numa","","well...","","","","","",""],
["","","","i guess she can't think any less of me than she does now","","","","","",""],
["","","","am i right? haha.","","","","","",""],
["","","","um.","","","","","",""],
["","","","sorry for being such a worry worm","","","","","",""],
["","you","","it's ok","","","","","",""],
["","_none","","numa takes a deep breath and gathers up the gifts in her arms.","","","","","",""],
["","numa","","OKAY!! let's do this!!!!","","","numa_meeting","","",""],
["numa_much","you","","what are you so worried about?","","","","","",""],
["","","","i mean, look at how much effort you've put into these gifts!","","","","","",""],
["","numa","","but what if she thinks i'm coming off too strong?","","","","","",""],
["","","","oh no, what if she thinks i'm weird??","","","","","",""],
["","","","what if she never wants to talk to me again?","","","","","",""],
["","","","oh god aaaaaaaaa","","","","","",""],
["","","","never mind i don't think i can do this ;;","","","","","",""],
["","you","","there's… no way that you're weirder than kyungsoon","","","","","",""],
["","numa","","huh?","","","","","",""],
["","you","","you can be weird together!","","","","","",""],
["","","","like two peas in a weird pod","","","","","",""],
["","numa","","…","","","","","",""],
["","you","","was that encouraging?","","","","","",""],
["","numa","","not really?","","","","","",""],
["","you","","okay, listen, it's too late to back out anyway!","","","","","",""],
["","","","come on, let's head to the commons","","","","","",""],
["","_none","","numa gulps.","","","","","",""],
["","numa","","ok…","","","","","",""],
["numa_meeting","_none","numa_neutral","the two of you make your way to the commons.","numa_goto_commons","","","","",""],
["","you","","are you ready?","","","","","",""],
["","_none","","numa shakes her head.","","","","","",""],
["","you","","go on, it'll be over soon","","","","","",""],
["","","","just go in and tell her you like her.","","","","","",""],
["","numa","","that's easy to say!","","","","","",""],
["","you","","just don't think about it! go in!!","","","","","",""],
["","numa","","you're right, you're right.","","","","","",""],
["","","","i can do this.","","","","","",""],
["","_none","","numa takes a deep breath, then bursts through the door.",[['_quest_numa_kyungsoon', false]],"","","","",""],
["","numa","_none","KYUNGSOON!","","","","","",""],
["","_none","","you listen through the door.","","","","","",""],
["","kyungsoon","","hm?","","","","","",""],
["","numa","","i, um, i just wanted to, uh","","","","","",""],
["","kyungsoon","","…","","","","","",""],
["","numa","","i mean","","","","","",""],
["","","","kyungsoon i, i, i have something to tell you!!","","","","","",""],
["","kyungsoon","","yeah?","","","","","",""],
["","_none","","you hear the library doors open.","oliver_hears_numa","","","","",""],
["","oliver","","i heard yelling, is everything okay out here?","","","","","",""],
["","","","oh, hi numa!","","","","","",""],
["","","","what's all that stuff for?","","","","","",""],
["","numa","","oh, haha, it's, um","","","","","",""],
["","oliver","","oh lord, what's that smell? is it the flowers?","","","","","",""],
["","numa","","aaa sorry","","","","","",""],
["","kyungsoon","","gross","","","","","",""],
["","oliver","","numa, are you… okay?","","","","","",""],
["","kyungsoon","","she was going to tell me something","","","","","",""],
["","oliver","","oh, well go ahead.","","","","","",""],
["","","","don't let me get in the way!","","","","","",""],
["","numa","","uhhhhhhhhhhh iii don't think i...","","","","","",""],
["","oliver","","go on!","","","","","",""],
["","numa","","kyungsoon…","","","","","",""],
["","","","i…","","","","","",""],
["","","","…","commons_flowers","","","","",""],
["","_none","","you hear the sound of flowers hitting the floor, then numa bursts through the door and runs down the hallway.","_quest_numa_friendship","","","","",""],
["","numa","numa_neutral","AAAAAAAAAAAAAAAA","_anim_right_to_left_run","","","","",""],
["","you","_none","numa?","","","","","",""],
["","oliver","","…","","","","","",""],
["","kyungsoon","","…","","","","","",""],
["","oliver","","what was all that about?","","","","","",""],
["","kyungsoon","","iuno","numa_crying","","null","","",""],
["numa_cry","_none","","you can hear the faint sound of crying through the vent.","","","","","",""],
["","you","","numa?","","not numa_consoled",['numa_cry_console', 'numa_cry_silent'],"","",""],
["numa_cry_console","numa","","go away!","numa_consoled","","","","",""],
["","","","","","","","",['don\'t feel bad', 'do you want to talk about it?', 'you really messed that up'],['numa_cry_feel', 'numa_cry_talk', 'numa_cry_mess']],
["numa_cry_silent","numa","","…","","","","","",""],
["","_none","","seems like she doesn't want to talk.","","","null","","",""],
["numa_cry_feel","you","","don't feel bad","","","","","",""],
["","","","you tried your best, but oliver got in the way.","","","","","",""],
["","numa","","…","","","","","",""],
["","you","","i bet kyungsoon is really enjoying those leaves!","","","","","",""],
["","numa","","…","","","","","",""],
["","you","","i think she liked the flowers?","","","","","",""],
["","numa","","she called them gross!","","","","","",""],
["","you","","gross in… a good way?","","","","","",""],
["","","","like how \"bad\" used to mean good","","","","","",""],
["","","","in the 80s","","","","","",""],
["","","","","","","","",['totally gross, duude', '(just cut your losses)'],['numa_cry_gross', 'numa_cry_end']],
["numa_cry_gross","you","","like, that's totally gross, duuude","","","","","",""],
["","_none","","you hear a strangled sound that might have been laughter.","","","","","",""],
["numa_cry_end","_none","","it doesn't look like she's coming out any time soon.","","","null","","",""],
["numa_cry_talk","you","","do you want to talk about it?","","","","","",""],
["","numa","","no.","","","","","",""],
["","you","","maybe later?","","","","","",""],
["","numa","","i'm going to stay in here","","","","","",""],
["","","","for eternity","","","","","",""],
["","you","","don't do that!!","","","","","",""],
["","numa","","…","","","numa_cry_end","","",""],
["numa_cry_mess","you","","you really messed that up","","","","","",""],
["","numa","","i know that already!","","","","","",""],
["","","","i mess up everything!!","","","","","",""],
["","you","","that's a mood","","","","","",""],
["","_none","","you hear numa start crying harder.","","","","","",""],
["","","","she's definitely not coming out now.","","","null","","",""]
]