extends Node

var raw_blocks = [
["talk_to_numa","_none","_none","_pass","","not saw_numa_intro",['numa_intro1', 'numa_c'],"","",""],
["numa_c","","","_pass","","trample_flag",['numa_intro2', 'numa_default'],"","",""],
["numa_intro1","","","_pass","","met_numa",['numa_intro1_alt', 'numa_intro1_normal'],"","",""],
["numa_intro1_normal","you","numa_neutral","hello?","met_numa","","","","",""],
["","???","","oh, hi! ","trample_flag","","","","",""],
["","","","um, you must be new","saw_numa_intro","","","","",""],
["","you","","yep!","","","","","",""],
["","","","what are you up to?","","","","","",""],
["","???","","oh, you know. gardening.","","","","","",""],
["","","","i guess that's kinda obvious, haha. sorry.","","","","","",""],
["","you","","haha, it's ok","","","","","",""],
["","","","i'm {player}. what's your name?","","","","","",""],
["","???","","it's numa","","","numa_intro1_combined","","",""],
["numa_intro1_alt","you","numa_neutral","hey!","saw_numa_intro","","","","",""],
["","numa","","oh, hi! ","trample_flag","","","","",""],
["","","","um, {player}, right?","","","","","",""],
["","you","","yep, that's me","","","","","",""],
["","","","what are you up to?","","","","","",""],
["","numa","","oh, you know. gardening.","","","","","",""],
["","","","i guess that's kinda obvious, haha. sorry.","","","","","",""],
["","you","","haha, it's ok","","","","","",""],
["numa_intro1_combined","","","","","","","",['it\'s cool that purrgatory has a garden', 'i can\'t believe plants can grow here', 'your flowers smell kind of bad'],['numa_garden', 'numa_grow', 'numa_smell']],
["numa_garden","you","","it's cool that purrgatory has a garden!","","","numa_blank1","","",""],
["numa_grow","you","","i can't believe plants can grow here","","","numa_blank1","","",""],
["numa_smell","you","","your flowers smell kind of bad...","","","numa_blank1","","",""],
["numa_blank1","numa","","uh, yeah, i guess","","","","","",""],
["","","","","","","","",['what are you going to do with these flowers?', 'what kind of flower is that?', 'what\'s your favorite kind of flower?'],['numa_do_what', 'numa_what_kind', 'numa_favorite']],
["numa_do_what","you","","what are you planning on doing with those flowers?","","","numa_blank2","","",""],
["numa_what_kind","you","","what kind of flower are you watering?","","","numa_blank2","","",""],
["numa_favorite","you","","what's your favorite kind of flower?","","","numa_blank2","","",""],
["numa_blank2","numa","","um, i dunno","","","","","",""],
["","you","","uhh","","","","","",""],
["","","","","","","","",['you don\'t talk much', 'bye for now'],['numa_talk_much', 'numa_bye']],
["numa_talk_much","you","","you don't talk much, do you?","","","","","",""],
["","numa","","[i]shrug[/i]","","","","","",""],
["numa_bye","you","","bye for now, i guess","","","","","",""],
["","","","enjoy gardening!","","","","","",""],
["","numa","","thanks!","","","","","",""],
["","","","enjoy, um, whatever you're doing.","","","","","",""],
["","you","","thanks","","","null","","",""],
["numa_intro2","_none","","maybe you should give her some space for now.","","","null","","",""],
["numa_leave","numa","numa_neutral","HEY! WATCH YOUR STEP!","surprise_audio","","","","",""],
["","_none","","you freeze with your foot in the air.","nearly_trampled_flower","","","","",""],
["","numa","","you almost stepped on a tulip!","","","","","",""],
["","","","do you know how hard it is to grow those in here??","","","","","",""],
["","you","","oh, sorry...","","","","","",""],
["","numa","","...","","","","","",""],
["","","","i'm sorry, i didn't mean to yell","","","","","",""],
["","","","what i meant was [i]please[/i] watch your step","","","","","",""],
["","","","if you don't mind.","","","","","",""],
["","you","","um, okay","","","","","",""],
["","","","i'll try not to step on anything","","","","","",""],
["","numa","","just, stay on the path from now on","","","","","",""],
["","you","","ok","","","","","",""],
["","numa","","thanks.","","","null","","",""],
["numa_default","_none","_none","_pass","","numa_quest_complete",['ks_and_numa_commons', 'numa_default2'],"","",""],
["numa_default2","numa","numa_neutral","oh, hey...","","","","","",""],
["numa_default_c1","","","_pass","","numa_pissed_off and not numa_snooped",['numa_default_taciturn', 'numa_default_c2'],"","",""],
["numa_default_c2","","","_pass","","numa_snooped and not numa_followed_up",['numa_follow_up', 'numa_default_main'],"","",""],
["numa_default_taciturn","","","","","","",['true', 'elijah_planning_slam and not invited_numa', 'true', 'true', 'true'],['what\'s up?', '(invite numa to the everything slam)', 'how\'s the gardening?', 'you must really care about those flowers', 'have you met the others?'],['numa_dot', 'numa_invitation', 'numa_dot', 'numa_dot', 'numa_dot']],
["numa_default_main","","","","","","",['true', 'elijah_planning_slam and not invited_numa', 'numa_snooped', 'true', 'true', 'not numa_snooped'],['what\'s up?', '(invite numa to the everything slam)', 'about kyungsoon...', 'how\'s the gardening?', 'you must really care about those flowers', 'have you met the others?'],['numa_wasup', 'numa_invitation', 'numa_ks', 'numa_how', 'numa_protective', 'numa_others']],
["numa_others","you","","have you met oliver and kyungsoon?","numa_asked_about_others","","","","",""],
["","_none","","numa nods.","","","","","",""],
["","you","","you must get to know each other pretty well when you're stuck in purrgatory together.","","","","","",""],
["","numa","","um, yeah, sort of!","","","","","",""],
["","","","except, um...","","","","","",""],
["","","","...","","","","","",""],
["","you","","yes?","","","","","",""],
["","numa","","well, kyungsoon, i haven't...","","","","","",""],
["","","","...","","","","","",""],
["","you","","what about kyungsoon?","","","","","",""],
["","numa","","uhhhhh...","","","","","",""],
["","you","","is... something wrong?","","","","","",""],
["","numa","","no no no, nothing like that!","","","","","",""],
["","","","aaa never mind, forget i said anything ;;","","","","","",""],
["","you","","uh, alright","","","null","","",""],
["numa_wasup","you","","what's up?","","",['_rand', 'numa_wasup1', 'numa_wasup2', 'numa_wasup3', 'numa_wasup4', 'numa_wasup5', 'numa_wasup6', 'numa_wasup7', 'numa_wasup8', 'numa_wasup9', 'numa_wasup10', 'numa_wasup11', 'numa_wasup12', 'numa_wasup13', 'numa_wasup14', 'numa_wasup15', 'numa_wasup16', 'numa_wasup17', 'numa_wasup18', 'numa_wasup19', 'numa_wasup20'],"","",""],
["numa_wasup1","numa","","um, just gardening things, haha","","","","","",""],
["","you","","haha","","","null","","",""],
["numa_wasup2","numa","","wish i had some sunscreen...","","","","","",""],
["","you","","but","","","","","",""],
["","","","there's no sun in purrgatory?","","","","","",""],
["","numa","","my skin is very sensitive ;;","","","null","","",""],
["numa_wasup3","numa","","um, the petunias are blooming nicely this time of year!","","","","","",""],
["","you","","oh, that's nice!","","","","","",""],
["","","","which ones are the petunias?","","","","","",""],
["","numa","","oh, um...","","","","","",""],
["","","","actually, we don't have any petunias","","","","","",""],
["","you","","oh","","","","","",""],
["","","","but didn't you say...?","","","","","",""],
["","numa","","i got nervous and lied","","","","","",""],
["","","","sorry ;;","","","null","","",""],
["numa_wasup4","numa","","oh, just watering this flower!","","","","","",""],
["","you","","haven't you been watering that flower for a while?","","","","","",""],
["","numa","","um, yeah","","","","","",""],
["","","","it takes a lot of water","","","null","","",""],
["numa_wasup5","numa","","time passes slowly in purrgatory...","","","","","",""],
["","","","even for a snail","","","null","","",""],
["numa_wasup6","numa","","i miss solving sudokus...","","","","","",""],
["","you","","are there no sudokus in purrgatory?","","","","","",""],
["","numa","","nope","","","","","",""],
["","","","only tic tac toe...","","","null","","",""],
["numa_wasup7","numa","","i hope my garden back at home is doing okay...","","","","","",""],
["","you","","do you think someone else is taking care of it?","","","","","",""],
["","numa","","maybe!","","","","","",""],
["","","","although my brothers don't really have any interest in gardening","","","","","",""],
["","","","and my mom is probably too busy","","","","","",""],
["","","","and my dad always wanted to dig it up to build a patio...","","","","","",""],
["","you","","oh","","","","","",""],
["","numa","","but you know, maybe they had a change in heart? ;;","","","null","","",""],
["numa_wasup8","numa","","i'm worried about the soil content here","","","","","",""],
["","","","i think it might be too sandy","","","","","",""],
["","you","","i'm [i]sand[/i] to hear that","","","","","",""],
["","numa","","oh, um, good one","","","","","",""],
["","","","haha","","","null","","",""],
["numa_wasup9","numa","","i've been thinking about pruning the bushes","","","","","",""],
["","","","i never did much with bushes when i was alive, but i heard it's supposed to help them grow","","","","","",""],
["","","","i think","","","","","",""],
["","you","","you should go for it!","","","","","",""],
["","numa","","yeah, but how much should i prune?","","","","","",""],
["","","","and from what part of the plant?","","","","","",""],
["","","","what tool do do i use??","","","","","",""],
["","","","what if i kill them by accident???","","","","","",""],
["","you","","uhhh","","","","","",""],
["","numa","","no, it's too scary, i can't ;;","","","null","","",""],
["numa_wasup10","numa","","um, i don't know","","","","","",""],
["","","","i'm tired","","","","","",""],
["","you","","me too","","","null","","",""],
["numa_wasup11","numa","","my therapist used to tell me to relax my muscles every now and then","","","","","",""],
["","you","","oh, that's a good idea!","","","","","",""],
["","","","are you doing it now?","","","","","",""],
["","numa","","uhhh","","","","","",""],
["","you","","you should relax your muscles","","","","","",""],
["","numa","","i'm,,, i'm trying","","","","","",""],
["","you","","what's so hard about it? just relax!","","","","","",""],
["","numa","","AAA I'M SORRY I'M TRYING","","","null","","",""],
["numa_wasup12","numa","","gosh, i could really use some ph strips...","numa_mentioned_ph_strips","","","","",""],
["","you","","what kind of garden doesn't even have ph strips?","","","","","",""],
["","numa","","RIGHT??","","","null","","",""],
["numa_wasup13","numa","","did you know dragonflies have existed for 300 million years?","","","","","",""],
["","you","","cool!","","","","","",""],
["","numa","","bug fact!!","","","null","","",""],
["numa_wasup14","numa","","did you know fruit flies were the first animals to go to space?","","","","","",""],
["","you","","wow, really?","","","","","",""],
["","numa","","that's a bug fact!!","","","null","","",""],
["numa_wasup15","numa","","did you know caterpillars have 12 eyes?","","","","","",""],
["","you","","oh wow","","","","","",""],
["","numa","","bam, bug fact!!","","","null","","",""],
["numa_wasup16","numa","","you know, i never thought my pet fish would outlive me...","","","","","",""],
["","you","","i don't think it would have enjoyed purrgatory very much","","","","","",""],
["","numa","","haha, i guess not","","","null","","",""],
["numa_wasup17","numa","","i should start my purrgatory mood tracker again...","","","","","",""],
["","you","","what's that?","","","","","",""],
["","numa","","it's when you write down how you feel every day!","","","","","",""],
["","","","um, it helps with tracking mental health and stuff, haha","","","","","",""],
["","you","","ah, why did you stop?","","","","","",""],
["","numa","","well... it turned out my mood was the same every day","","","","","",""],
["","you","","oh, makes sense","","","null","","",""],
["numa_wasup18","numa","","AAAA","","","","","",""],
["","you","","ah what's wrong?!","","","","","",""],
["","numa","","oh, sorry, you caught me by surprise ;;","","","","","",""],
["","you","","oh","","","","","",""],
["","","","jesus","","","null","","",""],
["numa_wasup19","numa","","it's probably a good thing there's no coffee in purrgatory...","","","","","",""],
["","","","i used to drink it a lot...","","","","","",""],
["","you","","yeah, i could see that","","","null","","",""],
["numa_wasup20","numa","","do you know any bug facts?","","","","","",""],
["","you","","ummm","","","","","",""],
["","","","idk, only boring ones","","","","","",""],
["","numa","","oh great, i love wood-boring beetles!","","","","","",""],
["","","","haha","","","","","",""],
["","","","um, get it?","","","","","",""],
["","you","","oh i see what you did there lol","","","null","","",""],
["numa_how","you","","how's the gardening going?","","","","","",""],
["","numa","","oh, the flowers are doing well!","","","","","",""],
["","","","it's, um, tough caring for flowers that don't exist anywhere on the mortal plane","","","","","",""],
["","","","but you know, i'm making do!","","","","","",""],
["","","","watching shade levels, experimenting with mulching, um... you know. that sort of stuff","","","","","",""],
["","you","","sounds awesome","","","","","",""],
["","numa","","haha um","","","","","",""],
["","","","yeah","","","","","",""],
["","","","","","","","",['were you a gardener in real life?', 'do you spend all your time here?'],['numa_gardener', 'numa_time']],
["numa_time","you","","do you spend all your time gardening?","","","","","",""],
["","numa","","yeah, most of it","","","","","",""],
["","","","usually i'm here or in my room.","","numa_snooped",['numa_time1', 'numa_time2'],"","",""],
["numa_time1","numa","","but um...","","","","","",""],
["","","","you already know about that","","","","","",""],
["","you","","oh, uh, yeah","","","","","",""],
["","","","sorry","","","null","","",""],
["numa_time2","you","","wait, you have a room?","","","","","",""],
["","numa","","yeah, i made a little room for myself in the vent system!","","","","","",""],
["","you","","huh, cool","","","","","",""],
["","numa","","so if you ever hear noises in the wall, you know who it is!","","","","","",""],
["","","","haha","","","","","",""],
["","","","um, just kidding","","","","","",""],
["","","","aa that was weird wasn't it, sorry","","","","","",""],
["","you","","lol it's okay","","","null","","",""],
["numa_protective","you","","you must really care about those flowers","","","","","",""],
["","numa","","um, yeah, i guess","","","","","",""],
["","","","sorry about earlier","","","","","",""],
["","","","again","","","","","",""],
["","","","sometimes i just get a little protective ;;","","","","","",""],
["","you","","aw, it's okay","","","","","",""],
["","","","do people step on them a lot?","","","","","",""],
["","numa","","well... not really","","","","","",""],
["","","","but you can never be too careful!","","","","","",""],
["","","","","","","","",['guess you nipped that problem in the bud', 'maybe you should try to relax', '(pretend to step on a flower)'],['numa_bud', 'numa_loose', 'numa_pretend']],
["numa_bud","you","","well, i guess you nipped that problem in the [i]bud[/i]","","","","","",""],
["","numa","","...","","","","","",""],
["","","","heh","","","","","",""],
["","you","","hehe","","","null","","",""],
["numa_loose","you","","maybe you should try to relax a little!","","","","","",""],
["","","","no offense, but you seem a little stressed","","","","","",""],
["","numa","","but gardening is relaxing","","","","","",""],
["","you","","ah, i see","","","","","",""],
["","numa","","it's just","","","","","",""],
["","","","SO RELAXING.","","","","","",""],
["","","","i'm SO RELAXED right now.","","","","","",""],
["","you","","um... i see","","","null","","",""],
["numa_pretend","you","","what if i did this?","numa_pissed_off","","","","",""],
["","_none","","you lift your foot in preparation to squash a flower.","","","","","",""],
["","numa","","don't","","","","","",""],
["","","","you","","","","","",""],
["","","","DARE","","","","","",""],
["","_none","","you uneasily retract your foot.","","","","","",""],
["","you","","...aw, i'm just teasing","","","","","",""],
["","","","i wasn't actually going to do it.","","","","","",""],
["","numa","","...","","","null","","",""],
["numa_dot","numa","","...","","","","","",""],
["","_none","","it looks like she doesn't want to talk to you anymore.","","","null","","",""],
["numa_gardener","you","","were you a gardener in real life, too?","","","","","",""],
["","numa","","well, i had a backyard garden!","","","","","",""],
["","","","i like to think i was pretty good at it, but, um","","","","","",""],
["","","","as a job, i was an intern at an accounting firm","","","","","",""],
["","you","","oh, i see","","","","","",""],
["","","","did you like accounting?","","","","","",""],
["","numa","","oh, yeah!","","","","","",""],
["","","","i mean, aren't all the cool kids into accounting? haha","","","","","",""],
["","","","","","","","",['i would have liked being an accountant', 'what do accountants do anyway?'],['numa_job', 'numa_cool']],
["numa_cool","you","","what kind of stuff do accountants do, anyway?","","","","","",""],
["","numa","","well, in a broad sense, they're in charge of keeping financial records!","","","","","",""],
["","","","i worked at a public accounting firm, which means businesses would come to us to prepare their financial statements and advise them on future transactions","","","","","",""],
["","","","it's really important work!","","","","","",""],
["","","","um, i was just an intern though, so mostly i did data entry","","","","","",""],
["","you","","cool","","","","","",""],
["","","","does that mean you could do my taxes?","","","","","",""],
["","numa","","oh, um, no, that's a different type of accounting","","","","","",""],
["","","","sorry","","","","","",""],
["","you","","oh okay","","","null","","",""],
["numa_job","you","","i think i would have liked being an accountant. ","","","","","",""],
["","","","i always liked numbers and stuff","","","","","",""],
["","numa","","oh, yeah, me too!","","","","","",""],
["","","","making spreadsheets was my favorite part of the job, haha","","","","","",""],
["","","","i know that's kinda dumb","","","","","",""],
["","you","","nah, spreadsheets are awesome!","","","","","",""],
["","numa","","aaa do you think so?","","","","","",""],
["","you","","yeah, totally","","","","","",""],
["","","","what kind of accounting did you do?","","","","","",""],
["","numa","","well, i worked at a public accounting firm, which means business would come to us to prepare their financial statements for them and advise them on future transactions","","","","","",""],
["","","","it's really important work!","","","","","",""],
["","","","um, i was just an intern though, so mostly i did data entry","","","","","",""],
["","","","but i wanted to be a CPA later in life!","","","","","",""],
["","","","i know, it's kind of boring...","","","","","",""],
["","you","","nah, that's really cool","","","","","",""],
["","numa","","aw, thanks :)","","","null","","",""],
["snoop","numa","numa_neutral","{player}?",[['met_numa', true], ['surprise_audio', true]],"","","","",""],
["","_none","","you stop short as you run into numa in the vents.","","","","","",""],
["","numa","","what are YOU doing in here?!","","","","","",""],
["","","","","","","","",['exploring', 'uhhh'],['snoop_sorry', 'snoop_dots']],
["snoop_sorry","you","","i was just exploring!","","","","","",""],
["","numa","","just [i]exploring[/i]? in someone else's room??","","","","","",""],
["","you","","i'm sorry, i didn't know...","","","snoop_1","","",""],
["snoop_dots","you","","uhhhhhhhh","","","","","",""],
["","numa","","were you snooping around in my room??","","","","","",""],
["snoop_1","numa","","i can't believe this!","","","","","",""],
["","","","you'd think screwing shut a door would be enough to keep people out","","","","","",""],
["","","","wait... you didn't read my notebook, did you??","","","","","",""],
["","","","","","","","",['yes', 'no'],['snoop_yes', 'snoop_no']],
["snoop_yes","you","","...yes, sorry","","","","","",""],
["","numa","","WHAT?!","","","","","",""],
["","you","","i'm sorry, i was curious! it wasn't embarrassing or anything!","","","","","",""],
["","numa","","THAT JOURNAL IS PRIVATE!","","","","","",""],
["","","","ASSHOLE!","numa_asshole","","","","",""],
["","you","","it was just a peek, i promise!","","","","","",""],
["","numa","","what the hell is wrong with you, going through someone's belongings like that?","","","","","",""],
["","","","oh god, did you see anything about--","","","","","",""],
["","","","about--","","","","","",""],
["","_none","","numa closes her eyes.","","","","","",""],
["","numa","","deep breaths, numa...","","","","","",""],
["","you","","i'm... i'm sorry numa, i didn't even think about what i was doing","","","","","",""],
["","","","it was wrong of me and i won't do it again.","","","","","",""],
["","numa","","...","","","","","",""],
["","","","it's... fine... i guess...","","","snoop_2a","","",""],
["snoop_no","you","","no, of course not!","","","","","",""],
["","numa","","okay, good.","","","","","",""],
["","","","because you shouldn't have!","","","","","",""],
["snoop_2a","you","","i'm sorry for asking, but...","","","","","",""],
["snoop_2","","","","","","",['not snoop_keeping_track', 'true', 'true'],['are you counting the days you\'ve been here?', 'is that a drawing of you and kyungsoon?', 'could you back up please'],['snoop_track', 'snoop_pic', 'snoop_back']],
["snoop_track","you","","are you counting the days you've been here?","snoop_keeping_track","","","","",""],
["","numa","","yeah. i guess.","","","","","",""],
["","you","","how come?","","","","","",""],
["","numa","","i don't know, i just have to keep track.","","","","","",""],
["","","","otherwise time just blends together and i hate it.","","","","","",""],
["","you","","i see","","","snoop_2","","",""],
["snoop_pic","you","","is that a drawing of you and kyungsoon?","","","","","",""],
["","numa","","no!","","","","","",""],
["","","","i mean, uh","","","","","",""],
["","","","maybe?","","","","","",""],
["","","","it's none of your business!","","","","","",""],
["","you","","sorry, sorry!","","","","","",""],
["","","","it's just... i didn't know you two were friends","","","","","",""],
["snoop_friends","numa","","well, we're not!","","","","","",""],
["","you","","girlfriends, then?","","","","","",""],
["","numa","","NO!","","","","","",""],
["","","","i mean, not that there would be anything wrong with that!","","","","","",""],
["","","","i mean--","","","","","",""],
["","_none","","numa covers her face.","","","","","",""],
["","numa","","aaaaaaaaaaa","","","","","",""],
["","you","","ohh, i get it","","","","","",""],
["","","","","","","","",['you have a crush on her', 'she has an identical twin'],['snoop_crush1', 'snoop_crush2']],
["snoop_crush1","you","","you have a crush on her!","","","","","",""],
["","numa","","OKAY, YES!","","","","","",""],
["","","","I HAVE A CRUSH ON KYUNGSOON!!","","","","","",""],
["","you","","i knew it!","","","snoop_crush3","","",""],
["snoop_crush2","you","","she has an identical twin!","","","","","",""],
["","numa","","...what?","","","","","",""],
["","","","no, i have a crush on her!","","","","","",""],
["","you","","...ohhh, that makes way more sense","","","","","",""],
["snoop_crush3","numa","","it's just that i can never work up the courage to talk to her even though i've been stuck here for YEARS","","","","","",""],
["","","","and i've never told anyone about it either because i'm afraid they'll leak the secret","","","","","",""],
["","","","i mean it's not like i can give her FLOWERS because they all smell HORRIBLE","","","","","",""],
["","","","aaaa i just don't know what to do!","","","","","",""],
["","_none","","numa puts her head in her hands.","","","","","",""],
["","numa","","why am i telling this to you of all people ;;","","","","","",""],
["","you","","it's okay, it's okay, i understand","","","","","",""],
["","","","stuff like that can be really stressful","","","","","",""],
["","numa","","tell me about it...","","","","","",""],
["snoop_c","","","","","","",['not snoop_fluffy', 'not snoop_offered_to_talk', 'true'],['but... why kyungsoon?', 'maybe i could talk to her for you', 'could you pleeease back up'],['snoop_attractive', 'snoop_talk', 'snoop_back3']],
["snoop_back","you","","could you, uh, back up please? ","","","","","",""],
["","","","there's not enough space to crawl past you","","","","","",""],
["","numa","","um, yeah. sure.","","","","","",""],
["","","","i was just wondering if you saw anything... you know... ","","","","","",""],
["","","","private","","","","","",""],
["","you","","private?","","","","","",""],
["","","","um... you mean that drawing of you and kyungsoon?","","","","","",""],
["","numa","","no!","","","","","",""],
["","","","i mean, uh","","","","","",""],
["","","","maybe?","","","","","",""],
["","you","","i mean, it's alright, there's nothing embarrassing about that!","","","","","",""],
["","","","although i didn't think you two were friends","","","snoop_friends","","",""],
["snoop_attractive","you","","but... i have to ask...","snoop_fluffy","","","","",""],
["","","","why kyungsoon?","","","","","",""],
["","numa","","what do you mean??","","","","","",""],
["","","","she's so tall... and mysterious...","","","","","",""],
["","","","and smart...","","","","","",""],
["","","","and pretty...","","","","","",""],
["","","","and... fluffy...","","","","","",""],
["","you","","huh","","","snoop_c","","",""],
["snoop_talk","you","","maybe i could talk to her for you and--","snoop_offered_to_talk","","","","",""],
["","numa","","DON'T YOU DARE!","","","","","",""],
["","","","i mean","","","","","",""],
["","_none","","numa takes another deep breath.","","","","","",""],
["","numa","","i mean, please don't do that.","","","","","",""],
["","you","","jeez, okay","","","","","",""],
["","numa","","sorry, it's just","","","","","",""],
["","","","if i'm going to tell her, i HAVE to do it myself","","","","","",""],
["","you","","i see...","","","snoop_c","","",""],
["snoop_back3","you","","could you pleeease back up so we can get out of this vent","","","","","",""],
["","numa","","oh, right","","","","","",""],
["","","","sorry, sorry...","","","","","",""],
["","_none","","numa backs up and you finally leave the vent","snoop_leave_vent","","","","",""],
["","numa","","...","","","","","",""],
["","you","","...","","","","","",""],
["","numa","","please don't tell anyone about this.","","","","","",""],
["","you","","my lips are sealed, i promise","","","","","",""],
["","numa","","can i have the screwdriver please","","","","","",""],
["","you","","here",[['_inv_screwdriver', false]],"","","","",""],
["","_none","","numa takes the screwdriver and hurries down the stairs.","","","null","","",""],
["numa_follow_up","you","","um","numa_followed_up","","","","",""],
["","","","hello","","","","","",""],
["","","","i'm really sorry about snooping around earlier","","","","","",""],
["","numa","","it's... fine.","","numa_asshole",['numa_follow_up1', 'numa_follow_up2'],"","",""],
["numa_follow_up1","","","sorry for calling you an asshole","","","numa_follow_up3","","",""],
["numa_follow_up2","","","sorry for blowing up at you","","","","","",""],
["numa_follow_up3","you","","it's okay","","","","","",""],
["","","","i probably deserved it","","","","","",""],
["","numa","","[i]shrug[/i]","","","","","",""],
["","you","","...","","","","","",""],
["","","","um... let me know if there's anything i can do to make up for it","","","","","",""],
["","numa","","sure","","","","","",""],
["","_none","","the two of you stand around awkwardly. then numa goes back to watering.","","","null","","",""],
["numa_ks","you","numa_neutral","so, about kyungsoon...","","numa_helping",['numa_gift_options', 'numa_plan'],"","",""],
["numa_plan","","","you still want to talk to her, right?","","","","","",""],
["","numa","","oh, yeah","","","","","",""],
["","","","um, sorry about venting to you about that","","","","","",""],
["","you","","heh, no pun intended?","","","","","",""],
["","numa","","huh?","","","","","",""],
["","","","oh. haha. no pun intended.","","","","","",""],
["","you","","think you'll talk to her soon?","","","","","",""],
["","numa","","i mean... i don't know.","","","","","",""],
["","","","i guess i want to make sure everything goes well","","","","","",""],
["","","","this is going to sound so stupid","","","","","",""],
["","","","i want to arrange a bouquet of flowers","","","","","",""],
["","","","and write her a poem","","","","","",""],
["","","","and get some food as a gift","","","","","",""],
["","","","but it's just so much work that i don't know where to get started...","","","","","",""],
["","","","","","","","",['i could help you with that', 'maybe you should just talk to her'],['numa_help', 'numa_talk']],
["numa_help","you","","i could try to help you with that!","numa_helping","","","","",""],
["","numa","","really?","","","","","",""],
["","you","","yeah, really!","","","","","",""],
["","","","consider it as making up for snooping around in your room","","","","","",""],
["","numa","","well...","","","","","",""],
["","","","maybe i [i]could[/i] use some help","_quest_numa_kyungsoon","","","","",""],
["","","","i guess it's pretty obvious that i'm not getting anywhere alone, huh? ;;","","","numa_gift_options","","",""],
["numa_talk","you","","you know, maybe you should just talk to her","","","","","",""],
["","","","i mean--","","","","","",""],
["","numa","","oh no no no, i can't do that","","","","","",""],
["","","","that's WAY too scary","","","","","",""],
["","you","","what is there to be afraid of?","","","","","",""],
["","","","we're already dead!","","","","","",""],
["","numa","","oh you know, just an ETERNITY of INESCAPABLE HUMILIATION","","","","","",""],
["","you","","...ah","","","","","",""],
["","numa","","yeah ;;","","","null","","",""],
["numa_gift_options","","","","","","",['numa_started_flowers or numa_started_poem or numa_started_food', 'true', 'true', 'true'],['ready to talk to her?', 'about the flowers...', 'about the poem...', 'about the food...'],['numa_ready?', 'numa_flowers_c', 'numa_poem_c', 'numa_food_c']],
["numa_flowers_c","","","_pass","","not numa_started_flowers",['numa_flowers1', 'numa_flowers_c2'],"","",""],
["numa_flowers_c2","","","_pass","","not numa_finished_flowers",['numa_flowers2', 'numa_flowers3'],"","",""],
["numa_flowers1","you","","do you need any help picking out flowers?","numa_started_flowers","","","","",""],
["","numa","","oh, yes please",[['flower_fails', 0]],"","","","",""],
["","","","i can visualize the arrangement in my head, but there are so many strange varieties in purrgatory that i have a hard time finding the ones i want ;;","","","","","",""],
["","you","","well, how about this one--","","","","","",""],
["","numa","","DON'T TOUCH THAT!","","","","","",""],
["","","","i mean","","","","","",""],
["","_none","","numa breathes deeply.","","","","","",""],
["","numa","","please don't touch them, they're fragile","","","","","",""],
["","","","just point at them","","","","","",""],
["","you","","okay, okay","","","","","",""],
["","","","i swear you're going to give me a heart attack one of these days...","","","","","",""],
["","numa","","sorry ;;","","","flowers_init","","",""],
["numa_flowers2","you","","let's give flower-picking another shot!","","flower_fails >= 2",['numa_flowers_skip', 'flowers_init'],"","",""],
["numa_flowers_skip","numa","","ummmmmmmm","","","","","",""],
["","","","you know, i appreciate you trying to help, but","","","","","",""],
["","","","it might be... faster... to do it by myself?","","","","","",""],
["","","","it's just, you know, i'm more familiar with the garden, and","","","","","",""],
["","","","you already tried a couple of times, and...","","","","","",""],
["","","","not that i think you're bad at finding flowers or anything, but...","","","","","",""],
["","","","you know...","","","","","",""],
["","","","","","","","",['let me try one more time!', 'okay, that\'s fair'],['numa_flowers_skip1', 'numa_flowers_skip2']],
["numa_flowers_skip1","you","","aw, just let me try one more time!","","","","","",""],
["","","","i think i can do it now","","","","","",""],
["","numa","","okay, one more time!","","","flowers_init","","",""],
["numa_flowers_skip2","you","","okay, that's fair","","","","","",""],
["","","","sorry i couldn't be more of a help","","","","","",""],
["","numa","","no no it's okay!","","","","","",""],
["","","","i really appreciate you trying ;;","numa_finished_flowers","","null","","",""],
["numa_flowers3","you","","how are the flowers?","","","","","",""],
["","numa","","oh, they're looking great!","","","","","",""],
["","you","","awesome","","","","","",""],
["","numa","","aaaaa i just hope she'll like them","","","","","",""],
["","","","if only they didn't smell like fish...","","","","","",""],
["","you","","well, if she likes the taste of paper, maybe she likes the smell of fish","","","","","",""],
["","numa","","maybe!!","","","null","","",""],
["numa_poem_c","","","_pass","","not numa_started_poem",['numa_poem1', 'numa_poem_c2'],"","",""],
["numa_poem_c2","","","_pass","","not numa_finished_poem",['numa_poem2', 'numa_poem3'],"","",""],
["numa_poem1","you","","how's that poem going?","numa_started_poem","","","","",""],
["","numa","","um, i think i could maybe use some help","","","","","",""],
["","","","creative writing was always one of my worst subjects...","","","","","",""],
["","you","","well, let's hear what you have so far!","","","","","",""],
["","numa","","are you sure?","","","","","",""],
["","","","it's not very good","","","","","",""],
["","","","actually, it's awful","","","","","",""],
["","","","actually it's pretty much the worst poem in the world","","","","","",""],
["","you","","aw, i'm sure it's not that bad","","","","","",""],
["","","","promise i won't judge","","","","","",""],
["","numa","","well, okay...","","","","","",""],
["","","","it goes like this:","","","","","",""],
["","","","roses are white","","","","","",""],
["","","","violets are white","","","","","",""],
["","","","to me, you are","","","","","",""],
["","","","a shining light","","","","","",""],
["","you","","sounds good so far!","","","","","",""],
["","numa","","aaa thank you","","","","","",""],
["","","","then it goes...","","","","","",""],
["","","","you are purple","","","","","",""],
["","","","soda is orange","","","","","",""],
["","","","...","","","","","",""],
["","","","that's all i have","","","","","",""],
["","","","nothing rhymes with orange ;;","","","","","",""],
["","you","","hmmmm....","","","","","",""],
["","","","","","","","",['and your face, i adore-enge', 'you pierce my heart, like a syringe', 'just switch the last two lines'],['numa_adore-enge', 'numa_syringe', 'numa_switch']],
["numa_adore-enge","you","","how about this","","","","","",""],
["","","","\"and your face, i adore-enge\"","","","numa_orange_after","","",""],
["numa_syringe","you","","how about this","","","","","",""],
["","","","\"you pierce my heart, like a syringe\"","","","numa_orange_after","","",""],
["numa_switch","you","","just switch the last two lines so you don't have to rhyme with orange!","","","","","",""],
["","","","\"soda is orange, you are purple\"","","","","","",""],
["","numa","","but what rhymes with purple?","","","","","",""],
["","you","","uhh","","","","","",""],
["","","","","","","","",['fizzy soda, i like to slurp-le', 'i got nothing'],['numa_slurp-le', 'numa_nothing']],
["numa_slurp-le","you","","\"fizzy soda, i like to slurp-le\"","","","numa_orange_after","","",""],
["numa_nothing","you","","i got nothing","","","numa_suit","","",""],
["numa_orange_after","numa","","...","","","","","",""],
["","","","that's definitely... creative!","","","","","",""],
["","you","","okay, it sucks","","","","","",""],
["numa_suit","you","","i guess poetry isn't my strong suit either","","","","","",""],
["","numa","","[i]sigh[/i]","","","","","",""],
["","","","i'm never going to finish this poem","","","","","",""],
["","","","maybe i should just stick to spreadsheets...","","","","","",""],
["","you","","don't give up yet, maybe you'll think of something!","","","","","",""],
["","","","or maybe we can find someone else to help?","","","","","",""],
["","numa","","who else would be willing to help with something like this?","","","","","",""],
["","you","","hmm...","","","","","",""],
["","","","i don't know, i'll think about it...","","","","","",""],
["","numa","","thanks, i guess...","","","null","","",""],
["numa_poem2","you","","any progress on the poem?","","","","","",""],
["","numa","","not yet, sorry","","","","","",""],
["","","","i still can't think of the next line","","","","","",""],
["","","","i know, it's so stupid ;;","","","","","",""],
["","you","","it's alright, take your time","","","","","",""],
["","","","maybe i can find someone else to help you...","","","null","","",""],
["numa_poem3","you","","was talking to elijah helpful?","","","","","",""],
["","numa","","oh, absolutely!","","","","","",""],
["","","","i'm just putting some final touches on the poem now","","","","","",""],
["","you","","can i hear it?","","","","","",""],
["","numa","","sure! ","","","","","",""],
["","","","here's a little excerpt:","","","","","",""],
["","","","you are purple","","","","","",""],
["","","","i am smitten","","","","","",""],
["","","","you're as cute","","","","","",""],
["","","","as a kitten!","ks_heard_cute_as_kitten","","","","",""],
["","you","","nice!","","","","","",""],
["","numa","","i know, it's so good!!","","","","","",""],
["","","","thanks again for your help :)","","","","","",""],
["","you","","it's nothing, really!","","","null","","",""],
["numa_food_c","","","_pass","","not numa_started_food",['numa_food1', 'numa_food_c2'],"","",""],
["numa_food_c2","","","_pass","","not numa_progressed_food",['numa_food2', 'numa_food_c3'],"","",""],
["numa_food_c3","","","_pass","","not numa_finished_food",['numa_food3', 'numa_food4'],"","",""],
["numa_food1","you","","what are you doing about food?","numa_started_food","","","","",""],
["","numa","","um, i guess i haven't really thought about it","","","","","",""],
["","","","i don't even know what kind of food she likes...","","","","","",""],
["","","","","","","","",['books', 'keys', 'signs'],['numa_books', 'numa_keys', 'numa_signs']],
["numa_books","you","","i heard she likes to eat books","","","","","",""],
["","numa","","books? really?","","","","","",""],
["","","","i guess i could give her my notebook...","","","","","",""],
["","you","","uh, are you sure you want her reading all of your personal writing?","","","numa_bad","","",""],
["numa_keys","you","","i heard she likes to eat keys","","","","","",""],
["","numa","","keys? really?","","","","","",""],
["","","","well, i guess i could give her my screwdriver, which is kind of like a key...","","","","","",""],
["","you","","uh, don't you need that to get into your room?","","","numa_bad","","",""],
["numa_signs","you","","i heard she likes to eat signs","","","","","",""],
["","numa","","signs? really?","","","","","",""],
["","","","i guess i could get that meowseum sign for her...","","","","","",""],
["","you","","uh, i'm not sure if the paint on that is safe to eat...","","","numa_bad","","",""],
["numa_bad","numa","","oh, yeah","","","","","",""],
["","","","aaa you're right, that was stupid","","","","","",""],
["","you","","no, it's okay!","","","","","",""],
["","numa","","weh ;;","","","","","",""],
["","you","","maybe i could talk to kyungsoon and find out what she likes?","","","","","",""],
["","numa","","oh, that would definitely be helpful!","","","","","",""],
["","","","just try to be discreet about it, please...","","","","","",""],
["","you","","i'll do my best!","","","null","","",""],
["numa_food2","you","","why don't you give kyungsoon some of that fruit in the other room?","","","","","",""],
["","","","it looks pretty tasty","","","","","",""],
["","numa","","oh, those are deathberries","","","","","",""],
["","","","don't eat those","","","","","",""],
["","","","you'll be sick for weeks","","","","","",""],
["","you","","oh","","","","","",""],
["","numa","","by the way, have you found out what food she likes yet?","","","","","",""],
["","you","","not yet!","","","","","",""],
["","numa","","okay, no rush...","","","null","","",""],
["numa_food3","you","","i asked kyungsoon about her favorite food!","","","","","",""],
["","numa","","oh, really? what did she say??","","","","","",""],
["","you","","she said it's leaves!","","","","","",""],
["","numa","","no way, that's awesome!","","","","","",""],
["","","","there's a ton of leaves in the park... i'll start gathering them ASAP!","","","","","",""],
["","you","","great!","","","","","",""],
["","numa","","oh, they're all dead and shriveled though","","","","","",""],
["","","","they probably won't taste very  good","","","","","",""],
["","","","oh no, what if that gives her the wrong impression??","","","","","",""],
["","you","","it's okay, it's the thought that counts!","","","","","",""],
["","","","probably","","","","","",""],
["","numa","","that's not very reassuring ;;","numa_finished_food","","null","","",""],
["numa_food4","you","","is the food all ready?","","","","","",""],
["","numa","","yep, i'm almost done gathering the tastiest looking leaves for her!","","","","","",""],
["","you","","i guess i'll just [i]leaf[/i] you to it, then","","","","","",""],
["","numa","","haha... good one","","","null","","",""],
["numa_ready?","you","","are you ready to talk to her yet?","","numa_finished_flowers and numa_finished_poem and numa_finished_food",['numa_ready', 'numa_not_ready'],"","",""],
["numa_not_ready","numa","","oh no, not yet!","","not numa_finished_flowers",['numa_r_flowers', 'numa_r_c1'],"","",""],
["numa_r_flowers","","","i still haven't picked out the right flowers for her...","","","","","",""],
["numa_r_c1","","","_pass","","not numa_finished_poem",['numa_r_poem', 'numa_r_c2'],"","",""],
["numa_r_poem","","","i haven't finished the poem yet...","","","","","",""],
["numa_r_c2","","","_pass","","not numa_finished_food",['numa_r_food', 'numa_r_end'],"","",""],
["numa_r_food","","","i don't even know what food to get her!","","","","","",""],
["numa_r_end","numa","","everything needs to be perfect","","","","","",""],
["","you","","hm, okay","","","null","","",""],
["numa_ready","numa","","well...","","","","","",""],
["","","","i guess i have everything ready...","","","","","",""],
["","_none","","numa looks over a bouquet of flowers, a handwritten card, and a basket of leaves.","","","","","",""],
["","numa","","it's just","","","","","",""],
["","","","she's so pretty and confident and smart and,,,","","","","","",""],
["","","","she could do so much better than me, you know?","","","","","",""],
["","you","","no way numa, you've got this","","","","","",""],
["","","","she's going to be blown away by all the gifts","","","","","",""],
["","","","i mean, look at how much effort you've put into them!","","","","","",""],
["","numa","","but what if she thinks i'm coming off too strong?","","","","","",""],
["","","","what if she thinks i'm weird??","","","","","",""],
["","","","what if she never wants to talk to me again?","","","","","",""],
["","","","oh god aaaaaaaaa","","","","","",""],
["","","","i don't think i can do this ;;","","","","","",""],
["","you","","listen... don't worry about seeming weird","","","","","",""],
["","","","you couldn't possibly be as weird as kyungsoon","","","","","",""],
["","","","you can be weird together!","","","","","",""],
["","","","like two peas in a weird pod","","","","","",""],
["","numa","","sure...","","","","","",""],
["","","","two peas in a... weird pod...","","","","","",""],
["","you","","okay, maybe that wasn't my best metaphor, but it's too late to back out anyway!","","","","","",""],
["","","","come on, let's head to the commons","","","","","",""],
["","_none","","numa takes a deep breath and gathers up the gifts in her arms.","","","","","",""],
["","numa","","OKAY!! let's do this!!!!","","","","","",""],
["","_none","numa_neutral","the two of you walk to the commons.","numa_goto_commons","","","","",""],
["","you","","are you ready?","","","","","",""],
["","_none","","numa shakes her head.","","","","","",""],
["","you","","go on, it'll be over soon!","","","","","",""],
["","","","just go in and tell her you like her","","","","","",""],
["","numa","","that's easy enough to say!","","","","","",""],
["","you","","just don't think about it! go in!!","","","","","",""],
["","numa","","you're right, you're right","","","","","",""],
["","","","i... i can do this!","","","","","",""],
["","_none","","numa takes a deep breath, then bursts through the door.",[['_quest_numa_kyungsoon', false]],"","","","",""],
["","numa","_none","KYUNGSOON!","","","","","",""],
["","kyungsoon","","hm?","","","","","",""],
["","numa","","i, um, i just wanted to, uh...","","","","","",""],
["","kyungsoon","","...","","","","","",""],
["","numa","","what i mean is","","","","","",""],
["","","","kyungsoon i, i, i have something to tell you!!","","","","","",""],
["","kyungsoon","","yeah?","","","","","",""],
["","_none","","you hear the library doors open.","oliver_hears_numa","","","","",""],
["","oliver","","i heard yelling, is everything okay out here?","","","","","",""],
["","","","oh, hi numa!","","","","","",""],
["","","","what's all that stuff for?","","","","","",""],
["","numa","","oh, haha, it's, um, it's just...","","","","","",""],
["","oliver","","oh jeez, what's that smell? ","","","","","",""],
["","","","is that the flowers?","","","","","",""],
["","numa","","aaa i'm sorry","","","","","",""],
["","oliver","","no no, it's okay","","","","","",""],
["","","","i just always forget how bad they smell...","","","","","",""],
["","kyungsoon","","oliver shut up about the gross flowers","","","","","",""],
["","","","she was gonna tell me something","","","","","",""],
["","oliver","","oh, well don't let me get in the way!","","","","","",""],
["","","","go ahead, numa","","","","","",""],
["","numa","","uhhhhhhhhhhh i don't think i...","","","","","",""],
["","oliver","","go on!","","","","","",""],
["","numa","","kyungsoon...","","","","","",""],
["","","","i...","","","","","",""],
["","","","...","commons_flowers","","","","",""],
["","_none","","you hear the sound of flowers hitting the floor, then numa bursts through the door.","_quest_numa_friendship","","","","",""],
["","numa","numa_neutral","AAAAAAAAAAAAAAAA","_anim_right_to_left_run","","","","",""],
["","you","_none","numa??","_anim_default","","","","",""],
["","oliver","","...","","","","","",""],
["","kyungsoon","","...","","","","","",""],
["","oliver","","what was all that about?","","","","","",""],
["","kyungsoon","","iuno","numa_crying","","null","","",""],
["numa_cry","_none","","you can hear the faint sound of crying through the vent.","","","","","",""],
["","you","","numa?","","not numa_consoled",['numa_cry_console', 'numa_cry_silent'],"","",""],
["numa_cry_console","numa","","go away!","numa_consoled","","","","",""],
["","","","","","","","",['don\'t feel bad', 'do you want to talk about it?', 'you really messed that up'],['numa_cry_feel', 'numa_cry_talk', 'numa_cry_mess']],
["numa_cry_silent","numa","","...","","","","","",""],
["","_none","","seems like she doesn't want to talk.","","","null","","",""],
["numa_cry_feel","you","","don't feel bad!","","","","","",""],
["","","","you tried your best, and it's not your fault that oliver got in the way","","","","","",""],
["","numa","","...","","","","","",""],
["","you","","i bet kyungsoon is really enjoying those leaves!","","","","","",""],
["","numa","","...","","","","","",""],
["","you","","i think she liked the flowers?","","","","","",""],
["","numa","","she called them gross!","","","","","",""],
["","you","","gross in... a good way?","","","","","",""],
["","","","like how bad used to mean good in the eighties?","","","","","",""],
["","numa","","...","","","","","",""],
["","","","","","","","",['totally gross, duude', '(just cut your losses)'],['numa_cry_gross', 'numa_cry_end']],
["numa_cry_gross","you","","like, that's totally gross, duuude","","","","","",""],
["","_none","","you hear a strangled sound that might have been laughter.","","","","","",""],
["numa_cry_end","_none","","it doesn't seem like she's coming out any time soon.","","","null","","",""],
["numa_cry_talk","you","","do you want to talk about it?","","","","","",""],
["","numa","","no!","","","","","",""],
["","you","","maybe later?","","","","","",""],
["","numa","","i'm going to stay in here","","","","","",""],
["","","","for ETERNITY","","","","","",""],
["","you","","no, don't do that!!","","","","","",""],
["","numa","","...","","","numa_cry_end","","",""],
["numa_cry_mess","you","","you really messed that up","","","","","",""],
["","numa","","i know that already!","","","","","",""],
["","","","i mess up everything!!","","","","","",""],
["","you","","that's a mood","","","","","",""],
["","_none","","you hear numa start crying harder.","","","","","",""],
["","","","she's definitely not coming out now.","","","null","","",""],
["numa_invitation","you","","hey, have you heard about the everything slam?","invited_numa","","","","",""],
["","numa","","everything slam? what's that?","","","","","",""],
["","you","","it's like a poetry slam, but people can do music or art or anything they want!","","","","","",""],
["","","","we're going to be doing it in the commons, and we'll ring the bell when it's about to start","","","","","",""],
["","","","do you want present something?","","","","","",""],
["","numa","","oh, um","","","","","",""],
["","","","i'm flattered, but, i don't know","","","","","",""],
["","","","i'm not good at any kind of art, really...","","","","","",""],
["","you","","well, i was thinking you might like putting on a gardening show!","","","","","",""],
["","numa","","oh... is that something i could do?","","","","","",""],
["","you","","if you want!","","","","","",""],
["","numa","","well, i think that would be fun!","","","","","",""],
["","","","people around here could definitely learn a thing or two about repotting... and soil analysis... and seed germination...","","","","","",""],
["","you","","awesome!","","","","","",""],
["","numa","","oh my gosh, i have so many ideas already","","","","","",""],
["","","","i need to put together a program ASAP!","","numa_snooped",['numa_invitation1', 'numa_invitation2'],"","",""],
["numa_invitation1","numa","","but...","","","","","",""],
["","","","i don't know... what if no one's interested?","","","","","",""],
["","","","aaa imagine if my presentation bored everyone to death","","","","","",""],
["","","","that would be so embarrassing ;;","","","","","",""],
["","you","","hm...","","","","","",""],
["","","","you know, kyungsoon will be there","","","","","",""],
["","numa","","really??","","","","","",""],
["","","","okay, i'll do it!","","","","","",""],
["","you","","hehe, that's the spirit!","","","","","",""],
["","numa","","i just hope she likes soil analysis...","","","null","","",""],
["numa_invitation2","you","","i'll leave you to it, then","","","","","",""],
["","numa","","ok!","","","","","",""],
["","","","see you there, {player}!","","","","","",""],
["","you","","seeya!","","","null","","",""]
]