extends Node

var raw_blocks = [
["talk_to_numa","_none","_none","_pass","","not met_numa",['numa_intro1', 'numa_c'],"","",""],
["numa_c","","","_pass","","trample_flag",['numa_intro2', 'numa_default'],"","",""],
["numa_intro1","","","_pass","","met_numa",['numa_intro1_alt', 'numa_intro1_normal'],"","",""],
["numa_intro1_normal","you","numa_neutral","hey!","met_numa","","","","",""],
["","???","","oh, hey! ","trample_flag","","","","",""],
["","","","um, you must be new","","","","","",""],
["","you","","yep","","","","","",""],
["","","","what are you doing?","","","","","",""],
["","???","","oh, you know. gardening.","","","","","",""],
["","","","i guess that's kinda obvious. haha. sorry.","","","","","",""],
["","you","","uh, it's ok","","","","","",""],
["","","","i'm {player}. what's your name?","","","","","",""],
["","???","","numa","","","numa_intro1_combined","","",""],
["numa_intro1_alt","you","numa_neutral","hey!","","","","","",""],
["","numa","","oh, hey! ","","","","","",""],
["","","","um, {player}, right?","","","","","",""],
["","you","","yep that's me","","","","","",""],
["","","","what are you up to?","","","","","",""],
["","numa","","oh, you know. gardening.","","","","","",""],
["","","","i guess that's kinda obvious. haha. sorry.","","","","","",""],
["","you","","uh, it's ok","","","","","",""],
["numa_intro1_combined","","","","","","","",['it\'s cool that purrgatory has a garden', 'i can\'t believe plants can grow here', 'your flowers smell kind of bad'],['numa_garden', 'numa_grow', 'numa_smell']],
["numa_garden","you","","it's cool that purrgatory has a garden","","","numa_blank1","","",""],
["numa_grow","you","","i can't believe plants can grow here","","","numa_blank1","","",""],
["numa_smell","you","","your flowers smell kind of bad…","","","numa_blank1","","",""],
["numa_blank1","numa","","uh, yeah. i guess","","","","","",""],
["","","","","","","","",['what are you going to do with these flowers?', 'what kind of flower is that?', 'what\'s your favorite kind of flower?'],['numa_do_what', 'numa_what_kind', 'numa_favorite']],
["numa_do_what","you","","what are you planning on doing with those flowers?","","","numa_blank2","","",""],
["numa_what_kind","you","","what kind of flower are you watering?","","","numa_blank2","","",""],
["numa_favorite","you","","what's your favorite kind of flower?","","","numa_blank2","","",""],
["numa_blank2","numa","","um, i dunno. ","","","","","",""],
["","you","","uhh","","","","","",""],
["","","","","","","","",['you don\'t talk much', 'bye for now'],['numa_talk_much', 'numa_bye']],
["numa_talk_much","you","","you don't talk much, do you?","","","","","",""],
["","_none","","numa shrugs.","","","","","",""],
["numa_bye","you","","bye for now, i guess","","","","","",""],
["","","","enjoy gardening!","","","","","",""],
["","numa","","thanks!","","","","","",""],
["","","","enjoy, um, whatever you're doing.","","","","","",""],
["","you","","thanks","","","null","","",""],
["numa_intro2","_none","","maybe you should give her some space for now.","","","null","","",""],
["numa_leave","numa","numa_neutral","HEY! watch your step!!","surprise_audio","","","","",""],
["","_none","","you freeze with your foot in the air.","nearly_trampled_flower","","","","",""],
["","numa","","you almost stepped on a tulip!","","","","","",""],
["","","","do you know how hard it is to grow those in here??","","","","","",""],
["","you","","oh, sorry...","","","","","",""],
["","_none","","numa takes a deep breath.","","","","","",""],
["","numa","","sorry, i didn't mean to yell","","","","","",""],
["","","","what i meant was [i]please[/i] watch your step","","","","","",""],
["","","","if you don't mind.","","","","","",""],
["","you","","um, okay","","","","","",""],
["","","","i'll try not to step on anything","","","","","",""],
["","numa","","just, stay on the path from now on","","","","","",""],
["","you","","ok","","","","","",""],
["","numa","","thanks.","","","null","","",""],
["numa_default","_none","_none","_pass","","numa_quest_complete",['ks_and_numa', 'numa_default2'],"","",""],
["numa_default2","_none","numa_neutral","the rancid smell of the flowers assaults you once more.","","","","","",""],
["numa_default_c1","","","_pass","","numa_pissed_off and not numa_snooped",['numa_default_taciturn', 'numa_default_c2'],"","",""],
["numa_default_c2","","","_pass","","numa_snooped and not numa_followed_up",['numa_follow_up', 'numa_default_main'],"","",""],
["numa_default_taciturn","","","","","","",['true', 'true', 'not numa_asked_about_eyes', 'not numa_asked_about_others'],['what\'s up?', 'how are the flowers?', 'do you technically have four eyes?', 'have you met the others?'],['numa_dot', 'numa_dot', 'numa_dot', 'numa_dot']],
["numa_default_main","","","","","","",['true', 'true', 'not numa_asked_about_eyes', 'not numa_asked_about_others and not numa_snooped', 'numa_snooped'],['what\'s up?', 'how are the flowers?', 'do you technically have four eyes?', 'have you met the others?', '(about kyungsoon)'],['numa_wasup', 'numa_how', 'numa_eyes', 'numa_others', 'numa_ks']],
["numa_others","you","","have you met oliver and kyungsoon?","numa_asked_about_others","","","","",""],
["","_none","","numa nods","","","","","",""],
["","you","","you must get to know each other pretty well when you're stuck in purrgatory together.","","","","","",""],
["","numa","","yeah, sort of.","","","","","",""],
["","","","except, um...","","","","","",""],
["","","","…","","","","","",""],
["","you","","yes?","","","","","",""],
["","numa","","well, kyungsoon, i haven't...","","","","","",""],
["","","","...","","","","","",""],
["","you","","what about kyungsoon?","","","","","",""],
["","numa","","•••","","","","","",""],
["","you","","did she... do something bad?","","","","","",""],
["","numa","","no no no no","","","","","",""],
["","","","uh, never mind. forget i said anything ;;","","","","","",""],
["","you","","uh, alright","","","null","","",""],
["numa_wasup","you","","what's up?","","","","","",""],
["","numa","","not much","","","","","",""],
["","you","","cool","","","null","","",""],
["numa_how","you","","how are the flowers?","","","","","",""],
["","numa","","oh, they're good.","","","","","",""],
["","","","i mean, they smell like crap. haha","","","","","",""],
["","","","but, um, otherwise they're doing good.","","","","","",""],
["","you","","good to hear.","","","","","",""],
["","numa","","…","","","","","",""],
["","","","","","","",['true', 'not numa_asked_about_gardener', 'not numa_asked_about_time and not numa_snooped', 'true'],['you seem to care about them a lot', 'were you a gardener in real life?', 'do you spend all your time here?', '(end the conversation)'],['numa_protective', 'numa_gardener', 'numa_time', 'numa_end']],
["numa_time","you","","do you spend all your time gardening?","numa_asked_about_time","","","","",""],
["","numa","","i mean, i guess","","","","","",""],
["","","","usually i'm here or in my room.","","","","","",""],
["","you","","wait, you have a room?","","","","","",""],
["","","","where?","","","","","",""],
["","numa","","um, it's in the vents","","","","","",""],
["","you","","huh.","","","","","",""],
["","numa","","so if you ever hear noises in the wall, you know who it is!","","","","","",""],
["","","","haha","","","","","",""],
["","","","um, just kidding","","","","","",""],
["","you","","okay","","","null","","",""],
["numa_protective","you","","you seem to care about those flowers a lot","","","","","",""],
["","numa","","um, yeah. sorry.","","","","","",""],
["","","","about earlier","","","","","",""],
["","you","","it's okay","","","","","",""],
["","","","","","","","",['do people step on them a lot?', 'you should relax', '(pretend to step on a flower)'],['numa_step', 'numa_loose', 'numa_pretend']],
["numa_step","you","","do people step on them a lot?","","","","","",""],
["","numa","","not really","","","","","",""],
["","you","","oh","","","","","",""],
["","","","well, i guess you nipped that problem in the [i]bud[/i]","","","","","",""],
["","numa","","…","","","","","",""],
["","","","heh","","","","","",""],
["","you","","hehe","","","null","","",""],
["numa_loose","you","","you seem kind of stressed. maybe you should relax a little.","","","","","",""],
["","numa","","gardening is relaxing.","","","","","",""],
["","you","","ah, i see","","","","","",""],
["","numa","","…","","","null","","",""],
["numa_pretend","you","","what if i did this?","numa_pissed_off","","","","",""],
["","_none","","you lift your foot in preparation to squash a flower","","","","","",""],
["","numa","","…","","","","","",""],
["","you","","i'm gonna step on it","","","","","",""],
["","numa","","•••","","","","","",""],
["","you","","really? nothing?","","","","","",""],
["","_none","","numa starts shaking.","","","","","",""],
["","you","","uh... never mind.","","","null","","",""],
["numa_dot","numa","","…","","","","","",""],
["","_none","","it looks like she doesn't want to talk to you anymore.","","","null","","",""],
["numa_eyes","you","","those are your eyestalks, right?","numa_asked_about_eyes","","","","",""],
["","numa","","mhm","","","","","",""],
["","you","","does that mean you technically have four eyes?","","","","","",""],
["","numa","","i mean, yeah.","","","","","",""],
["","you","","dope","","","null","","",""],
["numa_gardener","you","","were you a gardener in real life, too?","numa_asked_about_gardener","","","","",""],
["","numa","","no, i was an intern at an accounting firm","","","","","",""],
["","you","","oh, i see","","","","","",""],
["","","","did you like it?","","","","","",""],
["","numa","","mhm","","","","","",""],
["","","","i mean, aren't all the cool kids into accounting? haha","","","","","",""],
["","","","","","","","",['sounds kinda boring', 'sounds like my kind of job', 'cool'],['numa_boring', 'numa_job', 'numa_cool']],
["numa_cool","you","","that's pretty cool","","","","","",""],
["","numa","","yep","","","null","","",""],
["numa_boring","you","","isn't accounting boring? what kind of stuff did you do, anyway?","","","","","",""],
["","numa","","uh","","","","","",""],
["","","","financial statements and stuff","","","","","",""],
["","","","you know","","","","","",""],
["","you","","does that mean you could do my taxes?","","","","","",""],
["","numa","","uh, no, sorry.","","","","","",""],
["","","","that's the wrong type of accountant","","","","","",""],
["","you","","oh, my bad","","","null","","",""],
["numa_job","you","","i think i would have liked being an accountant. ","","","","","",""],
["","","","i always liked numbers","","","","","",""],
["","numa","","oh, yeah, me too!","","","","","",""],
["","","","i know it's kinda dumb but, i liked, um ","","","","","",""],
["","","","making spreadsheets and stuff, hah","","","","","",""],
["","you","","yo i love spreadsheets!","","","","","",""],
["","numa","","oh really?","","","","","",""],
["","","","cool (:","","","","","",""],
["","you","","what kind of accounting did you do?","","","","","",""],
["","numa","","i did financial accounting, mostly","","","","","",""],
["","","","cash flow and balance sheets and, you know, stuff like that.","","","","","",""],
["","","","i wanted to be a CPA later in life","","","","","",""],
["","you","","ah, i see","","","","","",""],
["","numa","","i know, it's kind of boring","","","","","",""],
["","you","","no, no, not at all.","","","","","",""],
["","_none","","numa shrugs","","","null","","",""],
["numa_end","you","","well, seeya later","","","","","",""],
["","numa","","seeya","","","null","","",""],
["snoop","numa","numa_neutral","{player}?",[['met_numa', true], ['surprise_audio', true]],"","","","",""],
["","_none","","you stop short as you run into numa in the vents.","","","","","",""],
["","you","","oh, numa","","","","","",""],
["","numa","","what are you doing in here?!","","","","","",""],
["","you","","um, is this where you live?","","","","","",""],
["","numa","","...yes?","","","","","",""],
["","","","","","","","",['i\'m sorry', '…'],['snoop_sorry', 'snoop_dots']],
["snoop_sorry","you","","i'm sorry, i was just exploring and i didn't know","","","","","",""],
["","numa","","just [i]exploring[/i]? in someone else's room??","","","","","",""],
["","you","","sorry...","","","snoop_1","","",""],
["snoop_dots","you","","...","","","","","",""],
["","numa","","were you snooping around in my room??","","","","","",""],
["snoop_1","numa","","i can't believe this!","","","","","",""],
["","","","you'd think screwing shut the door would be enough to keep people out...","","","","","",""],
["","","","wait","","","","","",""],
["","","","did...","","","","","",""],
["","","","did you read my notebook too??","","","","","",""],
["","","","","","","","",['yes', 'no'],['snoop_yes', 'snoop_no']],
["snoop_yes","you","","yes, i'm sorry","","","","","",""],
["","","","i was just curious","","","","","",""],
["","numa","","you WHAT?!","","","","","",""],
["","you","","it's okay! it wasn't embarrassing or anything!","","","","","",""],
["","numa","","THAT JOURNAL IS PRIVATE!","","","","","",""],
["","","","ASSHOLE!","numa_asshole","","","","",""],
["","you","","i'm sorry, i just took a peek, i promise!","","","","","",""],
["","numa","","i can't believe you--","","","","","",""],
["","","","why would--","","","","","",""],
["","","","...","","","","","",""],
["","","","does that mean you saw--","","","","","",""],
["","","","...","","","","","",""],
["","","","never mind.","","","","","",""],
["","_none","","numa closes her eyes, clearly taking deep breaths.","","","","","",""],
["","","","enough time passes that it's awkward.","","","snoop_2a","","",""],
["snoop_no","you","","no, of course not","","","","","",""],
["","numa","","oh. okay.","","","","","",""],
["","","","good, because you shouldn't have!","","","","","",""],
["snoop_2a","you","","sorry for asking, but...","","","","","",""],
["snoop_2","","","","","","",['not snoop_keeping_track', 'true', 'true'],['are you counting the days you\'ve been here?', 'is that a drawing of you and kyungsoon?', 'could you back up please'],['snoop_track', 'snoop_pic', 'snoop_back']],
["snoop_track","you","","are you keeping track of how long you've been here?","snoop_keeping_track","","","","",""],
["","numa","","yeah. i guess.","","","","","",""],
["","you","","how come?","","","","","",""],
["","numa","","i don't know, i just have to keep track.","","","","","",""],
["","","","otherwise time just blends together","","","","","",""],
["","you","","i see","","","snoop_2","","",""],
["snoop_pic","you","","is that a drawing of you and kyungsoon?","","","","","",""],
["","numa","","um, no. i mean, uh, maybe.","","","","","",""],
["","","","...","","","","","",""],
["snoop_friends","you","","you two must be friends, then?","","","","","",""],
["","numa","","well, not really…","","","","","",""],
["","you","","um… girlfriends?","","","","","",""],
["","_none","","numa mutters something that you can't hear","","","","","",""],
["snoop_pre_crush","","","","","","",['true', 'not snoop_tried_to_leave'],['you have a crush on her?', 'could you back up please'],['snoop_crush', 'snoop_back2']],
["snoop_crush","you","","do you… have a crush on her?","","","","","",""],
["","numa","","YES!","","","","","",""],
["","","","I HAVE A CRUSH ON KYUNGSOON!!","","","","","",""],
["","you","","oh","","","","","",""],
["","numa","","it's just that i can never work up the courage to talk to her, i've been stuck here for YEARS","","","","","",""],
["","","","and i've never told anyone about it either, in case they leaked the secret","","","","","",""],
["","","","and, i mean, i can't even give her flowers because they all smell horrible,","","","","","",""],
["","","","and,","","","","","",""],
["","_none","","numa puts her head in her hands.","","","","","",""],
["","numa","","why am i telling you this ;;","","","","","",""],
["","you","","no, it's ok","","","","","",""],
["","numa","","i'm sorry, i should go","","","","","",""],
["","you","","it's ok, it's ok! it's just…","","","","","",""],
["snoop_c","","","","","","",['not snoop_fluffy', 'not snoop_offered_to_talk', 'true'],['what\'s so attractive about her?', 'would you like me to talk to her for you?', 'could you pleeease back up'],['snoop_attractive', 'snoop_talk', 'snoop_back3']],
["snoop_back","you","","could you, uh, back up please? there's not enough space to crawl past you","","","","","",""],
["","numa","","um, yeah. sure.","","","","","",""],
["","","","i was just wondering if you… saw the picture","","","","","",""],
["","you","","uh, the one of you and kyungsoon?","","","","","",""],
["","numa","","uh, yeah. well, i mean, it's not...","","","","","",""],
["","","","yeah, that one.","","","snoop_friends","","",""],
["snoop_back2","you","","if you wouldn't mind backing up so i can get out of the vent…","snoop_tried_to_leave","","","","",""],
["","numa","","oh, yeah, of course, it's just…","","","","","",""],
["","","","about kyungsoon…","","","","","",""],
["","you","","mhm?","","","","","",""],
["","numa","","…","","","snoop_pre_crush","","",""],
["snoop_attractive","you","","i don't see what's so attractive about kyungsoon…?","snoop_fluffy","","","","",""],
["","numa","","really??","","","","","",""],
["","","","i mean, she's so tall and mysterious...","","","","","",""],
["","","","and smart","","","","","",""],
["","","","and pretty","","","","","",""],
["","","","and... fluffy","","","","","",""],
["","you","","huh","","","snoop_c","","",""],
["snoop_talk","you","","i could talk to her, if you want","snoop_offered_to_talk","","","","",""],
["","numa","","NO!","","","","","",""],
["","","","i mean","","","","","",""],
["","_none","","numa takes another deep breath.","","","","","",""],
["","numa","","i mean, please don't do that.","","","","","",""],
["","you","","jeez, okay","","","","","",""],
["","numa","","sorry, it's just","","","","","",""],
["","","","if i'm going to tell her, i want it to be perfect.","","","","","",""],
["","","","i want to give her gifts, maybe some food…","","","","","",""],
["","you","","food?","","","","","",""],
["","numa","","i mean, she really likes food, right?","","","","","",""],
["","you","","that's true","","","snoop_c","","",""],
["snoop_back3","you","","could you pleeease back up so we can get out of this vent","","","","","",""],
["","numa","","oh, sorry","","","","","",""],
["","","","sorry, sorry, sorry…","","","","","",""],
["","_none","","numa backs up and you finally leave the vent","snoop_leave_vent","","","","",""],
["","numa","","…","","","","","",""],
["","you","","…","","","","","",""],
["","numa","","um, please don't tell anyone about this","","","","","",""],
["","you","","my lips are sealed.","","","","","",""],
["","numa","","can i have the screwdriver please","","","","","",""],
["","you","","here",[['_inv_screwdriver', false]],"","","","",""],
["","_none","","numa takes the screwdriver and hurries down the stairs.","","","null","","",""],
["numa_follow_up","you","","um","numa_followed_up","","","","",""],
["","","","hey","","","","","",""],
["","numa","","hey","","","","","",""],
["","you","","sorry about snooping around earlier","","","","","",""],
["","numa","","it's... fine.","","numa_asshole",['numa_follow_up1', 'numa_follow_up2'],"","",""],
["numa_follow_up1","","","sorry for calling you an asshole.","","","numa_follow_up3","","",""],
["numa_follow_up2","","","sorry for blowing up at you.","","","","","",""],
["numa_follow_up3","you","","it's okay","","","","","",""],
["","","","i probably deserved it","","","","","",""],
["","_none","","numa shrugs.","","","","","",""],
["","numa","","let's... call it even?","","","","","",""],
["","","","i guess?","","","","","",""],
["","you","","sounds good to me.","","","","","",""],
["","numa","","great","","","null","","",""],
["numa_ks","you","numa_neutral","so, about kyungsoon…","","numa_helping",['numa_gift_options', 'numa_plan'],"","",""],
["","numa","","oh, yeah","","","","","",""],
["","","","um, sorry about venting to you about that","","","","","",""],
["","you","","heh, no pun intended?","","","","","",""],
["","numa","","pun?","","","","","",""],
["","","","...oh. haha.","","","","","",""],
["","you","","so uh","","","","","",""],
["numa_plan","you","","you still want to talk to her, right? what's the plan?","","","","","",""],
["","numa","","i mean... i guess... i wanted to make everything perfect","","","","","",""],
["","","","this is going to sound so stupid","","","","","",""],
["","","","i want to arrange a boquet of flowers","","","","","",""],
["","","","and write her a poem","","","","","",""],
["","","","and get some food as a gift, i guess","","","","","",""],
["","","","","","","","",['i could help you with that', 'you should really just talk to her'],['numa_help', 'numa_talk']],
["numa_help","you","","i could try to help you with that","numa_helping","","","","",""],
["","numa","","really?","","","","","",""],
["","you","","yeah, really!","","","","","",""],
["","","","consider it as making up for snooping around in your room","","","","","",""],
["","numa","","well...","","","","","",""],
["","","","i guess i could use some help.","_quest_numa_kyungsoon","","","","",""],
["","","","i mean, it's pretty obvious that i'm not getting anywhere alone, am i right?","","","","","",""],
["","","","haha","","","numa_gift_options","","",""],
["numa_talk","you","","it would be a lot easier if you just talked to her.","","","","","",""],
["","numa","","oh, no no no, i can't do that","","","","","",""],
["","","","that's way too scary","","","","","",""],
["","you","","we're already dead, what is there to be afraid of?","","","","","",""],
["","numa","","i don't know","","","","","",""],
["","","","an eternity of self-hatred,","","","","","",""],
["","","","fueled by inescapable rejection and humiliation?","","","","","",""],
["","you","","oh","","","","","",""],
["","","","hm","","","","","",""],
["","numa","","just normal feelings that everyone has, right?","","","","","",""],
["","","","hahaha","","","","","",""],
["","","","um. just kidding.","","","null","","",""],
["numa_gift_options","","","","","","","",['ready to talk to her?', 'flowers', 'poem', 'food'],['numa_ready?', 'numa_flowers_c', 'numa_poem_c', 'numa_food_c']],
["numa_flowers_c","","","_pass","","not numa_started_flowers",['numa_flowers1', 'numa_flowers_c2'],"","",""],
["numa_flowers_c2","","","_pass","","not numa_finished_flowers",['numa_flowers2', 'numa_flowers3'],"","",""],
["numa_flowers1","you","","do you need any help picking out flowers?","numa_started_flowers","","","","",""],
["","numa","","oh, yes, please",[['flower_fails', 0]],"","","","",""],
["","","","my eyesight is bad, so i have a hard time finding the ones i want ;;","","","","","",""],
["","you","","well, how about this one--","","","","","",""],
["","numa","","DON'T TOUCH THAT!","","","","","",""],
["","","","i mean","","","","","",""],
["","_none","","numa breathes deeply.","","","","","",""],
["","numa","","please don't touch them, they're fragile","","","","","",""],
["","","","just point at them","","","","","",""],
["","you","","you're going to give me a heart attack one of these days, numa","","","","","",""],
["","numa","","sorry ;;","","","flowers_init","","",""],
["numa_flowers2","you","","let's give flower-picking another shot…","","flower_fails >= 2",['numa_flowers_skip', 'flowers_init'],"","",""],
["numa_flowers_skip","numa","","ummmmmmmm","","","","","",""],
["","","","you know, i could always just... find the flowers myself...","","","","","",""],
["","","","if you'd rather, i mean","","","","","",""],
["","","","","","","","",['let me try one more time', 'yeah, you should probably do it yourself'],['numa_flowers_skip1', 'numa_flowers_skip2']],
["numa_flowers_skip1","you","","let me try one more time!","","","","","",""],
["","numa","","okay!!","","","flowers_init","","",""],
["numa_flowers_skip2","you","","yeah, i guess you should probably just do it yourself","","","","","",""],
["","","","i don't think i'm very good at this lol","","","","","",""],
["","","","sorry i couldn't be more of a help","","","","","",""],
["","numa","","no no it's okay!","","","","","",""],
["","","","umm i appreciate you trying","","","","","",""],
["","","","it'll just... probably... be faster by myself...","","","","","",""],
["","","","i mean i'm not saying you're bad at finding flowers or anything!!","","","","","",""],
["","","","it's just you know, i'm more familiar with the garden, and","","","","","",""],
["","","","you already tried a couple of times, and...","","","","","",""],
["","you","","no no i totally get it!","","","","","",""],
["","numa","","okay, cool","","","","","",""],
["","","","sorry ;;","numa_finished_flowers","","null","","",""],
["numa_flowers3","numa","","the flowers for kyungsoon are looking great!!","","","","","",""],
["","you","","great!","","","","","",""],
["","numa","","i just hope she'll like them...","","","","","",""],
["","","","want to help me find some more, just in case?","","","","","",""],
["","","","","","","","",['sure', 'not right now'],['flowers_init', 'numa_flowers_not']],
["numa_flowers_not","you","","not right now, sorry","","","","","",""],
["","numa","","oh, okay","","","null","","",""],
["numa_poem_c","","","_pass","","not numa_started_poem",['numa_poem1', 'numa_poem_c2'],"","",""],
["numa_poem_c2","","","_pass","","not numa_finished_poem",['numa_poem2', 'numa_poem3'],"","",""],
["numa_poem1","you","","how's that poem going?","numa_started_poem","","","","",""],
["","numa","","um, i think i could use some help, maybe","","","","","",""],
["","","","english was always one of my worst subjects","","","","","",""],
["","","","only b i've ever gotten...","","","","","",""],
["","you","","well, let's hear what you have so far.","","","","","",""],
["","numa","","are you sure?","","","","","",""],
["","","","it's not very good","","","","","",""],
["","","","actually, it's awful","","","","","",""],
["","","","actually it's pretty much the worst poem in the world","","","","","",""],
["","you","","damn","","","","","",""],
["","numa","","just, like, letting you know what you're getting into","","","","","",""],
["","you","","just give it a chance","","","","","",""],
["","","","promise i won't judge!","","","","","",""],
["","numa","","well...","","","","","",""],
["","","","it goes like this:","","","","","",""],
["","","","roses are white","","","","","",""],
["","","","violets are white","","","","","",""],
["","","","to me, you are","","","","","",""],
["","","","a shining light","","","","","",""],
["","you","","sounds good so far!","","","","","",""],
["","numa","","you are purple","","","","","",""],
["","","","i am orange","","","","","",""],
["","","","…","","","","","",""],
["","","","that's all i have","","","","","",""],
["","","","nothing rhymes with orange ;;","","","","","",""],
["","","","","","","","",['and your face / i adore-enge', 'you pierce my heart / like a syringe', 'just switch the last two lines'],['numa_adore-enge', 'numa_syringe', 'numa_switch']],
["numa_adore-enge","you","","how about this","","","","","",""],
["","","","\"and your face, i adore-enge\"","","","numa_orange_after","","",""],
["numa_syringe","you","","how about this","","","","","",""],
["","","","\"you pierce my heart, like a syringe\"","","","numa_orange_after","","",""],
["numa_switch","you","","just switch the last two lines so that you don't have to rhyme with orange.","","","","","",""],
["","","","\"i am orange, you are purple\"","","","","","",""],
["","numa","","i mean, but what rhymes with purple?","","","","","",""],
["","you","","uh","","","","","",""],
["","","","","","","","",['orange soda / i like to slurp-le', 'i got nothing'],['numa_slurp-le', 'numa_nothing']],
["numa_slurp-le","you","","\"orange soda, i like to slurp-le\"","","","numa_orange_after","","",""],
["numa_nothing","you","","i got nothing","","","numa_suit","","",""],
["numa_orange_after","numa","","…","","","","","",""],
["","you","","…","","","","","",""],
["","","","yeah, that sucks","","","","","",""],
["","numa","","sort of, yeah","","","","","",""],
["","","","sorry","","","","","",""],
["numa_suit","you","","i don't think poetry is my strong suit.","","","","","",""],
["","numa","","*sigh*","","","","","",""],
["","","","i'm never going to finish this poem.","","","","","",""],
["","","","maybe i should just stick to spreadsheets...","","","","","",""],
["","you","","don't give up yet, maybe you'll think of something.","","","","","",""],
["","","","or maybe someone else can help!","","","","","",""],
["","numa","","who else would be willing to help with something like this?","","","","","",""],
["","you","","hmm...","","","","","",""],
["","","","i don't know, i'll think about it","","","null","","",""],
["numa_poem2","you","","any progress on the poem?","","","","","",""],
["","numa","","not yet, sorry","","","","","",""],
["","","","i still can't think of the next line","","","","","",""],
["","","","i know, it's stupid ;;","","","","","",""],
["","you","","take your time","","","","","",""],
["","","","we have an eternity, after all.","","","null","","",""],
["numa_poem3","you","","was talking to elijah helpful?","","","","","",""],
["","numa","","yep!","","","","","",""],
["","","","i'm just putting some final touches on it now.","","","","","",""],
["","you","","can i hear it?","","","","","",""],
["","numa","","sure, here's a little excerpt:","","","","","",""],
["","","","you are purple","","","","","",""],
["","","","i am smitten","","","","","",""],
["","","","you're as cute","","","","","",""],
["","","","as a kitten!","ks_heard_cute_as_kitten","","","","",""],
["","you","","nice!","","","","","",""],
["","numa","","i know, it's so cute!!","","","","","",""],
["","","","thanks again for your help :)","","","","","",""],
["","you","","it's nothing, really.","","","null","","",""],
["numa_food_c","","","_pass","","not numa_started_food",['numa_food1', 'numa_food_c2'],"","",""],
["numa_food_c2","","","_pass","","not numa_progressed_food",['numa_food2', 'numa_food_c3'],"","",""],
["numa_food_c3","","","_pass","","not numa_finished_food",['numa_food3', 'numa_food4'],"","",""],
["numa_food1","you","","what are you doing about food?","numa_started_food","","","","",""],
["","numa","","um, i guess i haven't really thought about it","","","","","",""],
["","","","i don't even know what kind of food she likes…","","","","","",""],
["","","","","","","","",['books', 'keys', 'signs'],['numa_books', 'numa_keys', 'numa_signs']],
["numa_books","you","","i heard she likes to eat books.","","","","","",""],
["","numa","","books? really?","","","","","",""],
["","","","i guess i could give her my notebook…","","","","","",""],
["","you","","uh, are you sure you want her reading all of your personal writing?","","","numa_bad","","",""],
["numa_keys","you","","i heard she likes to eat keys.","","","","","",""],
["","numa","","keys? really?","","","","","",""],
["","","","well, i guess i could give her my screwdriver, which is kind of like a key…","","","","","",""],
["","you","","the one you need to get into your room?","","","numa_bad","","",""],
["numa_signs","you","","i heard she likes to eat signs.","","","","","",""],
["","numa","","signs? really?","","","","","",""],
["","","","i guess i could get that meowseum sign for her...","","","","","",""],
["","you","","the one that's made of glass?","","","numa_bad","","",""],
["numa_bad","numa","","oh","","","","","",""],
["","","","you're right, that was stupid","","","","","",""],
["","","","sorry","","","","","",""],
["","you","","it's okay!","","","","","",""],
["","numa","",";;","","","","","",""],
["","you","","maybe i could talk to kyungsoon and find out what she likes.","","","","","",""],
["","numa","","well, i mean, that would be helpful!","","","","","",""],
["","","","just remember to, you know, be discreet about it","","","","","",""],
["","you","","i'll see what i can do!","","","null","","",""],
["numa_food2","you","","why don't you just give her some of that fruit in the other room?","","","","","",""],
["","","","it looks pretty tasty","","","","","",""],
["","numa","","oh, those are deathberries.","","","","","",""],
["","","","don't eat that","","","","","",""],
["","","","you'll be sick for weeks","","","","","",""],
["","you","","oh","","","","","",""],
["","numa","","yep","","","null","","",""],
["numa_food3","you","","i asked kyungsoon about her favorite food!","","","","","",""],
["","numa","","oh, really?? what did she say?","","","","","",""],
["","you","","it's leaves.","","","","","",""],
["","numa","","no way, i love leaves!","","","","","",""],
["","you","","great!","","","","","",""],
["","numa","","oh, they're all going to be dead and shriveled though","","","","","",""],
["","","","they probably won't taste very  good","","","","","",""],
["","","","actually, never mind","","","","","",""],
["","","","this is a terrible idea","","","","","",""],
["","you","","hey, it's the thought that counts!","","","","","",""],
["","numa","","do you think?","","","","","",""],
["","you","","yeah!","","","","","",""],
["","","","probably","","","","","",""],
["","numa","","that's not very reassuring ;;","numa_finished_food","","null","","",""],
["numa_food4","you","","is the food all ready?","","","","","",""],
["","numa","","yep, i'm almost done gathering the tastiest looking leaves for her...","","","","","",""],
["","you","","well, i guess i'll just [i]leaf[/i] you to it, then","","","","","",""],
["","numa","","i mean, you can stay if you want","","","","","",""],
["","","","it's no problem","","","","","",""],
["","","","...oh, that was a pun, wasn't it?","","","","","",""],
["","you","","it was a pun, yeah","","","","","",""],
["","numa","","haha","","","null","","",""],
["numa_ready?","you","","so, are you going to talk to her?","","numa_finished_flowers and numa_finished_poem and numa_finished_food",['numa_ready', 'numa_not_ready'],"","",""],
["numa_not_ready","","","not yet.","","not numa_finished_flowers",['numa_r_flowers', 'numa_r_c1'],"","",""],
["numa_r_flowers","","","i still haven't picked out the right flowers for her…","","","","","",""],
["numa_r_c1","","","_pass","","not numa_finished_poem",['numa_r_poem', 'numa_r_c2'],"","",""],
["numa_r_poem","","","i haven't finished the poem yet…","","","","","",""],
["numa_r_c2","","","_pass","","not numa_finished_food",['numa_r_food', 'numa_r_end'],"","",""],
["numa_r_food","","","i don't even know what food to get her!","","","","","",""],
["numa_r_end","numa","","everything needs to be perfect.","","","","","",""],
["","you","","hm, okay","","","null","","",""],
["numa_ready","numa","","well… i guess…","","","","","",""],
["","","","i have everything ready…","","","","","",""],
["","_none","","numa looks over at a boquet of flowers, a handwritten card, and a basket of leaves.","","","","","",""],
["","numa","","it's just","","","","","",""],
["","","","she's so pretty and confident and smart and,","","","","","",""],
["","","","she could do so much better than me, you know?","","","","","",""],
["","","","","","","","",['you\'ve got this!', 'maybe you should be more subtle'],['numa_got', 'numa_much']],
["numa_got","you","","you've got this, numa!","","","","","",""],
["","","","she's going to be blown away by all the gifts","","","","","",""],
["","numa","","do you think so?","","","","","",""],
["","you","","absolutely","","","","","",""],
["","numa","","well...","","","","","",""],
["","","","i guess she can't think any less of me than she does now","","","","","",""],
["","","","am i right? haha.","","","","","",""],
["","","","um.","","","","","",""],
["","","","sorry for being such a worry worm","","","","","",""],
["","you","","it's ok","","","","","",""],
["","_none","","numa takes a deep breath and gathers up the gifts in her arms.","","","","","",""],
["","numa","","ok!! let's do this!!!!","","","numa_meeting","","",""],
["numa_much","you","","well, if you're worried, then…","","","","","",""],
["","","","maybe it would be better to be more subtle?","","","","","",""],
["","numa","","what do you mean?","","","","","",""],
["","","","do you think i'm coming off too strong?","","","","","",""],
["","","","oh no, what if she thinks i'm weird??","","","","","",""],
["","","","what if she never wants to talk to me again?","","","","","",""],
["","","","oh god","","","","","",""],
["","","","okay never mind","","","","","",""],
["","","","i don't think i can do this","","","","","",""],
["","you","","there's… no way that you're weirder than kyungsoon","","","","","",""],
["","numa","","huh?","","","","","",""],
["","you","","you can be weird together!","","","","","",""],
["","","","like two peas in a weird pod","","","","","",""],
["","numa","","…","","","","","",""],
["","","","was that encouraging?","","","","","",""],
["","numa","","not really","","","","","",""],
["","you","","okay, never mind subtlety.","","","","","",""],
["","","","you can't back out now!","","","","","",""],
["","","","come on, let's head to the commons","","","","","",""],
["","_none","","numa gulps.","","","","","",""],
["","numa","","ok…","","","","","",""],
["numa_meeting","_none","numa_neutral","the two of you make your way to the commons.","numa_goto_commons","","","","",""],
["","you","","are you ready?","","","","","",""],
["","_none","","numa shakes her head.","","","","","",""],
["","you","","go on, it'll be over soon","","","","","",""],
["","","","just go in and tell her you like her.","","","","","",""],
["","numa","","that's easy to say!","","","","","",""],
["","you","","just don't think about it! go in!!","","","","","",""],
["","numa","","you're right, you're right.","","","","","",""],
["","","","i can do this.","","","","","",""],
["","_none","","numa takes a deep breath, then bursts through the door.",[['_quest_numa_kyungsoon', false]],"","","","",""],
["","numa","_none","KYUNGSOON!","","","","","",""],
["","_none","","you listen through the door.","","","","","",""],
["","kyungsoon","","hm?","","","","","",""],
["","numa","","i, um, i just wanted to, uh","","","","","",""],
["","kyungsoon","","…","","","","","",""],
["","numa","","i mean","","","","","",""],
["","","","kyungsoon i, i, i have something to tell you!!","","","","","",""],
["","kyungsoon","","yeah?","","","","","",""],
["","_none","","you hear the library doors open.","oliver_hears_numa","","","","",""],
["","oliver","","i heard yelling, is everything okay out here?","","","","","",""],
["","","","oh, hi numa!","","","","","",""],
["","","","what's all that stuff for?","","","","","",""],
["","numa","","oh, haha, it's, um","","","","","",""],
["","oliver","","oh lord, what's that smell? is it the flowers?","","","","","",""],
["","numa","","ummmm","","","","","",""],
["","kyungsoon","","gross","","","","","",""],
["","oliver","","numa, are you… okay?","","","","","",""],
["","kyungsoon","","she was going to tell me something","","","","","",""],
["","oliver","","oh, well go ahead.","","","","","",""],
["","","","don't let me get in the way!","","","","","",""],
["","numa","","uhhhhhhhhhhh iii don't think i...","","","","","",""],
["","oliver","","go on!","","","","","",""],
["","numa","","kyungsoon…","","","","","",""],
["","","","i…","","","","","",""],
["","","","…","commons_flowers","","","","",""],
["","_none","","you hear the sound of flowers hitting the floor, then numa bursts through the door and runs down the hallway.","_quest_numa_friendship","","","","",""],
["","numa","numa_neutral","AAAAAAAAAAAAAAAA","_anim_right_to_left_run","","","","",""],
["","you","_none","numa?","","","","","",""],
["","oliver","","…","","","","","",""],
["","kyungsoon","","…","","","","","",""],
["","oliver","","what was all that about?","","","","","",""],
["","kyungsoon","","iuno","numa_crying","","null","","",""],
["numa_cry","_none","","you can hear the faint sound of crying through the vent.","","","","","",""],
["","you","","numa?","","not numa_consoled",['numa_cry_console', 'numa_cry_silent'],"","",""],
["numa_cry_console","numa","","go away!","numa_consoled","","","","",""],
["","","","","","","","",['don\'t feel bad', 'do you want to talk about it', 'you really messed that up'],['numa_cry_feel', 'numa_cry_talk', 'numa_cry_mess']],
["numa_cry_silent","numa","","…","","","","","",""],
["","_none","","seems like she doesn't want to talk.","","","null","","",""],
["numa_cry_feel","you","","don't feel bad","","","","","",""],
["","","","you tried your best, but oliver got in the way.","","","","","",""],
["","numa","","…","","","","","",""],
["","you","","i bet kyungsoon is really enjoying those leaves!","","","","","",""],
["","numa","","…","","","","","",""],
["","you","","i think she liked the flowers?","","","","","",""],
["","numa","","she called them gross!","","","","","",""],
["","you","","gross in… a good way?","","","","","",""],
["","","","like how \"bad\" used to mean good","","","","","",""],
["","","","in the 80s","","","","","",""],
["","","","","","","","",['totally gross, duude', '(just cut your losses)'],['numa_cry_gross', 'numa_cry_end']],
["numa_cry_gross","you","","like, that's totally gross, duuude","","","","","",""],
["","_none","","you hear a strangled sound that might have been laughter.","","","","","",""],
["numa_cry_end","_none","","it doesn't look like she's coming out any time soon.","","","null","","",""],
["numa_cry_talk","you","","do you want to talk about it?","","","","","",""],
["","numa","","no.","","","","","",""],
["","you","","maybe later?","","","","","",""],
["","numa","","i'm going to stay in here","","","","","",""],
["","","","for eternity","","","","","",""],
["","you","","don't do that!!","","","","","",""],
["","numa","","…","","","numa_cry_end","","",""],
["numa_cry_mess","you","","you really messed that up","","","","","",""],
["","numa","","i know that already!","","","","","",""],
["","","","i mess up everything!!","","","","","",""],
["","you","","that's a mood","","","","","",""],
["","_none","","you hear numa start crying harder.","","","","","",""],
["","","","she's definitely not coming out now.","","","null","","",""]
]