extends Node

var raw_blocks = [
["talk_to_oliver_about_numa","oliver","oliver_neutral","what was that all about?","","","","","",""],
["","","","","","","","",['you scared her off', 'who knows'],['oliver_scared', 'oliver_who_knows']],
["oliver_scared","you","","i think you scared her off","","","","","",""],
["","oliver","","really?","","","","","",""],
["","","","what did i say??","","","","","",""],
["","you","","i dunno man","","","null","","",""],
["oliver_who_knows","you","","uh... who knows?","","","","","",""],
["","oliver","","hm... mysterious...","","","null","","",""],
["oliver_default","_none","_none","_pass","","oliver_quest_complete",['oliver_default_f', 'oliver_default1'],"","",""],
["oliver_default1","_none","_none","_pass","","comforted_oliver",['oliver_default_e', 'oliver_default2'],"","",""],
["oliver_default2","_none","_none","_pass","","house_cat_pushed_glass",['oliver_default_d', 'oliver_default3'],"","",""],
["oliver_default3","_none","_none","_pass","","tori_visited_oliver",['oliver_default_c', 'oliver_default4'],"","",""],
["oliver_default4","_none","_none","_pass","","oliver_in_study",['oliver_default_b', 'oliver_default5'],"","",""],
["oliver_default5","_none","_none","_pass","","oliver_followed_up",['oliver_default_a', 'oliver_follow_up'],"","",""],
["oliver_follow_up","oliver","oliver_neutral","oh, hi, {player}.","oliver_followed_up","","","","",""],
["","you","","oliver, i'm really sorry about earlier","","","","","",""],
["","","","i should have realized that--","","","","","",""],
["","oliver","","no no, it's alright.","","","","","",""],
["","","","i overreacted. it's just one book, after all.","","","","","",""],
["","","","as much as it rubs me the wrong way to see a book treated like that, i... can't fault you for what you did.","","","","","",""],
["","you","","still, i'm sorry","","","","","",""],
["","","","i didn't mean to upset you.","","","","","",""],
["","oliver","","it's alright. if anything, kyungsoon's the one at fault here!","","","","","",""],
["","you","","heh, maybe","","","","","",""],
["","","","she seemed to touch on some... uh... touchy subjects during that argument?","","","","","",""],
["","oliver","","oh, you mean the bit about \"low blows\" and all that?","","","","","",""],
["","","","it's nothing serious.","","","","","",""],
["","","","kyungsoon just knows it's an easy way to push my buttons.","","","","","",""],
["","","","it's not like she knows exactly what my earthly regrets are, either. she's convinced that i murdered someone!","","","","","",""],
["","you","","ohhh","","","","","",""],
["","","","did you?","","","","","",""],
["","oliver","","no, of course not!","","","","","",""],
["","","","","","","","",['if you did, i won\'t judge', 'who was it?', 'i can\'t see you doing that'],['oliver_judge', 'oliver_who_was', 'oliver_cant_see']],
["oliver_judge","you","","if you did murder someone, i won't judge","","","","","",""],
["","","","just saying","","","","","",""],
["","oliver","","that's very kind of you, but the point is moot, because i didn't.","","","oliver_murder1","","",""],
["oliver_who_was","you","","who was it?","","","","","",""],
["","","","ooh, was it your wife?","","","","","",""],
["","","","was it your husband??","","","","","",""],
["","oliver","","what? no! i wasn't even married!","","","","","",""],
["","you","","yeah, you wouldn't have been, after you [i]murdered[/i] them.","","","","","",""],
["","oliver","","ugh, you're no better than kyungsoon.","","","","","",""],
["","","","i didn't murder anyone, and that's all I have to say on the matter ):<","","","oliver_murder1","","",""],
["oliver_cant_see","you","","yeah, i can't see you doing that tbh","","","","","",""],
["","oliver","","well [i]thank[/i] you.","","","","","",""],
["","","","at least someone in purrgatory has some sense.","","","oliver_murder1","","",""],
["oliver_murder1","you","","well, if you didn't murder anyone, then what are your \"earthly regrets?\"","","","","","",""],
["","oliver","","ah, well...","","","","","",""],
["","","","maybe we can discuss it some other time.","","","","","",""],
["","you","","ah, okay","","","","","",""],
["","","","sorry, i didn't mean to pry.","","","","","",""],
["","oliver","","it's fine. ","","","null","","",""],
["oliver_default_a","oliver","oliver_neutral","hi again, {player}!","","","","","",""],
["","","","","","","",['true', '_inv_natalies_books', 'true', 'true'],['what\'s up?', "(return natalie's books)", 'what do you think of the others?', 'how\'s your work going?'],['oliver_wasup', 'oliver_natalies_books', 'oliver_others', 'oliver_research']],
["oliver_wasup","you","","what's up?","","",['_rand', 'oliver_wasup1', 'oliver_wasup2', 'oliver_wasup3', 'oliver_wasup4', 'oliver_wasup5', 'oliver_wasup6', 'oliver_wasup7', 'oliver_wasup8', 'oliver_wasup10', 'oliver_wasup11', 'oliver_wasup12',  'oliver_wasup14', 'oliver_wasup15', 'oliver_wasup16', 'oliver_wasup17', 'oliver_wasup18', 'oliver_wasup19', 'oliver_wasup20', 'oliver_wasup21', 'oliver_wasup22'],"","",""],
["oliver_wasup1","oliver","","i'm thinking about sorting these alphabetically...","","","null","","",""],
["oliver_wasup2","oliver","","i dusted some books today.","","","","","",""],
["","you","","cool!","","","null","","",""],
["oliver_wasup3","oliver","","i think there's a mouse living in the library...","","","","","",""],
["","you","","you [i]think[/i]?","","","","","",""],
["","oliver","","i mean a little one!","","","","","",""],
["","","","i keep hearing squeaking in the night","","","","","",""],
["","","","ugh. maybe i'm just hearing things.","","","null","","",""],
["oliver_wasup4","oliver","","cataloging.","","","","","",""],
["","you","","so the ushe","","","","","",""],
["","oliver","","hah, yes, the \"ushe.\"","","","null","","",""],
["oliver_wasup5","oliver","","i don't know.","","","","","",""],
["","you","","who does?","","","null","","",""],
["oliver_wasup6","oliver","","thinking about thin mints.","","","","","",""],
["","you","","what about them?","","","","","",""],
["","oliver","","i wish i'd eaten more of them while i had the chance...","","","null","","",""],
["oliver_wasup7","oliver","","books, primarily.","","","","","",""],
["","you","","read anything interesting lately?","","","","","",""],
["","oliver","","uh... not really.","","","","","",""],
["","you","","that's fair","","","null","","",""],
["oliver_wasup8","oliver","","you know those \"animorphs\" books?","","","","","",""],
["","you","","yeah...?","","","","","",""],
["","oliver","","i can't stop thinking about the time they morphed into flies and one of them got swatted","","","","","",""],
["","","","isn't that messed up?","","","null","","",""],
["oliver_wasup10","oliver","","[i]achoo![/i]","","","","","",""],
["","","","dusting.","","","","","",""],
["","you","","you okay?","","","","","",""],
["","oliver","","i'm okay, just -- [i]achoo![/i] -- breathed a lot of dust.","","","","","",""],
["","you","","bless you","","","","","",""],
["","oliver","","thanks","","","null","","",""],
["oliver_wasup11","oliver","","tired.","","","","","",""],
["","you","","me too","","","null","","",""],
["oliver_wasup12","oliver","","did i ever tell you about my dust bunny collection?","","","","","",""],
["","you","","your... dust bunny collection?","","","","","",""],
["","oliver","","every time i find a big dust bunny i put it in a jar.","","","","","",""],
["","","","i just filled my third one!","","","","","",""],
["","","","","","","","",['that\'s pretty cool', 'that\'s the most boring thing you could collect'],['oliver_wasup12a', 'oliver_wasup12b']],
["oliver_wasup12a","you","","that's pretty cool","","","","","",""],
["","oliver","","thanks!","","","null","","",""],
["oliver_wasup12b","you","","no offense, but that's probably the most boring thing you could possibly collect","","","","","",""],
["","oliver","","...","","","","","",""],
["","","","i know ):","","","null","","",""],
["oliver_wasup14","oliver","","...","","","","","",""],
["","you","","oliver?","","","","","",""],
["","oliver","","huh? what?","","","","","",""],
["","you","","i said \"what's up?\"","","","","","",""],
["","oliver","","oh. sorry, haha. kind of tired.","","","","","",""],
["","you","","maybe you should take a break...","","","","","",""],
["","oliver","","maybe. in a bit.","","","null","","",""],
["oliver_wasup15","oliver","","i stubbed my toe earlier ):<","","","","","",""],
["","you","","ouch","","","","","",""],
["","oliver","","i suppose they removed our need for sustenance and sleep but they couldn't remove the pain from stubbed toes.","","","","","",""],
["","you","","lol, figures","","","null","","",""],
["oliver_wasup16","oliver","","thinking about dante's inferno.","","","","","",""],
["","you","","oh yeah?","","","","","",""],
["","oliver","","he got a few things wrong, heh.","","","","","",""],
["","you","","no kidding","","","null","","",""],
["oliver_wasup17","oliver","","thinking about the grapes of wrath.","","","","","",""],
["","you","","why?","","","","","",""],
["","oliver","","i remember i didn't understand why it was called \"the grapes of wrath.\"","","","","","",""],
["","","","never did find out, come to think of it...","","","","","",""],
["","you","","guess reading it was [i]fruit[/i]-less","","","","","",""],
["","oliver","","haha, well said.","","","null","","",""],
["oliver_wasup18","oliver","","thinking about that chess competition i won in 6th grade.","","","","","",""],
["","you","","oh, cool","","","","","",""],
["","oliver","","i was so proud of it at the time, but it seems kind of silly now.","","","","","",""],
["","","","beating 6th graders at chess isn't that much of an accomplishment.","","","","","",""],
["","you","","it's still pretty cool","","","","","",""],
["","oliver","","eh, i guess.","","","null","","",""],
["oliver_wasup19","oliver","","not much.","","","","","",""],
["","you","","cool","","","null","","",""],
["oliver_wasup20","oliver","","i miss my mom","","","","","",""],
["","you","","aw, i'm sorry ):","","","null","","",""],
["oliver_wasup21","oliver","","i wonder if natalie's done with the books i lent her?","","","","","",""],
["","you","","wait","","","","","",""],
["","","","she actually reads these things?","","","","","",""],
["","oliver","","well, i don't know what [i]else[/i] she'd be doing with them.","","","","","",""],
["","","","wait","","","","","",""],
["","","","do you think she eats books too??","","","","","",""],
["","you","","uh, probably not?","","","","","",""],
["","oliver","","i hope you're right...","","","null","","",""],
["oliver_wasup22","oliver","","you know, i suggested starting a book club once","","","","","",""],
["","you","","oh, how did that go down?","","","","","",""],
["","oliver","","not very well.","","","","","",""],
["","","","sean laughed for about ten minutes straight.","","","","","",""],
["","you","","heh","","","","","",""],
["","","","it is kinda funny","","","","","",""],
["","oliver","","well, i didn't think so ):<","","","null","","",""],
["oliver_others","_none_","_none","_pass","","oliver_asked_about_others",['oliver_others1a', 'oliver_others1'],"","",""],
["oliver_others1","you",['oliver_neutral'],"what do you think of the others?","oliver_asked_about_others","","","","",""],
["","","","like, kyungsoon and everyone else who's down here?","","","","","",""],
["","oliver","","well, all things considered, we could have been stuck with much worse company!","","","","","",""],
["","","","is there someone in particular you had in mind?","","","","","",""],
["oliver_others1a","you","","what do you think about...","","","","","",""],
["oliver_others2","","","","","","",['true', 'met_numa', 'met_elijah', 'met_sean or met_tori or met_natalie'],['kyungsoon', 'numa', 'elijah', '(someone else...)'],['oliver_about_ks', 'oliver_about_numa', 'oliver_about_elijah', 'oliver_others3']],
["oliver_others3","","","","","","",['met_sean', 'met_tori', 'met_natalie', 'true'],['sean', 'tori', 'natalie', '(someone else...)'],['oliver_about_sean', 'oliver_about_tori', 'oliver_about_natalie', 'oliver_others2']],
["oliver_about_ks","you","","kyungsoon?","","","","","",""],
["","oliver","","well, kyungsoon is certainly very...","","","","","",""],
["","","","um...","","","","","",""],
["","","","candid","","","","","",""],
["","you","","candid, huh?","","","","","",""],
["","oliver","","yes, and... morose","","","","","",""],
["","you","","is morose a good thing?","","","","","",""],
["","oliver","","well, uh, no, not typically.","","","","","",""],
["","","","i just mean that she's... languorous?","","","","","",""],
["","you","","i don’t know that one either","","","","","",""],
["","oliver","","phlegmatic? enervated.","","","","","",""],
["","you","","okay, you've GOT to be making these up.","","","","","",""],
["","oliver","","oh, never mind, you get what i'm trying to say!","","","","","",""],
["","","","if only i had my thesaurus with me...","","","null","","",""],
["oliver_about_elijah","you","","elijah?","","","","","",""],
["","oliver","","oh, well he's very nice!","","","","","",""],
["","","","and a talented writer, at that","","","","","",""],
["","you","","i see, i see","","","","","",""],
["","","","are you friends?","","","","","",""],
["","oliver","","well, i suppose so.","","","","","",""],
["","","","he tends to stay shut up in his study most of the time.","","","","","",""],
["","","","a habit that we may, uh, have in common.","","","","","",""],
["","you","","lol i see","","","","","",""],
["","oliver","","but yeah, you can see how that is not exactly... conducive to forming friendships.","","","","","",""],
["","you","","makes sense.","","","null","","",""],
["oliver_about_sean","you","","sean?","","","","","",""],
["","oliver","","oh, he's certainly very... audacious.","","","","","",""],
["","","","he has a bit of a rough exterior, but he's alright once you get to know him.","","","","","",""],
["","","","he's actually the most recent arrival, besides you!","","","","","",""],
["","you","","oh, when did he get here?","","","","","",""],
["","oliver","","hmm, i think about a year ago?","","","","","",""],
["","","","he made quite a first impression on me, too.","","","","","",""],
["","you","","oh yeah?","","","","","",""],
["","oliver","","yes, he, um","","","","","",""],
["","","","he made some, let's say, very forward advances.","","","","","",""],
["","you","","ohhhhhhh, i see","","","","","",""],
["","","","i guess you don't swing that way, huh?","","","","","",""],
["","oliver","","no no, it's not that.","","","","","",""],
["","","","i, uh, \"swing both ways,\" so to speak.","","","","","",""],
["","you","","just not into snakes?","","","","","",""],
["","oliver","","no no no, you're putting words in my mouth!","","","","","",""],
["","","","i'll admit that he's, um, quite handsome","","","","","",""],
["","","","it's just that i wasn't...","","","","","",""],
["","","","i mean, i'm not looking for someone, at this point in my life--","","","","","",""],
["","","","or death, that is--","","","","","",""],
["","","","but maybe if the circumstances were different, then--","","","","","",""],
["","","","i'm just focusing on my research right now, is all!","","","","","",""],
["","you","","heh, alright","","","null","","",""],
["oliver_about_numa","you","","numa?","","","","","",""],
["","oliver","","oh, she's very sweet!","","","","","",""],
["","","","a bit of a recluse, however. hardly talks to anyone.","","numa_quest_complete",['oliver_about_numa1', 'oliver_about_numa2'],"","",""],
["oliver_about_numa1","","","well, except kyungsoon, i guess.","","","","","",""],
["","","","still not entirely sure how [i]that[/i] happened.","","","","","",""],
["oliver_about_numa2","you","","have you tried to talk to her?","","","","","",""],
["","oliver","","yes, several times, in fact.","","","","","",""],
["","","","i knew she was good with numbers, so i thought i would run some of my statistics past her.","","","","","",""],
["","you","","oh, good idea!","","","","","",""],
["","oliver","","yes, i thought so too, but...","","","","","",""],
["","","","it was just... an awkward experience, for both of us.","","","","","",""],
["","","","i think she's just more interested in flowers than she is other people.","","","","","",""],
["","you","","i see","","","null","","",""],
["oliver_about_tori","you","","tori?","","","","","",""],
["","oliver","","ah, she's a good friend of mine!","","","","","",""],
["","","","we often consult each other on our respective endeavours.","","","","","",""],
["","","","she has a sharp mind, that one.","","","","","",""],
["","you","","oh, what endeavours, exactly?","","","","","",""],
["","oliver","","well, she's always busy with something or the other.","","","","","",""],
["","","","i think last i checked, she was trying to build a wind turbine out of scrap...?","","","","","",""],
["","you","","really? what for?","","","","","",""],
["","","","does purrgatory even... have wind?","","","","","",""],
["","oliver","","well, i was a bit confused about that part too.","","","","","",""],
["","","","but i'm sure she has her reasons!","","","null","","",""],
["oliver_about_natalie","you","","natalie?","","","","","",""],
["","oliver","","oh, i haven't had a chance to see her in a while.","","","","","",""],
["","","","her usual hideaway is a bit of a trek from the library.","","","","","",""],
["","","","she is quite the artist, however!","","","","","",""],
["","you","","yeah, i've seen some of her stuff","","","","","",""],
["","","","she's pretty good!","","","","","",""],
["","oliver","","indeed!","","","null","","",""],
["oliver_research","you","","how's your work going?","","","","","",""],
["","oliver","","it's going well, thank you for asking!","","","","","",""],
["","","","","","","","",['is this what you did in real life?', 'can i help?'],['oliver_real_life', 'oliver_can_help']],
["oliver_leave","you","","i gotta go, catch you later","","","","","",""],
["","oliver","","until next time!","","","null","","",""],
["oliver_real_life","you","","is this what you did in real life? work in a library?","","","","","",""],
["","oliver","","oh, not quite. ","","","","","",""],
["","","","i did have an affinity for books, but that never quite translated into work at a library.","","","","","",""],
["","","","no, i was a doctorate student when i died. ","","","","","",""],
["","","","worked part-time as a barista.","","","","","",""],
["","you","","ooh, cool","","","","","",""],
["","","","what were you researching?","","","","","",""],
["","oliver","","oh","","","","","",""],
["","","","um","","","","","",""],
["","","","nothing interesting, i'm afraid.","","","","","",""],
["","you","","aw, i'm sure that's not true!","","","","","",""],
["","oliver","","well, it was mathematics. ","","","","","",""],
["","","","number theory, to be specific.","","","","","",""],
["","","","or diophantine approximation, to be even more specific.","","","","","",""],
["","","","which is, by the way, the use of rational numbers to approximate real numbers.","","","","","",""],
["","","","it's closely linked to transcendental numbers, in fact, and was used to prove the transcendentality of pi in 1882 by--","","","","","",""],
["","_none","","he stops short.","","","","","",""],
["","oliver","","ahem, i mean","","","","","",""],
["","","","there's really not that much to say about it, haha","","","","","",""],
["","","","","","","","",['(push for more)', '(be grateful you dodged a math lecture)'],['oliver_ask_for_more', 'oliver_dodged']],
["oliver_ask_for_more","you","","aw, it sounds interesting","","","","","",""],
["","","","tell me more!","","","","","",""],
["","_none","","oliver coughs and looks at his feet.","","","","","",""],
["","oliver","","really, i insist, there's nothing more to be said.","","","","","",""],
["","","","i died before i could complete my work, anyway","","","","","",""],
["","","","so for all intents and purposes, that research was wasted.","","","","","",""],
["","you","","awww, but i wanna know about transcendental numbers","","","oliver_dodge2","","",""],
["oliver_dodged","you","","well, if you say so.","","","","","",""],
["oliver_dodge2","oliver","","actually, i just remembered i have some... very important work to attend to.","","","","","",""],
["","","","if you'll excuse me...","","","","","",""],
["","you","","oh, okay","","","","","",""],
["","_none","_none","oliver shuffles away.","oliver_why","","null","","",""],
["oliver_can_help","you","","anything i can do to help?","","","","","",""],
["","oliver","","well, as a matter of fact, yes!","","","","","",""],
["","","","i have an EXTREMELY exciting discovery i want to share with you.","","","","","",""],
["","_none","","oliver grabs a book off a nearby table and opens a bookmarked page.","","","","","",""],
["","oliver","","here, take a look at this...","_delay__goto_meopw","","null","","",""],
["oliver_can_help_meopw","you","","oh!","","","","","",""],
["","","","one of the meows is misspelled!","","","","","",""],
["","oliver","","yes! exactly!","","","","","",""],
["","","","instead of meow, it says meopw","","","","","",""],
["","","","m-e-o-p-w","","","","","",""],
["","","","what do you think it means??","","","","","",""],
["","","","","","","","",['um... does it mean anything?', 'it\'s the answer you\'ve been looking for!'],['oliver_nothing', 'oliver_key_to_the_code']],
["oliver_nothing","you","","um... does it have to mean anything?","","","","","",""],
["","","","i mean, it's just a printing error, right? like a typo","","","","","",""],
["","oliver","","is it a typo, or is it a key to the code?","","","","","",""],
["","","","is it nothing, or is it everything i've been hoping for?","","","","","",""],
["","","","that's the question!","","","oliver_can_help2","","",""],
["oliver_key_to_the_code","you","","this could be the answer you've been looking for!","","","","","",""],
["","oliver","","that's exactly what i'm hoping!","","","","","",""],
["","","","but i'm almost afraid to say it...","","","","","",""],
["oliver_can_help2","oliver","oliver_neutral","no, no, i shouldn't get my hopes up.",[['_goto_library', true], ['_hide_oliver_idle', true]],"","","","",""],
["","","","you see, i've measured it, weighed it, scrutinized every inch of the page...","","","","","",""],
["","","","but for all intents and purposes, this book is unremarkable.","","","","","",""],
["","","","so, to go back to your offer of help, i was hoping a fresh pair of eyes could shed some light on the situation!","","","","","",""],
["","you","","ooh, i'll do my best!","","","","","",""],
["","_none","","oliver shows you the book again.","","","","","",""],
["","oliver","","so, does anything immediately spring to mind? anything unusual or worthy of investigation?","","","","","",""],
["","you","","hm...","","","","","",""],
["oliver_can_help3","","","","","","",['not suggested_crease', 'not suggested_smudge', 'not suggested_binding', 'not suggested_code'],['this crease looks interesting', 'did you notice this smudge?', 'have you tried looking inside the binding?', 'maybe it\'s a secret code'],['oliver_crease', 'oliver_smudge', 'oliver_binding', 'oliver_code']],
["oliver_crease","you","","this crease in the corner looks interesting!","suggested_crease","","","","",""],
["","oliver","","ooh, sharp eye!","","","","","",""],
["","","","it looks like the page is crumpled slightly here.","","","","","",""],
["","","","clearly it means...","","","","","",""],
["","you","","...","","","","","",""],
["","oliver","","hmm...","","","","","",""],
["","you","","it means what?","","","","","",""],
["","oliver","","it means that...","","","","","",""],
["","","","...maybe someone was a little too forceful when turning the page?","","","","","",""],
["","you","","yeah, that's probably it","","","oliver_can_help3","","",""],
["oliver_smudge","you","","did you notice this smudge on the cover?","suggested_smudge","","","","",""],
["","oliver","","[i]gasp[/i]","","","","","",""],
["","","","how did i miss that before??","","","","","",""],
["","you","","is something written there?","","","","","",""],
["","","","maybe a clue?","","","","","",""],
["","oliver","","let's see...","","","","","",""],
["","_none","","oliver pulls out a magnifying glass and squints through it.","","","","","",""],
["","oliver","","it looks like it's...","","","","","",""],
["","","","yes, it seems to be...","","","","","",""],
["","","","a bit of dust?","","","","","",""],
["","_none","","oliver wipes it clean with his thumb.","","","","","",""],
["","you","","oh","","","oliver_can_help3","","",""],
["oliver_binding","you","","have you tried looking inside the binding?","suggested_binding","","","","",""],
["","","","like, there might be a message or something sewn into the spine","","","","","",""],
["","","","i think i saw that once in a spy movie!","","","","","",""],
["","oliver","","brilliant!","","","","","",""],
["","_none","","oliver holds the book to eye level and closely examines the spine","","","","","",""],
["","oliver","","hmm.... normally I would never do this, but I think we should take this book apart.","","","","","",""],
["","","","who knows what could be hidden inside? a message? a computer chip?","","","","","",""],
["","you","","the key to purrgatory?","","","","","",""],
["","oliver","","maybe so!! ","","","","","",""],
["","","","now, this shouldn't take more than a minute.","","","","","",""],
["","_none","","oliver takes an exacto knife from a drawer nearby, then cuts down the seam of the spine repeatedly.","","","","","",""],
["","oliver","","voila!","","","","","",""],
["","_none","","oliver holds up the separated stack of pages.","","","","","",""],
["","oliver","","now to take a closer look...","","","","","",""],
["","you","","...","","","","","",""],
["","oliver","","...","","","","","",""],
["","you","","see anything?","","","","","",""],
["","oliver","","well...","","","","","",""],
["","you","","there's nothing, isn't there?","","","","","",""],
["","oliver","","i mean, i wouldn't say [i]nothing,[/i] but...","","","","","",""],
["","","","...","","","","","",""],
["","","","yeah, there's nothing.","","","","","",""],
["","you","","aww","","","","","",""],
["","oliver","","[i]sigh[/i]","","","","","",""],
["","","","this poor book...","","","","","",""],
["","_none","","he cradles the deconstructed book as if mourning it.","","","oliver_can_help3","","",""],
["oliver_code","you","","maybe it's a secret code?","suggested_code","","","","",""],
["","","","like, maybe if you look at the first word on every page, it'll spell out a message or something?","","","","","",""],
["","oliver","","hey, that's not a bad idea!","","","","","",""],
["","","","well","","","","","",""],
["","","","no, that would just spell out \"meow meow meow\"","","","","","",""],
["","you","","oh. yeah","","","","","",""],
["","oliver","","but the idea of a hidden code is intriguing...","","","","","",""],
["","","","there are meows of varying lengths... maybe each one encodes a letter?","","","","","",""],
["","","","or maybe the punctuation is of importance?","","","","","",""],
["","you","","or you could count the number of meows on each page?","","","","","",""],
["","oliver","","yes, of course!","","","","","",""],
["","","","so many avenues of research!!","","suggested_binding",['oliver_code1', 'oliver_code2'],"","",""],
["oliver_code1","_none","","oliver gently gathers the parts of the deconstructed book.","","","oliver_code3","","",""],
["oliver_code2","_none","","oliver shuts the book.","","","","","",""],
["oliver_code3","oliver","","i need to develop a course of action immediately. there's no time to waste!","","","","","",""],
["","","","","","","","",['good luck!', 'good luck, but don\'t get your hopes up'],['oliver_got_this', 'oliver_just_empty']],
["oliver_got_this","you","","good luck!","","","","","",""],
["","oliver","","thank you, thank you.","","","oliver_code4","","",""],
["oliver_just_empty","you","","good luck!","","","","","",""],
["","","","but... try not to get your hopes up too much","","","","","",""],
["","","","i mean, it really might just be a typo.","","","","","",""],
["","","","\"p\" is right next to \"o\" on the keyboard, after all","","","","","",""],
["","oliver","","well... i suppose that's true.","","","","","",""],
["","","","i will have to bear that possibility in mind.","","","","","",""],
["oliver_code4","oliver","","now if you need me, i'll be in my study!","","","","","",""],
["","_none","","oliver rushes away before you can ask where his study is.","oliver_in_study","","null","","",""],
["oliver_default_b","oliver","oliver_neutral","oh, hey, {player}.","","seen_study",['oliver_default_b2', 'oliver_default_b1'],"","",""],
["oliver_default_b1","you","","so this is your study, huh?","seen_study","","","","",""],
["","oliver","","yes, indeed!","","","","","",""],
["","","","my little corner i've carved out of purrgatory.","","","","","",""],
["","","","um, sorry it's so messy.","","","","","",""],
["","you","","heh, it's alright.","","","","","",""],
["oliver_default_b2","oliver","","i'm a little busy right now. is there something you want to talk about?","","","","","",""],
["","","","","","","",['true', '_inv_natalies_books', 'true', 'true'],['what\'s up?', "(return natalie's books)", 'what do you think of the others?', 'how\'s your work going?'],['oliver_wasup', 'oliver_natalies_books', 'oliver_others', 'oliver_research_b']],
["oliver_research_b","you","","how's your work going?","","","","","",""],
["","oliver","","quite well, quite well.","","","","","",""],
["","","","just gathering some frequency data right now.","","","","","",""],
["","","","i've been working through some of the ideas we brainstormed earlier -- no results yet, but i'm confident i'll find a lead soon.","","","","","",""],
["","","","","","","",['true', 'not _inv_chess_letter', '_inv_chess_letter', 'true'],['is this what you did in real life?', 'can i help?', 'can i help?'],['oliver_real_life', 'oliver_can_help_b1', 'oliver_can_help_b2']],
["oliver_can_help_b1","you","","can i help?","","","","","",""],
["","oliver","","uhh, well","","","","","",""],
["","","","i really appreciate the offer, but...","","","","","",""],
["","","","i'm quite busy crunching data right now, so i just need some time, if you understand.","","","","","",""],
["","you","","are you sure? are there any errands you need done, or...?","","","","","",""],
["","oliver","","well...","","","","","",""],
["","","","i [i]suppose[/i] i need to deliver my next chess move to tori...","","","","","",""],
["","you","","your next chess move?","","","","","",""],
["","oliver","","yes, tori and i play chess by correspondence!","","","","","",""],
["","you","","wait... but... don't you both live in the same place?","","","","","",""],
["","","","why don't you just play the game in person?","","","","","",""],
["","oliver","","[i]shrug[/i]","","","","","",""],
["","","","it's more fun this way. builds up the anticipation.","","","","","",""],
["","","","anyway, she should be expecting this letter, if you wouldn't mind delivering it","","","","","",""],
["","","","if you haven't met her, she's the tall owl lady, impossible to miss.","","","","","",""],
["","you","","well, alrighty","","","","","",""],
["","","","post master {player} is on the case!","","","","","",""],
["","oliver","","haha, i appreciate it.","","","","","",""],
["","_none","","oliver hands you an envelope.",[['_inv_chess_letter', true], ['_quest_oliver_chess', true]],"","","","",""],
["","oliver","","now i'd better get back to my research.","","","","","",""],
["","you","","alright, catch ya later!","","","null","","",""],
["oliver_can_help_b2","you","","is there anything else i can do to help?","","","","","",""],
["","oliver","","no, no, delivering the letter will be fine, thank you.","","","","","",""],
["","you","","alrighty","","","null","","",""],
["oliver_default_c","you","oliver_neutral","oliver?","","","","","",""],
["","oliver","","huh?","","","","","",""],
["","","","oh. hello. sorry.","","","","","",""],
["","","","can i help you with something?","","","","","",""],
["","","","","","","",['true', '_inv_natalies_books', 'true', 'true'],['what\'s up?', "(return natalie's books)", 'what do you think of the others?', 'how\'s your work going?'],['oliver_wasup_c', 'oliver_natalies_books', 'oliver_others_c', 'oliver_research_c']],
["oliver_wasup_c","you","","what's up?","","","","","",""],
["","oliver","","still researching.","","","","","",""],
["","you","","cool, cool","","","","","",""],
["","oliver","","if i keep taking shots at the dark... something's gotta turn up eventually... right?","","","","","",""],
["","you","","um, sure!","","","null","","",""],
["oliver_others_c","you","","what do you think of the others?","","","","","",""],
["","oliver","","they're fine, i suppose","","","","","",""],
["","","","sorry, i don't really have time to chat right now.","","","","","",""],
["","you","","ah, that's okay","","","null","","",""],
["oliver_research_c","you","","how's your work going?","","","","","",""],
["","oliver","","still looking for a foothold.","","","","","",""],
["","","","the vignere cipher was a dead end... but maybe an affine cipher?","","","","","",""],
["","","","","","","",['true', 'not oliver_asked_for_soda', 'oliver_asked_for_soda'],['is this what you did in real life?', 'can i help?', 'can i help?'],['oliver_real_life_c', 'oliver_can_help_c1', 'oliver_can_help_c2']],
["oliver_real_life_c","you","","is this what you did in real life?","","","","","",""],
["","oliver","","not really.","","","","","",""],
["","","","well, if you mean beating my head against a wall hoping for a breakthrough, then yes.","","","","","",""],
["","","","i'm sorry, i really can't spare the time to talk right now.","","","","","",""],
["","you","","oh, that's alright.","","","null","","",""],
["oliver_leave_c","you","","i gotta go, catch you later","","","","","",""],
["","oliver","","until next time.","","","null","","",""],
["oliver_can_help_c1","you","","is there anything i can do to help?","","","","","",""],
["","oliver","","no thank you.","","","","","",""],
["","you","","are you sure? ","","","","","",""],
["","","","don't take this the long way, but... you look exhausted","","","","","",""],
["","oliver","","really, i'm fine.","","","","","",""],
["","you","","i could help you clean, keep you company--","","","","","",""],
["","oliver","","{player}!","","","","","",""],
["","","","i'm serious, i don't need any help. ","","","","","",""],
["","","","some space, please.","","","","","",""],
["","","","","","","","",['push it', 'back off'],['oliver_push_it', 'oliver_back_off']],
["oliver_push_it","you","","well i think you [i]do[/i] need help!","","","","","",""],
["","","","staying cooped up in here isn't healthy for you. you should at least let me get you something to drink!","","","","","",""],
["","","","...please?","","","","","",""],
["","oliver","","...","","","","","",""],
["","","","well...","","","","","",""],
["","","","i suppose i am a bit parched.","","","","","",""],
["","","","some orange soda would be nice.","oliver_asked_for_soda","","","","",""],
["","you","","alright, you got it. one orange soda coming right up!","_quest_oliver_soda1","","","","",""],
["","oliver","","thank you.","","","","","",""],
["","_none","","oliver goes back to scribbling without another word.","cat_in_house","","null","","",""],
["oliver_back_off","you","","geez, okay. i'm sorry","","","","","",""],
["","oliver","","it's fine. ","","","","","",""],
["","","","i'm... sorry for snapping at you.","","","","","",""],
["","you","","it's okay.","","","null","","",""],
["oliver_can_help_c2","you","","you said you wanted orange soda, right?","","","","","",""],
["","oliver","","yes, that's right.","","","","","",""],
["","you","","anything else i can do?","","","","","",""],
["","oliver","","no thank you.","","","","","",""],
["","you","","alrighty","","","null","","",""],
["oliver_default_d","you","","oliver?","","","","","",""],
["","","","...","","","","","",""],
["","","","oliver, i couldn't find a cup for your soda.","","","","","",""],
["","_none","","he's fast asleep.","","","","","",""],
["","","","","","","","",['wake him up', 'put his blanket over him', 'leave him alone'],['oliver_wake_up', 'oliver_blanket', 'oliver_leave_alone']],
["oliver_leave_alone","_none","","maybe you can check back later.","","","null","","",""],
["oliver_blanket","_none","","you grab the blanket from oliver's bed and drape it over his shoulders.","","","","","",""],
["","oliver","","pfdk... andrew, stop it...","","","","","",""],
["","_none","","you freeze.","","","","","",""],
["","oliver","","jusfive minutes....","","","","","",""],
["","_none","","you slowly back away from oliver.","","","","","",""],
["","","","before you can get out the door, you knock over a tin can full of pens.","","","","","",""],
["","oliver","oliver_neutral","[i]SNck.[/i] guck. huh?","_hide_oliver_asleep_at_desk","","","","",""],
["","you","","sorry! i didn't mean to wake you up!","","","oliver_wake_up2","","",""],
["oliver_wake_up","you","","oliver.","","","","","",""],
["","","","oliver!!","","","","","",""],
["","oliver","oliver_neutral","[i]SNck.[/i] guck. huh?","_hide_oliver_asleep_at_desk","","","","",""],
["","you","","sorry, you... fell asleep at your desk.","","","","","",""],
["oliver_wake_up2","oliver","","wh... it's ok, ij..","","","","","",""],
["","_none","","oliver stares blearily at you, then his papers.","","","","","",""],
["","oliver","","how long ws i out?","","","","","",""],
["","you","","i don't know, i just got here","","","","","",""],
["","","","i was going to tell you i couldn't find a cup.",[['_quest_oliver_soda2', false]],"","","","",""],
["","oliver","","ah, fuck, i'm gonna miss the deadline...","","","","","",""],
["","_none","","he rubs his eyes and searches for a pen.","","","","","",""],
["","you","","what deadline?","","","","","",""],
["","oliver","","thesis deadline. it's in...","","","","","",""],
["","","","it's...","","","","","",""],
["","","","where am i, again?","","","","","",""],
["","","","","","","","",['purrgatory', 'your study'],['oliver_where1', 'oliver_where2']],
["oliver_where1","you","","purrgatory, remember?","","","","","",""],
["","oliver","","oh. right.","","","","","",""],
["","","","purrgatory with two r's.","","","","","",""],
["","","","i remember i was very indignant about that...","","","oliver_where3","","",""],
["oliver_where2","you","","your study, remember?","","","","","",""],
["","oliver","","oh. right.","","","","","",""],
["","","","boy, i should really clean this place...","","","","","",""],
["oliver_where3","oliver","","sorry about that. i don't know what came over me.","","","","","",""],
["","","","thank you for waking me up, but i should get back to work.","","","","","",""],
["","","","","","","","",['oh no you don\'t', 'i really think you should take a break'],['oliver_oh_no_you_dont', 'oliver_take_a_break']],
["oliver_oh_no_you_dont","you","","oh, no you don't.","","","","","",""],
["","","","you're like, passing out due to exhaustion","","","","","",""],
["","","","you need a break.","","","","","",""],
["","oliver","","i'll be fine!","","","","","",""],
["","","","{player}, this is important.","","","","","",""],
["","","","this is the only lead that i--","","","","","",""],
["","you","","nope!","","","","","",""],
["","","","you're taking a break right now!","","","","","",""],
["","oliver","","...[i]sigh[/i]","","","","","",""],
["","","","i don't know. i've never been able to just sit around when there's work to be done.","","","oliver_take_a_break2","","",""],
["oliver_take_a_break","you","","oliver, i really think you should take a break.","","","","","",""],
["","","","you must be really tired if you fell asleep at your desk like that...","","","","","",""],
["","oliver","","i'll be fine!","","","","","",""],
["","","","{player}, this is important.","","","","","",""],
["","","","this is the only lead that i--","","","","","",""],
["","you","","i know, i know!","","","","","",""],
["","","","i'm just worried about your health and stuff","","","","","",""],
["","oliver","","i appreciate the concern. ","","","","","",""],
["","","","now please, i have to get back to work.","","","","","",""],
["","you","","fine...","","","","","",""],
["","oliver","","...[i]yawn.[/i] thank you. i'm glad you... see reason...","","","","","",""],
["","you","_none","will you at least stretch every now and then?","show_oliver_asleep_at_desk","","","","",""],
["","","","...","","","","","",""],
["","","","oliver?","","","","","",""],
["","","","...","","","","","",""],
["","","","OLIVER!!","","","","","",""],
["","oliver","oliver_neutral","HSBTHWHAT?","_hide_oliver_asleep_at_desk","","","","",""],
["","","","oh. sorry","","","","","",""],
["","you","","you fell asleep again","","","","","",""],
["","oliver","","yeah, i know","","","","","",""],
["","","","maybe... maybe you have a point.","","","","","",""],
["","you","","heh, i thought so.","","","","","",""],
["","oliver","","...[i]sigh[/i]","","","","","",""],
["","","","i've never been able to just sit around when there's work to be done.","","","","","",""],
["oliver_take_a_break2","you","","well, you don't have to sit around and do nothing!","","","","","",""],
["","","","maybe we can go for a walk?","","","","","",""],
["","","","get a change in scenery or something?","","","","","",""],
["","oliver","","a walk where, exactly?","","","","","",""],
["","you","","um...","oliver_on_date","","","","",""],
["","","","","","","","",['the park', 'the meowseum'],['oliver_scenery1', 'oliver_scenery2']],
["oliver_scenery1","you","","how about the park?","oliver_chose_park","","","","",""],
["","oliver","","that sounds...","","","","","",""],
["","","","agreeable.","","","","","",""],
["","you","","let's go, then!","","","","","",""],
["","oliver","","right now?","","","","","",""],
["","","","maybe I can just finish annotating this data and--","","","","","",""],
["","you","","yes, right now!","","","","","",""],
["","","","come on","","","","","",""],
["","oliver","","alright, alright.","","","","","",""],
["","_none","","oliver follows you to the park.","oliver_goto_park1","","","","",""],
["","you","","this is nice, right?","","","","","",""],
["","","","some fresh air and exercise!","","","","","",""],
["","oliver","","i'm not sure if i would this air \"fresh\"...","","","","","",""],
["","you","","but look at all those trees!","","","","","",""],
["","","","trees make oxygen, right?","","","","","",""],
["","oliver","","living ones, yes. i think all of these are dead.","","","","","",""],
["","you","","oh. right.","","","","","",""],
["","_none","","you walk in silence for a while.","oliver_goto_park2","","","","",""],
["","you","","i wonder who's buried here?","","","","","",""],
["","oliver","","[i]shrug[/i]","","","","","",""],
["","you","","whoever it is, they must have made a [i]grave[/i] mistake!","","","","","",""],
["","oliver","","...","","","","","",""],
["","","","hah","","","","","",""],
["","_none","","you walk in silence some more.","oliver_goto_park3","","","","",""],
["","you","","...","","","","","",""],
["","oliver","","...","","","oliver_scenery4","","",""],
["oliver_scenery2","you","","how about the meowseum?","oliver_chose_meowseum","","","","",""],
["","oliver","","that sounds...","","","","","",""],
["","","","agreeable.","","","","","",""],
["","you","","let's go, then!","","","","","",""],
["","oliver","","right now?","","","","","",""],
["","","","maybe I can just finish annotating this data and--","","","","","",""],
["","you","","yes, right now!","","","","","",""],
["","","","come on","","","","","",""],
["","oliver","","alright, alright.","","","","","",""],
["","_none","","oliver follows you to the meowseum.","oliver_goto_meowseum1","","","","",""],
["","you","","ah, culture and art. refreshing!","","","","","",""],
["","oliver","","i'm not sure if i would call this \"culture\"...","","","","","",""],
["","you","","what do you mean?","","","","","",""],
["","","","there's a da vinci right there!","","","","","",""],
["","oliver","","i think that one's vermeer.","","","","","",""],
["","you","","oh. right.","","","","","",""],
["","_none","","you walk in silence for a while.","oliver_goto_meowseum2","","","","",""],
["","you","","i wonder if the schrodinger's cat is dead or alive?","","","","","",""],
["","oliver","","[i]shrug[/i]","","","","","",""],
["","you","","i guess the smell would be a [i]dead[/i] giveaway!","","","","","",""],
["","oliver","","...","","","","","",""],
["","","","hah","","","","","",""],
["","_none","","you walk in silence some more.","oliver_goto_meowseum3","","","","",""],
["","you","","...","","","","","",""],
["","oliver","","...","","","oliver_scenery4","","",""],
["oliver_scenery4","","","","","","","",['you\'re so quiet', 'what\'s on your mind?'],['oliver_quiet', 'oliver_thinking_about']],
["oliver_quiet","you","","you're so quiet","","","","","",""],
["","","","like a mouse, even","","","","","",""],
["","oliver","","sorry.","","","","","",""],
["","","","just tired.","","","","","",""],
["","you","","it's alright","","","","","",""],
["","","","you don't have to apologize for something like that","","","","","",""],
["","oliver","","[i]shrug[/i]","","","oliver_lively","","",""],
["oliver_thinking_about","you","","what's on your mind?","","","","","",""],
["","oliver","","nothing.","","","","","",""],
["","","","just tired.","","","","","",""],
["","you","","are you sure?","","","","","",""],
["","","","you're usually more... lively","","","","","",""],
["","oliver","","i suppose i am.","","","","","",""],
["oliver_lively","you","","...","","","","","",""],
["","","","want to sit on that bench?","","","","","",""],
["","oliver","","sure.","","","","","",""],
["","_none","","you sit.","","","","","",""],
["","oliver","","...","","","","","",""],
["","you","","...","","","","","",""],
["","oliver","","you know...","","","","","",""],
["","","","i've always had a hard time admitting that i'm wrong.","","","","","",""],
["","you","","oh?","","","","","",""],
["","oliver","","yes, and sometimes it leads to me... acting rude.","","","","","",""],
["","","","it's something that i was working on. ","","","","","",""],
["","","","back when i was alive.","","","","","",""],
["","you","","ah, i see","","","","","",""],
["","","","","","","","",['i had that problem too', 'my problem is that i\'m ALWAYS wrong', '(stay quiet)'],['oliver_problem1', 'oliver_problem2', 'oliver_problem3']],
["oliver_problem1","you","","i used to have that problem too","","","","","",""],
["","","","i would get reeeally stubborn when i got into an argument, even if i wasn't sure about what i was saying","","","","","",""],
["","oliver","","i see.","","","","","",""],
["","","","how did you... you know... deal with it?","","","","","",""],
["","you","","well, i guess i just learned how to say \"you're right\" and move on","","","","","",""],
["","oliver","","but that's ridiculous","","","","","",""],
["","","","what if they're not right at all?","","","","","",""],
["","","","you'd just make them feel vindicated about their wrong opinion","","","","","",""],
["","you","","hmm... you're right","","","","","",""],
["","oliver","","exactly.","","","","","",""],
["","","","...","","","","","",""],
["","","","wait... did you just...","","","","","",""],
["","you","","hehe","","","","","",""],
["","","","maybe","","","","","",""],
["","","","i just think most things in life aren't worth arguing about, is all","","","","","",""],
["","oliver","","hmm.","","","oliver_problem3","","",""],
["oliver_problem2","you","","my problem is that i'm ALWAYS wrong","","","","","",""],
["","oliver","","well, i'm sure that's not true.","","","","","",""],
["","you","","nah, it's okay","","","","","",""],
["","","","being wrong has its upsides too","","","","","",""],
["","oliver","","what could possibly be an upside to being wrong?","","","","","",""],
["","you","","well, you learn a lot more that way!","","","","","",""],
["","","","and sometimes you learn from really interesting people","","","","","",""],
["","oliver","","hmm.","","","","","",""],
["oliver_problem3","oliver","","i remember in middle school--","","","","","",""],
["","","","this is kind of a stupid story, but--","","","","","",""],
["","","","on the way to school one day, my brother pointed out that my shirt was inside out.","","","","","",""],
["","you","","mhm","","","","","",""],
["","oliver","","the funny thing is, i already knew it was inside out, but i didn't want to acknowledge that he was right.","","","","","",""],
["","","","so i just left it like that the entire day","","","","","",""],
["","","","i told my friends it was an inside joke, and for some inane reason it started catching on.","","","","","",""],
["","","","the school was plagued with inside out clothes for weeks.","","","","","",""],
["","you","","nice","","","","","",""],
["","","","truly a trendsetter","","","","","",""],
["","oliver","","heh, in a way, yes.","","","","","",""],
["","","","but it's kind of sad, isn't it?","","","","","",""],
["","","","i wore my shirt inside out for an entire month just to prove my brother wrong.","","","","","",""],
["","you","","aw, you were just a kid.","","","","","",""],
["","","","kids do all sorts of dumb things.","","","","","",""],
["","oliver","","i suppose so.","","","","","",""],
["","","","...","","","","","",""],
["","you","","...","","","","","",""],
["","oliver","","want to play tic-tac-toe?","","","","","",""],
["","you","","sure!","","","ttt_init","","",""],
["oliver_after_ttt","you","","...","","","","","",""],
["","","","sorry for calling you a doo doo head","","","","","",""],
["","oliver","","it's fine. ","","","","","",""],
["","you","","...","","","","","",""],
["","oliver","","you know...","","","","","",""],
["","","","sometimes, i wonder","","","","","",""],
["","","","if i'm a good person","","","","","",""],
["","","","","","","","",['you are a good person!', 'no one\'s a good person, really', '(shrug)'],['oliver_good_person1', 'oliver_good_person2', 'oliver_good_person3']],
["oliver_good_person1","you","","aw, you are a good person!","","","","","",""],
["","","","you were really welcoming and kind to me when i showed up and...","","","","","",""],
["","","","you know...","","","","","",""],
["","","","you're really... passionate!","","","","","",""],
["","","","i'm not as good with words as you, but i think you get what i mean","","","","","",""],
["","oliver","","well... i'm glad you think so","","","","","",""],
["","","","but still...","","","oliver_good_person4","","",""],
["oliver_good_person2","you","","no one's a good person, really","","","","","",""],
["","","","i mean, we all have our flaws, right?","","","","","",""],
["","","","it's nothing worth beating yourself up about","","","","","",""],
["","oliver","","i guess that's true","","","","","",""],
["","","","but still...","","","oliver_good_person4","","",""],
["oliver_good_person3","you","","[i]shrug[/i]","","","","","",""],
["","","","i don't know.","","","","","",""],
["","oliver","","...","","","","","",""],
["","","","so you don't think i'm a good person either...","","","","","",""],
["","you","","no no, i didn't say that!","","","","","",""],
["","oliver","","it's okay.","","","","","",""],
["","","","it's no wonder you feel that way, after how i treated you.","","","","","",""],
["","","","i'm... sorry.","","","","","",""],
["","","","i should go.","","","","","",""],
["","you","","are you sure?","","","","","",""],
["","oliver","","i just... need some time alone.","oliver_bad_end","","","","",""],
["","you","","um, alright",[['oliver_on_date', false]],"","","","",""],
["","","","try to get some rest, okay?","comforted_oliver","","","","",""],
["","oliver","","whatever.","oliver_sleeping","","","","",""],
["","_none","","oliver hesitates, then trudges away.","oliver_sleeping_timer","","null","","",""],
["oliver_good_person4","","","it just seems like...","","","","","",""],
["","","","i keep making the same mistakes","","","","","",""],
["","","","over and over","","","","","",""],
["","_none","","oliver puts his head in his hands.","","","","","",""],
["","oliver","","i haven't learned anything, have i?","","","","","",""],
["","you","","i'm... sorry","","","","","",""],
["","","","do you want to talk about it?","","","","","",""],
["","oliver","","...","","","","","",""],
["","","","well...","","","","","",""],
["","","","you see, when i died...","","","","","",""],
["","","","i was working on my thesis","","","","","",""],
["","","","the littlewood conjecture. an obscure number theory problem.","","","","","",""],
["","","","it was...","","","","","",""],
["","","","well, it [i]felt[/i] like...","","","","","",""],
["","","","the most important thing in the world.","","","","","",""],
["","","","it feels silly to say it now.","","","","","",""],
["","","","i'm sorry, you probably don't want to hear any of this.","","","","","",""],
["","you","","no, it's okay","","","","","",""],
["","","","i don't mind listening","","","","","",""],
["","oliver","","[i]sniff[/i]","","","","","",""],
["","","","well","","","","","",""],
["","","","my brother, andrew, he reached out to me, after many years.","","","","","",""],
["","","","he had made some... uh... poor life choices, to say the least.","","","","","",""],
["","","","he needed help, and after our mother passed away, i was the only one left who [i]could[/i] help.","","","","","",""],
["","","","but i...","","","","","",""],
["","","","well, i was out of grant money","","","","","",""],
["","","","so i didn't think i could--","","","","","",""],
["","","","well, i calculated that--","","","","","",""],
["","","","i mean, taking into consideration my brother's lifestyle--","","","","","",""],
["","","","...","","","","","",""],
["","","","[i]sniff[/i]","","","","","",""],
["","","","never mind.","","","","","",""],
["","","","it doesn't matter. ","","","","","",""],
["","","","i cut off contact entirely.","","","","","",""],
["","","","i don't even know if he's alive or dead","","","","","",""],
["","you","","oh, i'm sorry...","","","","","",""],
["","oliver","","it's... it's fine.","","","","","",""],
["","","","the point is, i gave everything up for my research.","","","","","",""],
["","","","everything and everyone","","","","","",""],
["","","","and before i could even finish, there was a car accident","","","","","",""],
["","","","i remember...","","","","","",""],
["","_none","","oliver wipes his eyes.","","","","","",""],
["","oliver","","i remember","","","","","",""],
["","","","it wsa a snowy night","","","","","",""],
["","","","and","","","","","",""],
["","","","as i was dying","","","","","",""],
["","","","my last thoguht was","","","","","",""],
["","","","at least now i couldsee my mother","","","","","",""],
["","","","and apologize ","","","","","",""],
["","","","for e verythign","","","","","",""],
["","","","but...","","","","","",""],
["","","","...","","","","","",""],
["","","","","","","","",['hug him', 'pat his back'],['oliver_hug1', 'oliver_hug2']],
["oliver_hug1","_none","_none","you hug oliver.","","","","","",""],
["","you","","there there...","","","","","",""],
["","","","it's all in the past now","","","","","",""],
["","","","all you can do is try to move on","","","","","",""],
["","oliver","","[i]sniff[/i]","","","","","",""],
["","","","yeah...","","","","","",""],
["","","","maybe that's what they would have wanted...","","","","","",""],
["","_none","","you let oliver cry into your shoulder for a while.","","","oliver_hug3","","",""],
["oliver_hug2","_none","","you pat oliver's back.","","","","","",""],
["","you","","it's okay...","","","","","",""],
["","","","everyone makes mistakes sometimes, even big ones","","","","","",""],
["","","","there's nothing you can do to change it now","","","","","",""],
["","oliver","","[i]sniff[/i]","","","","","",""],
["","","","i know...","","","","","",""],
["","","","that's the worst part about it...","","","","","",""],
["","_none","","you keep oliver company as he cries for a while.","","","","","",""],
["oliver_hug3","_none","","eventually, he draws himself up.","","","","","",""],
["","oliver","oliver_neutral","[i]sniff[/i]","","","","","",""],
["","","","i should go.","","","","","",""],
["","you","","are you going to be okay?","","","","","",""],
["","oliver","","yes, i'll be fine.","","","","","",""],
["","","","i think... i'm going to take a nap.","","","","","",""],
["","you","","that is a very good idea","","","","","",""],
["","oliver","","and, um...","","","","","",""],
["","","","[i]sniff[/i]","","","","","",""],
["","","","thank you.","","","","","",""],
["","","","for playing tic-tac-toe with me.","","","","","",""],
["","you","","you're welcome!",[['oliver_on_date', false]],"","","","",""],
["","oliver","","i'll see you later.","comforted_oliver","","","","",""],
["","you","","seeya","oliver_sleeping","","","","",""],
["","_none","","oliver trudges away.","oliver_sleeping_timer","","null","","",""],
["oliver_sleeping","_none","","it looks like he's getting some much-needed rest.","","","","","",""],
["","","","better leave him alone for now.","","","null","","",""],
["oliver_default_e","oliver","oliver_neutral","hello, {player}!","","","","","",""],
["","you","","hey, you're awake!","","","","","",""],
["","","","are you feeling any better?","","","","","",""],
["","oliver","","yes yes, i'm feeling much better!","","","","","",""],
["","","","i really needed that nap.","","","","","",""],
["","you","","hehe, told you so","","","","","",""],
["","oliver","","yes, i... ","","","","","",""],
["","","","i suppose you were right on that one.","","","","","",""],
["","","","the truth is, the case of the intrusive \"p\" was stagnating, and hard. ","","","","","",""],
["","","","maybe it's time to admit there really is no hidden message in that book.","","","","","",""],
["","","","i like to imagine there's a typist that came out the wrong end of purrgatory, and the devil handed them a typewriter and said:","","","","","",""],
["","","","\"welcome to the hellfire press! your job is to type this one word over and over until the end of time.\"","","","","","",""],
["","","","and one day that typist's finger slipped, and this one misprint found its way to the shelves.","","","","","",""],
["","you","","wow","","","","","",""],
["","oliver","","eheh, excuse me waxing poetic for a moment.","","","","","",""],
["","","","all that to say, we may never know why this typo exists.","","","","","",""],
["","","","in any case, i decided it's best to return to my usual activities -- cataloging, and whatnot -- at least until new insight strikes.","","","","","",""],
["","","","thank you for all of your help.","","","","","",""],
["","you","","yeah, no problem!","","","","","",""],
["","","","i'm glad you're finally moving on","","","","","",""],
["","oliver","","in fact, if you don't mind, i have one more favor to ask of you.","","","","","",""],
["","you","","sure, what can i do?","","","","","",""],
["","oliver","","would you help me carry these books outside?","","","","","",""],
["","you","","uh, okay","","","","","",""],
["","","","why?","","","","","",""],
["","oliver","","you'll see, you'll see.","",['numa_at_commons', 'ks_at_commons'],['oliver_gave_books1', 'oliver_gave_books2', 'oliver_gave_books_alt'],"","",""],
["oliver_gave_books1","_none",['numa_neutral', 'kyungsoon_neutral', 'oliver_neutral'],"you walk to the commons together.","oliver_goto_commons","","oliver_gave_books3","","",""],
["oliver_gave_books2","_none",['kyungsoon_neutral', 'oliver_neutral'],"you walk to the commons together.","oliver_goto_commons","","","","",""],
["oliver_gave_books3","oliver","","kyungsoon!","","","","","",""],
["","kyungsoon","","...","","","","","",""],
["","","","yeah?","","","","","",""],
["","oliver","","um...","","","","","",""],
["","","","here are some books!","","","","","",""],
["","kyungsoon","","i can see that","","","","","",""],
["","oliver","","no no no","","","","","",""],
["","","","what i mean is","","","","","",""],
["","","","here are some books... for [i]you[/i]!","","","","","",""],
["","kyungsoon","","...","","","","","",""],
["","","","really?","","","","","",""],
["","oliver","","yep!","","","","","",""],
["","","","i've made copies of all of them, so you can eat to your stomach's content.","","","","","",""],
["","kyungsoon","","what's the catch?","","","","","",""],
["","oliver","","there's no catch!","","","","","",""],
["","","","i just thought i would share.","","","","","",""],
["","kyungsoon","","you... just thought you would share.","","","","","",""],
["","oliver","","yes, that's what i said.","","","","","",""],
["","_none","","oliver hastily puts down his stack of books. you drop yours as well.","gifted_books","","","","",""],
["","oliver","","so, uhhhhh","","","","","",""],
["","","","enjoy! ^^","","numa_at_commons",['oliver_gave_books4', 'oliver_gave_books5'],"","",""],
["oliver_gave_books4","_none",['numa_neutral', 'kyungsoon_neutral'],"oliver hurries back into the library. ","","","","","",""],
["","numa","","...","","","","","",""],
["","","","that was nice of him!","","","","","",""],
["","kyungsoon","","yeah","","","","","",""],
["","","","weirdly nice","","","","","",""],
["","_none","","kyungsoon picks up one of the books and bites into it.",[['_delay_oliver_quest_complete', true], ['_delay__goto_flashback_oliver', true]],"","null","","",""],
["oliver_gave_books5","_none","kyungsoon_neutral","oliver hurries back into the library.","","","","","",""],
["","you","","...","","","","","",""],
["","","","well, that was nice of him!","","","","","",""],
["","kyungsoon","","yeah","","","","","",""],
["","","","weirdly nice","","","","","",""],
["","_none","","kyungsoon picks up one of the books and bites into it.",[['_delay_oliver_quest_complete', true], ['_delay__goto_flashback_oliver', true]],"","null","","",""],
["oliver_end_pride_flashback","_none","_none","_pass","",['numa_at_commons', 'ks_at_commons'],['oliver_end_pride_flashback1', 'oliver_end_pride_flashback2', 'oliver_end_pride_flashback3'],"","",""],
["oliver_end_pride_flashback1","numa","","{player}!","","","","","",""],
["","","","...","","","","","",""],
["","","","{player}!! WAKE UP!!!","","","","","",""],
["","you",['numa_neutral', 'kyungsoon_neutral'],"...",[['flashback_goto_commons', true], ['_hide_kyungsoon_idle&numa_at_commons', true]],"","","","",""],
["","","","huh?","","","","","",""],
["","numa","","you're awake!","","","","","",""],
["","","","oh, thank goodness","","","","","",""],
["","","","do you feel okay?","","","","","",""],
["","","","how many fingers am i holding up?","","","","","",""],
["","you","","um... two","","","","","",""],
["","numa","","what year is it?","","","","","",""],
["","you","","uhhh... i don't know?","","","","","",""],
["","numa","","...","","","","","",""],
["","","","yeah...","","","","","",""],
["","","","me neither...","","","","","",""],
["","kyungsoon","","i think {they}{'re/'s} fine","","","","","",""],
["","you","","yeah, i feel alright","","","","","",""],
["","","","just a little dizzy","","","","","",""],
["","numa","","okay, but please be careful!","","","","","",""],
["","you","","i'll try","","","null","","",""],
["oliver_end_pride_flashback2","kyungsoon","","{player}?","","","","","",""],
["","","","...","","","","","",""],
["","","","dude... get up","","","","","",""],
["","you","kyungsoon_neutral","...",[['flashback_goto_commons', true], ['_hide_kyungsoon_idle', true]],"","","","",""],
["","","","huh?","","","","","",""],
["","kyungsoon","","i think you just blacked out","","","","","",""],
["","you","","oh","","","","","",""],
["","","","damn","","","","","",""],
["","kyungsoon","","are you ok?","","","","","",""],
["","you","","yeah","","","","","",""],
["","kyungsoon","","cool","","","null","","",""],
["oliver_end_pride_flashback3","you","","...","flashback_goto_commons","","","","",""],
["","_none","","you pick yourself up from the ground.","","","null","","",""],
["oliver_gave_books_alt","_none","oliver_neutral","you walk to the commons together.","oliver_goto_commons","","","","",""],
["","oliver","","kyungsoon?","","","","","",""],
["","","","huh, she's usually here.","","","","","",""],
["","you","","i think she went somewhere with numa","","","","","",""],
["","","","what did you want her for?","","","","","",""],
["","oliver","","well, i was going to give her these books!","","","","","",""],
["","you","","really??","","","","","",""],
["","","","what's the catch?","","","","","",""],
["","oliver","","oh, no catch!","","","","","",""],
["","","","i just thought i would share.","","","","","",""],
["","_none","","oliver puts down his stack of books. you drop yours as well.","gifted_books","","","","",""],
["","oliver","","here, i'll just leave a note.","","","","","",""],
["","","","for... kyungsoon. i've made... copies of... all of these books. enjoy! signed... oliver... smiley face.","","","","","",""],
["","","","ok, all done!","","","","","",""],
["","","","thanks again for your help, {player}.","","","","","",""],
["","you","","don't mention it!","","","","","",""],
["","oliver","","now if you'll need me, i'll be cataloging.","","","","","",""],
["","_none","_none","oliver returns to the library.",[['_delay_oliver_quest_complete', true], ['_delay__goto_flashback_oliver', true]],"","null","","",""],
["oliver_default_f","oliver","oliver_neutral","hey, {player}!","","","","","",""],
["","","","","","","",['true', '_inv_natalies_books', 'not oliver_bad_end', 'true', 'true'],['what\'s up?', "(return natalie's books)", '(ask about...)', 'what do you think of the others?', 'how\'s cataloging?'],['oliver_wasup', 'oliver_natalies_books', 'oliver_life', 'oliver_others', 'oliver_post_catalog']],
["oliver_life","","","","","","","",['family', 'school', 'interests'],['oliver_family', 'oliver_school', 'oliver_interests']],
["oliver_family","you","","so, what was your family like?","","","","","",""],
["","oliver","","oh, there's not much to say.","","","","","",""],
["","","","you've probably learned more about my family during my, um, [i]episode[/i], than anyone else in purrgatory has.","","","","","",""],
["","you","","ah, i see","","","","","",""],
["","","","you said you had a brother?","","","","","",""],
["","oliver","","yes, indeed. andrew.","","","","","",""],
["","","","he was always a handful for our mother. ","","","","","",""],
["","","","you know, he pulled the fire alarm during a test in 6th grade!","","","","","",""],
["","you","","that must have been [i]alarming[/i] for the teachers!","","","","","",""],
["","oliver","","heh, yes.","","","","","",""],
["","","","the tests got drenched, so they had to push it back to the next week.","","","","","",""],
["","","","the other kids thought he was a hero.","","","","","",""],
["","you","","nice","","","","","",""],
["","","","were you a troublemaker too?","","","","","",""],
["","oliver","","me? oh, no.","","","","","",""],
["","","","i was a model student. spent most of my time reading.","","","","","",""],
["","","","but, uh, you probably gathered that already.","","","","","",""],
["","you","","heh, yeah, sort of.","","","","","",""],
["","oliver","","we parted ways when i went to college and he found a living... um...","","","","","",""],
["","","","well","","","","","",""],
["","","","i'm not entire sure, but it may have involved","","","","","",""],
["","","","illegal... substances?","","","","","",""],
["","you","","you mean drugs?","","","","","",""],
["","oliver","","well, yes, to put it bluntly.","","","","","",""],
["","","","but i don't want to give you the wrong impression!","","","","","",""],
["","","","andrew was a good soul. he always looked out for me growing up.","","","","","",""],
["","","","all of the kids in school knew not to mess with me because they didn't want to make andrew angry.","","","","","",""],
["","","","i... just wish i had repaid him somehow before i died.","","","","","",""],
["","you","","aw...","","","null","","",""],
["oliver_school","you","","so, what was school like?","","","","","",""],
["","oliver","","oh, it was fine.","","","","","",""],
["","","","i was in a doctorate program at the university of pennsylvania when i died.","","","","","",""],
["","","","in retrospect, i wish i had done something else.","","","","","",""],
["","","","sort of a dismal way to go, attending school your entire life...","","","","","",""],
["","you","","i guess so","","","","","",""],
["","","","what else would you have done?","","","","","",""],
["","oliver","","i don't know.","","","","","",""],
["","","","maybe go to japan!","","","","","",""],
["","","","i always wanted to visit.","","","","","",""],
["","you","","ooh for sure","","","","","",""],
["","oliver","","is there any country you would have liked to visit?","","","","","",""],
["","you","","oh, maybe...","","","","","",""],
["","","","","","","","",['sweden', 'ecuador', 'laos'],['oliver_sweden', 'oliver_ecuador', 'oliver_laos']],
["oliver_sweden","you","","sweden?","","","","","",""],
["","oliver","","oh, i heard they have a great prison system!","","","","","",""],
["","","","um, not that i think you would have been arrested in sweden.","","","","","",""],
["","","","just a passing thought.","","","","","",""],
["","you","","lol","","","null","","",""],
["oliver_ecuador","you","","ecuador?","","","","","",""],
["","oliver","","oh, i heard they have big tortoises!","","","","","",""],
["","you","","they sure do!","","","null","","",""],
["oliver_laos","you","","laos?","","","","","",""],
["","oliver","","oh, i heard that they...","","","","","",""],
["","","","that they...","","","","","",""],
["","","","actually, i don't think i've ever heard anything about laos.","","","","","",""],
["","you","","i think it's a nice place!","","","null","","",""],
["oliver_interests","you","","so, what were your interests, when you were alive?","","","","","",""],
["","oliver","","ah, nothing terribly exotic.","","","","","",""],
["","","","i liked math... of course.","","","","","",""],
["","","","languages. coffee.","","","","","",""],
["","","","and, um, anime.","","","","","",""],
["","","","","","","","",['i love anime!', 'oh cool'],['oliver_anime1', 'oliver_anime2']],
["oliver_anime1","you","","i love anime!","","","","","",""],
["","oliver","","oh, i'm glad you agree!","","","","","",""],
["","","","as an undergraduate, the one leisurely activity i always found time for was the japanese animation society.","","","","","",""],
["","you","","wait","","","","","",""],
["","","","YOUR SCHOOL HAD AN ANIME CLUB??","","","","","",""],
["","oliver","","yes, we did!","","","","","",""],
["","","","it was quite active, too. one year we even put on a \"maid cafe.\"","","","","","",""],
["","you","","that's so cool!","","","","","",""],
["","","","did you volunteer as a maid?","","","","","",""],
["","oliver","","well","","","","","",""],
["","","","um","","","","","",""],
["","","","as a \"butler,\" yes, but--","","","","","",""],
["","you","","omg","","","","","",""],
["","oliver","","i -- i was under a lot of pressure from my friends!","","","","","",""],
["","you","","i bet you were the most popular butler (;","","","","","",""],
["","oliver","","well, i wouldn't say--","","","","","",""],
["","","","i mean, it was certainly a good--","","","","","",""],
["","","","that is to say, it was a successful--","","","","","",""],
["","","","sflgjdfk never mind!","","","","","",""],
["","you","","hehe, okay, okay","","","null","","",""],
["oliver_anime2","you","","oh, cool","","","","","",""],
["","oliver","","i can't believe i died before the first season finale of one-punch man...","","","","","",""],
["","you","","aw ):","","","","","",""],
["","oliver","","yes, it's one of my greatest regrets.","","","null","","",""],
["oliver_natalies_books","you","","hey, natalie asked me to return these books to you","returned_natalies_books","","","","",""],
["","oliver","","huh?","","","","","",""],
["","","","oh!","","","","","",""],
["","","","well, thank you very much! i'll check these in right away.",[['_inv_natalies_books', false], ['_quest_return_books', false]],"","","","",""],
["","you","","you're welcome!","","","","","",""],
["","oliver","","goodness, i almost forgot about these","","","","","",""],
["","","","did... did she happen to say whether she enjoyed them?","","","","","",""],
["","you","","uhhhh","","","","","",""],
["","","","","","","","",['i think she liked them', 'she didn\'t say', 'she was using them to hold up a table'],['oliver_natalies_books1', 'oliver_natalies_books2', 'oliver_natalies_books3']],
["oliver_natalies_books1","you","","i think she liked them!","","","","","",""],
["","oliver","","oh, good, good.","","","","","",""],
["","","","she really must have been taking her time with them, huh?","","","","","",""],
["","you","","haha, yeah.","","","oliver_natalies_books4","","",""],
["oliver_natalie_books2","you","","ah, she didn't really say","","","","","",""],
["","oliver","","oh. well, that's too bad.","","","oliver_natalies_books4","","",""],
["oliver_natalie_books3","you","","umm... actually, she was using them to hold up a table","","","","","",""],
["","oliver","","oh. well.","","","","","",""],
["","","","i guess that's one use for a book, haha.","","","oliver_natalies_books4","","",""],
["oliver_natalies_books4","oliver","","you know, there's a surprising amount of nuance if you read between the lines...","","","","","",""],
["","_none","","oliver riffles through one of the books and a piece of paper falls out.","","","","","",""],
["","oliver","","whoops!","","","","","",""],
["","","","is this yours?","","","","","",""],
["","you","","uh, no, it must be natalie's","","","","","",""],
["","oliver","","ah, i'll trust you to hold on to it, then.","_inv_business_card","","","","",""],
["","","","probably just a bookmark or something.","","","","","",""],
["","","","anyway, i'd better get these back on the shelf for future patrons","","","","","",""],
["","","","until next time!","","","","","",""],
["","you","","cya!","","","null","","",""],
["oliver_post_catalog","you","","so, how's cataloging?","","","","","",""],
["","oliver","","oh, you know how it goes.","","","","","",""],
["","you","","true, true.","","","","","",""],
["","","","...","","","","","",""],
["","","","actually, not really","","","","","",""],
["","","","what exactly are you doing with those books again...?","","","","","",""],
["","oliver","","oh, well, it's quite simple really!","","","","","",""],
["","","","i skim through the book, put an id sticker on it, and then write the id and title down on the catalog.","","","","","",""],
["","","","then i replace the book numerically so i can find it again later.","","","","","",""],
["","you","","huh","","","","","",""],
["","oliver","","if i'm feeling especially studious, i'll even write notes on the content!","","","","","",""],
["","you","","wow","","","","","",""],
["","","","and you've done this for... how many books?","","","","","",""],
["","_none","","oliver glances at his catalog.","","","","","",""],
["","oliver","","as of right now now, 15,182.","","","","","",""],
["","you","","...i'm starting to see why finding a typo was so exciting for you","","","","","",""],
["","oliver","","...","","","","","",""],
["","","","yeah...","","","null","","",""],
["oliver_ladder","_none","oliver_neutral","oliver looks up as you walk past.","","","","","",""],
["","oliver","","{player}?","","","","","",""],
["","you","","oh, hey oliver!","","","","","",""],
["","","","what's up?","","","","","",""],
["","oliver","","uh, not much!","","","","","",""],
["","","","i was just wondering...","","","","","",""],
["","","","you know...","","","","","",""],
["","you","","i know what?","","","","","",""],
["","_none","","he gestures at you.","","","","","",""],
["","oliver","","why are you carrying a ladder?","","","","","",""],
["","you","","oh!","","","","","",""],
["","","","uh, just thought it might come in handy","","","","","",""],
["","","","sorry","","","","","",""],
["","oliver","","ah, i see","","","","","",""],
["","you","","do you want me to put it back?","","","","","",""],
["","oliver","","no, no, i... suppose you can have it if you want!","","","","","",""],
["","you","","alright, thanks!","","","null","","",""]
]