extends Node

var raw_blocks = [
["talk_to_oliver_about_numa","oliver","oliver_neutral","what was that all about?","","","","",""],
["","","","","","","","",[['you scared her off', 'oliver_scared'], ['who knows', 'oliver_who_knows']]],
["oliver_scared","you","","i think you scared her off","","","","",""],
["","oliver","","really?","","","","",""],
["","","","what did i say??","","","","",""],
["","you","","i dunno man","","","null","",""],
["oliver_who_knows","you","","who knows","","","","",""],
["","oliver","","hm... mysterious...","","","null","",""],
["oliver_default","_none","_none","_pass","","house_cat_pushed_glass",['oliver_default_d', 'oliver_default1'],"",""],
["oliver_default1","_none","_none","_pass","","tori_visited_oliver",['oliver_default_c', 'oliver_default2'],"",""],
["oliver_default2","_none","_none","_pass","","oliver_in_study",['oliver_default_b', 'oliver_default_a'],"",""],
["oliver_default_a","oliver","oliver_neutral","hi again, {player}!","","","","",""],
["","","","","","","",['true', 'not followed_up_on_drama', 'true', 'true'],[['what\'s up?', 'oliver_wasup'], ['what was kyungsoon talking about?', 'oliver_follow_up_on_drama'], ['what do you think of the others?', 'oliver_others'], ['how\'s your work going?', 'oliver_research']]],
["oliver_wasup","you","","what's up?","","",['_rand', 'oliver_wasup1', 'oliver_wasup2', 'oliver_wasup3', 'oliver_wasup4', 'oliver_wasup5', 'oliver_wasup6', 'oliver_wasup7', 'oliver_wasup8', 'oliver_wasup9', 'oliver_wasup10', 'oliver_wasup11', 'oliver_wasup12', 'oliver_wasup13', 'oliver_wasup14', 'oliver_wasup15', 'oliver_wasup16', 'oliver_wasup17', 'oliver_wasup18', 'oliver_wasup19'],"",""],
["oliver_wasup1","oliver","","i'm thinking about sorting these alphabetically...","","","null","",""],
["oliver_wasup2","oliver","","i dusted some books today.","","","","",""],
["","you","","cool!","","","null","",""],
["oliver_wasup3","oliver","","i think there's a mouse living in the library...","","","","",""],
["","you","","you [i]think[/i]?","","","","",""],
["","oliver","","i mean a little one!","","","","",""],
["","","","i keep hearing squeaking in the night.","","","","",""],
["","","","ugh. maybe i'm just hearing things.","","","null","",""],
["oliver_wasup4","oliver","","cataloging.","","","","",""],
["","you","","so the ushe","","","","",""],
["","oliver","","hah, yes, the \"ushe.\"","","","null","",""],
["oliver_wasup5","oliver","","i don't know.","","","","",""],
["","you","","who does?","","","null","",""],
["oliver_wasup6","oliver","","thinking about thin mints.","","","","",""],
["","you","","what about them?","","","","",""],
["","oliver","","i wish i'd eaten more of them while i had the chance...","","","null","",""],
["oliver_wasup7","oliver","","books, primarily.","","","","",""],
["","you","","read anything interesting lately?","","","","",""],
["","oliver","","uh... not really.","","","","",""],
["","you","","that's fair","","","null","",""],
["oliver_wasup8","oliver","","i was wondering...","","","","",""],
["","","","did you ever read animorphs as a kid?","","","","",""],
["","","","","","","","",[['yes', 'oliver_wasup8a'], ['no', 'oliver_wasup8b']]],
["oliver_wasup8a","you","","yep","","","oliver_wasup8c","",""],
["oliver_wasup8b","you","","nope","","","","",""],
["oliver_wasup8c","oliver","","i can't stop thinking about the time they morphed into flies and one of them got swatted.","","","","",""],
["","","","isn't that messed up?","","","null","",""],
["oliver_wasup9","oliver","","thinking about moby dick.","","","","",""],
["","you","","what about it?","","","","",""],
["","oliver","","he shot a single harpoon at a giant whale.","","","","",""],
["","","","what did he think was going to happen?","","","null","",""],
["oliver_wasup10","oliver","","a[i]choo![/i]","","","","",""],
["","","","dusting.","","","","",""],
["","you","","you okay?","","","","",""],
["","oliver","","i'm okay, just - [i]achoo![/i] - breathed a lot of dust.","","","","",""],
["","you","","bless you","","","","",""],
["","oliver","","thanks","","","null","",""],
["oliver_wasup11","oliver","","tired.","","","","",""],
["","you","","me too","","","null","",""],
["oliver_wasup12","oliver","","did i ever tell you about my dust bunny collection?","","","","",""],
["","you","","your... dust bunny collection?","","","","",""],
["","oliver","","every time i find a big dust bunny i put it in a jar.","","","","",""],
["","","","i just filled my third one!","","","","",""],
["","","","","","","","",[['that\'s pretty cool', 'oliver_wasup12a'], ['that\'s the most boring thing you could collect', 'oliver_wasup12b']]],
["oliver_wasup12a","you","","that's pretty cool","","","","",""],
["","oliver","","thanks!","","","null","",""],
["oliver_wasup12b","you","","no offense, but that's the most boring thing you could possibly collect.","","","","",""],
["","oliver","","...","","","","",""],
["","","","i know ):","","","null","",""],
["oliver_wasup13","oliver","","thinking about harry potter.","","","","",""],
["","you","","what about it?","","","","",""],
["","oliver","","they could have avoided a lot of problems if they just had cell phones.","","","null","",""],
["oliver_wasup14","oliver","","...","","","","",""],
["","you","","oliver?","","","","",""],
["","oliver","","huh? what?","","","","",""],
["","you","","i said \"what's up?\"","","","","",""],
["","oliver","","oh. sorry, haha. kind of tired.","","","","",""],
["","you","","maybe you should take a break...","","","","",""],
["","oliver","","maybe. in a bit.","","","null","",""],
["oliver_wasup15","oliver","","i stubbed my toe earlier ):<","","","","",""],
["","you","","ouch","","","","",""],
["","oliver","","they removed our need for sustenance and sleep but they couldn't remove the pain from stubbed toes.","","","","",""],
["","you","","of course not. it's purrgatory.","","","","",""],
["","oliver","","of course.","","","null","",""],
["oliver_wasup16","oliver","","just thinking about dante's inferno.","","","","",""],
["","you","","oh yeah?","","","","",""],
["","oliver","","he got a few things wrong, heh.","","","","",""],
["","you","","no kidding","","","null","",""],
["oliver_wasup17","oliver","","thinking about the grapes of wrath.","","","","",""],
["","you","","why?","","","","",""],
["","oliver","","i remember when i read it in school, i didn't understand why it was called \"the grapes of wrath.\"","","","","",""],
["","","","i never did find out.","","","","",""],
["","you","","guess reading it was [i]fruitless[/i]","","","","",""],
["","oliver","","haha, i guess so.","","","null","",""],
["oliver_wasup18","oliver","","thinking about that chess competition i won in 6th grade.","","","","",""],
["","you","","oh, nice!","","","","",""],
["","oliver","","i was obscenely proud of it at the time, but it seems kind of silly now.","","","","",""],
["","","","beating 6th graders at chess isn't that much of an accomplishment.","","","","",""],
["","you","","that's still pretty cool","","","","",""],
["","oliver","","eh, i suppose so.","","","null","",""],
["oliver_wasup19","oliver","","not much.","","","","",""],
["","you","","cool","","","null","",""],
["oliver_follow_up_on_drama","you","","what was kyungsoon talking about, during the argument? ","followed_up_on_drama","","","",""],
["","","","you know, \"cardinal sin\" and all that?","","","","",""],
["","oliver","","oh. yes, that.","","","","",""],
["","you","","it's okay if you don't want to talk about it","","","","",""],
["","oliver","","no, no, it's all right.","","","","",""],
["","","","kyungsoon just thinks i'm too \"nice\" to be in purrgatory.","","","","",""],
["","","","she says i must have murdered someone to end up down here, or something like that.","","","","",""],
["","you","","...did you?","","","","",""],
["","oliver","","no, of course not!","","","","",""],
["","","","","","","","",[['if you did, i won\'t judge', 'oliver_judge'], ['who was it?', 'oliver_who_was'], ['i can\'t see you doing that', 'oliver_cant_see']]],
["oliver_judge","you","","if you did murder someone, i won't judge","","","","",""],
["","","","just saying","","","","",""],
["","oliver","","that's very kind of you, but the point is moot, because i [i]didn't.[/i]","","","","",""],
["","you","","alrighty then","","","null","",""],
["oliver_who_was","you","","who was it?","","","","",""],
["","","","ooh, was it your wife?","","","","",""],
["","","","or husband?","","","","",""],
["","oliver","","what? no! i wasn't even married!","","","","",""],
["","you","","yeah, you wouldn't have been, after you [i]murdered[/i] them.","","","","",""],
["","oliver","","you're no better than kyungsoon!","","","","",""],
["","","","i didn't murder anyone, and that's all I have to say on the matter ):<","","","","",""],
["","you","","if you say so~","","","null","",""],
["oliver_cant_see","you","","yeah, i can't see you doing that tbh","","","","",""],
["","oliver","","well [i]thank[/i] you.","","","","",""],
["","","","at least someone in purrgatory has some sense.","","","null","",""],
["oliver_others","_none_","_none","_pass","","oliver_asked_about_others",['oliver_others1a', 'oliver_others1'],"",""],
["oliver_others1","you",['oliver_neutral'],"what do you think of the others?","oliver_asked_about_others","","","",""],
["","","","like, kyungsoon and everyone else who's down here.","","","","",""],
["","oliver","","well, all things considered, we could have been stuck with much worse company.","","","","",""],
["","","","is there someone in particular you had in mind?","","","","",""],
["oliver_others1a","you","","what do you think about...","","","","",""],
["oliver_others2","","","","","","",['true', 'met_numa', 'met_elijah', 'met_sean'],[['kyungsoon', 'oliver_about_ks'], ['numa', 'oliver_about_numa'], ['elijah', 'oliver_about_elijah'], ['(someone else...)', 'oliver_others3']]],
["oliver_others3","","","","","","",['met_sean', 'met_tori', 'met_natalie', 'true'],[['sean', 'oliver_about_sean'], ['tori', 'oliver_about_tori'], ['natalie', 'oliver_about_natalie'], ['(someone else...)', 'oliver_others2']]],
["oliver_about_ks","you","","kyungsoon?","","","","",""],
["","oliver","","well, kyungsoon's very...","","","","",""],
["","","","um...","","","","",""],
["","","","candid.","","","","",""],
["","you","","candid, huh?","","","","",""],
["","oliver","","and... morose.","","","","",""],
["","you","","morose is a good thing?","","","","",""],
["","oliver","","well, uh, no, not typically.","","","","",""],
["","","","i just mean that she's… languorous?","","","","",""],
["","you","","i don’t know that one","","","","",""],
["","oliver","","phlegmatic...?","","","","",""],
["","you","","you have GOT to be making these up.","","","","",""],
["","oliver","","oh, never mind. you get what i'm trying to say!","","","","",""],
["","","","if only i had my thesaurus with me...","","","null","",""],
["oliver_about_elijah","you","","elijah?","","","","",""],
["","oliver","","oh, elijah is a great person!","","","","",""],
["","","","he doesn't look like it, but he's actually very sensitive.","","","","",""],
["","you","","why do you think he's down here?","","","","",""],
["","oliver","","well, i can't say for sure, but...","","","","",""],
["","","","i heard he was in the army.","","","","",""],
["","you","","do you think he died while in service?","","","","",""],
["","oliver","","could be, could be.","","","","",""],
["","","","he's never said, and thought it would be rude to ask.","","","","",""],
["","you","","ah, okay","","","null","",""],
["oliver_about_sean","you","","sean?","","","","",""],
["","oliver","","oh, he's certainly very... audacious.","","","","",""],
["","","","he has a bit of a rough exterior, but i think he's a good person overall.","","","","",""],
["","","","he's actually the most recent arrival, besides you!","","","","",""],
["","you","","really? how long has he been here?","","","","",""],
["","oliver","","ah, hard to tell. i think only a year or so...?","","","","",""],
["","","","numa would know; i think she keeps track of this kind of stuff.","","","","",""],
["","you","","how about you? how long have you been here?","","","","",""],
["","oliver","","i truly can't say.","","","","",""],
["","","","to be honest, i only remember sean's arrival because he made quite an impression on me.","","","","",""],
["","you","","oh yeah?","","","","",""],
["","oliver","","yes, he, um","","","","",""],
["","","","he made some, let's say, very forward advances.","","","","",""],
["","you","","LOL","","","","",""],
["","","","I guess you don't swing that way, huh?","","","","",""],
["","oliver","","no no, it's not that.","","","","",""],
["","","","i, uh, \"swing\" both ways, so to speak.","","","","",""],
["","you","","just not into snakes?","","","","",""],
["","oliver","","no no no, you're putting words in my mouth!","","","","",""],
["","","","i'll admit that he's, um, quite handsome","","","","",""],
["","","","it's just that i wasn't,","","","","",""],
["","","","i mean, i'm not looking for someone, at this point in my life, or death, that is, but","","","","",""],
["","","","maybe if the circumstances were different, then...","","","","",""],
["","","","sdklfjg never mind that","","","","",""],
["","","","i'm just focusing on my research right now, is all.","","","","",""],
["","you","","heh, alright","","","null","",""],
["oliver_about_numa","you","","numa?","","","","",""],
["","oliver","","oh, she's very sweet!","","","","",""],
["","","","a bit of a recluse, however. hardly talks to anyone.","","numa_quest_complete",['oliver_about_numa1', 'oliver_about_numa2'],"",""],
["oliver_about_numa1","","","well, except kyungsoon, i guess.","","","","",""],
["","","","still not entirely sure how [i]that[/i] happened.","","","","",""],
["oliver_about_numa2","you","","didn't you try to talk to her?","","","","",""],
["","oliver","","yes, a number of times, in fact.","","","","",""],
["","","","i knew she was a number afficionado, so i thought i would run some of my results past her.","","","","",""],
["","you","","and?","","","","",""],
["","oliver","","well, she seemed like she wanted to help, but she ended up going quiet.","","","","",""],
["","","","if you ask me, she's more interested in flowers than she is other people.","","","","",""],
["","you","","i see","","","","",""],
["","oliver","","oh! and i should warn you.","","","","",""],
["","","","do [i]not[/i] touch her flowers, or you will regret it very quickly.","","","","",""],
["","you","","oh yeah, i found that out first hand","","","","",""],
["","oliver","","she can be a bit paranoid.","","","null","",""],
["oliver_research","you","","how's your work going?","","","","",""],
["","oliver","","it's going well, thank you for asking!","","","","",""],
["","","","","","","","",[['is this what you did in real life?', 'oliver_real_life'], ['can i help?', 'oliver_can_help'], ['(leave)', 'oliver_leave']]],
["oliver_leave","you","","i gotta go, catch you later","","","","",""],
["","oliver","","until next time!","","","null","",""],
["oliver_real_life","you","","is this what you did in real life? work in a library?","","","","",""],
["","oliver","","oh, not quite. i did have an affinity for books, but that never quite translated into work at a library.","","","","",""],
["","","","no, i was a doctorate student when i died. ","","","","",""],
["","","","worked part-time as a barista.","","","","",""],
["","you","","ooh, cool.","","","","",""],
["","","","what was your thesis about?","","","","",""],
["","oliver","","oh...","","","","",""],
["","","","um...","","","","",""],
["","","","nothing interesting, i'm afraid.","","","","",""],
["","you","","try me.","","","","",""],
["","oliver","","well, it was mathematics. number theory, specifically.","","","","",""],
["","","","or diophantine approximation, even more specifically.","","","","",""],
["","","","which is the use of rational numbers to approximate real numbers, in case you didn't know.","","","","",""],
["","","","it's closely linked to transcendental numbers, and in fact, was used to prove the transcendentality of pi in 1882 by--","","","","",""],
["","_none","","he stops short.","","","","",""],
["","oliver","","ahem, i mean","","","","",""],
["","","","there's really not that much to say about it, haha","","","","",""],
["","","","","","","","",[['(push for more)', 'oliver_ask_for_more'], ['(be grateful you dodged a math lecture)', 'oliver_dodged']]],
["oliver_ask_for_more","you","","aw, it sounds interesting","","","","",""],
["","","","tell me more!","","","","",""],
["","_none","","oliver coughs and looks at his feet.","","","","",""],
["","oliver","","really, i insist, there's nothing more to be said.","","","","",""],
["","","","i didn't even find any results.","","","","",""],
["","you","","come ooon, i wanna know about transcendental numbers!","","","oliver_dodge2","",""],
["oliver_dodged","you","","well, if you say so.","","","","",""],
["oliver_dodge2","oliver","","actually, if you'll excuse me, i just remembered i have some... very important work to attend to.","","","","",""],
["","you","","oh, okay","","","","",""],
["","","","oliver shuffles away.","","","","",""],
["","_none","_none","must be a touchy subject.","oliver_why","","null","",""],
["oliver_can_help","you","","anything i can do to help?","","","","",""],
["","oliver","","well, as a matter of fact, yes!","","","","",""],
["","","","i recently discovered this book hidden in a corner of a shelf. take a look at this.","","","","",""],
["","_none","","he flips through a book and shows you one of the pages.","","","","",""],
["","you","","one of the meows is circled in pen...?","","","","",""],
["","oliver","","yes! exactly!","","","","",""],
["","","","someone has taken notes in this book!","","","","",""],
["","","","what could it mean?!","","","","",""],
["","","","","","","","",[['probably nothing', 'oliver_nothing'], ['maybe kyungsoon drew it', 'oliver_printing_error'], ['it\'s the answer you\'ve been looking for', 'oliver_key_to_the_code']]],
["oliver_nothing","you","","probably nothing","","","","",""],
["","","","i mean, it's just another \"meow\"","","","","",""],
["","oliver","","is it a meow, or is it a key to the code?","","","","",""],
["","","","is it nothing, or is it everything i've been hoping for?","","","","",""],
["","","","that's the question!","","","oliver_can_help2","",""],
["oliver_printing_error","you","","maybe kyungsoon drew it","","","","",""],
["","","","you should [i]page[/i] her and ask.","","","","",""],
["","oliver","","but why would kyungsoon be taking notes in these books?","","","","",""],
["","","","she's much more interested in [i]eating[/i] them than--","","","","",""],
["","","","oh, haha, i get it, \"page\" her.","","","","",""],
["","","","anyway, we mustn't rule out the possibility that this word was circled for a reason!","","","","",""],
["","","","this could be the key that i've been looking for all along!","","","oliver_can_help2","",""],
["oliver_key_to_the_code","you","","this could be the answer you've been looking for!","","","","",""],
["","oliver","","that's exactly what i'm hoping... but i'm almost afraid to say it.","","","","",""],
["oliver_can_help2","oliver","","no, no, i shouldn't get my hopes up.","","","","",""],
["","","","you see, i've measured it, weighed it, scrutinized every inch of the page...","","","","",""],
["","","","but for all intents and purposes, the \"meow\" is unremarkable.","","","","",""],
["","","","so, to go back to your offer of help, i was hoping a fresh pair of eyes would shed some light on the situation!","","","","",""],
["","you","","hm...","","","","",""],
["oliver_can_help3","","","","","","",['not suggested_crease', 'not suggested_smudge', 'not suggested_binding', 'not suggested_code'],[['this crease looks interesting', 'oliver_crease'], ['did you notice this smudge?', 'oliver_smudge'], ['have you tried looking inside the binding?', 'oliver_binding'], ['maybe it\'s a secret code', 'oliver_code']]],
["oliver_crease","you","","this crease in the corner looks interesting","suggested_crease","","","",""],
["","oliver","","ooh, sharp eye!","","","","",""],
["","","","it looks like the page is crumpled slightly here.","","","","",""],
["","","","clearly it means...","","","","",""],
["","you","","...","","","","",""],
["","oliver","","...","","","","",""],
["","you","","it means what?","","","","",""],
["","oliver","","it means that...","","","","",""],
["","","","...","","","","",""],
["","","","...someone was a little too forceful when turning the page?","","","","",""],
["","you","","yeah, that's probably it","","","oliver_can_help3","",""],
["oliver_smudge","you","","did you notice this smudge on the cover?","suggested_smudge","","","",""],
["","oliver","","*gasp*","","","","",""],
["","","","how did i miss that before??","","","","",""],
["","you","","is something written there?","","","","",""],
["","","","maybe a clue?","","","","",""],
["","oliver","","let's see...","","","","",""],
["","_none","","oliver pulls out a magnifying glass and squints through it.","","","","",""],
["","oliver","","it looks like it's…","","","","",""],
["","","","yes, it seems to be…","","","","",""],
["","","","a bit of dust.","","","","",""],
["","_none","","oliver wipes it clean with his thumb.","","","","",""],
["","you","","oh","","","oliver_can_help3","",""],
["oliver_binding","you","","have you tried looking inside the binding?","suggested_binding","","","",""],
["","","","there might be a message or something sewn into the spine.","","","","",""],
["","","","i think i saw that in a spy movie","","","","",""],
["","oliver","","brilliant!","","","","",""],
["","_none","","oliver holds the book to eye level and closely examines the spine","","","","",""],
["","oliver","","hmm... in fact... is it just me, or is there a slight lump in the cover?","","","","",""],
["","","","normally I would never do this, but I think we should take this book apart.","","","","",""],
["","","","who knows what could be hidden inside? a message? a computer chip?","","","","",""],
["","you","","the key to purrgatory?","","","","",""],
["","oliver","","maybe so!! ","","","","",""],
["","","","now, this shouldn't take more than a minute.","","","","",""],
["","_none","","oliver takes an exacto knife from a drawer nearby, then cuts down the seam of the spine repeatedly.","","","","",""],
["","oliver","","voila!","","","","",""],
["","you","","nice!!","","","","",""],
["","_none","","oliver holds up the separated stack of pages.","","","","",""],
["","oliver","","now to take a closer look...","","","","",""],
["","you","","...","","","","",""],
["","oliver","","...","","","","",""],
["","you","","anything?","","","","",""],
["","oliver","","hm...","","","","",""],
["","you","","there's nothing, isn't there?","","","","",""],
["","oliver","","well. i wouldn't say [i]nothing,[/i] but...","","","","",""],
["","","","...","","","","",""],
["","","","yeah, there's nothing. just a mangled book.","","","","",""],
["","you","","aw, sorry about that.","","","","",""],
["","oliver",""," [i]sigh[/i]","","","","",""],
["","","","it's… it's fine…","","","","",""],
["","_none","","he cradles the deconstructed book as if mourning it.","","","oliver_can_help3","",""],
["oliver_code","you","","maybe it's a secret code?","suggested_code","","","",""],
["","you","","like, maybe if you look at the first word on each of the other pages, it'll spell out a message or something?","","","","",""],
["","oliver","","well, remember the first word on each page is \"meow.\"","","","","",""],
["","you","","oh, right.","","","","",""],
["","oliver","","but that's not a bad idea...","","","","",""],
["","","","maybe the circled word doesn't hold a message itself, but acts as a marker that this book is exceptional.","","","","",""],
["","","","there are meows of varying lengths... maybe each one encodes a letter?","","","","",""],
["","","","or maybe the punctuation is of importance?","","","","",""],
["","you","","or you could count the number of meows on each page?","","","","",""],
["","oliver","","yes, of course!","","","","",""],
["","","","so many avenues of research!!","","suggested_binding",['oliver_code1', 'oliver_code2'],"",""],
["oliver_code1","_none","","oliver gently gathers the parts of the deconstructed book.","","","oliver_code3","",""],
["oliver_code2","_none","","oliver shuts the book.","","","","",""],
["oliver_code3","oliver","","i need to develop a course of action immediately. there's no time to waste!","","","","",""],
["","you","","isn't this a lot of hype for a circle in a book?","","","","",""],
["","oliver","","you have to understand…","","","","",""],
["","","","this is the only lead I have.","","","","",""],
["","","","when nothing makes sense, you have to cling to any semblance of meaning you can.","","","","",""],
["","","","","","","","",[['that makes sense', 'oliver_got_this'], ['i don\'t want you to get your hopes up', 'oliver_just_empty']]],
["oliver_got_this","you","","that makes sense.","","","","",""],
["","","","i believe in you! you've got this!!","","","","",""],
["","oliver","","thank you, thank you.","","","oliver_code4","",""],
["oliver_just_empty","you","","not to rain on your parade, but...","","","","",""],
["","","","i think someone just circled a word in the book because they were bored.","","","","",""],
["","","","i don't want you to get your hopes up, is all.","","","","",""],
["","oliver","","well…","","","","",""],
["","","","I will make sure to bear that possibility in mind.","","","","",""],
["oliver_code4","oliver","","now if you need me, i'll be in my study.","","","","",""],
["","_none","","oliver rushes away before you can respond or ask where his study is.","oliver_in_study","","null","",""],
["oliver_default_b","oliver","oliver_neutral","oh, hey, {player}.","","seen_study",['oliver_default_b2', 'oliver_default_b1'],"",""],
["oliver_default_b1","you","","so this is your study, huh?","seen_study","","","",""],
["","oliver","","yes, indeed!","","","","",""],
["","","","my little corner i've carved out of purrgatory.","","","","",""],
["","","","um, sorry it's so messy.","","","","",""],
["","you","","heh, it's alright.","","","","",""],
["oliver_default_b2","oliver","","i'm a little busy right now. is there something you want to talk about?","","","","",""],
["","","","","","","",['true', 'not followed_up_on_drama', 'true', 'true'],[['what\'s up?', 'oliver_wasup'], ['what was kyungsoon talking about?', 'oliver_follow_up_on_drama'], ['what do you think of the others?', 'oliver_others'], ['how\'s your work going?', 'oliver_research_b']]],
["oliver_research_b","you","","how's your work going?","","","","",""],
["","oliver","","quite well, quite well.","","","","",""],
["","","","just gathering some frequency data right now.","","","","",""],
["","","","i've been working through some of the ideas we brainstormed earlier -- no results yet, but i'm confident i'll find a lead soon.","","","","",""],
["","","","","","","",['true', 'not _inv_chess_letter', '_inv_chess_letter', 'true'],[['is this what you did in real life?', 'oliver_real_life'], ['can i help?', 'oliver_can_help_b1'], ['can i help?', 'oliver_can_help_b2'], ['(leave)', 'oliver_leave']]],
["oliver_can_help_b1","you","","can i help?","","","","",""],
["","oliver","","uhh, well","","","","",""],
["","","","i really appreciate the offer, but,","","","","",""],
["","","","i'm quite busy with gathering frequency data right now, so all i need is some time, if you understand.","","","","",""],
["","you","","are you sure? are there any errands you need done, or...?","","","","",""],
["","oliver","","i [i]suppose[/i] i need to deliver my next chess move to tori...","","","","",""],
["","you","","your next chess move?","","","","",""],
["","oliver","","yes, tori and i play chess by correspondence!","","","","",""],
["","you","","really?","","","","",""],
["","","","but you live in the same place","","","","",""],
["","","","you could just, like","","","","",""],
["","","","play the game in person","","","","",""],
["","_none","","oliver shrugs.","","","","",""],
["","oliver","","it's more fun this way. builds up the anticipation.","","","","",""],
["","","","anyway, her mailbox is in the train station, if you wouldn't mind delivering the letter.","","","","",""],
["","you","","sure, post master {player} is on the case!","","","","",""],
["","oliver","","haha, i appreciate it.","","","","",""],
["","_none","","oliver hands you an envelope.","_inv_chess_letter","","","",""],
["","oliver","","now i'd better get back to my research.","","","","",""],
["","you","","alright, catch ya later","","","null","",""],
["oliver_can_help_b2","you","","is there anything else i can do to help?","","","","",""],
["","oliver","","no, no, delivering the letter will be fine, thank you.","","","","",""],
["","","","you know how to find the train station, right?","","","","",""],
["","","","it's just past the meowseum and the warehouse.","","","","",""],
["","you","","alrighty, thanks","","","null","",""],
["oliver_default_c","you","oliver_neutral","oliver?","","","","",""],
["","oliver","","huh?","","","","",""],
["","","","oh. hello. sorry.","","","","",""],
["","","","can i help you with something?","","","","",""],
["","","","","","","","",[['what\'s up?', 'oliver_wasup_c'], ['what do you think of the others?', 'oliver_others_c'], ['how\'s your work going?', 'oliver_research_c']]],
["oliver_wasup_c","you","","what's up?","","","","",""],
["","oliver","","still researching.","","","","",""],
["","you","","cool","","","","",""],
["","oliver","","just a couple more shots in the dark... one of them has to hit eventually... right?","","","","",""],
["","you","","sure","","","null","",""],
["oliver_others_c","you","","what do you think of the others?","","","","",""],
["","oliver","","they're fine, i suppose","","","","",""],
["","","","sorry, i don't really have time to chat right now.","","","","",""],
["","you","","ah, that's okay","","","null","",""],
["oliver_research_c","you","","how's your work going?","","","","",""],
["","oliver","","still looking for a foothold…","","","","",""],
["","","","vignere cipher was a dead end… maybe an affine cipher?","","","","",""],
["","","","","","","",['true', 'not oliver_asked_for_soda', 'oliver_asked_for_soda', 'true'],[['is this what you did in real life?', 'oliver_real_life_c'], ['can i help?', 'oliver_can_help_c1'], ['can i help?', 'oliver_can_help_c2'], ['(leave)', 'oliver_leave_c']]],
["oliver_real_life_c","you","","is this what you did in real life?","","","","",""],
["","oliver","","well...","","","","",""],
["","","","actually, yes, more or less.","","","","",""],
["","","","i'm sorry, i really can't spare the time to talk right now.","","","","",""],
["","you","","that's alright.","","","null","",""],
["oliver_leave_c","you","","i gotta go, catch you later","","","","",""],
["","oliver","","until next time.","","","null","",""],
["oliver_can_help_c1","you","","is there anything i can do to help?","","","","",""],
["","oliver","","no thank you.","","","","",""],
["","you","","are you sure? don't take this the long way, but, you look exhausted.","","","","",""],
["","oliver","","really, i'm fine.","","","","",""],
["","you","","i could help you clean, keep you company--","","","","",""],
["","oliver","","{player}!","","","","",""],
["","","","i'm serious, i don't need any help. some space, please.","","","","",""],
["","","","","","","",[['(push it)', 'oliver_push_it'], ['(back off)', 'oliver_back_off']],""],
["oliver_push_it","you","","well i think you [i]do[/i] need help!","","","","",""],
["","","","staying in here cooped up isn't healthy for you. you should at least drink something.","","","","",""],
["","","","...please?","","","","",""],
["","oliver","","...","","","","",""],
["","","","well...","","","","",""],
["","","","i suppose i am a bit parched.","","","","",""],
["","","","some orange soda would be nice.","oliver_asked_for_soda","","","",""],
["","you","","alright, you got it. one orange soda coming right up!","","","","",""],
["","oliver","","thank you.","","","","",""],
["","_none","","oliver goes back to scribbling without another word.","","","null","",""],
["oliver_back_off","you","","geez, okay. i'm sorry","","","","",""],
["","oliver","","it's fine. ","","","","",""],
["","","","i'm... sorry for snapping at you.","","","","",""],
["","","","you know i'm not usually like this.","","","","",""],
["","you","","yeah, i know.","","","null","",""],
["oliver_can_help_c2","you","","you said you wanted orange soda, right?","","","","",""],
["","oliver","","yes, that's right.","","","","",""],
["","you","","anything else i can do?","","","","",""],
["","oliver","","no thank you.","","","","",""],
["","you","","alright","","","null","",""],
["oliver_default_d","you","","oliver?","","","","",""],
["","","","...","","","","",""],
["","","","oliver, i couldn't find a cup for your soda.","","","","",""],
["","","","...","","","","",""],
["","_none","","he's fast asleep.","","","","",""],
["","","","","","","","",[['wake him up', 'oliver_wake_up'], ['put his blanket over him', 'oliver_blanket'], ['leave him alone', 'oliver_leave_alone']]],
["oliver_leave_alone","_none","","maybe you can check back later.","","","null","",""],
["oliver_blanket","_none","","you grab the blanket from oliver's bed and drape it over his shoulders.","","","","",""],
["","oliver","","pfdk.. . andrew, stop it...","","","","",""],
["","_none","","you freeze.","","","","",""],
["","oliver","","jusfive minutes....","","","","",""],
["","_none","","you slowly back away from oliver.","","","","",""],
["","","","before you can get out the door, you knock over a tin can full of pens.","","","","",""],
["","oliver","oliver_neutral","S[i]Nck.[/i] guck. huh? ","","","","",""],
["","you","","sorry! i didn't mean to wake you up!","","","oliver_wake_up2","",""],
["oliver_wake_up","you","","oliver.","","","","",""],
["","","","oliver!!","","","","",""],
["","oliver","oliver_neutral","S[i]Nck.[/i] guck. huh? ","","","","",""],
["","you","","sorry, you fell asleep at your desk.","","","","",""],
["oliver_wake_up2","oliver","","wh... it's ok, ij..","","","","",""],
["","_none","","oliver stares blearily at you, then his papers.","","","","",""],
["","oliver","","how long ws i out?","","","","",""],
["","you","","i don't know, i just got here.","","","","",""],
["","oliver","","ah, fuck... i'm gonna miss the deadline...","","","","",""],
["","_none","","he rubs his eyes and searches for a pen.","","","","",""],
["","you","","what deadline?","","","","",""],
["","oliver","","thesis deadline. it's in...","","","","",""],
["","","","it's...","","","","",""],
["","","","where am i, again?","","","","",""],
["","","","","","","","",[['purrgatory', 'oliver_where1'], ['your study', 'oliver_where2']]],
["oliver_where1","you","","purrgatory, remember?","","","","",""],
["","oliver","","oh. right.","","","","",""],
["","","","purrgatory with two r's.","","","","",""],
["","","","i was very indignant about that while crossing the office styx...","","","oliver_where3","",""],
["oliver_where2","you","","your study, remember?","","","","",""],
["","oliver","","oh. right.","","","","",""],
["","","","boy, i should really clean this place...","","","","",""],
["oliver_where3","oliver","","sorry about that... don't know what came over me.","","","","",""],
["","","","thank you for waking me up. i should get back to work.","","","","",""],
["","","","","","","","",[['oh no you don\'t', 'oliver_oh_no_you_dont'], ['i really think you should take a break', 'oliver_take_a_break']]],
["oliver_oh_no_you_dont","you","","oh, no you don't.","","","","",""],
["","","","you're like","","","","",""],
["","","","passing out due to exhaustion.","","","","",""],
["","","","you need a break.","","","","",""],
["","oliver","","i'll be fine!","","","","",""],
["","","","{player}, this is important.","","","","",""],
["","","","when nothing makes sense, you have to--","","","","",""],
["","you","","nope!","","","","",""],
["","","","you're taking a break right now.","","","","",""],
["","oliver","","...[i]sigh[/i]","","","","",""],
["","","","i can't. i've never been able to just sit around when there's work to be done.","","","oliver_take_a_break2","",""],
["oliver_take_a_break","you","","oliver, i really think you should take a break.","","","","",""],
["","","","you're passing out due to exhaustion.","","","","",""],
["","oliver","","i'll be fine!","","","","",""],
["","","","{player}, this is important.","","","","",""],
["","","","when nothing makes sense, you have to--","","","","",""],
["","you","","i know, i know.","","","","",""],
["","","","i'm just worried for your health.","","","","",""],
["","oliver","","i appreciate the concern. now please, i have to get back to work.","","","","",""],
["","you","","fine...","","","","",""],
["","oliver","","...[i]yawn.[/i] thank you. i'm glad you... see reason...","","","","",""],
["","you","_none","will you at least stretch every now and then?","","","","",""],
["","","","...","","","","",""],
["","","","oliver?","","","","",""],
["","","","...","","","","",""],
["","","","OLIVER!!","","","","",""],
["","oliver","oliver_neutral","HSBTHWHAT?","","","","",""],
["","","","oh. sorry","","","","",""],
["","you","","you fell asleep again.","","","","",""],
["","oliver","","yes, i realize that.","","","","",""],
["","","","maybe... maybe you have a point.","","","","",""],
["","you","","thought so.","","","","",""],
["","oliver","","...[i]sigh[/i]","","","","",""],
["","","","i've never been able to just sit around when there's work to be done.","","","","",""],
["oliver_take_a_break2","you","","then why don't we do something else?","","","","",""],
["","","","maybe you could use a change in scenery.","","","","",""],
["","oliver","","like what?","","","","",""],
["","you","","like...","","","","",""],
["","","","","","","","",[['take a walk in the park', 'oliver_scenery1'], ['visit the meowseum', 'oliver_scenery2'], ['admire the drop-off', 'oliver_scenery3']]],
["oliver_scenery1","you","","take a walk in the park?","oliver_chose_park","","","",""],
["","oliver","","that sounds…","","","","",""],
["","","","agreeable.","","","","",""],
["","you","","let's go, then!","","","","",""],
["","oliver","","right now?","","","","",""],
["","","","maybe I can just finish annotating this data and--","","","","",""],
["","you","","yes, right now. come on!","","","","",""],
["","oliver","","alright…","","","","",""],
["","_none","","oliver follows you to the park.","oliver_goto_park1","","","",""],
["","you","","this is nice, right?","","","","",""],
["","","","some fresh air and exercise.","","","","",""],
["","oliver","","i'm not sure if i would this air \"fresh\"...","","","","",""],
["","you","","but look at all those trees!","","","","",""],
["","","","trees make oxygen, right?","","","","",""],
["","oliver","","living ones, yes. all of these are dead.","","","","",""],
["","you","","oh. right.","","","","",""],
["","_none","","you walk in silence for a while.","oliver_goto_park2","","","",""],
["","you","","wonder who's buried here?","","","","",""],
["","oliver","","i don't know.","","","","",""],
["","you","","i bet it's...","","","","",""],
["","","","","","","","",[['sinners', 'oliver_buried1'], ['cats', 'oliver_buried2'], ['nothing', 'oliver_buried3']]],
["oliver_buried1","you","","sinners. they were so evil that they're decompo-[i]sin[/i]!","","","oliver_buried4","",""],
["oliver_buried2","you","","cats. it would fit the theme","","","oliver_buried4","",""],
["oliver_buried3","you","","nothing. i bet it's just to scare us","","","oliver_buried4","",""],
["oliver_buried4","_none","","oliver shrugs.","","","","",""],
["","you","","well, that's my guess, anyway.","","","","",""],
["","oliver","","...","","","","",""],
["","_none","","you walk in silence some more.","oliver_goto_park3","","","",""],
["","you","","...","","","","",""],
["","oliver","","...","","","oliver_scenery4","",""],
["oliver_scenery2","you","","visit the meowseum?","oliver_chose_meowseum","","","",""],
["","oliver","","that sounds…","","","","",""],
["","","","agreeable.","","","","",""],
["","you","","let's go, then!","","","","",""],
["","oliver","","right now?","","","","",""],
["","","","maybe I can just finish annotating this data and--","","","","",""],
["","you","","yes, right now. come on!","","","","",""],
["","oliver","","alright…","","","","",""],
["","_none","","oliver follows you to the meowseum.","oliver_goto_meowseum1","","","",""],
["","you","","ah, culture and art. refreshing.","","","","",""],
["","oliver","","i'm not sure if i would this \"culture\"...","","","","",""],
["","you","","it's totally culture","","","","",""],
["","","","look at that da vinci!","","","","",""],
["","oliver","","i think that one's vermeer.","","","","",""],
["","you","","oh. right.","","","","",""],
["","_none","","you walk in silence for a while.","oliver_goto_meowseum2","","","",""],
["","you","","wonder what's in the box?","","","","",""],
["","oliver","","i don't know.","","","","",""],
["","you","","i bet it's...","","","","",""],
["","","","","","","","",[['a dead cat', 'oliver_box1'], ['a living cat', 'oliver_box2'], ['nothing', 'oliver_box3']]],
["oliver_box1","you","","a dead cat. this is the afterlife, right? that's a [i]dead[/i] giveaway!","","","oliver_box4","",""],
["oliver_box2","you","","a living cat. it just really likes sitting in that box","","","oliver_box4","",""],
["oliver_box3","you","","nothing. that's the trick, there was never a cat to begin with!","","","oliver_box4","",""],
["oliver_box4","_none","","oliver shrugs.","","","","",""],
["","you","","well, that's my guess, anyway.","","","","",""],
["","oliver","","...","","","","",""],
["","_none","","you walk in silence some more.","oliver_goto_meowseum3","","","",""],
["","you","","…","","","","",""],
["","oliver","","...","","","oliver_scenery4","",""],
["oliver_scenery3","you","","admire the drop-off?","oliver_chose_dropoff","","","",""],
["","oliver","","that sounds...","","","","",""],
["","","","agreeable.","","","","",""],
["","you","","let's go, then!","","","","",""],
["","oliver","","right now?","","","","",""],
["","","","maybe I can just finish annotating this data and--","","","","",""],
["","you","","yes, right now. come on!","","","","",""],
["","oliver","","alright…","","","","",""],
["","_none","","oliver follows you to the caves.","oliver_goto_dropoff1","","","",""],
["","you","","this room is really pretty.","","","","",""],
["","oliver","","i'm not sure if i would call it \"pretty\"...","","","","",""],
["","you","","it's totally pretty","","","","",""],
["","","","look at this stalactite!","","","","",""],
["","oliver","","that's a stalagmite.","","","","",""],
["","you","","oh. right.","","","","",""],
["","_none","","you walk in silence for a while.","oliver_goto_dropoff2","","","",""],
["","you","","i wonder what's down there? in the drop-off?","","","","",""],
["","oliver","","i don't know.","","","","",""],
["","you","","i bet it's...","","","","",""],
["","","","","","","","",[['hell', 'oliver_down_there1'], ['heaven', 'oliver_down_there2'], ['nothing', 'oliver_down_there3']]],
["oliver_down_there1","you","","hell. after all, it looks like a [i]hell[/i] of a drop!","","","oliver_down_there4","",""],
["oliver_down_there2","you","","heaven. the last thing you'd expect","","","oliver_down_there4","",""],
["oliver_down_there3","you","","nothing. if you fell, you'd just fall forever","","","oliver_down_there4","",""],
["oliver_down_there4","_none","","oliver shrugs.","","","","",""],
["","you","","well, that's my guess, anyway.","","","","",""],
["","oliver","","...","","","","",""],
["","_none","","you walk in silence some more.","oliver_goto_dropoff3","","","",""],
["","you","","…","","","","",""],
["","oliver","","...","","","","",""],
["oliver_scenery4","","","","","","","",[['you\'re as quiet as a mouse', 'oliver_quiet'], ['what\'s on your mind?', 'oliver_thinking_about']]],
["oliver_quiet","you","","you're as quiet as a mouse.","","","","",""],
["","oliver","","sorry.","","","","",""],
["","","","just tired.","","","","",""],
["","you","","it's alright. it's just","","","oliver_lively","",""],
["oliver_thinking_about","you","","what's on your mind?","","","","",""],
["","oliver","","nothing.","","","","",""],
["","","","just tired.","","","","",""],
["","you","","are you sure?","","","","",""],
["oliver_lively","","","you're usually more... lively","","","","",""],
["","oliver","","i suppose i am.","","","","",""],
["","you","","...","","","","",""],
["","","","want to sit?","","","","",""],
["","oliver","","sure.","","","","",""],
["","_none","","you sit.","","","","",""],
["","oliver","","...","","","","",""],
["","you","","...","","","","",""],
["","oliver","","you know, i've always had a hard time admitting that i'm wrong.","","","","",""],
["","you","","oh?","","","","",""],
["","oliver","","yes, it's something that i was... working on. ","","","","",""],
["","","","when i was alive.","","","","",""],
["","you","","ic","","","","",""],
["","","","","","","","",[['i have that problem too', 'oliver_problem1'], ['my problem is that i\'m ALWAYS wrong', 'oliver_problem2'], ['(stay quiet)', 'oliver_problem3']]],
["oliver_problem1","you","","i have that problem too. ","","","","",""],
["","","","i mean, who doesn't want to look smart?","","","","",""],
["","oliver","","really?","","","","",""],
["","","","how do you deal with it?","","","","",""],
["","you","","well, you just have to practice saying \"you're right\" and moving on.","","","","",""],
["","oliver","","but what if they're not right? i can't just--","","","","",""],
["","","","...","","","","",""],
["","","","ah, yes. i see your point.","","","","",""],
["","you","","hehe. exactly.","","","oliver_problem3","",""],
["oliver_problem2","you","","my problem is that i'm ALWAYS wrong","","","","",""],
["","oliver","","i'm sure that's not true.","","","","",""],
["","you","","it's okay, i know my strengths and weaknesses","","","","",""],
["","","","besides, there's nothing wrong with being wrong!","","","","",""],
["","oliver","","hm.","","","","",""],
["oliver_problem3","oliver","","i remember in middle school--","","","","",""],
["","","","this is kind of a stupid story, but","","","","",""],
["","","","on the way to school one day, my brother andrew, he pointed out that my shirt was inside out.","","","","",""],
["","you","","mhm.","","","","",""],
["","oliver","","the funny thing is, i already knew it was inside out, but i didn't want to acknowledge that he was right.","","","","",""],
["","","","so i just left it like that the entire day.","","","","",""],
["","","","i told my friends it was a new fashion trend, and they all started doing it too.","","","","",""],
["","you","","nice","","","","",""],
["","","","truly a trendsetter.","","","","",""],
["","oliver","","heh, in a way, yes.","","","","",""],
["","","","but it's kind of sad, isn't it?","","","","",""],
["","","","i wore my shirt inside out for an entire month just to prove my brother wrong.","","","","",""],
["","you","","aw, you were just a kid.","","","","",""],
["","","","kids do all sorts of dumb things.","","","","",""],
["","oliver","","i suppose so.","","","","",""],
["","","","...","","","","",""],
["","you","","...","","","","",""],
["","oliver","","want to play tic-tac-toe?","","","","",""],
["","you","","sure!","","","ttt_init","",""],
["oliver_after_ttt","you","oliver_neutral","...","","","","",""],
["","oliver","","{player}?","","","","",""],
["","you","","yeah?","","","","",""],
["","oliver","","sometimes, i get...","","","","",""],
["","","","the feeling","","","","",""],
["","","","that","","","","",""],
["","","","i'm not","","","","",""],
["","","","a good person","","","","",""],
["","","","","","","","",[['you are a good person', 'oliver_good_person1'], ['no one\'s a good person', 'oliver_good_person2']]],
["oliver_good_person1","you","","you are a good person!","","","null","",""],
["oliver_good_person2","you","","no one's a good person","","","null","",""]
]