extends Node

var raw_blocks = [
["piano_intro","_none","_none","sean plugs in the batteries.",[['_inv_battery1', false], ['_inv_battery2', false], ['_goto_keyboard', true], ['setup_piano', true]],"","","","",""],
["","sean","","we're GREEN, baby!!","_piano_lick1","","","","",""],
["","you","","we are?","disable_exit","","","","",""],
["","sean","","you know, like","sean_jammed","","","","",""],
["","","","like a green light?","","","","","",""],
["","","","just roll with it man!! words don't have to make sense if they're in tune!","_piano_lick2","","","","",""],
["","","","","","","","",['i\'m not sure if that\'s necessarily true', 'let\'s roll and rock baby face!'],['piano_intro1', 'piano_intro2']],
["piano_intro1","you","","i'm not sure if that's necessarily true?","","","","","",""],
["","sean","","who needs truth when u have GROOVE??","_delay__piano_lick3","","null","","",""],
["piano_intro2","you","","let's roll and rock baby face!","","","","","",""],
["","sean","","THAT'S the spirit!!","_delay__piano_lick3","","null","","",""],
["piano_intro3","sean","","also please keep your expectations low i am bad at piano","","","","","",""],
["","you","","lol, it's okay","","","","","",""],
["","sean","","i've been practicing though!","","","","","",""],
["","","","check this shit out","_delay__piano_fur_elise1","","null","","",""],
["piano_intro3a","sean","","fuck","_delay__piano_fur_elise2","","null","","",""],
["piano_intro3b","sean","","wait just, give me a second","","","","","",""],
["","you","","take your time","_delay__piano_fur_elise3","","null","","",""],
["piano_intro3c","sean","","ahhh, you know what, forget it","","","","","",""],
["","","","bach is overrated anyway","","","","","",""],
["","_none","","sean blows a raspberry.","","","","","",""],
["","","","","","","","",['agreed', 'i kinda like it', 'i think this one\'s beethoven'],['piano_intro4', 'piano_intro5', 'piano_intro6']],
["piano_intro4","you","","agreed","","","","","",""],
["","sean","","classical? more like. ASS-ical.","","","","","",""],
["","you","","lol gotem","","","piano_intro7","","",""],
["piano_intro5","you","","idk, i kinda like it","","","","","",""],
["","","","i think it's soothing","","","","","",""],
["","sean","","well, maybe it's good if you're trying to FALL ASLEEP","","","","","",""],
["","you","","i do use it to fall asleep!","","","","","",""],
["","sean","","oh","","","","","",""],
["","","","well, good for you","","","piano_intro7","","",""],
["piano_intro6","you","","i think this one's beethoven?","","","","","",""],
["","sean","","like the dog???","","","","","",""],
["","you","","...","","","","","",""],
["","","","yeah, why not!","","","","","",""],
["","_none","","sean shakes his head.","","","","","",""],
["","sean","","that talented motherfucking pupper.","","","piano_intro7","","",""],
["piano_intro7","sean","","anyway, do u know how to do heart and soul?","","","","","",""],
["","","","like the piano duet?","","","","","",""],
["","","","","","","","",['yeah!', 'nope'],['piano_heart1', 'piano_heart2']],
["piano_heart1","you","","yeah i think so!","","","","","",""],
["","","","do you want the bottom or top?","","","","","",""],
["","sean","","hey now, buy me a drink first ;)","","","","","",""],
["","you","","what-- no--","","","","","",""],
["","","","i meant the piano parts!","","","","","",""],
["","sean","","haha i'll take the bottom this time","","","","","",""],
["piano_heart1b","","","ready?","","","","","",""],
["","you","","scoot over a little?","","","","","",""],
["","sean","","alright, this good?","","","","","",""],
["","you","","yeah, i'm ready","","","","","",""],
["","sean","","TIME TO JAM","","","","","",""],
["","you","","WOOOOO JAM TIME","_delay__piano_heart_performance","","null","","",""],
["piano_heart2","you","","nope","","","","","",""],
["","sean","","dude i'll teach you!","","","","","",""],
["","","","it's SUPER easy","","","","","",""],
["","you","","sounds fun!","","","","","",""],
["","sean","","i'll teach you the top part, cus it's easier","","","","","",""],
["","","","are you watching?","","","","","",""],
["","you","","yeah, go ahead","","","","","",""],
["","sean","","it's like this...","_delay__piano_heart_tutorial","","null","","",""],
["piano_heart3","sean","","think you got it?","","","","","",""],
["","you","","uhhhh","","","","","",""],
["","","","","","","","",['one more time?', 'whatever let\'s do it!'],['piano_heart4', 'piano_heart5']],
["piano_heart4","you","","one more time, if you don't mind?","","","","","",""],
["","sean","","yeah, no problem","_delay__piano_heart_tutorial","","null","","",""],
["piano_heart5","you","","whatever let\'s do it!","","","","","",""],
["","sean","","alright!!","","","piano_heart1b","","",""],
["piano_heart6","sean","","hey that wasn't bad!","","","","","",""],
["","","","","","","","",['it was kind of bad', 'wooooo music!'],['piano_heart7', 'piano_heart8']],
["piano_heart7","you","","it was... kind of bad","","","","","",""],
["","sean","","ok maybe a little :P","","","piano_heart9","","",""],
["piano_heart8","you","","wooooooo music!!","","","piano_heart9","","",""],
["piano_heart9","you","","where'd you learn that?","","","","","",""],
["","sean","","oh, my partner taught me","","","","","",""],
["","","","i don't remember if i mentioned this, but my partner fuckin LOVED classical music","","","","","",""],
["","","","they were a goddamn prodigy on the keyboard","","","","","",""],
["","","","and like","","","","","",""],
["","","","you know i'm not into classical, right?","","","","","",""],
["","you","","uh huh","","","","","",""],
["","sean","","me, i need something with a beat","","","","","",""],
["","","","but when dani played the piano, it was like","","","","","",""],
["","","","WOW","","","","","",""],
["","","","fuckin transcendental","","","","","",""],
["","","","suddenly i understood why someone might devote their life to being able to play like that","","","","","",""],
["","","","not me, personally, but you know. someone.","","","","","",""],
["","","","that's the sort of shit that makes you fall in love with someone","","","","","",""],
["","you","","wow, yeah","","","","","",""],
["","sean","","me, i played guitar","","","","","",""],
["","","","so we used to jam on our respective instruments","","","","","",""],
["","","","neighbors would come bang on our door and complain","","","","","",""],
["","","","good times","","","","","",""],
["","you","","hah, nice","","","","","",""],
["","sean","","dude one time we were just jamming out","","","","","",""],
["","","","window open cus it's a nice day","","","","","",""],
["","","","and one of our neighbors pokes his head inside with a tiny dog in his arms, looking FURIOUS","","","","","",""],
["","","","and he's like--","","","","","",""],
["","???","","what is that godawful noise?","","met_tori",['sean_post_jam1', 'sean_post_jam2'],"","",""]
]