extends Node

var raw_blocks = [
["poems","_none","_none","read a poem from the pile?","","","","",['yes', 'no'],['poems_random', 'null']],
["poems_random","_none","_none","you pick up a crumped page.","read_elijahs_poems","",['_rand', 'poem1', 'poem2', 'poem3', 'poem5', 'poem6', 'poem7', 'poem8', 'poem9', 'poem10', 'poem11', 'poem12'],"","",""],
["poem1","_none","_none","[i]when will i learn?[/i]","","","","","",""],
["","","","[i]see me calling shots i can't make[/i]","","","","","",""],
["","","","[i]two-for-one, tear jerking,[/i]","","","","","",""],
["","","","[i]spitting mad, it's all the same[/i]","","","","","",""],
["","","","[i]come home to drywall cracks and oatmeal[/i]","","","","","",""],
["","","","[i]flies buzzing in my ear[/i]","","","","","",""],
["","","","[i]when will you learn?[/i]","","","","","",""],
["","","","[i]when will you learn?[/i]","","","poems_end","","",""],
["poem2","_none","_none","[i]roasted veggies[/i]","","","","","",""],
["","","","[i]potato, squash, and broccoli (frozen ok)[/i]","","","","","",""],
["","","","[i]mix with olive oil, apple vinegar, salt, pepper, basil, rosemary, red pepper flakes[/i]","","","","","",""],
["","","","[i]roast at 450 for 20 min[/i]","","","poems_end","","",""],
["poem3","_none","_none","[i]tinnitus[/i]","","","","","",""],
["","","","[i]silent screaming static[/i]","","","","","",""],
["","","","[i]shrill and seismic[/i]","","","","","",""],
["","","","[i]shit seriously sucks[/i]","","","poems_end","","",""],
["poem5","_none","_none","[i]i sat on the edge of my seat as[/i]","","","","","",""],
["","","","[i]the words poured out of their mouths and[/i]","","","","","",""],
["","","","[i]made my heart pound[/i]","","","","","",""],
["","","","[i]where do the words come from?[/i]","","","","","",""],
["","","","[i]is it the gallbladder?[/i]","","","","","",""],
["","","","[i]i spat their words back out[/i]","","","","","",""],
["","","","[i]like a hairball of letters[/i]","","","","","",""],
["","","","[i]thinking one day it'll be beautiful[/i]","","","","","",""],
["","","","[i]journeyed my whole life just to [/i]","","","","","",""],
["","","","[i]find out the earth is round[/i]","","","poems_end","","",""],
["poem6","_none","_none","[i]mt. mitchell[/i]","","","","","",""],
["","","","[i]we yell \"what?\" over laughing winds[/i]","","","","","",""],
["","","","[i]air rushing out nice and fast[/i]","","","","","",""],
["","","","[i]cobblestone and grass to my knees[/i]","","","","","",""],
["","","","[i]never knew this is where i belonged[/i]","","","","","",""],
["","","","[i]highest peak to the east[/i]","","","","","",""],
["","","","[i]of the mississippi river[/i]","","","","","",""],
["","","","[i]three bathroom stops and each[/i]","","","","","",""],
["","","","[i]dingy toilet is my salvation[/i]","","","poems_end","","",""],
["poem7","_none","_none","[i]when i'm feeling odontophorous[/i]","","","","","",""],
["","","","[i]sometimes i will preach to the chorus[/i]","","","","","",""],
["","","","[i]don't use bigs words[/i]","","","","","",""],
["","","","[i]or you'll sound like a nerd![/i]","","","","","",""],
["","","","[i]but time and again they ignore us[/i]","","","poems_end","","",""],
["poem8","_none","_none","[i]when i was younger[/i]","","","","","",""],
["","","","[i]a bird made a nest[/i]","","","","","",""],
["","","","[i]in my window[/i]","","","","","",""],
["","","","[i]i thought i was chosen[/i]","","","","","",""],
["","","","[i]for greatness[/i]","","","","","",""],
["","","","[i]actually[/i]","","","","","",""],
["","","","[i]my dad's car was chosen [/i]","","","","","",""],
["","","","[i]for bird poop[/i]","","","poems_end","","",""],
["poem9","_none","_none","[i]i worry about the trees[/i]","","","","","",""],
["","","","[i]that it took to make my sheets[/i]","","","","","",""],
["","","","[i]but i think it's alright[/i]","","","","","",""],
["","","","[i]'cus they're dead and so am i[/i]","","","poems_end","","",""],
["poem10","_none","_none","[i]the flood of '94[/i]","","","","","",""],
["","","","[i]i was just a kid[/i]","","","","","",""],
["","","","[i]sitting on the musty couch with [/i]","","","","","",""],
["","","","[i]my legs pulled up tight[/i]","","","","","",""],
["","","","[i]and marlin barking at the water[/i]","","","","","",""],
["","","","[i]i thought my couch would float away[/i]","","","","","",""],
["","","","[i]across the ocean [/i]","","","","","",""],
["","","","[i]to the strange place where [/i]","","","","","",""],
["","","","[i]people worship cows and [/i]","","","","","",""],
["","","","[i]drive on the left side of the road[/i]","","","poems_end","","",""],
["poem11","_none","_none","[i]regret[/i]","","","","","",""],
["","","","[i]you have so much to live for[/i]","","","","","",""],
["","","","[i]they said at last[/i]","","","","","",""],
["","","","[i]i wasn't supposed to see[/i]","","","","","",""],
["","","","[i]this side of the blast[/i]","","","poems_end","","",""],
["poem12","_none","_none","[i]everyone knows[/i]","saw_sean_poem","","","","",""],
["","","","[i]that snakes don't wear shoes[/i]","","","","","",""],
["","","","[i]so sean is a fake[/i]","","","","","",""],
["","","","[i]as feet he has two[/i]","","","poems_end","","",""],
["poems_end","_none","_none","_pass","","elijah_woke_up",['null', 'elijah_caught'],"","",""]
]