extends Node

var raw_blocks = [
["poems_random","elijah","","hm, let me think...","","",['_rand', 'poem1', 'poem2', 'poem3', 'poem6', 'poem7', 'poem8', 'poem9', 'poem10', 'poem11', 'poem12'],"","",""],
["poem1","elijah","","this one's called \"roasted veggies\"","","","","","",""],
["","","","[i]potato, squash, and broccoli (frozen ok)[/i]","","","","","",""],
["","","","[i]mix with olive oil, apple vinegar, salt, pepper, basil, rosemary, red pepper flakes[/i]","","","","","",""],
["","","","[i]roast at 450 for 20 min[/i]","","","","","",""],
["","you","","...that's just a recipe for roasted vegetables","","","","","",""],
["","elijah","","huh","","","","","",""],
["","","","so it is","","","null","","",""],
["poem2","elijah","","ah, this one was from my blue period!","","","","","",""],
["","you","","like picasso?","","","","","",""],
["","elijah","","no, it's the period when i used a blue pen","","","","","",""],
["","you","","oh","","","","","",""],
["","elijah","","it goes like this","","","","","",""],
["","","","[i]on saturday we play[/i]","","","","","",""],
["","","","[i]on sunday we pray[/i]","","","","","",""],
["","","","[i]on monday it's a leap day[/i]","","","","","",""],
["","","","[i]on tuesday i eat old bay[/i]","","","","","",""],
["","you","","huh","","","","","",""],
["","","","what about wednesday?","","","","","",""],
["","elijah","","oh, i don't do anything on wednesday.","","","null","","",""],
["poem3","elijah","","here's one","","","","","",""],
["","","","[i]tinnitus[/i]","","","","","",""],
["","","","[i]silent screaming static[/i]","","","","","",""],
["","","","[i]shrill and seismic[/i]","","","","","",""],
["","","","[i]shit seriously sucks[/i]","","","","","",""],
["","you","","dang, it really does suck","","","","","",""],
["","elijah","","truly","","","null","","",""],
["poem4","elijah","","oh, this one's alright.","","","","","",""],
["","","","[i]mt. mitchell[/i]","","","","","",""],
["","","","[i]we yell \"what?\" over laughing winds[/i]","","","","","",""],
["","","","[i]air rushing by nice and fast[/i]","","","","","",""],
["","","","[i]cobblestone and grass to my knees[/i]","","","","","",""],
["","","","[i]never knew this is where i belonged[/i]","","","","","",""],
["","","","[i]highest peak to the east of the mississippi river[/i]","","","","","",""],
["","","","[i]three bathroom stops and each dingy toilet is my salvation[/i]","","","","","",""],
["","you","","that one's nice!","","","","","",""],
["","elijah","","thank you, thank you","","","null","","",""],
["poem5","elijah","","how about this","","","","","",""],
["","","","[i]when i'm feeling odontophorous[/i]","","","","","",""],
["","","","[i]sometimes i will preach to the chorus[/i]","","","","","",""],
["","","","[i]don't use big words[/i]","","","","","",""],
["","","","[i]or you'll sound like a nerd![/i]","","","","","",""],
["","","","[i]but time and again they ignore us[/i]","","","","","",""],
["","you","","haha, i get it","","","","","",""],
["","elijah","","good. good.","","","null","","",""],
["poem6","elijah","","[i]when i was younger[/i]","","","","","",""],
["","","","[i]a bird made a nest[/i]","","","","","",""],
["","","","[i]in my window[/i]","","","","","",""],
["","","","[i]i thought i was chosen[/i]","","","","","",""],
["","","","[i]for greatness[/i]","","","","","",""],
["","","","[i]actually[/i]","","","","","",""],
["","","","[i]my dad's car was chosen[/i]","","","","","",""],
["","","","[i]for bird poop[/i]","","","","","",""],
["","you","","lol","","","","","",""],
["","elijah","","that one's called \"cleaning bird poop off my dad's car.\"","","","null","","",""],
["poem7","elijah","","here's a silly one","","","","","",""],
["","","","[i]i'd pine for the trees[/i]","","","","","",""],
["","","","[i]that we cut at the stem[/i]","","","","","",""],
["","","","[i]but now i feel better[/i]","","","","","",""],
["","","","[i]cus i'm dead just like them[/i]","","","","","",""],
["","you","","lol","","","null","","",""],
["poem8","elijah","","this one's interesting","","","","","",""],
["","","","[i]the flood of '94[/i]","","","","","",""],
["","","","[i]i was just a kid[/i]","","","","","",""],
["","","","[i]sitting on the musty couch with[/i]","","","","","",""],
["","","","[i]my legs pulled up tight[/i]","","","","","",""],
["","","","[i]and marlin barking at the water[/i]","","","","","",""],
["","","","[i]i thought my couch would float away[/i]","","","","","",""],
["","","","[i]across the ocean[/i]","","","","","",""],
["","","","[i]to the strange place where[/i]","","","","","",""],
["","","","[i]people worship cows and[/i]","","","","","",""],
["","","","[i]drive on the left side of the road[/i]","","","","","",""],
["","you","","india?","","","","","",""],
["","elijah","","yeah.","","","","","",""],
["","","","i wasn't a very worldly kid.","","","null","","",""],
["poem9","_none","","(placholder)","","","null","","",""],
["poem10","_none","","(placholder)","","","null","","",""]
]