extends Node

var raw_blocks = [
["talk_to_receptionist","you","receptionist_neutral","hello?",[['recep_main0', true], ['recep_main1', true]],"","","",""],
["","receptionist","","hello, hello. be a dear and fill out this form.","","","","",""],
["","you","","i don’t remember how i got here…","","","","",""],
["","receptionist","","that's too bad. i need you to sign on this dotted line here.","","","","",""],
["","_none","","the receptionist hands you a pen and a clipboard.","","","","",""],
["","","","registration: \n[  ] heaven\n[x] purrgatory\n[  ] hell","","","","",""],
["recep_main","","","","","","",['recep_main0', 'recep_main1', 'true'],[["purgatory is spelled wrong", "recep_spelling"], ["what if i don't sign?", "recep_dont"], ["ok", "recep_ok"]]],
["recep_spelling","you","","purgatory is spelled wrong here.",[['recep_main0', false]],"","","",""],
["","receptionist","","no it's not.","","","","",""],
["","you","","see, there's two r's. there should only be one.","","","","",""],
["","receptionist","","tell you what, dear, you go and get a degree in demon resources management, then you can come back and tell me how to do my job.","","","","",""],
["","you","","jeez, never mind","","","recep_main","",""],
["recep_dont","you","","what'll happen if i refuse to sign this?",[['recep_main1', false]],"","","",""],
["","receptionist","","we can always make room for you downstairs, if you'd rather.","","","","",""],
["","","","now hurry up, dear, we don't have all eternity.","","","recep_main","",""],
["recep_ok","_none","","you pick up the pen to write your name…","","","","",""],
["","","","(the player inputs their name here)","","","","",""],
["","receptionist","","wonderful. let's get you filed away with the others.","","","","",""],
["","_none","","the receptionist takes your documents and opens a file cabinet.","","","","",""],
["","receptionist","","let's see. you're number… eight?","","","","",""],
["","","","oh dear, that's over capacity.","","","","",""],
["","you","","what's wrong?","","","","",""],
["","receptionist","","just a clerical error, nothing to worry your little head about.","","","","",""],
["","","","why don't you head on into the portal. i've got to take this to the man downstairs.","","","","",""],
["","you","","wait, wait, i have so many questions!","","","","",""],
["","receptionist","","alright, dear. i'll make time for one, but then i really have to go.","","","","",""],
["","","","","","","","",[["who am i?", 'recep_who'], ["where am i?", 'recep_where'], ["who are you?", 'recep_you']]],
["recep_who","you","","who am i?","","","","",""],
["","receptionist","","well, that's simple. you're a deceased soul making the passage into the afterlife.","","","","",""],
["","you","","i'm dead??","","","","",""],
["","receptionist","","don't worry about it too much, dear. it'll all come back eventually.","","","recep_care","",""],
["recep_where","you","","where am i?","","","","",""],
["","receptionist","","the office styx, of course.","","","","",""],
["","you","","the office styx? what happened to the river?","","","","",""],
["","receptionist","","oh, we built a bridge over it, then we built an office building on the bridge.","","","","",""],
["","","","the ferry had a great ambiance, but the throughput was just terrible.","","","recep_care","",""],
["recep_you","receptionist","","why, i'm charon, of course. ferrywoman of the afterlife.","","","","",""],
["","you","","ferrywoman? where's the ferry?","","","","",""],
["","receptionist","","nowadays, the ferry is symbolic, dear. they put the boat itself in a museum.","","","","",""],
["recep_care","receptionist","","take care, now.","","","","",""],
["","_none","_none","the receptionist starts walking away.","met_receptionist","","null","",""],
["click_portal","_none","_none","_pass","","met_receptionist",['portal1', 'portal2'],"",""],
["portal1","","","you take a deep breath and step into the portal.","recep_entered_portal","","null","",""],
["portal2","","","looks like some sort of rotating portal.","","","null","",""]
]