extends Node

var raw_blocks = [
["talk_to_receptionist","you","receptionist_neutral","hello?",[['recep_main0', true], ['recep_main1', true]],"","","","",""],
["","receptionist","","hello, hello. be a dear and fill out this form.","","","","","",""],
["","you","","um, i don’t remember how i got here...","","","","","",""],
["","receptionist","","i'm sorry to hear that. i need you to sign on this dotted line here.","","","","","",""],
["","_none","registration","the receptionist hands you a pen and a clipboard.","","","","","",""],
["recep_main","","","","","","",['recep_main0', 'recep_main1', 'true'],['purgatory is spelled wrong', 'what if i don\'t sign?', '(sign your name)'],['recep_spelling', 'recep_dont', 'recep_ok']],
["recep_spelling","you","","um, purgatory is spelled wrong here",[['recep_main0', false]],"","","","",""],
["","receptionist","","no it's not.","","","","","",""],
["","you","","see, there's two r's","","","","","",""],
["","","","there should only be one","","","","","",""],
["","receptionist","","tell you what, dear. you go and get a degree in demon resources management, then you can come back and tell me how to do my job.","","","","","",""],
["","you","","sheesh, never mind...","","","recep_main","","",""],
["recep_dont","you","","what if i refuse to sign this?",[['recep_main1', false]],"","","","",""],
["","receptionist","","we can always make room for you downstairs, if you'd rather.","","","","","",""],
["","","","now hurry up, dear, we don't have all eternity.","","","recep_main","","",""],
["recep_ok","_none","","you pick up the pen to write your name.","","","","","",""],
["","","","",[['no_skip', true], ['enable_name_input', true]],"","","","",""],
["","receptionist","receptionist_neutral","{player}? wonderful. let's get you filed away with the others.",[['enable_name_input', false]],"","","","",""],
["","_none","","the receptionist takes your documents and opens a filing cabinet.","","","","","",""],
["","receptionist","","let's see. ","","","","","",""],
["","","","you're number... eight?","","","","","",""],
["","","","oh dear, that's over capacity.","","","","","",""],
["","you","","what's wrong?","","","","","",""],
["","receptionist","","just a clerical error, nothing to worry your little head about.","","","","","",""],
["","","","why don't you head on into the portal. i've got to take this to the man downstairs.","","","","","",""],
["","you","","wait, wait, i have so many questions!","","","","","",""],
["","receptionist","","alright, dear. i'll make time for one, but then i really have to go.","","","","","",""],
["","","","","","","","",['who am i?', 'where am i?', 'who are you?'],['recep_who', 'recep_where', 'recep_you']],
["recep_who","you","","who am i?","","","","","",""],
["","receptionist","","well, that's simple. ","","","","","",""],
["","","","you're {player}.","","","","","",""],
["","you","","no, i mean, where did i come from? what did i do for a living? stuff like that?","","","","","",""],
["","receptionist","","you already used up your one question, dear.","","","","","",""],
["","you","","but you didn't tell me anything!","","","","","",""],
["","receptionist","","should have thought of that before asking.","","","","","",""],
["","","","don't worry about it too much. it'll all come back eventually.","","","recep_care","","",""],
["recep_where","you","","where am i?","","","","","",""],
["","receptionist","","the office styx, of course.","","","","","",""],
["","you","","office styx? ","","","","","",""],
["","","","what happened to the river?","","","","","",""],
["","receptionist","","oh, we built a bridge over it, then we built an office building on the bridge.","","","","","",""],
["","","","the ferry was great for show, but the throughput was just terrible.","","","recep_care","","",""],
["recep_you","you","","who are you?","","","","","",""],
["","receptionist","","why, i'm charon, of course, ferrywoman of the afterlife.","","","","","",""],
["","you","","ferrywoman? ","","","","","",""],
["","","","where's the ferry?","","","","","",""],
["","receptionist","","nowadays the ferry is symbolic, dear. they put the boat itself in a museum.","","","","","",""],
["recep_care","receptionist","","take care, now.","","","","","",""],
["","_none","_none","the receptionist starts walking away.","met_receptionist","","null","","",""],
["click_portal","_none","_none","_pass","","met_receptionist",['portal1', 'portal2'],"","",""],
["portal1","","","you take a deep breath and step into the portal.","_delay_fade_out_trigger","","null","","",""],
["portal2","","","looks like some sort of rotating portal.","","","null","","",""],
["charon_busy","_none","_none","she seems... busy.","","","null","","",""]
]