extends Node

var raw_blocks = [
["talk_to_sean","_none","_none","_pass","","not met_sean",['es_intro', 'sean_default'],"",""],
["sean_default","_none","sean_neutral","_none","","","",['true', 'true', 'true', 'tried_meowseum_door and not (asked_about_meowseum_door and told_code_to_sean) and not (not asked_about_meowseum_door and opened_meowseum_door)'],[['what\'s up?', 'sean_whats_up'], ['what do you do for fun around here?', 'sean_for_fun'], ['looking good, snakey boy (;', 'sean_snakey_boy'], ['(about the meowseum door)', 'sean_meowseum']]],
["sean_whats_up","you","","what's up?","","","","",""],
["","sean","","not much, how's it hanging?","","","","",""],
["","you","","pretty good","","","","",""],
["","sean","","alright, keep it groovy.","","","","",""],
["","you","","lol, ok","","","null","",""],
["sean_for_fun","_none","","placeholder","","","null","",""],
["sean_snakey_boy","_none","","placeholder","","","null","",""],
["sean_meowseum","_none","_none","_pass","",['got_meowseum_passcode and asked_about_meowseum_door', 'asked_about_meowseum_door'],['sean_meowseum3', 'sean_meowseum2', 'sean_meowseum1'],"",""],
["sean_meowseum1","you","","do you know how to get into the meowseum?","","","","",""],
["","","","there's a padlock on the door","","","","",""],
["","sean","","oh, yeah!","","","","",""],
["","","","that's from hide-and-seek.","","","","",""],
["sean_hide_and_seek","","","","","","","",[['you were playing hide-and-seek?', 'sean_hide_and_seek1'], ['you padlocked a door while playing hide-and-seek?', 'sean_hide_and_seek2']]],
["sean_hide_and_seek1","you","","you were playing hide and seek?","","","","",""],
["","","","aren't you two kind of old for that?","","","","",""],
["","sean","","[i]shrug[/i]","","","","",""],
["","","","it was natalie's idea.","","","","",""],
["","elijah",['elijah_neutral', 'sean_neutral'],"hey, we're stuck in neverland.","display_elijah_and_sean","","","",""],
["","","","might as well act like it.","","","sean_hide_and_seek3","",""],
["sean_hide_and_seek2","you","","you padlocked a door while playing hide-and-seek?","","","","",""],
["","sean","","yeah, i wanted to make it a little spicier, you know?","","","","",""],
["","you","","...","","","","",""],
["","sean","","i mean, it worked, didn't it?","","","","",""],
["","elijah",['elijah_neutral', 'sean_neutral'],"yes, because you locked natalie into the museum.","display_elijah_and_sean","","","",""],
["","sean","","that's called strategy, baby!","","","","",""],
["","","","...","","","","",""],
["","","","you don't think she's still in there, do you?","","","","",""],
["","elijah","","i'm sure she found another way out.","","","","",""],
["","","","probably.","","","","",""],
["","sean","","...","","","","",""],
["","elijah","","...","","","","",""],
["sean_hide_and_seek3","sean","","anyway, i wrote the code down on one of elijah's old poems!","asked_about_meowseum_door","","","",""],
["","","","should be riiiiiight here","","","","",""],
["","","","...","","","","",""],
["","","","oh, shoot","","","","",""],
["","you","","what is it?","","","","",""],
["","sean","","must have fallen out of my pocket or something","","","","",""],
["","","","not sure where i dropped it, maybe in the park?","","got_meowseum_passcode",['sean_meowseum1b', 'sean_meowseum1a'],"",""],
["sean_meowseum1a","you","","okay, i'll see if i spot it.","","","","",""],
["","sean","","kk, thanks","","","","",""],
["","","","hey elijah! help me look around here.","","","","",""],
["","elijah","","[i]sigh[/i]","","","","",""],
["","","","why do i always end up cleaning up after your clever ideas?","","","","",""],
["","sean","","that's what friends are for, baby!","","","null","",""],
["sean_meowseum2","you","","any luck finding the passcode to the meowseum?","","","","",""],
["","sean","","i got nothing here.","","","","",""],
["","","","elijah?","","","","",""],
["","elijah",['elijah_neutral', 'sean_neutral'],"nope, lady luck has not visited us today.","display_elijah_and_sean","","elijah_lady_luck","",""],
["sean_meowseum3","you","","so, uh","","","","",""],
["","","","i think i found the passcode","","","","",""],
["","sean","","oh, for real?","","","","",""],
["sean_is_it_1234","you","","is it 1234?","","","","",""],
["","sean","","YEAH THAT'S IT","","","","",""],
["sean_ronnie_wood","sean","","i named it after my favorite ronnie wood album!","","","","",""],
["","you","","...really?","","","","",""],
["","sean","","man, how did i forget that?","","","","",""],
["","","","haha","","","","",""],
["","elijah",['elijah_neutral', 'sean_neutral'],"you never fail to impress me, sean.","display_elijah_and_sean","","","",""],
["","sean","","why, thank you!","","","","",""],
["","","","i think.","told_code_to_sean","","null","",""],
["sean_meowseum1b","you","","oh i think i saw it earlier!","","","sean_is_it_1234","",""]
]