extends Node

var raw_blocks = [
["talk_to_sean","_none","_none","_pass","","not met_sean",['es_intro', 'sean_default'],"","",""],
["sean_default","_none","sean_neutral","...","","","",['sean_went_to_piano and sean_moved_on_from_argument', 'sean_went_to_piano and not sean_moved_on_from_argument', 'true', 'true', 'tried_meowseum_door and not (asked_about_meowseum_door and told_code_to_sean) and not (not asked_about_meowseum_door and opened_meowseum_door)', 'true', 'true'],['let\'s jam!', 'what was that all about?', 'what\'s up?', 'what do you do for fun around here?', '(about the meowseum door)',  'anything you can tell me about this place?', 'looking good, snakey boy (;'],['sean_jam', 'sean_spat', 'sean_wasup', 'sean_for_fun', 'sean_meowseum', 'sean_purrgatory', 'sean_snakey_boy']],
["sean_wasup","you","sean_neutral","what's up?","","",['_rand', 'sean_wasup1', 'sean_wasup2', 'sean_wasup3', 'sean_wasup4', 'sean_wasup5', 'sean_wasup6', 'sean_wasup7', 'sean_wasup8', 'sean_wasup9', 'sean_wasup10', 'sean_wasup11', 'sean_wasup12', 'sean_wasup13', 'sean_wasup14', 'sean_wasup15', 'sean_wasup16', 'sean_wasup17', 'sean_wasup18', 'sean_wasup19', 'sean_wasup20'],"","",""],
["sean_meowseum","_none","_none","_pass","",['asked_elijah_only', 'got_meowseum_passcode and asked_about_meowseum_door', 'asked_about_meowseum_door'],['sean_meowseum_catchup', 'sean_meowseum3', 'sean_meowseum2', 'sean_meowseum1'],"","",""],
["sean_meowseum1","you","","do you know how to get into the meowseum?","","","","","",""],
["","","","there's a padlock on the door","","","","","",""],
["","sean","","oh, yeah!","","","","","",""],
["","","","that's from hide-and-seek.","","","","","",""],
["sean_hide_and_seek","","","","","","","",['you were playing hide-and-seek?', 'you padlocked a door while playing hide-and-seek?'],['sean_hide_and_seek1', 'sean_hide_and_seek2']],
["sean_hide_and_seek1","you","","you were playing hide and seek?","","","","","",""],
["","","","aren't you two kind of old for that?","","","","","",""],
["","sean","","[i]shrug[/i]","","","","","",""],
["","","","it was natalie's idea.","","elijah_and_sean_together",['sean_hide_and_seek1a', 'sean_hide_and_seek3'],"","",""],
["sean_hide_and_seek1a","elijah",['elijah_neutral', 'sean_neutral'],"hey, we're stuck in neverland.","display_elijah_and_sean","","","","",""],
["","","","might as well act like it.","","","sean_hide_and_seek3","","",""],
["sean_hide_and_seek2","you","","you padlocked a door while playing hide-and-seek?","","","","","",""],
["","sean","","yeah, i wanted to make the game a little spicier, you know?","","","","","",""],
["","you","","...","","elijah_and_sean_together",['sean_hide_and_seek2a', 'sean_hide_and_seek3'],"","",""],
["sean_hide_and_seek2a","sean","","i mean, it worked, didn't it?","","","","","",""],
["","elijah",['elijah_neutral', 'sean_neutral'],"yes, because you locked natalie into the museum.","display_elijah_and_sean","","","","",""],
["","sean","","that's called strategy, baby!","","","","","",""],
["","","","...","","","","","",""],
["","","","you don't think she's still in there, do you?","","","","","",""],
["","elijah","","i'm sure she found another way out.","","","","","",""],
["","","","probably.","","","","","",""],
["","sean","","...","","","","","",""],
["","elijah","","...","","","sean_hide_and_seek4","","",""],
["sean_hide_and_seek3","sean","","i mean, it [i]worked[/i].","asked_sean_only","","","","",""],
["sean_hide_and_seek4","","","anyway, i wrote the code down on one of elijah's old poems!","asked_about_meowseum_door","","","","",""],
["","","","should be riiiiiight here","","","","","",""],
["","","","...","","","","","",""],
["","","","oh, shoot","","","","","",""],
["","you","","what is it?","","","","","",""],
["","sean","","must have fallen out of my pocket or something","","","","","",""],
["","","","not sure where i dropped it, maybe in the park when we went for a walk?","","got_meowseum_passcode",['sean_meowseum1b', 'sean_meowseum1a'],"","",""],
["sean_meowseum1a","you","","okay, i'll take a [i]lock[/i] around!","","","","","",""],
["","sean","","heh, thanks :P","","elijah_and_sean_together",['sean_meowseum1c', 'null'],"","",""],
["sean_meowseum1c","","","hey elijah! help me look around here.","","","","","",""],
["","elijah","","[i]sigh[/i]","","","","","",""],
["","","","why do i always end up cleaning up after your clever ideas?","","","","","",""],
["","sean","","that's what friends are for, baby!","","","null","","",""],
["sean_meowseum2","you","","any luck finding the passcode to the meowseum?","","","","","",""],
["","sean","","got nothing here, sorry","","elijah_and_sean_together",['sean_meowseum2b', 'sean_meowseum2a'],"","",""],
["sean_meowseum2a","you","","aw","","","","","",""],
["","sean","","i bet i dropped it in the park earlier","","","","","",""],
["","","","you should take a look around there","","","","","",""],
["","you","","kk, thanks","","","null","","",""],
["sean_meowseum2b","","","elijah?","","","","","",""],
["","elijah",['elijah_neutral', 'sean_neutral'],"nope, lady luck has not visited us today.","display_elijah_and_sean","","elijah_lady_luck","","",""],
["sean_meowseum3","you","","so, uh","","","","","",""],
["","","","i think i found the passcode to the meowseum","","","","","",""],
["","sean","","oh, for real?","","","","","",""],
["sean_is_it_1234","you","","is it 1234?","","","","","",""],
["","sean","","YEAH THAT'S IT!","","","","","",""],
["sean_ronnie_wood","sean","","i named it after my favorite ronnie wood album!","","","","","",""],
["","you","","...really?","","","","","",""],
["","sean","","man, how did i forget that?","","","","","",""],
["","","","haha","","elijah_and_sean_together",['sean_ronnie_wood2', 'null'],"","",""],
["sean_ronnie_wood2","elijah",['elijah_neutral', 'sean_neutral'],"you never fail to impress me, sean.","display_elijah_and_sean","","","","",""],
["","sean","","why, thank you!","","","","","",""],
["","","","i think.","told_code_to_sean","","null","","",""],
["sean_meowseum1b","you","","oh i think i saw it earlier!","","","sean_is_it_1234","","",""],
["sean_meowseum_catchup","you","","hey, elijah said you might know the passcode to the meowseum?",[['asked_elijah_only', false]],"","","","",""],
["","sean","","oh!","","","","","",""],
["","","","that old thing","","","","","",""],
["","","","uhh","","","","","",""],
["","","","damn, i don't remember","","","","","",""],
["","","","and i don't remember where i left the paper that i wrote it down on...","","","","","",""],
["","you","","aw, that's ok","","","","","",""],
["","sean","","i'll look around! i'm sure we'll stumble across it or something","","","","","",""],
["","you","","thx","","","null","","",""],
["sean_wasup1","sean","","i miss peeing sometimes","","","","","",""],
["","you","","you miss... peeing?","","","","","",""],
["","sean","","yeah, you don't need to pee in purrgatory","","","","","",""],
["","","","no matter how much orange soda you drink.","","","","","",""],
["","you","","that's interesting","","","","","",""],
["","","","but... what do you miss about peeing?","","","","","",""],
["","sean","","hmm...","","","","","",""],
["","","","nothing in particular","","","","","",""],
["","","","it's just one of those things you don't appreciate until it's gone, ya know?","","","","","",""],
["","you","","i mean, sure","","","null","","",""],
["sean_wasup2","sean","","cowabunga!","","","","","",""],
["","you","","huh?","","","null","","",""],
["","sean","","i'm trying to gain a reputation as \"the guy who says cowabunga\"","","","","","",""],
["","","","do you think it's working?","","","","","",""],
["","","","","","","","",['yes', 'no'],['sean_wasup2a', 'sean_wasup2b']],
["sean_wasup2a","you","","sure!","","","","","",""],
["","sean","","cowabunga!!!","","","null","","",""],
["sean_wasup2b","you","","um, i don't know","","","","","",""],
["","","","i don't think you can force something like that, it just sort of happens","","","","","",""],
["","sean","","cowabunga ):","","","null","","",""],
["sean_wasup3","sean","","so you don't remember your past life at all?","","","","","",""],
["","you","","not really","","","","","",""],
["","sean","","man","","","","","",""],
["","","","you're lucky, in a way.","","","","","",""],
["","","","can't remember the ones you've left behind.","","","","","",""],
["","you","","aw","","","","","",""],
["","","","silver lining, i guess","","","null","","",""],
["sean_wasup4","sean","","i hope kyungsoon's okay","","","","","",""],
["","you","","did something happen to her?","","","","","",""],
["","sean","","nah, i just haven't seen her in a while","","","","","",""],
["","","","what if she suffered some sort of tragic cat-related accident??","","","","","",""],
["","you","","you mean some sort of... [i]cat[/i]-astrophe?","","","","","",""],
["","sean","","...[i]sigh[/i]","","elijah_and_sean_together",['sean_wasup4a', 'null'],"","",""],
["sean_wasup4a","elijah",['elijah_neutral', 'sean_neutral'],"you walked right into that one.","display_elijah_and_sean","","","","",""],
["","sean","","yeah, i know.","","","null","","",""],
["sean_wasup5","sean","","cravin' some orange soda rn","","","","","",""],
["","you","","isn't there some by the piano?","","","","","",""],
["","sean","","yeah, but i'm trying to lay off of soda a little","","","","","",""],
["","","","not good for the bod, ya know?","","","","","",""],
["","you","","oh yeah i know","","","null","","",""],
["sean_wasup6","sean","","[i]burp[/i]","","","","","",""],
["","","","scuse me","","","","","",""],
["","you","","you're excused","","","null","","",""],
["sean_wasup7","sean","","any thoughts on croutons?","","","","","",""],
["","you","","they're... crunchy?","","","","","",""],
["","sean","","fuck, they sure are","","","null","","",""],
["sean_wasup8","sean","","got any tattoos?","","","","","",""],
["","","","","","","","",['nope', 'a few', 'a lot'],['sean_wasup8a', 'sean_wasup8b', 'sean_wasup8c']],
["sean_wasup8a","you","","nope","","","","","",""],
["","sean","","aw, u missed out","","","sean_wasup8d","","",""],
["sean_wasup8b","you","","yeah, a few","","","","","",""],
["","sean","","sick!","","","sean_wasup8d","","",""],
["sean_wasup8c","you","","oh you know it","","","","","",""],
["","","","i got tattoos for days","","","","","",""],
["","sean","","aw yeah, that's what i'm talkin' about dude!!","","","","","",""],
["sean_wasup8d","you","","what about you, do you have any?","","","","","",""],
["","sean","","yeah, just a few","","","","","",""],
["","","","this one's my favorite.","","","","","",""],
["","_none","","he shows you a stylized deer head on his bicep.","","","","","",""],
["","you","","ooh, a deer?","","","","","",""],
["","sean","","yeah, for my partner.","","","","","",""],
["","","","they got a snake in the same place.","","","","","",""],
["","you","","awwwwwwwwwwwwwww that's adorable","","","","","",""],
["","sean","","i know, right??","","","null","","",""],
["sean_wasup9","sean","","wonder how my budgies are doing","","","","","",""],
["","you","","oh, you had birds?","","","","","",""],
["","","","what are their names?","","","","","",""],
["","sean","","goldenia, gabby, and gaylord.","","","","","",""],
["","","","they're adorable little fuckers :P","","","","","",""],
["","you","","those are good names!","","","","","",""],
["","sean","","thanks!","","","null","","",""],
["sean_wasup10","sean","","still waiting to be reborn as a zombie in my hometown cemetery","","","","","",""],
["","you","","oh man, i wish","","","","","",""],
["","","","at least let us be ghosts or something","","","","","",""],
["","sean","","ikr?","","","","","",""],
["","","","i know some people i would haunt the FUCK out of","","","null","","",""],
["sean_wasup11","sean","","do you know the wonder years? the band?","","","","","",""],
["","you","","i don't think so?","","","","","",""],
["","sean","","dude they're spectacular","","","","","",""],
["","","","i was going to see them live the year i died :/","","","","","",""],
["","you","","aw","","","","","",""],
["","sean","","yeah it sucks","","","null","","",""],
["sean_wasup12","sean","","you ever listen to metallica?","","","","","",""],
["","you","","not much","","","","","",""],
["","sean","","good.","","","","","",""],
["","","","they're overrated","","","null","","",""],
["sean_wasup13","sean","","you know that song, i can't get no satisfaction?","","","","","",""],
["","you","","yeah?","","","","","",""],
["","sean","","what the hell was he talking about","","","","","",""],
["","you","","uh, idk","","","","","",""],
["","","","sex?","","","","","",""],
["","sean","","u think it's about sex?","","","","","",""],
["","you","","i don't know, i'm just spitballing here","","","","","",""],
["","sean","","no you might be onto something","","","","","",""],
["","","","i'll have to think about this...","","","null","","",""],
["sean_wasup14","sean","","i have dancing queen stuck in my head","","","","","",""],
["","you","","oh, that's a good one","","","","","",""],
["","sean","","young and sweet","","","","","",""],
["","","","only seventeen","","","","","",""],
["","you","","something something tambourine?","","","","","",""],
["","sean","","close enough","","","null","","",""],
["sean_wasup15","sean","","i got sweet dreams stuck in my head.","","","","","",""],
["","you","","sweet dreams are made of cheeeese","","","","","",""],
["","sean","","you mean these?","","","","","",""],
["","you","","huh?","","","","","",""],
["","sean","","sweet dreams are made of these","","","","","",""],
["","","","right?","","elijah_and_sean_together",['sean_wasup15a', 'sean_wasup15b'],"","",""],
["sean_wasup15a","elijah",['elijah_neutral', 'sean_neutral'],"i thought it was \"sweet dreams are made of [i]this[/i]\"","display_elijah_and_sean","","","","",""],
["","sean","","no way","","","","","",""],
["","","","it's definitely these","","","","","",""],
["","elijah","","mmm that's not how i remember it","","","","","",""],
["","you","","i always thought it was cheese...","","","","","",""],
["","","","everything makes so much sense now","","","null","","",""],
["sean_wasup15b","you","","damn","","","","","",""],
["","","","i always thought it was cheese...","","","","","",""],
["","","","everything makes so much sense now","","","null","","",""],
["sean_wasup16","sean","","stairway to heaven is stuck in my head","","","","","",""],
["","you","","that's a good song!","","","","","",""],
["","sean","","i disagree","","","","","",""],
["","","","i've tried every staircase in purrgatory and none of them lead to heaven.","","","","","",""],
["","you","","lol","","","","","",""],
["","sean","","don't even get me [i]started[/i] on highway to hell!","","","null","","",""],
["sean_wasup17","sean","","[i]sigh[/i]","","","","","",""],
["","","","bruno mars is stuck in my head again","","","","","",""],
["","you","","what's wrong with bruno mars?","","","","","",""],
["","sean","","nothing!","","","","","",""],
["","","","i just don't want him in my head!!!","","","","","",""],
["","you","","oh","","","","","",""],
["","sean","","of all the things i like inside of me, bruno mars is not one of them.","","","","","",""],
["","you","","could you... phrase that differently?","","","","","",""],
["","sean","","i cannot","","","null","","",""],
["sean_wasup18","sean","","you ever wish you'd died in a different set of clothes?","","","","","",""],
["","you","","uh, not really","","","","","",""],
["","sean","","i mean, these shorts are great and all","","","","","",""],
["","","","but i wish i died in my pajamas.","","","","","",""],
["","","","if i'm gonna be here for eternity i might as well be comfortable.","","","null","","",""],
["sean_wasup19","sean","","do you know that song that goes like","","","","","",""],
["","","","doo doo doo, doo doo doo doo doo?","","","","","",""],
["","you","","uhhhhh","","","","","",""],
["","","","sing it again?","","","","","",""],
["","sean","","it's like doo doo doo, doo doo doo doo doo","","","","","",""],
["","you","","ummm i don't think so","","","","","",""],
["","sean","","damn","","","","","",""],
["","","","this is going to haunt me forever","","","null","","",""],
["sean_wasup20","sean","","i have megalovania stuck in my head","","","","","",""],
["","you","","oh, cool","","","","","",""],
["","","","...","","","","","",""],
["","","","now [i]i[/i] have megalovania stuck in my head","","","","","",""],
["","sean","","whoops","","","null","","",""],
["sean_snakey_boy","you","sean_neutral","looking good, snakey boy (;","","_pronouns_they or _pronouns_he",['sean_snakey_boy4', 'sean_snakey_boy1'],"","",""],
["sean_snakey_boy1","sean","","thanks!","","","","","",""],
["","you","","why don't we get to know each other a little better (;;;","","","","","",""],
["","sean","","oh","","","","","",""],
["","","","no thanks","","","","","",""],
["","","","","","","","",['you know u wanna (;;;;;;;', 'okay'],['sean_snakey_boy2', 'sean_snakey_boy3']],
["sean_snakey_boy2","you","","you know you wanna (;;;;;;;","","","","","",""],
["","sean","","uhh","","","","","",""],
["","","","don't, like, take this the wrong way, dude, but","","","","","",""],
["","","","you're not really... my type","","","","","",""],
["","you","","oh","","","","","",""],
["","sean","","because","","","","","",""],
["","","","i am gay","","","","","",""],
["","you","","ohhh","","","","","",""],
["","","","my bad","","","","","",""],
["","sean","","it's ok!","","","null","","",""],
["sean_snakey_boy3","you","","ah, okay","","","","","",""],
["","sean","","nothing pers!","","","null","","",""],
["sean_snakey_boy4","sean","","speak for yourself, cutie (;;","","","","","",""],
["","you","","why don't we get to know each other a little better (;;;","","elijah_and_sean_together",['sean_snakey_boy5', 'sean_snakey_boy6'],"","",""],
["sean_snakey_boy5","elijah",['elijah_neutral', 'sean_neutral'],"is all the winking really necessary?","display_elijah_and_sean","","","","",""],
["","sean","","elijah! ","","","","","",""],
["","","","we're having a moment here!","","","","","",""],
["","elijah","","unfortunately, i am a part of said moment.","","","","","",""],
["","","","by sheer proximity.","","","","","",""],
["","sean","","ah, i'm not really in the mood, anyway.","","","sean_snakey_boy7","","",""],
["sean_snakey_boy6","sean","","ah, i'm not really in the mood, sorry.","","","","","",""],
["sean_snakey_boy7","","","rain check? :P","","","","","",""],
["","you","","ugh, fiiiiine","","","null","","",""],
["sean_for_fun","you","sean_neutral","so, what do you do for fun around here?","","","","","",""],
["","sean","","oh, ya know","","","","","",""],
["","","","watch paint dry. watch grass grow.","","","","","",""],
["","","","pester elijah.","","elijah_and_sean_together",['sean_for_fun1', 'sean_for_fun2'],"","",""],
["sean_for_fun1","elijah",['elijah_neutral', 'sean_neutral'],"[i]sigh[/i]","display_elijah_and_sean","","","","",""],
["sean_for_fun2","sean","","it's boring as hell, to be honest.","","","","","",""],
["","","","","","","","",['what are your interests?', 'what did you do for fun in real life?'],['sean_hobbies', 'sean_real_life']],
["sean_hobbies","you","sean_neutral","well, what are your interests?","display_sean","","","","",""],
["","sean","","i'm really into music! used to work at a record store.","","","","","",""],
["","you","","what kind of music?","","","","","",""],
["","sean","","oh ya know, uhhhh, punk rock, alt rock, hardcore, metal...","","","","","",""],
["","you","","that's--","","","","","",""],
["","sean","","and space rock","","","","","",""],
["","you","","that's a lot of--","","","","","",""],
["","sean","","and drum and bass","","","","","",""],
["","you","","...","","","","","",""],
["","sean","","and uk garage, psytrance, prog trance, and 80's pop","","","","","",""],
["","","","you know, stuff like that.","","","","","",""],
["","you","","that's a lot of music!","","","","","",""],
["","sean","","yeah i got around :P","","","","","",""],
["","","","my partner likes classical, so they were starting to get me into that too.","","","","","",""],
["","","","very, very gradually.","","","","","",""],
["","","","never thought i would enjoy music written before 1900, but here we are.","","","","","",""],
["","you","","it's good to have an open mind about that kind of thing","","","","","",""],
["","sean","","totally.","","","null","","",""],
["sean_real_life","you","sean_neutral","well, what did you do for fun in real life?","display_sean","","","","",""],
["","sean","","hmm, guess i went out a lot","","","","","",""],
["","","","gotta live it up while you're still young, right? :P","","","","","",""],
["","you","","lol yeah","","","","","",""],
["","sean","","young [i]and[/i] alive","","","","","",""],
["","you","","yep","","","","","",""],
["","sean","","also taught myself how to play guitar. was working on drums too when i died.","","elijah_and_sean_together",['sean_real_life1', 'sean_real_life2'],"","",""],
["sean_real_life1","elijah",['elijah_neutral', 'sean_neutral'],"yes, sean has always had a propensity for making noise.","display_elijah_and_sean","","","","",""],
["","sean","","hey, what's wrong with that?","","","","","",""],
["","","","life is short! make as much noise as you want! be loud and proud!!","","","","","",""],
["","elijah","","well...","","","","","",""],
["","","","that would be good advice, if we were still alive.","","","","","",""],
["sean_real_life2","sean","","oh!","","","","","",""],
["","","","i also started a youtube channel where i played the guitar for my birds!","","","","","",""],
["","you","","no way that's adorable!!!!!!!","","","","","",""],
["","sean","","ikr????","","","","","",""],
["","","","duude","","","","","",""],
["","","","those were the days...","","","null","","",""],
["sean_purrgatory","you","","anything you can tell me about this place?","","","","","",""],
["","sean","","you mean purrgatory?","","","","","",""],
["","","","i dunno, i think it's pretty self-explanatory","","","","","",""],
["","","","something specific you wanna know?","","","","","",""],
["","","","","","","","",['how do you get out?', 'any places i should check out?', 'any people i should meet?'],['sean_get_out', 'sean_places', 'sean_people']],
["sean_get_out","you","","i guess, how do you get out of here?","","","","","",""],
["","sean","","beats me, dude","","","","","",""],
["","","","never seen anybody leave before.","","","","","",""],
["","you","","oh","","","","","",""],
["","","","do you have any, like... clues?","","","","","",""],
["","sean","","tell you what, next time i run into god, i'll pass on your question :P","","","","","",""],
["","you","","heh thanks","","elijah_and_sean_together",['sean_get_out1', 'null'],"","",""],
["sean_get_out1","elijah",['elijah_neutral', 'sean_neutral'],"you should ask tori, if you run into her.","display_elijah_and_sean","","","","",""],
["","","","she's always working on a new escape plan or something.","","","","","",""],
["","you","","oh, alright","","","null","","",""],
["sean_places","you","","any places i should check out?","","","","","",""],
["","sean","","in... purrgatory?","","","","","",""],
["","","","i don't know, it's not exactly a scenic route","","","","","",""],
["","","","the keyboard's pretty cool, i guess","","","","","",""],
["","you","","alright, i'll [i]key[/i]-p that in mind!","","","","","",""],
["","sean","","lol","","elijah_and_sean_together",['sean_places1', 'sean_places2'],"","",""],
["sean_places1","elijah",['elijah_neutral', 'sean_neutral'],"the park's a nice place to hang out too.","display_elijah_and_sean","","","","",""],
["","","","it's pretty cozy, once you get over the fact that the river is made of milk.","","","","","",""],
["sean_places2","sean","","oh! ","","","","","",""],
["","","","have you been to the dropoff?","","","","","",""],
["","","","big hole in the ground in the cave area.","","saw_dropoff",['sean_places2a', 'sean_places2b'],"","",""],
["sean_places2a","you","","yeah, i think i've seen it","","","","","",""],
["","sean","","isn't it wicked??","","elijah_and_sean_together",['sean_places3', 'sean_places4'],"","",""],
["sean_places2b","you","","uh, it doesn't ring a bell","","","","","",""],
["","sean","","you should check it out, it's pretty wicked.","","elijah_and_sean_together",['sean_places3', 'sean_places4'],"","",""],
["sean_places3","elijah",['elijah_neutral', 'sean_neutral'],"make sure not to fall in.","display_elijah_and_sean","","","","",""],
["","","","as far as we know, it goes down forever.","","","","","",""],
["","you","","oh, damn","","","","","",""],
["sean_places4","sean","","[i]my[/i] theory is that it goes to hell.","","","","","",""],
["","you","","that would... make sense","","","","","",""],
["","","","theologically speaking","","","","","",""],
["","sean","","mhm.","","","null","","",""],
["sean_people","you","","any people i should meet?","","","","","",""],
["","sean","","well, i'm sure you'll meet all of us before long...","","","","","",""],
["","","","oh!","","","","","",""],
["","","","have you met natalie yet?","","met_natalie",['sean_people1', 'sean_people2'],"","",""],
["sean_people1","you","","yeah i've met natalie!","","","","","",""],
["","sean","","isn't she a riot?","","","","","",""],
["","you","","yeah she's a lot of [i]pun[/i] to be around!","","","","","",""],
["","sean","","oh man","","","","","",""],
["","","","you two are perfect for each other","","","null","","",""],
["sean_people2","you","","i don't think so?","","","","","",""],
["","sean","","oh man","","","","","",""],
["","","","you like puns, right?","","","","","",""],
["","","","","","","","",['yes', 'duh', 'obviously'],['sean_people2a', 'sean_people2b', 'sean_people2c']],
["sean_people2a","you","","yep","","","sean_people3","","",""],
["sean_people2b","you","","duh","","","sean_people3","","",""],
["sean_people2c","you","","obviously","","","","","",""],
["sean_people3","sean","","then you two are gonna get along great :P","","","","","",""],
["","you","","i'm o-[i]pun[/i] to the possibility!","","","null","","",""],
["sean_spat","you","","what was that all about, earlier?","sean_moved_on_from_argument","","","","",""],
["","","","if you don't mind","","","","","",""],
["","sean","","ah, don't worry about it, dude.","","","","","",""],
["","","","it's no bigs","","","","","",""],
["","you","","it seemed maybe a little bigs...?","","","","","",""],
["","sean","","like medium size?","","","","","",""],
["","you","","yeah like a medium fries and coke?","","","","","",""],
["","","","if you don't wanna talk about it, it's cool","","","","","",""],
["","sean","","nah it's ok","","","","","",""],
["","","","i just get caught up in my head sometimes","","","","","",""],
["","","","like i think","","","","","",""],
["","","","what if i had gone to college? or like, what if i had joined a band?","","","","","",""],
["","","","done something productive, ya know.","","","","","",""],
["","","","hell what if i had run for president??","","","","","",""],
["","you","","i don't know if i would have wanted to live in that country","","","","","",""],
["","sean","","LOL ","","","","","",""],
["","","","fair :P","","","","","",""],
["","","","anyway yeah, it's no bigs, like i said.","","","","","",""],
["","you","","i see","","","","","",""],
["","sean","","...","","","","","",""],
["","","","plus he brought up dani.","","","","","",""],
["","","","my partner.","","","","","",""],
["","","","he didn't have to do that, ya know?","","","","","",""],
["","","","","","","","",['were you close?', 'i\'m sorry'],['sean_spat1', 'sean_spat2']],
["sean_spat1","you","","were you close?","","","","","",""],
["","sean","","oh, yeah.","","","","","",""],
["","","","peas in a pod.","","","","","",""],
["","","","...","","","sean_spat3","","",""],
["sean_spat2","you","","i'm sorry","","","","","",""],
["","","","you must miss them","","","","","",""],
["","sean","","i mean","","","","","",""],
["","","","...","","","","","",""],
["","","","yeah","","","","","",""],
["","","","i miss them so much","","","","","",""],
["","you","","...","","","","","",""],
["sean_spat3","sean","","anyway, enough sappy shit","","","","","",""],
["","","","wanna play some music??","","","","","",""],
["","you","","on the piano?","","","","","",""],
["","sean","","yep!","","","","","",""],
["","","","","","","","",['sure!', 'i don\'t know how to play...', 'maybe later'],['sean_spat4', 'sean_spat5', 'sean_spat6']],
["sean_spat4","you","","hmm, sure","","","sean_jam","","",""],
["sean_spat5","you","","oh, i don't know how to play...","","","","","",""],
["","sean","","me neither!!","","","","","",""],
["","","","but dani taught me some basics, so i can show you too","","","","","",""],
["","","","what do you say?","","","","",['sure!', 'maybe later'],['sean_spat4', 'sean_spat6']],
["sean_spat6","you","","maybe in a bit","","","","","",""],
["","","","i got some other stuff to do","","","","","",""],
["","sean","","alright, no probs","","","","","",""],
["","","","the jam session can wait :P","","","null","","",""],
["sean_jam","_none","_none","_pass","",['not sean_out_of_batteries', '_inv_battery1 and _inv_battery2', '_inv_scissor1 or _inv_battery2'],['sean_jam0', 'sean_jam_c', 'sean_jam_b', 'sean_jam_a'],"","",""],
["sean_jam0","you","","let's jam!","","","","","",""],
["","sean","","alright!!!!","","","","","",""],
["","_none","","sean presses a bunch of keys at once, but nothing happens.","","","","","",""],
["","sean","","...","","","","","",""],
["","you","","it didn't make any noise","","","","","",""],
["","sean","","yeah i know","","","","","",""],
["","","","hold on","","","","","",""],
["","","","...","","","","","",""],
["","","","crap","","","","","",""],
["","you","","is it broken?","","","","","",""],
["","sean","","it's out of battery","","","","","",""],
["","","","AGAIN","","","","","",""],
["","you","","awww man","","","","","",""],
["","sean","","maaaaaaaaaaan ):<","","","","","",""],
["","","","we need to find two double-a batteries","","","","","",""],
["","","","cus otherwise we are prohibited from jamming","","","","","",""],
["","you","","banned from the jam","","","","","",""],
["","sean","","exactly","","","","","",""],
["","you","","well, i'll see if i find some...","sean_out_of_batteries","","null","","",""],
["sean_jam_a","you","","did you find any batteries?","","","","","",""],
["","sean","","nope","","","","","",""],
["","","","but also i haven't left this room","","","","","",""],
["","you","","uh... why not?","","","","","",""],
["","sean","","i'm lazy","","","","","",""],
["","you","","that's fair","","","null","","",""],
["sean_jam_b","you","","i found a battery!","","","","","",""],
["","sean","","great!","","","","","",""],
["","","","just one more and we can jaaaaaaaam","","","","","",""],
["","you","","question","","","","","",""],
["","","","why am i doing all the searching?","","","","","",""],
["","sean","","because i'm lazy","","","","","",""],
["","you","","that's fair","","","null","","",""],
["sean_jam_c","you","","placeholder :3","","","null","","",""]
]