extends Node

var raw_blocks = [
["talk_to_sean","_none","_none","_pass","","not met_sean",['es_intro', 'sean_default-1'],"","",""],
["sean_default-1","_none","_none","_pass","","sean_went_to_piano and not sean_moved_on_from_argument",['sean_spat', 'sean_default-2'],"","",""],
["sean_default-2","_none","_none","_pass","","sean_quest_complete",['sean_post_quest', 'sean_default'],"","",""],
["sean_default","_none","sean_neutral","...","","","",['sean_went_to_piano and not sean_jammed', 'true', 'true', 'sean_went_to_piano and sean_jammed', 'tried_meowseum_door and not (asked_about_meowseum_door and told_code_to_sean) and not (not asked_about_meowseum_door and opened_meowseum_door)', 'true', 'true'],['let\'s jam!', 'what\'s up?', 'what do you do for fun around here?', '(about elijah\'s poems)', '(about the meowseum door)',  'anything you can tell me about this place?', 'looking good, snakey boy (;'],['sean_jam', 'sean_wasup', 'sean_for_fun', 'sean_snoop', 'sean_meowseum', 'sean_purrgatory', 'sean_snakey_boy']],
["sean_wasup","you","sean_neutral","what's up?","","",['_rand', 'sean_wasup1', 'sean_wasup2', 'sean_wasup3', 'sean_wasup4', 'sean_wasup5', 'sean_wasup6', 'sean_wasup7', 'sean_wasup8', 'sean_wasup9', 'sean_wasup10', 'sean_wasup11', 'sean_wasup12', 'sean_wasup13', 'sean_wasup14', 'sean_wasup15', 'sean_wasup16', 'sean_wasup17', 'sean_wasup18', 'sean_wasup19', 'sean_wasup20'],"","",""],
["sean_meowseum","_none","_none","_pass","",['asked_elijah_only', 'got_meowseum_passcode and asked_about_meowseum_door', 'asked_about_meowseum_door'],['sean_meowseum_catchup', 'sean_meowseum3', 'sean_meowseum2', 'sean_meowseum1'],"","",""],
["sean_meowseum1","you","","do you know how to get into the meowseum?","","","","","",""],
["","","","there's a padlock on the door","","","","","",""],
["","sean","","oh, yeah!","","","","","",""],
["","","","that's from hide-and-seek.","","","","","",""],
["sean_hide_and_seek","","","","","","","",['you were playing hide-and-seek?', 'you padlocked a door while playing hide-and-seek?'],['sean_hide_and_seek1', 'sean_hide_and_seek2']],
["sean_hide_and_seek1","you","","you were playing hide and seek?","","","","","",""],
["","","","aren't you two kind of old for that?","","","","","",""],
["","sean","","[i]shrug[/i]","","","","","",""],
["","","","it was natalie's idea.","","elijah_and_sean_together",['sean_hide_and_seek1a', 'sean_hide_and_seek3'],"","",""],
["sean_hide_and_seek1a","elijah",['elijah_neutral', 'sean_neutral'],"hey, we're stuck in neverland.","display_elijah_and_sean","","","","",""],
["","","","might as well act like it.","","","sean_hide_and_seek3","","",""],
["sean_hide_and_seek2","you","","you padlocked a door while playing hide-and-seek?","","","","","",""],
["","sean","","yeah, i wanted to make the game a little spicier, you know?","","","","","",""],
["","you","","...","","elijah_and_sean_together",['sean_hide_and_seek2a', 'sean_hide_and_seek3'],"","",""],
["sean_hide_and_seek2a","sean","","i mean, it worked, didn't it?","","","","","",""],
["","elijah",['elijah_neutral', 'sean_neutral'],"yes, because you locked natalie into the museum.","display_elijah_and_sean","","","","",""],
["","sean","","that's called strategy, baby!","","","","","",""],
["","","","...","","","","","",""],
["","","","you don't think she's still in there, do you?","","","","","",""],
["","elijah","","i'm sure she found another way out.","","","","","",""],
["","","","probably.","","","","","",""],
["","sean","","...","","","","","",""],
["","elijah","","...","","","sean_hide_and_seek4","","",""],
["sean_hide_and_seek3","sean","","i mean, it [i]worked[/i].","asked_sean_only","","","","",""],
["sean_hide_and_seek4","","","anyway, i wrote the code down on one of elijah's old poems!","asked_about_meowseum_door","","","","",""],
["","","","should be riiiiiight here","","","","","",""],
["","","","...","","","","","",""],
["","","","oh, shoot","","","","","",""],
["","you","","what is it?","","","","","",""],
["","sean","","must have fallen out of my pocket or something","","","","","",""],
["","","","not sure where i dropped it, maybe in the park when we went for a walk?","","got_meowseum_passcode",['sean_meowseum1b', 'sean_meowseum1a'],"","",""],
["sean_meowseum1a","you","","okay, i'll take a [i]lock[/i] around!","","","","","",""],
["","sean","","heh, thanks :P","","elijah_and_sean_together",['sean_meowseum1c', 'null'],"","",""],
["sean_meowseum1c","","","hey elijah! help me look around here.","","","","","",""],
["","elijah","","[i]sigh[/i]","","","","","",""],
["","","","why do i always end up cleaning up after your clever ideas?","","","","","",""],
["","sean","","that's what friends are for, baby!","","","null","","",""],
["sean_meowseum2","you","","any luck finding the passcode to the meowseum?","","","","","",""],
["","sean","","got nothing here, sorry","","elijah_and_sean_together",['sean_meowseum2b', 'sean_meowseum2a'],"","",""],
["sean_meowseum2a","you","","aw","","","","","",""],
["","sean","","i bet i dropped it in the park earlier","","","","","",""],
["","","","you should take a look around there","","","","","",""],
["","you","","kk, thanks","","","null","","",""],
["sean_meowseum2b","","","elijah?","","","","","",""],
["","elijah",['elijah_neutral', 'sean_neutral'],"nope, lady luck has not visited us today.","display_elijah_and_sean","","elijah_lady_luck","","",""],
["sean_meowseum3","you","","so, uh","","","","","",""],
["","","","i think i found the passcode to the meowseum","","","","","",""],
["","sean","","oh, for real?","","","","","",""],
["sean_is_it_1234","you","","is it 1234?","","","","","",""],
["","sean","","YEAH THAT'S IT!","","","","","",""],
["sean_ronnie_wood","sean","","i named it after my favorite ronnie wood album!","","","","","",""],
["","you","","...really?","","","","","",""],
["","sean","","man, how did i forget that?","","","","","",""],
["","","","haha","","elijah_and_sean_together",['sean_ronnie_wood2', 'null'],"","",""],
["sean_ronnie_wood2","elijah",['elijah_neutral', 'sean_neutral'],"you never fail to impress me, sean.","display_elijah_and_sean","","","","",""],
["","sean","","why, thank you!","","","","","",""],
["","","","i think.","told_code_to_sean","","null","","",""],
["sean_meowseum1b","you","","oh i think i saw it earlier!","","","sean_is_it_1234","","",""],
["sean_meowseum_catchup","you","","hey, elijah said you might know the passcode to the meowseum?",[['asked_elijah_only', false]],"","","","",""],
["","sean","","oh!","","","","","",""],
["","","","that old thing","","","","","",""],
["","","","uhh","","","","","",""],
["","","","damn, i don't remember","","","","","",""],
["","","","and i don't remember where i left the paper that i wrote it down on...","","","","","",""],
["","you","","aw, that's ok","","","","","",""],
["","sean","","i'll look around! i'm sure we'll stumble across it or something","","","","","",""],
["","you","","thx","","","null","","",""],
["sean_wasup1","sean","","i miss peeing sometimes","","","","","",""],
["","you","","you miss... peeing?","","","","","",""],
["","sean","","yeah, you don't need to pee in purrgatory","","","","","",""],
["","","","no matter how much orange soda you drink.","","","","","",""],
["","you","","that's interesting","","","","","",""],
["","","","but... what do you miss about peeing?","","","","","",""],
["","sean","","hmm...","","","","","",""],
["","","","nothing in particular","","","","","",""],
["","","","it's just one of those things you don't appreciate until it's gone, ya know?","","","","","",""],
["","you","","i mean, sure","","","null","","",""],
["sean_wasup2","sean","","cowabunga!","","","","","",""],
["","you","","huh?","","","null","","",""],
["","sean","","i'm trying to gain a reputation as \"the guy who says cowabunga\"","","","","","",""],
["","","","do you think it's working?","","","","","",""],
["","","","","","","","",['yes', 'no'],['sean_wasup2a', 'sean_wasup2b']],
["sean_wasup2a","you","","sure!","","","","","",""],
["","sean","","cowabunga!!!","","","null","","",""],
["sean_wasup2b","you","","um, i don't know","","","","","",""],
["","","","i don't think you can force something like that, it just sort of happens","","","","","",""],
["","sean","","cowabunga ):","","","null","","",""],
["sean_wasup3","sean","","so you don't remember your past life at all?","","","","","",""],
["","you","","not really","","","","","",""],
["","sean","","man","","","","","",""],
["","","","so you could have been, like, a movie star","","","","","",""],
["","","","or a champion hot dog eater","","","","","",""],
["","you","","anything's possible!","","","null","","",""],
["sean_wasup4","sean","","i hope kyungsoon's okay","","","","","",""],
["","you","","did something happen to her?","","","","","",""],
["","sean","","nah, i just haven't seen her in a while","","","","","",""],
["","","","what if she suffered some sort of tragic cat-related accident??","","","","","",""],
["","you","","you mean some sort of... [i]cat[/i]-astrophe?","","","","","",""],
["","sean","","...[i]sigh[/i]","","elijah_and_sean_together",['sean_wasup4a', 'null'],"","",""],
["sean_wasup4a","elijah",['elijah_neutral', 'sean_neutral'],"you walked right into that one.","display_elijah_and_sean","","","","",""],
["","sean","","yeah, i know.","","","null","","",""],
["sean_wasup5","sean","","cravin' some orange soda rn","","","","","",""],
["","you","","isn't there some by the piano?","","","","","",""],
["","sean","","yeah, but i'm trying to lay off of soda a little","","","","","",""],
["","","","not good for the bod, ya know?","","","","","",""],
["","you","","oh yeah i know","","","null","","",""],
["sean_wasup6","sean","","[i]burp[/i]","","","","","",""],
["","","","scuse me","","","","","",""],
["","you","","you're excused","","","null","","",""],
["sean_wasup7","sean","","any thoughts on croutons?","","","","","",""],
["","you","","they're... crunchy?","","","","","",""],
["","sean","","fuck, they sure are","","","null","","",""],
["sean_wasup8","sean","","got any tattoos?","","","","","",""],
["","","","","","","","",['nope', 'a few', 'a lot'],['sean_wasup8a', 'sean_wasup8b', 'sean_wasup8c']],
["sean_wasup8a","you","","nope","","","","","",""],
["","sean","","aw, u missed out","","","sean_wasup8d","","",""],
["sean_wasup8b","you","","yeah, a few","","","","","",""],
["","sean","","sick!","","","sean_wasup8d","","",""],
["sean_wasup8c","you","","oh you know it","","","","","",""],
["","","","i got tattoos for days","","","","","",""],
["","sean","","aw yeah, that's what i'm talkin' about dude!!","","","","","",""],
["sean_wasup8d","you","","what about you, do you have any?","","","","","",""],
["","sean","","yeah, just a few","","","","","",""],
["","","","this one's my favorite.","","","","","",""],
["","_none","","he shows you a stylized deer head on his bicep.","","","","","",""],
["","you","","ooh, a deer?","","","","","",""],
["","sean","","yeah, for my partner.","","","","","",""],
["","","","they got a snake in the same place.","","","","","",""],
["","you","","awwwwwwwwwwwwwww that's adorable","","","","","",""],
["","sean","","i know, right??","","","null","","",""],
["sean_wasup9","sean","","wonder how my budgies are doing","","","","","",""],
["","you","","oh, you had birds?","","","","","",""],
["","sean","","yeah, they were adorable little fuckers :P","","","null","","",""],
["sean_wasup10","sean","","still waiting to be reborn as a zombie in my hometown cemetery","","","","","",""],
["","you","","oh man, i wish","","","","","",""],
["","","","at least let us be ghosts or something","","","","","",""],
["","sean","","ikr?","","","","","",""],
["","","","i know some people i would haunt the FUCK out of","","","null","","",""],
["sean_wasup11","sean","","do you know the wonder years? the band?","","","","","",""],
["","you","","i don't think so?","","","","","",""],
["","sean","","dude they're spectacular","","","","","",""],
["","","","i was going to see them live the year i died :/","","","","","",""],
["","you","","aw","","","","","",""],
["","sean","","yeah it sucks","","","null","","",""],
["sean_wasup12","sean","","you ever listen to metallica?","","","","","",""],
["","you","","not much","","","","","",""],
["","sean","","good.","","","","","",""],
["","","","they're overrated","","","null","","",""],
["sean_wasup13","sean","","you know that song, i can't get no satisfaction?","","","","","",""],
["","you","","yeah?","","","","","",""],
["","sean","","what the hell was he talking about","","","","","",""],
["","you","","uh, idk","","","","","",""],
["","","","sex?","","","","","",""],
["","sean","","u think it's about sex?","","","","","",""],
["","you","","i don't know, i'm just spitballing here","","","","","",""],
["","sean","","no you might be onto something","","","","","",""],
["","","","i'll have to think about this...","","","null","","",""],
["sean_wasup14","sean","","i have dancing queen stuck in my head","","","","","",""],
["","you","","oh, that's a good one","","","","","",""],
["","sean","","young and sweet","","","","","",""],
["","","","only seventeen","","","","","",""],
["","you","","something something tambourine?","","","","","",""],
["","sean","","close enough","","","null","","",""],
["sean_wasup15","sean","","i got sweet dreams stuck in my head.","","","","","",""],
["","you","","sweet dreams are made of cheeeese","","","","","",""],
["","sean","","you mean these?","","","","","",""],
["","you","","huh?","","","","","",""],
["","sean","","sweet dreams are made of these","","","","","",""],
["","","","right?","","elijah_and_sean_together",['sean_wasup15a', 'sean_wasup15b'],"","",""],
["sean_wasup15a","elijah",['elijah_neutral', 'sean_neutral'],"i thought it was \"sweet dreams are made of [i]this[/i]\"","display_elijah_and_sean","","","","",""],
["","sean","","no way","","","","","",""],
["","","","it's definitely these","","","","","",""],
["","elijah","","mmm that's not how i remember it","","","","","",""],
["","you","","i always thought it was cheese...","","","","","",""],
["","","","everything makes so much sense now","","","null","","",""],
["sean_wasup15b","you","","damn","","","","","",""],
["","","","i always thought it was cheese...","","","","","",""],
["","","","everything makes so much sense now","","","null","","",""],
["sean_wasup16","sean","","stairway to heaven is stuck in my head","","","","","",""],
["","you","","that's a good song!","","","","","",""],
["","sean","","i disagree","","","","","",""],
["","","","i've tried every staircase in purrgatory and none of them lead to heaven.","","","","","",""],
["","you","","lol","","","","","",""],
["","sean","","don't even get me [i]started[/i] on highway to hell!","","","null","","",""],
["sean_wasup17","sean","","[i]sigh[/i]","","","","","",""],
["","","","bruno mars is stuck in my head again","","","","","",""],
["","you","","what's wrong with bruno mars?","","","","","",""],
["","sean","","nothing!","","","","","",""],
["","","","i just don't want him in my head!!!","","","","","",""],
["","you","","oh","","","","","",""],
["","sean","","of all the things i like inside of me, bruno mars is not one of them.","","","","","",""],
["","you","","could you... phrase that differently?","","","","","",""],
["","sean","","i cannot","","","null","","",""],
["sean_wasup18","sean","","you ever wish you'd died in a different set of clothes?","","","","","",""],
["","you","","uh, not really","","","","","",""],
["","sean","","i mean, these shorts are great and all","","","","","",""],
["","","","but i wish i died in my pajamas.","","","","","",""],
["","","","if i'm gonna be here for eternity i might as well be comfortable.","","","null","","",""],
["sean_wasup19","sean","","do you know that song that goes like","","","","","",""],
["","","","doo doo doo, doo doo doo doo doo?","","","","","",""],
["","you","","uhhhhh","","","","","",""],
["","","","sing it again?","","","","","",""],
["","sean","","it's like doo doo doo, doo doo doo doo doo","","","","","",""],
["","you","","ummm i don't think so","","","","","",""],
["","sean","","damn","","","","","",""],
["","","","this is going to haunt me forever","","","null","","",""],
["sean_wasup20","sean","","i have megalovania stuck in my head","","","","","",""],
["","you","","oh, cool","","","","","",""],
["","","","...","","","","","",""],
["","","","now [i]i[/i] have megalovania stuck in my head","","","","","",""],
["","sean","","whoops","","","null","","",""],
["sean_snakey_boy","you","sean_neutral","looking good, snakey boy (;","","_pronouns_they or _pronouns_he",['sean_snakey_boy4', 'sean_snakey_boy1'],"","",""],
["sean_snakey_boy1","sean","","thanks!","","","","","",""],
["","you","","why don't we get to know each other a little better (;;;","","","","","",""],
["","sean","","oh","","","","","",""],
["","","","no thanks","","","","","",""],
["","","","","","","","",['you know u wanna (;;;;;;;', 'okay'],['sean_snakey_boy2', 'sean_snakey_boy3']],
["sean_snakey_boy2","you","","you know you wanna (;;;;;;;","","","","","",""],
["","sean","","uhh","","","","","",""],
["","","","don't, like, take this the wrong way, dude, but","","","","","",""],
["","","","you're not really... my type","","","","","",""],
["","you","","oh","","","","","",""],
["","sean","","because","","","","","",""],
["","","","i am gay","","","","","",""],
["","you","","ohhh","","","","","",""],
["","","","my bad","","","","","",""],
["","sean","","it's ok!","","","null","","",""],
["sean_snakey_boy3","you","","ah, okay","","","","","",""],
["","sean","","nothing pers!","","","null","","",""],
["sean_snakey_boy4","sean","","speak for yourself, cutie (;;","","","","","",""],
["","you","","why don't we get to know each other a little better (;;;","","elijah_and_sean_together",['sean_snakey_boy5', 'sean_snakey_boy6'],"","",""],
["sean_snakey_boy5","elijah",['elijah_neutral', 'sean_neutral'],"is all the winking really necessary?","display_elijah_and_sean","","","","",""],
["","sean","","elijah! ","","","","","",""],
["","","","we're having a moment here!","","","","","",""],
["","elijah","","unfortunately, i am a part of said moment.","","","","","",""],
["","","","by sheer proximity.","","","","","",""],
["","sean","","ah, i'm not really in the mood, anyway.","","","sean_snakey_boy7","","",""],
["sean_snakey_boy6","sean","","ah, i'm not really in the mood, sorry.","","","","","",""],
["sean_snakey_boy7","","","rain check? :P","","","","","",""],
["","you","","ugh, fiiiiine","","","null","","",""],
["sean_for_fun","you","sean_neutral","so, what do you do for fun around here?","","","","","",""],
["","sean","","oh, ya know","","","","","",""],
["","","","watch paint dry. watch grass grow.","","","","","",""],
["","","","pester elijah.","","elijah_and_sean_together",['sean_for_fun1', 'sean_for_fun2'],"","",""],
["sean_for_fun1","elijah",['elijah_neutral', 'sean_neutral'],"[i]sigh[/i]","display_elijah_and_sean","","","","",""],
["sean_for_fun2","sean","","it's boring as hell, to be honest.","","","","","",""],
["","","","","","","","",['what are your interests?', 'what did you do for fun in real life?'],['sean_hobbies', 'sean_real_life']],
["sean_hobbies","you","sean_neutral","well, what are your interests?","display_sean","","","","",""],
["","sean","","i'm really into music! used to work at a record store.","","","","","",""],
["","you","","what kind of music?","","","","","",""],
["","sean","","oh ya know, uhhhh, punk rock, alt rock, hardcore, metal...","","","","","",""],
["","you","","that's--","","","","","",""],
["","sean","","and shoegaze","","","","","",""],
["","you","","that's a lot of--","","","","","",""],
["","sean","","and drum and bass","","","","","",""],
["","you","","...","","","","","",""],
["","sean","","and uk garage, psytrance, prog trance, and 80's pop","","","","","",""],
["","","","you know, stuff like that.","","","","","",""],
["","you","","that's a lot of music!","","","","","",""],
["","sean","","yeah i got around :P","","","","","",""],
["","","","my partner likes classical, so they were starting to get me into that too.","","","","","",""],
["","","","very, very gradually.","","","","","",""],
["","","","never thought i would enjoy music written before 1900, but here we are.","","","","","",""],
["","you","","it's good to have an open mind about that kind of thing!","","","null","","",""],
["sean_real_life","you","sean_neutral","well, what did you do for fun in real life?","display_sean","","","","",""],
["","sean","","hmm, guess i went out a lot","","","","","",""],
["","","","gotta live it up while you're still young, right? :P","","","","","",""],
["","you","","lol yeah","","","","","",""],
["","sean","","young [i]and[/i] alive","","","","","",""],
["","you","","yep","","","","","",""],
["","sean","","also taught myself how to play guitar. was working on drums too when i died.","","","","","",""],
["","you","","cool!","","elijah_and_sean_together",['sean_real_life1', 'null'],"","",""],
["sean_real_life1","elijah",['elijah_neutral', 'sean_neutral'],"yes, sean has always had a propensity for making noise.","display_elijah_and_sean","","null","","",""],
["sean_purrgatory","you","","anything you can tell me about this place?","","","","","",""],
["","sean","","you mean purrgatory?","","","","","",""],
["","","","i dunno, i think it's pretty self-explanatory","","","","","",""],
["","","","something specific you wanna know?","","","","","",""],
["","","","","","","","",['how do you get out?', 'any places i should check out?', 'any people i should meet?'],['sean_get_out', 'sean_places', 'sean_people']],
["sean_get_out","you","","i guess, how do you get out of here?","","","","","",""],
["","sean","","beats me, dude","","","","","",""],
["","","","never seen anybody leave before.","","","","","",""],
["","you","","oh","","","","","",""],
["","","","do you have any, like... clues?","","","","","",""],
["","sean","","tell you what, next time i run into god, i'll pass on your question :P","","","","","",""],
["","you","","heh thanks","","elijah_and_sean_together",['sean_get_out1', 'null'],"","",""],
["sean_get_out1","elijah",['elijah_neutral', 'sean_neutral'],"you should ask tori, if you run into her.","display_elijah_and_sean","","","","",""],
["","","","she's always working on a new escape plan or something.","","","","","",""],
["","you","","oh, alright","","","null","","",""],
["sean_places","you","","any places i should check out?","","","","","",""],
["","sean","","in... purrgatory?","","","","","",""],
["","","","i don't know, it's not exactly a scenic route","","","","","",""],
["","","","the keyboard's pretty cool, i guess","","","","","",""],
["","you","","alright, i'll [i]key[/i]-p that in mind!","","","","","",""],
["","sean","","lol","","elijah_and_sean_together",['sean_places1', 'sean_places2'],"","",""],
["sean_places1","elijah",['elijah_neutral', 'sean_neutral'],"the park's a nice place to hang out too.","display_elijah_and_sean","","","","",""],
["","","","it's pretty cozy, once you get over the fact that the river is made of milk.","","","","","",""],
["sean_people","you","","any people i should meet?","","","","","",""],
["","sean","","well, i'm sure you'll meet all of us before long...","","","","","",""],
["","","","oh!","","","","","",""],
["","","","have you met natalie yet?","","met_natalie",['sean_people1', 'sean_people2'],"","",""],
["sean_people1","you","","yeah i've met natalie!","","","","","",""],
["","sean","","isn't she a riot?","","","","","",""],
["","you","","yeah she's a lot of [i]pun[/i] to be around!","","","","","",""],
["","sean","","oh man","","","","","",""],
["","","","you two are perfect for each other","","","null","","",""],
["sean_people2","you","","i don't think so?","","","","","",""],
["","sean","","oh man","","","","","",""],
["","","","you like puns, right?","","","","","",""],
["","","","","","","","",['yes', 'duh', 'obviously'],['sean_people2a', 'sean_people2b', 'sean_people2c']],
["sean_people2a","you","","yep","","","sean_people3","","",""],
["sean_people2b","you","","duh","","","sean_people3","","",""],
["sean_people2c","you","","obviously","","","","","",""],
["sean_people3","sean","","then you two are gonna get along great :P","","","","","",""],
["","you","","i'm o-[i]pun[/i] to the possibility!","","","null","","",""],
["sean_spat","sean","sean_neutral","hey, dude, sorry about earlier with elijah","sean_moved_on_from_argument","","","","",""],
["","","","didn't mean to get you caught up in all that","","","","","",""],
["","you","","that's ok!!","","","","","",""],
["","","","do you want to talk about it?","","","","","",""],
["","sean","","ah, don't worry about it","","","","","",""],
["","","","it's no bigs","","","","","",""],
["","you","","it seemed maybe a little bigs...?","","","","","",""],
["","sean","","like medium size?","","","","","",""],
["","you","","yeah like a medium fries and coke?","","","","","",""],
["","","","if you don't wanna talk about it, it's cool","","","","","",""],
["","sean","","nah it's ok","","","","","",""],
["","","","i just get caught up in my head sometimes","","","","","",""],
["","","","like i think","","","","","",""],
["","","","what if i had gone to college? or like, what if i had joined a band?","","","","","",""],
["","","","done something productive, ya know.","","","","","",""],
["","","","hell what if i had run for president??","","","","","",""],
["","you","","i don't know if i would have wanted to live in that country","","","","","",""],
["","sean","","LOL ","","","","","",""],
["","","","fair :P","","","","","",""],
["","","","anyway yeah, it's no bigs, like i said.","","","","","",""],
["","you","","i see","","","","","",""],
["","sean","","...","","","","","",""],
["","","","plus he didn't have to bring up dani.","","","","","",""],
["","","","ya know what i mean?","","","","","",""],
["","","","","","","","",['touchy subject?', 'i\'m sorry'],['sean_spat1', 'sean_spat2']],
["sean_spat1","you","","touchy subject?","","","","","",""],
["","sean","","no, it's not a [i]touchy subject[/i]","","","","","",""],
["","you","","oh, sorry","","","","","",""],
["","sean","","i mean","","","","","",""],
["","","","it's not","","","","","",""],
["","","","listen, i'll talk about dani all day if you let me!!","","","","","",""],
["","","","but when [i]he[/i] says it, it's","","","","","",""],
["","","","like","","","","","",""],
["","","","you know what, never mind","","","sean_spat3","","",""],
["sean_spat2","you","","i'm sorry","","","","","",""],
["","","","you must miss them","","","","","",""],
["","sean","","whatever, dude","","","","","",""],
["sean_spat3","","","enough sappy shit","","","","","",""],
["","","","wanna play some music??","","","","","",""],
["","you","","on the piano?","","","","","",""],
["","sean","","yep!","","","","","",""],
["","","","","","","","",['sure!', 'i don\'t know how to play...', 'maybe later'],['sean_spat4', 'sean_spat5', 'sean_spat6']],
["sean_spat4","you","","hmm, sure!","","","sean_jam","","",""],
["sean_spat5","you","","oh, i don't know how to play...","","","","","",""],
["","sean","","me neither!!","","","","","",""],
["","","","but dani taught me some basics, so i can show you too","","","","","",""],
["","","","what do you say?","","","","",['sure!', 'maybe later'],['sean_spat4', 'sean_spat6']],
["sean_spat6","you","","maybe in a bit","","","","","",""],
["","","","i got some other stuff to do","","","","","",""],
["","sean","","alright, no probs","","","","","",""],
["","","","the jam session can wait :P","","","null","","",""],
["sean_jam","_none","_none","_pass","",['not sean_out_of_batteries', '_inv_battery1 and _inv_battery2', '_inv_scissor1 or _inv_battery2'],['sean_jam0', 'sean_jam_c', 'sean_jam_b', 'sean_jam_a'],"","",""],
["sean_jam0","you","","let's jam!","","","","","",""],
["","sean","","alright!!!!","","","","","",""],
["","_none","","sean presses a bunch of keys at once, but nothing happens.","","","","","",""],
["","sean","","...","","","","","",""],
["","you","","it didn't make any noise","","","","","",""],
["","sean","","yeah i know","","","","","",""],
["","","","hold on","","","","","",""],
["","you","","did u turn it on","","","","","",""],
["","sean","","yeah i turned it on","","","","","",""],
["","","","...","","","","","",""],
["","","","damn","","","","","",""],
["","","","it must be out of battery","","","","","",""],
["","","","AGAIN","","","","","",""],
["","you","","awww man","","","","","",""],
["","sean","","maaaaaaaaaaan ):<","","","","","",""],
["","","","we need to find two double-a batteries","","","","","",""],
["","","","cus otherwise we are prohibited from jamming","","","","","",""],
["","you","","banned from the jam","","","","","",""],
["","sean","","exactly","","","","","",""],
["","you","","well, i'll see if i find some...","sean_out_of_batteries","","null","","",""],
["sean_jam_a","you","","did you find any batteries?","","","","","",""],
["","sean","","nope","","","","","",""],
["","","","but also i haven't left this room","","","","","",""],
["","you","","uh... why not?","","","","","",""],
["","sean","","because i'm lazy","","","","","",""],
["","you","","that's fair","","","null","","",""],
["sean_jam_b","you","","i found a battery!","","","","","",""],
["","sean","","great!","","","","","",""],
["","","","just one more and we can jaaaaaaaam","","","","","",""],
["","you","","question","","","","","",""],
["","","","why am i doing all the searching?","","","","","",""],
["","sean","","because i'm lazy","","","","","",""],
["","you","","that's fair","","","null","","",""],
["sean_jam_c","you","","i got two batteries!!","","","","","",""],
["","sean","","YES!!!","","","","","",""],
["","","","oh my GOD i've been waiting to jam for so long","","","","","",""],
["","you","","wait no longer!!","","","","","",""],
["","sean","","i literally cannot wait a single more second","","","","","",""],
["","","","gimme those batteries","sean_replaced_batteries","","piano_intro","","",""],
["sean_post_jam","sean",['sean_neutral', 'tori_neutral'],"oh. hey, tori","custom_goto_piano2","met_tori",['sean_post_jam1', 'sean_post_jam2'],"","",""],
["sean_post_jam1","tori","","{player}, good to see you again.","","","","","",""],
["","","","sean, how many times do i have to tell you, [i]some[/i] people are trying to work around here.","","","","","",""],
["","sean","","work on what??","","","","","",""],
["","","","we're LITERALLY dead","","","","","",""],
["","tori","","on important things!","","","","","",""],
["","","","important purrgatory work.","","","","","",""],
["","sean","","preening your feathers is [i]not[/i] important work.","","","","","",""],
["","tori","","listen, just try to keep it down.","","","sean_post_jam3","","",""],
["sean_post_jam2","tori","","sean, how many times do i have to tell you, [i]some[/i] people are trying to work around here.","","","","","",""],
["","","","oh, who's this?","","","","","",""],
["","you","","i'm {player}","","","","","",""],
["","tori","","hmm, interesting.","","","","","",""],
["","","","i've been expecting you.","","","","","",""],
["","sean","","that's not ominous at all","","","","","",""],
["","tori","","it's not ominous! just a fact!","","","","","",""],
["","","","i'm tori. i look forward to getting to know you better.","","","","","",""],
["","","","","","","","",['same here', 'that still sounds ominous', 'cool'],['sean_post_jam2a', 'sean_post_jam2b', 'sean_post_jam2c']],
["sean_post_jam2a","you","","um, same here!","","","","","",""],
["","sean","","it's not a business meeting, guys","","","","","",""],
["","tori","","you ever heard of being polite, sean?","","","sean_post_jam2d","","",""],
["sean_post_jam2b","you","","that still sounds kind of ominous...","","","","","",""],
["","_none","","tori rolls her eyes.","","","","","",""],
["","tori","","fine, you got me, i'm trying to lure you into my lair so i can eat you whole.","","","","","",""],
["","sean","","i KNEW it!","","","sean_post_jam2d","","",""],
["sean_post_jam2c","you","","cool","","","","","",""],
["","tori","","cool?","","","","","",""],
["","you","","yeah that's cool","","","","","",""],
["","tori","","cool","","","","","",""],
["sean_post_jam2d","tori","","anyway, i'll let you get back to your \"jam session.\"","","","","","",""],
["","","","just please try to keep it down.","","","","","",""],
["sean_post_jam3","","","no offense, but a choir of meows is not exactly angelic.","","","","","",""],
["","sean","","yeah, yeah, whatever","","","","","",""],
["","you","","sorry if we BOARD you","","","","","",""],
["","","","...like a keyBOARD","","","","","",""],
["","tori","","hah.","","","","","",""],
["","_none",['sean_neutral'],"tori walks back up the stairs.","","","","","",""],
["","sean","","pbbbbt","","","","","",""],
["","","","sorry about that, tori's a real downer","","","","","",""],
["","you","","it's ok!","","","","","",""],
["","","","i think she's alright","","","","","",""],
["","sean","","heh, that's very magna... magnamious of you","","","","","",""],
["","you","","huh?","","","","","",""],
["","sean","","magnami...nous?","","","","","",""],
["","","","i don't know, it's a word elijah taught me","","","","","",""],
["","you","","oh lol","","","","","",""],
["","sean","","yeah lol","","","","","",""],
["","","","did you know he writes poems about me??","","","","","",""],
["","you","","really?","","","","","",""],
["","","","like love poems?","","","","","",""],
["","sean","","LOL no","","","","","",""],
["","","","he's straight as a stick, dude","","","","","",""],
["","","","it's probably just something dumb","","","","","",""],
["","","","he refuses to admit it but i swear he let it slip a while ago and, like","","","","","",""],
["","","","it's been bothering me, ya know?","","","","","",""],
["","you","","i'm sure it's something nice!!","","","","","",""],
["","sean","","don't believe it","","","","","",""],
["","","","i think he writes only depressing poems","","","","","",""],
["","","","not that he lets me read any of them...","","","","","",""],
["","you","","hmm","","","","","",""],
["","","","what if i...","","","","","",""],
["","","","","","","","",['secretly read his poems and found out?', 'asked him nicely if i can read more poems?'],['sean_annoying5', 'sean_annoying6']],
["sean_annoying5","you","","secretly read his poems and found out?","","","","","",""],
["","sean","","really?","","","","","",""],
["","","","you would do that?","","","","","",""],
["","you","","yeah, like, maybe while he's asleep or something i can sneak a look","","","","","",""],
["","","","i'm kinda curious too","","","","","",""],
["","sean","","ohohoh, i like how you think ;)","","","","","",""],
["","","","not that i'm","","","","","",""],
["","","","encouraging you to invade elijah's privacy or anything","","","","","",""],
["","","","obviously that would be an immoral thing to do","","","","","",""],
["","","","[i]cough cough[/i]","","","","","",""],
["","you","","hehe i get you","","","","","",""],
["","sean","","for real though, be careful though, ok?","","","","","",""],
["","","","don't get in trouble for my sake","","","","","",""],
["","you","","don't worry, i'll be fine","","","sean_annoying7","","",""],
["sean_annoying6","you","","asked him nicely if i can read more poems?","","","","","",""],
["","sean","","really?","","","","","",""],
["","","","i meeeeean, i guess that would be cool","","","","","",""],
["","","","i am pretty freaking curious","","","","","",""],
["","you","","me too, tbh","","","","","",""],
["","sean","","up to you, ok?","","","","","",""],
["","","","you really don't have to do anything for my sake","","","","","",""],
["","you","","i gotcha","","","","","",""],
["sean_annoying7","sean","","listen, sorry for dumping so much shit on you","","","","","",""],
["","","","thanks for helping me take my mind off things!","","","","","",""],
["","you","","yeah no worries, it was fun!!","","","","","",""],
["","sean","","wish i had my guitar so i could play some proper music","","","","","",""],
["","","","but u know, i'll take what i can get","","","","","",""],
["","you","","mhm.","","","","","",""],
["","sean","","let's jam some other time, ok?","","","","","",""],
["","you","","kk","","","null","","",""],
["sean_snoop","_none","_none","_pass","","read_elijahs_poems",['sean_snoop_after', 'sean_snoop_before'],"","",""],
["sean_snoop_before","you","","uh, you wanted me to find out what elijah is writing about you, right?","","","","","",""],
["","sean","","yeah dude i'm HELLA curious","","","","","",""],
["","","","curious to the MAX","","","","","",""],
["","","","but like... don't do anything dumb on my behalf ok?","","","","","",""],
["","you","","lol, don't worry","","","","","",""],
["","sean","","I'M the only one who should be doing dumb things around here!","","","null","","",""],
["sean_snoop_after","you","","guess who read some poems!!","","","","","",""],
["","sean","","no way!!","","","","","",""],
["","","","how did u convince him?","","","","","",""],
["","","","wait, it doesn't matter","","","","","",""],
["","","","what was he writing about me?","","","","","",""],
["","you","","umm","","","","","",""],
["","","","well","","","","","",""],
["","","","","","","","",['nothing', 'that ur handsome and funny'],['sean_snoop1', 'sean_snoop2']],
["sean_snoop1","you","","nothing","","","","","",""],
["","sean","","really?","","","sean_snoop3","","",""],
["sean_snoop2","you","","that you're really handsome and funny!!","","","","","",""],
["","sean","","pfft, yeah right.","","","","","",""],
["","","","wait","","","","","",""],
["","","","are you serious?","","","","","",""],
["","you","","umm","","","","","",""],
["","","","no, sorry","","","sean_snoop3","","",""],
["sean_snoop3","you","","i didn't find any mention of you at all...","","","","","",""],
["","sean","","damn","","","","","",""],
["","","","i guess i should be relieved","","","","","",""],
["","","","but now i feel kind of disappointed","","","","","",""],
["","you","","aw, i'm sorry","","","","","",""],
["","sean","","it's okay!","","","","","",""],
["","","","you see normally people can't resist writing poems about me","","","","","",""],
["","","","i just naturally attract people's attention :3","","","","","",""],
["","you","","lol","","","","","",""],
["","sean","","...","","","","","",""],
["","","","HEY uhhhh","","","","","",""],
["","","","so this might be kind of random but","","","","","",""],
["","","","do you think i'm annoying?","","","","","",""],
["","","","","","","","",['no!', 'maybe a little', 'what do you mean?'],['sean_annoying1', 'sean_annoying2', 'sean_annoying3']],
["sean_annoying1","you","","no, of course not!","","","","","",""],
["","sean","","like really?","","","","","",""],
["","","","you can be honest, i have thick scales :P","","","","","",""],
["","you","","you're not annoying!!","","","","","",""],
["","","","i promise","","","","","",""],
["","sean","","ok, good","","","sean_annoying4","","",""],
["sean_annoying2","you","","well... maybe, a little","","","","","",""],
["","","","sorry","","","","","",""],
["","sean","","ahhh, well","","","","","",""],
["","","","what else is new","","","","","",""],
["","you","","but you're fun to hang out with!!","","","","","",""],
["","sean","","thanks dude","","","sean_annoying4","","",""],
["sean_annoying3","you","","what do you mean?","","","","","",""],
["","sean","","umm idk","","","","","",""],
["sean_annoying4","sean","","sorry that question probably sounded hella needy","","","","","",""],
["","","","it's just that i've been worrying lately that maybe i'm annoying elijah or something","","","","","",""],
["","","","he seems like...","","","","","",""],
["","","","cranky?","","","","","",""],
["","","","more than usual?","","","","","",""],
["","you","","maybe he's just having a bad day?","","","","","",""],
["","","","i guess when i talked to him earlier he did seem kind of...","","","","","",""],
["","","","blue","","","","","",""],
["","sean","","ugh","","","","","",""],
["","","","i've been trying to cheer him up, you know","","","","","",""],
["","","","feel like he could use the companionship","","","","","",""],
["","","","but maybe i'm just making it worse","","","","","",""],
["","you","","mm...","","","","","",""],
["","sean","","things just haven't been the same since i died, man","","","","","",""],
["","","","i used to be GREAT at cheering people up!","","","","","",""],
["","you","","i feel that","","","","","",""],
["","","","i don't even know what i was like before i died","","","","","",""],
["","sean","","still don't remember anything?","","","","","",""],
["","you","","it's coming back in bits and pieces","","","","","",""],
["","","","but... yeah, not much","","","","","",""],
["","sean","","man, you're lucky","","","","","",""],
["","","","in a way","","","","","",""],
["","you","","really??","","","","","",""],
["","sean","","well, at least you don't remember the things that...","","","","","",""],
["","","","you know, like all the things you miss","","","","","",""],
["","","","iuno dude iuno what i'm saying lol","","","","","",""],
["","you","","i mean that's true","","","","","",""],
["","sean","","i think it's being cooped up inside that's messing with my head","","","","","",""],
["","","","i need some fresh air, man!","","","","","",""],
["","","","dani was always the stay-at-home type, i don't know how they could stand it","","","","","",""],
["","","","","","","","",['me too', 'i think i\'m more the going out type'],['sean_dani1', 'sean_dani2']],
["sean_dani1","you","","me too!","","","","","",""],
["","sean","","man, freaking introverts","","","","","",""],
["","","","bet purrgatory's a slice of heaven for you, huh? :P","","","","","",""],
["","you","","idk i prefer my heaven with less stairs","","","","","",""],
["","sean","","LOL","","","sean_dani3","","",""],
["sean_dani2","you","","i think i'm more of the going out type","","","","","",""],
["","sean","","so you get me dude!!","","","","","",""],
["sean_dani3","sean","","man it's so ironic","","","","","",""],
["","","","the reason i died was because i went on a walk to get some fresh air","","","","","",""],
["","","","maybe buy an energy drink or somethin, ya feel?","","","","","",""],
["","you","","i see","","","","","",""],
["","sean","","ugh, dani told me not to go out, too","","","","","",""],
["","","","said it was too cold","","","","","",""],
["","","","you know i can still hear the song they were playing at the corner store? when i died?","","","","","",""],
["","","","it's funny","","","","","",""],
["","","","keeps getting stuck on my head","","","","","",""],
["","","","drives me crazy","","","","","",""],
["","","","it's actually not funny at all, i don't know why i said that","","","","","",""],
["","you","","oh","","","","","",""],
["","sean","","worst part is dani didn't know","","","","","",""],
["","","","that i died, i mean","","","","","",""],
["","","","i mean i guess they found out eventually","","","","","",""],
["","","","police probably showed up at our door or something","","","","","",""],
["","","","but like","","","","","",""],
["","","","imagine how that feels?","","","","","",""],
["","","","just like","","","","","",""],
["","","","waiting longer and longer","","","","","",""],
["","","","but the person you're waiting for never comes back","","","","","",""],
["","","","","","","","",['i\'m sorry', 'you must miss them', '...'],['sean_dani4', 'sean_dani5', 'sean_dani6']],
["sean_dani4","you","","i'm sorry","","","","","",""],
["","sean","","[i]sniff[/i]","","","","","",""],
["","","","thanks man","","","sean_dani7","","",""],
["sean_dani5","you","","you must miss them","","","","","",""],
["","sean","","[i]sniff[/i]","","","","","",""],
["","","","yeah man","","","","","",""],
["","","","i miss them so much","","","","","",""],
["","you","","):","","","sean_dani7","","",""],
["sean_dani6","you","","...","","","","","",""],
["sean_dani7","sean","","we were just starting our new life together","","","","","",""],
["","","","new apartment and everything","","","","","",""],
["","","","i wish i could just get over it and move on with my afterlife, but...","","","","","",""],
["","","","it's so hard dude","","","","","",""],
["","","","everything feels pointless sometimes","","","","","",""],
["","","","i'm gonna be hearing that stupid corner store music forever","","","","","",""],
["","","","and there's nothing i can do about it","","","","","",""],
["","","","","","","","",['healing takes time dude', 'you could always try drowning it out', '...'],['sean_heal1', 'sean_heal2', 'sean_heal3']],
["sean_heal1","you","","healing takes time dude, but things will get better eventually","","","","","",""],
["","","","there's no rush","","","","","",""],
["","","","just be patient, and try not to beat yourself up about it","","","","","",""],
["","sean","","...","","","","","",""],
["","","","guess you're right","","","","","",""],
["","you","","maybe it's a good thing we're in purrgatory!","","","","","",""],
["","","","you can take all the time you need","","","","","",""],
["","sean","","hah","","","","","",""],
["","","","of course you'd find the silver lining in purrgatory","","","","","",""],
["","you","","i try","","","sean_heal4","","",""],
["sean_heal2","you","","you could always try drowning it out with more music","","","","","",""],
["","","","well, as long as tori's not around","","","","","",""],
["","sean","","heh, that might work","","","","","",""],
["","","","i did always want to be a songwriter","","","","","",""],
["","","","i might be late to the party, but...","","","","","",""],
["","","","better late than never?","","","","","",""],
["","you","","that's the spirit!!","","","sean_heal4","","",""],
["sean_heal3","you","","...","","","","","",""],
["sean_heal4","sean","","you know what?","","","","","",""],
["","","","i'm done moping around ","","","","","",""],
["","","","well","","","","","",""],
["","","","for now.","","","","","",""],
["","","","i should go check up on elijah","","","","","",""],
["","","","but ummm","","","","","",""],
["","","","thanks for listening dude","","","","","",""],
["","","","i really needed that ","","","","","",""],
["","you","","you're welcome!!","","","","","",""],
["","sean","","elijah's still in the study, right?","","","","","",""],
["","you","","oh, actually, he said he was going for a walk.","","","","","",""],
["","sean","","a walk? really?","","","","","",""],
["","","","he never goes for walks.","","","","","",""],
["","you","","huh, that's weird.","","","","","",""],
["","sean","","actually, i wonder if...","","","","","",""],
["","","","well, no, probably not.","","","","","",""],
["","","","well, i guess better safe than sorry...?","","","","","",""],
["","you","","?","","","","","",""],
["","sean","","uhh, {player}, do you know how elijah died?","","","","","",""],
["","","","","","","","",['no', 'yes'],['sean_worry1', 'sean_worry2']],
["sean_worry1","you","","no...?","","","","","",""],
["","sean","","well","","","","","",""],
["","","","it's probably not my place to say","","","","","",""],
["","","","but ummmm damn","","","sean_worry3","","",""],
["sean_worry2","you","","i think so","","","","","",""],
["","sean","","ok, so you probably understand why i'm uh","","","","","",""],
["","","","well not [i]worried[/i] exactly","","","","","",""],
["","","","i don't think he'd do it [i]again[/i], i just","","","","","",""],
["","","","wanna make sure he's okay, i guess?","","","","","",""],
["sean_worry3","","","i'm gonna go look for him","","","","","",""],
["","","","if you run into him first, do me a favor and just, like, keep him company, okay?","","","","","",""],
["","you","","okay...","","","","","",""],
["","sean","","i don't want to spook you or anything!","","","","","",""],
["","","","he's probably fine","","","","","",""],
["","","","just, you know.","","","","","",""],
["","","","yeah","","","","","",""],
["","","","ok bye!","","","","","",""],
["","you","","cya","sean_looking_for_elijah","","null","","",""],
["sean_post_quest","_none","_none","_pass","","sean_heard_blues",['sean_default_b', 'sean_post_quest_a'],"","",""],
["sean_post_quest_a","sean","sean_neutral","yo {player}!","sean_heard_blues","","","","",""],
["","you","","yo!","","","","","",""],
["","","","how are things with elijah?","","","","","",""],
["","sean","","oh fantastic dude","","","","","",""],
["","","","fan freaking tastic","","","","","",""],
["","","","did that sound sarcastic? that was sincere","","","","","",""],
["","you","","nah it didn't sound sarcastic","","","","","",""],
["","","","how come you two aren't hanging out?","","","","","",""],
["","sean","","elijah said he didn't want to stay in the study all day anymore","","","","","",""],
["","","","so he's in the garden helping numa instead","","","","","",""],
["","","","besides, i'm busy dude!","","","","","",""],
["","","","busy chasin my dreams!!","","","","","",""],
["","you","","i guess you finally cut to the [i]chase[/i]? ","","","","","",""],
["","","","and [i]chased[/i] your dreams?","","","","","",""],
["","sean","","haha yeah dude","","","","","",""],
["","","","i'm writing a song!!","","","","","",""],
["","you","","no way that's awesome!!","","","","","",""],
["","sean","","it's soooo groovy","","","","","",""],
["","","","here, listen to this","","","","","",""],
["","","","ahem","","","","","",""],
["","","","[i]i'm stuck in purrgatory too[/i]","","","","","",""],
["","","","[i]it's just not the same without you, boo~[/i]","","","","","",""],
["","","","[i]think i'll take a purrgatory snooze[/i]","","","","","",""],
["","","","[i]and maybe i'll wake up next to you~[/i]","","","","","",""],
["","","","what do you think?","","","","","",""],
["","","","","","","","",['it\'s groovy', 'it\'s funky', 'it\'s radical'],['sean_post_quest1', 'sean_post_quest1', 'sean_post_quest1']],
["sean_post_quest1","you","","i think it's really good!","","","","","",""],
["","sean","","i'm going for a kind of bluesy vibe","","","","","",""],
["","","","though that's kind of hard with--","","","","","",""],
["","tori",['sean_neutral', 'tori_neutral'],"SEAN!","","","","","",""],
["","sean","","oh not this again","","","","","",""],
["","tori","","how many times do i have to tell you--","","","","","",""],
["","sean","","i had it on quiet, i swear! i just turned it up so i could show {player}--","","","","","",""],
["","tori","","some people are trying to WORK around here--","","","","","",""],
["","sean","","well some people are trying to UNLOCK THEIR TRUE POTENTIAL","","","","","",""],
["","_none","","...you think maybe you should let them work it out.","sean_arguing_with_tori","","null","","",""],
["sean_arguing_with_tori","sean",['sean_neutral', 'tori_neutral'],"how come you're the only one that ever complains about me playing the piano?","","","","","",""],
["","","","do owls even have ears??","","","","","",""],
["","tori","","do snakes even have hands???","","","null","","",""],
["sean_default_b","sean","sean_neutral","what's up dude!","","","","","",""],
["","","","","","","","",['what\'s up?', 'how\'s the song going?', '(ask about...)'],['sean_wasup', 'sean_blues', 'sean_ask_about']],
["sean_blues","you","","how's the music going?","","","","","",""],
["","sean","","it's rockin' dude","","","","","",""],
["","","","i'll make sure to show you when i'm done","","","","","",""],
["","you","","alright!","","","","","",""],
["","sean","","hell maybe i'll hold a concert!!!","","","","","",""],
["","you","","hey that would be sick!","","","","","",""],
["","sean","","invite elijah and natalie and everyone","","","","","",""],
["","","","except tori","","","","","",""],
["","","","maybe if she apologizes first","","","","","",""],
["","","","i'll have to think about tori","","","","","",""],
["","you","","lol","","","null","","",""],
["sean_ask_about","","","","","","","",['dani', 'home', 'hobbies'],['sean_post_dani', 'sean_home', 'sean_hobbies']],
["sean_post_dani","you","","so, how'd you and dani meet?","","","","","",""],
["","","","you don't have to talk about it if you don't want btw","","","","","",""],
["","sean","","nah it's cool","","","","","",""],
["","","","it was at a record store!","","","","","",""],
["","","","so like my sister owned a record store, right?","","","","","",""],
["","","","called rattlesnake records","","","","","",""],
["","","","soon as i graduated i pestered her until she let me work there LOL","","","","","",""],
["","","","and good thing she did or i never would have met dani","","","","","",""],
["","you","","ooh, i see","","","","","",""],
["","","","i guess you met in [i]record[/i] time!","","","","","",""],
["","sean","","hah","","","","","",""],
["","","","yeah they came in asking about slowdive vinyls and i was like","","","","","",""],
["","","","no way you listen to slowdive??","","","","","",""],
["","","","and they were like","","","","","",""],
["","","","no, i can't stand them","","","","","",""],
["","","","but one of my friends collects records and he begged me to help him find this one LOL","","","","","",""],
["","you","","LOL","","","","","",""],
["","sean","","i might have told you, they were more of a classical kind of dude","","","","","",""],
["","","","played the piano","","","","","",""],
["","","","anyways","","","","","",""],
["","you","","did they play piano for a living?","","","","","",""],
["","sean","","oh god no","","","","","",""],
["","","","they were a freelance photographer","","","","","",""],
["","","","which is only SLIGHTLY more lucrative :P","","","","","",""],
["","you","","oh cool","","","","","",""],
["","sean","","you know","","","","","",""],
["","","","i guess the nice thing about your partner being a photographer is that they'll have about a billion photos to remember you by","","","","","",""],
["","you","","that's a nice thought","","","","","",""],
["","sean","","mhm","","","","","",""],
["","","","and only [i]some[/i] of them are nudes","","","","","",""],
["","you","","o","","","null","","",""],
["sean_home","you","","so, where did you live?","","","","","",""],
["","sean","","philly, why?","","","","","",""],
["","you","","just curious.","","","","","",""],
["","sean","","how about you?","","","","","",""],
["","","","oh you probably don't remember","","","","","",""],
["","you","","yeah","","","","","",""],
["","sean","","think it was a small place or a big place?","","","","","",""],
["","","","","","","","",['small', 'big'],['sean_home1', 'sean_home2']],
["sean_home1","you","","small, probably","","","","","",""],
["","","","i think i would have liked to live in a small, peaceful town","","","","","",""],
["","sean","","dude you would have loved my hometown","","","","","",""],
["","","","little place called tionesta","","","","","",""],
["","","","guess how many people were in my graduating class?","","","","","",""],
["","you","","ummmm","","","","","",""],
["","","","a hundred?","","","","","",""],
["","sean","","17 :P","","","","","",""],
["","you","","jeez","","","","","",""],
["","sean","","yeah man","","","","","",""],
["","","","i was SO happy when i finally got out of there","","","","","",""],
["","","","fuck small towns tbh","","","","","",""],
["","","","no offense","","","","","",""],
["","you","","none taken!","","","sean_home3","","",""],
["sean_home2","you","","big, probably","","","","","",""],
["","","","i think i would have liked being somewhere where things are always happening","","","","","",""],
["","sean","","same dude!!","","","","","",""],
["","","","god i was SO happy when i got out of my hometown ","","","","","",""],
["","","","guess how many people were in my graduating class?","","","","","",""],
["","you","","ummmm","","","","","",""],
["","","","a hundred?","","","","","",""],
["","sean","","17 :P","","","","","",""],
["","you","","jeez","","","","","",""],
["","sean","","yeah man","","","","","",""],
["","","","fuck small towns tbh","","","","","",""],
["","you","","yeah dude","","","","","",""],
["sean_home3","sean","","it was so booooooooooring","","","","","",""],
["","","","our idea of a night out was going to pizza joe's at 8pm","","","","","",""],
["","","","not to mention what happened when the ENTIRE SCHOOL found out i was gay","","","","","",""],
["","","","had to scrub slurs off my locker and shit","","","","","",""],
["","you","","yikes","","","","","",""],
["","sean","","yikes is right dude","","","","","",""],
["","","","but it's fine!","","","","","",""],
["","","","moved out when i was 18, crashed with debbie for a while","","","","","",""],
["","","","debbie's my sister, did i mention that already?","","","","","",""],
["","you","","maybe...?","","","","","",""],
["","sean","","anyway, dani and i scraped together enough money to rent an apartment","","","","","",""],
["","","","it was trashy as hell","","","","","",""],
["","","","window painted shut, heat didn't work half the time","","","","","",""],
["","","","and for some reason flushing the toilet sometimes made the fire alarm go off?","","","","","",""],
["","you","","huh","","","","","",""],
["","sean","","man, i loved that place...","","","null","","",""],
["sean_hobbies","you","","so what were your hobbies?","","","","","",""],
["","sean","","hmmm","","","","","",""],
["","","","does fucking count? ;)","","","","","",""],
["","you","","maybe?","","","","","",""],
["","sean","","hehe","","","","","",""],
["","","","i don't know, dude","","","","","",""],
["","","","music, i guess, but i was never as good at it as dani","","","","","",""],
["","","","oh i liked horror movies!","","","","","",""],
["","you","","oh yeah?","","","","","",""],
["","sean","","yeah ever since my siblings showed me resident evil on vhs when i was 8","","","","","",""],
["","you","","isn't that... kinda young?","","","","","",""],
["","sean","","what? nah","","","","","",""],
["","","","is it?","","","","","",""],
["","","","nahh","","","","","",""],
["","","","that's totally normal","","","","","",""],
["","you","","[i]shrug[/i]","","","","","",""],
["","sean","","you know, i used to go for walks in the cemetery and imagine zombies crawling out of the grave","","","","","",""],
["","","","that's normal too, right?","","","","","",""],
["","you","","yeah, sure","","","","","",""],
["","sean","","hmm... what else","","","","","",""],
["","","","OH i was a youtuber dude!!","","","","","",""],
["","you","","really??","","","","","",""],
["","sean","","yeah i started a channel where i play guitar for my birds!!","","","","","",""],
["","you","","wait that's amazing","","","","","",""],
["","sean","","I KNOW","","","","","",""],
["","you","","do you think they liked it?","","","","","",""],
["","sean","","sometimes","","","","","",""],
["","","","i think gabby liked it","","","","","",""],
["","","","but gaylord always tried to peck at the strings","","","","","",""],
["","","","the adorable little shit","","","","","",""],
["","you","","gaylord?","","","","","",""],
["","sean","","ya their names are gabby, goldenia, and gaylord","","","","","",""],
["","you","","those are good names!","","","","","",""],
["","sean","","thanks!","","","null","","",""]
]