extends Node

var raw_blocks = [
["slam_kyungsoon","you","kyungsoon_neutral","kyungsoon, you made it!","","","","","",""],
["","","","","","kyungsoon_quest_complete",['slam_kyungsoon1', 'slam_kyungsoon2'],"","",""],
["slam_kyungsoon1","kyungsoon","","yep","","","","","",""],
["","you","","looks like numa's all set up for her show","","","","","",""],
["","kyungsoon","","yep","","","","","",""],
["","you","","have you thought of anything to present yourself?","","","","","",""],
["","kyungsoon","","nah","","","","","",""],
["","","","i'ma watch","","","","","",""],
["","you","","cool, cool","","","","","",""],
["","","","do you... want a chair?","","","","","",""],
["","","","we have plenty","","","","","",""],
["","kyungsoon","","that would require moving","","","","","",""],
["","","","so no","","","","","",""],
["","you","","fair","","","","","",""],
["","_none","","numa calls from across the room.","","","","","",""],
["","numa","","hey kyungsoon!","","","","","",""],
["","","","would you help me move these bags of fertilizer??","","","","","",""],
["","_none","_none","kyungsoon hops to her feet and runs over.","","","","","",""],
["","kyungsoon","","yeah babe where do you want them?","","","","","",""],
["","you","","...","","","null","","",""],
["slam_kyungsoon2","kyungsoon","","made it to the commons?","","","","","",""],
["","","","where i've been sitting the whole time?","","","","","",""],
["","you","","uh... yeah!","","","","","",""],
["","kyungsoon","","...","","","","","",""],
["","","","sure did","","","","","",""],
["","","","almost didn't make it","","","","","",""],
["","","","traffic was horrible","","","","","",""],
["","you","","oh, yeah?","","","","","",""],
["","kyungsoon","","yeah i had to grab onto the back of a truck while riding a skateboard","","","","","",""],
["","","","it was pretty intense","","","","","",""],
["","you","","dang","","","null","","",""],
["slam_oliver","you","oliver_neutral","hey oliver! ","","","","","",""],
["","oliver","","hey!","","","","","",""],
["","","","don't mind me, i'm just putting the final touch on my research poster","","","","","",""],
["","you","","it looks very, uh","","","","","",""],
["","","","detailed!","","","","","",""],
["","oliver","","why thank you!","","","","","",""],
["","","","been a while since i prepared one of these by hand","","","","","",""],
["","","","i would have preferred putting together a powerpoint or something, but","","","","","",""],
["","","","one must make do!","","","","","",""],
["","you","","dang, we should ask them to install powerpoint in purrgatory","","","","","",""],
["","oliver","","yes, or any sort of database or computational engine really","","","","","",""],
["","","","or... a computer","","","","","",""],
["","","","would save me a lot of hand cramps. eheh","","","null","","",""],
["slam_sean","you","sean_neutral","sean, what's up?","","","","","",""],
["","sean","","{player}!","","","","","",""],
["","","","just warming up the old fingies, haha","","","","","",""],
["","you","","you feel ready for your performance?","","","","","",""],
["","sean","","oh i was BORN ready, baby!","","","","","",""],
["","","","i can feel my blood pumpin, dude. heart racing. all that jazz","","","","","",""],
["","","","elijah told me he scheduled me first, so i'm gonna be opening up the whole shebang","","","","","",""],
["","","","i was DESTINED for this. HEADLINING at the PURRGATORY MUSIC FESTIVAL!","","","","","",""],
["","you","","ooh, good luck!","","","","","",""],
["","sean","","thanks, dude. but honestly?","","","","","",""],
["","","","don't need it B)","","","","","",""],
["","you","","that's the spirit!","","","null","","",""],
["slam_tori","tori","tori_neutral","{player}, there you are.","","","","","",""],
["","","","these are for you.","","","","","",""],
["","_none","","tori deposits a stack of wooden planks in your arms.","","","","","",""],
["","you","","whoa!","","","","","",""],
["","tori","","thought i'd start off with a kata or two.","","","","","",""],
["","","","then, move on to the planks -- that's what everyone wants to see.","","","","","",""],
["","","","hold one low like this. i'll do a knee strike. hold one at chest level. palm heel strike.","","","","","",""],
["","","","in the following order: jumping front kick. hook punch. spinning hook kick. flying side kick.","","","","","",""],
["","","","not much you can do with just one demonstrator, but i figure we can show off the basics.","","","","","",""],
["","","","get all that?","","","","","",""],
["","you","","...uh...","","","","","",""],
["","tori","","actually, don't worry about it, i can walk you through it when the time comes.","","","","","",""],
["","","","i can even grab oliver if need be.","","","","","",""],
["","","","just hold the plank and try not to flinch.","","","","","",""],
["","you","","okay, cool!","","","","","",""],
["","tori","","how about you? ","","","","","",""],
["","","","are you presenting anything?","","","","","",""],
["","you","","oh, uh, i don't know","","","","","",""],
["","","","i didn't really think about it","","","","","",""],
["","tori","","no natural talents come to mind?","","","","","",""],
["","you","","i guess if i had any, i forgot them","","","","","",""],
["","","","turns out i'm pretty good at running errands, though?","","","","","",""],
["","tori","","oh, yeah. ","","","","","",""],
["","","","that's sure to be a crowd-pleaser.","","","","","",""],
["","you","","hehe","","","null","","",""],
["slam_natalie","natalie","natalie_neutral","{player}!!","","","","","",""],
["","you","","hey natalie!","","","","","",""],
["","","","glad you made it!","","","","","",""],
["","natalie","","dude i wouldn't have missed it for anything","","","","","",""],
["","","","i wasn't sure what exactly i was supposed to \"present,\" so i asked elijah and he said i can just hang up my stuff","","","","","",""],
["","","","it'll be like a pop up art gallery!","","","","","",""],
["","you","","awesome!","","","","","",""],
["","","","what's that one?","","","","","",""],
["","natalie","","oh, i call this one \"composition in blue\"","","","","","",""],
["","","","kind of a more abstract sort of thing. exploring themes and whatnot","","","","","",""],
["","you","","ooh, cool","","","","","",""],
["","","","what about that one?","","","","","",""],
["","natalie","","that's a picture of me going to jupiter in a rocket ship!","","","","","",""],
["","you","","ooh!","","","null","","",""],
["slam_numa","numa","numa_neutral","oh, hi {player}!","","","","","",""],
["","you","","hey numa","","","","","",""],
["","","","how are you feeling about the gardening show?","","","","","",""],
["","numa","","oh, i'm so excited and nervous at the same time!","","","","","",""],
["","","","i decided i'll repot a shrub and then show how to germinate a tulip seed","","","","","",""],
["","","","and along the way, i can talk a little about my favorite topic... soil analysis!!","","","","","",""],
["","","","but i don't even have ph strips...","numa_mentioned_ph_strips","","","","",""],
["","","","what if i get the ph adjustment all wrong??","","","","","",""],
["","","","or what if i drop the shrub and get dirt EVERYWHERE??","","","","","",""],
["","","","do you know how many shrubs i've dropped?","","","","","",""],
["","","","AT LEAST ONE!","","","","","",""],
["","you","","hey, you'll be alright!","","","","","",""],
["","","","this is just a time when you can share something you care about","","","","","",""],
["","","","it doesn't need to be perfect!","","","","","",""],
["","numa","","you're right... it doesn't need to be perfect...","","","","","",""],
["","","","OR DOES IT??","","","","","",""],
["","you","","no","","","","","",""],
["","","","it doesn't","","","","","",""],
["","numa","","oh, okay","","","","","",""],
["","","","sorry ;;","","","null","","",""],
["slam_elijah","","","_pass","","talked_to_slam_elijah",['slam_elijah_again', 'slam_elijah1'],"","",""],
["slam_elijah1","you","elijah_neutral","elijah!","talked_to_slam_elijah","","","","",""],
["","elijah","","hey, that's my name, don't wear it out.","","","","","",""],
["","you","","dang, you got everything set up, like... really fast","","","","","",""],
["","elijah","","well, thank you. i try.","","","","","",""],
["","you","","no like","","","","","",""],
["","","","i was literally just here and it was empty","","","","","",""],
["","elijah","","huh. weird","","","","","",""],
["","you","","anyway, how are you feeling?","","","","","",""],
["","elijah","","oh, i'm good! i'm good.","","","","","",""],
["","","","honestly, not as nervous as i thought i'd be.","","","","","",""],
["","","","it's been a hot minute since this place has been this bustling. think that's good for my old brain. a little bit of a jumpstart.","","","","","",""],
["","you","","glad to hear that!","","","","","",""],
["","","","yeah, purrgatory's so big sometimes you forget there's actually a bunch of us in it together","","","","","",""],
["","elijah","","absolutely. absolutely.","","","","","",""],
["","you","","well, when do you think we're going to get started?","","","","","",""],
["","elijah","","could start whenever. could start now, even.","","","","","",""],
["","","","what do you say, master of ceremonies?","","","","","",""],
["","","","","","","","",['let\'s start!', 'in a bit'],['slam_elijah3', 'slam_elijah2']],
["slam_elijah_again","elijah","","hey, {player}.","","","","","",""],
["","","","ready to get the everything slam rolling?","","","","","",""],
["","","","","","","","",['let\'s start!', 'in a bit'],['slam_elijah3', 'slam_elijah2']],
["slam_elijah2","you","","maybe in a bit.","","","","","",""],
["","elijah","","hey, take your time. i'll be here.","","","null","","",""],
["slam_elijah3","you","","let's start!","","","","","",""],
["","elijah","","no time like the present, huh?","","","","","",""],
["","","","yeah, might as well get started. might as well.","","","","","",""],
["","_none","","elijah clears his throat.","","","","","",""],
["","elijah","","hey, y'all! we're about ready to start!","","","null","","",""]
]