extends Node

var raw_blocks = [
["slam_kyungsoon","","","_pass","",['post_slam', 'looking_for_poem'],['slam_kyungsoon_after', 'slam_kyungsoon_shh', 'slam_kyungsoon0'],"","",""],
["slam_kyungsoon0","you","kyungsoon_neutral","kyungsoon, you made it!","","kyungsoon_quest_complete",['slam_kyungsoon1', 'slam_kyungsoon2'],"","",""],
["slam_kyungsoon1","kyungsoon","","...","","","","","",""],
["","","","sure did","","","","","",""],
["","you","","looks like numa's all set up for her show","","","","","",""],
["","kyungsoon","","yep","","","","","",""],
["","you","","have you thought of anything to present yourself?","","","","","",""],
["","kyungsoon","","nah","","","","","",""],
["","","","ima watch","","","","","",""],
["","you","","cool, cool","","","","","",""],
["","","","do you... want a chair?","","","","","",""],
["","","","we have plenty","","","","","",""],
["","kyungsoon","","that would require moving","","","","","",""],
["","","","so no","","","","","",""],
["","you","","fair","","","","","",""],
["","_none","","numa calls from across the room.","_hide_slam_numa&slam_kyungsoon","","","","",""],
["","numa","","hey kyungsoon!","","","","","",""],
["","","","would you help me move these bags of fertilizer??","","","","","",""],
["","_none","_none","kyungsoon hops to her feet and runs over.","","","","","",""],
["","kyungsoon","","yeah babe where do you want them?","","","","","",""],
["","you","","...","","","null","","",""],
["slam_kyungsoon2","kyungsoon","","...","","","","","",""],
["","","","sure did","","","","","",""],
["","","","almost didn't make it","","","","","",""],
["","","","traffic was horrible","","","null","","",""],
["","you","","i see, i see","","","","","",""],
["slam_oliver","you","oliver_neutral","hey oliver! ","","","","","",""],
["","oliver","","hey!","","","","","",""],
["","","","don't mind me, i'm just putting the final touch on my research poster.","","","","","",""],
["","you","","it looks very, uh","","","","","",""],
["","","","detailed!","","","","","",""],
["","oliver","","why, thank you!","","","","","",""],
["","","","it's been a while since i had to prepare one of these by hand.","","","","","",""],
["","","","i would have preferred putting together a powerpoint or something, but...","","","","","",""],
["","","","one must make do!","","","","","",""],
["","you","","true, true","","","","","",""],
["","","","we should ask them to install powerpoint in purrgatory when we have the chance","","","","","",""],
["","oliver","","haha, yes","","","","","",""],
["","","","or any sort of database or computational engine, really.","","","","","",""],
["","","","or just... a computer","","","","","",""],
["","","","would save me a lot of hand cramps. eheh.","","","","","",""],
["","you","","if you had one, would that make you... a computer mouse?","","","","","",""],
["","oliver","","well, i suppose it would!","","","null","","",""],
["slam_sean","you","sean_neutral","sean, what's up?","","","","","",""],
["","sean","","{player}!","","","","","",""],
["","","","just chilling while everyone gets set up, haha","","","","","",""],
["","you","","i see, i see","","","","","",""],
["","","","you feel ready for your performance?","","","","","",""],
["","sean","","oh, yeah","","","","","",""],
["","","","i was BORN ready","","","","","",""],
["","","","i can feel my blood pumpin, dude. heart racing. all that jazz","","","","","",""],
["","","","elijah told me he scheduled me first, so i'm gonna be opening up the whole shebang","","","","","",""],
["","","","can you believe it?","","","","","",""],
["","","","HEADLINING at the PURRGATORY MUSIC FESTIVAL!","","","","","",""],
["","you","","ooh, good luck!","","","","","",""],
["","sean","","thanks, dude. but honestly?","","","","","",""],
["","","","don't need it B)","","","","","",""],
["","you","","that's the spirit!","","","null","","",""],
["slam_tori","tori","tori_neutral","{player}, there you are.","","","","","",""],
["","","","these are for you.","","","","","",""],
["","_none","","tori deposits a stack of wooden planks in your arms.","","","","","",""],
["","you","","whoa!","","","","","",""],
["","tori","","thought i'd start off with a kata or two.","","","","","",""],
["","","","then, move on to the planks -- that's what everyone wants to see.","","","","","",""],
["","","","hold one low like this. i'll do a knee strike. hold one at chest level. palm heel strike.","","","","","",""],
["","","","in the following order: jumping front kick. hook punch. spinning hook kick. flying side kick.","","","","","",""],
["","","","get all that?","","","","","",""],
["","you","","uh...","","","","","",""],
["","tori","","actually, don't worry about it, i can walk you through it when the time comes.","","","","","",""],
["","","","just hold the plank and try not to flinch.","","","","","",""],
["","","","or if you change your mind, i can always rope in oliver or something.","","","","","",""],
["","you","","okay, cool!","","","","","",""],
["","tori","","how about you? ","","","","","",""],
["","","","are you presenting anything?","","","","","",""],
["","you","","oh, uh, i don't know","","","","","",""],
["","","","i didn't really think about it","","","","","",""],
["","tori","","no natural talents come to mind?","","","","","",""],
["","you","","i guess if i had any, i forgot about them :/","","","","","",""],
["","","","turns out i'm pretty good at running errands, though?","","","","","",""],
["","tori","","oh, yeah. ","","","","","",""],
["","","","that's sure to be a crowd-pleaser.","","","","","",""],
["","you","","hehe","","","null","","",""],
["slam_natalie","natalie","natalie_neutral","{player}!!","","","","","",""],
["","you","","hey natalie!","","","","","",""],
["","","","glad you made it!","","","","","",""],
["","natalie","","dude i wouldn't have missed it for anything","","","","","",""],
["","","","i even cooked up some new drawings, like this one!","","","","","",""],
["","you","","awesome!","","","","","",""],
["","","","what's that one called?","","","","","",""],
["","natalie","","i call it \"ruminations on melancholy\"","","","","","",""],
["","","","it's sort of an abstract expression of the emotions of purrgatory, represented by both the low value contrast and the unstable shapes that draw your eye in a spiral.","","","","","",""],
["","you","","cool, cool","","","","","",""],
["","","","what about that one?","","","","","",""],
["","natalie","","that's a picture of me going to jupiter in a rocket ship!","","","","","",""],
["","you","","ooh!","","","null","","",""],
["slam_numa","numa","numa_neutral","oh hi {player}!","","","","","",""],
["","you","","hey numa!","","","","","",""],
["","","","how are you feeling about the gardening show?","","","","","",""],
["","numa","","oh, i'm so excited and nervous at the same time!","","","","","",""],
["","","","i decided i'll show how to germinate a tulip seed and then repot a shrub","","","","","",""],
["","","","and along the way, i can talk a little about my favorite topic... soil analysis!!","","","","","",""],
["","","","but i don't even have ph strips...","numa_mentioned_ph_strips","","","","",""],
["","","","what if i get the ph adjustment all wrong??","","","","","",""],
["","","","or what if i drop the shrub and get dirt EVERYWHERE??","","","","","",""],
["","","","do you know how many shrubs i've dropped?","","","","","",""],
["","","","AT LEAST ONE!","","","","","",""],
["","you","","hey, you'll be alright!","","","","","",""],
["","","","this is just a time when you can share something you care about","","","","","",""],
["","","","it doesn't need to be perfect!","","","","","",""],
["","numa","","you're right... it doesn't need to be perfect...","","","","","",""],
["","","","OR DOES IT??","","","","","",""],
["","you","","no","","","","","",""],
["","","","it doesn't","","","","","",""],
["","numa","","oh, okay","","","","","",""],
["","","","sorry ;;","","","null","","",""],
["slam_elijah","","","_pass","","talked_to_slam_elijah",['slam_elijah_again', 'slam_elijah1'],"","",""],
["slam_elijah1","you","elijah_neutral","elijah!","talked_to_slam_elijah","","","","",""],
["","elijah","","what's up, man?","","","","","",""],
["","you","","dang, you got everything set up, like... really fast","","","","","",""],
["","elijah","","well, thank you. i try.","","","","","",""],
["","you","","no like","","","","","",""],
["","","","i was literally just here and it was empty","","","","","",""],
["","elijah","","huh. weird.","","","","","",""],
["","you","","anyway, how are you feeling?","","","","","",""],
["","elijah","","oh, i'm good! i'm good.","","","","","",""],
["","","","honestly, not as nervous as i thought i'd be.","","","","","",""],
["","","","it's been a hot minute since this place has been this bustling. ","","","","","",""],
["","","","think that's good for my old brain. a little bit of a jumpstart.","","","","","",""],
["","you","","glad to hear that!","","","","","",""],
["","","","yeah, purrgatory's so big that it's easy to forget there's actually a bunch of us here","","","","","",""],
["","elijah","","you said it.","","","","","",""],
["","you","","well, when do you think we're going to get started?","","","","","",""],
["","elijah","","could start whenever. could start now, even.","","","","","",""],
["","","","what do you say, master of ceremonies?","","","","","",""],
["","","","","","","","",['let\'s start!', 'in a bit'],['slam_elijah3', 'slam_elijah2']],
["slam_elijah_again","elijah","elijah_neutral","hey, {player}.","","","","","",""],
["","","","ready to get the everything slam rolling?","","","","","",""],
["","","","","","","","",['let\'s start!', 'in a bit'],['slam_elijah3', 'slam_elijah2']],
["slam_elijah2","you","","maybe in a bit.","","","","","",""],
["","elijah","","hey, take your time! make sure everyone's ready. i'll be here.","","","null","","",""],
["slam_elijah3","you","","let's start!","","","","","",""],
["","elijah","","no time like the present, huh?","","","","","",""],
["","","","thanks for everything you've done, man. i'll take it from here.","","","","","",""],
["","you","","roger!","","","","","",""],
["","_none","","elijah clears his throat.","","","","","",""],
["","elijah","","hey, y'all! ","","","","","",""],
["","","","we're about ready to start!","","","","","",""],
["","_none","","everyone wraps up their preparations and gets seated.","slam_intro","","","","",""],
["","","","you find an empty chair near the back.","","","","","",""],
["","elijah","","what a turnout, huh? what a turnout.","","","","","",""],
["","","","a sincere thanks to everyone for coming to the everything slam.","","","","","",""],
["","","","the first ever combination poetry slam, art gallery, music festival, gardening show, martial arts demo, and research symposium in all of history.","","","","","",""],
["","","","probably.","","","","","",""],
["","","","i'm not gonna lie, it's been a while since i've seen some of y'all.","","","","","",""],
["","_none","","there's a murmur of agreement in the audience.","","","","","",""],
["","elijah","","this is our time to catch up, get to know what our brothers and sisters have been working on.","","","","","",""],
["","","","and while we're at it, this is a great opportunity to give a warm welcome to the newest member of the family, {player}.","","","","","",""],
["","you","","huh?","","","","","",""],
["","elijah","","hey, man. we wouldn't be doing this slam without you.","","","","","",""],
["","","","glad you're here.","","","","","",""],
["","","","well, not glad you're [i]here[/i]. but you know what i mean.","","","","","",""],
["","_none","","a few chuckles come from the audience.","","","","","",""],
["","elijah","","anyway, you didn't come here to hear me ramble on.","","","","","",""],
["","","","as you'll see on your programs, sean is up first with his performance of an original song, \"purrgatory blues.\"","","","","","",""],
["","","","presenting next will be oliver, tori, numa, and yours truly, in that order.","","","","","",""],
["","","","sean, take the stage!","","","","","",""],
["","_none","sean_neutral","sean hops up to a smattering of applause.","","","","","",""],
["","sean","","thanks, elijah!","","","","","",""],
["","","","it's great to be here. really great.","","","","","",""],
["","","","lot of new faces in the crowd today, huh?","","","","","",""],
["","","","how about you, in the glasses. you come here often?","","","","","",""],
["","oliver",['sean_neutral', 'oliver_neutral'],"huh?","","","","","",""],
["","","","sean, it's me, oliver.","","","","","",""],
["","sean","","oliver? i like that name! very classy.","","","","","",""],
["","","","wouldn't mind getting to know ya better sometime ;)","","","","","",""],
["","oliver","","???","","","","","",""],
["","sean","","how bout you? the scary looking one with the wings?","","","","","",""],
["","tori",['sean_neutral', 'tori_neutral'],"sean, you're here to sing, not flirt with the audience.","","","","","",""],
["","sean","","hey, it's called working the floor, ever heard of it??","","","","","",""],
["","","","sheesh, the gall of some people.","","","","","",""],
["","_none","sean_neutral","sean presses the power button.",[['_music_null', true], ['button_sound', true]],"","","","",""],
["","sean","","anyway, let's get down to business!","","","","","",""],
["","","","this little song i wrote goes out to dani, the love of my life","","","","","",""],
["","","","you were my best friend, man. my confidante. all those fancy words","","","","","",""],
["","","","sometimes it's hard to believe you're not here anymore, ya know?","","","","","",""],
["","","","sorry, y'all. you know i don't like getting all sappy","","","","","",""],
["","","","but sometimes... you gotta let it all out","","","","","",""],
["","","","dani, if you're out there... i miss you, man","","","","","",""],
["","","","i miss you real, real bad","","","","","",""],
["","","","but i know you're doing alright, cus you're you. and that's what matters.","","","","","",""],
["","","","...","","","","","",""],
["","_none","","sean takes a deep breath, then starts playing.","","","","","",""],
["","","","[i]hey babe don't know if you can hear me[/i]","purrgatory_blues0","","","","",""],
["","","","[i]but how's the weather down in philly?[/i]","purrgatory_blues1","","","","",""],
["","","","[i]did you ever try that dirty chai?[/i]","purrgatory_blues2","","","","",""],
["","","","[i]and is our english ivy still alive?[/i]","purrgatory_blues3","","","","",""],
["","","","[i]wish i could see you one more time[/i]","purrgatory_blues4","","","","",""],
["","","","[i]hug you, kiss you, make your lyrics rhyme[/i]","purrgatory_blues5","","","","",""],
["","","","[i]back home where nothing ever changes[/i]","purrgatory_blues6","","","","",""],
["","","","[i]wish i was better off but the truth is[/i]","purrgatory_blues7","","","","",""],
["","","","[i]i'm stuck in purrgatory too[/i]","purrgatory_blues8","","","","",""],
["","","","[i]it's just not the same without you, boo[/i]","purrgatory_blues9","","","","",""],
["","","","[i]think i'll take a purrgatory snooze[/i]","purrgatory_blues10","","","","",""],
["","","","[i]and maybe i'll wake up next to you[/i]","purrgatory_blues11","","","","",""],
["","","","[i]i've got the purrgatory blues[/i]","purrgatory_blues12","","","","",""],
["","","","[i]oh it ain't no purrgatory cruise[/i]","purrgatory_blues13","","","","",""],
["","","","[i]if you can hear this purrgatory tune[/i]","purrgatory_blues14","","","","",""],
["","","","[i]just know i'm thinking of you[/i]","purrgatory_blues15","","","","",""],
["","_none","elijah_neutral","elijah taps your shoulder.","purrgatory_blues_loop","","","","",""],
["","elijah","","pssst, {player}","","","","","",""],
["","","","i have an emergency!","","","","","",""],
["","you","","huh? what happened?","","","","","",""],
["","_none","","elijah motions you over to the corner where you can talk quietly.","_goto_commons1_slam","","","","",""],
["","elijah","","i lost my damn poem!","","","","","",""],
["","you","","oh no!","","","","","",""],
["","elijah","","i swear i had it on hand when i left the meowseum, but it's gone without a trace.","","","","","",""],
["","","","i made so many last-minute changes, man... there's no way i'll be able to do it from memory.","","","","","",""],
["","","","i'm sorry to drag you into this, but would you mind helping me look for it?","","","","","",""],
["","","","","","","","",['when did you last see it?', 'i don\'t want to miss the others, but...', 'you should have been more careful!'],['slam_elijah4', 'slam_elijah5', 'slam_elijah6']],
["slam_elijah4","you","","hmm, when did you last see it?","","","","","",""],
["","elijah","","i've been all over purrgatory helping the others set up, man. could be anywhere by now.","","","","","",""],
["","you","","dang...","","","slam_elijah7","","",""],
["slam_elijah5","you","","well, i don't want to miss the others, but...","","","slam_elijah7","","",""],
["slam_elijah6","you","","no offense, but you should have been more careful!","","","","","",""],
["","","","something as important as this...","","","","","",""],
["","elijah","","jeez, i know, i know...","","","slam_elijah7","","",""],
["slam_elijah7","elijah","","i'm really sorry, man, it's just...","","","","","",""],
["","","","i'm afraid of backing out. seems like everything's been building up to this. ","","","","","",""],
["","","","who knows the next time i'll have an opportunity like this?","","","","","",""],
["","","","a chance to get out of this rut?","","","","","",""],
["","you","","i totally understand","","","","","",""],
["","","","i'm sure if we work together we'll find it in no time!","","","","","",""],
["","elijah","","i appreciate it, man. you're the best.","","","","","",""],
["","","","alright, i'm heading out.","","","","","",""],
["","","","i'm gonna start near natalie's place, in case i dropped it while helping her prepare her drawings","_delay__quest_elijah_poem","","","","",""],
["","","","come give me a shout if you find it.","_delay_remove_slam_intro","","","","",""],
["","_none","_none","elijah hurries out of the room.","_delay_looking_for_poem","","null","","",""],
["slam_kyungsoon_shh","kyungsoon","kyungsoon_neutral","lost a poem, huh?","","","","","",""],
["","","","","","","","",['have you seen it?', 'DID YOU EAT IT??'],['slam_kyungsoon_shh1', 'slam_kyungsoon_shh2']],
["slam_kyungsoon_shh1","you","","have you seen it?","","","","","",""],
["","kyungsoon","","seen what?","","","","","",""],
["","you","","elijah's poem!","","","","","",""],
["","kyungsoon","","what about elijah's poem?","","","","","",""],
["","you","","have you-- ","","","","","",""],
["","","","oh, never mind, you're no use.","","","","","",""],
["","kyungsoon","","thanks, i try","","","null","","",""],
["slam_kyungsoon_shh2","you","","DID YOU EAT IT??","","","","","",""],
["","kyungsoon","","lmao no","","","","","",""],
["","you","","kyungsoon i swear if you ate it--","","","","","",""],
["","kyungsoon","","hey, i didn't eat it","","","","","",""],
["","","","i'm not that much of an asshole","","","","","",""],
["","you","","okay, good","","","null","","",""],
["slam_tori_shh","you","tori_neutral","hey, tori--","","","","","",""],
["","tori","","shh!","","","","","",""],
["","you","","sorry, sorry...","","","null","","",""],
["slam_natalie_shh","natalie","natalie_neutral","dang, i didn't know he could sing like that!","","","","","",""],
["","you","","i know, right?","","","null","","",""],
["slam_oliver_shh","oliver","oliver_neutral","he's quite good, isn't he?","","","","","",""],
["","you","","mhm","","","null","","",""],
["slam_numa_shh","numa","numa_neutral","wow...","","","","","",""],
["","","","i wonder if anyone will ever sing me a song like that...","","","null","","",""],
["slam_sean_shh","_none","_none","he's busy right now!","","","null","","",""],
["slam_found_poem","you","elijah_neutral","ELIJAH!",[['purrgatory_blues_loop', false], ['looking_for_poem', false], ['slam_outro', true], ['elijah_alert', true], ['_quest_elijah_poem', false]],"","","","",""],
["","elijah","","huh? what's up?","","","","","",""],
["","you","","ON YOUR FOOT!","","","","","",""],
["","_none","","elijah lifts his foot and retrieves the poem stuck to it.","","","","","",""],
["","elijah","","well, jiminy cricket.","","","","","",""],
["","you","","oh my GOD i looked all over purrgatory for that thing","","","","","",""],
["","elijah","","damn, {player}, i'm sorry--","","","","","",""],
["","you","","it's okay! we gotta get back before it's your turn!","","","","","",""],
["","elijah","","you're right, you're right!","","","","","",""],
["","","","right behind ya!","","","","","",""],
["","_none","","the two of you rush through purrgatory.","_goto_hallway3","","","","",""],
["","elijah","","huff... huff...","","","","","",""],
["","","","haven't gotten this much exercise... in years...","","","","","",""],
["","you","","guess the everything slam came with a cardio workout too!","","","","","",""],
["","elijah","","hah... good one...","","","","","",""],
["","_none","_none","finally, you arrive at the commons.","_goto_commons2_slam","","","","",""],
["","","","numa is patting down the soil on a newly repotted shrub.","","","","","",""],
["","numa","numa_neutral","...even 75 or 80 miles away, the plants can respond so differently.","","","","","",""],
["","","","so if you can get your information close to home, you'll be much better off!","","","","","",""],
["","","","unfortunately, there's not really a guide to purrgatory soil, but...","","","","","",""],
["","_none",['numa_neutral', 'tori_neutral'],"tori raises her hand.","","","","","",""],
["","tori","","i have another question.","","","","","",""],
["","","","is it ever worth it to buy grafted plants, like grafted tomato plants?","","","","","",""],
["","numa","","oh, that's a great question!","","","","","",""],
["","","","most of the grafting by commercial growers comes from the fact that they grow tomatos in very intense situations.","","","","","",""],
["","","","grafting makes the rootstocks resistant to disease, and gives them a lot of vigor.","","","","","",""],
["","","","but for a backyard gardener, i don't think it's necessary.","","","","","",""],
["","","","just rotate your crops, watch out for diseases, use locally grown, and for the most part you'll be fine!","","","","","",""],
["","tori","","i see. thank you.","","","","","",""],
["","numa","","umm, does anyone else have any questions?","","","","","",""],
["","","","...","","","","","",""],
["","","","in that case, um, i think that's all i have!","","","","","",""],
["","","","thanks everyone ^^","","","","","",""],
["","_none","_none","everyone applauds as numa hauls the potted plant to the side and takes her seat.","","","","","",""],
["","","","elijah jogs up to the front, breathing hard.","","","","","",""],
["","elijah","elijah_neutral","hey, yall.","","","","","",""],
["","","","phew!","","","","","",""],
["","","","looks like i got back... huff... just in time.","","","","","",""],
["","","","sorry about having to dip, there. hope the everything slam's been going alright.","","","","","",""],
["","_none","","some of the others nod in agreement.","","","","","",""],
["","elijah","","thanks for imparting some of that expert gardening knowledge to us, numa.","","","","","",""],
["","","","presenting next will be...","","","","","",""],
["","","","well, looks like it's just me left.","","","","","",""],
["","","","hah. just, uh, let me catch my breath real fast.","","","","","",""],
["","_none","","elijah takes a deep breath.","","","","","",""],
["","elijah","","phew.","","","","","",""],
["","","","uhm.","","","","","",""],
["","","","i just want to thank everyone for coming one more time.","","","","","",""],
["","","","purrgatory can be a real downer, y'all.","","","","","",""],
["","","","a place where nothing happens and nothing matters.","","","","","",""],
["","","","but we keep on doing our little chores, 'cus that's what people do.","","","","","",""],
["","","","we plant our flowers.","","","","","",""],
["","","","we count our books.","","","","","",""],
["","","","we keep each others' heads up.","","","","","",""],
["","","","and hey... i think that's special.","","","","","",""],
["","","","i really do.","","","","","",""],
["","","","...","","","","","",""],
["","","","this is something i've been working on for a while, now.","","","","","",""],
["","","","it's called \"the bus stop\"","","","","","",""],
["","","","...","","","","","",""],
["","","","it was a hot summer","_music_null","","","","",""],
["","","","sidewalks sizzling, streets deserted","","","","","",""],
["","","","friends long gone to greener pastures","","","","","",""],
["","","","leaving me alone to wait for the rapture","","","","","",""],
["","","","i fell through the cracks at an early age","","","","","",""],
["","","","snapped up by a piranha with a flag on his arm","","","","","",""],
["","","","who didn't tell me about food in brown pouches or ringing ears","","","","","",""],
["","","","or nightmares every day for years","","","","","",""],
["","","","...","","","","","",""],
["","","","i came home to a world that had moved on","","","","","",""],
["","","","drywall cracks and oatmeal and flies buzzing all night long","","","","","",""],
["","","","politicians arguing on tv about oil and freedom overseas","","","","","",""],
["","","","man, i just wanted a paycheck and maybe some AC","","","","","",""],
["","","","it was a hot summer","","","","","",""],
["","","","i tried to catch a bus out of town","","","","","",""],
["","","","the engine was fine, it was me that broke down","","","","","",""],
["","","","idling on the shoulder til i was covered in moss","","","","","",""],
["","","","flies whispering \"would they notice if you were gone?\"","","","","","",""],
["","","","...","","","","","",""],
["","","","once again, the bus is late","","","","","",""],
["","","","but this time, i ain't afraid to wait.","","","","","",""],
["","_none","","elijah lowers his poem. after a moment of silence, the others start clapping.","","","","","",""],
["","elijah","","thanks, y'all.","","","","","",""],
["","","","that's all we have for today.","","","","","",""],
["","","","hey, if you haven't, check out some of the beautiful art by natalie on your way out.","","","","","",""],
["","","","and thanks again to everyone for being here.","","","","","",""],
["","","","it... it means a lot.","","","","","",""],
["","sean",['elijah_neutral', 'sean_neutral'],"wouldn'ta missed it for the world, buddy","","","","","",""],
["","natalie",['elijah_neutral', 'sean_neutral', 'natalie_neutral'],"same here!","","","","","",""],
["","oliver",['elijah_neutral', 'sean_neutral', 'natalie_neutral', 'oliver_neutral'],"and thank you for organizing it!","_delay__music_Welcome_To_Purrgatory","","","","",""],
["","elijah","","aw, shucks. y'all are too nice.","_delay_remove_slam_outro","","","","",""],
["","_none","_none","a chatter arises as the audience starts to disperse.","_delay_post_slam","","null","","",""],
["slam_oliver_after","you","oliver_neutral","oliver!","","","","","",""],
["","","","sorry i missed your presentation... how'd it go?","","","","","",""],
["","oliver","","quite well, actually!","","","","","",""],
["","","","we had an interesting discussion about library of congress classification.","","","","","",""],
["","you","","oh?","","","","","",""],
["","oliver","","yes, i thought our books should be filed under PN for literature, but natalie suggested QL for cats","","","","","",""],
["","","","it's quite an open ended topic!","","","","","",""],
["","you","","ah, interesting","","","","","",""],
["","oliver","","after that, tori recruited me to assist in her karate demonstration.","","","","","",""],
["","","","the experience was, um","","","","","",""],
["","","","exhilarating, to say the least","","","","","",""],
["","you","","oh dang, i think i was supposed to be the one holding the planks","","","","","",""],
["","","","thanks for filling in!","","","","","",""],
["","oliver","","ah... no problem, heh","","","null","","",""],
["slam_kyungsoon_after","you","kyungsoon_neutral","so, what did you think about the slam?","","","","","",""],
["","kyungsoon","","i liked it","","","","","",""],
["","you","","really??","","","","","",""],
["","kyungsoon","","yeah","","","","","",""],
["","","","oliver almost got kicked in the face","","","","","",""],
["","you","","oh lol","","","","","",""],
["","","","did you like anything else?","","","","","",""],
["","kyungsoon","","...","","","","","",""],
["","","","the garden stuff was interesting i guess","","","","","",""],
["","","","and the song didn't sound horrible","","","","","",""],
["","you","","awesome!","","","null","","",""],
["slam_try_to_leave","_none","_none","numa catches your attention as you reach for the door.","_hide_slam_elijah_after","","","","",""],
["","numa",['elijah_neutral', 'numa_neutral'],"oh, {player}!","","","slam_elijah_after0","","",""],
["slam_elijah_after","_none",['elijah_neutral', 'numa_neutral'],"numa and elijah are chatting when you approach.","","","","","",""],
["","numa","","...picked it up from the internet, mostly!","","","","","",""],
["","","","there are a few gardening podcasts i really liked, haha","","","","","",""],
["","elijah","","that's awesome, man.","","","","","",""],
["","","","an old friend of mine had an herb garden. meant to get into it one day, but i never did.","","","","","",""],
["","numa","","well, it's never too late to get started.","","","","","",""],
["","","","oh hi {player}!","","","","","",""],
["slam_elijah_after0","","","thanks so much for inviting me here, it was so much fun ^^","","","","","",""],
["","you","","aw, you're welcome!","","","","","",""],
["","","","","","","","",['it wasn\'t too nervewracking after all?', 'what part did you like best?', 'would you do it again?'],['slam_elijah_after1', 'slam_elijah_after2', 'slam_elijah_after3']],
["slam_elijah_after1","you","","it wasn't too nervewracking after all?","","","","","",""],
["","numa","","well, um, it was a little scary at first","","","","","",""],
["","","","but once i started talking i stopped being so nervous","","","","","",""],
["","","","i got into the flow zone!","","","","","",""],
["","you","","that's great!","","","slam_elijah_after4","","",""],
["slam_elijah_after2","you","","what part did you like best?","","","","","",""],
["","numa","","um, i really liked hearing about oliver's research","","","","","",""],
["","","","how libraries are organized and stuff like that","","","","","",""],
["","","","oh, and the art is really good too!","","","","","",""],
["","you","","that's great!","","","slam_elijah_after4","","",""],
["slam_elijah_after3","you","","would you do it again?","","","","","",""],
["","numa","","oh absolutely!","","","","","",""],
["","","","if i could do it again, i think i'd like to get everyone their own plants and tools so they can follow along","","","","","",""],
["","","","like a gardening workshop!","","","","","",""],
["","you","","ooh, that would be cool","","","slam_elijah_after4","","",""],
["slam_elijah_after4","numa","","anyway, i should probably start bringing these pots back to the garden...","","","","","",""],
["","elijah","","need any help?","","","","","",""],
["","numa","","oh, if you don't mind!","","","","","",""],
["","","","these pots can be kind of heavy, haha","","","","","",""],
["","you","","i can take one too!","","","","","",""],
["","numa","","aww, thank you","","","","","",""],
["","","","you two are so nice ;;","","","","","",""],
["","_none","","you grab a large potted plant and stagger up the stairs with the others.","_goto_commons3","","","","",""],
["","elijah","","you know, numa...","","","","","",""],
["","","","if you ever need some help in the garden, i'd be down for whatever.","","","","","",""],
["","","","you said it's never too late to get started, right?","","","","","",""],
["","numa","","absolutely!","","","","","",""],
["","","","umm, i have been meaning to weed the park for a while","","","","","",""],
["","","","do you want to help with that?","","","","","",""],
["","","","it can be sort of strenuous work...","","","","","",""],
["","elijah","","nah, that sounds perfect.","","","","","",""],
["","","","a little bit of exercise would probably be good for my bones.","","","","","",""],
["","_none",['elijah_neutral', 'numa_neutral', 'sean_neutral'],"you bump into sean in the hallway.","_goto_hallway1","","","","",""],
["","sean","","whoa, coming through, haha","","","","","",""],
["","elijah","","hey, sean! great job with your song today.","","","","","",""],
["","sean","","heyyy, thanks elijah my right hand man!","","","","","",""],
["","","","your poem was really dope too","","","","","",""],
["","elijah","","you think so?","","","","","",""],
["","sean","","oh yeah, i loved that bit, uh","","","","","",""],
["","","","moss growing on your shoulders or whatever","","","","","",""],
["","","","very poetic","","","","","",""],
["","elijah","","aw, thanks, man","","","","","",""],
["","","","i worked hard on it.","","","","","",""],
["","sean","","um, sucks that you had to go through all that, though.","","","","","",""],
["","","","military and stuff","","","","","",""],
["","elijah","","oh, it's old news. old news.","","","","","",""],
["","","","it's just nice to get it out of my head and into the air sometimes","","","","","",""],
["","sean","","yeah, i get that!","","","","","",""],
["","","","i feel the same way about my song!","","","","","",""],
["","","","even though dani can't really hear me, it still feels nice getting it out there","","","","","",""],
["","elijah","","heh. that's what's up.","","","","","",""],
["","sean","","and um","","","","","",""],
["","","","sorry about breaking that statue","","","","","",""],
["","elijah","","oh, i couldn't care less about that.","","","","","",""],
["","","","sorry for grilling you so hard about it.","","","","","",""],
["","sean","","nahhh, i totally overreacted","","","","","",""],
["","","","that's on me","","","","","",""],
["","you","","uh, sorry to interrupt, but--","","","","","",""],
["","_none","","you lurch as you nearly lose your grip on the potted plant. ","","","","","",""],
["","you","","whoa!","","","","","",""],
["","_none","","sean helps you steady your grip.","","","","","",""],
["","sean","","dang, careful!","","","","","",""],
["","","","want me to get that for you?","","","","","",""],
["","you","","oh no, i'm fine!","","","","","",""],
["","sean","","dude, you've done so much shit for us recently","","","","","",""],
["","","","lemme hold a plant for you it's cool","","","","","",""],
["","you","","well... if you insist","","","","","",""],
["","_none","","you carefully transfer the plant to sean's arms.","","","","","",""],
["","sean","","oof, that's heavier than it looks","","","","","",""],
["","","","where we going, numa?","","","","","",""],
["","numa","","to the garden!","","","","","",""],
["","_none","elijah_neutral","as the other stagger away, elijah lags behind.","","","","","",""],
["","elijah","","hey, master of ceremonies.","","","","","",""],
["","","","just wanted to say thanks one more time.","","","","","",""],
["","you","","no problem!","","","","","",""],
["","elijah","","not just for helping organize. ","","","","","",""],
["","","","for being a friend.","","","","","",""],
["","you","","aw, well--","","","","","",""],
["","sean","","ELIJAH, you coming??","","","","","",""],
["","elijah","","yeah, i'm coming!","","","","","",""],
["","","","seeya, man.","","","","","",""],
["","you","","seeya!","","","","","",""],
["","_none","_none","elijah winks and hurries away.",[['_delay__goto_flashback_elijah', true], ['_delay_elijah_quest_complete', true], ['_delay_sean_quest_complete', true], ['elijah_and_sean_together', true], ['slam_in_session', false], ['post_slam', false]],"","null","","",""],
["end_flashback","you","","...","","","","","",""],
["","_none","","you pick yourself up from the ground.","","","null","","",""],
["slam_phone","_none","_none","it would be rude to make a call right now!","","","null","","",""],
["slam_exit","","","_pass","","post_slam",['slam_try_to_leave', 'slam_exit1'],"","",""],
["slam_exit1","_none","_none","you should probably stick around until the slam is over.","","","null","","",""],
["slam_planks","_none","_none","some planks for tori to break.","","","null","","",""],
["slam_planks2","_none","_none","these planks were absolutely decimated.","","","null","","",""],
["slam_kyungsoon_art","_none","_none","a drawing of kyungsoon.","","","null","","",""],
["slam_doggers","_none","_none","a dog making a silly face.","","","null","","",""],
["slam_s","_none","_none","a cool S.","","","null","","",""],
["slam_building","_none","_none","a drawing of an apartment block.","","","null","","",""],
["slam_research_poster","_none","_none","a very detailed research poster.","","","","","",""],
["","","","it's titled \"meow, meow, meow: making sense of the nonsensical\"","","","null","","",""],
["slam_books","_none","_none","some books.","","","null","","",""],
["slam_saturn","_none","_none","saturn.","","","null","","",""],
["slam_earth","_none","_none","earth.","","","null","","",""],
["slam_donut","_none","_none","a jelly donut.","","","","","",""],
["","","","you [i]donut[/i] really understand how this relates to the other two...","","","null","","",""],
["slam_streamers","","","_pass","","looking_for_poem or post_slam",['slam_streamers2', 'slam_streamers1'],"","",""],
["slam_streamers1","_none","_none","dang, they put up streamers and everything!","","","null","","",""],
["slam_streamers2","_none","_none","streamers.","","","null","","",""],
["slam_potted_plant1","_none","_none","a medium-sized potted plant.","","","null","","",""],
["slam_potted_plant2","_none","_none","a large potted plant.","","","null","","",""],
["slam_tools","_none","_none","some gardening tools.","","","null","","",""],
["slam_seeds","_none","_none","seeds.","","","","","",""],
["","","","this must be a [i]seedy[/i] neighborhood.","","","null","","",""],
["slam_carrots","_none","_none","carrots?","","","","","",""],
["","","","where did those come from?","","","null","","",""],
["slam_rocket","_none","_none","a moth on a spaceship.","","","null","","",""],
["slam_swirl","_none","_none","a swirly thing.","","","null","","",""],
["slam_lab","_none","_none","a lab in a cab.","","","null","","",""],
["slam_pug","_none","_none","a pug in a mug.","","","null","","",""],
["slam_dane","_none","_none","what's this one supposed to be?","","","","","",""],
["","","","...","","","","","",""],
["","","","ohhh.","","","","","",""],
["","","","a great dane in a freight train.","","","null","","",""],
["slam_sleepy","_none","_none","aww, what a sleepy kitty!","","","null","","",""],
["slam_shapes","","","_pass","","looking_for_poem or post_slam",['slam_shapes2', 'slam_shapes1'],"","",""],
["slam_shapes1","_none","_none","some shapes and stuff.","","","","","",""],
["","","","this is [i]shape[/i]-ing up to be a great slam!","","","null","","",""],
["slam_shapes2","_none","_none","some shapes and stuff.","","","null","","",""],
["slam_poster","_none","_none","it's the purrgatory everything slam!","","","null","","",""],
["slam_city","_none","_none","a drawing of a city.","","","null","","",""],
["slam_bagel","_none","_none","a drawing of a bagel.","","","null","","",""],
["slam_piano","_none","_none","the meow piano.","","","null","","",""],
["slam_chairs","_none","_none","someone set up these chairs very nicely.","","","","","",""],
["","","","they must have been feeling [i]chair-[/i]itable!","","","null","","",""],
["slam_stool","_none","_none","a stool in a world of chairs.","","","null","","",""],
["slam_poster_after","_none","_none","the everything slam lives on in your memory.","","","null","","",""],
["slam_research_poster_after","_none","_none","oliver's research poster from the everything slam.","","","null","","",""]
]