extends Node

var raw_blocks = [
["tori_visiting_oliver","_none",['tori_neutral', 'oliver_neutral'],"tori leads you to the study.","_goto_study","","","","",""],
["","tori","","oliver. good to see you.","tori_visited_oliver","","","","",""],
["","oliver","","huh?","","","","","",""],
["","","","oh, tori. good to see you!","","","","","",""],
["","","","can i help you with something? looking for a book?","","","","","",""],
["","tori","","no offense, but it'll take a few more years before i get bored enough to read one of your books.","","","","","",""],
["","oliver","","eheh. right.","","","","","",""],
["","tori","","i'm just checking in. {player} tells me you're on another wild goose chase?","","","","","",""],
["","you","","well, i didn't say [i]that[/i], exactly...","","","","","",""],
["","oliver","","no, no. i understand. ","","","","","",""],
["","","","i know it sounds far-fetched.","","","","","",""],
["","","","but i've never seen anything written in these books before -- you see, one of the \"meows\" is circled on page 86 and--","","","","","",""],
["","tori","","spare me the details. {player} told me all about it.","","","","","",""],
["","oliver","","ah, i see.","","","","","",""],
["","tori","","i'm guessing this means you'll be locked up in your study for the next month or so?","","","","","",""],
["","oliver","","hopefully less than that!","","","","","",""],
["","","","but, if that's what it takes...","","","","","",""],
["","tori","","i'm also guessing that our chess game is on hold?","","","","","",""],
["","oliver","","well","","","","","",""],
["","","","i don't really have time to play right now. sorry.","","","","","",""],
["","_none","","tori eyes oliver for a moment, then shrugs.","","","","","",""],
["","tori","","no worries. we have until eternity to finish it. ","","","","","",""],
["","","","or until i find a way out of here.","","","","","",""],
["","","","whichever comes first.","","","","","",""],
["","oliver","","maybe if i get through my to-do list...","","","","","",""],
["","","","where did i put that again?","","","","","",""],
["","","","i'm sure i can make some time--","","","","","",""],
["","_none","","oliver sends a pile of books tumbling onto the ground","","","","","",""],
["","oliver","","ack!","","","","","",""],
["","","","","","","","",['you look tired', 'i think you need to tidy up a little'],['tori_tired', 'tori_clean']],
["tori_tired","you","","are you alright? you look tired","","","","","",""],
["","tori","","no kidding.","","","","","",""],
["","oliver","","i'm fine, i'm fine!","","","","","",""],
["","","","just... a little disoriented, is all","","","tori_visiting_oliver2","","",""],
["tori_clean","you","","i think you need to tidy up a little","","","","","",""],
["","tori","","no kidding.","","","","","",""],
["","oliver","","i swear it's not usually this bad!","","","","","",""],
["","","","cleaning just hasn't been... the highest priority, recently","","","","","",""],
["tori_visiting_oliver2","you","","are you sure you don't need a rest? ","","","","","",""],
["","","","maybe you can take a break to play chess or something.","","","","","",""],
["","oliver","","don't worry about me. i'm indefatiguable.","","","","","",""],
["","you","","indefa-what?","","","","","",""],
["","oliver","","indefatiguable. tireless.","","","","","",""],
["","tori","","suuure, it's not that you're avoiding the game because you know your queen is as good as mine.","","","","","",""],
["","oliver","","don't be ridiculous!","","","","","",""],
["","","","the weak points in your pawn structure are almost too easy to exploit. ","","","","","",""],
["","","","we'll see what good your extra knight does when your king is left defenseless on the back rank!","","","","","",""],
["","tori","","alright, alright. spare me the master plan.","","","","","",""],
["","","","i'm gonna get going, alright?","","","","","",""],
["","","","do your work. i'll do mine. one of these days we'll find something important.","","","","","",""],
["","oliver","","will do.","","","","","",""],
["","tori","","see you, {player}.","","","","","",""],
["","you","","cya","","","null","","",""],
["tori_train","???","tori_neutral","{player}.","met_tori","","","","",""],
["","","","i've been expecting you.","","","","","",""],
["","","","","","","","",['huh???', 'as have i'],['tori_train1', 'tori_train2']],
["tori_train1","you","","huh??","","","","","",""],
["","","","how did you know my name?","","","","","",""],
["","???","","it says on the screen!","","","","","",""],
["","_none","","you look at the ARRIVALS screen, which has only one entry, listing your name and the day you died.","","","","","",""],
["","you","","oh, weird","","","","","",""],
["","???","","yes, your name appeared on this screen a week ago, and i've been expecting you since.","","","","","",""],
["","","","actually, i expected you to show up in a train","","","","","",""],
["","","","but god forbid anything in this place make sense.","","","","","",""],
["","you","","i see...","","","","","",""],
["","???","","my name is tori!","","","tori_train3","","",""],
["tori_train2","you","","as have i...","","","","","",""],
["","","","...amelia?","","","","","",""],
["","???","","nice try. my name is tori.","","","","","",""],
["","you","","damn, i was close","","","","","",""],
["","","","but wait, how did you know my name?","","","","","",""],
["","tori","","it says on the screen!","","","","","",""],
["","_none","","you look at the \"arrivals\" screen, which has only one entry, listing your name.","","","","","",""],
["","you","","oh, weird","","","","","",""],
["","tori","","yes, your name appeared on this screen a week ago, and i've been expecting you since.","","","","","",""],
["","","","actually, i expected you to show up in a train","","","","","",""],
["","","","but god forbid anything in this place make sense.","","","","","",""],
["","you","","i see...","","","","","",""],
["","tori","","as you know, my name is tori!","","","","","",""],
["tori_train3","tori","","entrepreneur, black belt, and deceased soul.","","","","","",""],
["","","","if you don't mind, i have some questions for you.","","","","","",""],
["","_none","","tori lifts a clipboard.","","","","","",""],
["","you","","oh, uh, ok, i guess","","","","","",""],
["","tori","","one. who are you, and how did you arrive here?","","","","","",""],
["","","","","","","","",['tell the truth', 'lie'],['tori_train4', 'tori_train5']],
["tori_train4","you","","i woke up in an office with an old lady, who said i was going to purrgatory?","","","","","",""],
["","","","then i went through a portal and ended up here","","","","","",""],
["","tori","","checks out.","","","tori_train6","","",""],
["tori_train5","you","","i'm the devil!","","","","","",""],
["","tori","","really.","","","","","",""],
["","you","","yes, i'm here to deliver judgement on you lost souls","","","","","",""],
["","tori","","...uh huh. and i'm the archangel gabriel.","","","","","",""],
["","","","not that i have anything against role playing, but how did you really get here?","","","","","",""],
["","you","","oh uh","","","","","",""],
["","","","i woke up in an office with an old lady, who sent me through a portal","","","","","",""],
["","tori","","there, that wasn't so hard, was it?","","","","","",""],
["tori_train6","tori","","two. what did you do for a living?","","","","","",""],
["","you","","i don't remember...","","","","","",""],
["","tori","","reeeeally.","","","","","",""],
["","you","","really!","","","","","",""],
["","","","i woke up without any memories, i swear","","","","","",""],
["","tori","","hmm","","","","","",""],
["","_none","","tori flips through her clipboard.","","","","","",""],
["","tori","","well, that cancels out most of the rest of my questions. ugh.","","","","","",""],
["","","","one last question. what do you think THAT means?","","","","","",""],
["","_none","","she points at the \"departures\" screen, which says \"heaven: delayed\"","","","","","",""],
["","","","","","","","",["it means they'll let us out soon", "it means we're stuck here"],['tori_train7', 'tori_train8']],
["tori_train7","you","","oh, maybe it means they'll let us out soon!","","","","","",""],
["","tori","","an optimist, huh?","","","","","",""],
["","","","that's good. you'll need that.","","","tori_train9","","",""],
["tori_train8","you","","maybe it means we'll be stuck here for a while?","","","","","",""],
["","tori","","a realist, huh?","","","","","",""],
["","","","i'm the same.","","","","","",""],
["tori_train9","tori","","but I'M not interested in standing around and waiting for some celestial being to have mercy on me.","","","","","",""],
["","","","i'm trying to break out of here, and i think that sign means i'm close.","","","","","",""],
["","","","can i count on your help??","","","","","",""],
["","","","","","","","",["maaaybe", "sure!"],['tori_train10', 'tori_train11']],
["tori_train10","you","","maaaaaybe?","","","","","",""],
["","tori","","alright, i'll take it.","","","tori_train12","","",""],
["tori_train11","you","","sure!","","","","","",""],
["","tori","","that's the spirit!","","_inv_chess_letter",['tori_train11a', 'tori_train12'],"","",""],
["tori_train11a","","","","","","","",['(deliver oliver\'s letter)', '(wait \'til later)'],['tori_chess', 'tori_train12']],
["tori_train12","tori","","i'll see you around, colleague.","","","","","",""],
["","you","","cya!","tori_train_complete","","null","","",""],
["tori_park_intro","","","_pass","",['park_game', 'talked_to_tori_park'],['tori_park_tori', 'tori_park_intro_b', 'tori_park_intro_a'],"","",""],
["tori_park_intro_a","tori","tori_neutral","{player}! just the person i wanted to see.","talked_to_tori_park","","","","",""],
["","you","","oh wow","","","","","",""],
["","","","are you trying to... dig out of purrgatory?","","","","","",""],
["","tori","","what do you think i'm doing?","","","","","",""],
["","","","digging a latrine?","","","","","",""],
["","you","","but aren't you, like...","","","","","",""],
["","","","going the wrong direction?","","","","","",""],
["","tori","","eh, it's worth a shot.","","","","","",""],
["","","","if i end up in hell, i'll just march up to the devil's throne and give him a piece of my mind.","","","","","",""],
["","","","want to grab a shovel?","","","","","",""],
["","","","","","","",['true', 'true', '_inv_chess_letter'],['alright', 'maybe later', '(deliver oliver\'s letter)'],['tori_park_intro1', 'tori_park_intro2', 'tori_chess']],
["tori_park_intro1","you","","alright, i [i]dig[/i] it!","","","","","",""],
["","tori","","hilarious.","","","","","",""],
["","","","here's your shovel. knock yourself out","","","","","",""],
["","","","not literally. i already have enough problems as is.","","","","","",""],
["","you","","i'll try!","","","","","",""],
["","tori","","i'm not going to lie, i've been digging up some weird stuff...","","","","","",""],
["","","","just dig in as many places as possible, until you find something interesting.","","","","","",""],
["","","","got it?","","","","","",""],
["","you","","sounds easy enough!","","","","","",""],
["","_none","","(explore the park and click on hotspots on the ground to dig!)","_delay_start_park_game","","null","","",""],
["tori_park_intro2","you","","maybe later!","","","","","",""],
["","tori","","suit yourself.","","","null","","",""],
["tori_park_intro_b","tori","tori_neutral","you're back. want to lend a hand?","","","","","",""],
["","you","","can't we just chat...?","","","","","",""],
["","tori","","if you haven't noticed, i'm a little busy.","","","","","",""],
["","","","now are you going to help or not?","","","","","",""],
["","","","","","","",['true', 'true', '_inv_chess_letter'],['alright', 'maybe later', '(deliver oliver\'s letter)'],['tori_park_intro1', 'tori_park_intro2', 'tori_chess']],
["tori_park_tori","you","tori_neutral","how's it going?","","","","","",""],
["","tori","","not great, but i'm not giving up yet.","","","","","",""],
["","","","i'm not afraid to get my hands dirty if it means escaping.","","","","","",""],
["","","","or a lot dirty.","","","","","",""],
["","","","wish i had gloves.","","","null","","",""],
["tori_park_rock","_none","","you found...","increment_holes","","","","",""],
["","","dig_rock","a rock!","","","","","",""],
["","you","","that doesn't rock.","_dug_rock","hole_count == 16",['tori_park_ending', 'null'],"","",""],
["tori_park_coin","_none","","you found...","increment_holes","","","","",""],
["","","dig_coin","a coin!","","","","","",""],
["","you","","buried coins? that doesn't even make cents.","_dug_coin","hole_count == 16",['tori_park_ending', 'null'],"","",""],
["tori_park_can","_none","","you found...","increment_holes","","","","",""],
["","","dig_can","a can of beans!","","","","","",""],
["","you","","i can-t believe it!","","","","","",""],
["","tori",['dig_can', 'tori_neutral'],"hey, i love beans!","","","","","",""],
["","","","let me see that.","","","","","",""],
["","","","...","","","","","",""],
["","","","apparently this expired in 500 AD.","","","","","",""],
["","you","","oh","_dug_can","hole_count == 16",['tori_park_ending', 'null'],"","",""],
["tori_park_bone","_none","","you found...","increment_holes","","","","",""],
["","","dig_bone","a bone!","","","","","",""],
["","you","","i have a bone to pick with this place.","","","","","",""],
["","tori",['dig_bone', 'tori_neutral'],"you said it.","_dug_bone","hole_count == 16",['tori_park_ending', 'null'],"","",""],
["tori_park_kyungsoon","_none","","you found...","increment_holes","","","","",""],
["","","kyungsoon_neutral","kyungsoon!","","","","","",""],
["","you","","kyungsoon????","","","","","",""],
["","kyungsoon","","sup","","","","","",""],
["","you","","what are you doing in the ground??","","","","","",""],
["","kyungsoon","","idk","","","","","",""],
["","","","just chilling","","","","","",""],
["","tori",['kyungsoon_neutral', 'tori_neutral'],"kyungsoon, do you want to help us dig?","","","","","",""],
["","kyungsoon","","i'd rather read one of oliver's books","","","","","",""],
["","tori","","that's fair","","","","","",""],
["","you","","???","","","","","",""],
["","kyungsoon","","i'm going to go back to the commons now","","","","","",""],
["","tori","","take care","_dug_kyungsoon","hole_count == 16",['tori_park_ending', 'null'],"","",""],
["tori_park_worm","_none","","you found...","increment_holes","","","","",""],
["","","dig_worm","a worm!","","","","","",""],
["","tori",['dig_worm', 'tori_neutral'],"what do you think that worm did to end up in purrgatory?","","","","","",""],
["","you","","hmm....","","","","","",""],
["","","","assault and bug-tery?","","","","","",""],
["","tori","","i'm sorry i asked","_dug_worm","hole_count == 16",['tori_park_ending', 'null'],"","",""],
["tori_park_diamond","_none","","you found...","increment_holes","","","","",""],
["","","dig_diamond","a diamond!","","","","","",""],
["","you","","holy shit","","","","","",""],
["","tori",['dig_diamond', 'tori_neutral'],"is that a diamond?","","","","","",""],
["","you","","yeah, i think so","","","","","",""],
["","","","do you think it's real?","","","","","",""],
["","tori","","hold it up to your mouth and breathe on it. if the fog disperses immediately, it's real.","","","","","",""],
["","_none","","you breathe on the stone.","","","","","",""],
["","you","","it's real!","","","","","",""],
["","","","we found a real diamond!!","","","","","",""],
["","tori","","great.","","","","","",""],
["","","","but what are we going to do with it?","","","","","",""],
["","you","","uh","","","","","",""],
["","","","idk","","","","","",""],
["","tori","","give it to kyungsoon","","","","","",""],
["","","","maybe she'll eat it.","_dug_diamond","hole_count == 16",['tori_park_ending', 'null'],"","",""],
["tori_park_foot","_none","","you found...","increment_holes","","","","",""],
["","","dig_foot","a foot!","","","","","",""],
["","you","","...i'm just going to leave that where i found it","","","","","",""],
["","tori",['dig_foot', 'tori_neutral'],"you mean you're not going to [i]toe[/i] it away?","","","","","",""],
["","you","","wait, was that a pun??","","","","","",""],
["","tori","","oh god","","","","","",""],
["","","","you're rubbing off on me","_dug_foot","hole_count == 16",['tori_park_ending', 'null'],"","",""],
["tori_park_fridge","_none","","you found...","increment_holes","","","","",""],
["","","dig_fridge","a mini fridge!","","","","","",""],
["","you","","i was starting to get hot, so good thing we found something that's a [i]little cooler[/i]!","_dug_fridge","hole_count == 16",['tori_park_ending', 'null'],"","",""],
["tori_park_shovel","_none","","you found...","increment_holes","","","","",""],
["","","dig_shovel","a shovel!","","","","","",""],
["","you","","huh?","","","","","",""],
["","tori","tori_neutral","a buried shovel. ironic.","_dug_shovel","hole_count == 16",['tori_park_ending', 'null'],"","",""],
["tori_park_robot","_none","","you found...","increment_holes","","","","",""],
["","","dig_robot","a toy robot!","","","","","",""],
["","you","","something a-bot this doesn't feel right","_dug_robot","hole_count == 16",['tori_park_ending', 'null'],"","",""],
["tori_park_ukulele","_none","","you found...","increment_holes","","","","",""],
["","","dig_ukulele","a ukulele!","","","","","",""],
["","you","","uke gotta be kidding me.","","","","","",""],
["","tori",['dig_ukulele', 'tori_neutral'],"i used to play the ukulele!","","","","","",""],
["","","","in fact, i directed my school's ukulele ensemble.","","","","","",""],
["","you","","oh, do you want it?","","","","","",""],
["","tori","","no thanks. i'm afraid it'll somehow make meow noises.","_dug_ukulele","hole_count == 16",['tori_park_ending', 'null'],"","",""],
["tori_park_nothing","_none","","you found...","increment_holes","","","","",""],
["","","","nothing!","","","","","",""],
["","you","","boo","_dug_nothing","hole_count == 16",['tori_park_ending', 'null'],"","",""],
["tori_park_clock","_none","","you found...","increment_holes","","","","",""],
["","","dig_clock","a cat-themed clock!","","","","","",""],
["","you","","that is creepy.","_dug_clock","hole_count == 16",['tori_park_ending', 'null'],"","",""],
["tori_park_chess","_none","","you found...","increment_holes","","","","",""],
["","","dig_chess","a cat-themed chess piece!","","","","","",""],
["","you","","i'm starting to get a little board.","","","","","",""],
["","tori",['dig_chess', 'tori_neutral'],"need a break?","","","","","",""],
["","you","","oh, no, that was just a pun","","","","","",""],
["","tori","","oh. should have figured.","_dug_chess","hole_count == 16",['tori_park_ending', 'null'],"","",""],
["tori_park_snowglobe","_none","","you found...","increment_holes","","","","",""],
["","","dig_snowglobe","a snowglobe!","","","","","",""],
["","you","","oh, cool, a snowglobe!","_dug_snowglobe","hole_count == 16",['tori_park_ending', 'null'],"","",""],
["tori_park_ending","numa",['tori_neutral', 'numa_neutral'],"TORI!!!","surprise_audio","","","","",""],
["","","","WHAT THE HELL ARE YOU DOING?!","","","","","",""],
["","tori","","oh, just trying to save us all. you're welcome.","","","","","",""],
["","numa","","YOU'RE RUINING THE PARK!","","","","","",""],
["","tori","","debatable.","","","","","",""],
["","","","did you miss the part about saving us all?","","","","","",""],
["","numa","","WEEDING THIS PARK TAKES AGES!","","","","","",""],
["","","","oh my god how many holes did you dig??","","","","","",""],
["","tori","","ummm...","","","","","",""],
["","","","about a dozen?","","","","","",""],
["","","","","","","","",["i'm so sorry", "it's for the best"],['tori_park_ending1', 'tori_park_ending2']],
["tori_park_ending1","you","","i'm so sorry, i didn't even think about the damage we're doing...","","","","","",""],
["","numa","","of COURSE you didn't!!","","","tori_park_ending3","","",""],
["tori_park_ending2","you","","tori's right, it's for the best...","","","","","",""],
["","numa","","well, you could have at least ASKED!!","","","","","",""],
["tori_park_ending3","_none","","numa closes her eyes","","","","","",""],
["","numa","","ok...","","","","","",""],
["","","","deep breaths, numa...","","","","","",""],
["","tori","","listen, i'm sorry. i'll make it up to you, somehow.","","","","","",""],
["","","","leave {player} out of it, at least. it was my idea.","","","","","",""],
["","numa","","fine.","","","","","",""],
["","","","we'll talk about this. ","","","","","",""],
["","","","later.","","","","","",""],
["","","","after i cool down.","","","","","",""],
["","_none","tori_neutral","numa stomps away.","","","","","",""],
["","tori","","...","","","","","",""],
["","","","sheesh","","","","","",""],
["","player","","whoops...","","","","","",""],
["","tori","","my bad, {player}. this plan was a bust, anyway.","","","","","",""],
["","you","","i guess it wasn't a very [i]hole[/i]-some plan","","","","","",""],
["","tori","","you can say that again.","","","","","",""],
["","","","i'll see you around, okay?","","","","","",""],
["","you","","okay...","tori_park_complete","","","","",""],
["","tori","","stay sharp.","_delay_remove_park_game","","null","","",""],
["tori_park_leave","_none","","you should probably finish helping tori before you leave.","","","null","","",""],
["tori_park_hole","_none","","one of the holes you dug.","","","null","","",""],
["tori_closet","","","_pass","","talked_to_tori_closet",['tori_closet1', 'tori_closet2'],"","",""],
["tori_closet1","tori","tori_neutral","you're back.","","","","","",""],
["","","","now are you free?","","","","","",""],
["","","","","","","",['true', 'true', '_inv_chess_letter'],['affirmative', 'later', '(deliver oliver\'s letter)'],['tori_closet3', 'tori_closet4', 'tori_chess']],
["tori_closet2","tori","tori_neutral","ah, my favorite sinner.","talked_to_tori_closet","","","","",""],
["","","","wear these. you'll need it.","","","","","",""],
["","_none","","she hands you a pair of heavy-duty gloves.","","","","","",""],
["","you","","what's up now?","","","","","",""],
["","tori","","electricity. it makes the world go round. ","","","","","",""],
["","","","and also purrgatory, presumably.","","","","","",""],
["","you","","oh, this must be where purrgatory's electricity comes from!","","","","","",""],
["","tori","","yes, great deduction.","","","","","",""],
["","","","these wires have to be hooked up to something, and that something is outside of purrgatory.","","","","","",""],
["","","","first step is to figure out how this box works!","","","","","",""],
["","","","think you can help?","","","","","",""],
["","","","","","","",['true', 'true', '_inv_chess_letter'],['affirmative', 'later', '(deliver oliver\'s letter)'],['tori_closet3', 'tori_closet4', 'tori_chess']],
["tori_closet4","you","","umm, maybe later","","","","","",""],
["","","","i'm not really keen on messing with electricity...","","","","","",""],
["","tori","","you do you.","","","null","","",""],
["tori_closet3","you","","sure, i'll do my best!","","","","","",""],
["","tori","","perfect.","","","","","",""],
["","","","here, take a look.","","","","","",""],
["tori_wire_intro","tori","_none","now, i'm no amateur at electrical engineering, but i've never seen a circuit like this before.","_goto_wire_game","","","","",""],
["","","","maybe something will happen if you connect the nodes?","","","","","",""],
["","you","","are you sure this is safe??","","","","","",""],
["","tori","","fairly sure. let's say 90%.","","","","","",""],
["","_none","","(click on a node and drag to create a wire!)","","","null","","",""],
["tori_wire_blackout","you","","uh oh","","","","","",""],
["","tori","tori_neutral","{player}, what did you do??",['_goto_closet', '_hide_tori_closet'],"","","","",""],
["","you","","i don't know! i just messed with the wires!","","","","","",""],
["","tori","","looks like the power's out all over purrgatory.","","","","","",""],
["","","","great. juuust what we needed.","","","","","",""],
["","you","","umm, maybe if we undo what i did, the lights will turn back on?","","","","","",""],
["","","","if it's not too dark to see the wires...","","","","","",""],
["","tori","","well, it's a good thing i can see in the dark!","","","","","",""],
["","","","go look for another source of light, like a flashlight or something. i'll keep messing around with this.","","","","","",""],
["","you","","oh, okay","","","","","",""],
["","","","but...","","","","","",""],
["","","","um...","","","","","",""],
["","tori","","but what?","","","","","",""],
["","you","","it's kind of spooky out there...","","","","","",""],
["","tori","","sigh","","","","","",""],
["","","","i think you'll be fine.","","","","","",""],
["","you","","okay...","","","null","","",""],
["tori_blackout","","","_pass","","_inv_candle",['tori_blackout2', 'tori_blackout1'],"","",""],
["tori_blackout1","tori","tori_neutral","any luck finding a light?","","","","","",""],
["","you","","no...","","","","","",""],
["","tori","","well, hurry up, we don't have all eternity!","","","","","",""],
["","","","hmm... maybe if i connect these two...","","","null","","",""],
["natalie_blackout","","","_pass","","_inv_candle",['natalie_blackout2', 'natalie_blackout1'],"","",""],
["natalie_blackout1","you","natalie_neutral","you have candles!!","","","","","",""],
["","natalie","","yeah i do!!","","","","","",""],
["","","","this is the first time i've ever gotten the chance to actually use them","","","","","",""],
["","","","i am very happy","","","","","",""],
["","you","","you're happy the lights are out?","","","","","",""],
["","natalie","","well, yeah","","","","","",""],
["","","","the ambience is way better now","","","","","",""],
["","","","makes me want to take a niiiice, long nap","","","","","",""],
["","you","","nice!","","","","","",""],
["","","","can i borrow one of ur candles btw","","","","","",""],
["","natalie","","sure, what for?","","","","","",""],
["","you","","oh, tori and i were messing with the electricity when the lights turned off","","","","","",""],
["","natalie","","heh, that must have been a nasty surpr-eyes","","","","","",""],
["","","","take as many as you want!","","","","","",""],
["","","","but no rush in turning the lights back on, alright?","","","","","",""],
["","you","","we'll see","_delay__inv_candle","","null","","",""],
["natalie_blackout2","you","natalie_neutral","enjoying your candles?","","","","","",""],
["","natalie","","zzz.... hm?","","","","","",""],
["","","","oh yeah","","","","","",""],
["","","","love em","","","null","","",""],
["elijah_blackout","","","_pass","",['met_elijah', '_pronouns_she'],['elijah_blackout1', 'es_intro', 'es_intro1'],"","",""],
["elijah_blackout1","elijah","elijah_neutral","lights are out.","","","","","",""],
["","","","think it's a sign of the end times?","","","","","",""],
["","you","","um i think it's more a sign of tori and i were messing with the electricity","","","","","",""],
["","elijah","","oh.","","","","","",""],
["","","","that makes sense too","","","null","","",""],
["numa_blackout","","","_pass","",['not met_numa', 'trample_flag'],['numa_intro1', 'numa_intro2', 'numa_blackout1'],"","",""],
["numa_blackout1","numa","numa_neutral","the lights went out...","","","","","",""],
["","you","","sorry, that was my fault","","","","","",""],
["","numa","","oh it's alright","","","","","",""],
["","","","i just hope my flowers will be okay...","","","null","","",""],
["kyungsoon_blackout","you","kyungsoon_neutral","hey","","","","","",""],
["","kyungsoon","","hey","","","","","",""],
["","you","","it's dark","","","","","",""],
["","kyungsoon","","yep","","","","","",""],
["","you","","how do you feel about that?","","","","","",""],
["","kyungsoon","","eh","","","null","","",""],
["oliver_blackout","oliver","oliver_neutral","{player}! the lights went out in the middle of a CRUCIAL part of my research!","","","","","",""],
["","","","do you have any clue what's going on??","","","","","",""],
["","you","","sorry, that was my fault!","","","","","",""],
["","","","tori and i were messing with the electricity","","","","","",""],
["","oliver","","oh, really?","","","","","",""],
["","you","","we're trying to fix it!","","","","","",""],
["","oliver","","please do","","","","","",""],
["","","","i can't read a single meow under these conditions!","","","null","","",""],
["sean_blackout","","","_pass","",['met_sean', '_pronouns_she'],['sean_blackout1', 'es_intro', 'es_intro1'],"","",""],
["sean_blackout1","sean","sean_neutral","ayyy, {player}, my funky friend!","","","","","",""],
["","","","the lights went out, how rad is that?","","","","","",""],
["","you","","pretty rad, i guess","","","","","",""],
["","sean","","that's the spirit ","","","","","",""],
["","","","my pugnacious pal!","","elijah_and_sean_together",['sean_blackout2', 'null'],"","",""],
["sean_blackout2","elijah",['elijah_neutral', 'sean_neutral'],"i don't think pugnacious means what you think it does, sean","","","","","",""],
["","sean","","oh, whatever. it sounds cool.","","","null","","",""],
["elijah_blackout_nap","_none","","you should probably fix the lights before bothering elijah.","","","null","","",""],
["oliver_blackout_nap","_none","","you should probably fix the lights before bothering oliver.","","","null","","",""],
["tori_blackout2","you","tori_neutral","i brought a candle!","","","","","",""],
["","tori","","great!","","","","","",""],
["","","","hopefully you'll be able to make heads or tails of this, because i certainly can't.","","","","","",""],
["","you","","i'll take a look, but no promises...","","","","","",""],
["","","_none","(click on a node and drag to create a wire!)",[['_goto_wire_game', true], ['start_skip_timer', true]],"","null","","",""],
["tori_wire_skip","tori","","whoa, how did you do that?","tori_closet_complete","","","","",""],
["","you","","uhhh idk","","","","","",""],
["","","","a little shelf popped out of the side and i pressed a button and the lights came back on.","","","","","",""],
["","tori","","huh","","","","","",""],
["","","","not the weirdest thing i've seen all day.","","","tori_wire_success1","","",""],
["tori_wire_success","tori","","hey, you actually did it!","tori_closet_complete","","","","",""],
["","","","not bad. not bad at all.","","","","","",""],
["","you","","it wasn't that bad, you just had to connect the nodes!","","","","","",""],
["","tori","","you're practically an engineer already.","","","","","",""],
["tori_wire_success1","","tori_neutral","well, guess we're back to square one, huh?","_goto_closet","","","","",""],
["","you","","i don't really want to mess with it any more...","","","","","",""],
["","tori","","yeah, maybe we should quit while we're ahead.","","","","","",""],
["","","","we might have lost this battle, but i'm not out of ideas yet.","","","","","",""],
["","","","not nearly.","","","","","",""],
["","","","i'll see you around, okay?","","","","","",""],
["","you","","okay!","","","","","",""],
["","tori","","don't be a stranger.","","","null","","",""],
["","_none","_none","guess there's no need to carry this candle around anymore.",[['_inv_candle', false]],"","","","",""],
["tori_dropoff","","","_pass","",['preparing_for_climb', 'talked_to_tori_dropoff'],['tori_dropoff8', 'tori_dropoff6', 'tori_dropoff_a'],"","",""],
["tori_dropoff_a","tori","tori_neutral","{player}! my favorite accomplice!","talked_to_tori_dropoff","","","","",""],
["","you","","um","","","","","",""],
["","","","do i want to ask what you're doing now?","","","","","",""],
["","tori","","the dropoff. a mystery that's been staring us in the face for far too long.","","","","","",""],
["","","","it's finally time to breach it.","","","","","",""],
["","you","","is it though??","","","","","",""],
["","","","that doesn't seem safe at all","","","","","",""],
["","tori","","don't worry, i've done my fair share of spelunking, so it'll be perfectly safe.","","","","","",""],
["","","","do you want to escape or not?","","","","","",""],
["","you","","i mean...","","","","","",""],
["","","","i guess so...","","","","","",""],
["","tori","","then listen up.","","","","","",""],
["","","","this shaft is too narrow for me or natalie to fly down. so instead i dug through the warehouse until i found this!","","","","","",""],
["","","","a hundred feet of strong, braided nylon rope. give or take a few.","","","","","",""],
["","","","one of us is going to go down there. the only question is which.","","","","","",""],
["","","","","","","","",['me', 'you', 'how about no one??'],['tori_dropoff1', 'tori_dropoff2', 'tori_dropoff3']],
["tori_dropoff1","you","","i'll do it.","","","","","",""],
["","","","if anyone's going to go down there, it should be me","","","","","",""],
["","tori","","why, exactly, should it be you?","","","","","",""],
["","you","","i mean, idk","","","","","",""],
["","","","i don't even remember my life","","","","","",""],
["","","","i have the least to lose!","","","","","",""],
["","tori","","hm","","","","","",""],
["","","","as much as i appreciate the bravado, i can't ask you to go down on a good conscience","","","","","",""],
["","","","so instead, i think we should flip a coin.","","","tori_dropoff4","","",""],
["tori_dropoff2","you","","umm","","","","","",""],
["","","","will you do it?","","","","","",""],
["","","","you're probably stronger than me...","","","","","",""],
["","tori","","i might, yes.","","","","","",""],
["","","","but in case of an emergency, shouldn't the person at the top be someone strong enough to pull up the other?","","","","","",""],
["","you","","oh yeah, that makes sense...","","","","","",""],
["","tori","","i think we should flip a coin.","","","tori_dropoff4","","",""],
["tori_dropoff3","you","","how about no one??","","","","","",""],
["","","","we don't need to risk our lives!","","","","","",""],
["","","","or, uh, our afterlives","","","","","",""],
["","tori","","sure, and what else would you rather do?","","","","","",""],
["","","","sit around until someone descends from on high to save us?","","","","","",""],
["","","","how would you feel if it turned out the exit was right in front of us the entire time?","","","","","",""],
["","you","","i mean...","","","","","",""],
["","","","i guess that makes sense...","","","","","",""],
["","tori","","i would volunteer to go down myself...","","","","","",""],
["","","","but on the other talon, the person at the top should probably be someone strong enough to pull up the other.","","","","","",""],
["","","","so i think we should flip a coin.","","","tori_dropoff4","","",""],
["tori_dropoff4","you","","a coin?","","","","","",""],
["","tori","","if it's heads, i'll go down. if it's tails, you go down.","","","","","",""],
["","","","that sounds fair, right?","","","","","",""],
["","you","","yeah, i guess that's fair","","","","","",""],
["","tori","","alright, then.","","","","","",""],
["","","","are you ready?","","","","","",""],
["","","","","","","",['true', 'true', '_inv_chess_letter'],['i think i have some other stuff to do', 'i guess so', '(deliver oliver\'s letter)'],['tori_dropoff5', 'tori_dropoff7', 'tori_chess']],
["tori_dropoff5","you","","actuallyyyy i think i have some other stuff to do or something...","","","","","",""],
["","tori","","alright. i'll be waiting.","","","","","",""],
["","","","i'm sure as hell not climbing down there alone.","","","null","","",""],
["tori_dropoff6","tori","tori_neutral","ready now?","","","","","",""],
["","","","","","","",['true', 'true', '_inv_chess_letter'],['i think i have some other stuff to do', 'i guess so', '(deliver oliver\'s letter)'],['tori_dropoff5', 'tori_dropoff7', 'tori_chess']],
["tori_dropoff7","you","","i guess so???","","","","","",""],
["","tori","","well, here goes nothing.","","","","","",""],
["","_none","","...","toss_coin","","","","",""],
["","tori","","tails. that's you.","","","","","",""],
["","you","","[i]gulp[/i]","","","","","",""],
["","tori","","don't worry! i know how to tie a harness.","","","","","",""],
["","","","don't ask why","","","","","",""],
["","","","hold your arms up?","","","","","",""],
["","_none","","you hold your arms up patiently while tori ties it around you.","","","","","",""],
["","tori","","there, that should hold you if you lose your grip.","","","","","",""],
["","","","but try to hold onto the rope if you can.","","","","","",""],
["","you","","alright...","","","","","",""],
["","tori","","i'll tie the rope around this post, but i'll keep a hold of it too.","","","","","",""],
["","","","it'll be perfectly safe!","","","","","",""],
["","you","","okay!","","","","","",""],
["","","","cool!","","","","","",""],
["","_none","","tori finishes tying the rope, then throws the slack down the hole. then she hands you a flashlight.","","","","","",""],
["","tori","","all set.","","","","","",""],
["","you","","do i just... climb down?","","","","","",""],
["","tori","","yes, that's the idea.","","","","","",""],
["","","","whenever you're ready.","preparing_for_climb","","null","","",""],
["tori_dropoff8","tori","tori_neutral","well? what are you waiting for?","","","","","",""],
["","","","heaven could be within our grasp!","","","","","",""],
["","you","","yeah! i guess!","","","","","",""],
["","","","it's kinda scary though...","","","","","",""],
["","tori","","i'll be right here, holding on tight.","","","null","","",""],
["tori_leave_dropoff","_none","","you couldn't leave even if you wanted to, because you're tied to the post.","","","null","","",""],
["tori_climb0","you","","alright, here goes nothing...","","","","","",""],
["","_none","","(press up and down to climb the rope!)","","","null","","",""],
["tori_climb1","tori","","see anything yet?","","","","","",""],
["","you","","not really!","","","null","","",""],
["tori_climb_snowglobe","you","","cool, a snowglobe!","","","","","",""],
["","tori","","sorry, a snowglobe?","","","","","",""],
["","you","","yeah, there was one sitting in an alcove in the wall!","","","","","",""],
["","tori","","strange.","","","null","","",""],
["tori_climb2","tori","","how about now?","","","","","",""],
["","you","","still nothing...","","","","","",""],
["","","","um, it's kinda dark down here.","","","","","",""],
["","tori","","gee, if only you had some sort of tool for producing light","","","","","",""],
["","you","","oh, yeah","turn_on_flashlight","","null","","",""],
["tori_climb_ttt","you","","there's a tic tac toe game down here!","","","","","",""],
["","tori","","you'd better not be pulling my leg.","","","","","",""],
["","you","","no really, there is!","","","","","",""],
["","","","who could have played it??","","","","","",""],
["","tori","","i don't know.","","","","","",""],
["","","","i swear this place is just messing with us.","","","null","","",""],
["tori_climb3","you","","wow, this pit is really deep...","","","null","","",""],
["tori_climb4","you","","um, tori?","","","","","",""],
["","tori","","yes?","","","","","",""],
["","you","","i've gone down kinda far...","","","","","",""],
["","","","and it's really dark and spooky down here...","","","","","",""],
["","","","maybe i should come back up?","","","","","",""],
["","tori","","come on, don't give up now!","","","","","",""],
["","","","you're almost at the end of the rope!","","","","","",""],
["","you","","okay, okay","","","","","",""],
["","","","just a little bit longer...","","","null","","",""],
["tori_climb_lucifur","you","","hey, there's something on the wall!","","","","","",""],
["","tori","","what is it?","","","","","",""],
["","you","","it's some writing...","","","","","",""],
["","","","it says...","","","","","",""],
["","","","\"lucifur wuz here too\"","","","","","",""],
["","_none","","[i]crack![/i]","climb_crack1","","","","",""],
["","you","","what was that?!","","","","","",""],
["","tori","","nothing!","","","","","",""],
["","_none","","[i]CRACK[/i]","climb_crack2","","","","",""],
["","you","","AAAAAAAAAAAAAAA","","","","","",""],
["","tori","","it's ok! it's ok! i got the rope!","","","","","",""],
["","you","","oh my god","","","","","",""],
["","tori ","","just hang on, i'll pull you up!","","","","","",""],
["","_none","","(press up repeatedly to hang on!)","_delay_start_climb_game","","null","","",""],
["tori_climb_fall","you","","AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA","","","","","",""],
["","","","oof","","","","","",""],
["","tori","","{player}!! are you okay??","","","","","",""],
["","you","","i'm okay, the harness caught me!","","","","","",""],
["","tori","","jeez, you gave me a heart attack!","","","","","",""],
["","","","just... stay there, i'll keep pulling you up!","","","","","",""],
["","you","","stay here? where else am i going to go???","","","","","",""],
["","tori","","NOW is when you develop a sense of sarcasm??","","","null","","",""],
["tori_climb_return","tori","","got you!","tori_dropoff_complete","","","","",""],
["","_none","tori_neutral","tori pulls you onto the platform.","_goto_dropoff1","","","","",""],
["","you","","oh my GOD i'm never doing that again","","","","","",""],
["","tori","","no kidding!","","","","","",""],
["","","","damn, i really didn't think the post would break.","","","","","",""],
["","","","good thing i had a good hold on it.","","","","","",""],
["","you","","i almost DIED","","","","","",""],
["","tori","","{player}, you know you're already--","","","","","",""],
["","you","","i almost died TWICE","","","","","",""],
["","tori","","listen, i'm really sorry. i didn't think the post would break.","","","","","",""],
["","","","at least we got to see what's down there!","","","","","",""],
["","","","the only thing you saw was some graffiti?","","","","","",""],
["","you","","yes","","","","","",""],
["","tori","","and just a straight shaft all the way?","","","","","",""],
["","you","","yep","","","","","",""],
["","tori","","dammit.","","","","","",""],
["","","","and are you... okay?","","","","","",""],
["","you","","idk","","","","","",""],
["","","","i think i just need to","","","","","",""],
["","","","lie down for a little bit","","","","","",""],
["","tori","","alright, let me get these ropes off you.","","","","","",""],
["","","","so.","","","","","",""],
["","","","thanks for going down. that was really brave.","","","","","",""],
["","you","","yeah ur welcome","","","","","",""],
["","tori","","i'll uh","","","","","",""],
["","","","i'll talk to you later.","","","","","",""],
["","you","","seeya","","","null","","",""],
["tori_climb_again","_none","","you're not even getting CLOSE to that edge again","","","null","","",""],
["tori_end","","","_pass","","talked_to_tori_end",['tori_end_c', 'tori_end_d'],"","",""],
["tori_end_d","tori","tori_neutral","ah, {player}.","talked_to_tori_end","","","","",""],
["","","","good to see you.","","","","","",""],
["","you","","you too","","","","","",""],
["","tori","","have you, uh","","","","","",""],
["","","","recovered? since the incident?","","","","","",""],
["","you","","the one at the dropoff","","","","","",""],
["","tori","","no, the OTHER time i nearly dropped you into an infinite hole","","","","","",""],
["","you","","yeah i'm fine i guess","","","","","",""],
["","tori","","good!","","","","","",""],
["","","","i think... i will need your help with my latest plan","","","","","",""],
["","","","this time there's no chance of harm at all","","","","","",""],
["","","","no angry gardeners, no live wires, no endless pits","","","","","",""],
["","","","just a door.","","","","","",""],
["","","","do you have the time?","","","","","",""],
["","","","","","","",['true', 'true', '_inv_chess_letter'],['sure', 'not right now', '(deliver oliver\'s letter)'],['tori_end_a', 'tori_end_b', 'tori_chess']],
["tori_end_b","you","","um, not right now","","","","","",""],
["","tori","","that's alright.","","","","","",""],
["","","","i can understand your misgivings given what happened last time.","","","null","","",""],
["tori_end_c","tori","tori_neutral","ah, are you here to help?","","","","","",""],
["","","","","","","",['true', 'true', '_inv_chess_letter'],['sure', 'not right now', '(deliver oliver\'s letter)'],['tori_end_a', 'tori_end_b', 'tori_chess']],
["tori_end_a","you","","i think i can handle a door!","","","","","",""],
["","tori","","great!","","","","","",""],
["","you","","so, what's the plan?","","","","","",""],
["","tori","","step one. get through this door.","","","","","",""],
["","","","step two. freedom.","","","","","",""],
["","you","","...","","","","","",""],
["","","","is that it?","","","","","",""],
["","tori","","for now.","","","","","",""],
["","","","any ideas?","","","","","",""],
["","you","","uhhh","","","","","",""],
["tori_end_main","","","","","","",['not tori_end_tried_kicking', 'not tori_end_tried_feeling', 'not tori_end_tried_knocking', 'true'],['kick it', 'look for hidden compartments', 'knock on it', 'wait'],['tori_end1', 'tori_end2', 'tori_end3', 'tori_end4']],
["tori_end1","you","","kick it?","tori_end_tried_kicking","","","","",""],
["","tori","","hey, it's worth a shot.","","","","","",""],
["","_none","","you kick the door.","","","","","",""],
["","you","","ow!","","","","","",""],
["","tori","","sit down in front of the door and hit it with your heels. that's the easiest way.","","","","","",""],
["","you","","oh, cool","","","","","",""],
["","","","should i ask how you know about...?","","","","","",""],
["","tori","","no.","","","","","",""],
["","_none","","you both start kicking the door.","start_kicking_sounds","","","","",""],
["","","","[i]thud. thud. thud.[/i]","","","","","",""],
["","you","","do you think it's getting weaker?","","","","","",""],
["","tori","","not really.","","","","","",""],
["","_none","","[i]thud. thud. thud.[/i]","","","","","",""],
["","tori","","what is this door made of, steel?","","","","","",""],
["","_none","","[i]thud. thud. thud.[/i]","","","","","",""],
["","you","","so, what did numa say after she cooled down? about the holes?","","","","","",""],
["","tori","","oh, she was still pretty mad","","","","","",""],
["","","","i agreed to fill them back in and help with pruning","","","","","",""],
["","you","","that's good","","","","","",""],
["","_none","","[i]thud. thud. thud.[/i]","","","","","",""],
["","tori","","apologizing. one of the few things i never learned how to do.","","","","","",""],
["","","","i always end up sounding sarcastic.","","","","","",""],
["","","","","","","","",['aw, it\'s not that hard', 'actions speak louder than words', '...'],['tori_end1a', 'tori_end1b', 'tori_end1c']],
["tori_end1a","you","","aw, it's not that hard!","","","","","",""],
["","","","just say \"sorry,\" acknowledge why what you did was wrong, then ask what you can do to make up for it","","","","","",""],
["","tori","","hmm","","","","","",""],
["","","","well when you put it THAT way, it sounds easy","","","","","",""],
["","you","","idk, that's just how i usually go about it","","","","","",""],
["","tori","","how about this?","","","","","",""],
["","","","sorry. almost dropping you into an endless pit was selfish of me. what can i do to make up for it?","","","","","",""],
["","you","","aww, thanks!","","","","","",""],
["","","","umm","","","","","",""],
["","","","don't drop me into pits anymore?","","","","","",""],
["","tori","","i can handle that.","","","","","",""],
["","you","","sweet","","","tori_end1d","","",""],
["tori_end1b","you","","well, actions speak louder than words","","","","","",""],
["","","","maybe if you have trouble verbalizing an apology, you can show that you care in other ways?","","","","","",""],
["","tori","","hm...","","","","","",""],
["","","","that's an interesting idea.","","","","","",""],
["","you","","idk, just thinking out loud","","","","","",""],
["","tori","","how about this?","","","","","",""],
["","","","why don't you take a break? i'll kick for both of us.","","","","","",""],
["","you","","oh, thanks! my feet were getting kind of sore.","","","","","",""],
["","tori","","no problem. i like kicking.","","","","","",""],
["","","","one of the many joys of having feet.","","","tori_end1d","","",""],
["tori_end1c","you","","...","","","","","",""],
["tori_end1d","_none","","[i]thud. thud. thud.[/i]","","","","","",""],
["","tori","","i don't think this is working","stop_kicking_sounds","","","","",""],
["","you","","yeah, me neither","","","","","",""],
["","tori","","now what?","","","tori_end_main","","",""],
["tori_end2","you","","look for hidden compartments?","tori_end_tried_feeling","","","","",""],
["","","","like, maybe there's a panel on the wall that opens the door when you push it","","","","","",""],
["","tori","","honestly, i wouldn't put it past this place to work on spy movie logic.","","","","","",""],
["","_none","","both of you start feeling up the walls.","","","","","",""],
["","you","","just walls over here","","","","","",""],
["","tori","","same","","","","","",""],
["","_none","","...","","","","","",""],
["","you","","so, um","","","","","",""],
["","","","you have an... interesting variety of skills","","","","","",""],
["","","","what did you do before you died?","","","","","",""],
["","tori","","oh, i was a student.","","","","","",""],
["","","","philosophy and business. minor in economics.","","","","","",""],
["","","","i just have a lot of hobbies.","","","","","",""],
["","you","","oh, wow","","","","","",""],
["","","","and you still had time to get a black belt, go spelunking, learn electrical engineering, and...?","","","","","",""],
["","tori","","become a FIDE Master at chess? yep","","","","","",""],
["","you","","that's crazy!","","","","","",""],
["","tori","","average american works 35 hours a week.","","","","","",""],
["","","","i use all 168.","","","","","",""],
["","","","","","","","",['did you ever rest?', 'how did you make time for friends?', '...'],['tori_end2a', 'tori_end2b', 'tori_end2c']],
["tori_end2a","you","","did you ever, like, rest?","","","","","",""],
["","tori","","no, i haven't slept since 2010.","","","","","",""],
["","you","","wait, really??","","","","","",""],
["","tori","","...no, that was sarcasm.","","","","","",""],
["","","","i used to sleep from midnight to six every night, but i don't think you need to sleep in purrgatory","","","","","",""],
["","","","gives me more time to work.","","","","","",""],
["","you","","how about like, just relaxing though?","","","","","",""],
["","tori","","sure, i play chess with oliver to give my brain a break.","","","","","",""],
["","you","","you play chess for a BREAK??","","","","","",""],
["","","","geez, starting to see why you and oliver are friends.","","","","","",""],
["","tori","","i don't know. i like being productive, sue me.","","","","","",""],
["","you","","maybe a break would be good for you!","","","","","",""],
["","","","you know, stop worrying about escaping for a bit and just try to make the best of what we have","","","","","",""],
["","tori","","maybe you have a point.","","","tori_end2d","","",""],
["tori_end2b","you","","how did you make time for friends?","","","","","",""],
["","tori","","heh, if they can't keep up, then i leave them behind!","","","","","",""],
["","","","...","","","","","",""],
["","","","i didn't have a lot of friends.","","","","","",""],
["","you","","awww","","","","","",""],
["","","","at least you get a second chance in purrgatory!","","","","","",""],
["","tori","","of course you'd find the silver lining in being stuck with the same seven people forever.","","","","","",""],
["","you","","well, have you made friends with them?","","","","","",""],
["","tori","","i'm friends with oliver.","","","","","",""],
["","","","and... numa, to an extent.","","","","","",""],
["","","","maybe not anymore.","","","","","",""],
["","you","","and...?","","","","","",""],
["","tori","","i don't know, i talk to natalie sometimes?","","","","","",""],
["","","","what is this, a therapy session??","","","","","",""],
["","you","","it's just, all i've been doing since i got here is walking around chatting with the other people","","","","","",""],
["","","","so i'm surprised you've been here for so long and you haven't gotten to know them","","","","","",""],
["","tori","","i guess... you have a point.","","","","","",""],
["","","","maybe i'll invite them to our wall-feeling party and we can all get to know each other better.","","","","","",""],
["","you","","sure!","","","","","",""],
["","tori","","no, that was sarcasm!!","","","tori_end2d","","",""],
["tori_end2c","you","","...","","","","","",""],
["tori_end2d","tori","","listen, i don't think we're going to find any secret panels","","","","","",""],
["","you","","yeah, it was a long shot anyway","","","","","",""],
["","tori","","any other ideas?","","","tori_end_main","","",""],
["tori_end3","you","","knock on it?","tori_end_tried_knocking","","","","",""],
["","tori","","sure, why not.","","","","","",""],
["","_none","","tori knocks on the door.","","","","","",""],
["","you","","...","","","","","",""],
["","tori","","...","","","","","",""],
["","you","","i guess they're not home","","","tori_end_main","","",""],
["tori_end4","you","","wait?","","","","","",""],
["","","","you know, maybe it only opens once for ten minutes every thousand years, or something?","","tori_end_tried_knocking and tori_end_tried_feeling and tori_end_tried_kicking",['tori_end4b', 'tori_end4a'],"","",""],
["tori_end4a","tori","","not that i'm against the idea of waiting for a thousand years, maybe we should try something else in the meanwhile?","","","","","",""],
["","you","","yeah, that makes sense...","","","tori_end_main","","",""],
["tori_end4b","tori","","hmmm...","","","","","",""],
["","","","sitting around and doing nothing seems counterintuitive to escaping","","","","","",""],
["","you","","i don't know, it's purrgatory","","","","","",""],
["","","","isn't that kinda the theme?","","","","","",""],
["","tori","","i guess it's worth a shot.","","","","","",""],
["","you","","exactly!","","","","","",""],
["","tori","","time to sit here and do nothing.","","","","","",""],
["","you","","yep","","","","","",""],
["","tori","","okay.","","","","","",""],
["","","","i'm starting now.","","","","","",""],
["","_none","","...","","","","","",""],
["","","","....","","","","","",""],
["","","",".....","","","","","",""],
["","","","......","","","","","",""],
["","tori","","must have been an hour by now, right?","","","","","",""],
["","you","","um","","","","","",""],
["","","","felt more like 30 seconds to me","","","","","",""],
["","tori","","oh","","","","","",""],
["","_none","","...","","","","","",""],
["","","","....","","","","","",""],
["","","",".....","","","","","",""],
["","","","......","","","","","",""],
["","","",".......","","","","","",""],
["","","","........","","","","","",""],
["","","",".........","","","","","",""],
["","","","..........","","","","","",""],
["","tori","","you know, this isn't as bad as i thought.","","","","","",""],
["","","","it's sort of like meditating.","","","","","",""],
["","you","","yeah, we're just straight up chilling.","","","","","",""],
["","tori","","i've never noticed so many details on the walls, before.","","","","","",""],
["","you","","me neither","","","","","",""],
["","_none","","...","","","","","",""],
["","","","....","","","","","",""],
["","","",".....","","","","","",""],
["","","","......","","","","","",""],
["","","",".......","","","","","",""],
["","","","........","","","","","",""],
["","","",".........","","","","","",""],
["","","","..........","","","","","",""],
["","","","...........","","","","","",""],
["","","","............","","","","","",""],
["","","",".............","","","","","",""],
["","","","..............","","","","","",""],
["","tori","","hey, {player}","","","","","",""],
["","you","","yeah?","","","","","",""],
["","tori","","thanks for helping me with everything.","","","","","",""],
["","","","even if we couldn't find a way to escape.","","","","","",""],
["","","","it was... fun","","","","","",""],
["","you","","aw, you're welcome!","","","","","",""],
["","","","i thought it was fun too","","","","","",""],
["","","","when i wasn't almost dying","","","","","",""],
["","tori","","right.","","","","","",""],
["","_none","","...","","","","","",""],
["","","","....","","","","","",""],
["","","",".....","","","","","",""],
["","","","......","","","","","",""],
["","tori","","you can go, if you want.","","","","","",""],
["","","","i think i'll stay here for a while.","","","","","",""],
["","","","don't wanna miss the door if it opens.","","","","","",""],
["","you","","okay!","","","","","",""],
["","","","i'll come back to check on you every now and then.","","","","","",""],
["","tori","","sounds good.","","","","","",""],
["","","","til next time, associate.","queue_tori_flashback","","null","","",""],
["tori_default","","","_pass","","queue_tori_flashback",['tori_serene', 'tori_default1'],"","",""],
["tori_serene","_none","","she looks serene.","","","null","","",""],
["tori_default1","tori","tori_neutral","hi, {player}.","","","","","",""],
["","","","","","","",['true', 'true', 'true', '_inv_chess_letter'],['what\'s up?', 'how\'s the door?', 'how was life?', '(deliver oliver\'s letter)'],['tori_wasup', 'tori_door', 'tori_life', 'tori_chess']],
["tori_chess","you","","actually, oliver had a letter for you",[['_quest_oliver_chess', false], ['_inv_chess_letter', false]],"","","","",""],
["","","","he said it's his next chess move, or something.","","","","","",""],
["","tori","","oh? let's take a look.","","","","","",""],
["","","","...","","","","","",""],
["","","","heh, it's almost like he WANTS me to trap his queen.","","","","","",""],
["","","","how's the boy doing, anyway?","","","","","",""],
["","you","","oh, uh, not too great","","","","","",""],
["","","","he found something in one of his books and he's been researching it constantly","","","","","",""],
["","tori","","yeah, that sounds like oliver.","","","","","",""],
["","","","maybe we should pay him a quick visit, and i can tell him to his face what i think of this move.","","","","","",""],
["","you","","sure, if you want!","","","","","",""],
["","tori","","follow me.","","","tori_visiting_oliver","","",""],
["tori_wasup","you","tori_neutral","what's up?","","",['_rand', 'tori_wasup1', 'tori_wasup2', 'tori_wasup3', 'tori_wasup4', 'tori_wasup5', 'tori_wasup6', 'tori_wasup7', 'tori_wasup8', 'tori_wasup9', 'tori_wasup10', 'tori_wasup11', 'tori_wasup12', 'tori_wasup13', 'tori_wasup14', 'tori_wasup15', 'tori_wasup16', 'tori_wasup17', 'tori_wasup18', 'tori_wasup19', 'tori_wasup20'],"","",""],
["tori_wasup1","tori","","i don't know, the sky.","","","","","",""],
["","you","","is it?","","","","","",""],
["","tori","","no, i guess not","","","null","","",""],
["tori_wasup2","tori","","door","","","","","",""],
["","you","","door","","","null","","",""],
["tori_wasup3","tori","","always meant to learn asl before i died","","","","","",""],
["","you","","oh, to talk to deaf people?","","","","","",""],
["","tori","","yes, but also to communicate while scuba diving","","","null","","",""],
["tori_wasup4","tori","","what's 6 times 7?","","","","","",""],
["","you","","uh","","","","","",""],
["","","","uhhh","","","","","",""],
["","","","42?","","","","","",""],
["","tori","","good.","","","","","",""],
["","","","just a little test to keep you on your toes.","","","","","",""],
["","you","","??","","","null","","",""],
["tori_wasup5","tori","","as soon as we find a way out of here, we're going to be kicking ourselves for not thinking of it sooner.","","","","","",""],
["","you","","oh yeah","","","","","",""],
["","","","what if it's something like, you have to click your heels three times and say \"there's no place like heaven\"?","","","","","",""],
["","tori","","i've tried that.","","","","","",""],
["","you","","oh, really?","","","","","",""],
["","tori","","yes, with every number of heel clicks up to twelve.","","","","","",""],
["","you","","why'd you stop at twelve?","","","","","",""],
["","tori","","thirteen's unlucky. might have gone to hell.","","","null","","",""],
["tori_wasup6","tori","","did you know i took ballet until i was twelve?","","","","","",""],
["","you","","oh, that's cool!","","","","","",""],
["","","","why'd you stop?","","","","","",""],
["","tori","","my friend darius made fun of me, so i switched to karate so i could beat him up","","","","","",""],
["","you","","oh","","","null","","",""],
["tori_wasup7","tori","","i wonder what my sensei would think of me now","","","","","",""],
["","you","","probably good things!","","","null","","",""],
["tori_wasup8","tori","","i'm starting to see why kyungsoon does what she does","","","","","",""],
["","","","sitting in one place doing nothing kinda grows on you after a while","","","null","","",""],
["","you","","wow, really?","","","","","",""],
["","tori","","no. sarcasm.","","","null","","",""],
["tori_wasup9","tori","","i counted all the specks on the opposite wall","","","","","",""],
["","you","","oh, how many are there?","","","","","",""],
["","tori","","eight thousand, three hundred and forty two","","","","","",""],
["","you","","wow","","","null","","",""],
["tori_wasup10","tori","","hm?","","","","","",""],
["","","","sorry, dozed off for a second there","","","","","",""],
["","you","","oh, nothing","","","null","","",""],
["tori_wasup11","tori","","I JUST HAD A BREAKTHROUGH!","","","","","",""],
["","you","","oh?","","","","","",""],
["","tori","","wait no","","","","","",""],
["","","","false alarm","","","","","",""],
["","you","","oh ok","","","null","","",""],
["tori_wasup12","tori","","just solved the collatz conjucture","","","","","",""],
["","","","don't tell oliver","","","","","",""],
["","you","","i won't!","","","null","","",""],
["tori_wasup13","tori","","i thiiink i have checkmate in eighteen in my game against oliver","","","","","",""],
["","you","","in eighteen??","","","","","",""],
["","tori","","eighteen moves from now, yeah.","","","","","",""],
["","you","","is that a lot?","","","","","",""],
["","tori","","no, just nearly half of an average chess game.","","","null","","",""],
["tori_wasup14","tori","","did you know all froot loops are the same color?","","","","","",""],
["","you","","blasphemy","","","null","","",""],
["tori_wasup15","tori","","did you know iguanas have three eyes?","","","","","",""],
["","you","","really??","","","","","",""],
["","tori","","yeah, i had one as a pet","","","","","",""],
["","","","his name was goliath","","","","","",""],
["","you","","wow","","","null","","",""],
["tori_wasup16","tori","","literally nothing","","","","","",""],
["","you","","same","","","null","","",""],
["tori_wasup17","tori","","do you think they have airpods in heaven?","","","","","",""],
["","you","","i hope not","","","","","",""],
["","tori","","i don't know. they're sort of convenient.","","","","","",""],
["","","","extremely tacky, though.","","","","","",""],
["","you","","heaven earpods are probably more fashionable.","","","","","",""],
["","tori","","probably, yeah.","","","null","","",""],
["tori_wasup18","tori","","hold on","","","","","",""],
["","","","...","","","","","",""],
["","you","","wh","","","","","",""],
["","tori","","sh!!","","","","","",""],
["","","","...","","","","","",""],
["","","","sorry, i thought i saw the door move","","","","","",""],
["","","","but it was just your shadow.","","","","","",""],
["","you","","oh, sorry","","","","","",""],
["","tori","","you're sorry for casting a shadow?","","","","","",""],
["","you","","...i guess??","","","null","","",""],
["tori_wasup19","tori","","i'm pretty sure i never waited this long for anything in my life","","","","","",""],
["","you","","not very patient, huh?","","","","","",""],
["","tori","","i used to drive to a dmv in the middle of the mojave desert to avoid having to stand in line.","","","null","","",""],
["tori_wasup20","tori","","not much.","","","","","",""],
["","","","how about you? i feel like i never ask you what's up.","","","","","",""],
["","you","","oh, uh, not much!","","","","","",""],
["","","","i've been walking around in circles for a while","","","","","",""],
["","tori","","what for?","","","","","",""],
["","you","","i guess i've been running a lot of errands for people?","","","","","",""],
["","tori","","sounds like a great way to spend your afterlife.","","","","","",""],
["","you","","i mean... could be worse!","","","null","","",""],
["tori_door","you","","how's the door?","","","","","",""],
["","","","still waiting for it to open?","","","","","",""],
["","tori","","don't talk to me about the door.","","","","","",""],
["","","","me and the door are not on speaking terms anymore.","","","","","",""],
["","you","","i guess it doesn't a-door you anymore, huh?","","","","","",""],
["","tori","","funny.","","","","","",""],
["","","","i have a system now. i look at the door for two hours, then i look away from the door for one hour, then i try the doorknob.","","","","","",""],
["","","","rinse and repeat.","","","","","",""],
["","you","","sounds... fun?","","","","","",""],
["","tori","","very.","","","null","","",""],
["tori_life","you","","so, how was your life?","","","","","",""],
["","tori","","well, i would have liked it to be a little longer, but otherwise it was alright.","","","","","",""],
["","you","","any regrets?","","","","","",""],
["","tori","","hmm....","","","","","",""],
["","","","i have three.","","","","","",""],
["","","","one, i never got to start my own business","","","","","",""],
["","","","me and my friend ran a campus laundry business in our first year of university, but that doesn't count.","","","","","",""],
["","you","","i see i see","","","","","",""],
["","tori","","two, walking under the tree that got struck by lightning and killed me","","","","","",""],
["","you","","oh yeah ","","","","","",""],
["","","","that's a big one","","","","","",""],
["","tori","","no kidding.","","","","","",""],
["","you","","what about the third one?","","","","","",""],
["","tori","","hm?","","","","","",""],
["","you","","you said you had three?","","","","","",""],
["","tori","","oh, yes","","","","","",""],
["","","","the third one is","","","","","",""],
["","","","uh","","","","","",""],
["","you","","yeeees?","","","","","",""],
["","tori","","it's a little embarrassing.","","","","","",""],
["","you","","go ooooon","","","","","",""],
["","tori","","...","","","","","",""],
["","","","three, never kissed a girl","","","","","",""],
["","you","","awwwwwwwwwwwwwww","","_pronouns_she",['tori_life1', 'tori_life2'],"","",""],
["tori_life1","you","","do you... wanna try it?","","","","","",""],
["","tori","","what, with you?","","","","","",""],
["","you","","why not?","","","","","",""],
["","tori","","i think i'll pass","","","","","",""],
["","","","no offense.","","","","","",""],
["","","","that's just kind of a weird to offer to someone.","","","","","",""],
["","you","","ok, that's fair","","","null","","",""],
["tori_life2","you","","poor lovestruck tori","","","","","",""],
["","tori","","[i]i've said too much[/i]","","","null","","",""]
]