extends Node

var raw_blocks = [
["talk_to_tori","tori","tori_neutral","(placeholder)",[['_quest_oliver_chess', false], ['met_tori', true]],"","","","",""],
["tori_visiting_oliver","tori",['tori_neutral', 'oliver_neutral'],"oliver. good to see you.","tori_goto_study","","","","",""],
["","oliver","","huh?","tori_visited_oliver","","","","",""],
["","","","oh, tori. good to see you!","","","","","",""],
["","","","can i help you with something? looking for a book?","","","","","",""],
["","tori","","no offense, but it'll take a few more years before i get bored enough to read one of your books.","","","","","",""],
["","oliver","","eheh. right.","","","","","",""],
["","tori","","i'm just checking in. {player} tells me you're on another wild goose chase?","","","","","",""],
["","you","","well, i didn't say [i]that[/i], exactly...","","","","","",""],
["","oliver","","no, no. i understand. ","","","","","",""],
["","","","i know it sounds far-fetched.","","","","","",""],
["","","","but i've never seen anything written in these books before -- you see, one of the \"meows\" is circled on page 86 and--","","","","","",""],
["","tori","","spare me the details. {player} told me all about it.","","","","","",""],
["","oliver","","ah, i see.","","","","","",""],
["","tori","","i'm guessing this means you'll be locked up in your study for the next month or so?","","","","","",""],
["","oliver","","hopefully less than that!","","","","","",""],
["","","","but, if that's what it takes...","","","","","",""],
["","tori","","i'm also guessing that our chess game is on hold?","","","","","",""],
["","oliver","","well","","","","","",""],
["","","","i don't really have time to play right now. sorry.","","","","","",""],
["","_none","","tori eyes oliver for a moment, then shrugs.","","","","","",""],
["","tori","","no worries. we have until eternity to finish it. ","","","","","",""],
["","","","or until i find a way out of here.","","","","","",""],
["","","","whichever comes first.","","","","","",""],
["","oliver","","maybe if i get through my to-do list...","","","","","",""],
["","","","where did i put that again?","","","","","",""],
["","","","i'm sure i can make some time--","","","","","",""],
["","_none","","oliver sends a pile of books tumbling onto the ground","","","","","",""],
["","oliver","","ack!","","","","","",""],
["","","","","","","","",['you look tired', 'i think you need to tidy up a little'],['tori_tired', 'tori_clean']],
["tori_tired","you","","are you alright? you look tired","","","","","",""],
["","tori","","no kidding.","","","","","",""],
["","oliver","","i'm fine, i'm fine!","","","","","",""],
["","","","just... a little disoriented, is all","","","tori_visiting_oliver2","","",""],
["tori_clean","you","","i think you need to tidy up a little","","","","","",""],
["","tori","","no kidding.","","","","","",""],
["","oliver","","i swear it's not usually this bad!","","","","","",""],
["","","","cleaning just hasn't been... the highest priority, recently","","","","","",""],
["tori_visiting_oliver2","you","","are you sure you don't need a rest? ","","","","","",""],
["","","","maybe you can take a break to play chess or something.","","","","","",""],
["","oliver","","don't worry about me. i'm indefatiguable.","","","","","",""],
["","you","","indefa-what?","","","","","",""],
["","oliver","","indefatiguable. tireless.","","","","","",""],
["","tori","","suuure, it's not that you're avoiding the game because you know your queen is as good as mine.","","","","","",""],
["","oliver","","don't be ridiculous!","","","","","",""],
["","","","the weak points in your pawn structure are almost too easy to exploit. ","","","","","",""],
["","","","we'll see what good your extra knight does when your king is left defenseless on the back rank!","","","","","",""],
["","tori","","alright, alright. spare me the master plan.","","","","","",""],
["","","","i'm gonna get going, alright?","","","","","",""],
["","","","do your work. i'll do mine. one of these days we'll find something important.","","","","","",""],
["","oliver","","will do.","","","","","",""],
["","tori","","see you, {player}.","","","","","",""],
["","you","","cya","","","null","","",""]
]