extends Node

var raw_blocks = [
["tori_visiting_oliver","_none",['tori_neutral', 'oliver_neutral'],"tori leads you to the study.",[['_goto_study', true], ['hide_oliver_custom', true]],"","","","",""],
["","tori","","oliver. good to see you.","tori_visited_oliver","","","","",""],
["","oliver","","huh?","","","","","",""],
["","","","oh, tori. good to see you too!","","","","","",""],
["","","","can i help you with something? looking for a book?","","","","","",""],
["","tori","","no offense, but it'll take a few more years before i get bored enough to read one of your books.","","","","","",""],
["","oliver","","eheh. no offense taken.","","","","","",""],
["","tori","","i'm just checking in. {player} tells me you're on another wild mouse chase?","","","","","",""],
["","you","","well, i didn't say [i]that[/i], exactly...","","","","","",""],
["","oliver","","no, no. i understand. ","","","","","",""],
["","","","i know it sounds far-fetched, but--","","","","","",""],
["","","","i've never seen anything like it before!","","","","","",""],
["","","","you see, one of the \"meows\" is misspelled on page 69 and--","","","","","",""],
["","tori","","spare me the details. {player} told me all about it.","","","","","",""],
["","oliver","","oh. right","","","","","",""],
["","tori","","i'm guessing this means you'll be locked up in your study for the next month or so?","","","","","",""],
["","oliver","","um, hopefully less than that!","","","","","",""],
["","","","but if that's what it takes...","","","","","",""],
["","tori","","...and that our chess game is on hold?","","","","","",""],
["","oliver","","well","","","","","",""],
["","","","i don't really know if i can make time to play right now...","","","","","",""],
["","tori","","[i]shrug[/i]","","","","","",""],
["","","","no worries. we have forever to finish it. ","","","","","",""],
["","","","or until i find a way out of here.","","","","","",""],
["","","","whichever comes first.","","","","","",""],
["","oliver","","maybe if i can get through my to-do list...","","","","","",""],
["","","","where did i put that again?","","","","","",""],
["","","","i'm sure i can squeeze it a few moves somewhere--","","","","","",""],
["","_none","","oliver sends a pile of books tumbling onto the ground","","","","","",""],
["","oliver","","ack!","","","","","",""],
["","","","","","","","",['you look tired', 'i think you need to tidy up a little'],['tori_tired', 'tori_clean']],
["tori_tired","you","","are you alright? you look tired","","","","","",""],
["","tori","","no kidding.","","","","","",""],
["","oliver","","i'm fine, i'm fine!","","","","","",""],
["","","","just... a little disoriented, is all","","","tori_visiting_oliver2","","",""],
["tori_clean","you","","i think you might need to tidy up a little","","","","","",""],
["","tori","","no kidding.","","","","","",""],
["","oliver","","i swear it's not usually this bad!","","","","","",""],
["","","","cleaning just hasn't been... the highest priority, recently","","","","","",""],
["tori_visiting_oliver2","you","","are you sure you don't need to rest? ","","","","","",""],
["","","","maybe chess can be a good excuse to take a break!","","","","","",""],
["","oliver","","no, no. i can't take a break. not right now.","","","","","",""],
["","tori","","suuure, you're not just avoiding the game because you know your knight is as good as mine.","","","","","",""],
["","oliver","","don't be ridiculous!","","","","","",""],
["","","","the weak points in your pawn structure are almost too easy to exploit. ","","","","","",""],
["","","","we'll see what good your extra knight does when your king is left defenseless on the back rank!","","","","","",""],
["","tori","","alright, alright. spare me the master plan.","","","","","",""],
["","","","i'm gonna get going, alright?","","","","","",""],
["","","","just remember to stretch every now and then.","","","","","",""],
["","oliver","","will do.","","","","","",""],
["","tori","","see you, {player}.","","","","","",""],
["","you","","cya","","","null","","",""],
["tori_train","","","_pass","","met_tori",['tori_train_alt', 'tori_train_normal'],"","",""],
["tori_train_normal","???","tori_neutral","{player}.","met_tori","","","","",""],
["","","","i've been expecting you.","","","","","",""],
["","","","","","","","",['huh??', 'as have i'],['tori_train1', 'tori_train2']],
["tori_train1","you","","huh??","","","","","",""],
["","","","how did you know my name?","","","","","",""],
["","???","","simple. it says right there on the screen.","","","","","",""],
["","_none","","you look at the \"arrivals\" screen, where your name is listed.","","","","","",""],
["","you","","oh, weird","","","","","",""],
["","???","","yes, your name has been up there for over a week.","","","","","",""],
["","","","but as usual, no one seemed to notice but me.","","","","","",""],
["","","","to be fair, i was expecting you to show up in a train...","","","","","",""],
["","","","anyway, my name is tori.","","","tori_train3","","",""],
["tori_train2","you","","as have i...","","","","","",""],
["","","","...amelia?","","","","","",""],
["","???","","nice try. it's tori.","","","","","",""],
["","you","","damn, worth a shot","","","","","",""],
["","","","but how did you know my name?","","","","","",""],
["","tori","","simple. it says right there on the screen.","","","","","",""],
["","_none","","you look at the \"arrivals\" screen, where your name is written.","","","","","",""],
["","you","","oh, weird","","","","","",""],
["","tori","","yes, your name has been up there for over a week.","","","","","",""],
["","","","but as usual, no one seemed to notice but me.","","","","","",""],
["","","","to be fair, i was expecting you to show up in a train...","","","","","",""],
["","","","anyway, my name is tori.","","","tori_train3","","",""],
["tori_train_alt","tori","tori_neutral","{player}.","","","","","",""],
["","","","we meet again, on this most fated of days.","","","","","",""],
["","you","","um, hi!","","","","","",""],
["","","","why so... ominous?","","","","","",""],
["","tori","","take a look at the screen up there.","","","","","",""],
["","_none","","you look at the \"arrivals\" screen, where your name is written.","","","","","",""],
["","you","","oh, weird","","","","","",""],
["","tori","","yes, your name has been up there for over a week.","","","","","",""],
["","","","but as usual, no one seemed to notice but me.","","","","","",""],
["","","","to be fair, i was expecting you to show up in a train...","","","","","",""],
["","","","anyway, i never properly introduced myself to you.","","","","","",""],
["","","","my name is tori.","","","tori_train3","","",""],
["tori_train3","tori","","entrepreneur, black belt, and deceased soul.","","","","","",""],
["","","","if you don't mind, i have some questions for you.","","","","","",""],
["","_none","","tori lifts a clipboard.","","","","","",""],
["","you","","uh, ok, i guess","","","","","",""],
["","tori","","one. who are you, and what is your purpose here?","","","","","",""],
["","","","","","","","",['tell the truth', 'lie'],['tori_train4', 'tori_train5']],
["tori_train4","you","","i woke up in an office with an old lady, who said i was going to purrgatory?","","","","","",""],
["","","","then i went through a portal and ended up here","","","","","",""],
["","tori","","hmm. that checks out.","","","tori_train6","","",""],
["tori_train5","you","","uhhh, i'm the janitor! i'm just here to do my regular cleaning.","","","","","",""],
["","tori","","uh-huh.","","","","","",""],
["","","","and where were you when sean spilled orange soda all over the commons?","","","","","",""],
["","you","","uhhhhhh, on sick leave?","","","","","",""],
["","tori","","very funny.","","","","","",""],
["","","","who are you for real?","","","","","",""],
["","you","","okay, the truth is i'm no one special","","","","","",""],
["","","","i woke up in an office with an old lady, who sent me through a portal","","","","","",""],
["","tori","","yeah, that sounds more likely.","","","","","",""],
["tori_train6","tori","","two. what would you say was your greatest sin?","","","","","",""],
["","you","","um, i don't really remember","","","","","",""],
["","tori","","really.","","","","","",""],
["","you","","yeah, i woke up without any memories at all","","","","","",""],
["","","","sorry...","","","","","",""],
["","tori","","hmm","","","","","",""],
["","","","i suppose people [i]have[/i] reported memory loss before...","","","","","",""],
["","_none","","tori flips through her clipboard.","","","","","",""],
["","tori","","well, that answers most of the rest of my questions. ugh.","","","","","",""],
["","","","one last question. what do you think THAT means?","","","","","",""],
["","_none","","she points at the \"departures\" screen, which says \"heaven: delayed\"","","","","","",""],
["","","","","","","","",["it means they'll let us out soon!", "it means we're stuck here", "it's just a joke"],['tori_train7', 'tori_train8', 'tori_train8a']],
["tori_train7","you","","maybe it means they'll let us out soon!","","","","","",""],
["","tori","","an optimist, huh?","","","","","",""],
["","","","that's good. you'll need that.","","","tori_train9","","",""],
["tori_train8","you","","maybe it means we'll be stuck here for a while?","","","","","",""],
["","tori","","a realist, huh?","","","","","",""],
["","","","i'm the same.","","","tori_train9","","",""],
["tori_train8a","you","","it's probably just a joke?","","","","","",""],
["","","","like most of the signs in here","","","","","",""],
["","tori","","well, that's certainly an astute observation.","","","tori_train9","","",""],
["tori_train9","tori","","regardless, i'm not interested in standing around and waiting for some celestial being to have mercy on me.","","","","","",""],
["","","","i'm trying to break out of here, and i think that sign means i'm close.","","","","","",""],
["","","","can i count on your help, newbie?","","","","","",""],
["","","","","","","","",["um, idk", "sure!"],['tori_train10', 'tori_train11']],
["tori_train10","you","","um, idk","","","","","",""],
["","","","i'll help where i can, i guess","","","","","",""],
["","tori","","alright, i'll take it.","","","tori_train11b","","",""],
["tori_train11","you","","sure!","","","","","",""],
["","tori","","that's the spirit!","","","","","",""],
["tori_train11b","tori","","now if you'll excuse me, i've got some work to attend to. i think it's time to [i]dig up[/i] some clues.","_delay_tori_train_complete","_inv_chess_letter or (elijah_planning_slam and not invited_tori)",['tori_train11a', 'tori_train12'],"","",""],
["tori_train11a","","","","","","",['_inv_chess_letter', 'elijah_planning_slam and not invited_tori', 'true'],['deliver oliver\'s letter', 'invite tori to the everything slam', 'wait till later'],['tori_chess', 'tori_invitation', 'tori_train12']],
["tori_train12","tori","","stay frosty, {player}.","","","","","",""],
["","you","","cya!","","","","","",""],
["","_none","_none","tori briskly walks away.","","","null","","",""],
["tori_park_intro","","","_pass","",['park_game', 'talked_to_tori_park'],['tori_park_tori', 'tori_park_intro_b', 'tori_park_intro_a'],"","",""],
["tori_park_intro_a","tori","tori_neutral","{player}! just the person i wanted to see.","talked_to_tori_park","","","","",""],
["","you","","oh wow","","","","","",""],
["","","","are you trying to... dig out of purrgatory?","","","","","",""],
["","tori","","what do you think i'm doing?","","","","","",""],
["","","","digging a latrine?","","","","","",""],
["","you","","but... is going further down really going to help us?","","","","","",""],
["","tori","","eh, it's worth a shot.","","","","","",""],
["","","","you know what they say, what goes down must come up!","","","","","",""],
["","you","","i... don't think they say that...","","","","","",""],
["","tori","","nonsense. want to grab a shovel?","","","","","",""],
["","","","","","","",['true', 'true', '_inv_chess_letter', 'elijah_planning_slam and not invited_tori', 'true'],['alright', 'maybe later', '(deliver oliver\'s letter)', '(invite tori to the everything slam)', 'this seems kind of pointless...'],['tori_park_intro1', 'tori_park_intro2', 'tori_chess', 'tori_invitation', 'tori_park_intro3']],
["tori_park_intro1","you","","alright, i [i]dig[/i] it!","","","","","",""],
["","tori","","hilarious.","","","","","",""],
["","","","here's your shovel. knock yourself out","","","","","",""],
["","","","and let me know if you dig up anything weird, alright?","","","","","",""],
["","you","","sounds easy enough!","","","","","",""],
["","_none","","(explore the park and click on hotspots on the ground to dig!)","_delay_start_park_game","","null","","",""],
["tori_park_intro2","you","","maybe later!","","","","","",""],
["","tori","","suit yourself.","","","null","","",""],
["tori_park_intro3","you","","this just seems kind of pointless...","","","","","",""],
["","","","i mean, surely you can't just brute force your way out of purrgatory?","","","","","",""],
["","tori","","uh-huh. and i suppose you're an expert on the afterlife now?","","","","","",""],
["","","","went and got a debriefing from old gabriel, did you?","","","","","",""],
["","you","","i don't know, it just doesn't seem right!","","","","","",""],
["","tori","","typical. giving up before you even begin.","","","","","",""],
["","","","if you ever feel like taking control of your own destiny, i'll be right here.","","","","","",""],
["","you","","alright...","","","null","","",""],
["tori_park_intro_b","tori","tori_neutral","ah, you're back. want to lend a hand?","","","","","",""],
["","you","","can't we just chat...?","","","","","",""],
["","tori","","if you haven't noticed, i'm a little busy.","","","","","",""],
["","","","now are you going to help or not?","","","","","",""],
["","","","","","","",['true', 'true', '_inv_chess_letter', 'elijah_planning_slam and not invited_tori'],['alright', 'maybe later', '(deliver oliver\'s letter)', '(invite tori to the everything slam)'],['tori_park_intro1', 'tori_park_intro2', 'tori_chess', 'tori_invitation']],
["tori_park_tori","you","tori_neutral","how's it going?","","","","","",""],
["","tori","","not great, but i haven't given up yet!","","","","","",""],
["","","","i'm not afraid to get my hands a little dirty if it means escaping.","","","","","",""],
["","","","or a lot dirty, actually","","","","","",""],
["","","","some gloves wouldn't hurt...","","","null","","",""],
["tori_park_rock","_none","","you found...","increment_holes","","","","",""],
["","","dig_rock","a rock!","","","","","",""],
["","you","","that doesn't [i]rock.[/i]","_dug_rock","hole_count == 16",['tori_park_ending', 'null'],"","",""],
["tori_park_coin","_none","","you found...","increment_holes","","","","",""],
["","","dig_coin","a coin!","","","","","",""],
["","you","","buried coins? that doesn't even make [i]cents.[/i]","_dug_coin","hole_count == 16",['tori_park_ending', 'null'],"","",""],
["tori_park_can","_none","","you found...","increment_holes","","","","",""],
["","","dig_can","a can of black beans!","","","","","",""],
["","you","","i [i]can[/i]-t believe it!","","","","","",""],
["","tori",['dig_can', 'tori_neutral'],"hey, i love black beans!","","","","","",""],
["","","","is it still good?","","","","","",""],
["","you","","um, let me see","","","","","",""],
["","","","...","","","","","",""],
["","","","next to \"best by\" it just says \"good luck\"","","","","","",""],
["","tori","","huh","_dug_can","hole_count == 16",['tori_park_ending', 'null'],"","",""],
["tori_park_bone","_none","","you found...","increment_holes","","","","",""],
["","","dig_bone","a bone!","","","","","",""],
["","you","","i have a [i]bone[/i] to pick with this place.","","","","","",""],
["","tori",['dig_bone', 'tori_neutral'],"you said it.","_dug_bone","hole_count == 16",['tori_park_ending', 'null'],"","",""],
["tori_park_kyungsoon","_none","","you found...","increment_holes","","","","",""],
["","","kyungsoon_neutral","kyungsoon!","","","","","",""],
["","you","","kyungsoon????","","","","","",""],
["","kyungsoon","","sup","","","","","",""],
["","you","","what are you doing in the ground??","","","","","",""],
["","kyungsoon","","idk","","","","","",""],
["","","","just chilling","","","","","",""],
["","tori",['kyungsoon_neutral', 'tori_neutral'],"kyungsoon, do you want to help us dig?","","","","","",""],
["","kyungsoon","","lol no thanks","","","","","",""],
["","","","i'm just gonna go back to the commons","","","","","",""],
["","tori","","okay, take care","","","","","",""],
["","you","","??????","_dug_kyungsoon","hole_count == 16",['tori_park_ending', 'null'],"","",""],
["tori_park_worm","_none","","you found...","increment_holes","","","","",""],
["","","dig_worm","a worm!","","","","","",""],
["","tori",['dig_worm', 'tori_neutral'],"what do you think that worm did to end up in purrgatory?","","","","","",""],
["","you","","hmm....","","","","","",""],
["","","","digging under the influence?","","","","","",""],
["","tori","","...i'm sorry i asked","_dug_worm","hole_count == 16",['tori_park_ending', 'null'],"","",""],
["tori_park_diamond","_none","","you found...","increment_holes","","","","",""],
["","","dig_diamond","a diamond!","","","","","",""],
["","you","","holy shit","","","","","",""],
["","tori",['dig_diamond', 'tori_neutral'],"what is it?","","","","","",""],
["","you","","look, i found a diamond!","","","","","",""],
["","","","do you think it's real?","","","","","",""],
["","tori","","hold it up to your mouth and breathe on it. ","","","","","",""],
["","","","if the fog goes away immediately, it's real.","","","","","",""],
["","_none","","you breathe on the gem.","","","","","",""],
["","you","","oh my god, it's real!","","","","","",""],
["","tori","","great.","","","","","",""],
["","","","but what are we going to do with it?","","","","","",""],
["","you","","uhhhh","","","","","",""],
["","","","huh","","","","","",""],
["","","","good point","","","","","",""],
["","tori","","give it to kyungsoon","","","","","",""],
["","","","maybe she'll eat it.","_dug_diamond","hole_count == 16",['tori_park_ending', 'null'],"","",""],
["tori_park_foot","_none","","you found...","increment_holes","","","","",""],
["","","dig_foot","a foot!","","","","","",""],
["","you","","...i'm just going to leave that where i found it","","","","","",""],
["","tori",['dig_foot', 'tori_neutral'],"you mean you're not going to [i]toe[/i] it away?","","","","","",""],
["","you","","wait, was that a pun??","","","","","",""],
["","tori","","oh god","","","","","",""],
["","","","you're rubbing off on me","_dug_foot","hole_count == 16",['tori_park_ending', 'null'],"","",""],
["tori_park_fridge","_none","","you found...","increment_holes","","","","",""],
["","","dig_fridge","a mini fridge!","","","","","",""],
["","you","","i was starting to get hot, so it's a good thing i got a [i]little cooler[/i]","_dug_fridge","hole_count == 16",['tori_park_ending', 'null'],"","",""],
["tori_park_shovel","_none","","you found...","increment_holes","","","","",""],
["","","dig_shovel","a shovel!","","","","","",""],
["","you","","...this feels weird for some reason","_dug_shovel","hole_count == 16",['tori_park_ending', 'null'],"","",""],
["tori_park_robot","_none","","you found...","increment_holes","","","","",""],
["","","dig_robot","a toy robot!","","","","","",""],
["","you","","something a-[i]bot[/i] this doesn't feel right","_dug_robot","hole_count == 16",['tori_park_ending', 'null'],"","",""],
["tori_park_ukulele","_none","","you found...","increment_holes","","","","",""],
["","","dig_ukulele","a ukulele!","","","","","",""],
["","you","","[i]uke[/i] gotta be kidding me","","","","","",""],
["","tori",['dig_ukulele', 'tori_neutral'],"hey, i used to play the ukulele!","","","","","",""],
["","","","did you know i directed my school's ukulele ensemble?","","","","","",""],
["","you","","oh cool! ","","","","","",""],
["","","","do you want this one?","","","","","",""],
["","tori","","no thanks. ","","","","","",""],
["","","","i'm afraid it'll somehow make meow noises.","_dug_ukulele","hole_count == 16",['tori_park_ending', 'null'],"","",""],
["tori_park_nothing","_none","","you found...","increment_holes","","","","",""],
["","","","nothing!","","","","","",""],
["","you","","boo","_dug_nothing","hole_count == 16",['tori_park_ending', 'null'],"","",""],
["tori_park_clock","_none","","you found...","increment_holes","","","","",""],
["","","dig_clock","a cat-themed clock!","","","","","",""],
["","you","","that is creepy.","_dug_clock","hole_count == 16",['tori_park_ending', 'null'],"","",""],
["tori_park_chess","_none","","you found...","increment_holes","","","","",""],
["","","dig_chess","a cat-themed chess piece!","","","","","",""],
["","you","","i'm starting to get a little [i]board[/i]","","","","","",""],
["","tori",['dig_chess', 'tori_neutral'],"need a break?","","","","","",""],
["","you","","oh, no, that was just a pun","","","","","",""],
["","tori","","oh. should have figured.","_dug_chess","hole_count == 16",['tori_park_ending', 'null'],"","",""],
["tori_park_snowglobe","_none","","you found...","increment_holes","","","","",""],
["","","dig_snowglobe","a snowglobe!","","","","","",""],
["","you","","cool, a snowglobe!",[['_dug_snowglobe', true], ['_delay__inv_snowglobe_park', true]],"hole_count == 16",['tori_park_ending', 'null'],"","",""],
["tori_park_ending","","","_pass","","met_numa",['tori_park_ending_normal', 'tori_park_ending_alt'],"","",""],
["tori_park_ending_normal","numa",['tori_neutral', 'numa_neutral'],"TORI!!!","surprise_audio","","","","",""],
["","","","WHAT THE HELL ARE YOU DOING?!","tori_park_complete","","","","",""],
["","tori","","oh, just trying to save us all. you're welcome.","","","","","",""],
["","numa","","YOU'RE RUINING THE PARK!!","","","","","",""],
["","tori","","ehhh","","","","","",""],
["","","","debatable","","","","","",""],
["","","","did you miss the part about saving us all?","","","","","",""],
["","numa","","oh my god","","","","","",""],
["","","","how many holes did you dig?","","","","","",""],
["","tori","","don't worry, no more than twenty","","","","","",""],
["","numa","","TWENTY??","","","","","",""],
["","","","","","","","",["i'm so sorry", "it's for the best"],['tori_park_ending1', 'tori_park_ending2']],
["tori_park_ending1","you","","i'm so sorry, i didn't even think about the damage we're doing...","","","","","",""],
["","numa","","of COURSE you didn't!!","","","tori_park_ending3","","",""],
["tori_park_ending2","you","","tori's right, it's for the best...","","","","","",""],
["","numa","","well, you could have at least ASKED!!","","","","","",""],
["tori_park_ending3","_none","","numa closes her eyes.","","","","","",""],
["","numa","","ok, ok...","","","","","",""],
["","","","deep breaths, numa...","","","","","",""],
["","tori","","listen, i'm sorry. i'll make it up to you, somehow.","","","","","",""],
["","","","leave {player} out of it, at least. it was my idea.","","","","","",""],
["","numa","","fine.","","","","","",""],
["","","","we'll talk about this. ","","","","","",""],
["","","","later.","","","","","",""],
["","_none","tori_neutral","numa stomps away.","","","","","",""],
["","tori","","...","","","","","",""],
["","","","sheesh","","","","","",""],
["","","","my bad, {player}. this plan was a bust, anyway.","","","","","",""],
["","you","","i guess it wasn't a very [i]hole[/i]-some plan","","","","","",""],
["","tori","","you can say that again.","","","","","",""],
["","","","but don't worry -- i have a feeling my next plan will be [i]electric[/i].","","","","","",""],
["","","","i'll see you around, okay?","","","","","",""],
["","you","","okay...","","","","","",""],
["","tori","","stay sharp.","_delay_remove_park_game","","null","","",""],
["tori_park_ending_alt","???",['tori_neutral', 'numa_neutral'],"TORI!!!",[['surprise_audio', true], ['met_numa', true]],"","","","",""],
["","","","WHAT THE HELL ARE YOU DOING?!","","","","","",""],
["","tori","","oh, just trying to save us all. you're welcome.","","","","","",""],
["","???","","YOU'RE RUINING THE PARK!!","","","","","",""],
["","tori","","ehhh","","","","","",""],
["","","","debatable","","","","","",""],
["","","","did you miss the part about saving us all?","","","","","",""],
["","???","","oh my god","","","","","",""],
["","","","how many holes did you dig??","","","","","",""],
["","tori","","don't worry, no more than twenty","","","","","",""],
["","???","","TWENTY??","","","","","",""],
["","you","","oh my gosh, i'm sorry... is this your park?","","","","","",""],
["","???","","wait","","","","","",""],
["","","","who are you?","","","","","",""],
["","you","","i'm {player},` i'm new here!","","","","","",""],
["","???","","...you're telling me someone just arrived and you've ALREADY roped {them} into your STUPID PLANS??","","","","","",""],
["","tori","","hey, {they} volunteered for this!","","","","","",""],
["","","","...also my plans are not stupid.","","","","","",""],
["","_none","","the snail closes her eyes.","","","","","",""],
["","???","","ok, ok...","","","","","",""],
["","","","deep breaths, numa...","","","","","",""],
["","tori","","listen, i'm sorry. i'll make it up to you, somehow.","","","","","",""],
["","","","leave {player} out of it, at least. it was my idea.","","","","","",""],
["","numa","","fine.","","","","","",""],
["","","","we'll talk about this. ","","","","","",""],
["","","","later.","","","","","",""],
["","_none","tori_neutral","numa stomps away.","","","","","",""],
["","tori","","...","","","","","",""],
["","","","sheesh","","","","","",""],
["","","","my bad, {player}. this plan was a bust, anyway.","","","","","",""],
["","you","","i guess it wasn't a very [i]hole[/i]-some plan","","","","","",""],
["","tori","","you can say that again.","","","","","",""],
["","","","but don't worry -- i have a feeling my next plan will be [i]electric[/i].","","","","","",""],
["","","","i'll see you around, okay?","","","","","",""],
["","you","","okay...","","","","","",""],
["","tori","","stay sharp.","tori_park_complete","","","","",""],
["","_none","_none","tori marches off.","_delay_remove_park_game","","null","","",""],
["tori_park_leave","_none","","you should probably finish helping tori before you leave.","","","null","","",""],
["tori_park_hole","_none","","one of the holes you dug.","","","null","","",""],
["tori_closet","","","_pass","","talked_to_tori_closet",['tori_closet1', 'tori_closet2'],"","",""],
["tori_closet1","tori","tori_neutral","you're back.","","","","","",""],
["","","","now are you free?","","","","","",""],
["","","","","","","",['true', 'true', '_inv_chess_letter', 'elijah_planning_slam and not invited_tori'],['affirmative', 'later', '(deliver oliver\'s letter)', '(invite tori to the everything slam)'],['tori_closet3', 'tori_closet4', 'tori_chess', 'tori_invitation']],
["tori_closet2","tori","tori_neutral","ah, {player}, my favorite sinner.","talked_to_tori_closet","","","","",""],
["","","","wear these. you'll need it.","","","","","",""],
["","_none","","tori hands you a pair of heavy-duty gloves.","","","","","",""],
["","you","","huh?","","","","","",""],
["","","","what's up now?","","","","","",""],
["","tori","","electricity. it makes the world go round. ","","","","","",""],
["","","","and also purrgatory, presumably.","","","","","",""],
["","","","these wires have to be hooked up to something, and that something is outside of purrgatory.","","","","","",""],
["","","","thus, this box could be our ticket out of here!","","","","","",""],
["","","","think you can help?","","","","","",""],
["","","","","","","",['true', 'true', '_inv_chess_letter', 'elijah_planning_slam and not invited_tori'],['affirmative', 'maybe later', '(deliver oliver\'s letter)', '(invite tori to the everything slam)'],['tori_closet3', 'tori_closet4', 'tori_chess', 'tori_invitation']],
["tori_closet4","you","","umm, maybe later","","","","","",""],
["","","","i'm not really keen on messing with live wires...","","","","","",""],
["","tori","","well, that's what the gloves are for.","","","","","",""],
["","","","but you do you.","","","null","","",""],
["tori_closet3","you","","sure, i'll do my best!","","","","","",""],
["","tori","","perfect.","","","","","",""],
["","","","here, take a look.","","","","","",""],
["tori_wire_intro","_none","_none","you peer into the electrical box.","_goto_wire_game","","","","",""],
["","tori","","now, i'm no amateur when it comes to electrical engineering, but frankly this circuit is dumbfounding me.","","","","","",""],
["","","","maybe something is supposed to happen if you connect the nodes a certain way?","","","","","",""],
["","","","i was hoping you'd have better luck than me.","","","","","",""],
["","you","","are you sure this is safe??","","","","","",""],
["","tori","","fairly sure. let's say 90%.","","","","","",""],
["","","","i gave you the gloves, didn't i?","","","","","",""],
["","you","","i guess so...","","","","","",""],
["","_none","","(click and drag on a node to create a wire!)","","","null","","",""],
["tori_wire_blackout","you","","uh oh","queue_hide_tori","","","","",""],
["","tori","tori_neutral","{player}, what did you do??","_goto_closet","","","","",""],
["","you","","i don't know! i just connected some wires!","","","","","",""],
["","tori","","ugh","","","","","",""],
["","","","looks like the power's out all over purrgatory.","","","","","",""],
["","","","great. juuust what we needed.","","","","","",""],
["","you","","umm, maybe if i undo what i did, the lights will turn back on?","","","","","",""],
["","_none","","you squint, but you can't make out any of the wires in the dark.","","","","","",""],
["","tori","","...maybe let someone with night vision take over for now.","","","","","",""],
["","","","why don't you go look for a light source?","","","","","",""],
["","","","i'll keep messing with this in the meanwhile.","_quest_tori_lights","","","","",""],
["","you","","um, okay","","","","","",""],
["","","","but...","","","","","",""],
["","tori","","but what?","","","","","",""],
["","you","","it looks kind of spooky out there...","","","","","",""],
["","tori","","[i]sigh[/i]","","","","","",""],
["","","","you're a big kid. you'll be fine.","","","","","",""],
["","you","","okay...","_delay_blackout_music","","null","","",""],
["tori_blackout","","","_pass","","_inv_candle",['tori_blackout2', 'tori_blackout1'],"","",""],
["tori_blackout1","tori","tori_neutral","any luck finding a light?","","","","","",""],
["","you","","no...","","","","","",""],
["","tori","","well, hurry up, already.","","","","","",""],
["","","","hmm... maybe if i connect these two...","","","null","","",""],
["natalie_blackout","","","_pass","","_inv_candle",['natalie_blackout2', 'natalie_blackout1'],"","",""],
["natalie_blackout1","you","natalie_neutral","natalie, you have candles!!","","","","","",""],
["","natalie","","yeah i do!!","","","","","",""],
["","","","this is the first time i've actually gotten to use them","","","","","",""],
["","","","i am very happy","","","","","",""],
["","you","","you're not concerned about the electricity being out?","","","","","",""],
["","natalie","","not really","","","","","",""],
["","","","the ambience is way better this way","","","","","",""],
["","","","makes me want to take a niiiice, long nap","","","","","",""],
["","you","","i see","","","","","",""],
["","","","can i borrow one of your candles btw?","","","","","",""],
["","natalie","","sure, take as many as you want!","","","","","",""],
["","you","","thanks!","","","","","",""],
["","","","uhh, i'll just take this one","_inv_candle","","","","",""],
["","natalie","","sounds good","","","","","",""],
["","you","","i gotta go, but i'll see you around","","","","","",""],
["","natalie","","cya dude","","","","","",""],
["","","","come back if you wanna nap together!","","","","","",""],
["","you","","um, i'll think about it!","","","null","","",""],
["natalie_blackout2","you","natalie_neutral","enjoying the darkness?","","","","","",""],
["","natalie","","zzz.... ","","","","","",""],
["","","","hm? sorry, i was dozing off","","","","","",""],
["","you","","are you enjoying the darkness?","","","","","",""],
["","natalie","","oh yeah","","","","","",""],
["","","","lovin it","","","null","","",""],
["elijah_blackout","","","_pass","","met_elijah",['elijah_blackout1', 'es_intro_elijah'],"","",""],
["elijah_blackout1","elijah","elijah_neutral","so, the lights are out.","","","","","",""],
["","","","think it's a sign of the end times?","","","","","",""],
["","you","","um i think it's more a sign that tori and i were messing with the electrical box","","","","","",""],
["","elijah","","oh.","","","","","",""],
["","","","that makes sense too","","","null","","",""],
["numa_blackout","","","_pass","",['not met_numa', 'trample_flag'],['numa_intro1', 'numa_intro2', 'numa_blackout1'],"","",""],
["numa_blackout1","numa","numa_neutral","oh... i hope my flowers will be okay in the dark...","","","","","",""],
["","you","","i'm sure they'll be fine!","","","null","","",""],
["kyungsoon_blackout","you","kyungsoon_neutral","hey","","","","","",""],
["","kyungsoon","","hey","","","","","",""],
["","you","","it's dark","","","","","",""],
["","kyungsoon","","yep","","","","","",""],
["","you","","how do you feel about that?","","","","","",""],
["","kyungsoon","","normal","","","null","","",""],
["oliver_blackout","oliver","oliver_neutral","{player}! the lights went out during a CRUCIAL part of my research!","","","","","",""],
["","","","do you have any clue what's going on??","","","","","",""],
["","you","","sorry, that was my fault!","","","","","",""],
["","","","tori and i were messing with the electricity and we sort of caused a power failure?","","","","","",""],
["","","","but we're trying to fix it!","","","","","",""],
["","oliver","","please do","","","","","",""],
["","","","i can't read a single meow under these conditions!","","","null","","",""],
["sean_blackout","","","_pass","","met_sean",['sean_blackout1', 'es_intro_sean'],"","",""],
["sean_blackout1","sean","sean_neutral","ayyy, {player}, my funky friend","","","","","",""],
["","","","the lights went out, how rad is that?","","","","","",""],
["","you","","pretty rad, i guess","","","","","",""],
["","sean","","that's the spirit, my pugnacious pal!","","elijah_and_sean_together",['sean_blackout2', 'null'],"","",""],
["sean_blackout2","elijah",['elijah_neutral', 'sean_neutral'],"i don't think pugnacious means what you think it does, sean","display_elijah_and_sean","","","","",""],
["","sean","","who cares what it means?","","","","","",""],
["","","","it sounds cool as hell","","","null","","",""],
["elijah_blackout_nap","_none","","you should probably fix the lights before bothering elijah.","","","null","","",""],
["oliver_blackout_nap","_none","","you should probably fix the lights before bothering oliver.","","","null","","",""],
["tori_blackout2","you","tori_neutral","i brought a candle!",[['_quest_tori_lights', false]],"","","","",""],
["","tori","","great!","","","","","",""],
["","","","hopefully you can make heads or tails of this, because i'm stumped","","","","","",""],
["","you","","i'll take a look, but no promises...","","","","","",""],
["","_none","_none","(click and drag on a node to create a wire!)",[['_goto_wire_game', true], ['start_skip_timer', true]],"","null","","",""],
["tori_wire_skip","tori","","whoa, how did you do that?","tori_closet_complete","","","","",""],
["","you","","uh","","","","","",""],
["","","","a little shelf popped out of the side and i pressed a button and the lights came back on?","","","","","",""],
["","tori","","huh","","","","","",""],
["","","","not the weirdest thing i've seen today.","","","tori_wire_success1","","",""],
["tori_wire_success","tori","","hey, you actually did it!","tori_closet_complete","","","","",""],
["","you","","it wasn't that bad, you just had to connect the nodes!","","","","","",""],
["","tori","","damn, guess you have some engineering chops in ya.","","","","","",""],
["tori_wire_success1","","tori_neutral","well, guess we're back to square one, huh?","_goto_closet","","","","",""],
["","you","","i think maybe we should stop messing with it for now...","","","","","",""],
["","tori","","i think that's a good call.","","","","","",""],
["","","","not to leave you on a [i]cliff[/i]-hanger, but i've got a few more ideas yet.","","","","","",""],
["","","","don't be a stranger.","","","","","",""],
["","you","","okay!","","","","","",""],
["","_none","_none","tori leaves.","","","","","",""],
["","","","guess there's no need to carry this candle around anymore.",[['_inv_candle', false]],"","null","","",""],
["tori_dropoff","","","_pass","",['preparing_for_climb', 'talked_to_tori_dropoff'],['tori_dropoff8', 'tori_dropoff6', 'tori_dropoff_a'],"","",""],
["tori_dropoff_a","tori","tori_neutral","{player}! my favorite accomplice!","talked_to_tori_dropoff","","","","",""],
["","you","","um","","","","","",""],
["","","","do i want to ask what you're doing now?","","","","","",""],
["","tori","","the dropoff. a mystery that's been staring us in the face for far too long.","","","","","",""],
["","","","it's finally time to breach its harrowing depths.","","","","","",""],
["","you","","is it though??","","","","","",""],
["","","","that seems really dangerous?","","","","","",""],
["","tori","","don't worry, i've done my fair share of spelunking, so it'll be perfectly safe.","","","","","",""],
["","","","do you want to escape or not?","","","","","",""],
["","you","","i mean...","","","","","",""],
["","","","i guess so...","","","","","",""],
["","tori","","then listen up.","","","","","",""],
["","","","unfortunately, this shaft is too narrow for me to fly down. that's what this is for.","","","","","",""],
["","_none","","tori holds up the rope.","","","","","",""],
["","tori","","a hundred feet of strong, braided nylon rope.","","","","","",""],
["","","","one of us is going to go down there. the only question is which.","","","","","",""],
["","","","","","","","",['...did you say you\'ve been spelunking?', 'i feel like we\'re going the wrong way', 'this reeeeally doesn\'t seem safe'],['tori_dropoff1', 'tori_dropoff2', 'tori_dropoff3']],
["tori_dropoff1","you","","umm","","","","","",""],
["","","","did you say you've been spelunking?","","","","","",""],
["","tori","","oh yes. ellison's cave, carlsbad caverns... i've hit the hotspots.","","","","","",""],
["","you","","ooh, cool!","","","","","",""],
["","","","what's that like?","","","","","",""],
["","tori","","it's tremendous. i--","","","","","",""],
["","","","hey, don't try to change the subject!","","","","","",""],
["","you","","eep, sorry","","","tori_dropoff4","","",""],
["tori_dropoff2","you","","i really feel like we're going the wrong way","","","","","",""],
["","","","like","","","","","",""],
["","","","shouldn't we be trying to go... up?","","","","","",""],
["","tori","","worried the hole will deposit us directly into hell?","","","","","",""],
["","you","","maybe??","","","","","",""],
["","tori","","well, so be it.","","","","","",""],
["","","","i have a few choice words for the devil anyhow.","","","tori_dropoff4","","",""],
["tori_dropoff3","you","","this reeeeally doesn't seem safe","","","","","",""],
["","","","like, i don't know if it's possible to die in purrgatory, but i really don't want to find out!","","","","","",""],
["","tori","","fine, then what would you rather do?","","","","","",""],
["","","","sit around until someone descends from on high to save us?","","","","","",""],
["","","","how would you feel if it turned out the exit was right in front of us the entire time?","","","","","",""],
["","you","","i mean...","","","","","",""],
["","","","i guess that would suck...","","","","","",""],
["","tori","","exactly.","","","tori_dropoff4","","",""],
["tori_dropoff4","tori","","i'm going to flip that coin we found in the park.","","","","","",""],
["","","","if it's heads, i'll go down and you hold the rope. if it's tails, vice versa.","","","","","",""],
["","","","that sounds fair, right?","","","","","",""],
["","you","","yeah, i guess that's fair...","","","","","",""],
["","tori","","alright, then.","","","","","",""],
["","","","are you ready?","","","","","",""],
["","","","","","","",['true', 'true', '_inv_chess_letter', 'elijah_planning_slam and not invited_tori'],['i think i have some other stuff to do', 'i guess so', '(deliver oliver\'s letter)', '(invite tori to the everything slam)'],['tori_dropoff5', 'tori_dropoff7', 'tori_chess', 'tori_invitation']],
["tori_dropoff5","you","","actuallyyyy i think i have some other stuff to do first...","","","","","",""],
["","tori","","hmph. fine. but i'll be waiting.","","","null","","",""],
["tori_dropoff6","tori","tori_neutral","ready now?","","","","","",""],
["","","","","","","",['true', 'true', '_inv_chess_letter', 'elijah_planning_slam and not invited_tori'],['i think i have some other stuff to do', 'i guess so', '(deliver oliver\'s letter)', '(invite tori to the everything slam)'],['tori_dropoff5', 'tori_dropoff7', 'tori_chess', 'tori_invitation']],
["tori_dropoff7","you","","i guess so??","","","","","",""],
["","tori","","well, here goes nothing.","","","","","",""],
["","_none","","...","toss_coin","","","","",""],
["","tori","","tails. that's you.","","","","","",""],
["","you","","[i]gulp[/i]","","","","","",""],
["","tori","","don't worry, i'll make you a secure harness first."," ","","","","",""],
["","","","i have lots of practice tying people up.","","","","","",""],
["","","","...don't ask","","","","","",""],
["","","","hold up your arms?","","","","","",""],
["","_none","","you hold up your arms and tori ties a makeshift harness around you.","","","","","",""],
["","tori","","there, that should catch you if you lose your grip.","","","","","",""],
["","","","but still try to hold onto the rope if you can.","","","","","",""],
["","you","","alright...","","","","","",""],
["","tori","","i'll tie the other end around this post, and i'll keep a hold of it too.","","","","","",""],
["","","","see, it'll be perfectly safe!","","","","","",""],
["","you","","okay yeah","","","","","",""],
["","","","safe","","","","","",""],
["","_none","","tori finishes tying the rope, then throws the slack down the hole. finally, she hands you a flashlight.","","","","","",""],
["","tori","","all set.","","","","","",""],
["","you","","do i just... climb down now?","","","","","",""],
["","tori","","yes, that's the idea.","","","","","",""],
["","","","whenever you're ready.","_delay_preparing_for_climb","","null","","",""],
["tori_dropoff8","tori","tori_neutral","well? what are you waiting for?","","","","","",""],
["","","","heaven could be within our grasp!","","","","","",""],
["","you","","yeah! i guess!","","","","","",""],
["","","","it's kinda scary though...","","","","","",""],
["","tori","","don't worry, i'll hold on tight.","","","null","","",""],
["tori_leave_dropoff","_none","","you couldn't leave even if you wanted to because you're tied to the post.","","","null","","",""],
["tori_climb0","you","","alright, here goes nothing...","","","","","",""],
["","_none","","(hold up or down to climb the rope!)","","","null","","",""],
["tori_climb1a","tori","","see anything yet?","","","","","",""],
["","you","","not really!","","","","","",""],
["","","","...","","","","","",""],
["","","","um, the rope is kind of creaking a lot","","","","","",""],
["","tori","","ropes tend to do that, yes.","","","","","",""],
["","you","","...","","","","","",""],
["","","","maybe i should have written a will or something before coming down here...","","","","","",""],
["","tori","","[i]sigh[/i]","","","","","",""],
["","","","don't be ridiculous. you're already dead.","","","","","",""],
["","you","","oh yeah... true...","","","null","","",""],
["tori_climb1b","you","","when are you supposed to write a will, anyway?","","","","","",""],
["","","","i don't think i had a will when i died","","","","","",""],
["","tori","","well, you can legally write a will once you turn 18.","","","","","",""],
["","","","it's not a big deal if you don't have one.","","","","","",""],
["","","","they'll give your personal belongings and assets to your spouse, children, or parents.","","","","","",""],
["","you","","oh, cool","","","null","","",""],
["tori_climb1c","you","","what about stuffed animals?","","","","","",""],
["","tori","","yes, those count as personal belongings.","","","","","",""],
["","you","","oh, right","","","null","","",""],
["tori_climb_snowglobe","you","","cool, a snowglobe!","_inv_snowglobe_dropoff","","","","",""],
["","tori","","sorry, a snowglobe?","","","","","",""],
["","you","","yeah, there was one sitting in an alcove in the wall!","","","","","",""],
["","tori","","strange.","","","","","",""],
["","","","you know, i feel like i've seen a lot of those lying around.","","","","","",""],
["","you","","me too!","","","","","",""],
["","","","do you think it means anything?","","","","","",""],
["","tori","","hmmm","","","","","",""],
["","","","maybe if you collect all of them and bring them to one location, then...?","","","","","",""],
["","","","no, that's too far-fetched, even for this place","","","","","",""],
["","you","","yeah, probably","","","null","","",""],
["tori_climb2a","you","","did i ever tell you i'm afraid of the dark?","","","","","",""],
["","tori","","i think you mentioned it once, yeah","","","","","",""],
["","you","","well","","","","","",""],
["","","","it's getting kinda dark down here","","","","","",""],
["","tori","","gee, if only you had some sort of tool for producing light","","","","","",""],
["","you","","oh, yeah","","","","","",""],
["","","","...","turn_on_flashlight","","","","",""],
["","","","it's still pretty dark...","","","","","",""],
["","tori","","[i]sigh[/i]","","","","","",""],
["","","","you know, i used to have a friend just like you ","","","","","",""],
["","","","slept with a night light till she was sixteen","","","","","",""],
["","you","","oh wow","","","","","",""],
["","tori","","she used to call me in the middle of the night because she saw something move in her bedroom.","","","","","",""],
["","","","mind you, we were teenagers then.","","","","","",""],
["","you","","that does sound like something i would do","","","","","",""],
["","tori","","yep.","","","null","","",""],
["tori_climb2b","tori","","you know, one time she called me at 3 am because she thought someone had broken into the house","","","","","",""],
["","","","of course, [i]i[/i] told her to call 911, but she didn't want to get off the phone with me","","","","","",""],
["","","","so i had to drive all the way to her place in my pajamas.","","","","","",""],
["","you","","was she okay??","","","","","",""],
["","tori","","oh yeah, she was fine","","","","","",""],
["","","","turned out her carrot got loose, knocked the toaster off the counter, and started screeching ","","","","","",""],
["","","","scared the hell out of me when i went inside, too.","","","","","",""],
["","you","","her carrot??","","","","","",""],
["","tori","","parrot! her pet parrot!","","","","","",""],
["","you","","ohhh","","","","","",""],
["","","","sorry, it's sort of hard to hear from down here","","","","","",""],
["","tori","","it's fine.","","","null","","",""],
["tori_climb_ttt","_none","_none","_pass","","saw_climb_ttt",['tori_climb_ttt2', 'tori_climb_ttt1'],"","",""],
["tori_climb_ttt1","you","","there's a tic tac toe game down here!","saw_climb_ttt","","","","",""],
["","tori","","a what?","","","","","",""],
["","you","","a tic tac toe game!!","","","","","",""],
["","tori","","you'd better not be pulling my wing.","","","","","",""],
["","you","","no really, there is!","","","","","",""],
["","tori","","[i]sigh[/i]","","","","","",""],
["","","","this raises more questions than it answers","","","","","",""],
["","you","","true","","","null","","",""],
["tori_climb_ttt2","tori","","who won, x's or o's?","","","","","",""],
["","you","","looks like it was a tie","","","","","",""],
["","tori","","should have known.","","","null","","",""],
["tori_climb2c","you","","so, what was your friend's name?","","","","","",""],
["","tori","","aisha.","","","","","",""],
["","you","","didn't you say you were teenagers?","","","","","",""],
["","","","where were her parents?","","","","","",""],
["","tori","","she had a father, but he wasn't exactly home all the time.","","","","","",""],
["","you","","that's terrible!","","","","","",""],
["","tori","","eh. she was old enough to take care of herself.","","","","","",""],
["","","","i guess.","","","","","",""],
["","","","...","","","","","",""],
["","","","we fell out of touch after high school. i think she's a veterinarian now?","","","","","",""],
["","you","","oh, good for her","","","null","","",""],
["tori_climb3a","you","","i have a theory!","","","","","",""],
["","tori","","yes?","","","","","",""],
["","you","","what if","","","","","",""],
["","","","this used to be a really long hallway?","","","","","",""],
["","","","and people would play tic-tac-toe in it and stuff","","","","","",""],
["","","","but at some point it got turned sideways","","","","","",""],
["","","","so now it's a really deep pit?","","","","","",""],
["","tori","","no offense, but that's...","","","","","",""],
["","","","...","","","","","",""],
["","","","actually, that makes sense in a weird kind of way","","","","","",""],
["","you","","right??","","","null","","",""],
["tori_climb3b","tori","","actually, i changed my mind. that literally makes no sense","","","","","",""],
["","you","","yeah, that's fair","","","null","","",""],
["tori_climb_lucifur","you","","hey, there's something written on the wall!","","","","","",""],
["","tori","","what is it?","","","","","",""],
["","you","","hold on","","","","","",""],
["","","","it says...","","","","","",""],
["","","","\"lucifur wuz here too\"","","","","","",""],
["","_none","","[i]crack![/i]","climb_crack1","","","","",""],
["","you","","what was that?!","","","","","",""],
["","tori","","nothing!","","","","","",""],
["","_none","","[i]CRACK[/i]","climb_crack2","","","","",""],
["","you","","AAAAAAAAAAAAAAA","","","","","",""],
["","","","OHMY GOD IM GONNA DIE","","","","","",""],
["","tori","","it's ok! it's ok! i got the rope!","","","","","",""],
["","you","","TORI EHLP","","","","","",""],
["","tori ","","just hang on, i'll pull you up!","","","","","",""],
["","_none","","(press up repeatedly to hang on!)","_delay_start_climb_game","","null","","",""],
["tori_climb_fall","you","","AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA","","","","","",""],
["","","","oof","","","","","",""],
["","tori","","{player}!! are you okay??","","","","","",""],
["","you","","i'm okay, the harness caught me!","","","","","",""],
["","tori","","jeez, you gave me a heart attack!","","","","","",""],
["","","","just... stay there, i'll keep pulling you up!","","","","","",""],
["","you","","stay here? where else am i going to go???","","","","","",""],
["","tori","","NOW is when you develop a sense of sarcasm??","_delay__music_Phew","","null","","",""],
["tori_climb_fall_alt","you","","AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA","","","","","",""],
["","","","oof","","","","","",""],
["","tori","","{player}!! are you okay??","","","","","",""],
["","you","","i'm okay, the harness caught me!","","","","","",""],
["","tori","","jesus christ, did you even TRY to hold on?","","","","","",""],
["","you","","um","","","","","",""],
["","","","not really, no","","","","","",""],
["","tori","","ugh, just stay there, i'll keep pulling you up!","_delay__music_Phew","","null","","",""],
["tori_climb_return","tori","","got you!","tori_dropoff_complete","","","","",""],
["","_none","tori_neutral","tori pulls you onto the platform.","_goto_dropoff1","","","","",""],
["","you","","oh my GOD i'm never doing that again","","","","","",""],
["","tori","","yeah... [i]huff[/i]... no kidding","","","","","",""],
["","","","i'm just glad you're okay","","","","","",""],
["","you","","i almost DIED","","","","","",""],
["","tori","","{player}, we've been over this, you're already--","","","","","",""],
["","you","","fine, i almost died AGAIN","","","","","",""],
["","tori","","listen, i'm sorry. i thought that post was stronger than that.","","","","","",""],
["","","","at least we got to see what's down there, right?","","","","","",""],
["","you","","which is a fat load of NOTHING","","","","","",""],
["","tori","","i mean, still!","","","","","",""],
["","","","we never would have known otherwise.","","","","","",""],
["","you","","aahhsdgafdfg","","","","","",""],
["","tori","","...","","","","","",""],
["","","","are you... okay?","","","","","",""],
["","you","","idk","","","","","",""],
["","","","i think i just need to","","","","","",""],
["","","","lie down for a little bit","","","","","",""],
["","tori","","alright, let me get these ropes off you.","","","","","",""],
["","","","...","","","","","",""],
["","","","thanks for doing that. it was really brave.","","","","","",""],
["","you","","yeah","","","","","",""],
["","tori","","i'll, um, talk to you later.","","","","","",""],
["","you","","okay","","","","","",""],
["","_none","","tori awkwardly walks away.","","","null","","",""],
["tori_climb_again","_none","","you're not even getting CLOSE to that edge again","","","null","","",""],
["tori_climb_easter_egg","tori","_none","...","","","","","",""],
["","","","{player}","","","","","",""],
["","you","","hi!","","","","","",""],
["","tori","","why did you climb all the way back up?","","","","","",""],
["","you","","um, idk ","","","","","",""],
["","","","just wanted to say hi","","","","","",""],
["","tori","","you know you're going to have to climb all the way back down, right?","","","","","",""],
["","you","","...","","","","","",""],
["","","","yeah... ","","","null","","",""],
["tori_end","","","_pass","","talked_to_tori_end",['tori_end_c', 'tori_end_d'],"","",""],
["tori_end_d","tori","tori_neutral","ah, {player}.","talked_to_tori_end","","","","",""],
["","","","good to see you.","","","","","",""],
["","you","","you too!","","","","","",""],
["","tori","","have you, uh","","","","","",""],
["","","","recovered? since the dropoff incident?","","","","","",""],
["","you","","yeah, i'm fine, i guess","","","","","",""],
["","tori","","good!","","","","","",""],
["","","","if you don't mind, i need some help again.","","","","","",""],
["","","","this time there's no chance of harm at all.","","","","","",""],
["","","","no angry gardeners, no live wires, no endless pits","","","","","",""],
["","","","just a door.","","","","","",""],
["","","","do you have the time?","","","","","",""],
["","","","","","","",['true', 'true', '_inv_chess_letter', 'elijah_planning_slam and not invited_tori'],['sure', 'not right now', '(deliver oliver\'s letter)', '(invite tori to the everything slam)'],['tori_end_a', 'tori_end_b', 'tori_chess', 'tori_invitation']],
["tori_end_b","you","","um, not right now","","","","","",""],
["","tori","","that's alright.","","","","","",""],
["","","","i can understand your misgivings given what happened last time.","","","null","","",""],
["tori_end_c","tori","tori_neutral","ah, are you here to help?","","","","","",""],
["","","","","","","",['true', 'true', '_inv_chess_letter', 'elijah_planning_slam and not invited_tori'],['sure', 'not right now', '(deliver oliver\'s letter)', '(invite tori to the everything slam)'],['tori_end_a', 'tori_end_b', 'tori_chess', 'tori_invitation']],
["tori_end_a","you","","i think i can handle a door!","","","","","",""],
["","tori","","great!","","","","","",""],
["","you","","so, what's the plan?","","","","","",""],
["","tori","","step one. figure out how to open this door.","","","","","",""],
["","","","step two. freedom.","","","","","",""],
["","you","","...","","","","","",""],
["","","","is that it?","","","","","",""],
["","tori","","for now.","","","","","",""],
["","","","any ideas on how to get this thing open?","","","","","",""],
["","you","","uhhh","","","","","",""],
["tori_end_main","","","","","","",['not tori_end_tried_kicking', 'not tori_end_tried_feeling', 'not tori_end_tried_knocking', 'true'],['kick it', 'look for hidden compartments', 'knock on it', 'wait'],['tori_end1', 'tori_end2', 'tori_end3', 'tori_end4']],
["tori_end1","you","","we could kick it?","tori_end_tried_kicking","","","","",""],
["","tori","","hmm","","","","","",""],
["","","","worth a shot.","","","","","",""],
["","_none","","you kick the door.","single_kick","","","","",""],
["","you","","ow","","","","","",""],
["","tori","","no, not like that.","","","","","",""],
["","","","sit down in front of the door and hit it with your heels. i've learned from experience.","","","","","",""],
["","you","","oh, cool","","","","","",""],
["","","","do i want to know...?","","","","","",""],
["","tori","","probably not.","","","","","",""],
["","_none","","you both start kicking the door.","start_kicking_sounds","","","","",""],
["","","","[i]thud. thud. thud.[/i]","","","","","",""],
["","you","","do you think it's getting weaker?","","","","","",""],
["","tori","","hm...","","","","","",""],
["","","","not really","","","","","",""],
["","_none","","[i]thud. thud. thud.[/i]","","","","","",""],
["","tori","","what is this door made of, steel?","","","","","",""],
["","_none","","[i]thud. thud. thud.[/i]","","","","","",""],
["","you","","so, what did numa say after she cooled down? about the holes?","","","","","",""],
["","tori","","oh, she was still pretty mad","","","","","",""],
["","","","i agreed to fill them back in and help with pruning to make up for it","","","","","",""],
["","you","","that's good","","","","","",""],
["","_none","","[i]thud. thud. thud.[/i]","","","","","",""],
["","tori","","apologizing. one of the few things i never learned how to do.","","","","","",""],
["","","","i always end up sounding sarcastic.","","","","","",""],
["","","","","","","","",['aw, it\'s not that hard!', 'well, actions speak louder than words', 'figures'],['tori_end1a', 'tori_end1b', 'tori_end1c']],
["tori_end1a","you","","aw, it's not that hard!","","","","","",""],
["","","","just say sorry, explain what you did was wrong, then ask what you can do to make up for it","","","","","",""],
["","tori","","hmm","","","","","",""],
["","","","well when you put it THAT way, it sounds easy","","","","","",""],
["","you","","idk, that's just how i usually go about it","","","","","",""],
["","tori","","how about this?","","","","","",""],
["","","","sorry. almost dropping you into an endless pit was selfish of me. what can i do to make up for it?","","","","","",""],
["","you","","awww, thanks","","","","","",""],
["","","","um","","","","","",""],
["","","","don't drop me into pits anymore?","","","","","",""],
["","tori","","i think i can handle that.","","","","","",""],
["","you","","sweet","","","tori_end1d","","",""],
["tori_end1b","you","","well, actions speak louder than words","","","","","",""],
["","","","maybe if you have trouble verbalizing an apology, you can show that you care in other ways?","","","","","",""],
["","tori","","hm...","","","","","",""],
["","","","that's an interesting idea.","","","","","",""],
["","you","","idk, just thinking out loud","","","","","",""],
["","tori","","how about this","","","","","",""],
["","","","why don't you take a break? i'll kick for both of us.","","","","","",""],
["","you","","oh, thanks! ","","","","","",""],
["","","","my feet were getting kind of sore.","","","","","",""],
["","tori","","no problem. i like kicking.","","","","","",""],
["","","","one of the many joys of having feet.","","","tori_end1d","","",""],
["tori_end1c","you","","figures.","tori_bad_choice2","","","","",""],
["","","","...no offense.","","","","","",""],
["","tori","","no, i... guess i deserve that.","","","","","",""],
["","you","","...","","","tori_end1d","","",""],
["tori_end1d","_none","","[i]thud. thud. thud.[/i]","","","","","",""],
["","tori","","i don't think this is working","stop_kicking_sounds","","","","",""],
["","you","","yeah, me neither","","","","","",""],
["","tori","","now what?","","","tori_end_main","","",""],
["tori_end2","you","","we could look for hidden compartments?","tori_end_tried_feeling","","","","",""],
["","","","like, maybe there's a panel on the wall that opens up when you push it?","","","","","",""],
["","tori","","not a bad idea.","","","","","",""],
["","","","i wouldn't put it past this place to work on escape room logic.","","","","","",""],
["","_none","","both of you start feeling up the walls.","","","","","",""],
["","you","","just walls over here","","","","","",""],
["","tori","","same","","","","","",""],
["","_none","","...","","","","","",""],
["","you","","so, um","","","","","",""],
["","","","how long have you been looking for a way out of here?","","","","","",""],
["","tori","","since the day i arrived, pretty much.","","","","","",""],
["","","","hard to tell how long it's been.","","","","","",""],
["","","","maybe a few years.","","","","","",""],
["","you","","oh wow, that's a lot of dedication","","","","","",""],
["","tori","","heh","","","","","",""],
["","","","do you think i became a black belt in karate, FIDE master in chess, and an expert businessperson by giving up easily?","","","","","",""],
["","","","every day i'm not trying to escape could be another day of freedom we're missing out on.","","","","","",""],
["","you","","dang, i see","","","","","",""],
["","","","but... still...","","","","","",""],
["","","","","","","","",['don\'t you ever get tired?', 'don\'t you ever do things for fun?', 'seems like a waste of time'],['tori_end2a', 'tori_end2b', 'tori_end2c']],
["tori_end2a","you","","don't you ever get tired?","","","","","",""],
["","tori","","well... it gets tough, sometimes, constantly running into dead ends.","","","","","",""],
["","","","but let me tell you a secret, {player}.","","","","","",""],
["","","","there's two types of people in the world -- winners, and quitters.","","","","","",""],
["","","","if you don't stay strong and meet life's challenges head on, then i'm afraid that makes you a quitter.","","","","","",""],
["","you","","but it's also important to step back from something when it gets too much for you!","","","","","",""],
["","","","...right?","","","","","",""],
["","tori","","heh, sounds like quitting to me.","","","","","",""],
["","you","","noooo, just taking a break!","","","","","",""],
["","","","i mean, taking time off to take care of yourself doesn't mean you're giving up","","","","","",""],
["","tori","","i [i]know[/i] that.","","","","","",""],
["","you","","right, right.","","","","","",""],
["","","","sorry, just... thought it might be relevant","","","","","",""],
["","tori","","...","","","","","",""],
["","","","well...","","","","","",""],
["","","","i suppose i have been a bit one-minded at times.","","","tori_end2d","","",""],
["tori_end2b","you","","don't you ever do things for fun?","","","","","",""],
["","tori","","i play chess with oliver for fun.","","","","","",""],
["","","","it keeps my brain sharp.","","","","","",""],
["","you","","well that's not for fun then!","","","","","",""],
["","","","that's, like, mental training or whatever","","","","","",""],
["","tori","","i just don't have time for fun and games!","","","","","",""],
["","","","finding a way out of here is the only thing that's really important. everything else can come after.","","","","","",""],
["","you","","yeahhh, but you have to step back sometimes to take care of yourself, too!","","","","","",""],
["","","","if you're gonna be down here for a while, you might as well have a good time","","","","","",""],
["","","","...right?","","","","","",""],
["","tori","","well, what can you do for \"fun\" in purrgatory anyway?","","","","","",""],
["","you","","i guess you could play horseshoe?","","","","","",""],
["","tori","","we have horeshoe in purrgatory?","","","","","",""],
["","you","","yeah, it's in the park!","","","","","",""],
["","","","you never noticed??","","","","","",""],
["","tori","","hm.","","","","","",""],
["","","","i guess not.","","","","","",""],
["","you","","or, or you could just invite people to hang out! ","","","","","",""],
["","","","you don't have to do anything specific","","","","","",""],
["","tori","","sure, maybe i'll invite the others to our wall-feeling party and we can all get to know each other better.","","","","","",""],
["","you","","good idea!","","","","","",""],
["","tori","","no, that was sarcasm, {player}","","","","","",""],
["","you","","oh","","","","","",""],
["","","","yeah, i guess this room would get cramped with all of us in it","","","tori_end2d","","",""],
["tori_end2c","you","","it sort of seems like a waste of time","tori_bad_choice1","","","","",""],
["","tori","","sorry?","","","","","",""],
["","you","","i mean, you're running around doing all this random stuff","","","","","",""],
["","","","but have you gotten any further than you were before?","","","","","",""],
["","tori","","well, i guess not.","","","","","",""],
["","","","but that just means i have to keep at it!","","","","","",""],
["","you","","[i]shrug[/i]","","","","","",""],
["","","","i guess if that's how you want to spend your afterlife...","","","","","",""],
["","tori","","...","","","tori_end2d","","",""],
["tori_end2d","tori","","listen, i don't think we're going to find any secret panels","","","","","",""],
["","you","","true, it was a long shot","","","","","",""],
["","tori","","any other ideas?","","","tori_end_main","","",""],
["tori_end3","you","","we could knock?","tori_end_tried_knocking","","","","",""],
["","tori","","sure, why not.","","","","","",""],
["","_none","","tori knocks on the door.","door_knock","","","","",""],
["","you","","...","","","","","",""],
["","tori","","...","","","","","",""],
["","you","","i guess they're not home","","","","","",""],
["","tori","","shame.","","","tori_end_main","","",""],
["tori_end4","you","","we could wait?","","","","","",""],
["","","","you know, maybe it only opens once every ten thousand years, or something?","","tori_end_tried_knocking and tori_end_tried_feeling and tori_end_tried_kicking",['tori_end4b', 'tori_end4a'],"","",""],
["tori_end4a","tori","","not that i'm against the idea of waiting for ten thousand years, but maybe we should try something else in the meanwhile?","","","","","",""],
["","you","","yeah, that makes sense...","","","tori_end_main","","",""],
["tori_end4b","tori","","hmmm...","","","","","",""],
["","","","just sitting around and waiting seems a bit counterintuitive to escaping, don't you think?","","","","","",""],
["","you","","i don't know, it's purrgatory","","","","","",""],
["","","","isn't waiting around kinda the theme?","","","","","",""],
["","tori","","...i guess it's worth a shot.","","","","","",""],
["","you","","exactly!","","","","","",""],
["","tori","","so, time to sit here and do nothing.","","","","","",""],
["","you","","yep","","","","","",""],
["","tori","","okay.","","","","","",""],
["","","","i'm starting now.","","","","","",""],
["","you","","okay!","","","","","",""],
["","_none","","...","","","","","",""],
["","","","....","","","","","",""],
["","","",".....","","","","","",""],
["","","","......","","tori_bad_choice1 and tori_bad_choice2",['tori_end4c', 'tori_end4c'],"","",""],
["tori_bad_end","tori","","um, i can take it from here.","","","","","",""],
["","","","i think i've wasted enough of your time.","","","","","",""],
["","you","","oh, are you sure?","","","","","",""],
["","tori","","it's not like both of us sitting here is going to make it open faster.","","","","","",""],
["","you","","alright then","","","","","",""],
["","","","take care","","","","","",""],
["","tori","","you too.","_delay_queue_tori_flashback","","null","","",""],
["tori_end4c","tori","","must have been an hour by now, right?","","","","","",""],
["","you","","um","","","","","",""],
["","","","felt more like 30 seconds to me","","","","","",""],
["","tori","","oh","","","","","",""],
["","_none","","...","","","","","",""],
["","","","....","","","","","",""],
["","","",".....","","","","","",""],
["","","","......","","","","","",""],
["","","",".......","","","","","",""],
["","","","........","","","","","",""],
["","","",".........","","","","","",""],
["","","","..........","","","","","",""],
["","tori","","you know, this isn't as bad as i thought.","","","","","",""],
["","","","it's sort of like meditating.","","","","","",""],
["","you","","yeah, we're just straight up chilling.","","","","","",""],
["","tori","","i've never noticed so many details on the walls before.","","","","","",""],
["","you","","me neither","","","","","",""],
["","_none","","...","","","","","",""],
["","","","....","","","","","",""],
["","","",".....","","","","","",""],
["","","","......","","","","","",""],
["","","",".......","","","","","",""],
["","","","........","","","","","",""],
["","","",".........","","","","","",""],
["","","","..........","","","","","",""],
["","","","...........","","","","","",""],
["","","","............","","","","","",""],
["","","",".............","","","","","",""],
["","","","..............","","","","","",""],
["","tori","","hey, {player}","","","","","",""],
["","you","","yeah?","","","","","",""],
["","tori","","i appreciate you sticking with me, even if my plans didn't amount to much.","","","","","",""],
["","","","most of the others can't be bothered to help.","","","","","",""],
["","","","either they're busy with their own projects or they'd rather sit on their asses doing nothing for eternity.","","","","","",""],
["","","","and... i know i can be prickly, at times.","","","","","",""],
["","","","so i appreciate it.","","","","","",""],
["","you","","aw, you're welcome!","","","","","",""],
["","","","i thought it was fun","","","","","",""],
["","","","when i wasn't almost dying, anyway","","","","","",""],
["","tori","","right.","","","","","",""],
["","_none","","...","","","","","",""],
["","","","....","","","","","",""],
["","","",".....","","","","","",""],
["","","","......","","","","","",""],
["","tori","","you can go, if you want.","","","","","",""],
["","","","i think i'll stay here for a while.","","","","","",""],
["","","","don't wanna miss the door if it opens.","","","","","",""],
["","you","","okay!","","","","","",""],
["","","","maybe i'll come back to check on you every now and then.","","","","","",""],
["","tori","","sounds good.","","","","","",""],
["","","","till next time, associate.","","","","","",""],
["","you","","till next time!","_delay_queue_tori_flashback","","null","","",""],
["tori_default","","","_pass","","queue_tori_flashback",['tori_serene', 'tori_default1'],"","",""],
["tori_serene","","","_pass","","tori_bad_choice1 and tori_bad_choice2",['tori_serene2', 'tori_serene1'],"","",""],
["tori_serene1","_none","","she looks serene.","","","null","","",""],
["tori_serene2","_none","","her expression is unreadable.","","","null","","",""],
["tori_default1","tori","tori_neutral","hi, {player}.","_hide_tori_exit2","","","","",""],
["","","","","","","",['true', '_inv_chess_letter', 'elijah_planning_slam and not invited_tori', 'true', 'true'],['what\'s up?', '(deliver oliver\'s letter)', '(invite tori to the everything slam)', 'how\'s the door?', 'how was life?'],['tori_wasup',  'tori_chess', 'tori_invitation', 'tori_door', 'tori_life']],
["tori_chess","you","","um, oliver had a letter for you",[['_quest_oliver_chess', false], ['_inv_chess_letter', false]],"","","","",""],
["","","","he said it's his next chess move or something.","","","","","",""],
["","tori","","oh? let's take a look.","","","","","",""],
["","","","...","","","","","",""],
["","","","heh, it's almost like he WANTS me to take his knight.","","","","","",""],
["","","","how's the boy doing, anyway?","","","","","",""],
["","you","","uhhh, not too great","","","","","",""],
["","","","he found a typo in one of his books and he's been researching it really hard","","","","","",""],
["","","","he thinks it's a code of some sort","","","","","",""],
["","tori","","yeah, that sounds like oliver.","","","","","",""],
["","","","maybe i should pay him a quick visit. care to come with?","","","","","",""],
["","you","","sure, if you want!","","","","","",""],
["","tori","","follow me.","","","tori_visiting_oliver","","",""],
["tori_wasup","you","tori_neutral","what's up?","","",['_rand', 'tori_wasup1', 'tori_wasup2', 'tori_wasup3', 'tori_wasup4', 'tori_wasup5', 'tori_wasup6', 'tori_wasup7', 'tori_wasup8', 'tori_wasup9', 'tori_wasup10', 'tori_wasup11', 'tori_wasup12', 'tori_wasup13', 'tori_wasup14', 'tori_wasup15', 'tori_wasup16', 'tori_wasup17', 'tori_wasup18', 'tori_wasup19', 'tori_wasup20'],"","",""],
["tori_wasup1","tori","","i don't know, the sky.","","","","","",""],
["","you","","is it?","","","","","",""],
["","tori","","no, i guess not","","","null","","",""],
["tori_wasup2","tori","","door","","","","","",""],
["","you","","yeah","","","null","","",""],
["tori_wasup3","tori","","you know, i always meant to learn asl before i died","","","","","",""],
["","you","","oh, to talk to deaf people?","","","","","",""],
["","tori","","yes, but also to communicate while scuba diving","","","null","","",""],
["tori_wasup4","tori","","what's 6 times 7?","","","","","",""],
["","you","","uh","","","","","",""],
["","","","uhhh","","","","","",""],
["","","","42?","","","","","",""],
["","tori","","good.","","","","","",""],
["","","","just a little test to keep you on your toes.","","","","","",""],
["","you","","??","","","null","","",""],
["tori_wasup5","tori","","as soon as we find a way out of here, we're going to be kicking ourselves for not thinking of it sooner.","","","","","",""],
["","you","","oh yeah","","","","","",""],
["","","","what if it's something like, you have to click your heels three times and say \"there's no place like heaven\"?","","","","","",""],
["","tori","","i've tried that.","","","","","",""],
["","you","","oh, really?","","","","","",""],
["","tori","","yes, with every number of heel clicks up to twelve.","","","","","",""],
["","you","","why'd you stop at twelve?","","","","","",""],
["","tori","","thirteen's unlucky. might've gone to hell.","","","null","","",""],
["tori_wasup6","tori","","did you know i took ballet until i was twelve?","","","","","",""],
["","you","","oh, that's cool!","","","","","",""],
["","","","why'd you stop?","","","","","",""],
["","tori","","my friend darius made fun of me, so i switched to karate so i could beat him up","","","","","",""],
["","you","","oh, cool","","","null","","",""],
["tori_wasup7","tori","","i wonder what my sensei would think of me now","","","","","",""],
["","you","","probably good things!","","","null","","",""],
["tori_wasup8","tori","","i'm starting to see why kyungsoon does what she does","","","","","",""],
["","","","sitting in one place doing nothing kinda grows on you after a while","","","","","",""],
["","you","","wow, really?","","","","","",""],
["","tori","","no. sarcasm.","","","null","","",""],
["tori_wasup9","tori","","i counted all the specks on the opposite wall","","","","","",""],
["","you","","oh, how many are there?","","","","","",""],
["","tori","","eight thousand, three hundred and forty two","","","","","",""],
["","you","","wow","","","null","","",""],
["tori_wasup10","tori","","hm?","","","","","",""],
["","","","sorry, dozed off for a second there","","","","","",""],
["","you","","oh, nothing","","","null","","",""],
["tori_wasup11","tori","","[i]gasp[/i]","","","","","",""],
["","","","i just had a breakthrough!","","","","","",""],
["","you","","oh?","","","","","",""],
["","tori","","wait no","","","","","",""],
["","","","false alarm","","","","","",""],
["","you","","oh ok","","","null","","",""],
["tori_wasup12","tori","","solved the collatz conjecture in my head while i was waiting","","","","","",""],
["","","","don't tell oliver","","","","","",""],
["","you","","i won't!","","","null","","",""],
["tori_wasup13","tori","","i thiiink i have checkmate in eighteen in my game against oliver","","","","","",""],
["","you","","in eighteen??","","","","","",""],
["","tori","","eighteen moves from now, yeah.","","","","","",""],
["","you","","is that a lot?","","","","","",""],
["","tori","","yes. that is a lot","","","null","","",""],
["tori_wasup14","tori","","did you know all froot loops are the same flavor?","","","","","",""],
["","you","","blasphemy","","","null","","",""],
["tori_wasup15","tori","","did you know iguanas have three eyes?","","","","","",""],
["","you","","really??","","","","","",""],
["","tori","","yep, two normal ones and one hidden one in the middle","","","","","",""],
["","","","i had one as a pet. his name was goliath","","","","","",""],
["","you","","wow","","","null","","",""],
["tori_wasup16","tori","","literally nothing","","","","","",""],
["","you","","same","","","null","","",""],
["tori_wasup17","tori","","do you think they have airpods in heaven?","","","","","",""],
["","you","","i hope not","","","","","",""],
["","tori","","i don't know. they're sort of convenient.","","","","","",""],
["","","","tacky, but convenient.","","","","","",""],
["","you","","maybe heaven earpods are more fashionable?","","","","","",""],
["","tori","","probably, yeah.","","","null","","",""],
["tori_wasup18","tori","","hold on","","","","","",""],
["","","","...","","","","","",""],
["","you","","wh--","","","","","",""],
["","tori","","sh!!","","","","","",""],
["","","","...","","","","","",""],
["","","","sorry, i thought i saw the door move","","","","","",""],
["","","","but it was just your shadow.","","","","","",""],
["","you","","oh, sorry","","","","","",""],
["","tori","","you're sorry for casting a shadow?","","","","","",""],
["","you","","...i guess??","","","null","","",""],
["tori_wasup19","tori","","i'm pretty sure i've never waited this long for anything in my life","","","","","",""],
["","you","","not very patient, huh?","","","","","",""],
["","tori","","i used to drive to a dmv in the middle of the mojave desert to avoid having to stand in line.","","","null","","",""],
["tori_wasup20","tori","","not much.","","","","","",""],
["","","","how about you? i feel like i never ask you what's up.","","","","","",""],
["","you","","oh, uh, not much!","","","","","",""],
["","","","i've just been walking around in circles","","","","","",""],
["","tori","","what for?","","","","","",""],
["","you","","i guess i've been running a lot of errands for people?","","","","","",""],
["","tori","","sounds like a great way to spend your afterlife.","","","","","",""],
["","you","","i mean... could be worse!","","","null","","",""],
["tori_door","you","","how's the door?","","","","","",""],
["","","","still waiting for it to open?","","","","","",""],
["","tori","","don't talk to me about the door.","","","","","",""],
["","","","me and the door are not on speaking terms anymore.","","","","","",""],
["","you","","i guess you don't a-[i]door[/i] it anymore, huh?","","","","","",""],
["","tori","","funny.","","","","","",""],
["","","","i have a system now. i look at the door for two hours, then i look away from the door for one hour, then i try the doorknob.","","","","","",""],
["","","","rinse and repeat.","","","","","",""],
["","","","see, i don't want to stare constantly in case it's one of those things where it only happens when you're not looking.","","","","","",""],
["","","","but i can't look away for too long in case i miss something, right?","","","","","",""],
["","","","that's why i alternate.","","","","","",""],
["","you","","sounds... logical?","","","","","",""],
["","tori","","thanks.","","","null","","",""],
["tori_life","you","","so, how was your life?","","","","","",""],
["","tori","","well, i would have liked it to be a little longer, but otherwise it was alright.","","","","","",""],
["","","","","","","","",['any highlights?', 'any regrets?', 'any last words?'],['tori_life9', 'tori_life8', 'tori_life7']],
["tori_life9","you","","any highlights?","","","","","",""],
["","tori","","hmmm","","","","","",""],
["","","","el capitan was pretty great","","","","","",""],
["","","","and that time i met carol chomsky","","","","","",""],
["","you","","who?","","","","","",""],
["","tori","","wife of noam chomsky.","","","","","",""],
["","","","most people don't know she was an accomplished linguist in her own right.","","","","","",""],
["","you","","o","","","","","",""],
["","tori","","i had a busy life, it's hard to choose just a few highlights.","","","","","",""],
["","","","how about you?","","","","","",""],
["","you","","hmmm","","","","","",""],
["","","","i don't know, i still don't remember much","","","","","",""],
["","","","maybe the first time i ate a burrito!","","","","","",""],
["","tori","","really?","","","","","",""],
["","you","","yeah!","","","","","",""],
["","","","it was really good!","","","","","",""],
["","tori","","out of every earthly experience your favorite was eating rice and beans wrapped in a tortilla?","","","","","",""],
["","you","","yeah but for the first time ever","","","","","",""],
["","","","don't you remember your first burrito?","","","","","",""],
["","tori","","no, of course not!","","","","","",""],
["","","","wait","","","","","",""],
["","","","actually, yes","","","","","",""],
["","","","it was probably that taco truck on paradise road","","","","","",""],
["","you","","wasn't it good??","","","","","",""],
["","tori","","it was okay, i guess.","","","","","",""],
["","","","i wouldn't call it life changing or anything.","","","","","",""],
["","you","","well, of course not. it's just a burrito.","","","","","",""],
["","tori","","[i]sigh[/i]","","","null","","",""],
["tori_life8","you","","any regrets?","","","","","",""],
["","tori","","hmm....","","","","","",""],
["","","","i have three.","","","","","",""],
["","","","one, i never got to start my own business","","","","","",""],
["","","","me and my friend ran a campus laundry business in college, but that doesn't count.","","","","","",""],
["","you","","i see, i see","","","","","",""],
["","tori","","two, walking under the tree that got struck by lightning and killed me","","","","","",""],
["","you","","oh yeah ","","","","","",""],
["","","","that's a big one","","","","","",""],
["","tori","","no kidding.","","","","","",""],
["","you","","what about the third one?","","","","","",""],
["","tori","","hm?","","","","","",""],
["","you","","you said you have three regrets?","","","","","",""],
["","tori","","oh, yes","","","","","",""],
["","","","the third one is","","","","","",""],
["","","","uh","","","","","",""],
["","you","","yeeees?","","","","","",""],
["","tori","","it's a little embarrassing.","","","","","",""],
["","you","","go ooooon","","","","","",""],
["","tori","","...","","","","","",""],
["","","","i've kissed my fair share of guys, but never a girl.","","","","","",""],
["","you","","awwwwwwwwwwwwwww","","_pronouns_she",['tori_life1', 'tori_life2'],"","",""],
["tori_life1","","","_pass","","","","",['do you... want to try it?', 'that\'s a shame'],['tori_life1a', 'tori_life2']],
["tori_life1a","you","","do you... wanna try it?","","","","","",""],
["","tori","","what, with you?","","","","","",""],
["","you","","why not?","","","","","",""],
["","tori","","uh, no thanks.","","","","","",""],
["","","","no offense.","","","","","",""],
["","","","that's just kind of a weird thing to do with someone you just met.","","","","","",""],
["","you","","ok, that's fair","","","null","","",""],
["tori_life2","you","","that's a shame ):","","","null","","",""],
["tori_life7","you","","any last words?","","","","","",""],
["","tori","","is that a threat or a question?","","","","","",""],
["","you","","um, idk ","","","","","",""],
["","","","i just thought it would be funny to say","","","","","",""],
["","tori","","hah.","","","","","",""],
["","","","come to think of it, i'm not sure what my last words were.","","","","","",""],
["","","","i died on the way back from the office, so it might have been something work related.","","","","","",""],
["","you","","like \"oh no, the stocks are down by five percent\"?","","","","","",""],
["","tori","","sure. something like that.","","","","","",""],
["","","","most likely just \"bye, see you tomorrow.\"","","","","","",""],
["","you","","aw, that's boring.","","","","","",""],
["","tori","","you're right, i should have ended all my conversations with wise snippets in case of an accident.","","","","","",""],
["","you","","exactly!","","","","","",""],
["","","","anyway, i've got to go","","","","","",""],
["","","","money is the root of all evil. albert einstein.","","","","","",""],
["","tori","","[i]sigh[/i]","","","null","","",""],
["tori_invitation","you","","by the way, me and elijah have been planning an everything slam","invited_tori","","","","",""],
["","tori","","an everything slam, huh?","","","","","",""],
["","you","","yeah, it's like a poetry slam but you can do anything you want!","","","","","",""],
["","","","do you wanna come?","","","","","",""],
["","tori","","well, i don't know. i'm pretty busy.","","","","","",""],
["","","","what would i present, anyway?","","","","","",""],
["","you","","uhhh","","","","","",""],
["","","","you do karate, right?","","","","","",""],
["","","","what about a martial arts demo?","","","","","",""],
["","tori","","hm....","","","","","",""],
["","","","now that you mention it, i've always wanted to do a karate demonstration.","","","","","",""],
["","you","","ooooh can i hold the pieces of wood as you break them?","","","","","",""],
["","tori","","heh","","","","","",""],
["","","","we might be able to arrange that","","","","","",""],
["","you","","let's do it then!!","","","","","",""],
["","tori","","alright, i'm sold!","","","","","",""],
["","","","when are we gathering?","","","","","",""],
["","you","","at the toll of the bell, or something!","","","","","",""],
["","tori","","sounds good.","","","","","",""],
["","","","hm, i may have to carve some time out of my schedule to de-rust...","","","","","",""],
["","","","dying will really do a number to your muscles","","","","","",""],
["","you","","oh yeah, i bet","","","null","","",""]
]