extends Node

var raw_blocks = [
["ttt_init","_none","_none","oliver pulls a pencil out of his pocket and draws a board.","oliver_goto_ttt","","","",""],
["","oliver","","i'll go first.","ttt_init_delay","","null","",""],
["ttt_now_you_go","oliver","_none","okay, now you draw an X anywhere on the board.","","","","",""],
["","you","","i know how to play tic-tac-toe!","","","","",""],
["","oliver","","right, right, sorry","ttt_continue_delay","","null","",""],
["ttt_hmm","oliver","_none","hmm...","ttt_continue_delay","","null","",""],
["ttt_stalemate1","oliver","_none","that's a tie","ttt_stalemate1","","","",""],
["","you","","yep","","","ttt_game2","",""],
["ttt_loss1","oliver","_none","i win!","ttt_loss1","","","",""],
["","you","","damn","","","ttt_game2","",""],
["ttt_bad1","oliver","_none","i wouldn't have done that, if i were you","ttt_bad1","","","",""],
["","you","","uh oh","ttt_continue_delay","","null","",""],
["ttt_very_bad1","oliver","_none","um, are you sure about that?","","","","",""],
["","you","","oh","ttt_continue_delay","","null","",""],
["ttt_about_to_lose1","you","_none","crap","","","","",""],
["","","","i see the problem now","ttt_continue_delay","","null","",""],
["ttt_game2","oliver","_none","up for another?","","","","",""],
["","you","","sure!","ttt_init_delay","","null","",""],
["ttt_stalemate2","_none","_none","_pass","","ttt_stalemate1",['ttt_stalemate2_again', 'ttt_stalemate2_better'],"",""],
["ttt_stalemate2_again","oliver","_none","stalemate, again.","ttt_stalemate2","","","",""],
["","you","","darn","","","","",""],
["","","","just watch, i'll get you this time!","","","","",""],
["","oliver","","don't be too hasty...","","","","",""],
["","you","","what do you mean?","","","","",""],
["","oliver","","nothing, nothing.","","","ttt_game3","",""],
["ttt_stalemate2_better","oliver","","stalemate this time.","ttt_stalemate2","","","",""],
["","you","","that's an improvement","","","","",""],
["","","","just watch, i'll get you this time!","","","","",""],
["","oliver","","don't be too hasty...","","","","",""],
["","you","","what do you mean?","","","","",""],
["","oliver","","nothing, nothing.","","","ttt_game3","",""],
["ttt_loss2","_none","_none","_pass","","ttt_loss1",['ttt_loss2_again', 'ttt_loss2_worse'],"",""],
["ttt_loss2_again","oliver","_none","that's another win.","ttt_loss2","","","",""],
["","you","","damn, you're really good at this","","","","",""],
["","oliver","","ah, it's only algorithmic...","","","","",""],
["","you","","what do you mean?","","","","",""],
["","oliver","","nothing, nothing.","","","ttt_game3","",""],
["ttt_loss2_worse","oliver","","that's a win!","ttt_loss2","","","",""],
["","you","","damn, you're really good at this","","","","",""],
["","oliver","","ah, it's only algorithmic...","","","","",""],
["","you","","what do you mean?","","","","",""],
["","oliver","","nothing, nothing.","","","ttt_game3","",""],
["ttt_bad2","_none","_none","_pass","","ttt_bad1",['ttt_bad2_again', 'ttt_bad2_new'],"",""],
["ttt_bad2_new","oliver","_none","i wouldn't have done that, if i were you","ttt_bad2","","","",""],
["","you","","uh oh","ttt_continue_delay","","null","",""],
["ttt_bad2_again","oliver","_none","bad move again","ttt_bad2","","","",""],
["","you","","really?!","ttt_continue_delay","","null","",""],
["ttt_very_bad2","oliver","_none","uh...","ttt_continue_delay","","null","",""],
["ttt_about_to_lose2","_none","_none","_pass","","ttt_bad1",['ttt_about_to_lose2_again', 'ttt_about_to_lose2_new'],"",""],
["ttt_about_to_lose2_again","you","_none","ugh, not again","ttt_continue_delay","","null","",""],
["ttt_about_to_lose2_new","you","_none","crap","","","","",""],
["","","","i see the problem now","ttt_continue_delay","","null","",""],
["ttt_game3","oliver","_none","let's do another.","ttt_init_delay","","null","",""],
["ttt_stalemate3","_none","_none","_pass","","ttt_loss1 and ttt_loss2",['ttt_stalemate3_finally', 'ttt_stalemate3_again'],"",""],
["ttt_stalemate3_finally","you","_none","hey, you finally didn't win!","ttt_stalemate3","","","",""],
["","oliver","","yes, but neither did you.","","","","",""],
["","you","","true.","","","","",""],
["","","","very fitting for purrgatory","","","","",""],
["","oliver","","indeed.","","","","",""],
["","you","","maybe the key to getting out of here is beating you at tic-tac-toe!","","","","",""],
["","oliver","","heh, i wouldn't hold your breath.","ttt_init_delay","","null","",""],
["ttt_stalemate3_again","oliver","","another tie.","ttt_stalemate3","","","",""],
["","you","","very fitting for purrgatory","","","","",""],
["","oliver","","indeed.","","","","",""],
["","you","","maybe the key to getting out of here is beating you at tic-tac-toe!","","","","",""],
["","oliver","","heh, i wouldn't hold your breath.","ttt_init_delay","","null","",""],
["ttt_loss3","_none","_none","_pass","","ttt_stalemate1 and ttt_stalemate2",['ttt_loss3_finally', 'ttt_loss3_again'],"",""],
["ttt_loss3_finally","you","_none","agh, i'm losing my touch.","ttt_loss3","","","",""],
["","oliver","","it's okay, maybe you'll get it next time!","","","","",""],
["","you","","sure, sure.","","","","",""],
["","","","start another one, i think i know what i did wrong","","","","",""],
["","oliver","","will do.","ttt_init_delay","","null","",""],
["ttt_loss3_again","oliver","","another win.","ttt_loss3","","","",""],
["","you","","agh, i missed that one up","","","","",""],
["","oliver","","it's okay, maybe you'll get it next time!","","","","",""],
["","you","","sure, sure.","","","","",""],
["","","","start another one, i think i know what i did wrong","","","","",""],
["","oliver","","will do.","ttt_init_delay","","null","",""],
["ttt_bad3","_none","_none","_pass","","ttt_bad1 or ttt_bad2",['ttt_bad3_again', 'ttt_bad3_new'],"",""],
["ttt_bad3_again","oliver","_none","...","ttt_bad3","","","",""],
["","you","","don't say anything","","","","",""],
["","","","i can tell from your face that that was a bad move","","","","",""],
["","oliver","","yeeeah...","ttt_continue_delay","","null","",""],
["ttt_very_bad3","oliver","_none","*cough*","ttt_continue_delay","","null","",""],
["ttt_bad3_new","oliver","_none","i wouldn't have done that, if i were you","ttt_bad3","","","",""],
["","you","","uh oh","ttt_continue_delay","","null","",""],
["ttt_about_to_lose3_new","you","_none","crap","","","","",""],
["","","","i see the problem now","ttt_continue_delay","","null","",""],
["ttt_about_to_lose3","_none","_none","_pass","","ttt_bad1 or ttt_bad2",['ttt_about_to_lose3_again', 'ttt_about_to_lose3_new'],"",""],
["ttt_about_to_lose3_again","you","_none","how does this keep happening?!","ttt_continue_delay","","null","",""],
["ttt_stalemate4","oliver","_none","tie.","","","","",""],
["","you","","i hope you're not growing [i]tie[/i]-rd of this","","","","",""],
["","oliver","","heh, not quite yet!","","","ttt_game5","",""],
["ttt_loss4","oliver","_none","win.","","","","",""],
["","you","","i'm going to be so excited [i]win[/i] i finally beat you","","","","",""],
["","oliver","","heh, i'm sure you will.","","","","",""],
["ttt_game5","you","","to be honest","","","","",""],
["","","","not sure what else to try here","","","","",""],
["","oliver","","one more?","","","","",""],
["","you","","sure","ttt_init_delay","","null","",""],
["ttt_bad4","_none","_none","_pass","","ttt_bad1 or ttt_bad2 or ttt_bad3",['ttt_bad4_again', 'ttt_bad4_new'],"",""],
["ttt_bad4_again","oliver","","...","ttt_continue_delay","","null","",""],
["ttt_bad4_new","oliver","_none","i wouldn't have done that, if i were you","ttt_bad4","","","",""],
["","you","","uh oh","ttt_continue_delay","","null","",""],
["ttt_very_bad4","oliver","_none","...","ttt_continue_delay","","null","",""],
["ttt_about_to_lose4_new","you","_none","crap","","","","",""],
["","","","i see the problem now","ttt_continue_delay","","null","",""],
["ttt_about_to_lose4_again","you","","sigh","ttt_continue_delay","","null","",""],
["ttt_about_to_lose4","_none","_none","_pass","","ttt_bad1 or ttt_bad2 or ttt_bad3",['ttt_about_to_lose4_again', 'ttt_about_to_lose4_new'],"",""],
["ttt_stalemate5","oliver","_none","stalemate.","","","ttt_post_game","",""],
["ttt_loss5","oliver","_none","that's a win!","","","ttt_post_game","",""],
["ttt_bad5","_none","_none","_pass","","ttt_bad1 or ttt_bad2 or ttt_bad3 or ttt_bad4",['ttt_bad5_again', 'ttt_bad5_new'],"",""],
["ttt_bad5_new","oliver","_none","i wouldn't have done that, if i were you","","","","",""],
["","you","","uh oh","ttt_continue_delay","","null","",""],
["ttt_bad5_again","oliver","","...","ttt_continue_delay","","null","",""],
["ttt_very_bad5","oliver","_none","...","ttt_continue_delay","","null","",""],
["ttt_about_to_lose5_new","you","_none","crap","","","","",""],
["","","","i see the problem now","ttt_continue_delay","","null","",""],
["ttt_about_to_lose5_again","you","",":/","ttt_continue_delay","","null","",""],
["ttt_about_to_lose5","_none","_none","_pass","","ttt_bad1 or ttt_bad2 or ttt_bad3 or ttt_bad4",['ttt_about_to_lose5_again', 'ttt_about_to_lose5_new'],"",""],
["ttt_post_game","you","","damn","","","","",""],
["","","","maybe my first move is wrong?","","","","",""],
["","","","i gotta be missing something","","","","",""],
["","oliver","","er...","","","","",""],
["","","","{player}?","","","","",""],
["","you","","yeah?","","","","",""],
["","oliver","","i have somewhat of a, uh, confession to make.","","","","",""],
["","","","you know that tic-tac-toe is a solved game, right?","","","","",""],
["","","","","","","","",[['yes', 'ttt_solved1'], ['what', 'ttt_solved2']]],
["ttt_solved1","you","","yeah, it's not that hard to find the best strategy","","","","",""],
["","oliver","","right.","","","ttt_solved3","",""],
["ttt_solved2","you","","uh, what does that mean?","","","","",""],
["","oliver","","it means the perfect strategy has been discovered.","","","","",""],
["","you","","ah, ok","","","","",""],
["ttt_solved3","oliver","","and... i happen to know that optimal strategy","","","","",""],
["","","","so if you go second, then...","","","","",""],
["","","","it's impossible to win","","","","",""],
["","you","","oh","","","","",""],
["","","","so THAT'S why you always went first!","","","","",""],
["","oliver","","yes, indeed.","","","","",""],
["","you","","then why would you even ask to play in the first place???","","","","",""],
["","oliver","","well...","","","","",""],
["","","","i guess...","","","","",""],
["","","","i just like the feeling of winning.","","","","",""],
["","you","","oh.","","","","",""],
["","","","who doesn't?","","oliver_chose_park",['ttt_backto_park', 'ttt_backto'],"",""],
["ttt_backto","_none","_none","_pass","","oliver_chose_meowseum",['ttt_backto_meowseum', 'ttt_backto_dropoff'],"",""],
["ttt_backto_park","oliver","oliver_neutral","...","ttt_goto_park","","oliver_after_ttt","",""],
["ttt_backto_meowseum","oliver","oliver_neutral","...","ttt_goto_meowseum","","oliver_after_ttt","",""],
["ttt_backto_dropoff","oliver","oliver_neutral","...","ttt_goto_dropoff","","oliver_after_ttt","",""]
]