extends Node

var raw_blocks = [
["ttt_init","_none","_none","oliver pulls a pencil out of his pocket and draws a board.","oliver_goto_ttt","","","","",""],
["","oliver","","i'll go first.","_delay_ttt_init","","null","","",""],
["ttt_now_you_go","oliver","_none","okay, now you draw an X anywhere on the board.","","","","","",""],
["","you","","i know how to play tic-tac-toe!","","","","","",""],
["","oliver","","right, right, sorry","_delay_ttt_continue","","null","","",""],
["ttt_hmm","oliver","_none","hmm...","_delay_ttt_continue","","null","","",""],
["ttt_stalemate1","oliver","_none","that's a tie","ttt_stalemate1","","","","",""],
["","you","","yep","","","ttt_game2","","",""],
["ttt_loss1","oliver","_none","i win!","ttt_loss1","","","","",""],
["","you","","damn","","","ttt_game2","","",""],
["ttt_bad1","oliver","_none","i wouldn't have done that, if i were you","ttt_bad1","","","","",""],
["","you","","uh oh","_delay_ttt_continue","","null","","",""],
["ttt_very_bad1","oliver","_none","um, are you sure about that?","","","","","",""],
["","you","","...oh","_delay_ttt_continue","","null","","",""],
["ttt_about_to_lose1","you","_none","crap","","","","","",""],
["","","","i see the problem now","_delay_ttt_continue","","null","","",""],
["ttt_game2","oliver","_none","up for another?","","","","","",""],
["","you","","sure!","_delay_ttt_init","","null","","",""],
["ttt_stalemate2","_none","_none","_pass","","ttt_stalemate1",['ttt_stalemate2_again', 'ttt_stalemate2_better'],"","",""],
["ttt_stalemate2_again","oliver","_none","stalemate, again.","ttt_stalemate2","","","","",""],
["","you","","darn","","","","","",""],
["","","","just watch, i'll get you this time!","","","","","",""],
["","oliver","","we'll see about that!","","","ttt_game3","","",""],
["ttt_stalemate2_better","oliver","","stalemate this time.","ttt_stalemate2","","","","",""],
["","you","","that's an improvement","","","","","",""],
["","","","just watch, i'll get you this time!","","","","","",""],
["","oliver","","we'll see about that!","","","ttt_game3","","",""],
["ttt_loss2","_none","_none","_pass","","ttt_loss1",['ttt_loss2_again', 'ttt_loss2_worse'],"","",""],
["ttt_loss2_again","oliver","_none","that's another win.","ttt_loss2","","","","",""],
["","you","","damn, you're really good at this!","","","","","",""],
["","oliver","","ah, it's only algorithmic...","","","ttt_game3","","",""],
["ttt_loss2_worse","oliver","","that's a win!","ttt_loss2","","","","",""],
["","you","","damn, you're really good at this","","","","","",""],
["","oliver","","ah, it's only algorithmic...","","","ttt_game3","","",""],
["ttt_bad2","_none","_none","_pass","","ttt_bad1",['ttt_bad2_again', 'ttt_bad2_new'],"","",""],
["ttt_bad2_new","oliver","_none","i wouldn't have done that, if i were you","ttt_bad2","","","","",""],
["","you","","uh oh","_delay_ttt_continue","","null","","",""],
["ttt_bad2_again","oliver","_none","bad move again","ttt_bad2","","","","",""],
["","you","","really?!","_delay_ttt_continue","","null","","",""],
["ttt_very_bad2","oliver","_none","uh...","_delay_ttt_continue","","null","","",""],
["ttt_about_to_lose2","_none","_none","_pass","","ttt_bad1",['ttt_about_to_lose2_again', 'ttt_about_to_lose2_new'],"","",""],
["ttt_about_to_lose2_again","you","_none","ugh, not again","_delay_ttt_continue","","null","","",""],
["ttt_about_to_lose2_new","you","_none","crap","","","","","",""],
["","","","i see the problem now","_delay_ttt_continue","","null","","",""],
["ttt_game3","oliver","_none","let's do another.","_delay_ttt_init","","null","","",""],
["ttt_stalemate3","_none","_none","_pass","","ttt_loss1 and ttt_loss2",['ttt_stalemate3_finally', 'ttt_stalemate3_again'],"","",""],
["ttt_stalemate3_finally","you","_none","hey, you finally didn't win!","ttt_stalemate3","","","","",""],
["","oliver","","yes, but neither did you.","","","","","",""],
["","you","","truuue","","","","","",""],
["","","","very fitting for purrgatory","","","","","",""],
["","oliver","","indeed.","","","","","",""],
["","you","","maybe the key to getting out of here is beating you at tic-tac-toe!","","","","","",""],
["","oliver","","heh, that would sure be something.","_delay_ttt_init","","null","","",""],
["ttt_stalemate3_again","oliver","","another tie.","ttt_stalemate3","","","","",""],
["","you","","very fitting for purrgatory","","","","","",""],
["","oliver","","indeed.","","","","","",""],
["","you","","maybe the key to getting out of here is beating you at tic-tac-toe!","","","","","",""],
["","oliver","","heh, that would sure be something.","_delay_ttt_init","","null","","",""],
["ttt_loss3","_none","_none","_pass","","ttt_stalemate1 and ttt_stalemate2",['ttt_loss3_finally', 'ttt_loss3_again'],"","",""],
["ttt_loss3_finally","you","_none","agh, i'm losing my touch.","ttt_loss3","","","","",""],
["","oliver","","it's okay, maybe you'll get it next time!","","","","","",""],
["","you","","sure, sure.","","","","","",""],
["","","","start another one, i think i know what i did wrong","","","","","",""],
["","oliver","","will do.","_delay_ttt_init","","null","","",""],
["ttt_loss3_again","oliver","","another win.","ttt_loss3","","","","",""],
["","you","","agh, i missed that one up","","","","","",""],
["","oliver","","it's okay, maybe you'll get it next time!","","","","","",""],
["","you","","sure, sure.","","","","","",""],
["","","","start another one, i think i know what i did wrong","","","","","",""],
["","oliver","","will do.","_delay_ttt_init","","null","","",""],
["ttt_bad3","_none","_none","_pass","","ttt_bad1 or ttt_bad2",['ttt_bad3_again', 'ttt_bad3_new'],"","",""],
["ttt_bad3_again","oliver","_none","...","ttt_bad3","","","","",""],
["","you","","don't say anything","","","","","",""],
["","","","i can tell from your face that that was a bad move","","","","","",""],
["","oliver","","yeeeah...","_delay_ttt_continue","","null","","",""],
["ttt_very_bad3","oliver","_none","[i]cough[/i]","_delay_ttt_continue","","null","","",""],
["ttt_bad3_new","oliver","_none","i wouldn't have done that, if i were you","ttt_bad3","","","","",""],
["","you","","uh oh","_delay_ttt_continue","","null","","",""],
["ttt_about_to_lose3_new","you","_none","crap","","","","","",""],
["","","","i see the problem now","_delay_ttt_continue","","null","","",""],
["ttt_about_to_lose3","_none","_none","_pass","","ttt_bad1 or ttt_bad2",['ttt_about_to_lose3_again', 'ttt_about_to_lose3_new'],"","",""],
["ttt_about_to_lose3_again","you","_none","how does this keep happening?!","_delay_ttt_continue","","null","","",""],
["ttt_stalemate4","oliver","_none","tie.","","","","","",""],
["","you","","i hope you're not growing [i]tie[/i]-rd of this","","","","","",""],
["","oliver","","heh, not quite yet!","","","ttt_game5","","",""],
["ttt_loss4","oliver","_none","win.","","","","","",""],
["","you","","i'm going to be so excited [i]win[/i] i finally beat you!","","","","","",""],
["","oliver","","heh, i'm sure you will.","","","","","",""],
["ttt_game5","you","","ughhhh","","","","","",""],
["","","","i suck at this game","","","","","",""],
["","oliver","","aw, well, that's not necessarily true.","","","","","",""],
["","","","one more?","","","","","",""],
["","you","","sure","_delay_ttt_init","","null","","",""],
["ttt_bad4","_none","_none","_pass","","ttt_bad1 or ttt_bad2 or ttt_bad3",['ttt_bad4_again', 'ttt_bad4_new'],"","",""],
["ttt_bad4_again","oliver","","...","_delay_ttt_continue","","null","","",""],
["ttt_bad4_new","oliver","_none","i wouldn't have done that, if i were you","ttt_bad4","","","","",""],
["","you","","uh oh","_delay_ttt_continue","","null","","",""],
["ttt_very_bad4","oliver","_none","...","_delay_ttt_continue","","null","","",""],
["ttt_about_to_lose4_new","you","_none","crap","","","","","",""],
["","","","i see the problem now","_delay_ttt_continue","","null","","",""],
["ttt_about_to_lose4_again","you","","sigh","_delay_ttt_continue","","null","","",""],
["ttt_about_to_lose4","_none","_none","_pass","","ttt_bad1 or ttt_bad2 or ttt_bad3",['ttt_about_to_lose4_again', 'ttt_about_to_lose4_new'],"","",""],
["ttt_stalemate5","oliver","_none","stalemate.","","","ttt_post_game","","",""],
["ttt_loss5","oliver","_none","that's a win!","","","ttt_post_game","","",""],
["ttt_bad5","_none","_none","_pass","","ttt_bad1 or ttt_bad2 or ttt_bad3 or ttt_bad4",['ttt_bad5_again', 'ttt_bad5_new'],"","",""],
["ttt_bad5_new","oliver","_none","i wouldn't have done that, if i were you","","","","","",""],
["","you","","uh oh","_delay_ttt_continue","","null","","",""],
["ttt_bad5_again","oliver","","...","_delay_ttt_continue","","null","","",""],
["ttt_very_bad5","oliver","_none","...","_delay_ttt_continue","","null","","",""],
["ttt_about_to_lose5_new","you","_none","crap","","","","","",""],
["","","","i see the problem now","_delay_ttt_continue","","null","","",""],
["ttt_about_to_lose5_again","you","",":/","_delay_ttt_continue","","null","","",""],
["ttt_about_to_lose5","_none","_none","_pass","","ttt_bad1 or ttt_bad2 or ttt_bad3 or ttt_bad4",['ttt_about_to_lose5_again', 'ttt_about_to_lose5_new'],"","",""],
["ttt_post_game","you","","damn!","","","","","",""],
["","","","i've gotta be doing something wrong...","","","","","",""],
["","","","hm... maybe if i had played here instead...?","","","","","",""],
["","oliver","","uh...","","","","","",""],
["","","","{player}?","","","","","",""],
["","you","","yeah?","","","","","",""],
["","oliver","","i have somewhat of a confession to make.","","","","","",""],
["","","","you know that tic-tac-toe is a solved game, right?","","","","","",""],
["","","","","","","","",['yes', 'what?'],['ttt_solved1', 'ttt_solved2']],
["ttt_solved1","you","","yeah, it's not that hard to find the perfect strategy","","","","","",""],
["","oliver","","right.","","","ttt_solved3","","",""],
["ttt_solved2","you","","uh, what do you mean?","","","","","",""],
["","oliver","","i mean the perfect strategy for this game is known.","","","","","",""],
["ttt_solved3","oliver","","and if you go second against a person who knows that perfect strategy...","","","","","",""],
["","","","then it's impossible to win","","","","","",""],
["","you","","ohhh","","","","","",""],
["","","","so THAT'S why you always went first!","","","","","",""],
["","oliver","","yes, indeed.","","","","","",""],
["","you","","maaan","","","","","",""],
["","","","why would you even play if you know you're going to win every time? ):<","","","","","",""],
["","oliver","","[i]sigh[/i]","","","","","",""],
["","","","i don't know.","","","","","",""],
["","you","","cus you're a doo doo head, that's why","","","","","",""],
["","oliver","","...","","","","","",""],
["","","","maybe it's because","","","","","",""],
["","","","i just wanted to feel successful again","","","","","",""],
["","you","","...oh","played_ttt","oliver_chose_park",['ttt_backto_park', 'ttt_backto'],"","",""],
["ttt_backto","_none","_none","_pass","","oliver_chose_meowseum",['ttt_backto_meowseum', 'ttt_backto_dropoff'],"","",""],
["ttt_backto_park","oliver","oliver_neutral","...",[['ttt_goto_park', true], ['oliver_queue_silence', true]],"","oliver_after_ttt","","",""],
["ttt_backto_meowseum","oliver","oliver_neutral","...",[['ttt_goto_meowseum', true], ['oliver_queue_silence', true]],"","oliver_after_ttt","","",""],
["ttt_backto_dropoff","oliver","oliver_neutral","...","ttt_goto_dropoff","","oliver_after_ttt","","",""]
]