extends Node

var raw_blocks = [
["talk_to_kyungsoon","_none","_none","_pass","","","met_kyungsoon",['kyungsoon_thought', 'kyungsoon_intro']],
["kyungsoon_intro","_none","kyungsoon_neutral","you approach the person sitting by the wall.","",[['met_kyungsoon', true]],"",""],
["","you","","hello","","","",""],
["","???","","hey","","","",""],
["","","","you're new","","","",""],
["","you","","yep","","","",""],
["","???","","…","","","",""],
["","you","","what's your name?","","","",""],
["","???","","kyungsoon.","","","",""],
["","","","",[['nice to meet you', 'kyungsoon_meet'], ['are you ok?', 'kyungsoon_ok']],"","",""],
["kyungsoon_meet","you","","nice to meet you, kyungsoon.","","","",""],
["","kyungsoon","","…","","","",""],
["","_none","","she seems to be lost in thought.","","","","null"],
["kyungsoon_ok","you","","are you, like, okay?","","","",""],
["","kyungsoon","","yeah","","","",""],
["","you","","okay","","","",""],
["","kyungsoon","","…","","","",""],
["","_none","","she seems to be lost in thought.","","","","null"],
["kyungsoon_thought","kyungsoon","","that's a cat","","","",""],
["","you","","sure is","","","",""],
["","kyungsoon","","…","","","",""],
["","_none","","seems like that's all she has to say on the matter.","","","","null"],
["talk_to_oliver","_none","_none","_pass","","","met_oliver",['oliver_choice', 'oliver_intro']],
["oliver_choice","","","_pass","","","book_state",['oliver_choice_2', 'oliver_go_on']],
["oliver_choice_2","","","_pass","","","oliver_questioned",['oliver_chat_choice', 'oliver_books']],
["oliver_intro","???","oliver_neutral","oh, hello! you must be new!","",[['met_oliver', true]],"",""],
["","","","allow me to introduce myself. my name is oliver.","","","",""],
["","","","i'm the librarian here.","","","",""],
["","you","","i'm $player.","","","",""],
["","","","",[['nice to meet you!', 'oliver_nice'], ['librarian?', 'oliver_librarian']],"","",""],
["oliver_nice","you","","nice to meet you!","","","",""],
["","oliver","","and you as well!","","","","oliver_librarian_end"],
["oliver_librarian","you","","purrgatory has a librarian?","","","",""],
["","oliver","","well, not officially. this library was already here when i showed up. but it was in such a state of disarray i had to do something about it!","","","",""],
["","","","what you see before you is the product of many hours of shelving and dusting.","","","",""],
["","_none","","he looks very proud about this.","","","",""],
["","","","",[['it\'s very clean!', 'oliver_clean'], ['don\'t you have anything better to do?', 'oliver_anything_better']],"","",""],
["oliver_clean","you","","it's very clean!","","","",""],
["","oliver","","well, thank you very much!","","","","oliver_librarian_end"],
["oliver_anything_better","you","","don't you have anything better to do?","","","",""],
["","oliver","","well… keeping the library tidy is important… right?","","","",""],
["","","","at least i'm doing [i]something[/i] instead of just sitting around, like certain people.","","","",""],
["oliver_librarian_end","oliver","","anyway, feel free to browse around! just let me know if you find something you'd like to check out.","","","",""],
["","you","","will do.","","","",""],
["","_none","","oliver steps back and watches you expectantly.","","","","null"],
["read_book","_none","_none","_pass","","","book_state_2",['book3', 'book_choice']],
["book_choice","","","you grab a book from the shelves.","","","book_state",['book2', 'book1']],
["book1","_none","book","it's just the word \"meow\" over and over.","",[['book_state', true]],"",""],
["","oliver","","oh, i forgot to mention, our collection is a bit… limited.","","","",""],
["","you","","i see.","","","",""],
["","_none","","maybe you should try a different book.","","","","null"],
["book2","_none","book","this book is exactly the same as the other one.","",[['book_state_2', true]],"","null"],
["book3","_none","book","you \"read\" one of the \"books.\"","","","","null"],
["oliver_go_on","oliver","oliver_neutral","don't be afraid to look around!","","","",""],
["","you","","okay!","","","","null"],
["oliver_books","you","oliver_neutral","…are all the books like this?","",[['oliver_questioned', true]],"",""],
["","oliver","","well, yes, i'm afraid so.","","","",""],
["","","","at least, as far as we know! i haven't been able to catalog the entire collection yet, so there could be some hidden gems in there!","","","",""],
["","","","",[['seems unlikely', 'oliver_doubt'], ['catalog?', 'oliver_catalog'], ['hehe. cat-alog.', 'oliver_pun']],"","",""],
["oliver_doubt","you","","seems unlikely. it looks like this place is designed to be as boring as possible.","","","",""],
["","oliver","","ah. perhaps…","","","",""],
["","","","that is an opinion shared by many in this place.","","","",""],
["","","","regardless, it doesn't hurt to be thorough.","","","","oliver_pattern"],
["oliver_pun","you","","hehe. cat-alog.","","","",""],
["","oliver","","heh, yes, i am [i]cat[/i]-aloging the library.","","","","oliver_catalog_2"],
["oliver_catalog","you","","you're making a catalog?","","","",""],
["oliver_catalog_2","oliver","","take a look! i hit 15,000 yesterday!","","","",""],
["","_none","catalog","oliver shows you the catalog.","","","",""],
["","oliver","","by my estimate, that's more than 2% of the books in the library. still a lot of work to be done!","","","",""],
["","you","","oh, wow","","","",""],
["oliver_pattern","","","if you don't mind me asking… what are you hoping to find?","","","",""],
["","oliver","","well, you see…","","","",""],
["","","","i like to imagine that there's a pattern.","","","",""],
["","","","some sort of rhyme or reason. a lexicon that explains what all the nonsense means, or at least where it came from","","","",""],
["","","","after all, even a code of one word is a code that can be broken!","","","",""],
["","","","a language just begging to be understood!","","","",""],
["","","","",[['i hope you figure it out', 'oliver_hope'], ['(skeptical silence)', 'oliver_skeptical']],"","",""],
["oliver_hope","you","","i hope you figure it out!","","","",""],
["","oliver","","thank you, thank you.","","","",""],
["","","","i'm glad you understand.","","","",""],
["","","","it might be a lot of work, but when i discover the method behind the madness, it'll all be worth it.","","","","oliver_pattern_end"],
["oliver_skeptical","_none","","you glance skeptically at the bookshelves","","","",""],
["","oliver","","haha. well. that's... what i hope, anyway.","","","",""],
["","","","sounds pretty silly when i say it out loud.","","","",""],
["","","","um. forget i said anything.","","","",""],
["oliver_pattern_end","oliver","","anyway, did you find anything you'd like to check out?","","","",""],
["","","","",[['this book', 'oliver_check_out'], ['you', 'oliver_flirt'], ['no thanks', 'oliver_no_thanks']],"","",""],
["oliver_no_thanks","you","","no thanks.","","","",""],
["","oliver","","ah, that's ok. but let me know if you find something you like, okay?","","","",""],
["","you","","alright","","","",""],
["","oliver","","and before i forget…","","","",""],
["","","","welcome to purrgatory ^^","","","","null"],
["oliver_flirt","you","","the only thing I'm checking out is you ;3","","","",""],
["","_none","","oliver looks taken aback.","","","",""],
["","oliver","","uh, sorry?","","","",""],
["","","","",[['you know what i mean', 'oliver_flirt_more'], ['never mind, sorry', 'oliver_never_mind']],"","",""],
["oliver_flirt_more","you","","you know what i mean ;3333","","","",""],
["","oliver","","ahem. i, uh, i'm not sure that i do.","","","",""],
["","","","",[["let's get freaky", 'oliver_oh_god'], ['never mind, sorry', 'oliver_never_mind']],"","",""],
["oliver_oh_god","you","","let's get freaky babyyyy","","","",""],
["","oliver","","i think i need to… attend to some business… elsewhere in the library.","","","",""],
["","_none","","oliver leaves.","",[['oliver_why', 'true']],"","null"],
["","","","","","","",""],
["oliver_never_mind","you","","never mind, sorry.","","","",""],
["","oliver","","ah, it's ok. but do let me know if you'd like to check something out. ","","","",""],
["","","","that is, if you -- if you'd like to check [i]a book[/i] out.","","","",""],
["","you","","right.","","","","null"],
["oliver_chat_choice","_none","_none","_pass","","","got_commons_key",['oliver_abc', 'oliver_chat_choice_2']],
["oliver_chat_choice_2","","","_pass","","","checked_out_book",['oliver_chat_2', 'oliver_chat_1']],
["oliver_chat_1","oliver","","hello again! looking to check out a book?","","","",""],
["","","","",[['nah, just browsing', 'oliver_browsing'], ['how do i unlock the door outside?', 'oliver_commons_door'], ['yes please', 'oliver_check_out']],"","",""],
["oliver_chat_2","oliver","","hello again! i hope you're enjoying your book!","","","",""],
["","","","",[['just saying hi', 'oliver_hi'], ['how do i unlock the door outside?', 'oliver_commons_door']],"","",""],
["oliver_browsing","you","","nah, just browsing.","","","",""],
["","oliver","","ah, alright. well, don't let me distract you.","","","",""],
["","","","i'll just be over here. cataloging.","","","","null"],
["oliver_check_out","you","","yes please, can i check out this one?","",[['checked_out_book', true]],"",""],
["","oliver","","oh, wonderful! let me just make a note in the catalog.","","","",""],
["","","","i didn't actually expect you to -- well -- never mind that.","","","",""],
["","","","let me see… where did i put my stamp?","","","",""],
["","","","uhhhhh, ok, forget the stamp, i'll just write it down for you","","","",""],
["","","","this book is due back on…","","","",""],
["","","","well, we don't really have dates down here, do we","","","",""],
["","","","and there's nothing i can do if you're late","","","",""],
["","","","uhhh sdlfjs","","","",""],
["","","","just try to bring it back eventually, okay?","","","",""],
["","you","","haha, okay","","","",""],
["","_none","","oliver writes \"Due date: Eternity\" on a slip of paper and tucks it into the book.","","","",""],
["","oliver","","sorry about all that! enjoy your book!!","","","",""],
["","you","","no problem.","","","","null"],
["oliver_hi","you","","just stopping by to say hi.","","","",""],
["","oliver","","well hello to you too!","","","","null"],
["oliver_abc","oliver","","you know, i've been thinking about sorting these alphabetically…","","","","null"],
["oliver_commons_door","oliver","","you mean the door in the commons? it's usually unlocked.","","","",""],
["","","","i think kyungsoon is holding onto the key.","","","",""],
["","you","","ok, thanks","","","","null"]
]